### ISSUE TITLE
No Destiny.HistoricalStats.DestinyLeaderboard definition

### ISSUE THREAD

**Issue by Anakros** [Bungie-net/api#1]
I'm trying to generate API client library using [go-swagger](https://github.com/go-swagger/go-swagger) from `openapi-2.json`, but unfortunately it fails due to non-existing `Destiny.HistoricalStats.DestinyLeaderboard` definition. Is that something you missed?

Although, please take a look at `openapi-2.json` validation logs from `swagger-codegen-cli` tool: https://gist.github.com/Anakros/22fca19844ce82a8082945f9579f3509

**Comment by vthornheart-bng** [comment]
Ah, yes, thank you for these!  I will comb through those and fix up our generator to output the missing entities as soon as I get the opportunity!

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by vpzed** [comment]
Also if you use the [online validator](http://online.swagger.io/validator/debug?url=https://raw.githubusercontent.com/Bungie-net/api/master/openapi-2.json) on the v2.0 spec it will provide additional items for review.

Most of the errors are three things:

1. The use of a schema element in a parameter which is not "in: body" (i.e. "in: path" or "in: query".  
 [Reference](https://github.com/OAI/OpenAPISpecification/blob/master/versions/2.0.md#parameterObject)

2. Missing description property in responses object. [Reference](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#responseObject)

3. A parameter type is missing; however, I think that some of this might be related to the unexpected schema elements mentioned in item 1, so I'd fix the first two items and rerun it to see if that helps.

I've attached a sorted version of the messages to this as it might be helpful.
[messages-sorted.txt](https://github.com/Bungie-net/api/files/1248020/messages-sorted.txt)

**Comment by vthornheart-bng** [comment]
Sweet, great info - deeply appreciated!  I will nip those in the bud!

**Comment by vthornheart-bng** [comment]
Sweet, found the issue in the code generator.  Next deployment of documentation/specs will have it.  Thanks for the report!
