### ISSUE TITLE
Request: Single Manifest Item Lookup

### ISSUE THREAD

**Issue by bladefist** [Bungie-net/api#10]
In the D1 api we could look up a single hash and get it's definition.

Url is: `https://www.bungie.net/d1/platform/Destiny/Manifest/{type}/{hash}/`  This was very useful, would love to it make a come back!  If it's not possible, I understand. thanks!

**Comment by vthornheart-bng** [comment]
Yeah, totally feasible and reasonable!  We talked offline about it, and just to frame the conversation for others who are interested in this - we both agreed that it should not and we would not want it to return related definitions like ?definitions=1 used to in D1 API.

**Comment by ckhicks** [comment]
Yeah those definitions made for some pretty large requests - glad to have the single hash option when needed, though.

**Comment by afehners** [comment]
I'd like to add my vote also. 
Nice new API compared to D1, but having no API to call to get basic item information, such as it's name, and instead having to maintain a local SQLIte database and make sure it's up to date is a shame.

**Comment by glass-ships** [comment]
Forgive me if this closed issue isn't the best place to ask this, but.. 

What's the recommended way to _get_ hash values and their associated common name or item? 

Having to use the hash to make API requests is fine, but the amount of digging around and googling in order to find what hash to use where is... definitely a process.

**Comment by hellocontrol-bng** [comment]
@glass-ships it depends on what exactly you're looking to do. Are you trying to figure out which hash to use to look up a particular, specific thing, but you're having trouble figuring out that thing's hash ahead of time? If so, you can fetch all of the definitions at once, or all of the ones for a particular type, using the `jsonWorldContentPaths` property of the manifest. Then you can search those files to find whatever hash you want.

If I've misunderstood your goal, let me know!

**Comment by glass-ships** [comment]
I think that's exactly what I'm looking for! 

So far, my methodology has been to fetch the json, create a "hashes" dictionary, and fetch the 'name' and 'hash' of each item in each category, as below. I've put the code into a [pastebin](https://pastebin.com/6Vpjuf8c) for reference. 

This works well for a lot of the tables, but some like DestinyActivityDefinitions have entries with different formats, like missing a description or a name value. 

Is this the best approach to take for pre-fetching definitions? 

My thought is that it may be handy to be able to quickly/easily reference a local dict object than to explore through the full Manifest/API every time I find a new call I'd like to make. 
```

**Comment by hellocontrol-bng** [comment]
@glass-ships The way we do it on B.net is to create a dictionary where the keys are the definition types, and the values are dictionaries of hashes to definitions (`Dictionary<DefinitionType, Dictionary<string, Definition>>`)

**Comment by glass-ships** [comment]
Thanks @hellocontrol-bng for the tip! 

I'm not sure I fully understand, can you elaborate a little on that? 

(sorry again for the pings on a closed issue)

**Comment by hellocontrol-bng** [comment]
Our structure looks like this:

```
{
    DestinyInventoryItemDefinition: {
        "135664246531": {
            display properties: { 
                ...
            }
            // Definition here
        }
    }
}
```

Basically if you know the type of the definition and the hash, it's easy to look up the definition with this structure:

```
const definitionType = "DestinyInventoryItemDefinition";
const hash = "135664246531";
const definition = definitions[definitionType][hash];
```
