### ISSUE TITLE
No medal data beyond allMedalsEarned, allMedalsScore, and medalsUnknown returned

### ISSUE THREAD

**Issue by adherrling** [Bungie-net/api#100]
As the issue states, the only data on medals returned by the /.../Account/{destinyMembershipId}/Stats/?groups=3 endpoint is allMedalsEarned, allMedalsScore, and medalsUnknown. This is true when querying an account or an individual character.

**Comment by vthornheart-bng** [comment]
Hmm, I will have to look into this - is this a recent change as of the latest deployment, or were you not getting them before today (9/13) as well?

**Comment by adherrling** [comment]
Unfortunately, today is the first time I've tried to pull medals data, so I am not sure.

**Comment by vthornheart-bng** [comment]
Anyone else had an experience with it before today?  Feel free to bring your info forward!  Either way, I'll be looking into this.

**Comment by vpzed** [comment]
I tried but was unable to get Medals data before today, and the returns were like this:

                "medalsUnknown": {
                    "statId": "medalsUnknown",
                    "basic": {
                        "value": 0,
                        "displayValue": "0"
                    },
                    "pga": {
                        "value": 0,
                        "displayValue": "0.0"
                    }
                },
                "allMedalsScore": {
                    "statId": "allMedalsScore",
                    "basic": {
                        "value": 0,
                        "displayValue": "0"
                    }
                },
                "allMedalsEarned": {
                    "statId": "allMedalsEarned",
                    "basic": {
                        "value": 0,
                        "displayValue": "0"
                    },
                    "pga": {
                        "value": 0,
                        "displayValue": "0.0"
                    }

**Comment by Tetron-bng** [comment]
Are you still seeing this issue?  I was unable to repro, but I did discover the "allMedalsEarned" is always returning 0 (fixed in next release).  I removed "allMedalsScore" too since medals score is not really a thing anymore.

**Comment by Tetron-bng** [comment]
This should be working now. Let me know if it is not.
