### ISSUE TITLE
OAuth Error Help [iOS Swift]

### ISSUE THREAD

**Issue by jonesandcode** [Bungie-net/api#1000]
I am using a cocoa pod called OAuthSwift to handle my OAuth login and I am running into a problem.

I am logged in on the site. However, it doesn't use my redirect URI and displays an error on the site saying "Authorization query string parameters are not valid". 

I did see in the documentation you are **not** supposed to pass the scope parameter to the server. The cocoa pod API requires this property, and I just have it set to an empty string. Could that be causing my issue?

![Simulator Screen Shot - iPhone Xʀ - 2019-08-05 at 14 08 39](https://user-images.githubusercontent.com/36642060/62486681-edd5e300-b78d-11e9-9f7a-03f92c841999.png)

**I just started writing the app and have the login code in `viewDidLoad` just to get up and running.**

`    override func viewDidLoad() {
        super.viewDidLoad()

        var oauthswift = OAuth2Swift(consumerKey: "****",
                                     consumerSecret: "***",
                                     authorizeUrl: "https://www.bungie.net/en/oauth/authorize",
                                     accessTokenUrl: "https://www.bungie.net/platform/app/oauth/token/",
                                     responseType: "code")

        oauthswift.allowMissingStateCheck = true

        oauthswift.authorize(withCallbackURL: "com.jonesandcode.TransmatApp:/authenticate",
                             scope: "", state: "") { (result) in
                                switch result {
                                case .success(let (credential, response, _)):
                                    print(credential.oauthToken)
                                case .failure(let error):
                                    print(error.localizedDescription)
                                }
        }

        oauthswift.authorizeURLHandler = SafariURLHandler(viewController: self, oauthSwift: oauthswift)
    }
}`

**Comment by vthornheart-bng** [comment]
Oof, that is possible.  Are you able to intercept what URL it is hitting specifically (say, with an MITM app like Fiddler?)  That could indicate whether scope is ending up in the URL of the request and being rejected as a result.

**Comment by jonesandcode** [comment]
I tried intercepting it using Charles proxy but it seems to stop recording once it pops over to Safari, I'm going to try a few more tricks though 🤞

**Comment by jonesandcode** [comment]
@vthornheart-bng thanks for adding the question label. 

Looks like it probably has to do with my redirect URI. I was able to find my request and I get a response code of 302, and my request URL looks good. It's not passing the scope parameter. 

So it sounds like something in my project set up, _thank god._ 

Thanks for the help!

**Comment by vthornheart-bng** [comment]
Cool, no problem!  Glad you found the likely suspect!

**Comment by floatingatoll** [comment]
If you got a 302 from a Bungie.net, that often means you’re missing a trailing slash on some URL somewhere. They all have trailing slashes. So if it’s a GET ... 302 Location: .../ that’s going to break it since the redirects won’t work right.

**Comment by jonesandcode** [comment]
Good to know! Thanks @floatingatoll
