### ISSUE TITLE
RFC: Cross Save, changes to Platform name/gamertag search

### ISSUE THREAD

**Issue by vthornheart-bng** [Bungie-net/api#1003]
I'll be adding this to the Cross Save FAQ shortly, but I wanted to make this a separate RFC to raise attention to this late-breaking change to Cross Save plans.

Currently, if you are performing gamertag search with SearchDestinyPlayer, by default we return the Membership ID and Destiny Profile that were originally associated with that gamertag, and not the active Destiny Profile that can play with that gamertag's account.  You may have noticed this if you search for some of these test users who have already been cross saved.  This allowed user search to continue returning historical accounts, but would make for extra work for apps that want to show current rather than historical information.

We are making plans at the moment to return the currently active Cross Save Membership ID/Destiny Profile instead if you have cross save enabled.

This will simplify the workflow for those of you (including us) who only want to see the currently active Destiny account for a gamertag/platform name.

For those of you who want to do gamertag/platform name searches for the historical/inactive accounts, we will add an option to the search for your use case.  A new "returnOriginalProfile" querystring parameter will be added.  If that's set to true, you will get the original destiny profile - if any - for that gamertag/platform name.

**Comment by justrealmilk** [comment]
100% sugar

**Comment by chronow** [comment]
Please tell me, how to get a player profile by specifying a nickname Buttle.net(as ex. #user1234) ???

**Comment by justrealmilk** [comment]
@chronow you should join the Discord @ https://discord.gg/E5uB4BW and we can help you out
