### ISSUE TITLE
08 Aug TWAB not in API?

### ISSUE THREAD

**Issue by soren42** [Bungie-net/api#1004]
When pulling from GetTrendingCatagories, neither the "Latest" nor the "News" branches contain the latest This Week at Bungie entry, at least as of 10 Aug 2019.

**Comment by justrealmilk** [comment]
Strange that it’s not but don’t forget that it’s an unsupported endpoint.

**Comment by soren42** [comment]
Is there a list of what's supported and what's unsupported that's **maintained** somewhere?  Because https://destinydevs.github.io/BungieNetPlatform/docs/services/Trending/Trending-GetTrendingCategories still shows it as "Officially Supported"… and I can't seem to find anything elsewhere.

**Comment by justrealmilk** [comment]
That's not official documentation 😛

**Comment by soren42** [comment]
No, of course, but the "official" documentation doesn't seem to list what's supported and what isn't… unless I'm missing something.  Several branches and/or endpoints have a "Preview" label beside them, but GetTrendingCatagories isn't one of those.  That community documentation was the only source I could find that listed anything as supported or unsupported.

**Comment by BlazeBoss17** [comment]
It's not on the RSS feed either. Deej published this week's (normally dmg/cozmo do it) so he probably forgot a step.

**Comment by vthornheart-bng** [comment]
Oh yeah, should be good now!  Sorry about the time lag on this, was fixed a while ago after someone (possibly you?  I can't recall now who hit me up!) on Reddit mentioned the same thing, but I missed the notification about the github issue being created.
