### ISSUE TITLE
MIDA Multi-tool objectives still classified

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1006]
Questline item: 2081553940
https://data.destinysets.com/i/InventoryItem:2081553940

Objectives are all classified.

Pls declassify 🥳

**Comment by delphiactual** [comment]
https://github.com/Bungie-net/api/issues/566

**Comment by vthornheart-bng** [comment]
Ah, junk.  Sorry folks, I've been meaning to take a look - the redactions are in the game designer's hands now, so I don't do direct redaction anymore.  I'm guessing this was redacted with too aggressive of an end date/no end date.  I'll go take a look!

**Comment by vthornheart-bng** [comment]
Huh, and I thought we'd unredacted it back in January, so that's... interesting.  Maybe something else is going on there.  I'm going to have to go digging.

**Comment by vthornheart-bng** [comment]
Ahhh, there it is, found it!  Yeah, someone got a little trigger happy there.  Apparently in #566 we unredacted the item, but not the objectives.  Fixed for next go-round now!
