### ISSUE TITLE
Can't download Manifest files using links from "Destiny2.GetDestinyManifest" endpoint

### ISSUE THREAD

**Issue by squalx** [Bungie-net/api#1008]
I'm sure I'm doing something wrong, but I haven't been working with Bungie's API for a while and now I came back and can't retrieve the manifest. I fetch the manifest URLs and then I compose the link like this:
https://www.bungie.net/Platform/Destiny2/Manifest/common/destiny2_content/sqlite/en/world_sql_content_6a74c8e2272ec3f899cba933f5bcc04c.content

When I hit that on the browser I get a 404. I used to be able to do it. I've tried with Postman using the API key and it still gives me a 404.

I am signed into Bungie.net on the browser when I do this, in case it matters.

Thanks in advance.

**Comment by dad2cl3** [comment]
Try taking out Platform/Destiny2/Manifest/

**Comment by squalx** [comment]
Perfect. Thanks!
