### ISSUE TITLE
MembershipType in GetActivityHistory's result

### ISSUE THREAD

**Issue by JimboJacksonBroDudeMan** [Bungie-net/api#1010]
for xbox players it's a 1.  for ps4 players it's a 2.  For PC players it's a 0.  Shouldn't it be a 4?  

http://destinydevs.github.io/BungieNetPlatform/docs/API-Test#/Destiny2/GetActivityHistory/p:membershipType=4,destinyMembershipId=4611686018471126197,characterId=2305843009326285729/q:mode=0,count=100

**Comment by delphiactual** [comment]
from the footer

```
BungieNetPlatform maintained by DestinyDevs.
This is a community run wiki and is not offically supported by Bungie.
```

**Comment by vthornheart-bng** [comment]
Hmm, I believe this is a symptom of the ongoing problems we're having getting a consistent membershipType mentioned here:

https://github.com/Bungie-net/api/issues/978

I have no ETA on the fix unfortunately: we're in limbo at the moment on whether or when this bug will be fixed.
