### ISSUE TITLE
Cross save game version?

### ISSUE THREAD

**Issue by BoofLord** [Bungie-net/api#1011]
Assuming someone has cross saves enabled and their primary account is PS4 based, how do you find what game version they have on xbox?  Can you?

**Comment by BoofLord** [comment]
it seems like it changes to your last logged in platforms game version...

**Comment by vthornheart-bng** [comment]
Yes, unfortunately this is an issue for which we do not have a solid solution for users at this time.  We go into it a bit here:

https://github.com/Bungie-net/api/wiki/FAQ:-Cross-Save-pre-launch-testing,-and-how-it-may-affect-you

An alternative to checking this data is hopefully going to come alongside the Shadowkeep release, but we won't be able to talk about that a bit more closer to when Shadowkeep goes live unfortunately.
