### ISSUE TITLE
Specific game modes not pulling data that group game modes do

### ISSUE THREAD

**Issue by cjhoffmn** [Bungie-net/api#1015]
I've been building a game data analysis tool to look at historical games.  
(Step1) it pulls a list of games of a player then 
(Step2) pulls a PGCR for each game in the list.  It also displays the pulled "game mode" of each game pulled and analyzed.

Gamemode:48 (rumble) works just fine - as do many others.  But if I pull gamemode:57 (privatematchesrumble) it returns no games.  However, if I pull down gamemode 32(privatematchesall) I get a list of privates, including the game mode 57 rumble matches I'm after.  (This appears to be the case in other "individual game modes" that will show up in the group game modes as well - I just know the numbers for the rumble stuff).

Is there some other way to look at the gamemodes that gives me a different view to pull things differently?  Or are some of them not able to search for some reason?

The get request looks like this:
("GET", "https://www.bungie.net/platform/Destiny2/{{Plform}}/Account/{{Account}}/Character/{{Character}}/Stats/Activities/?page=0&count=250&mode=57")

(If I change the mode=57 to mode=32 I'll get all privates as a list  and the 57s will be in there.  If I pull it with the 57 - it returns an empty response.)

**Comment by vthornheart-bng** [comment]
My apologies for the long delay!  I missed the notification about this issue being created, and I'm now trying to catch up and file bugs while I have a few minutes.

Filing a bug to investigate this.
