### ISSUE TITLE
World content file size

### ISSUE THREAD

**Issue by rraziel** [Bungie-net/api#1016]
This is not exactly about the API but I figured this was a good place to ask anyway.

My application downloads the JSON world content file - although I assume my issue happens with any file anyway, including the sqlite ones - and this can take quite a while, obviously.

I am displaying progress in the application so that the users know something is still happening, but it would be really nice to be able to show some kind of progress bar or a percentage.

For that I need to know the file size, but I can't seem to be able to get it ahead of download. I tried a `HEAD` request but the response does not include a `content-length` header.

Is there any way the servers hosting those files - I assume these come from Cloudflare's CDN - could add the `content-length` header, at least for those large files (probably doesn't matter for images and other regular-size assets)?

**Comment by floatingatoll** [comment]
What is an example full URL that you’re performing a HEAD request against that is not returning a valid Content-Length?

**Comment by rraziel** [comment]
Right now I use: https://www.bungie.net/common/destiny2_content/json/en/aggregate-2897f1bd-269c-4b6e-a1bf-61a8577b687b.json
I don't see any `content-length` header (and it doesn't look like the response is chunked either, which could have explained its absence).

**Comment by cjhoffmn** [comment]
I tried to hit that yesterday quite a few times - and it never completed - I assume because of the file size.  I'd love to hear more about this too...

**Comment by justrealmilk** [comment]
Usually, this is because when web servers encode to GZIP, they do so in chunks so they don’t know the total length until it’s sent the lot which is obviously too late

**Comment by as-com** [comment]
The JSON file is 80 MB, but it gzips very nicely to ~5 MB of transfer. You might want to use that as a rule of thumb to estimate the progress bar percentage, since 5 MB isn’t much for a broadband connection and progress bars are never exact anyways.

**Comment by rraziel** [comment]
Yes right now I simply hard-coded a rough estimate: worst case it'll stick an extra second to 100% or jump from 80-ish to 100%.
On my own computer it takes less than a second to download, I can really only see it when I simulate low bandwidth.
Anyway, seems alright to me, was just wondering if there was some way to get that size.
If somebody else feels like there is more to add, I guess they can reopen the issue.
Thanks for the information.

**Comment by floatingatoll** [comment]
I’d love to reopen it, but I cannot :(
