### ISSUE TITLE
API Usage metrics?

### ISSUE THREAD

**Issue by soren42** [Bungie-net/api#1019]
Are there any per-API key usage metrics out there that are accessible to end users?  I assume Bungie is tracking that stuff to ensure abuse doesn't occur, but is any of it public?

**Comment by floatingatoll** [comment]
Note that, as an API key holder, I would really appreciate _not_ having my key's statistics shared with _others_. If Bungie grants me access to my own statistics, that’s fine, but the last thing we need is “which is better” leaderboards for third-party clients.

**Comment by Tetron-bng** [comment]
Check out /App/ApiUsage/{applicationId}/.  This will let you view usage for all platform API calls for apps owned by the authenticated user.  

Note:  The applicationId is not the API key, but rather the integer that identifies your app (you can see it on the URL when looking at your app in the portal.

**Comment by soren42** [comment]
Thank you, @Tetron-bng!  I assume you mean the integer string at the end of the URL: https://www.bungie.net/en/Application/Detail/ **####**.  (Especially as seeing that's the only AppId I can even get authorisation to view…)  However, when I poll that endpoint, I get:
```json
{
"range": {
"start": "2019-08-29T19:15:00Z",
"end": "2019-08-30T19:15:00Z"
},
"apiCalls": [ ],
"throttledRequests": [ ]
}
```
Shouldn't there be data here?

**Comment by vthornheart-bng** [comment]
Ah, I'm actually glad this came up!  This is a recently introduced bug in the API: we've stopped successfully returning apiCalls and throttledRequests.  I'll file a bug shortly.

**Comment by vthornheart-bng** [comment]
TFS 826232

**Comment by Tetron-bng** [comment]
Hopefully just a configuration issue?

**Comment by vthornheart-bng** [comment]
Yes, some things got rearranged internally in terms of where this data is stored, and it looks like the external endpoint was missed in the change!
