### ISSUE TITLE
/GroupV2/{groupId}/Members/ currentPage should be a query parameter

### ISSUE THREAD

**Issue by oupablo** [Bungie-net/api#102]
Currently in 

"/GroupV2/{groupId}/Members/" in the swagger 2 definition

currentPage is listed as a path parameter when it should be set as a query parameter

**Comment by vthornheart-bng** [comment]
Aye, same problem that user search had before.  I'll look into it!

**Comment by nine13tech** [comment]
To add more detail here...  
In the Python output (I assume other languages suffer the same issue) of the GroupV2 Get Members endpoint it is failing to create the URL:  
the URL as made by the current Bungie output (called resource_path):  
`/GroupV2/{groupId}/Members/` with the path_params: `{'currentPage': 1, 'groupId': 910604}`  
the output code for this constructor is: `resource_path = '/GroupV2/{groupId}/Members/'.replace('{format}', 'json')`  

the URL constructed when working should look like this:
`/GroupV2/910604/Members/?currentPage=1`  
the corrected code:
`resource_path = '/GroupV2/'+str(group_id)+'/Members/?currentPage='+str(currentpage)`
but that is a hack and slash way of getting this to work.

**Comment by vthornheart-bng** [comment]
I'll retire this one in favor of 124, which is more comprehensive.
