### ISSUE TITLE
World content issue for Exodus Down plate

### ISSUE THREAD

**Issue by rraziel** [Bungie-net/api#1021]
Just rather minor bug: the Exodus Down "plate" (I assume) has the wrong name for both the old set and the menagerie one, as it's just called "Exodus Down".
Old set: https://data.destinysets.com/i/InventoryItem:177493699
New set: https://data.destinysets.com/i/InventoryItem:1156448694

**Comment by vthornheart-bng** [comment]
Ah, I'll let folks know about that!

**Comment by vthornheart-bng** [comment]
Oh, actually looking at the latest version it looks like they fixed it.  Sweet!
