### ISSUE TITLE
Potential world content issue for emblem background colors

### ISSUE THREAD

**Issue by rraziel** [Bungie-net/api#1022]
It looks like (when comparing my app to the actual game screen) that a lot of emblems have an incorrect - or sometimes slightly off - backgroundColor in their item definition.
It's a bit tricky giving a full list with the actual colors, so first I was wondering if anyone else noticed the same thing?

**Comment by soren42** [comment]
So, having just recently gone through this exercise in my own code, I would first refer you to the best guide out there on building clan banners at [https://github.com/xlxCLUxlx/Destiny2API/wiki/Building-Your-Clan-Banner:--How-To](https://github.com/xlxCLUxlx/Destiny2API/wiki/Building-Your-Clan-Banner:--How-To).  That said, I did have similar issues when building my tool in PHP — issues which I was introducing by not using the proper True Colour functions.  Once the correct functions were used, my banner images match Bungie's perfectly.  I've see the same thing in the tool associated with the Guide I linked above, as well as with [Tom's _(Experimental)_ Clan Banner Builder](https://braytech.org/experiments/clan-banner-builder/); clearly it's possible to exactly match Bungie's colour display.  Perhaps look at the image manipulation functions in the language you're using to see if there are any colour caveats.

**Comment by rraziel** [comment]
I pretty much just pick the red/green/blue/alpha and turn it into a css rgba(), but I'll take a look at those sites.

**Comment by rraziel** [comment]
So yeah, there is nothing special about color conversion: I just checked the "Try the Special" emblem and in-game it's a red background while the definition has r:5, g:5, b:4 which is basically black, cf https://data.destinysets.com/i/InventoryItem:1409726988

**Comment by soren42** [comment]
Oh, I'm sorry — you said "emblem background colours" and I read "banner background colours" — my mistake.  However, as I said, I did struggle with getting the rgba colours to look correct there.  That said, I don't have firsthand experience with the images from elsewhere in the API, but I imagine there's similar issues.

**Comment by justrealmilk** [comment]
I’ve always suspected that the game uses a performance efficient library to check the most prominent colour at runtime. As for the colour values we see in emblem definitions, my understanding is that these are input manually by the artists and as they’re not used in game they may not bother much

**Comment by rraziel** [comment]
Not sure about that, those background colors are generally displayed before the emblem is actually loaded.
Also, I've seen at least one - iirc the [Iron Banner gold medal](https://data.destinysets.com/i/InventoryItem:1162929425) one - that is a completely different color and really pops out. And in this instance it looks like it has the right definition, or looks quite close anyway.
