### ISSUE TITLE
Pending clan member endpoint does not honour authorisation

### ISSUE THREAD

**Issue by soren42** [Bungie-net/api#1023]
The `/GroupV2/{$id}/Members/Pending/` endpoint correctly requires authentication, however, once a user is authenticated, they can see _**any**_ clan's pending members — regardless of whether they're authorised to do so.  (I assume that since this is not the way BungieNet works, that this is not the intended behaviour.)

**Comment by justrealmilk** [comment]
Can be reproduced here http://braytech.org/clan/admin

**Comment by vthornheart-bng** [comment]
Ah, thank you for the heads up!  I appreciate it!
