### ISSUE TITLE
Retrieving all vendor item perks

### ISSUE THREAD

**Issue by rraziel** [Bungie-net/api#1024]
More a question than an issue, and let's take Xur as an example because, well, it's the week-end (+ his will is not his own).

If I get a character's vendor info, I can see which items are available for sale, their cost and such. This includes their perks, as in the perks displayed in-game when you hover over the item.

For example, this week's Aeon Safe has `Auto Rifle Loader` and `Grenade Launcher Scavenger`.

However, in-game I can go to details and see the perks columns and see:
- 2 possible traits related to stats (`Mobility Enhancement Mod`, `Plasteel Reinforcement Mod`)
- 3 possible perks for the column with `Auto Rifle Loader` (`Scout Rifle Loader`, `Submachine Gun Loader`)
- 2 possible perks for the one with `Grenade Launcher Scavenger` (`Special Ammo Finder`)

So my question would be: can you obtain that data, and if so where from? Is it the correct endpoint but I am missing a component identifier?

Note: checked with other vendors in case this was a Xur limitation (as you cannot get his location), but the behavior appears to be identical.

**Comment by andyschott** [comment]
I haven't tried to get perk data from items sold on vendors, but I hope/assume that doing so should be no different than getting perk data from an item in a player's inventory/vault. Given that assumption, maybe [Help with getting armor perks](https://github.com/Bungie-net/api/issues/839) can point you in the right direction?

If that doesn't help, I know I've written code before to get all of the possible perks for an item. It's been a while so I don't remember the calls off the top of my head. If you still can't get it working, let me know and I can look up what I did previously to get this info.

**Comment by rraziel** [comment]
Thanks for the link, it contains useful information.

Well you are probably right, I kinda completely ignored the `sockets` part of the response thinking "whatever that thing is, I can figure it out later".

Looks like now is the time 😃

**Comment by vthornheart-bng** [comment]
Catching up on Github asks that I missed in the pre-Shadowkeep busyness... I'll close this one out since that is the correct spot - though as you're seeing in prod now, we're having 99 problems with sockets.

When the dust settles and socket data starts getting returned again, in whatever form it's returned, you'll be able to use whatever you implement for both Vendors and items!
