### ISSUE TITLE
Affinitization docs : wrong cookie name?

### ISSUE THREAD

**Issue by mikechambers** [Bungie-net/api#1027]
Looking at the Affinitization docs at:

https://github.com/Bungie-net/api/wiki/Affinitization:-benefits,-drawbacks,-how-to

it says to look for the cookie named:

```Q6dA7jjmn3WPGkYAhga2oHvTT+8b849OPtfBrw@@```

However, the cookies that the server is sending to me is named:

```Q6dA7jjmn3WPBQVW4Frm5i3QXv0q+I9ddZfGro+PognXQwjW```

Not sure if the docs need to be updated, or if the cookies are named differently per instance / server.

**Comment by vthornheart-bng** [comment]
Ah yes, we definitely need to update that.  Thanks!
