### ISSUE TITLE
Super Kills stat removed from stats endpoint

### ISSUE THREAD

**Issue by bladefist** [Bungie-net/api#103]
This doesn't sound intentional so thought I better report it here.   It was there before today update.

**Comment by vthornheart-bng** [comment]
Ah, thank you!

**Comment by adherrling** [comment]
In addition (possible related), weaponKillsAbility is now returning 0 for me despite weaponKillsMelee, weaponKillsGrenade, and weaponKillsSuper not being 0.

**Comment by Tetron-bng** [comment]
I am not able repro these issues. I do find that some game modes will have zero kills for Supers or Abilities, but other game modes will have non-zero values.  Are there instances where you are certain the value should be non-zero for specific game modes?

**Comment by bladefist** [comment]
@Tetron-bng Hello!   The link below had SuperKills for each mode when the D2 api released.  After the first update, you guys removed it.  I'd like to have access to it again. 

https://www.bungie.net/Platform/Destiny2/1/Account/4611686018455152673/Character/0/Stats/?modes=AllPvP,Survival,Countdown,Control,Clash,Supremacy,TrialsOfTheNine

**Comment by Tetron-bng** [comment]
If you add &groups=Weapons,General do you find what you are looking for?

**Comment by Tetron-bng** [comment]
@adherrling  Ability kills are specifically kills done by abilities unique to a player's class.  It no longer includes melee, super, grenade.

**Comment by Tetron-bng** [comment]
This is fixed.
