### ISSUE TITLE
[Request] Community challenges in the Milestones endpoint

### ISSUE THREAD

**Issue by SarKurd** [Bungie-net/api#1031]
Is it possible to add community challenges in the Milestones endpoint or maybe create another endpoint.

At this moment i don't see a way to get accurate result.

**Comment by vthornheart-bng** [comment]
Unfortunately, I'm 99% sure that this data is being acquired after the fact from long-running BI queries that we can't feasibly provide real time data for without a significant change to our stats architecture.  I'll talk with some folks about it, but I don't think it's going to be possible to provide anything that approximates real/timely data for these community challenges unfortunately.

**Comment by SarKurd** [comment]
Thanks for the reply, understandable :)
