### ISSUE TITLE
GetClanLeaderboards unexpected exception for maxtop

### ISSUE THREAD

**Issue by kylerberry** [Bungie-net/api#1034]
I'm attempting to fetch leaderboards for a clan of 76 members (clanId=882490)

- when providing `maxtop` 3 more members are returned than the requested number
- in my case, providing a `maxtop` **greater than** `24` throws an exception.

**followup:** I attempted to get data for another clan with a `maxtop = 9999` and it worked perfectly.

**Comment by Tetron-bng** [comment]
Can you paste the exact URLs you are composing?

**Comment by kylerberry** [comment]
@Tetron-bng 

**Not Working:**
Req:
`https://www.bungie.net/Platform/Destiny2/Stats/Leaderboards/Clans/882490?modes=4&maxtop=25`
Resp:
```
{"ErrorCode":3,"ThrottleSeconds":0,"ErrorStatus":"UnhandledException","Message":"We've encountered an error, please try again later.","MessageData":{}}
```
**Working:**
Req:
`https://www.bungie.net/Platform/Destiny2/Stats/Leaderboards/Clans/882490?modes=4&maxtop=24`

note that the only difference is `maxtop` 24 vs 25

**Comment by Tetron-bng** [comment]
Interesting.  The exception you are seeing means there is probably a coding bug in the Bungie.net server.  vthornheart will be able to dig into that.  

I have found you can work around this if you narrow the number of stats getting returned using the statid parameter like this:
https://www.bungie.net/Platform/Destiny2/Stats/Leaderboards/Clans/882490?modes=4&maxtop=100&statid=lbPrecisionKills
