### ISSUE TITLE
Destiny API app is not in my account!

### ISSUE THREAD

**Issue by VictorPuga** [Bungie-net/api#1035]
This issue is not regarding the API, but a Bungie error that I encountered.

I recently wanted to check some info in an application I made with the Destiny API, but when I enter the page, it says that it is not mine. Here are some screenshots:

https://drive.google.com/open?id=1ejZq14uyxsDV1k8xRNDK8EtAq1B6m_Rh
https://drive.google.com/open?id=1C2Tn6frqJ_CTxksXtobRd1lr7GKCvHHh

PS: I don't know if I should post this to GitHub, but the help forums weren't enough

**Comment by delphiactual** [comment]
did you recently disassociate an account from being linked?

**Comment by floatingatoll** [comment]
Did you recently do anything involving crossplay and/or multiple accounts?

**Comment by VictorPuga** [comment]
I did enable crossplay

**Comment by vthornheart-bng** [comment]
What were the steps you took when you enabled Cross Save?  Did you *un*-link any accounts?

If you unlinked accounts and then linked them together into a new bungie.net profile, you may have abandoned your old Bungie.net account, which would have your application tied to it.  If that occurred, the only advice I can give is to create new Application(s) with your new account and swap out your existing API Keys for the new one(s).

**Comment by Tetron-bng** [comment]
https://www.bungie.net/en/Help/Article/12130 -  You can also recover the previous account by following the steps under 'recovery' in this article.

**Comment by VictorPuga** [comment]
I don't think I got prompted to unlink my account, just got asked the credentials for the new platforms to enable cross play.

So, if disable cross save I will be able to recover my account. But if I enable it again, will my account be unlikned again?

**Comment by vthornheart-bng** [comment]
The act of cross saving itself is not able to orphan your Bungie.net account - but you can orphan it from a scenario like this:

* You have a bungie.net account (BNet Account X) with platforms A and B linked
* You log into Bungie.net with Platform C, and create a new Bungie.net account (BNet Account Y) as a result (it has no knowledge of A and B)
* You go through Cross Save with the new BNet Account Y, linking platform accounts A and B.  The act of linking them to BNet Account Y *unlinks* platform accounts A and B from BNet account X, causing X to be orphaned.

Now that you have A, B, and C all linked to Y, I don't believe you can possibly go through such a scenario again unless you did something very unusual (for instance, you try to link them to a whole new platform account D and go through the whole scenario above all over again... like if you own multiple Playstation accounts and link to the wrong one)

**Comment by vthornheart-bng** [comment]
Note that Step 2 could have potentially happened months or years ago, sitting on its own BNet account until you finally cross saved: it could have been a time bomb waiting to go off for you, where it wasn't clear that you had two different and unrelated BNet accounts and some of your platforms linked on one vs. the other.

**Comment by VictorPuga** [comment]
So, just a recap on what should I do:

- Disable cross save.
- Follow the "Bungie.net Profile Recovery" section in https://www.bungie.net/en/Help/Article/12130.
- Wait some time until I can enable cross save again.

**Comment by vthornheart-bng** [comment]
For an alternative to step 3, my suggestion would be asking player support in the help forums to help you re-do your cross save.  Explain to them what occurred, and you can link to this thread so they can see the history of what happened.

**Comment by VictorPuga** [comment]
How would you recommend me to do that? I did post the same issue from GitHub to the Help Forums, and I have no answers to the thread, while you guys have guided me all along.

**Comment by vthornheart-bng** [comment]
Hmm, send me a link to the help forum post you made, and I'll see if I can hit someone up about it.

**Comment by VictorPuga** [comment]
https://www.bungie.net/en/Forums/Post/253587486

Thank you very much for all your help.

**Comment by vthornheart-bng** [comment]
No prob!

**Comment by VictorPuga** [comment]
I recovered my profile!!!

I got helped in the player support, and now I was able to recover it. I will now enable cross save and hope for the best.

**Comment by VictorPuga** [comment]
Done.
I have access to my original account, as well as to the API Keys and all that stuff.

**Comment by VictorPuga** [comment]
Thank you guys for everything you did!

**Comment by vthornheart-bng** [comment]
Sweet, I'm glad it all worked out!
