### ISSUE TITLE
"Wrong" display name in PGCR for cross-save accounts

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#1036]
If a cross-save enabled account plays on a platform other than their "home" platform (e.g. PS4-originating account plays on PC), the displayName for that player in the PGCR is "incorrect". By showing the membership info for the original platform, it will also show the displayName from that platform, rather than the displayName players saw in game.

An example is PGCR [4631908867](https://www.bungie.net/en/PGCR/4631908867) with player "Ali_Man_22". This game was played on PC, and the display name "Ali_Man_22" is from his PS4 Account. In-game, his display name was "GameXYZ".

I understand what/why this happens, but it can be confusing to see different display names in the PGCR than what was actually in the game. While i understand showing the battle-net displayName in this field might not be best, perhaps it could be in additional field like "inGameDisplayName"?

**Comment by floatingatoll** [comment]
If a Steam user changes their profile name after a match, which would you expect to see:

1) Their primary platform’s account name

2) The Steam account name they had at the time of the match?

3) The Steam account name they had at the time that the PGCR was generated and cached?

4) Their current Steam account name at the time that you fetch the PGCR?
