### ISSUE TITLE
D1 Manifest Endpoint Returns a Broken Link for English Manifest File

### ISSUE THREAD

**Issue by serkanbal** [Bungie-net/api#1037]
The manifest endpoint for D1 *sometimes* returns the url `/common/destiny_content/sqlite/en/world_sql_content_f5c774300deb31540a26099000ae9094.content` for the english manifest file. This url leads to a page with 404 error.

Other times it returns the url which was not changed for over a year now: `/common/destiny_content/sqlite/en/world_sql_content_b6c7590005d9365b2723f8995f361e3f.content`

I did not check manifest for other languages. There might be a similar situation with those, too.

**Comment by serkanbal** [comment]
I also realized that the D1 manifest which -I believe- is supposed to be the latest one (`/common/destiny_content/sqlite/en/world_sql_content_f5c774300deb31540a26099000ae9094.content`) has a good deal of broken links for weapon & armor perk icons.

Here are a few example links:
High Caliber Rounds - `/common/destiny_content/icons/9a8766ef4296f0bb15583ba830673471.png`
Secret Round - `/common/destiny_content/icons/9971dfd88416c0cfbad977bbffe039eb.png`
Appended Magazine - `/common/destiny_content/icons/ffe1da7ea020018652fdf05b7e558a45.png`

I am reporting this as I think it might be relevant.

**Comment by vthornheart-bng** [comment]
Good info, thank you - I appreciate it!

I'm hoping to get a fix for this in on Monday.  D1's had to take the back-burner on priorities, so I'm only now looping back to this.

**Comment by vthornheart-bng** [comment]
Okay, at last this is fixed.  We had to work on some deployment-related issues we were having with that legacy D1 content.

You'll notice that the manifest file name has changed again, but it now should be consistent across all of our servers.  It still could change in the future, so keep using the manifest endpoint to detect changes - but the servers should consistently return the same files, whatever the current ones happen to be, from here on for D1 content.

Thanks for bringing this to my attention!
