### ISSUE TITLE
Include information about Slot Allocation in manifest

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#1038]
In talking to @vthornheart-bng about #1029 he mentioned that there could be some information about "Slot Allocation" which could help with the new Shadowkeep segmented stats and also provide some hints about the rounding mode to use. This issue is a reminder to include that data if possible.

**Comment by bhollis** [comment]
The other property I was interested in was the `roundUp` property.

**Comment by bhollis** [comment]
Actually, I may have misinterpreted what "Slot Allocation" refers to (I confused equipment slots with segmented stats). I think it'd still be interesting to have that info, but it'd *also* be great to know about segmented stats :-)

**Comment by vthornheart-bng** [comment]
Unfortunately, I asked around and the segmented stats are basically hard coded into the UI tooltip screens that are shown in the game.  Bummer.  We've got no way to get at them, and I've been strongly advised by the folks who built that system to not re-implement it in the API as it is indeed subject to change without warning.

But the slot allocation is a horse of a different color.  When I get some time, I need to ask about *if* I am allowed to return it and whether it'll be actually useful for you folks, but let's get that on the backlog at least.
