### ISSUE TITLE
how do I get the current nightfalls? 

### ISSUE THREAD

**Issue by michabbb** [Bungie-net/api#1039]
since two weeks, without changing my code, I no longer get the nightfall strikes from the he milestone list, seems like there has something changed. can someone please explain me what? did I miss something??

thanks!!

**Comment by vthornheart-bng** [comment]
I'm going to have to look into it, I believe there was a report from another user last week that also mentioned milestones not coming back consistently.  Unfortunately, if we're experiencing a bug in Milestones our next window for releasing a fix is going to be with the Shadowkeep launch (10/1).

**Comment by andyschott** [comment]
This sounds like the same issue as [#1028](https://github.com/Bungie-net/api/issues/1028).

**Comment by mistahj67** [comment]
#1028

**Comment by xenodus** [comment]
@michabbb Started having the same issue 2 weeks ago too.

Managed to get around the issue by reverting to an old script that grabbed the active nightfalls via character profile with activities (204) and comparing the activities against the activity definition manifest where activityTypeHash is 575572995 and having modifiers count > 0.

**Comment by michabbb** [comment]
@xenodus thanks for the tip. so which api call are you doing here exactly, can you please give me the name of it?

**Comment by xenodus** [comment]
@michabbb Destiny2.GetProfile

e.g. https://www.bungie.net/Platform/Destiny2/4/Profile/4611686018474971535/Character/2305843009339205184?components=204

**Comment by michabbb** [comment]
will try, thanks 👍
