### ISSUE TITLE
GetHistoricalStatsForAccount returns an UnhandledException

### ISSUE THREAD

**Issue by NullRoz007** [Bungie-net/api#104]
Unless I'm doing something wrong here, GetHistoricalStatsForAccount (https://www.bungie.net/Platform/Destiny2/2/Account/4611686018429443774/Stats/?groups=1), returns:

```json
{ 
  "ErrorCode": 3,
  "ThrottleSeconds": 0,
  "ErrorStatus": "UnhandledException",
  "Message": "We've encountered an error, please try again later.",
  "MessageData": {} 
}
```
Just to note, I've only had this issue since todays update.

**Comment by rentalhost** [comment]
Do you have some update on this issue? There some way to us workaround it until it be fixed?
Thanks!

**Comment by BinarMorker** [comment]
Are there any alternatives to lookup deleted characters' stats?

**Comment by vthornheart-bng** [comment]
@BinarMorker Oh, in the future could you make questions like this part of a separate issue?  That way we don't derail Issues that are about other topics!

But to answer your question, unfortunately there is no options at the moment for accessing the information of deleted characters.  I believe that, if you were to query for PGCRs that involved them, their info will still be returned: but I don't think querying directly for them will work.  I'll have to test it at some point to make sure, but it's not intended behavior for deleted characters' data to be returned.

**Comment by BinarMorker** [comment]
I believe this question was relevant because this is the use I make of this
endpoint. Will this endpoint be accessible again?

On Wed, Sep 20, 2017 at 6:38 PM, Vendal Thornheart <notifications@github.com

**Comment by vthornheart-bng** [comment]
Ohh, I see - I thought you were asking an unrelated question!

I do not have an ETA for a fix on the issue at this time.

**Comment by iBotPeaches** [comment]
This is working again. Had to have happened in past 2 hours. My requests are working now.

**Comment by vthornheart-bng** [comment]
Oy, yes!  Sorry guys, that family emergency happened after I fixed it but before the fix was confirmed and deployed, so I didn't update here.  Should be good to go.

**Comment by BinarMorker** [comment]
Thank you very much! Solid work here, works exactly as before :D

**Comment by vthornheart-bng** [comment]
Excellent, glad to hear it!
