### ISSUE TITLE
Heroic Menagerie activity gone from Destiny2.GetCharacter with character activities

### ISSUE THREAD

**Issue by xenodus** [Bungie-net/api#1041]
I've been using Destiny2.GetCharacter (204 component) to grab the available heroic menagerie and its modifiers previously but that data seems to have vanished.

I'm currently getting the following activities:

Daily Heroic Story Mission: Scorned: 1132291813
Zero Hour (Heroic): 2731208666
Crown of Sorrow: Normal: 3333172150
The Menagerie: 352668024
The Reckoning: Tier I: 3143659188
The Reckoning: Tier II: 3264501078
The Reckoning: Tier III: 1446606128
Iron Banner: 3753505781
Last Wish: Level 55: 2122313384
Last Wish: Normal: 1661734046
Scourge of the Past: 548750096
Scourge of the Past: 2812525063
Nightfall: Exodus Crash: 1282886582
Nightfall: The Insight Terminus: 1034003646
Nightfall: The Corrupted: 3034843176
Nightfall: A Garden World: 411726442
The Corrupted: 3374205762
Vanguard Strikes: Level 50: 1895583725

**Comment by justrealmilk** [comment]
If you’re using cross save and you last played on a platform where you don’t have access to the content, it will reflect that. Same rule applies on a character level. TLDR do you have access in game?

**Comment by xenodus** [comment]
Nope, not cross saving and have been using the same character that have access to the activity in-game to do the api calls.

**Comment by vthornheart-bng** [comment]
Hmm, I'll have to look into it.  Did this start happening as of yesterday?

**Comment by xenodus** [comment]
@vthornheart-bng Yes!

**Comment by vthornheart-bng** [comment]
Hmm, I wonder if something changed with how the Heroic Menagerie was set up.  I'll have to look into it.  I assume in-game you still see it as an activity that you can access?  Like it hasn't disappeared?

**Comment by vthornheart-bng** [comment]
Hmm, I hit a random user and got 2509539867 ("The Menagerie: The Menagerie (Heroic)") returned.  Hit me up with your membership and character ID, maybe this is specific to your account.

**Comment by xenodus** [comment]
Just checked and the activity appears in the api call once again on my side too now. 

Could it be due to me not having logged into the character after the maintenance and making the api call previously?

Nevertheless, it seems to be working again. Thank you.

**Comment by vthornheart-bng** [comment]
Hmm, perhaps - that's an odd situation, but it could be that something changed in how the activity was set up such that you had to log in again before it became "visible".

I'll close this one out for now!  Let me know if you run into any other issues!
