### ISSUE TITLE
Access to Scopes for Message endpoints?

### ISSUE THREAD

**Issue by soren42** [Bungie-net/api#1042]
Is there any chance that (in the near-ish future) that we'll be able to have access to the /Message/ endpoints for sending BungieNet messages from our applications?

(FYI, my specific use case is a little something like this: I have activity requirements for members of my clans — let's say, complete some in-game activity every 30 days… just so we can keep recruiting active players.  When a member is approaching 30 days without playing D2 — say on idle day 25 — I'd love to be able to have my automated clan admin dashboard send them a BungieNet direct message from **me** warning them that they're close to being kicked.  This is preferable to just booting them from the clan, which is what the tool does currently.  In the past, this was feasible to do by hand, however, as we've grown, there's just too much turnover and too many clans to expect this to remain something that is manually discharged.)

**Comment by vthornheart-bng** [comment]
I'll bring it up - however, we've had problems with people using the Messaging system to spam folks in the past, which makes me hesitant to open the use of it up.  We'll have to consider the implications.  There'd definitely be some benefits of opening it up as well from this perspective, potentially.

**Comment by floatingatoll** [comment]
OP, would the messages always be sent from a clan admin to a clan member in that same clan?

**Comment by rraziel** [comment]
Not trying to hijack this issue, but being able to:
1. create fireteams (so far it seems everything is read-only) and
2. invite people who have joined said fireteam
Would be very nice as well.

I assume the requirements - the user needs to have joined the fireteam before receiving an invite - should prevent any misuse, but this wouldn't be the first time I underestimate how evil people can be...

**Comment by soren42** [comment]
> OP, would the messages always be sent from a clan admin to a clan member in that same clan?
@floatingatoll 
Yes, at least in my use case — and I believe that would help limit the spam potential.

**Comment by floatingatoll** [comment]
Fireteam joins are off limits for the API as previously discussed every year or so. Search older, closed, issues for Discord integration and Fireteams for more details.

**Comment by rraziel** [comment]
Ah my bad, wasn't aware of those discussions.

**Comment by rraziel** [comment]
Just to be sure I get you right though - eg wrt #955 which seems to say there is some work in progress - when you say off limits you mean never going to happen or just not happening in the foreseeable future?

**Comment by vthornheart-bng** [comment]
I've given it some further consideration, and I think that the big problem for us isn't actually the security but rather that our resources are already stretched thin on Bungie.net.  Endpoints that we make publicly available become endpoints that we have to provide support for and guarantee some degree of backwards compatibility and uptime for in the future.  I think given how little time we can allocate even to the Destiny API at the moment, extending that official support to other systems would likely be a bad idea.  (also, these messaging endpoints were definitely never built with external user convenience in mind... if we did get the time to support it publicly, I'd like for it to come with some refactoring for user convenience)

I'm going to say that we can't do it *for now*, but if we end up in the future with enough people on our team to give the API the attention and support it deserves, I'd put this on the list of features I'd like to provide official support for.  So let's put it on the future wishlist, and I'll try to remember this should we end up in that ideal future.
