### ISSUE TITLE
IMPORTANT: Shadowkeep pre-release documentation and notes

### ISSUE THREAD

**Issue by vthornheart-bng** [Bungie-net/api#1044]
Head here for more information: https://github.com/Bungie-net/api/wiki/2.4.0-(Shadowkeep)-API-Changes

**Comment by ckhicks** [comment]
> so we'll see if my pre-regret will turn into actual regret

😂We appreciate your work, Thorn.

**Comment by rraziel** [comment]
Well I don't know how accurate this transitory component is going to be but even if it is not, you certainly deserve a beer should you ever be around Paris 😃 .
Actually you already deserve one even without this transitory data, so, there, a beer no matter what (2 with the transitory data?).
