### ISSUE TITLE
[Question]Plugs Definition 

### ISSUE THREAD

**Issue by atheon-v** [Bungie-net/api#1046]
Hi Guys! Hope you can help me. 
I'm using Destiny2.GetProfile endpoint to get equipped items. One of components is "ItemSockets" and  i can see "itemComponents"->"sockets"->data list. In that list i found "plugHash" values. As i understand these plugHashes are presenting inserted not-static perks, modes, shaders, masterwork etc, basically all items player can change, but unfortunately i can't found way to define name/icon for that hashes via manifest db. The question is - if i see pligHash "1294026524" where/how i can find details related with this hash(name, icon, impact etc)?

**Comment by andyschott** [comment]
IIRC plugs are in the same table as inventory items - DestinyInventoryItemDefinition IIRC. So load plugs the same way that you load the static information for any equippable item.

**Comment by atheon-v** [comment]
Thanks, @andyschott ! That's really fun)) i thought there is separated source and didn't search in this table) Thanks a lot!

**Comment by joshhunt** [comment]
@atheon-v Pro tip - basically _everything_ in Destiny is an 'InventoryItem'. That would be your first stop for searching for things. 

Secondly, and this is a shameless self promotion, you can use https://data.destinysets.com/ to search the definitions. If you just put the hash in there it would tell you what it is, and what table its in :) 

<img width="365" alt="Screenshot 2019-10-01 at 9 59 38 am" src="https://user-images.githubusercontent.com/46142/65948463-38907600-e432-11e9-97ad-8b45f6b934a3.png">

**Comment by atheon-v** [comment]
Thanks, @joshhunt, data.destinysets.com is very helpful and great work! Thanks for this service!
