### ISSUE TITLE
During maintenance, auth endpoints return 400 for server error

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#1048]
<img width="461" alt="Screen Shot 2019-09-30 at 3 23 56 PM" src="https://user-images.githubusercontent.com/313208/65921261-9bccca80-e396-11e9-9910-d866df081472.png">
<img width="519" alt="Screen Shot 2019-09-30 at 3 24 09 PM" src="https://user-images.githubusercontent.com/313208/65921262-9bccca80-e396-11e9-953b-8498db2cefb3.png">

During the Shadowkeep maintenance, I noticed that the auth endpoints were returning 400 with a payload of "SystemDisabled". I'd expect a 500-series error for this - in DIM, we assumed 400s meant that the auth token was not valid and logged people out.

**Comment by floatingatoll** [comment]
For bonus points, use 503 + Retry-After to indicate either # of seconds until next retry or outright “don’t try again until XYZ”:

503 Service Temporarily Unavailable
Retry-After: Tue, 01 Oct 2019 17:00:00 GMT

Most clients will ignore the retry-after, but any that want to stand up a countdown clock can then do so :)
