### ISSUE TITLE
GetItem returns an UnhandledException Error

### ISSUE THREAD

**Issue by alexanderwe** [Bungie-net/api#105]
Currently I am getting the same UnhandledException error on the `GetItem` endpoint as mentioned for the `GetHistoricalStatsForAccount ` endpoint in #104. 

I hope I do not query this endpoint in a wrong way.

Query: `https://www.bungie.net/Platform/Destiny2/-1/Profile/4611686018452033461/Item/2907129557/?components=307,302
` (Query on Sunshot item)

Response: 
```
{ ErrorCode: 3,
  ThrottleSeconds: 0,
  ErrorStatus: 'UnhandledException',
  Message: 'We\'ve encountered an error, please try again later.',
  MessageData: {} }
```

**Comment by vthornheart-bng** [comment]
Hmm, you've run into an interesting issue - it should return ParameterParseError instead of UnhandledException, but what I think is happening for you is that you're passing -1 in as the MembershipType.  That's not a valid membership type: you'll want to pass the one that matches the membershipId you're using (in this case, the membership ID is 4611686018452033461 - you'll have to look up what their type is)

**Comment by alexanderwe** [comment]
@vthornheart-bng Thank you very much for pointing things out related to the MembershipType. I was not aware of the fact that the MembershipType has to explicitly match to the MembershipId, because `-1` seems to be a valid value when searching for players. That's why I also used it on other endpoints. 
I tried it with the correct type and the error is gone. 

One question/suggestion: Maybe it would be a `nice to have` if the ParameterParseError could indicate which parameter is causing the error to occur, but this just came into my mind.

Thanks again for clarifying the issue with the MembershipType.

**Comment by vthornheart-bng** [comment]
Aye, an understandable point of potential confusion: the -1 maps to "All", which is only valid for searches unfortunately.  In all other contexts, we need the specific membershipType: it prevents us from having to do the same search a second time on the backend to get the matching membershipType.

I will add that to future documentation for that membershipType property!  I also would like to have ParameterParseError return more information.  I'll mark this as an Enhancement request - I'd like to see this come to pass at some point as well.

**Comment by alexanderwe** [comment]
If I would have thought a little deeper about this I should have come to the same conclusion myself :D. But I think I am going to mention your comment on this in the documentation of my API package if you agree with this. 

Thanks for marking this as an Enhancement request. Would be very neat, if it gets implemented in the future.

**Comment by vthornheart-bng** [comment]
No worries, all good!  Yeah, next time around it'll be in our docs.  We don't make it very clear currently when one membershipType option is valid and when it isn't!

**Comment by alexanderwe** [comment]
Thanks a lot !
