### ISSUE TITLE
Le Monarque is gone from API?

### ISSUE THREAD

**Issue by Redthirst** [Bungie-net/api#1052]
I've just noticed that Le Monarque no longer shows in the Exotics section in DIM, which pulls it from Bungie's API. I've posted about it on DIM's Github but was asked to post here instead.

**Comment by vthornheart-bng** [comment]
Hmm, can you still get it in game?

**Comment by vthornheart-bng** [comment]
Hmm, it looks like it's still there.  I see it as hash 3588934839.

**Comment by Redthirst** [comment]
Hopefully I can get it in game, although it was moved from a random drop to a quest reward. It's possible that it's a bug in Destiny Item Manager specifically, but I was sent here from their GitHub.

**Comment by floatingatoll** [comment]
I’m able to see Le Monarque in the Exotics section of my collection in the official companion app. Could you please test the Bungie.net <http://bungie.net/> website or official companion app and see if it’s showing in your collection there?

My Profile > Collections > Exotic > Energy

**Comment by Redthirst** [comment]
Just checked it in Bungie.net, and I don't see it. There is one entry in the Energy Exotics listed as "Unknown", but seeing how Jotunn is openly displayed, I don't see why Le Monarque would be hidden under the "Unknown label". 

I'm not sure about the official app, as I'm not using it, going to download it today when I have a bit more time.

**Comment by justrealmilk** [comment]
It’s possible it wasn’t in the previous manifest as it was previously erroneously in the kinetic node. Restart the companion app or use https://braytech.org/collections/1068557105/2214408526/3919988882

**Comment by Redthirst** [comment]
Braytech doesn't show it(the "Unknown" weapon from Bungie.net is Divinity, according to Braytech), haven't checked the companion app yet. 

I don't think it really matters as long as I actually get the bow in game, but I won't know until 3 weeks have passed.

**Comment by Redthirst** [comment]
Just installed the official Compainion App and there's no Le Monarque under Collection>Exotic>Energy.

**Comment by justrealmilk** [comment]
Its display state also changed from always visible to visible only if acquired. If you go to Braytech -> Settings -> uncheck _Hide invisible collection items

**Comment by Redthirst** [comment]
Alright, that does it for me and it's now visible. So I guess case closed, it's just marked as hidden until acquired after Shadowkeep update, even though Jotunn remains visible.

**Comment by floatingatoll** [comment]
Maybe not case closed —

Thorn, do you want to verify that they intended Le Monarque to be “invisible until acquired” in the API, since that’s a particularly weird one to be in that state?

**Comment by vthornheart-bng** [comment]
I think it'll be better to wait and see if we get another one like this.  If they misconfigured the item, it's too late for them to fix it now that it's live anyways.

**Comment by Redthirst** [comment]
As long as it's still available and it doesn't interfere with the game it should be low-priority. But I don't think it's intended seeing how Jotunn is visible.
