### ISSUE TITLE
SearchDestinyPlayer for steam platform returns only one displayName per case match

### ISSUE THREAD

**Issue by v-fedorov** [Bungie-net/api#1054]
For example I have a sample set of steam players with the displayName "Shadow".
![image](https://user-images.githubusercontent.com/1764879/66090056-b26a5180-e54f-11e9-86ee-cbd96474372c.png)

but `Platform/Destiny2/SearchDestinyPlayer/3/Shadow/` returns only one match for displayName "Shadow" and then another for "shadow" then "SHADOW" and so on.

```
{"iconPath":"\/img\/theme\/destiny\/icons\/icon_steam.png","crossSaveOverride":0,"isPublic":false,"membershipType":3,"membershipId":"4611686018489705044","displayName":"Shadow"}
```

**Comment by vthornheart-bng** [comment]
Ah, this one could be a bit before we can get a fix, if we can.  There's a downstream system that we rely on for these search results, and it looks like it only returns one name at a time.  I'll need to hit them up about it.

**Comment by vthornheart-bng** [comment]
TFS 838479

**Comment by justrealmilk** [comment]
I know you're super busy (as always!) but I'm just realising now how infuriating this! 

![200 1](https://user-images.githubusercontent.com/156681/82328454-4166a400-9a23-11ea-9a93-db2ff3c12606.gif)
