### ISSUE TITLE
SearchDestinyPlayer for cross save accounts returning displayName/membershipType for primary account

### ISSUE THREAD

**Issue by v-fedorov** [Bungie-net/api#1055]
ex: searching steam name `Platform/Destiny2/SearchDestinyPlayer/3/joel.jib/`
returns
```
{"iconPath":"\/img\/theme\/destiny\/icons\/icon_steam.png","crossSaveOverride":0,"isPublic":false,"membershipType":1,"membershipId":"4611686018429588688","displayName":"Cheese Monkey"}
```
Which is that players override account on xbox and not having the steam name there makes it really confusing

**Comment by floatingatoll** [comment]
Is searching by name valid for platform Steam at all? I’m a bit surprised it doesn’t return 403 Forbidden.

**Comment by floatingatoll** [comment]
Never mind, I see it returns current Steam results! Nifty.

**Comment by vthornheart-bng** [comment]
I'll need to give this one some thought.  We have competing priorities that result in the results you're getting there, but I would like to give a better experience when searching for cross save users.  I'll add a bug so that I can loop back to this.

**Comment by vthornheart-bng** [comment]
TFS 838478
