### ISSUE TITLE
Suggestions - Add deleted characters to the Profile call

### ISSUE THREAD

**Issue by BoofLord** [Bungie-net/api#1056]
Currently the only way to get deleted characters is with the account level stats endpoint.  This is not efficient if all you need are the deleted characters.  If they were in the Profile call, you might be able to reduce the load.

**Comment by vthornheart-bng** [comment]
Ah, unfortunately we don't have the ability to do so!  Once the characters are deleted, they're gone from the datasource that we use to pull live game data.  The only place it lives is in the Stats system - which we can't query when we fetch characters for performance reasons.  Sorry about that!
