### ISSUE TITLE
Chrome Version 77 Black screen at Application Page

### ISSUE THREAD

**Issue by JoachimFlottorp** [Bungie-net/api#1057]
When I go to the page https://www.bungie.net/en/Application
Which is where you get the API key, nothing happens. The page only shows black. Nothing else. Is the API down, gone or what?

**Comment by EdgarVerona** [comment]
Hang tight - we have a bug on that page that will be fixed by a hotfix later today.

**Comment by JoachimFlottorp** [comment]
Alright, great to hear that it is being fixed.
