### ISSUE TITLE
TalentGrid definitions no longer include display info

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#1059]
As an example: https://data.destinysets.com/i/TalentGrid:2307176982

We've been using talent grids to display subclass info. However with the most recent updates, this info is no longer very useful. `nodes[x].steps[y]` no longer has filled in `displayProperties`, `nodeStepHash`, etc. All nodes show as "hidden" as well.

Without this info we can't display the subclass configuration, or do some other cool things like highlighting the current subclass on the icon.

**Comment by vthornheart-bng** [comment]
Ooh, I'll have to look into this - it ought to still have that data in it, something has likely gone awry in that data.

**Comment by vthornheart-bng** [comment]
Ah, sure enough it's broken.  Sorry about that, total miss on our part.  I'm filing a bug now.
