### ISSUE TITLE
Not all vendor challenges available from milestones

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#1060]
From looking at the Tower, it appears every vendor has a challenge that returns powerful gear. However, only four are available in Milestones. Also:

* The challenges don't have the name of the vendor in their description - they just say "Complete bounties from this vendor".
* Progress doesn't appear to show up.
* There are no rewards defined.

**Comment by dcaslin** [comment]
Ikora's weekly milestone "Know Thy Enemy - An Arm And a Leg" probably fits into this. It's weekly repeatable and returns Tier 3 Powerful gear. Both items are in the Manifest DB as quests at the moment (for example one of the steps of An Arm and a Leg is has 691192862).

**Comment by vthornheart-bng** [comment]
Yeah, I dig that - and thanks for posting here, I lost sight of this issue in the other things that have been going on.  I'll file a bug on all this.
