### ISSUE TITLE
No stats / investment stats for Armor 2.0 in definition

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#1061]
https://data.destinysets.com/i/InventoryItem:4078925540

Armor 2.0 items don't have all six stats listed in either the `stats` or `investmentStats` fields of `DestinyInventoryItemDefinition`. I realize these can't really be populated with base values, but if that's the case they might as well not even be there.

Side note - it'd be amazing to have the stat ranges present here, so we could calculate how close to an optimal roll we have gotten.

**Comment by bhollis** [comment]
For DIM, what would be useful is if the "live" instanced item information we get from GetProfile included the investment stats along with the regular stats. Though, I suppose we can also just 🤞and assume those stats don't have interpolation.

Beyond that, I guess all I'm asking is that the definitions either include all those stats or none - today there are just three out of six. It wouldn't affect my life though, it just seems weird. 

If we could get stat range info in the definitions, then definitely my vote would be for that to be present for all six.

**Comment by EdgarVerona** [comment]
Makes sense all around - I'll need to investigate.  Right now when it comes to investmentStats and stats, we don't do any special computation anymore/trying to figure out the ways in which an item can spawn, so those are all coming straight from game content.  The fact that they're not defined there makes me think that they must be coming from some other source - perhaps exclusively from the plugs inserted?  I'm not certain.  I will need to investigate to find out before I can say for sure what's up with those additional stats.  Once I find that out, we can work out what we can do from there!

**Comment by vthornheart-bng** [comment]
TFS 838473
