### ISSUE TITLE
Screenshot missing for at least 1 weapon

### ISSUE THREAD

**Issue by sgtfrankieboy** [Bungie-net/api#1062]
While browsing through the data I noticed that the screenshot for the Malfeasance (204878059) is returning a 404 Not Found from bungie.net

https://www.bungie.net/destiny/common/destiny2_content/screenshots/204878059.jpg

**Comment by vthornheart-bng** [comment]
Hmm, I'll give it a look!

**Comment by vthornheart-bng** [comment]
Ah - so strangely, the URL's a bit off there... it should be:

https://www.bungie.net/common/destiny2_content/screenshots/204878059.jpg

Are you seeing the other one in our data?

**Comment by sgtfrankieboy** [comment]
Whoops, seems to be a brainfart on my side. Image is correct in the bungie data. Sorry for the bother!

**Comment by EdgarVerona** [comment]
No worries, it's all good!
