### ISSUE TITLE
CurrentPage with Group Search, API Bug or Docs Issue?

### ISSUE THREAD

**Issue by BarryCarlyon** [Bungie-net/api#1063]
After banging my head against the wall. I was stuck getting the error described in #647 

I have observed that the minimum required fields are essentially `name` and `currentPage`

I was doing:

```
                name: 'SomeName',
                groupType: 1
```

And was getting the invalid parameters

So chased the other ticket down and poked about a bit, it works with

```
                name: 'SomeName',
                groupType: 1,
                "currentPage": 1
```

and then any combination up to "all the fields"

```
                name: 'SomeName',
                groupType: 1,
                "creationDate": 0,
                "sortBy": 0,
                "itemsPerPage": 100,
                "currentPage": 1
```

Basically `currentPage` is a required field but the docs don't say it is. (I mean sure you need a name too but thats sorta obvious as otherwise you won't get any results.)

Could also be the API doesn't have a default page if one isn't specified?

**Comment by vthornheart-bng** [comment]
Yeah, I dig that!  I'll file a bug.  It seems reasonable that it should have a default value!

**Comment by vthornheart-bng** [comment]
TFS 838463
