### ISSUE TITLE
Weekly Vanguard Strikes & Reckoning removed from Milestones api call. How should I get their current modifiers now?

### ISSUE THREAD

**Issue by xenodus** [Bungie-net/api#1064]
Weekly Vanguard Strikes & Reckoning seems to be removed from /Destiny2/Milestones/ API call since Shadowkeep.

Are there other ways to get their modifiers programmatically? Thanks!

Result of Milestones API call (name/id)
--
Flashpoint: 463010297
Xûr: 534869653
Leviathan Raid: 3660836525
Leviathan, Eater of Worlds Raid Lair: 2986584050
Spire of Stars Raid Lair: 2683538554
Last Wish Raid: 3181387331
Weekly Clan Engrams: 4253138191
Clan Rewards: 3603098564
Scourge of the Past: 1342567285
Crown of Sorrow: 2590427074
The Dawning: Eva's Return: 4128810957
The Season of Giving: 3177730289
The Lost Cryptarch: 2958665367
The Revelry Begins: 3915793660
Spring Comes to Eververse: 291994631
Shady Schemes: 3802603984
Vanguard Service: 2709491520
Live-Fire Exercises: 2594202463
Spare Parts: 3899487295
Nightfall: The Ordeal Weekly Completions: 1942283261
Nightfall: The Ordeal Weekly Score: 2029743966
Weekly Gambit Challenge: 3448738070
Crucible Rotator Playlist Challenge: 4191379729
Crucible Core Playlist Challenge: 2434762343

**Comment by ttgmpsn** [comment]
Those aren't the only activities where you can't get the modifiers for. There is a workaround I detailed in #432 (my request to add modifiers to the CharacterActivities component) - the bungie.net website seems to get access to more data than we, and can be "abused".

**Comment by xenodus** [comment]
Thanks @ttgmpsn ! I'll update my app to scrapping the website too for now.

**Comment by vthornheart-bng** [comment]
Oh man, that's a throwback, I'm glad you linked to that bug @ttgmpsn .

Hang tight on that guys, I'd prefer to return it from the API - both because we just plain ought to, and because scraping the site is computationally expensive for us (which obviously given the current situation we're experiencing is something we're a bit sensitive about) :)

I'll see if I can cram a fix in for #432 that might assist with this situation.  It's a good idea, we've just never gotten around to it.

**Comment by floatingatoll** [comment]
For those not aware, and I’m not Bungie so small errors are possible here  -

The API, including the Bungie website, has second-tier priority to the game internal APIs, so when the first-tier priority clients (Xbox, PlayStation, Steam, Strava) are really super busy (like Tuesday) the API goes down until things chill out. So if you scrape the website a lot you could end up hammering a lot of unrelated backend systems that the website uses - at which point the API could go down.

If you can at all be patient, please do wait until Thorn &co can catch up. There’s just two people on the API team and there’s millions of us and our requests.

**Comment by xenodus** [comment]
Will do! Shall wait for the update!

**Comment by vthornheart-bng** [comment]
Oh, actually yeah let me go ahead and close this one and get #432 on the docket!
