### ISSUE TITLE
Missing vendor categories from profile vendors

### ISSUE THREAD

**Issue by rraziel** [Bungie-net/api#1065]
Hello,

When retrieving vendor data, the categories are not filled for:

- `1841717884` (Petra Venj)
- `1748437699` (Tyra Karn) (yes, I know, who even remembers she exists?)
- `919809084` (Eva Lavente) (probably normal as she's not around right now)
- `1976548992` (Ikora Rey) (probably normal as she's usel... not selling anything right now)

So, yes, mostly Petra 😄 .

Instead there is just an empty list, meaning no way to get the categories and the items within those categories.

**Comment by EdgarVerona** [comment]
Indeed, unfortunately for Petra Venj this is a limitation of the API with regards to how the Vendor was set up.  To fix it, we would need the game designers to change how she was implemented - but they don't have time to go back and change the various systems that would need to be changed to make her work again while also providing us her data.

More details here:

https://github.com/Bungie-net/api/issues/704

The other vendors should return data once they actually are available in the game and sell items!

**Comment by rraziel** [comment]
Ah my bad hadn't seen that other issue, I'll close this one then.
