### ISSUE TITLE
Chrome warning for cross-domain cookies

### ISSUE THREAD

**Issue by rraziel** [Bungie-net/api#1066]
Chrome recently started issuing warning regarding the cookies set by the Bungie platform:

A cookie associated with a cross-site resource at http://www.bungie.net/ was set without the SameSite attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with SameSite=None and Secure. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by vthornheart-bng** [comment]
Thank you!  We'll take a look at that!

**Comment by vthornheart-bng** [comment]
TFS 837872

**Comment by floatingatoll** [comment]
https://blog.chromium.org/2019/10/developers-get-ready-for-new.html

**Comment by Tetron-bng** [comment]
Bungie.net uses cookies in the 3P cases sparingly, mainly for performance improvements around caching (at least that is how my memory serves).  Will anything break if a client does not honor cookies being set by Bungie.net?

**Comment by vthornheart-bng** [comment]
Indeed, I believe the only one that will actually matter is the affinitization cookie.  I'm asking around about that now, to see if we can change it!
