### ISSUE TITLE
Question about profile transitory data

### ISSUE THREAD

**Issue by Aioros** [Bungie-net/api#1067]
The Transitory component (party members, current activity details, last orbited destination) was a great addition, and I'm sure it's going to be very useful for many of us. I have a couple of questions about it:

1. I noticed the `partyMembers ` data is a little stranger than I expected. It seems to always have 20 elements (mostly empty); the `emblemHash` seems to be the same for all fireteam members (at least it was in my test); and I couldn't find a description of the possible `status` values.
2. Is there any chance for this dataset to include all players in the instance, and not just the actual fireteam? Basically what the in-game Roster menu shows. I realize this is a long shot, but I wonder if that's at all feasible.

**Comment by justrealmilk** [comment]
partyMembers was a mistake and will be removed soon

**Comment by rraziel** [comment]
Moreover, I find it strange - maybe because that's really the information I was most interested in - that the current activity does not include the actual... activity.
I was expecting some kind of activityHash or activityType/ModeHash?
Any chance this would be added? Because right now I can tell there are 8/24 people in the tower, but not that the player is in the tower, for example.

**Comment by justrealmilk** [comment]
You need to corroborate the activity from another component. It’s not in transitory data as it would require an extra call on the backend.

**Comment by vthornheart-bng** [comment]
Aye, the Transitory data is essentially a bucket of "buyer beware" data from potentially unstable data sources on the game server.  The current activity, strangely, is a bit more stable: and as such, it's been returned for a while in the API in DestinyCharacterActivitiesComponent, which predates the Transitory component.

You'll want to fetch that component to get that info: I didn't add it to the Transitory component to avoid redundancy - give that a shot and let me know if that helps!

**Comment by rraziel** [comment]
Yup that's fine, I had it from that other component already,
I just figured using the lowest number of components at a time when querying would reduce the load on the servers (trying to help :smile:).

**Comment by vthornheart-bng** [comment]
Aye, I totally appreciate it!

Indeed, if folks find they're going to consistently query for both only to get that data, I'm definitely up for a little duplication to save returning extra components!

Other people using transitory data, are you in the same boat?  Would you request the Activities component if you had the current activity data in the Transitory component?

**Comment by rraziel** [comment]
If it helps, my use-case is basically to build a view similar to the clan roster in-game (players, grouped if they are in a fireteam, and seeing what they are doing right now).

But to get back to the initial issue, the "filler" players are a bit strange indeed.

And to get back to the documentation, I think the mysterious "posse" is just all the blueberries? :smile:

**Comment by Aioros** [comment]
Same boat for me. I imagine that most of the people interested in the transitory bucket would also be looking for current activity info.
