### ISSUE TITLE
Some items have reusable plugs in definitions that they can't actually get in the real world

### ISSUE THREAD

**Issue by EdgarVerona** [Bungie-net/api#1069]
For instance, take this weapon:

https://data.destinysets.com/i/InventoryItem:1645386487

The Firefly perk on this weapon can't be obtained in the real world, but socket index 3 has it defined as a reusable plug item, even though it is using randomized rolls.

Currently, the assumption folks make about the data is that this is the plug that will be assigned if you pull the item out of collections: but this is not necessarily the case, and can be misleading.

When I can find time, I'd like to see if I can find a way to remove these plug definitions when we know that they will never actually be used, and potentially add data about what plug will be inserted by default from collections if possible.  (I cannot guarantee that this is possible/feasible, will need to investigate)

**Comment by vthornheart-bng** [comment]
TFS 838429
