### ISSUE TITLE
Lore icons resolution

### ISSUE THREAD

**Issue by rraziel** [Bungie-net/api#1072]
Right now icons for lore (both lore and record really, + the presentation node has no icon) are in a very low resolution: 84x84.
In-game, the book covers for all lore triumphs seem to be very detailed, so I was wondering if there was any chance we'd get the URL to the higher resolution version.

**Comment by vthornheart-bng** [comment]
Hmm, there was a time where we used to provide the book cover images, though admittedly the last time we used them was in D1 so it could have broken without our knowledge.  I'll file a bug to investigate!

**Comment by vthornheart-bng** [comment]
TFS 838420
