### ISSUE TITLE
How to get new character stats?

### ISSUE THREAD

**Issue by ernie117** [Bungie-net/api#1074]
I'm currently using this call to get character information `https://www.bungie.net/Platform/Destiny2/3/Profile/4611686018467844361/?components=200` which only returns light, mobility, etc as part of the response:
         
```
"stats": {
  "1935470627": 765,
  "2996146975": 34,
  "392767087": 33,
  "1943323491": 31
},
```

I've tried looking through the 2.4 update docs and looking through the issues here but can't find any info on how to get the newer stats like discipline, intellect, etc. Is there a new component/endpoint or something or is this info just not available yet?

Thanks.

**Comment by rraziel** [comment]
I just compute it from the equipped gear, not sure there is pre-made aggregate somewhere.

**Comment by rraziel** [comment]
Just a quick added note in case you read this these days: the API is currently throttled/limited so such stats are not available on gear either.

**Comment by ernie117** [comment]
Okay, thanks for your replies.
