### ISSUE TITLE
currentActivityModeType contains wrong info in Survival Freelance

### ISSUE THREAD

**Issue by mikechambers** [Bungie-net/api#1075]
Calling:

https://www.bungie.net/Platform/Destiny2/1/Profile/4611686018429783292/?components=200,202,204&count=1

To get the users status.

When user is in Survival Freelance playlist currentActivityModeType and currentActivityModeTypes are returning the wrong data and in the wrong order:

They are currently returning:

```
"currentActivityModeType": 5,
"currentActivityModeTypes": [
    5,
    10
],
```

Which is AllPVP and Control.

It should be returning:

```
"currentActivityModeType": 37,
"currentActivityModeTypes": [
    37,
    5
],
```

which is Survival and AllPvP

2 Things:

currentActivityModeType should be 37, not 5.

currentActivityModeTypes should be 37,5, not 5, 10. (all other game types return in order of most to least specific).

Attached the the complete data set returned from the call while in a game.

[mode_bug.txt](https://github.com/Bungie-net/api/files/3694768/mode_bug.txt)

**Comment by mikechambers** [comment]
fyi, this seems to be correct in activities. Ill double check tonight and confirm whether its still an issue when checking status.

**Comment by vthornheart-bng** [comment]
My suspicion is that either this algorithm or how we assign activityModes to activities in the definitions is broken by the changes that happened to crucible playlists.  I'll file a bug!

**Comment by vthornheart-bng** [comment]
TFS 838408

**Comment by mikechambers** [comment]
Note, it is the same issue for Labs Elimination.

**Comment by mikechambers** [comment]
Note, also an issue for Momentum control, which only returns crucible.

```
                    "currentActivityHash": 750001803,
                    "currentActivityModeHash": 1164760504,
                    "currentActivityModeType": 5,
                    "currentActivityModeHashes": [
                        1164760504
                    ],
                    "currentActivityModeTypes": [
                        5
                    ],
```
