### ISSUE TITLE
Set overrideStyleItemHash for items with ornaments

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#1077]
This is a total wild wishlist item, but now that the game shows items with their ornamented style and the ornament icons are really nice, it'd be amazing if the API would use `DestinyItemComponent#overrideStyleItemHash` to point to the correct ornament icon. Of course, we can (and will) do this by digging through the sockets and plugs, but it feels like the job `overrideStyleItemHash` was born to do.

**Comment by vthornheart-bng** [comment]
That is a 100% fantastic idea, let me see what we can do!

**Comment by bhollis** [comment]
I guess I was wrong about the game actually using the ornament icons though 😰

If it isn’t displayed that way in game it’s probably best to stay a DIM only feature. Somebody had said they were updated in game and I was too lazy to check.

**Comment by vthornheart-bng** [comment]
I think the idea is solid, to have a field that quickly indicates the currently active ornament without having to fetch the enormous and currently inactive sockets component.  I'm game for adding a new convenience field for that purpose, that might save both of us a lot of bandwidth!

**Comment by bhollis** [comment]
It wouldn't save DIM any bandwidth, since we'll still get all the sockets for other stuff...

**Comment by vthornheart-bng** [comment]
Ah, understandable.

**Comment by vthornheart-bng** [comment]
TFS 838416
