### ISSUE TITLE
Question on the game version vs season hashes

### ISSUE THREAD

**Issue by YourFavoritePerson** [Bungie-net/api#1078]
I don't quite understand the relationship between the season hashes and the versionsowned variable.

The newest doc says: "First, Seasons are something purchased with silver - as such, they will stay with the Destiny Profile that purchased them, **regardless of the platform on which you play**".  I expected the season hashes array to be kinda like a "max version owned" variable for any platform because it indicates it follows you from platform to platform.

As I understand it, the versions owned variable currently indicates the version owned on the latest platform you played on.   To me, that means that someone can have a version owned variable set to less than 32 (lower than shadowkeep) but still have the season hashes.

I set my stuff up to see if they have the first shadowkeep season pass hash code as a means to see if they own shadowkeep *somewhere*.  Someone tried joining and was rejected for not owning shadowkeep, so I investigated it a bit.  His game version was a 39 but he didn't have any season hashes in that array.  It's an easy fix on my side but I'm just not sure how these two things relate to each other.  I'm missing something.

This was the guy btw: https://www.bungie.net/en/Profile/254/16880842/ChickenoodLz

**Comment by bhollis** [comment]
Season hashes are list of the season passes a person has bought. They won’t tell you if somebody bought Shadowkeep unfortunately.

**Comment by YourFavoritePerson** [comment]
My understanding of it is that Shadowkeep comes with the season of the undying, so how can someone have a game version of a 39 and no season pass?  They have to own shadowkeep to get to a 39.

On steam: "Buy Destiny 2: Shadowkeep
Includes Shadowkeep, Season of the Undying and Shadowkeep Pre-Order Pack"

On PS4: "Destiny 2: Shadowkeep includes a digital copy of the game and a single Season Pass, providing exclusive activities and rewards."

On xbox:  " Season Pass for Season of the Undying*"

**Comment by floatingatoll** [comment]
I believe it’s possible to play Shadowkeep with alternate and crossplay accounts in such a way that the season passes end up either applied to another account and/or converted to silver, since Shadowkeep is a DLC purchase (content is available to all logged in accounts using that installation) rather than a season pass (one is included for free, and applied to their first character that logged in after getting the DLC, but not later characters).

**Comment by vthornheart-bng** [comment]
Indeed, what floatingatoll mentioned is possible for this to occur.  It all depends on if they logged in on Steam before activating cross save, and/or before PC Migrating.  In either of those scenarios, they could end up with Seasons applied to an account that they did not intend/that did not end up being the account on which they actually end up playing.

Ask that user if they can actually access season content: and if they can't, have them contact Player Support to see if they can resolve the issue.

If they *can* access season content as-is, then loop back here and I'll do some investigating.

**Comment by YourFavoritePerson** [comment]
They can't access the content.  He says thanks.  He had no idea why it wasnt working.

Where's player support?

**Comment by vthornheart-bng** [comment]
Ah, understandable, no worries!

Have him head to https://www.bungie.net/en/Forums/Topics?pNumber=0&tg=Help&tSort=0&tType=0&d=0&lang=en, and post there letting them know that he can't access his Shadowkeep season, and that he may have lost it in the PC Migration process.  The support folks check that forum - though they're a bit swamped at the moment, they should get back to him once they're able!

**Comment by YourFavoritePerson** [comment]
Thanks.  I'll let him know.
