### ISSUE TITLE
Engrams have a primary stat (power) equal to your seasonal artifact power

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#1079]
Engrams in the postmaster appear to come with a Power primary stat that's equal to the current Seasonal Artifact's power. I'm not sure what that's supposed to represent, but DIM displays power for anything that has it, which results in weird UI:

![image](https://user-images.githubusercontent.com/313208/66341656-96becc80-e8fc-11e9-815b-c01a0031019a.png)

I'm specifically talking about the `DestinyItemInstanceComponent#primaryStat` property, which is set to this:

![image](https://user-images.githubusercontent.com/313208/66342424-3c267000-e8fe-11e9-9bfe-97bf46e134f9.png)

**Comment by vthornheart-bng** [comment]
Ah, at one point I believe this was returning the power level that you see when you hover over it in game.  Very possible that this broke.  I will file a bug!

**Comment by vthornheart-bng** [comment]
TFS 838415
