### ISSUE TITLE
Ikora's Challenge not in Milestones

### ISSUE THREAD

**Issue by dcaslin** [Bungie-net/api#108]
Here's sc_SlayerAge's profile as an example: https://www.bungie.net/Platform/Destiny2/2/Profile/4611686018445232688/?components=CharacterProgressions,

I believe we'd expect the milestone hash to be 2122634728.

**Comment by sgtfrankieboy** [comment]
Seems to be a duplicate of/addition to #88.

**Comment by dcaslin** [comment]
Good call
