### ISSUE TITLE
Vex Offensive Activity returning pgcrImage for Menagerie

### ISSUE THREAD

**Issue by kramrm** [Bungie-net/api#1080]
Activity Mode 1963485238 for Vex Offensive appears to return pgcrImage for the Menagerie.

Returns: /img/destiny_content/pgcr/menagerie.jpg
Should be: /img/destiny_content/pgcr/vex_offensive.jpg

**Comment by kramrm** [comment]
Note: Vex Offensive Final Assault returns vex_offensive.jpg, as does my activity history on Bungie's web site.

**Comment by vthornheart-bng** [comment]
Ah, thanks for reporting this!  I'll file a bug!

**Comment by vthornheart-bng** [comment]
TFS 838475

**Comment by kramrm** [comment]
It also looks like Nightmare Hunt ActivityMode:332181804 is also returning the Menagerie pgcrImage.  Not sure which image it should be for this as this is for the hunts overall, and each individual hunt seems to have their own image as well.

**Comment by kramrm** [comment]
In the same vein, the Nightmare Hunt weekly milestone Milestone:2246196133 is returning Image for vanguard_strike_playlist, which doesn't seem specific to this activity milestone.

**Comment by kramrm** [comment]
I see that the pgcrImage values have been corrected, though the Milestone in my previous message is still showing Vanguard_Strike_Playlist
