### ISSUE TITLE
PGCR UnhandledException

### ISSUE THREAD

**Issue by BlazeBoss17** [Bungie-net/api#1081]
Many postgames return with an ErrorCode=3, UnhandledException. Here are some examples:

4783650786
4780915727
4781581022
4784038711
4778956355
4780273341
4784096780
4780426381
4782473928
4781983755
4783340416
4780060007
4783601492
4783984833
4783564010
4780766150
4783085099
4781142056
4782866342
4779556787
4782944273
4783788632
4782418869
4780258236
4780936851
4783783248
4781367654
4783886184
4779937811
4783377698
4782532512
4780603626
4779225903
4782254462
4778206253
4781406422
4783946970
4780863667
4783588704
4781220445
4783812368
4784197424
4784251099
4784403324
4784402143
4784520900
4784687202
4784813855
4784991844
4784953386

**Comment by TorKallon** [comment]
Agreed. We have the same list. They are consistent.

**Comment by EdgarVerona** [comment]
I'll be looking into this today, I think I've found the likely culprit but I need to do some verification.  It is definitely too late for today's deployment, but I'll get the fix out for our next deployment (tentatively 10/22, or earlier if a hotfix is approved)
