### ISSUE TITLE
Game content error: Nightfall: The Ordeal: Legend (The Scarlet Keep)

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1084]
Nightfall: The Ordeal: Legend activity for this week is The Scarlet Keep though this version of the activity erroneously describes itself as Strange Terrain... which trickles down into the API.

Its hash is: `1193451437`

![tiger_release_final_20191009_153835](https://user-images.githubusercontent.com/156681/66454455-476ace80-eaab-11e9-8500-a2675223ef9f.png)

**Comment by vthornheart-bng** [comment]
Oh, very odd!  I'll bring this up to someone.

**Comment by justrealmilk** [comment]
Fixed according to today's patch notes
