### ISSUE TITLE
Postgame Carnage Reports displaying wrong team name

### ISSUE THREAD

**Issue by mikechambers** [Bungie-net/api#1085]
Calling:

https://www.bungie.net/Platform/Destiny2/Stats/PostGameCarnageReport/4822954418/

The teamName for the second team name is wrong. It should be Alpha, but it is showing the teamId.

```
"teams": [
            {
                "teamId": 17,
                "standing": {
                    "basic": {
                        "value": 0.0,
                        "displayValue": "Victory"
                    }
                },
                "score": {
                    "basic": {
                        "value": 129.0,
                        "displayValue": "129"
                    }
                },
                "teamName": "Bravo"
            },
            {
                "teamId": 18,
                "standing": {
                    "basic": {
                        "value": 1.0,
                        "displayValue": "Defeat"
                    }
                },
                "score": {
                    "basic": {
                        "value": 123.0,
                        "displayValue": "123"
                    }
                },
                "teamName": "18"
            }
        ]
```

**Comment by delphiactual** [comment]
https://github.com/Bungie-net/api/issues/627

**Comment by vthornheart-bng** [comment]
Ah, yes - my apologies on this, the existing bug has been so low in our priority list that it's never been addressed.  Something funky is going on there, but as of yet it's been so low of a priority that we haven't been able to investigate.  The recommended workaround for now would be to not show the team name (note that in the game we don't actually use the Alpha and Bravo designators for teams anymore either)

**Comment by mikechambers** [comment]
Thanks. And sorry for missing the duplicate.

**Comment by vthornheart-bng** [comment]
It's all good, don't worry about duplicates - there's a lot in the backlog!
