### ISSUE TITLE
Garden of Salvation activity lacks directActivity fields

### ISSUE THREAD

**Issue by rraziel** [Bungie-net/api#1087]
Just thought it was odd as the other raids have it (and I was using it to filter raids :smile:), but the activity type hash is present anyway.
Maybe deprecate the direct fields?

**Comment by vthornheart-bng** [comment]
Hmm, I feel like it _ought to_ have one, but I'm not sure why it's missing it.  I think it's worth investigating, as it is useful for a few purposes (including our own sometimes!)

**Comment by lowlines** [comment]
Adding to this, it is missing the normal `activityModeTypes` and `activityModeHashes` properties like other raids.
