### ISSUE TITLE
Progression season resets (where applicable) have gone missing

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1089]
Follow up on a casual mention to help you track it more easily...

https://github.com/Bungie-net/api/issues/780 went live and we love it. 

It's an array of seasonNumber:resetsTotal on Valor and Infamy progressions

With Shadowkeep, it went missing. 💔

**Comment by vthornheart-bng** [comment]
Oh, shoot.  Something must have changed about how that was implemented - I'm going to have to give it a look.  Thanks for the heads up!
