### ISSUE TITLE
GetHistoricalStatsForAccount() returning error code 3

### ISSUE THREAD

**Issue by lax20attack** [Bungie-net/api#109]
Request:
https://www.bungie.net/Platform/Destiny2/1/Account/4611686018429660408/Stats/?groups=General,Weapons

Returns:
UnhandledException - Code 3

Docs link:
https://bungie-net.github.io/multi/operation_get_Destiny2-GetHistoricalStatsForAccount.html#operation_get_Destiny2-GetHistoricalStatsForAccount

Thanks!

**Comment by iBotPeaches** [comment]
#104 :)
