### ISSUE TITLE
Content creator assets

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1090]
This has been asked before but I thought I'd raise it again as circumstances have changed and matured (independence).

We often ask for higher resolution/quality icons and related images i.e. https://github.com/Bungie-net/api/issues/1072, and as there's presumably fewer loops to jump through now, I'd like to ask again on behalf of content creators (artists, streamers, lore heads, and most importantly, developers).

I propose creating, essentially, a media kit on a seasonal basis and putting on the press kit dropbox or similar. I'm proposing this as high res lore book covers add up to some bandwidth on their own let alone all the other artifacts so make us host them!

Ty ty ty

**Comment by vthornheart-bng** [comment]
What images would you want to see in that media kit - both existing types of images and new images, if you're imagining new ones?  Just to get an idea of the scope.

**Comment by justrealmilk** [comment]
key items include

- lore book covers
- triumph seals
- collections badges

are pretty standard ones but the rest are generally pretty specific to the season, especially moving forward with the changes to the game

- artifact and its states (https://www.bungie.net/7/ca/destiny/bgs/seasons/VEye.png is an incredible example of how a media assets can double up)
- seasonal banners seen in places such as the season pass game UI (a smaller squarer version appears through the API in one of the season definitions)

and then there's some categories that I just want to spoil myself with which are totally okay to exclude but hey nothing ventured nothing gained

- I like to theme parts of my project (braytech.org) based on the current season. There are parts of the game UI that are constructed of various smaller rasterised layers to create a total effect. Using one or some of these items can be akin to window dressing or _theming_ as I mentioned - like the cherry on top of a cake

I know artists _love_ high quality reference imagery and that youtubers would relish assets such as the gate lord's eye above.

**Comment by erijohnt** [comment]
I was just searching for these exact kinds of assets and happened to stumble on this PR while digging! In particular, I was working on a map/diagram for use as a raid guide. I'm using various icons like the main quest marker, crosshairs (from the Destiny font), and mote-related triumph images. So +1 for the items mentioned above. 

Also if icons for the [UI elements](https://www.behance.net/gallery/60073341/Destiny-2-UI-Visual-Design) were high-res or even available as vectors (svg/eps/ai), that would send me and other infographic designers over the moon.
