### ISSUE TITLE
Discipline, Intellect, Stregth in Destiny2.GetProfile

### ISSUE THREAD

**Issue by atheon-v** [Bungie-net/api#1093]
Hi! Will new stats be added to "Characters" component of Destiny2.GetProfile endpoint?
For now "stats" reflect only light/mobility/recovery/resilience.
Thanks!

**Comment by NigelHietala** [comment]
Yes it would be great to have these added

**Comment by vthornheart-bng** [comment]
Ah, thank you for reporting this!  Indeed, it ought to be returned - this feels like a higher priority bug if it's not being returned, so I will bump that higher in my list.

**Comment by atheon-v** [comment]
Thanks, @vthornheart-bng !

**Comment by vthornheart-bng** [comment]
No prob!  This one'll be fixed for our next deployment.

**Comment by vthornheart-bng** [comment]
Ah sweet, glad it worked out!
