### ISSUE TITLE
Zoom stat reports aggregating by Character

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#1094]
https://data.destinysets.com/i/Stat:3555269338

I think the Zoom stat should use DestinyStatAggregationType.Item, not DestinyStatAggregationType.Character, since zoom (I think) only applies while using that particular item.

**Comment by vthornheart-bng** [comment]
I'll have to look into that - these are game sourced, and may be a typo or error that they can fix.

**Comment by bhollis** [comment]
Or maybe it reveals a deep mystery of the game mechanics... ;-)

**Comment by vthornheart-bng** [comment]
Ha, maybe!  What a hack that'd be!
