### ISSUE TITLE
itemCategoryHashes can be null

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#1096]
The openapi description does not mark `DestinyInventoryItemDefinition#itemCategoryHashes` as nullable, but it often is. This is true of a lot of properties, but this is the one that tends to trip up DIM contributors the most. If it were marked nullable in the openapi JSON, we'd generate it as nullable in TypeScript and get a warning when we assumed it was there.

**Comment by vthornheart-bng** [comment]
Yes, that makes a lot of sense - I'll add it to the documentation bugs!
