### ISSUE TITLE
Weekly and Daily XP 

### ISSUE THREAD

**Issue by bglaser484** [Bungie-net/api#1098]
My clan used weekly XP as a way to measure the activeness of our members. Since Shadowkeep launched, the weekly progress for the XP character progression is returning 0 XP for **every** one of our members. Did weekly XP get moved somewhere else? Is it no longer a thing? Is this just a bug?
![image](https://user-images.githubusercontent.com/37781441/66719458-0e3da180-edbe-11e9-98c1-46aad27a25f6.png)

**Comment by vthornheart-bng** [comment]
We'll have to look into this one.

**Comment by bglaser484** [comment]
> Does it work with progression hash `3298204156`?

No, as that's XP towards the season rank. If a player gets to rank 100, the XP from `3298204156` will return 0 as well.

**Comment by bglaser484** [comment]
> We'll have to look into this one.

Any update on this?

**Comment by dcaslin** [comment]
Was about to file a new issue and noticed this one. I'm seeing reports of this as well. I have a dedicated user that was tracking this and notifying me in real time and he discovered that weekly XP seems to have reset to zero today during daily reset. https://twitter.com/samuelldrew/status/1213873564044210177

I can definitely confirm that my personal account, 1/4611686018434964640 reset back to zero on all progressions today at reset as well.

**Comment by vthornheart-bng** [comment]
Hmm, I'm going to hit someone up on the game side as it looks like this is a problem further downstream.  I just checked the raw data on your account and, indeed, the weekly progress is at 0 - if you had made progress this week (I assume that you did, just to make sure?), then this value doesn't look right to me but I don't have the ability to pull the correct value without a game side fix.

**Comment by dcaslin** [comment]
Thanks for looking! Can confirm I made progress this week. 

FWIW I actually conveniently have an approximate Twitter timestamp between: 

8:07PM EST on 1/3: https://twitter.com/D2Checklist/status/1213304027368300544

and 

10:39 PM EST on 1/3: https://twitter.com/D2Checklist/status/1213304027368300544

wherein I turned in 36 bounties, which was worth ~500K XP. At the moment my account shows 200K XP for the week (which matches other reports of b/c I haven't played as much since Sunday)

**Comment by vthornheart-bng** [comment]
Sweet, this is good info - thank you very much!

**Comment by dcaslin** [comment]
Btw, I read back through these comments and suspect the original October report and this new one may actually be different issues. I can pretty confidently guess that the weekly reset issues that I'm describing arose on or after the Season of Dawn release. (Didn't want to give false impressions to anyone debugging on the Bungie side)
