### ISSUE TITLE
Many new mods including the artifact ones incorrectly have a semi opaque trim 

### ISSUE THREAD

**Issue by NigelBreslaw** [Bungie-net/api#1099]
For example https://data.destinysets.com/i/InventoryItem:4088080601 should not have the semi transparent pixels all the way to the edge. It should be clipped to just the shape of the mod. I had a look at the files in the PC game dump and they are correct there e.g.
![01a3-00002367](https://user-images.githubusercontent.com/1957186/66740351-9f268280-ee7b-11e9-90e2-03ea32736328.png)

Im not sure I am explaining it well. Basically the mod should be there, but the pixels around it should be 100% transparent, but they are not.

So I wonder if it is just a bug as they get exported? It stops it being possible to make a pixel perfect Artifact UI with the API graphics 😭

**Comment by justrealmilk** [comment]
![01A3_12DB_00](https://user-images.githubusercontent.com/156681/66769155-c15de600-eef7-11e9-98c9-cb93a4accc59.png)

This is a white image link.

I know it's not most the performant option, but I stumbled across a PNG that could perhaps be used as a mask?

**Comment by vthornheart-bng** [comment]
I'm going to have to ask people about this one.  May potentially be something in our import pipeline, but if it's not then there may not be much we can do about.
