### ISSUE TITLE
Freelance Survival: Missing Icon

### ISSUE THREAD

**Issue by t3rr11** [Bungie-net/api#1100]
It seems the new Freelance Survival activity definition (740891329) has no icon:
![image](https://user-images.githubusercontent.com/2139233/66786972-b02dcd00-ef29-11e9-8397-86dc378cc71a.png)

I think it might have been glanced over as the new raid (2659723068) and vex offensive (2999911583) activity definitions both have icons.

**Comment by vthornheart-bng** [comment]
Sweet, thank you for this report!  We'll have to give it a look - it may be a game-side content issue, but if it is we may end up having to wire something up to fix it manually.  It's worth a look either way!
