### ISSUE TITLE
Emblem Archivist's Prize missing secondaryOverlay and secondarySpecial properties

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1101]
The emblem _Archivist's Prize_ is missing secondaryOverlay and secondarySpecial properties resulting in:

![image](https://user-images.githubusercontent.com/156681/66805725-1259f280-ef69-11e9-939a-9f5224675dd5.png)

It's not redacted - I think it's a code-redeemed emblem (new with Shadowkeep) and that these properties simply haven't been linked up.

https://data.destinysets.com/i/InventoryItem:2526736323

**Comment by floatingatoll** [comment]
That specific emblem appears to bugged in-game as well, reports one player who has it from Anthology book 2:

https://imgur.com/4YVKxfk

**Comment by jshaffstall-bng** [comment]
Good catch, unfortunately this is a game content issue, and it looks like it won't be fixed until the release of the next season. Sorry!

Logged in TFS as bug 840699.
