### ISSUE TITLE
[QUESTION] Is it possible to know plug is related with masterwork

### ISSUE THREAD

**Issue by atheon-v** [Bungie-net/api#1102]
Hi! Hope someone already had this task and can help me find way to separate masterwork plugs(Tier 1/2/3/.. Weapon, Masterwork, Upgrade Armor)? For example this one - https://data.destinysets.com/i/InventoryItem:3020065863
And same case for exotic catalyst items - https://data.destinysets.com/i/InventoryItem:2085058762

**Comment by delphiactual** [comment]
plug.plugCategoryIdentifier

**Comment by atheon-v** [comment]
Thanks, @delphiactual !
Do you mean just check if "v460.plugs.armor.masterworks.stat.resistance_3" contains "masterwork" string or there is any relation/definition of "v460.plugs.armor.masterworks.stat.resistance_3"?

**Comment by delphiactual** [comment]
Check for the substring

**Comment by atheon-v** [comment]
Ok, got it! Thanks again!
