### ISSUE TITLE
Shadowkeep Triumph Issues

### ISSUE THREAD

**Issue by t3rr11** [Bungie-net/api#1104]
So throughout my time working with the Bungie API I've learnt a few things. Since the introduction of forsaken the triumphs endpoint has been one of my favorite things to work with. It provides so much detail about the game and so much detail tracking pretty much every aspect of the game. When black armory came out. There weren't many (if any) triumphs to track things that came with that DLC, the triumphs added were very limited and when looking for new niche things to work with i was left a little disappointed. But i kept on going! Things got better and the triumphs to track black armory things came and so did more triumphs with events, it was great again! Come Shadowkeep i've noticed quite a few changes in triumphs, new categories, many many new triumphs, multiple tier level triumphs. It's been fun to work with and i will continue to do so.

The main point of the issue is to note a few things that i'm hoping could get fixed or added or even just explained. 

Firstly, I use the records from the PresentationNode: `1256609117` to track the completions of strikes (excluding the other records in there). My issue being that the new strikes for Shadowkeep have not been updated in that PresentationNode possibly due to there being no triumphs attached to the completion of those new strikes. I was wondering if new triumphs could please be added.
![image](https://user-images.githubusercontent.com/2139233/66910343-ecf6e280-f055-11e9-927e-e11d278fcd7a.png)

Secondly, I use triumphs to also track the completion of raids but also to determine if that person has completed the flawless as that also is a triumph (Like a diamond, etc). Now the issue here is that the new Shadowkeep raid, whilst it does have a triumph it for some reason is not a profileRecord triumph but a characterRecord triumph which does not keep the constancy of the other raids. Why? Really is my main question. (But it would be great if this was changed as well)
![image](https://user-images.githubusercontent.com/2139233/66910828-dc933780-f056-11e9-831f-457dc3d3b824.png)

Thirdly, I just wanted to note that i love the triumph endpoint, It has allowed me to do so much and to go so far with my projects. I understand it may not be a priority over content but i'd love the addition of more triumphs with future updates and events, I'll be using them all in some way or another! 😄

**Comment by vthornheart-bng** [comment]
Good questions and input, I greatly appreciate it!  I'm also glad that you've gotten good use out of the Triumphs data!

I will have to ask the folks that make the triumphs data about those first two questions.  I'll see what I can find out!

**Comment by vthornheart-bng** [comment]
The latter looks to definitely be a bug in how we determine the scope of some records.  I will check on this and see what can be done!

**Comment by t3rr11** [comment]
Thanks for checking it out!

**Comment by vthornheart-bng** [comment]
I've got a bug filed for the latter - the former, I talked to someone and it sounds like the plan going forward is that there's not going to be a Triumph for individual Strike completions anymore unfortunately.  Sorry about that!

**Comment by t3rr11** [comment]
Ahh darn, no worries. If you think up another way to track individual strikes i'll happily change up my code, as for now i'll discontinue the strike specific completions log for consistency. I've been getting quite a few messages informing me that i haven't added the new strikes yet, easier to remove than to explain many times over haha

**Comment by EdgarVerona** [comment]
Aye, totally understandable.  I wish I had better news on that front!

**Comment by t3rr11** [comment]
The second issue with the triumphs being characterRecords rather than profileRecords has been fixed. The Garden of Salvation triumph is now a profileRecord triumph. I've also noticed that you even went and fixed the MMXIX seal triumph which was located under characterRecords also. It to has been moved to profileRecords. 

Thank you so much for this quick fix as always! <3

**Comment by t3rr11** [comment]
"Season 8: Valor Legend" triumph was also moved from characterRecords to profileRecords. (for anyone wondering where it went)

**Comment by EdgarVerona** [comment]
Yes!  In trying to find ways to optimize the "fake" plug sets, I came up with a new algorithm for determining what entities are actually account-based rather than character-based, and it managed to capture a few Triumphs that were miscategorized as a beneficial side effect!

**Comment by t3rr11** [comment]
Well that worked out great haha!
