### ISSUE TITLE
Dolphin emoji is shown instead of [Medium blocker]

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#1105]
In Objective 3792840449 (Medium Blockers, from the "Blockade" bounty https://data.destinysets.com/i/InventoryItem:552709552/Objective:3792840449), the Medium Blocker icon is not replaced with its textual format as most others are.

<img width="556" alt="Screenshot 2019-10-18 at 5 23 02 pm" src="https://user-images.githubusercontent.com/46142/67111013-f5712980-f1cb-11e9-96d8-185fb50a9211.png">

The result of this is that it shows as a dolphin emoji, for better or worse 

![Image from iOS](https://user-images.githubusercontent.com/46142/67111140-3d904c00-f1cc-11e9-99a3-2c9e46de52a6.png)

**Comment by vthornheart-bng** [comment]
Fixed: Medium blockers now referred to in game as dolphins.

;) I'll file a bug to take a look!

**Comment by sundevour** [comment]
it's a private use character, the whale being rendered there is decided by whatever device or application you're viewing it in

the API already uses private use characters for weapon types in objective descriptions, in non-latin-character set manifests, so though this one doesn't match the other two blocker descriptions, it's not completely unusual for the API and definitely not a whale

**Comment by sundevour** [comment]
still the most hilarious API quirk yet

**Comment by justrealmilk** [comment]
idk sun it looks whalely like a whale to me

**Comment by sundevour** [comment]
tom life as an Apple user must be harrowing
