### ISSUE TITLE
Vendors return empty and flag as private

### ISSUE THREAD

**Issue by samyjwv** [Bungie-net/api#1107]
The Vendors endpoint it's return empty and flag as privacy 2 (private) in some characters not all.

This occurs to 1/3 of my characters.

> Settings > Privacy > Bungie.net Privacy

All checked.
![](https://i.imgur.com/WCeeYrG.png)

> Logs

{"Response":{"vendorGroups":{"data":{"groups":[]},"privacy":2},"vendors":{"data":{

**Comment by floatingatoll** [comment]
Have those characters logged in since Shadowkeep?

**Comment by samyjwv** [comment]
> Have those characters logged in since Shadowkeep?
Yes they have.

![](https://i.imgur.com/BWPU2NG.png)

The Hunter and Titan characters was transfer from Blizzard Client.
The Warlock char was created already in Shadowkeep.

This only happens on my Warlock.

Other people are report the same issue:
https://www.reddit.com/r/DestinyItemManager/comments/djp4u2/vendors_tab_is_blank/f4aadiv/
https://github.com/DestinyItemManager/DIM/issues/4436

If you need more information for debug, just let me know.

**Comment by floatingatoll** [comment]
Could you link to the Bungie.net profile for any of these characters? It has various useful IDs in it that may help diagnosis.

**Comment by samyjwv** [comment]
Profile Id: 21180428
https://www.bungie.net/en/Profile/254/21180428/Sammy

Hunter
https://www.bungie.net/en/Gear/3/4611686018476646711/2305843009465364303

Titan
https://www.bungie.net/en/Gear/3/4611686018476646711/2305843009464934541

Warlock (char that occurs)
https://www.bungie.net/en/Gear/3/4611686018476646711/2305843009510675093

**Comment by vthornheart-bng** [comment]
Logged as TFS 842434 for me to investigate!

**Comment by vthornheart-bng** [comment]
Quick question @samyjwv - that Warlock character who was created after New Light debuted: is that character able to reach the Tower?  (as in, have you gotten through that initial mission with them?)

**Comment by criscofats** [comment]
> 
> 
> Quick question @samyjwv - that Warlock character who was created after New Light debuted: is that character able to reach the Tower? (as in, have you gotten through that initial mission with them?)

I know you didn't ask me, but my only character is a new light character that this occurs on and they can reach the tower.
https://www.bungie.net/en/Gear/3/4611686018489329510/2305843009504534148

**Comment by vthornheart-bng** [comment]
Mmm, good to know.  I think I see what's going on here - I'm testing a fix locally now.  Not going to make it in time for tomorrow's deployment, but hopefully the deployment after if all goes well.  Indeed as you folks suspected, it has to do with the change in what is accessible to a new character and how that's checked with New Light!

**Comment by samyjwv** [comment]
> Quick question @samyjwv - that Warlock character who was created after New Light debuted: is that character able to reach the Tower? (as in, have you gotten through that initial mission with them?)

Yes, its able to reach the Tower, but i don't recall if was through initial quest or it's already available.

Like @criscofats it's only occurs on the new light character.

Good to know you are on right path.

**Comment by samyjwv** [comment]
It's fixed.
Thank you.

**Comment by vthornheart-bng** [comment]
Glad it worked out - thank you for reporting it!
