### ISSUE TITLE
Quest Step Items Missing Main Questline DisplayProperties

### ISSUE THREAD

**Issue by lowlines** [Bungie-net/api#1108]
Recently all new quests keep a copy of the setData property that used to be found on the main questlineItem, but this has resulted in there no longer being any info about the main quest with regards to displaying it in a similar manner to how it is in-game.

Eg. "Bounty Season" is a questline present in Shadowkeep however there is no way to return this top level info from any of the quest steps.
[https://data.destinysets.com/i/InventoryItem:3306947316](https://data.destinysets.com/i/InventoryItem:3306947316)

I reckon the setData property needs a displayProperties property that has the questline display info.

**Comment by jshaffstall-bng** [comment]
Yep, hopefully this won't be too tricky to add.

**Comment by joshhunt** [comment]
I noticed this with a few of the new quests, where the data explorer links to itself as the questline "parent" and I was really confused, but not really enough to investigate what's going on...

**Comment by justrealmilk** [comment]
@joshhunt this is where we all went when we couldn't work out what was wrong in our own apps.

**Comment by jshaffstall-bng** [comment]
This is filed internally as TFS bug 841614.

**Comment by jshaffstall-bng** [comment]
Good news, the 'questLineName' will be added to the itemDefinition.setData with the content update on 10/29. Enjoy!

**Comment by justrealmilk** [comment]
Is there a single quest line item that all of these items are linked to?

**Comment by lowlines** [comment]
Old quests will have `questLineName` empty so I'd suggest doing a check to see if the questlineItemHash is the same as the quest step hash and handle it accordingly.
