### ISSUE TITLE
Question: CORS request did not succeed for Browser Based Apps

### ISSUE THREAD

**Issue by juwanpetty** [Bungie-net/api#1109]
Hello! 

I filled out the Origin Header section where we register our application:
<img width="858" alt="Screen Shot 2019-10-20 at 2 11 25 PM" src="https://user-images.githubusercontent.com/10606336/67163996-d3021c00-f343-11e9-86a7-c0550d692223.png">

Though when I hit the `https://www.bungie.net/Platform/App/OAuth/Token/` endpoint: 
<img width="894" alt="Screen Shot 2019-10-20 at 3 28 00 PM" src="https://user-images.githubusercontent.com/10606336/67165008-4577f980-f34e-11e9-83ed-58c855f20f25.png">

I'm getting a `Cross-Origin Request Blocked` error in the console:
<img width="538" alt="Screen Shot 2019-10-20 at 3 29 20 PM" src="https://user-images.githubusercontent.com/10606336/67165024-76582e80-f34e-11e9-983e-34c58d187720.png">
<img width="551" alt="Screen Shot 2019-10-20 at 3 32 51 PM" src="https://user-images.githubusercontent.com/10606336/67165078-e9fa3b80-f34e-11e9-89de-a4609acbe008.png">

Don't know what I'm doing wrong here. Any help appreciated.

**Comment by juwanpetty** [comment]
I removed the `X-API-Key` from the header

**Comment by andyschott** [comment]
You need `X-API-Key` in the header for the requests to succeed.

Assuming you're just developing locally for now, I think it's safe to set the origin header to `*`. Once you deploy your code to the internet you'd want that to match your domain name, of course.

**Comment by floatingatoll** [comment]
I thought Bungie doesn’t allow * in the site admin settings?

**Comment by juwanpetty** [comment]
@andyschott I added back the `X-API-Key` and changed the Origin Header to: `*`
I'm still getting a `307 | Temporary Redirect`

**Comment by andyschott** [comment]
@floatingatoll I've used it frequently, but I'm using the keys in a server app, not a browser based one. Maybe that's the difference?

@juwanpetty I'm not sure what else to suggest - I haven't personally seen that error. :( Maybe someone else here will have some ideas.

**Comment by delphiactual** [comment]
add the trailing `/` to `Token`

**Comment by juwanpetty** [comment]
@delphiactual That fixed my problem, thanks!
