### ISSUE TITLE
Spec version not incremented with new release

### ISSUE THREAD

**Issue by vpzed** [Bungie-net/api#111]
The version inside the specs after the new release is still 2.0.0.  Since changes were made I would have expected it to increment at least to 2.0.1.

     },
      "version": "2.0.0"
     },

**Comment by vthornheart-bng** [comment]
Ah, yeah, good call.  I tossed that version number in somewhat haphazardly.  Hmm... I'll have to look into connecting it to something that's more likely to be automatically updated in the future.
