### ISSUE TITLE
Season rank (1628407317) incorrectly capped at 100 in API

### ISSUE THREAD

**Issue by dcaslin** [Bungie-net/api#1110]
For example, this user (at time of filing this issue) is at 117 in game, but API reports 100 for progression 1628407317. 

Platform: 1 (XBox)
Member id: 4611686018430177680

**Comment by justrealmilk** [comment]
I was literally wondering how we handle > 100 this afternoon. Would love it if all we needed to do was wait for an API change!

**Comment by dcaslin** [comment]
FWIW same users companion app now shows 119. I searched the Progressions component of his GetProfile for "119" and didn't see anything, so either there's another public endpoint that's reporting > 100 that I don't know about or the companion is doing some black magic.

**Comment by jshaffstall-bng** [comment]
Hey yeah, this is a little confusing. The regular season 8 rank progression goes up to level 100 and has all of the reward items (hash 1628407317). But after 100, it swaps to the 'prestige' progression for higher ranks (hash 3184735011).

You should be able to get the 'prestige' progression hash off of the season pass definition.

**Comment by dcaslin** [comment]
Note for anyone else that stumbles here, the prestige progression and regular progression are documented in the DestinySeasonPassDefinition in the manifest.
