### ISSUE TITLE
Breakthrough listed as competitive game mode

### ISSUE THREAD

**Issue by mikechambers** [Bungie-net/api#1112]
https://www.bungie.net/Platform/Destiny2/1/Account/4611686018488857462/Character/2305843009491344202/Stats/Activities/?mode=5&count=200&page=0

Search in results for reference id 2748633318 which is a Breakthrough game. The modes type contains 69 (PVPCompetitive):

```"period": "2019-10-23T10:56:03Z",
"activityDetails": {
    "referenceId": 2748633318,
    "directorActivityHash": 3011324617,
    "instanceId": "4975001329",
    "mode": 65,
    "modes": [
        5,
        69,
        65
    ],
    "isPrivate": false,
    "membershipType": 1
},
```

It should not list 69, as it does not reward glory and is not in the competitive mode.

**Comment by vthornheart-bng** [comment]
Ah, thank you!  Fixing that up for next deployment!
