### ISSUE TITLE
~11/12 - The manifest will start including Destiny definitions per-type

### ISSUE THREAD

**Issue by hellocontrol-bng** [Bungie-net/api#1113]
Related: #785 

**EDIT**: This is for JSON only

For the deployment after our 10/29 deployment, we plan to include new paths to JSON definition files in the manifest. These will be per-type, in addition to the existing aggregate JSON file we serve now.

The filenames will be in the format `DefinitionType-guid.json` (e.g. `DestinyInventoryItemDefinition-7b3e5ed6-3e9d-49a0-97c3-47ce4a20469c.json`). You'll be able to get at them in the new `jsonWorldComponentContentPaths` in the manifest:

```
{
    "Response": {
        "jsonWorldContentPaths": {
            "en": "/common/destiny2_content/json/en/aggregate-7b3e5ed6-3e9d-49a0-97c3-47ce4a20469c.json",
           ...
        "jsonWorldComponentContentPaths": {
            "en": {
                "DestinyEnemyRaceDefinition": "/common/destiny2_content/json/en/DestinyEnemyRaceDefinition-7b3e5ed6-3e9d-49a0-97c3-47ce4a20469c.json",
            ...
	...
    ...
}
```

These are available for all the existing definitions that appear in the aggregate file. The aggregate file won't go away - it will be accessible using the same `jsonWorldContentPaths` property as before.

**NOTE**
Additionally, you'll see a new, special file listed called `DestinyInventoryItemLiteDefinition`. These definitions are identical to the item definitions, but a few of the properties are stripped. This is to reduce download size for users. It is important to know that this property is experimental and currently very much catered to our specific needs. It is available to you, but anyone using it should understand that it is highly likely to change without warning. **Use at your own risk**!

**Comment by justrealmilk** [comment]
Any chance it'll include DestinyHistoricalStatsDefinition?

**Comment by t3rr11** [comment]
> Any chance it'll include DestinyHistoricalStatsDefinition? "And that detective is the right question"

**Comment by bhollis** [comment]
Very very exciting. 

Will the lite version be documented? I’d love to figure out whether we could use it.

**Comment by hellocontrol-bng** [comment]
> Any chance it'll include DestinyHistoricalStatsDefinition?

At this point, it will not - that is a pretty different thing, so it'd be a different exploration.

**Comment by hellocontrol-bng** [comment]
> Will the lite version be documented? I’d love to figure out whether we could use it.

Most likely not for the initial launch - it's a special snowflake that doesn't really follow the normal rules and thus it will not be caught by the documentation generator. That said, if it is trivial to include, we may do so in the future.

**Comment by ckhicks** [comment]
Really, really love this direction. Thank you in advance!

**Comment by sgtfrankieboy** [comment]
>Any chance it'll include DestinyHistoricalStatsDefinition?

Isn't it already available at the Destiny2.GetHistoricalStatsDefinition endpoint?

**Comment by riceOtaku** [comment]
This looks like a huge QOL improvement. I am working on my first bungie API-based app and after having read documentation, and seeing these json paths in my first manifest response, I was pretty excited.
