### ISSUE TITLE
GetMembershipFromHardLinkedCredential returns HTML on invalid input

### ISSUE THREAD

**Issue by mikechambers** [Bungie-net/api#1115]
https://www.bungie.net/Platform/User/GetMembershipFromHardLinkedCredential/12/STEAM_0%3A0%3A24828187/

Note, using the regular Steam ID and not the Steam 64 id. This returns an HTML page from the server, and not a standard JSON error page that other apis return. It should return a standard JSON error

This makes it difficult to capture and parse the error message.

Returned error below:

```
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8" />
	<title>Bungie.net: 400 Bad Request</title>
	<link type="text/css" rel="stylesheet" href="/css/error.css" />
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
</head>

<body>
	<header>
		<a id="logo" href="/"></a>
	</header>
	<div class="container">
		<h1>400: Bad Request</h1>
		<div class="message">
			<p>
				What were you looking for again? Whatever it was, you won’t find it here. <br /><br />

			Click the back button to go slowly back out of this room. <br /><br />
		</p>

		</div>
		<div class="footer">
			<p>
				This error has automatically been logged and we are aware of your plight.<br />
				<br />
			HTTP Client Error; 400 Bad Request

		</p>
		</div>
	</div>
</body>

</html>
```

**Comment by vthornheart-bng** [comment]
Ah, thanks for reporting this!  I'll add it to the backlog.

**Comment by vthornheart-bng** [comment]
Something I should note though, this endpoint requires you to enter the user's numeric steam ID.

STEAM_0%3A0%3A24828187

Looks like a URL encoded string with numbers at the end, but either way this request will fail.  Double check what's building up the URL for your request, and make sure it's the numeric identifier for the account!

**Comment by vthornheart-bng** [comment]
Ah yeah - SteamID64 specifically.

**Comment by mikechambers** [comment]
Yeah, I am taking user input, and they sometimes enter the wrong steam ID format. I explicitly check for STEAM on the client side now, so that doesn't go to the server, but the original request is still valid in case they enter in the wrong steam id or format (or even their nick name).

**Comment by vthornheart-bng** [comment]
Totally agreed!  Just wanted to check with you in case there was anything happening on your side where it was automatically pushing the wrong ID.

**Comment by mark1973ryan** [comment]
A call to:
https://www.bungie.net/User/GetMembershipFromHardLinkedCredential/SteamId/76561197974365107/

Gives a 404 page:

<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8" />
	<title>Bungie.net: 404 Page Not Found</title>
	<link type="text/css" rel="stylesheet" href="/css/error.css" />
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
</head>

<body>
	<header>
		<a id="logo" href="/"></a>
	</header>
	<div class="container">
		<h1>404: Page Not Found</h1>
		<div class="message">
			<p>
				Sorry, the page you're looking for has moved or been incinerated.<br /><br />
			</p>
		</div>
		<div class="footer">
			<p>
				This error has automatically been logged and we are aware of your plight.<br />
				<br />
				HTTP Client Error; 404 Page Not Found

			</p>
		</div>
	</div>
</body>

</html>

That is definitely my Steam64 ID

steamID: clipboardSTEAM_0:1:7049689
steamID3: [U:1:14099379]
steamID64: 76561197974365107
name: Valan
profile: http://steamcommunity.com/profiles/76561197974365107

**Comment by justrealmilk** [comment]
>A call to: ...

@mark1973ryan check the path you’re requesting, most if not all API requests start with /Platform/
