### ISSUE TITLE
Nightfall Ordeal Display Properties Inconsistencies 

### ISSUE THREAD

**Issue by lowlines** [Bungie-net/api#1116]
So it looks like Nightfall Ordeals set the original activity name to `description`.
https://data.destinysets.com/i/Activity:2021103427

Whereas the old Scored Nightfalls set it to the `selectionScreenDisplayProperties.name`.
https://data.destinysets.com/i/Activity:3034843176

Would it be possible to get a `Nightfall Ordeal` activityModeType so one could conditionally grab the original activity name?

**Comment by vthornheart-bng** [comment]
Cool, added that to the backlog!
