### ISSUE TITLE
All bungie.net copy text is spaced incorrectly

### ISSUE THREAD

**Issue by floatingatoll** [Bungie-net/api#1120]
FWIW, the latest update to Bungie.net seems to have broken styling site wide. It's due to the introduction of the Symbols PC font into text content that isn't symbols, as shown in the attached screenshots. I don't know what the underlying cause of that introduction is, but the fix is apparent and immediate when made. I noted in the CSS that there's various clauses that seem designed to set that font _only_ on symbols that can use it, but with a _different_ font name, so maybe there's some sort of mishmash/overlap to be worked out here.

<img width="1155" alt="Screen Shot 2019-10-29 at 10 03 28" src="https://user-images.githubusercontent.com/92684/67790847-b052c000-fa33-11e9-93b3-161c15b83234.png">

<img width="1158" alt="Screen Shot 2019-10-29 at 10 03 40" src="https://user-images.githubusercontent.com/92684/67790859-b779ce00-fa33-11e9-9bca-2a23d4042c1c.png">

**Comment by vthornheart-bng** [comment]
Ah, thanks for the report!  I'm bubbling it up.
