### ISSUE TITLE
return ornamentHash as a separate property

### ISSUE THREAD

**Issue by marquesinijatinha** [Bungie-net/api#1122]
Now that Destiny 2 is using the ornament icons in game to reflect the currently equipped ornament, it would be useful to have the ornament hash being returned as an item or instanceInfo property instead of digging through sockets to find the current ornament.

**Comment by bhollis** [comment]
This will be present under `overrideStyleItemHash` (though it's not limited to ornaments - it also applies to things like emblem variants).

**Comment by marquesinijatinha** [comment]
nvm then, it already works for the same purpose
