### ISSUE TITLE
Non-selected perks missing from class items

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#1123]
Thank you so much for updating the API to restore full perk info. Unfortunately, unless I'm missing something, Armor 1.0 class items still aren't showing their non-selected perks:

![image](https://user-images.githubusercontent.com/313208/67828652-731d1b00-fa91-11e9-8b42-27424b61ce1d.png)

**Comment by vthornheart-bng** [comment]
Hmm, I'll take a look in there.  Just to make sure - are you checking both reusablePlugs and plugSets for the data?

**Comment by bhollis** [comment]
Yup we’re looking at both the plugsets and the reusable plugs.

**Comment by wickles** [comment]
I'm seeing the same behavior with Y1 weapons. 

![2019-11-11 18_57_52-ShareX-chrome](https://user-images.githubusercontent.com/4229542/68635361-85e21780-04b5-11ea-87a3-351d37a3941c.png)

**Comment by bhollis** [comment]
I don't really care about this anymore now that armor 2.0 class items don't have perks generally
