### ISSUE TITLE
overrideStyleItemHash often has the defaultOrnament hash

### ISSUE THREAD

**Issue by NigelBreslaw** [Bungie-net/api#1125]
Items that support ornaments, but don't have one applied are still returning a overrideStyleItemHash such as  "2931483505", "702981643" and "1959648454" which is just the default plug. I can filter them out but it might future proof things if these were not returned. Also save you a bit of data.

**Comment by vthornheart-bng** [comment]
Ah, I believe Shaffstall recently checked in a fix for this.  Hopefully we should have this for the next deployment!

**Comment by bhollis** [comment]
@NigelHietala in DIM we write:

```
if (overrideStyleItem && overrideStyleItem.plug && overrideStyleItem.plug.isDummyPlug) {
  overrideStyleItem = null;
}
```
