### ISSUE TITLE
Could we get a table of \1f4f to “icon font” mappings in the manifest database?

### ISSUE THREAD

**Issue by floatingatoll** [Bungie-net/api#1127]
The new API update is publishing the custom icons as raw Unicode characters, such as U+1F4F and similar. This is super awesome, thank you for making this change! Could you add a table to the manifest database that simply lists the characters in the icon font and what their non-localized label is? I noticed in site.css that they’re all present as a generated list, and so I’m hoping we could get that same list without much work so that we know what characters to display with the custom font, and what they mean in API terms.

For example, that table would contain an entry “F12D” => “destinyuiunlocked” – it doesn’t so much matter what the label is, it just matters that we know it’s a thing to replace:

```.icon-destinyuiunlocked:before {
    content: "\f12d";
}

.icon-destinyvendorcruible:before {
    content: "\f147";
}

.icon-destinyvendorengram:before {
    content: "\f148";
}

.icon-destinyweapontypearc:before {
    content: "\f12e";
}

.icon-destinyweapontypekinetic:before {
    content: "\f12f";
}```

**Comment by vthornheart-bng** [comment]
Hmm, I think those were manually crafted by folks working on the UI.  But it would be nice to have a single identifier for both.  I'll file a bug and talk to folks about it: I was just talking to someone this morning about exposing our Symbol-to-Localized Text mappings, but that is automatically generated and thus doesn't include these manually crafted identifiers in them.  But perhaps they could if we change some things around!

**Comment by floatingatoll** [comment]
At worst, just a table listing the U+1F4F would be fine :)

**Comment by vthornheart-bng** [comment]
Sweet - yeah that we can definitely provide.  Internally before we build out the content databases, we build our own table of symbols to localized text, which we don't expose (because I didn't think anyone would actually care about it!): but I can get that piped out so that you folks can use it!  Just a matter of when I can loop around to it.  I've got it in our backlog now.
