### ISSUE TITLE
Exotic catalyst objectives are wrong

### ISSUE THREAD

**Issue by dcaslin** [Bungie-net/api#1128]
All the completion values seem to be one and the progress is some seemingly arbitrary number. For example take my Jade rabbit. It has a kill enemies objective: https://data.destinysets.com/i/Objective:73837075

My triumph looks correct, showing 1/1 on catalyst insertion and 223/250 for crucible kills.

![image](https://user-images.githubusercontent.com/16437968/67917343-142dd380-fb6f-11e9-8e3e-e801c2e7e986.png)

However on the plug object it shows me as "8/1". 

![image](https://user-images.githubusercontent.com/16437968/67917229-c9ac5700-fb6e-11e9-87e2-13697610e981.png)

All other catalyst objectives I've checked also show a completionValue of 1 and progress values that don't appear to correlate with the Trumphs at all.

**Comment by vthornheart-bng** [comment]
Hmm, I'll need to look into that - the in-game UI for catalyst plugs should be driven the same way as all other plug objectives, in that it'd use the objective string/progress data to show progress.  This implies to me that there's some extra transformation happening on that plug objective data that we're not accounting for, something only being used by catalysts.

I'll file a bug.
