### ISSUE TITLE
Some collectibles store the sourceString in the displayProperties.description

### ISSUE THREAD

**Issue by lowlines** [Bungie-net/api#1129]
Just some inconsistencies here where the `sourceString` is stored in the `displayProperties.description`. Seems to be tied to emblems?

ie
https://data.destinysets.com/i/Collectible:2386408655

**Comment by vthornheart-bng** [comment]
Unfortunately we don't have direct control over that data.  But I will hit up some folks who do, and see if it would be possible to change that around.
