### ISSUE TITLE
HistoricalStatsForAccount has no Mode support

### ISSUE THREAD

**Issue by mistahj67** [Bungie-net/api#113]
There is no way to obtain account based stats on a per mode basis. Currently the only route I see is to hit the GetActivityHistory endpoint for each individual characterId. This will quickly become an issue as people delete characters and their list of characterIds increase.

"
GetActivityHistory or similiar version in D1 that allowed for stats by activity for account. It looks like the D2 GetActivityHistory only accepts 1 characterId. In the D1 endpoint we could do something like this:   /d1/Platform/Destiny/Stats/{MembershipType}/{MembershipId}/{CharacterId}/?modes=4&periodType=3&definitions=false Where we would be able to obtain account data for modes by supplying a 0 in place of the characterId
"

**Comment by vthornheart-bng** [comment]
Good call, I'll look into this.

**Comment by Tetron-bng** [comment]
You can use GetActivityHistory  and specify character ID 0 to get all characters.

**Comment by mistahj67** [comment]
When I try that ID 0, I received an empty response. 
{
    "Response": {},
    "ErrorCode": 1,
    "ThrottleSeconds": 0,
    "ErrorStatus": "Success",
    "Message": "Ok",
    "MessageData": {}
}

**Comment by Tetron-bng** [comment]
Sorry, you are right. I was looking at the GetHistoricalStats() endpoint.  Currently there is not a way to get activity history for an account without regard for character.
