### ISSUE TITLE
DestinyItemComponentSetOfint64.stats does not seem to include Armor 2.0 Class item stats.

### ISSUE THREAD

**Issue by ryan-rushton** [Bungie-net/api#1132]
I was expecting DestinyItemComponentSetOfint64.stats.data to include values for Armor 2.0 class items, particularly ones that stat effecting mods. They don't seem to be present in any of the responses I have investigated.

**Comment by vthornheart-bng** [comment]
Ah, thanks for the report - I'll need to look into this!

**Comment by vthornheart-bng** [comment]
TFS 846772
