### ISSUE TITLE
Some quest starters not accessible until picked up from vendors

### ISSUE THREAD

**Issue by lowlines** [Bungie-net/api#1133]
So it looks like there might be some quest starters which you cannot get any information about them until you visit the vendor. Even polling that vendor's inventory will not provide you with this information.

ie https://data.destinysets.com/i/InventoryItem:3398477426
This quest will be active when you inspect Master Rahool at the Tower before talking to him however there is no hidden item in your inventory nor does it get returned when you request his inventory. My guess it that the quest step lives inside a vendor interaction that isn't picked up by the API?

**Comment by lowlines** [comment]
Here's another one from Ikora for doing all the Y1 exotic quests.
https://data.destinysets.com/i/InventoryItem:998190725

**Comment by vthornheart-bng** [comment]
Hmm, good to know!  Thank you, we'll have to give this a look!

Would there be an ideal place you'd like to see this - perhaps in Milestones (though I hesitate to add more to Milestones: perhaps more appropriately, would you rather see this aggregated into a component that relays information about available quests?)

**Comment by lowlines** [comment]
Currently I'm merging Milestones, Available Activities and Quest Steps that are either in your pursuits or in a hidden bucket in your inventory. I think seeing available/abandoned quests from vendors without having to poll them individually would be helpful.

**Comment by vthornheart-bng** [comment]
Definitely good to know, thank you!

**Comment by vthornheart-bng** [comment]
I'm filing a bug for it, I definitely think this would be useful!
