### ISSUE TITLE
Scourge of the Past raid has no dummy rewards

### ISSUE THREAD

**Issue by lowlines** [Bungie-net/api#1135]
All other raids appear to have some level of potential rewards in their definitions but not the Fallen raid.

https://data.destinysets.com/i/Activity:548750096
https://data.destinysets.com/i/Activity:2812525063

**Comment by vthornheart-bng** [comment]
Unfortunately, this particular set of data is sourced from the game itself, and because that raid's pretty old now I don't think they're going to actually update it if we request it.
