### ISSUE TITLE
Add Steam IDs to GetBungieNetUserById and GetMembershipDataById.

### ISSUE THREAD

**Issue by StormTester** [Bungie-net/api#1137]
It would be invaluable for these endpoints to output steam IDs so that services could provide the information to users for LFG purposes, as you can't join people on steam display names.

**Comment by joshhunt** [comment]
It's been mentioned a few times on here before (links not handy), but Steam IDs are considered "private information", and can not be freely published by the API. This is very similar to how on Battle.net the Destiny API wouldn't publish the #4321 numbers in the battle tags.

**Comment by floatingatoll** [comment]
Steam offers a "sign in" workflow that you can integrate into any LFG site – you can see this in use at TRN, for example. You should use that _rather than_ ask users to input a SteamID; for usability, for errorproofing, and to prevent malicious behavior.

**Comment by vthornheart-bng** [comment]
Ooh, that is slick and good to know about!  Thanks for that heads up @floatingatoll!
