### ISSUE TITLE
groupedCategoryHashes filled with `0` for Armor and Weapon Mods categories

### ISSUE THREAD

**Issue by sgtfrankieboy** [Bungie-net/api#1138]
The Armor Mods and Weapon Mods DestinyItemCategoryDefinition are returning buggy data since the 78971.19.10.29.0845-9 manifest update.

The `groupedCategoryHashes` property has multiple entries with a hash of 0 instead of the proper category hashes, which are now missing from that list.

The hashes: `610365472` `4104513227`

**Comment by vthornheart-bng** [comment]
Ah, crap!  Good find, thank you - I'm unsure what happened there, but that must have been a very recent break.  I'll file a bug to investigate.

**Comment by vthornheart-bng** [comment]
Phew, I'm wrong - it's actually a very, very old bug that just happened to not manifest until now.  That's yucky.  I'm going to push for approval to get a fix in for the deployment next week.
