### ISSUE TITLE
PGCRs only being published every 30 minutes

### ISSUE THREAD

**Issue by as-com** [Bungie-net/api#1142]
It seems that PGCRs are only being published every half hour, almost exactly on the half hour. For the time between the half hour marks, there are no new PGCRs to be seen.

Anecdotally this started happening Sunday evening.

**Comment by joshhunt** [comment]
If this is intentional (which would be unfortunate), it would be great to get some guidance around this so we can adjust and take into account rather than spinning on 404s for 20 minutes at a time

**Comment by v-fedorov** [comment]
Looks more like 15 minutes on my end

**Comment by TorKallon** [comment]
It carries. Sometimes it’s 5 minutes, sometimes it is as long as 40 minutes. 

I’d suggest you add a backoff to your code so when you see 404s at a high rate you slow down your requests and only check once every few seconds.

**Comment by vthornheart-bng** [comment]
Unfortunately, Bnet has no control over the rate at which PGCRs publish.  We're at the mercy of the game backend, that throttles it or sometimes encounters bottlenecks that prevent them from being published.  Indeed, the only thing I can recommend is the same thing Tor mentioned - exponential backoff.  We can't provide any guarantee of timeliness for PGCRs, nor consistency in the rate at which they are published.

**Comment by as-com** [comment]
Interestingly, earlier this evening the issue seems to have been resolved. I'll close this issue for now.
