### ISSUE TITLE
Particular membershipId is not returned by searchDestinyPlayer

### ISSUE THREAD

**Issue by ykslebutv** [Bungie-net/api#1143]
This call `/platform/Destiny2/SearchDestinyPlayer/3/bullet/` returns 10 results but this membershipId: `4611686018467781206` is not among them even though it should be.

My first thought was that results are limited to or paginated by 10, but then I found some examples that yield more than 10 results so that's not the case.

**Comment by floatingatoll** [comment]
Is that missing user a Steam user?

**Comment by vtubelsky** [comment]
@floatingatoll yes, it's a steam account (cross save enabled)

**Comment by floatingatoll** [comment]
I don’t suppose they’ve set their profile to private?

**Comment by vtubelsky** [comment]
it is public, `/platform/Destiny2/3/Profile/4611686018467781206/?components=Profiles,Characters` works fine

**Comment by vthornheart-bng** [comment]
Hmm, does the user have any unusual characters in their actual name?  Or is it literally straight up "bullet"?

**Comment by vtubelsky** [comment]
@vthornheart-bng It is just "bullet", nothing fancy.

**Comment by vthornheart-bng** [comment]
Bah, amidst other things going on I forgot to file an actual bug for this.  I'll be doing that shortly.

**Comment by vthornheart-bng** [comment]
TFS 850697

**Comment by ashleypb** [comment]
I have the same issue with a membershipId not appearing, again a steam user, `Eon` maybe just a coincidence but that also returns 10 results but is missing the membershipId `4611686018468670093`
