### ISSUE TITLE
Pyramidion Emblems Missing secondaryOverlay

### ISSUE THREAD

**Issue by Jansten** [Bungie-net/api#1144]
Looking at the four Pyramidion emblems, all of them have the wrong image for their secondaryOverlay.  Instead the transparent icon, what's returned is a white box with no emblem (even when viewed in Photoshop).  The four emblems are:

The Pyramidion
Operation Intrepid
Spiraling into the Infinite
An Inscrutable Amygdaloid Eigenstate

Completely understand that this isn't a high priority, but I wanted to report this as I found it.

**Comment by justrealmilk** [comment]
https://github.com/Bungie-net/api/issues/852

**Comment by Jansten** [comment]
Ugh, not sure why I didn’t find this when I searched. Thanks! Closing this out

**Comment by justrealmilk** [comment]
i mean i'd leave it open to increase visibility
