### ISSUE TITLE
GetCommonSettings returns empty clan banner decals

### ISSUE THREAD

**Issue by BOBRIWE** [Bungie-net/api#1145]
[`.GetCommonSettings`](https://bungie-net.github.io/multi/operation_get_-GetCommonSettings.html#operation_get_-GetCommonSettings) return [`Common.Models.CoreSettingsConfiguration`](https://bungie-net.github.io/multi/schema_Common-Models-CoreSettingsConfiguration.html#schema_Common-Models-CoreSettingsConfiguration) with empty clan banner decals, gonfalons.

![Screenshot from 2019-11-15 18-10-55](https://user-images.githubusercontent.com/28153175/68953618-5263fd80-07d3-11ea-90bb-7bedad16029a.png)

**Comment by vthornheart-bng** [comment]
Ah, thank you for reporting this!  I will file a bug shortly.

**Comment by vthornheart-bng** [comment]
TFS 850695

**Comment by BOBRIWE** [comment]
Great!
