### ISSUE TITLE
Xur not properly resetting

### ISSUE THREAD

**Issue by xgerhard** [Bungie-net/api#1146]
Hi Vthorn, not sure how the Xur reset works on Bungies end, but thought I would create an issue here, since the API data is incorrect at reset.
Last week (8th nov) the saleItems for Xur response were empty at reset except the default items (my script might have hit an unlucky timing there of the exact reset).

This issue is more about the saleItems changing an hour after reset, two weeks in a row, seems to only be the weapon both times.

**Comment by floatingatoll** [comment]
Vthorn - Note that there is a corresponding in-game issue with Xûr’s inventory and so this may be the API reflecting the gamestate ‘accurately’

**Comment by vthornheart-bng** [comment]
Does it match what the game is providing for Xur during that hour?

**Comment by xgerhard** [comment]
Yes, it does match with the in game sale items.

**Comment by vthornheart-bng** [comment]
Ah, shoot.  Yeah, this means the problem is deeper, in the game itself.  I will bubble this up, thank you for reporting this!

**Comment by vthornheart-bng** [comment]
Spoke to some folks - looks like it was indeed a problem with daylight savings time.  Whoops!  #abolishdaylightsavingstime

I've been told that from this week onward it should no longer occur!

**Comment by xgerhard** [comment]
Good to hear, thanks for looking into it!
