### ISSUE TITLE
Claws of the Wolf is missing impact stat

### ISSUE THREAD

**Issue by delphiactual** [Bungie-net/api#1148]
Follow-up to https://github.com/Bungie-net/api/issues/1131

The only gun in the entire database that is missing its impact stat is https://data.destinysets.com/i/InventoryItem:1280933460

**Comment by vthornheart-bng** [comment]
Hmm, what do you see when you get that item in the game?  Does it show an impact stat?

**Comment by delphiactual** [comment]
Yes it does.
![Destiny 2 11_19_2019 5_13_51 PM](https://user-images.githubusercontent.com/4798491/69197898-2789ea00-0af0-11ea-8c69-96d72fa99856.png)
![Destiny 2 11_19_2019 5_14_05 PM](https://user-images.githubusercontent.com/4798491/69197899-2789ea00-0af0-11ea-8a4e-2c566efb3ee9.png)

**Comment by delphiactual** [comment]
It does have an erroneous `Blast Radius` of 90...

**Comment by vthornheart-bng** [comment]
Huh, very interesting!  I'll file a bug on this, thanks for reporting it!

**Comment by vthornheart-bng** [comment]
TFS 851066
