### ISSUE TITLE
GroupV2.GetGroupsForMember returns a 307 redirect and downgrades to HTTP

### ISSUE THREAD

**Issue by W1ndst0rm** [Bungie-net/api#1149]
I'm trying to get what clan a user is in, but the GroupV2.GetGroupsForMember endpoint returns an HTML page with a 307 status code that redirects to an HTTP version of the endpoint. The HTTP endpoint provides the data I'm expecting when I test it with Postman, but it is blocked as mixed content when accessed in browser.

Rendered HTML page
![rPgDMriToG](https://user-images.githubusercontent.com/20608358/69001863-89094900-08a3-11ea-97ee-e10513b8b491.png)

Response Headers 
![bbiNoTuVWk](https://user-images.githubusercontent.com/20608358/69001613-0e3e2f00-089f-11ea-954c-9ca3e6130717.png)

**Comment by Tetron-bng** [comment]
Make sure you include the trailing slash in the request URL.  The servers are trying to redirect you to the URL with the trailing slash, but the platform defaults to http and thus creates this problem.

**Comment by W1ndst0rm** [comment]
Makes sense, many thanks!
