### ISSUE TITLE
GetMembershipById failing for users who played D1 on legacy consoles

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#115]
This one's a bit less solid - I'm hoping you can help me find a full repro.

At DIM we've been seeing reports that users who played D1 on PS3/Xbox 360 are getting the message "It looks like this account is on a legacy platform." from DIM. Here's our issue for it: https://github.com/DestinyItemManager/DIM/issues/2127

Going off only the screenshot in that issue, I was able to make a request to https://www.bungie.net/Platform/Destiny2/2/Profile/4611686018454963271/?components=100,102,103,200,201,202,204,205,300,301,302,304,305,306,307,308 with no problem, so I suspect the issue is with `GetMembershipById` (we don't call a lot of APIs for D2 thanks to the much more concise API design, thanks!) Unfortunately I don't have an example of a B.net membership ID that reproduces this, and I don't think I can backtrack from the Destiny account to the B.net membership.

**Comment by serkanbal** [comment]
Just an insight:
I was experiencing the same issue. It is resolving itself when the player logs in D1 on a current gen console.

**Comment by vthornheart-bng** [comment]
Hmm, interesting - I'll have to dig around a bit further on that.  If you can get me an example of a membership ID - or even a bungled session from a user who experienced it - let me know!

**Comment by shinenyuri** [comment]
I had this problem just recently, so I came here to communicate about it.

I'm a Destiny 1 player from PS3, and I never bought the game again in PS4, but I did get Destiny 2 for PS4, yet can't connect into the DIM because of this bug.

Unsure if this is the membership ID you mean, but... 12988403

If that's not it then tell me.

**Comment by vthornheart-bng** [comment]
Ah yes, is this you?

https://www.bungie.net/en/Profile/254/12988403/neromercer3600

Thank you for sharing this info - your account is in exactly the state we need to be able to investigate this!  Many thanks!  There's a lot of issues we're tacking at the moment, so there may be some lag time before I can swing back around to this issue - but I will investigate this as soon as I'm able to.  Having your account known to be in this state will be a big help, and is greatly appreciated.

**Comment by ChelseaD4gger** [comment]
I've had the same problem and don't have the ability to log into d1 on my xbox one cuz i only own it for 360

**Comment by vthornheart-bng** [comment]
@bhollis, when this occurs for you, can you confirm that the error you are receiving is DestinyLegacyPlatformInaccessible?

**Comment by bhollis** [comment]
I can't confirm - I've never had it happen to me, so I haven't seen the full response. Only screenshots of our error message. 

-Ben

**Comment by SunburnedGoose** [comment]
![screen shot 2017-09-20 at 12 18 39 pm](https://user-images.githubusercontent.com/984608/30657949-ca5de242-9dfe-11e7-9a1d-ffe0d7c56f08.png)

Here's the network call @vthornheart-bng and response we're getting.

![screen shot 2017-09-20 at 12 19 06 pm](https://user-images.githubusercontent.com/984608/30657961-daac332e-9dfe-11e7-8e35-198aba20c70f.png)

**Comment by SunburnedGoose** [comment]
This user played on Xbox 360 for D1, then picked up D2 on Xbox One.  Their account is inaccessible on bungie.net, destiny companion app, and DIM.

**Comment by vthornheart-bng** [comment]
Sweet, thanks for this info!  That confirms that the fix I just made should resolve the problem for people in this situation once it's live.  I'll keep you all posted for when that gets deployed.

**Comment by bhollis** [comment]
I just wanted to check in - I believe this fix has been deployed and everything's OK now. Is that right?

**Comment by vthornheart-bng** [comment]
Yes, this should be set now - my apologies for the delay, I'm finally going through the Issues and trying to update things!

**Comment by bhollis** [comment]
No sweat, thanks for tracking this down!
