### ISSUE TITLE
Auth issues

### ISSUE THREAD

**Issue by YourFavoritePerson** [Bungie-net/api#1150]
Since the tweet on 11/15 my token refresh script has been failing.  There is a newer tweet that claims this was fixed, but it doesn't seem to be.

An example clan/account is:
clan: https://www.bungie.net/en/ClanV2?groupId=3789276
account: https://www.bungie.net/en/Profile/254/21202762/Akumati11

it's giving me bad request responses ("HttpStatusCode was not OK.  It was a '400' (BadRequest)"). last time I saw this my tokens expired, but that was 2 weeks ago and they expire after a year.

**Comment by YourFavoritePerson** [comment]
the tweet says you might need to log out and in again to get it to work so I'll try getting new tokens.  I didnt have to do this for the first 1 year and 15 days so if this does fix it, why is it necessary this time?  Is this going to be the norm for now on?

**Comment by TorKallon** [comment]
All old tokens were invalidated. You need to get people to authenticate again and then refresh the new tokens.

**Comment by YourFavoritePerson** [comment]
Yea, I did do that and it did fix it.  I'm just curious if this is going to be a regular thing since this isnt how it's been in the past.

**Comment by hellocontrol-bng** [comment]
> Yea, I did do that and it did fix it. I'm just curious if this is going to be a regular thing since this isnt how it's been in the past.

Shouldn't be. We won't do this unless there's an issue that warrants it. It causes some load for us as everyone rushes to authenticate, so we do avoid it if possible.
