### ISSUE TITLE
CrossPlay account w/ Twitch can't load D1 characters

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#1151]
This account is originally Xbox, but just added Stadia. It has D1 characters, but when getting those characters via:

https://www.bungie.net/D1/Platform/Destiny/1/Account/4611686018443852891/

Responds with:
```
{"ErrorCode":1618,"ThrottleSeconds":0,"ErrorStatus":"DestinyUnexpectedError","Message":"An unexpected error has occurred while trying to grab Destiny information.  Let us know if you see this.","MessageData":{}}
```

**Comment by vthornheart-bng** [comment]
https://www.youtube.com/watch?v=6N-_RIVpZvY

Thanks for reporting this, I'll file a bug.

**Comment by vthornheart-bng** [comment]
TFS 851087

**Comment by ckhicks** [comment]
Dude, I can't imagine the additional platform headaches y'all are dealing with now that something else has been added to the mix. Keep up the good work.

**Comment by benjaminhollissc** [comment]
Seeing evidence now that it returns 401 from the D1 profile endpoint, which will trap DIM in a login loop (we log in, load D1 accounts, and think our token is bad and start over again).

**Comment by vthornheart-bng** [comment]
As the Cranberries would say, this bug continues to linger.  We're looking into attempting a fix early in the new year.  Until then, unfortunately, we're still stuck with this situation.  We'll let you all know once we've deployed a fix!

**Comment by doktor5000** [comment]
> We're looking into attempting a fix early in the new year. Until then, unfortunately, we're still stuck with this situation.

Is there any workaround in the meantime, or is a fix already in sight, maybe? From what I understood, affected users could currently only disable crossave, as there are no means to temporarily unlink just the Stadia accounts, correct ? Although then users would not be able to able to use their accounts on Stadia, nor on PC for example, unless they wait 90 days to reenable crossave.

**Comment by Achronos-BNG** [comment]
A fix for this issue is in testing now.  Assuming no issues are found, I hope to deploy it soon.

**Comment by galador** [comment]
So far, I've only seen mention of Stadia here, but it seems that the newer Twitch linking seems to cause this problem, too. Could not see my D1 account in DIM, but after I unlinked Twitch, I could see the D1 account there, again.

**Comment by dconefourseven** [comment]
> So far, I've only seen mention of Stadia here, but it seems that the newer Twitch linking seems to cause this problem, too. Could not see my D1 account in DIM, but after I unlinked Twitch, I could see the D1 account there, again.

Plus 1. I just linked my Twitch account for the new extension, and this issue has regressed on my account. 

@Achronos-BNG Please be aware of this new repro.

**Comment by Achronos-BNG** [comment]
Yes, I'm sorry I didn't comment before.  We are aware of this new iteration of the problem.  As you can probably tell by it affecting the game (the Tapir error), this is a Destiny (1) game bug.  It was filed, but as there is a work around (unlink Twitch), and it is a Destiny 1 bug, it will likely be a bit before it gets fixed.

**Comment by Achronos-BNG** [comment]
This issue should be fixed now (both the Destiny 1 Tapir error as well as the issues loading D1 character data).
