### ISSUE TITLE
Missing data from GetProfile (Acting as account is private)

### ISSUE THREAD

**Issue by t3rr11** [Bungie-net/api#1152]
So i've noticed a weird bug. I have a bot that retrieves clan members and then cycles through each one and grabs the profiles of each member. It runs at 2 members per second (0.5s interval) so well below the 30 a second limit.

In order to check if an account is private i just check if data exists inside of a profile component endpoint. For example: 800 for character records. If there is no data i assume the account is private.

Well sometimes an account comes back with no data in those endpoints (characterProgressions, characterActivities, characterRecords and characterCollectibles). So my bot assumes they are private. But after doing more inspection it seems some accounts are not private but are coming back with no data.

![image](https://user-images.githubusercontent.com/2139233/69228651-de12cb00-0bd3-11ea-9f7f-6376fa586c65.png)

I was wondering if you could explain what is going on here? Is this a bug you are aware of?

Here are some more examples. I scan 8 clans now so at the very maximum i am hitting 16 calls per second so it can't possibly be that, also considering data is coming back and it's not throwing a throttling warning. 

Scan 1: (It thinks Foxxninja, setis and UhSn_p and KaotikSQRL are private when they are public. pepperoncini is actually private)
![image](https://user-images.githubusercontent.com/2139233/69228778-1d411c00-0bd4-11ea-87a5-b0430b0ccae2.png)

Scan 2: (It thinks mudders, UhSn_p, Foxxninja and I_am_Aver are now private, 2 new accounts that returned with no data but KaotikSQRL and setis are now public since they didn't return private this time around)
![image](https://user-images.githubusercontent.com/2139233/69228896-56798c00-0bd4-11ea-90e2-123181d225d4.png)

**Comment by t3rr11** [comment]
I actually think this might be an error on my part, returning the wrong name associated with the private account. Just doing checks now.

**Comment by t3rr11** [comment]
Yup ignore me, turns out i was returning the wrong displayname causing variation, but going from clan to clan i see the pattern there was always 3 and always 2 private accounts in specific clans. After returning the right names, found they were actually private. closing this issue now.

**Comment by vthornheart-bng** [comment]
Ah, no worries!
