### ISSUE TITLE
Documentation Typo on Destiny.Components.Presentation.DestinyPresentationNodeComponent

### ISSUE THREAD

**Issue by kramrm** [Bungie-net/api#1153]
On the documentation for DestinyPresentationNodeComponent, the `completionValue` has the following description with the word **node** misspelled.
> The value at which the presentation ode is considered to be complete

<https://bungie-net.github.io/multi/schema_Destiny-Components-Presentation-DestinyPresentationNodeComponent.html#schema_Destiny-Components-Presentation-DestinyPresentationNodeComponent>

**Comment by vthornheart-bng** [comment]
Ah, good eye - thanks!
