### ISSUE TITLE
Vendors response missing Visage of Calus

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#1154]
I'm getting Vendors from `https://www.bungie.net/Platform/Destiny2/<membershipType>/Profile/<destinyMembershipId>/Character/<characterId>/Vendors/`, but it no longer includes the [Visage of Calus](https://data.destinysets.com/i/Vendor:1944634565) in its `vendorGroups.data.groups` or `vendors.data`.

**Comment by vthornheart-bng** [comment]
Ah, my apologies on not mentioning this earlier - we were running into a bug with that vendor that was causing the whole endpoint to not return data.  To quickly resume returning the Vendor, we had to turn off that vendor.  It will come back the next time we do a full content deployment!

**Comment by bhollis** [comment]
Thanks, we’ll await the next deployment!

**Comment by TeeTeeHaa** [comment]
Emperor Calus is not amused that his Visage was not considered worthy enough for this season.

**Comment by bhollis** [comment]
This won't survive to Beyond Light
