### ISSUE TITLE
Clan joinDate variable is not accurate.

### ISSUE THREAD

**Issue by t3rr11** [Bungie-net/api#1155]
When looking at the members listing of `/Platform/GroupV2/{ groupId }/Members/` the joinDate variable associated with each member is incorrect. This variable logs the time a member was invited and not the time a member has accepted and joined. As i understand with clans invited players count towards the 100 member limit, so i assume that the invite date from that data is carried over when i played joins. I was wondering if this could be changed as i require accurate data for a project i am working on. 

I have a node js bot that scans these groups and checks for differences between 2 custom made files to determine if variables in those have changed and if so it will output a broadcast to a discord server. But i have an issue where it spams if a player joins a clan because obviously there is new data. The way i have tried to prevent this is by checking if the player has joined the clan in the last 15 minutes, but with the way the join date variable logs this causes issues for people who do not accept the invitation straight away.

![image](https://user-images.githubusercontent.com/2139233/69789469-8c3ff580-1210-11ea-8f8d-a194241e7a8b.png)

If this is not something that can be fixed easy and requires too much work i have another way around by checking the see if their name was in the previous file and if not then don't broadcast, this may however cause more issues so having this variable changed to be accurate would be awesome if possible!

Thanks as always!

**Comment by floatingatoll** [comment]
What data from the player record are you using to determine the time stamp for “has achieved the title”?

**Comment by t3rr11** [comment]
So when i grab the players data is compares it against the players old data which at the moment is only 1 minute 40 seconds old. So when it checks the record variable for lets say wayfarer, the completion value will be false in the old file and the new file will have the completion value as true. Therefor that player has obtained the wayfarer title in the last 1 minute 40 seconds. Then the bot will send a broadcast to that players clan discord. 

So there is no timestamp for the record itself but it can be pretty accurate. But as you can tell if the old file does not contain data for that player and the new file contains a true completion value for wayfarer, it will announce it. To prevent this i check against that players joinDate in the clan file to determine if they've just joined the clan or not which would have been a great way to prevent spam but it's not accurate.

**Comment by t3rr11** [comment]
To avoid this problem for now i've added a check to catch if the player has achieved more than 2 titles or 6 items in that 1 minute 40 seconds and if so prevent announcement.

![image](https://user-images.githubusercontent.com/2139233/69920467-44eb8a80-14d8-11ea-86df-565bf45eeec6.png)

But this is a terrible way to work around this as what if a clan finished up their enlightenment title together that would be 6 titles in that 1 minute 40 seconds and would not be announced.

**Comment by vthornheart-bng** [comment]
I'll file a bug on this, thank you!

**Comment by vthornheart-bng** [comment]
TFS 854485

**Comment by t3rr11** [comment]
I know it's a big ask but could you let me know if this gets fixed, It's quite hard to test / check for.

**Comment by vthornheart-bng** [comment]
I will let you know when I hear more on it - unfortunately, I've got no update so far.
