### ISSUE TITLE
Countdown crucible mode definition states it is not a PvP activity

### ISSUE THREAD

**Issue by movsesyanpv** [Bungie-net/api#1156]
When looking at countdown (3646079260) at [destinysets](https://data.destinysets.com/i/Activity:3646079260) I've discovered this:
```
{
    ...
    "isPvP": false,
    "insertionPoints": [],
    "activityLocationMappings": [],
    "hash": 3646079260,
    ...
}
```
Shouldn't it be like this: ```"isPvP": true```?

**Comment by t3rr11** [comment]
Good find :o

**Comment by vthornheart-bng** [comment]
Ah, yes, many thanks!  I'll file a bug on this momentarily as well!

**Comment by vthornheart-bng** [comment]
TFS 854487
