### ISSUE TITLE
St0mp-EE5 Screenshot from hash 193869520 is blank

### ISSUE THREAD

**Issue by janweinen** [Bungie-net/api#1157]
I have recently played around a bit with Destiny API and noticed that the screenshot that is returned from the database (at least from this hash: 193869520, I received the hash from the public Xur endpoint) returns an image without the exotic:

![193869520](https://user-images.githubusercontent.com/30630373/70220986-c09f3e80-1747-11ea-8610-52f9820087eb.jpg)

When searching on light.gg I get two entries for St0mp-EE5. Here are the corresponding image links:
with item: https://www.bungie.net/common/destiny2_content/screenshots/1245809814.jpg
without item: https://www.bungie.net/common/destiny2_content/screenshots/193869520.jpg

I checked this in the destinysets database explorer and it was the same here: 
with item: https://data.destinysets.com/i/InventoryItem:1245809814
without item: https://data.destinysets.com/i/InventoryItem:193869520

**Comment by vthornheart-bng** [comment]
Ah, good find, thank you!  We've sometimes had trouble with these generated screenshots, and have to regenerate them as a result.  Usually we catch it beforehand, but it looks like we missed this one.  Thank you for reporting it!

**Comment by vthornheart-bng** [comment]
TFS 854488
