### ISSUE TITLE
Call for Winter Wishlist 2019 requests!  Limited time this year.

### ISSUE THREAD

**Issue by vthornheart-bng** [Bungie-net/api#1158]
So this year's been a year of not having enough time to work on the API, and unfortunately that continues this winter.  However, as the year comes to a close I would at least like to know what the community feels is the highest priority, so that I can see if we can cram a few of those requests in during the holiday week if possible!

If you want to review last year's winter wishlist, check it out here:

https://github.com/Bungie-net/api/issues/756

Please provide a link to TFS tasks that you would like to see implemented/resolved, "thumbs up" the posts in this thread for tasks you'd like to see implemented, and before the week of December 22nd I'll try to prioritize those by request vs. difficulty/feasibility of implementing/fixing them!

Thanks for your patience and for being such a good community.  Even if we don't have a chance to work on a lot of improvements this time around, taking this time to see what you all think of as highest priorities will help us to push in the right direction as time allows in the new year!

**Comment by mistahj67** [comment]
https://github.com/Bungie-net/api/issues/775

**Comment by justrealmilk** [comment]
* Time Destiny profile was created or time of very first activity start
* Time of completion attached to high value records 
  * Or even just seals? That'd be pretty cool
* Ornaments get a set of presensation nodes in Collections
* Artifact mods to have missing item category hashes i.e. 1052191496 for weapon mods

**Comment by justrealmilk** [comment]
Datetime Destiny profile created #1159

**Comment by justrealmilk** [comment]
Datetime triumph seals are completed #1160

**Comment by justrealmilk** [comment]
Season of the Undying artifact mods are missing category hash for weapon mods #1161

**Comment by BlazeBoss17** [comment]
Activities never showing up in activity history  #867

**Comment by delphiactual** [comment]
#1162 Additional info per season

**Comment by delphiactual** [comment]
#561 add season property to InventoryItemDefinition

**Comment by justrealmilk** [comment]
Continued work on [Bungie-net/api/wiki/3D-Content-Documentation](https://github.com/Bungie-net/api/wiki/3D-Content-Documentation)

Please upvote

**Comment by YourFavoritePerson** [comment]
These probably wouldnt be used by many people but...

Top request:  1 API call to get everyone in a clan, the people pending, the people invited, the people banned, etc.  As much data in 1 call as possible to reduce round trips.  Also if the normal, no auth clan endpoint could tell you the quantity of slots the clan has available, that'd be helpful.  This is because pending/invited users take up slots, so it isn't as simple as a 100-[clan member count] to see if there is room in the clan.  you need to hit the normal clan endpoint, the pending people endpoint and the invited people endpoint to get the number.

Fix paging on the banned member endpoint #933.  I'd love to be able to audit the people we've banned from our clans, but right now you can't check who is banned.  You also can't see the comments you input when you ban someone.

**Comment by justrealmilk** [comment]
#1168 Add current season pass progression hashes to destiny2CoreSettings (GetCommonSettings endpoint)

**Comment by StormTester** [comment]
#909 endingPhaseIndex or array of completed phases in PGCR.

**Comment by vthornheart-bng** [comment]
Any other requests?

So far we've got the following, and I'm categorizing them right now with the sort order of "potential to actually implement it", then "number of votes", then by the date it was posted in this thread.

## Yes, barring unexpected issues and after I think a bit more about the potential negative implications of these changes:

- 2 votes, #561 add season property to InventoryItemDefinition
- 1 vote, #1161 Season of the Undying artifact mods are missing category hash for weapon mods
- 1 vote, #933 Fix paging on the banned member endpoint

## Possibly!  Need to check on status of downstream systems, what data is available, and whether others on the team would be comfortable with the change

- 3 votes, #1159 Datetime Destiny profile created
- 1 vote, #867 Activities never showing up in activity history
- 1 vote, #1162 Additional info per season (softLevelCap, powerfulLevelCap, pinnacleLevelCap, brightEngramHash)
- 1 vote, #909 endingPhaseIndex or array of completed phases in PGCR.
- 1 vote, Endpoint to get full Clan data, nonpaged with as much status info as possible

## Not likely due to amount of time it would take

- 3 votes (and many other emojis), Continued work on Bungie-net/api/wiki/3D-Content-Documentation
  - This one would require a lot of time from someone with that specific knowledge, and I don't think I'm going to be able to pull them away long enough to do it.  (I can't, as I'm utterly ignorant about our 3D data unfortunately, and 3D rendering in general!)

## Not likely without much larger architectural or downstream system changes

- 4 votes, #1160 Datetime triumph seals are completed 
  - Unfortunately, because the game doesn't store it (except in apparently some situations where the unlock value happens to be changed to "ticks since jan 1 1970 UTC" when it completes), we don't have a way to return this data)
- 4 Votes, #775 Clan webhook support (we would need some more significant architectural changes to support webhooks, particularly if it also had to handle when changes are made outside of Bungie.net but also inside as well.  Can't promise that for our short window where we can make changes)

**Comment by benjaminhollissc** [comment]
https://github.com/Bungie-net/api/issues/1173

**Comment by delphiactual** [comment]
#779 Valor and Gambit multipliers

**Comment by justrealmilk** [comment]
#1178 Class stat description strings

**Comment by TitoLasVegas** [comment]
Please see [#1185 ](https://github.com/Bungie-net/api/issues/1185)

**Comment by kj415j45** [comment]
Fix #822
