### ISSUE TITLE
Additional Info on DestinySeasonDefinition

### ISSUE THREAD

**Issue by delphiactual** [Bungie-net/api#1162]
including `pinnacleCap`, `powerfulCap`, `softCap`, `powerFloor` and `brightEngramHash` per season would be super awesome. Any or all of these would be a welcome addition.

**Comment by kramrm** [comment]
Also including the seasonal gear icon indicator would be nice to have too.
https://www.bungie.net/7/ca/destiny/bgs/season10/gear_rasputin_icon.png
https://www.bungie.net/7/ca/destiny/bgs/season10/pass_corner_rasputin.png

**Comment by JpDeathBlade** [comment]
To add to the watermark and watermarkShelved, a tooltip version where the watermark is flipped would be nice also.
