### ISSUE TITLE
Members name (fireteam) of a NF or raid?

### ISSUE THREAD

**Issue by Romans96** [Bungie-net/api#1163]
Hello! Searching for nightfalls or raid or other activitis, i find that part of code, for each activity:
```
"fireteamId": {
    "statId": "fireteamId",
    "basic": {
        "value": anid.0,
        "displayValue": "-anotherid"
    }
},
```

So i need to find the membership ids of the component of that team. How can i do?
i tried with the endpoint 
`https://www.bungie.net/Platform/Fireteam/Clan/id/ActiveCount/`
But it returns erroreCode: 1, with any results, so how can i do?

THank you!

**Comment by justrealmilk** [comment]
Which endpoint returns your snippet?

Clans are actually groups as far as the API is concerned and groups are not fireteams.

**Comment by Romans96** [comment]
> Which endpoint returns your snippet?
> 
> Clans are actually groups as far as the API is concerned and groups are not fireteams.

The only endpoint that i find to search activity for a specific membershipid (in this case for NF):

`https://www.bungie.net/Platform/Destiny2/3/Account/membershipid/Character/characterid/Stats/Activities?mode=46`

**Comment by Romans96** [comment]
So nobody can help me? I can't find how to obtain the ids of the firteam for that activity

**Comment by justrealmilk** [comment]
The activities endpoints return results that include a reference or instance ID. You use this ID to fetch the related PGCR. This PGCR contains data on all of the activities participants.

Join the official unofficial Discord for more help https://discord.gg/fnDPxB3

**Comment by vthornheart-bng** [comment]
Apologies for not seeing this earlier - and thank you @justrealmilk for providing the info!
