### ISSUE TITLE
Duplicate triumph records (Season of Dawn)

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1166]
![image](https://user-images.githubusercontent.com/156681/70587463-acf74a80-1c15-11ea-958a-5024c253a123.png)

Season 7: Engagment and Everything In Its Rights Place... possibly others

https://data.destinysets.com/i/PresentationNode:3025751065/PresentationNode:3220433604/PresentationNode:1333331795

**Comment by justrealmilk** [comment]
![tiger_release_final_20191211_181718](https://user-images.githubusercontent.com/156681/70603549-83a0e380-1c42-11ea-8ad6-c93e50db90a7.png)

Worldline Catalyst

**Comment by vthornheart-bng** [comment]
Oh, this is a bug you're seeing in game?  Interesting - I'll report it!  Somehow I missed a whole block of these github issues that got filed, so I'm catching up now!  Apologies for the delay in responding!
