### ISSUE TITLE
Shadowkeep seal completion record has started enumerating as rewardUnavailable

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1167]
![image](https://user-images.githubusercontent.com/156681/70589936-d4054a80-1c1c-11ea-88f3-e6f2bed50028.png)

I'm unsure why it's flagging itself this way, but it's a significant user experience issue. Personally, I use the flag to hide limited time titles from users such as Undying and MMXIX.

Maybe it was erroneously marked the same way as undying?

**Comment by justrealmilk** [comment]
Actually, Undying isn't marked as unvailable (visible to a user who hasn't completed any of the records) - I think whoever did the job may have got the seals mixed up!

**Comment by vthornheart-bng** [comment]
Ah, I'll ask about that!

**Comment by vthornheart-bng** [comment]
Just to get clarification - so the real issue is that the temporary Undying record should be marked as unavailable but isn't?

**Comment by justrealmilk** [comment]
correct - when enumerated, the completion record for Shadowkeep (`2209950401`) says it's not longer available although Undying is. these should be reversed

**Comment by vthornheart-bng** [comment]
And just to make sure we're looking at the same records, for Shadowkeep the actual completion Record itself is hash 3793754396, and for undying it's 2707428411

**Comment by justrealmilk** [comment]
_yeah damn I thought I was using the record hash, not the presentation node hash_

Correct

**Comment by vthornheart-bng** [comment]
Cool, no worries!  I have passed the info on - unfortunately it looks like this is something that'd require a game side fix.  Thank you for letting us know about it!
