### ISSUE TITLE
The large emblem banners are missing from the API

### ISSUE THREAD

**Issue by designker** [Bungie-net/api#117]
The new ones that can run across the length of the screen. Just raising this here for completeness

**Comment by vthornheart-bng** [comment]
Good call - yeah, these went missing sometime before we went live, I'll need to hunt them down.

**Comment by benedfit** [comment]
Are there any plans to return the transparent version of the main emblem image too? The one that bleeds out of the player nameplate on the character screen?

**Comment by vthornheart-bng** [comment]
Hmm, can you show me a picture of the specific one you're looking for?  I want to make sure I'm picturing the same one you are benedfit!

**Comment by ArkahnX** [comment]
https://imgur.com/fUWQ3uV

This screenshot contains examples of both images. The main issue is about the top banner for the character inventory page, the latest comment is the transparent version of the emblem that hovers to the left of your name and level, and slightly overhangs the banner.

**Comment by vthornheart-bng** [comment]
Ah!  I see - yes, I did a bit of investigating and I fixed the top banner not being returned for the next release (pending testing).  I'll go see if I can find that transparent image as well soon(tm).

**Comment by vthornheart-bng** [comment]
You should have them now!
