### ISSUE TITLE
Steelfeather Repeater definition is messed up

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#1170]
Not sure if any of the other Sundial weapons have this issue, but https://data.destinysets.com/i/InventoryItem:159303539 is pretty nuts. It claims a bizarre inventory bucket (2422292810) (which is the same one Borealis Catalyst had: https://github.com/Bungie-net/api/issues/687), it claims to be type "Dummy", has no damage type, etc.

There's a separate version that makes more sense: https://data.destinysets.com/i/InventoryItem:1251729046, but the weird one is the one I got.

**Comment by bhollis** [comment]
Yeah, looks like this is true of the other weapons as well.

**Comment by vthornheart-bng** [comment]
Very interesting!  As in the other Sundial weapons specifically have this strange setup?  I could see it if that one was a dummy item for display purposes.  And yeah - that bucket you're seeing it defined with is the "temporary" bucket.  A little inside baseball: when a designer wants you to get an in-game popup as if you received an item but without directly giving you the item for some reason, they'll make a "dummy" item that goes into the temporary bucket.  The act of it hitting your inventory triggers that pop-up.

When you look in your inventory, could you check if you happen to have one of each (the real one and this fake one)?  The temporary bucket will keep the last 5 dummy items that were populated in this way, so you could very well have *both* the dummy item and the real item in your inventory, but only one of them is in a visible/usable bucket.

**Comment by bhollis** [comment]
The dummy one is definitely the one in my inventory - I’ll check to see if the other one is somewhere else. 

This may also be related to this bug: https://reddit.com/r/DestinyTheGame/comments/ea3lfx/sundial_weapons_can_be_used_for_infusion_without/

**Comment by vthornheart-bng** [comment]
Hmm, sounds troublesome.  I will hit some folks up and loop back.

**Comment by bhollis** [comment]
Now, I can confirm that the only item I see for Steelfeather Repeater has hash 1251729046. Before, the item was in the postmaster - so maybe it was still a dummy while it was in there.

**Comment by vthornheart-bng** [comment]
Ah, it sounds like a patch that is going live this week should resolve the issue, at least the one mentioned in the reddit thread.  It's still possible/legitimate for someone to use a dummy item for a postmaster item however, so you may end up still seeing that.  The act of pulling an item from the Webmaster is a trigger point for dummy items to perform various actions, so if someone was being clever they may have set up the content in this way legitimately (for better or worse).

**Comment by hellocontrol-bng** [comment]
@vthornheart-bng Postmaster* 😉

**Comment by vthornheart-bng** [comment]
Ha, good find.  Web <> Post

**Comment by bhollis** [comment]
This appears to have all gotten cleared up!
