### ISSUE TITLE
OAuth in Postman getting error with redirect_uri

### ISSUE THREAD

**Issue by reddigfabian** [Bungie-net/api#1172]
When attempting to request a new auth token via Postman the request fails with the following error.

Error: Cound not complete OAuth 2.0 token request: "redirect_uri does not match application configuration."

However I don't have a redirect uri specified in the application console.

**Comment by Tetron-bng** [comment]
You are correct, you should not get this error if you do no specify a redirect_uri since the one configured with the application will be used.  Can you post the request/responses of your flow here to see if we can notice anything amis?  (obscure your key and client secret if any, or prepare to rotate those).

**Comment by Tetron-bng** [comment]
Oh wait, I just realized you stated you *DON'T* have a redirect URI specified in the application console.  The error message may just be imprecise in this case.  You MUST specify some type of redirect URI in the application console.

**Comment by gadielkalleb** [comment]
I have the same problem, I am mapping the authentication routes and groups and clans, my case is to use in the app I am building with React Native, in this case how can I do this url redirection?

**Comment by floatingatoll** [comment]
You would typically use a callback URL in that scenario. Auth0 (unrelated to Bungie) published a writeup on how to do this with React Native, in case it's of any help: https://auth0.com/docs/quickstart/native/react-native/00-login

**Comment by floatingatoll** [comment]
Postman question: In the Postman client OAuth 2.0 docs, you can see "Callback URL" shown in the screenshot on this page: https://learning.postman.com/docs/sending-requests/authorization/

They also appear to indicate what to provide for sites that won't accept a blank callback URL, which may be of use to you:

> *Callback URL*: The client application callback URL redirected to after auth, and that should be registered with the API provider. If not provided, Postman will use a default empty URL and attempt to extract the code or access token from it—if this does not work for your API, you can use the following URL: `https://www.postman.com/oauth2/callback`

**Comment by gadielkalleb** [comment]
@floatingatoll Thanks, sorry for the delay in responding, but everything went well here thanks, that was it.
