### ISSUE TITLE
Empty progress data on several milestones since Season of Dawning

### ISSUE THREAD

**Issue by dcaslin** [Bungie-net/api#1175]
Crucible Core: 2434762343

Crucible Rotator: 4191379729

Nightfall Ordeal weekly: 1942283261

Nightfall 100K Score: 2029743966

Vanguard Strikes: 1437935813

all return effectively empty of completion data, for example: 

```
                         {
                            "milestoneHash": 1437935813,
                            "startDate": "2019-12-10T17:00:00Z",
                            "endDate": "2019-12-17T17:00:00Z",
                            "order": 2000
                        }

```

**Comment by vthornheart-bng** [comment]
TFS 857517

**Comment by ttgmpsn** [comment]
Probably related to / dupe of #1164

**Comment by xenophic328** [comment]
any update on this ?

**Comment by vthornheart-bng** [comment]
Ah yes, my apologies on not updating this issue!  I have found the root cause, and though it's not going to make it live in time for the bnet release next week, it will appear in the release after.
