### ISSUE TITLE
Request for Comment: PGCR removal of Bungie.net membership info

### ISSUE THREAD

**Issue by vthornheart-bng** [Bungie-net/api#1176]
As those of you scraping PGCRs probably know, PGCRs have been having a rough time lately.  They've gone through phases over the years of holding on, and times where we have been unable to serve all the incoming PGCR requests.

We are looking to do some optimizations in the new year that should hopefully help the situation, but one of them involves a potentially breaking change to remove data that I'm hoping people generally don't need or could grab and store off in other ways if they do need it.  But I'd like your input.

I am looking to **remove the entries.player.bungieNetUserInfo property**.

Destiny membership data (entries.player.destinyUserInfo and other properties found in the DestinyPlayer object) would still be returned, but you wouldn't automatically get the associated bungie.net Membership anymore.  My hope is that, for most scraper sites, you either don't need their bungie.net relationship or are already tracking those relationships separately.

If you are dependent on this data, there's a workaround you could employ.  When you see an unrecognized Destiny membership ID, you could make a call to an endpoint like GetMembershipDataById to get the associated BNet membership, and then store that in your own system so that you don't have to make a second call from there on out for that membership.

Let me know what you all think: if you're using this data, if the workaround mentioned would work for you, or if your site could live without this data (for instance, if you were using it but for a trivial feature that you wouldn't mind removing).

Thank you!  Removing this data is an important step in trying to provide more consistent PGCR access.   Hopefully it will bear good fruit, and won't cause too much of an inconvenience for those of you using the PGCR endpoint.

**Comment by TorKallon** [comment]
This wouldn't be an issue at all for Charlemagne. We do use that info, but
we already have it for existing users and can easily make an extra call
when we see someone new.

**Comment by bladefist** [comment]
Destiny Tracker Here - We're good w/ this!

**Comment by joshhunt** [comment]
Just to be clear - this is just the Bungie.net profile stuff? Destiny membershipType and membershipId will remain for each player, right? So you'll still be able to know which destiny player was in an activity?

That's fine. I don't use this (and i would be surprised if many did!)

**Comment by t3rr11** [comment]
Guardianstats here as well. I don't use this data, so all is good!

**Comment by vthornheart-bng** [comment]
Cool, and yes indeed:  strictly the bungie.net profile data would be removed.  Destiny membership type, membership ID, and other info would be retained!

**Comment by dcaslin** [comment]
I apparently use this for a single thing at D2Checklist... but it's nothing important and I'm 90% sure I can just use regular Destiny member info (and if I can't use any of it, I'll remove the silly little feature). Godspeed improving performance!

**Comment by dcaslin** [comment]
And... my usage of it is removed. In case anyone else needs it, you can look up the Bungie membership on the fly with:

`Destiny2/' + membershipType + '/Profile/' + membershipId + '/LinkedProfiles/`

**Comment by vthornheart-bng** [comment]
Sweet, thank you!  You all rock, I appreciate it!

**Comment by chrisfried** [comment]
I do currently use this info directly from PGCRs... But I imagine I could work around it easily enough.

**Comment by BlazeBoss17** [comment]
Raid.report does not use this data

**Comment by bladefist** [comment]
@vthornheart-bng Is this going to go live soon?

**Comment by vthornheart-bng** [comment]
TBD on the specific date.  We actually ended up in a pretty decent place at the moment server perf-wise, and we've got several higher priority projects we're trying to work on at the moment: so for the time being this is on our backlog of changes we're planning to make but haven't had the time to do yet.  I will let you folks know when we loop back around to it!

Until then, if anyone is using it for some reason, feel free to use this lag time to find alternatives!

**Comment by justrealmilk** [comment]
I'm confused about what's going

```
{
  "standing": 1,
  "score": {
    "basic": {
      "value": 47,
      "displayValue": "47"
    }
  },
  "player": {
    "destinyUserInfo": {
      "iconPath": "/common/destiny2_content/icons/f34823bfdefc09b2976228c3e649d5f2.jpg",
      "crossSaveOverride": 3,
      "applicableMembershipTypes": [
        1,
        2,
        3
      ],
      "isPublic": true,
      "membershipType": 3,                      // removing this at this time incurs an extra API request
      "membershipId": "4611686018467256093",    // need this
      "displayName": "Seance"
    },
    "characterClass": "Warlock",
    "classHash": 2271682572,                    // super handy for reporting the class the player ran in case the character has since been deleted
    "raceHash": 3887404748,
    "genderHash": 2204441813,
    "characterLevel": 50,
    "lightLevel": 965,
    "emblemHash": 3605490915
  },
  "characterId": "2305843009300685430",
  "values": {
    ...
  }
}
```

**Comment by t3rr11** [comment]
> entries.player.bungieNetUserInfo property

Yeah i'm a little confused as well, I don't see this property, has it already been removed now?

**Comment by bladefist** [comment]
@justrealmilk @t3rr11 They are removing `entries.player.bungieNetUserInfo`  The membershipId/Type is  destinyUserInfo, not bungie.  If something was removed otherwise, that might be a bug?

**Comment by vthornheart-bng** [comment]
Hmm, yes if you're not getting destinyUserInfo that's an unintended bug.  Is anyone not receiving destinyUserInfo?  Just making sure!

**Comment by vthornheart-bng** [comment]
I apologize for not communicating when the change was going to go live - the change is already live, but should only affect the bungieNetUserInfo property.  If you're seeing any other data that mysteriously disappeared, hit me up with a PGCR ID and let me know the situation (you're seeing data not come down for a property across the board, or for specific PGCRs where you would expect it etc)

**Comment by bladefist** [comment]
I checked one match and it looked fine.  Pretty conclusive imo. lol

**Comment by t3rr11** [comment]
Yeah i also don't see any problems other than the missing bungieNetUserInfo property (which makes sense as the change went live), All working as intended on my end.

**Comment by vthornheart-bng** [comment]
Sweet - good deal!  Sorry about the lack of communication for the timeline!  (fortunately it sounds like most people either moved away or were never using it)
