### ISSUE TITLE
Mars Adventures returning pgcrImage for Dreaming City

### ISSUE THREAD

**Issue by kramrm** [Bungie-net/api#1177]
Passing these on from someone else.  At least two Mars adventures are showing pgcrImage values for Dreaming City Images.

activityHashes
Psionic Potential 1811228210, 2302677459, 3384410381, 3909841711, 1657356109
Deathly Tremors 1294490226, 1682036469, 4094398454

**Comment by vthornheart-bng** [comment]
Ooh, good find, thank you!

**Comment by vthornheart-bng** [comment]
TFS 860343

**Comment by kramrm** [comment]
this has been fixed.
