### ISSUE TITLE
Unable to retrieve Dawning ingredient quantities

### ISSUE THREAD

**Issue by ashiswin** [Bungie-net/api#1179]
Even though the manifest file contains hashes for the various Dawning ingredients, I am unable to find them in any of the returned responses from the various endpoints. Hence, I am unable to retrieve the quantities of each of the Dawning ingredients currently held by my account.

**Comment by vthornheart-bng** [comment]
I'll file a bug to investigate - it could be that the Dawning item is implemented such that you don't actually get instances of the ingredient items, but instead it's playing games with sockets and plugs.  Unfortunately, I don't know for sure - I'll need to do a little digging to be able to provide a good answer when I get the time to investigate.

In the meantime, if anyone out here has already done so, feel free to drop the scoop here!  I haven't had time to look into how the Dawning oven is implemented.
