### ISSUE TITLE
Get clan members in Power Query?

### ISSUE THREAD

**Issue by robcsaszar** [Bungie-net/api#118]
I realize this is more of an unorthodox method of accessing the API but I'd like to work with the dataset in Excel directly, until a web alternative is available, although I doubt one that has all features I need will be.
I am trying to do a simple query to my clan, simple list of members so I can verify new vs. old and go further to get their characters and power levels.

https://www.bungie.net/Platform/GroupV2/2103644/Members/ doesn't seem to work for me, I get the following response from the server:

> ErrorCode: 18
> ThrottleSeconds: 0
> ErrorStatus: InvalidParameters
> Message: The input parameters were invalid, please enter valid input, and try again.

The {groupID} is the number at the end of this URL which is my clan page: https://www.bungie.net/en/ClanV2?groupid=2103644

I've used the correct API key, header, etc. and I can't for the life of my understand why I get this error.
Do I need to authorize with the Bungie OAuth URL?

Once again, if it isn't obvious, my knowledge if obviously limited with the API and GitHub in general - my sincere thanks for understanding.

**Comment by vpzed** [comment]
Add ?currentPage=1 to the end and it will work.

**Comment by robcsaszar** [comment]
Damn, I feel like an idiot, so simple. Thank you!

**Comment by vpzed** [comment]
Don't be it is incorrectly listed in the Path parameters when it should be in the Query parameters so it is easy to overlook.
