### ISSUE TITLE
inconsistent itemTypeDisplayName on class item mods

### ISSUE THREAD

**Issue by archived-2f4dd0** [Bungie-net/api#1180]
some class item mods say they are "Class Item Armor Mod" and some say "Class Item Mod".

there's no apparent logic to it, no other difference in item or plug structure.
there's season 9 stuff in either, so big shrug, doesn't seem like a naming convention change from a specific time.

don't know if this is under API control or generated in the game's data but it's yours now to decide :)

`"Class Item Mod"`
Ashes to Assets
Emperor's Shock
Remote Connection
Emperor's Blaze
Hands-On
Enhanced Ashes to Assets
Emperor's Balance
Guardian Angel
Heavy Finisher
Void Battery
From the Depths
Solar Plexus
Light Reactor
Pump Action

`"Class Item Armor Mod"`
Insulation
Dynamo
Empty Mod Socket
Better Already
Invigoration
Distribution
Light Conductor
Bleeding Edge
Recuperation
Blast Off
Absolution
Bomber
Innervation
Enhanced Bomber
Dire Artillery
Outreach
Storm of Lead
Perpetuation
Bulwark Finisher
Healthy Finisher
Special Finisher
One-Two Finisher
Snapload Finisher
Explosive Finisher

**Comment by vthornheart-bng** [comment]
Ah, unfortunately these strings are sourced game-side: but I will let them know that the naming convention changed.  I'm unsure if it was intentional or not!
