### ISSUE TITLE
The Any Energy Type doesn't have an icon

### ISSUE THREAD

**Issue by JpDeathBlade** [Bungie-net/api#1181]
The Any EnergyType [hash: [1198124803](https://data.destinysets.com/i/EnergyType:1198124803)] and Any Energy Type Cost [hash: [3578062600](https://data.destinysets.com/i/Stat:3578062600)] doesn't have an icon. They should be a tiny hammer.

![tiger_release_final_20191223_225849](https://user-images.githubusercontent.com/1441829/71679840-89c44480-2d56-11ea-9ea5-f83ed42cd30c.png)

**Comment by vthornheart-bng** [comment]
Ah, good catch, thank you!  I will file a bug on this.

**Comment by vthornheart-bng** [comment]
TFS 860342
