### ISSUE TITLE
Activity 1412142789 Is not returning details

### ISSUE THREAD

**Issue by kramrm** [Bungie-net/api#1182]
This activity is not returning any name/description/image when looking up the definition.

https://data.destinysets.com/i/Activity:1412142789

**Comment by justrealmilk** [comment]
what should it be

**Comment by kramrm** [comment]
I honestly don't know.  I just double checked, and it is no longer showing in my list of available activities.  All I see is Last City/Story/PvE, and don't have confirmation of what it exactly is.
