### ISSUE TITLE
PVP Match In Progress Data

### ISSUE THREAD

**Issue by TitoLasVegas** [Bungie-net/api#1185]
I've been looking around and I don't think live match data is currently available, and if not I'd like to request this to be added to the wishlist. I'm talking about in-match data. 

GetProfile gives me the playlist, map and my own fireteam (great), but nothing about my opponents.

GetActivityHistory and PostGameCarnageReport have all the data components I need but aren't available until after the match completes.

Look at destiny trials report website as an example. This is a pvp community need.

**Comment by vthornheart-bng** [comment]
Unfortunately, the stats system is at its core set up to be a process that can only accumulate data after an activity has ended completely.  This is not great, and there's been conjecture about an alternative system: but the cost and time it would take to do that replacement wholesale is unfortunately extremely large given the dependencies on the existing systems.

I've got it as a wishlist item for the distant future, should we reach a point where we can pay those costs: but I don't know if or when it will ever come about unfortunately.

**Comment by StormTester** [comment]
A quick point for consideration, returning all users in an activity would be amazing, even if you weren't able to return the stats of the current activity in real-time.

Just posting this on the off chance that there may be some internal workaround to provide this data with the current system, through the current features in place that allow you to check who's in your fireteam and what map/mode you're in.

**Comment by vthornheart-bng** [comment]
Aye - I was hoping that the data in the new "Transient" property would serve this purpose, but the reports I've been hearing is that it's been unreliable, and at best has only your own Fireteam.  I'll be bringing it up in the coming months internally, as I'd like to see us get that sort of info - not only for those of you who want this data externally, but internally as well it'd be really useful for our own apps and features!

**Comment by StormTester** [comment]
Nice. Looking forward to hear what comes of that.

I've been using the Transitory component for a while now for my discord bot, really useful to give quick summaries about how many raid clears everyone in your fireteam has or their PVP stats as well as loadouts. Haven't personally experienced any unreliable data or complaints from users about inaccurate information, although I am only using it to get membershipId and displayName's, can't comment on the other data it provides.

**Comment by TitoLasVegas** [comment]
Matches what I've seen. The Transitory component has my own fireteam but stops there. I haven't seen anything odd or that I'd call unreliable. I assumed during development this was to prevent some sort of match making abuse, but thinking again you'd have to be locked into the match for this data anyway.

As a note I've used it for CharacterIds to then begin looking at which character is active, classes, and eventually equipment loadouts. 

Also looking forward to any updates later!

**Comment by rslifka** [comment]
I'm not sure if 2.5 years is a distant enough future, but alas here we are :)

From an earlier comment:

> returning all users in an activity would be amazing

Yep! Nothing more than that; we can do the rest.

🤞

**Comment by jukebox42** [comment]
+1 membershipId and MtembershipType for all players in an activity would be perfect :). teamId if you are feeling generous
