### ISSUE TITLE
Activity medals definitions and PGCRs round-up

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1186]
Greetings earthlings.

I come to you today with a request: give medals! I've done some digging and found a bunch of related issues for your 2020 perusal.

#### No icons
#762 Gambit medal icons not in definitions: still an issue but it can be worked around.

#### Medals missing from PGCRs
#900 Gambit Prime medals not yet being returned: I'm unsure of how true this is today but I can tell you with certainty that very few medals are returned with PGCRs, at least from Gambit. _The Drifter, not unlike Lord Saladin, hands out medals like he's having a closing down sale._
#1291 Medals missing from Trials of Osiris reports

#### Issues where `statDescription` is a copy of `statName`
#1147 Iron Banner Medals include incorrect description
#887 Medal Descriptions Aren't Descriptive

**Comment by vthornheart-bng** [comment]
Ah!  Thank you for aggregating these requests, I appreciate it!

We're up to our ears in other urgent work at the moment, but I am going to push this request to folks.

**Comment by justrealmilk** [comment]
Thanks vthorn

Personally, I'm only concerned with #900, but I thought as I was going to bother with you with a whole issue that I may as well collate related

**Comment by vthornheart-bng** [comment]
It is good, I appreciate your thoroughness!

**Comment by t3rr11** [comment]
I would also like to add, Doubles medals also do not show up in PGCRs. They just return: "medalUnknown".

**Comment by justrealmilk** [comment]
I suspect that wherever a medal can not be found server side, it returns an instance of `medalUnknown` kind of like a "hey there's things here but idk about them"

**Comment by t3rr11** [comment]
Yup, I think you'd be right on the mark with that assumption. Interesting that doubles aren't found though, guess that didn't come out with the base game as i thought it did.

**Comment by t3rr11** [comment]
Just to add to this even more, I'd love trials medals to be added whenever you guys get around to medals. Currently every game just adds 1 x unknown medal. Not even sure what that would be tbh haha

**Comment by justrealmilk** [comment]
I wonder if the reason why it's not so easy is because the servers that process and save PGCR data need to be messed with. Understandably a big ask just for medals. But eh

**Comment by v-fedorov** [comment]
bump!
