### ISSUE TITLE
Global effort endpoints

### ISSUE THREAD

**Issue by t3rr11** [Bungie-net/api#1187]
I know it's a really late ask, but any chance we could grab an endpoint for the upcoming global effort? These events seem to be occurring more often and i would love to see endpoints for them.

**Comment by vthornheart-bng** [comment]
That is a really good question.  I've been knee deep in work unrelated to the API that has taken up all of my time, I haven't actually had a chance to even ask them how they're doing it this time around!

So I don't know how feasible it is right now.  But @jshaffstall-bng has been taking over API maintenance in my stead, I will file a bug and hit him up about it if he ends up with time to investigate!

**Comment by kramrm** [comment]
https://data.destinysets.com/i/Record:3393252660 appears to be related to donated fractaline, but caps at 5000.  If it is possible for that to overflow, that would be appreciated (and hopefully not too difficult)

**Comment by t3rr11** [comment]
You legitimately beat me to it, Please have this overflow come back as i use triumphs as well a way to track player data like this and having this capped means it will give inaccurate results.

**Comment by vthornheart-bng** [comment]
Ah!  I would like to see that too - let me ask some people.  The API doesn't actually control whether we get overflow, but I can hit up someone on the game side and see if it'd be possible in the future.

**Comment by t3rr11** [comment]
We all managed to find a progression that lets us get passed this issues, this time around, but if possible i'd still like to find out if it's possible to continue the overflow on the last objective node as i use that as my main source of information gathering as not everything is progression related. Unless it could be 🤔

**Comment by joshhunt** [comment]
FWIW, the progression hash 2480822985 tracks how much that user has donated, and it goes over 5000.

**Comment by vthornheart-bng** [comment]
Ah, good, I'm glad there's at least something available that you all can use even if it's not the most convenient path to it!

**Comment by t3rr11** [comment]
I love you guys. Thanks for the pursuit to track this time around! :D
