### ISSUE TITLE
What is TigerDemon (Membership Type: 10)?

### ISSUE THREAD

**Issue by MarkAlmighty** [Bungie-net/api#1188]
Per the subject, what is membership type 10 "TigerDemon"? I can't figure out where I came across its existence, but I put it into a list along with 0:None, 1:Xbox, 2:PSN, 3:Steam, 4:Blizzard, 5:Stadia, 254:Bungie, -1:All.

**Comment by vthornheart-bng** [comment]
Ah, a fair question!  The gist is that this was an account type used exclusively for internal testing during the Destiny 1 time period.  Because some internal test environments still have such accounts for legacy testing, and for backwards compatibility, it's basically going to live as a membership type forever even though it's no longer used.

**Comment by MarkAlmighty** [comment]
> 
> 
> Ah, a fair question! The gist is that this was an account type used exclusively for internal testing during the Destiny 1 time period. Because some internal test environments still have such accounts for legacy testing, and for backwards compatibility, it's basically going to live as a membership type forever even though it's no longer used.

Great, thanks for the quick answer! That tells me I don't have to bother accounting for it in my Destiny 2 web app.

**Comment by vthornheart-bng** [comment]
No prob, glad to be of help!

**Comment by floatingatoll** [comment]
@vthornheart-bng Is there an "active platforms" list in a manifest somewhere that does _not_ include Tiger and Battle.net and _does_ include Stadia? This isn't exactly a request per se, but if it's already buried in a manifest somewhere, that would be useful for app authors.

**Comment by vthornheart-bng** [comment]
There isn't, but there _ought to_ be!  Right now we expose just the BungieMembershipType enum, which is full of historical cruft.  I dig the idea of exposing a more curated subset in some form.  Hopefully for now though, folks who want to work with the API will be able to infer which Membership Types are relevant for them from the ones we support in the real world.  We may have to hold with that for the time being.
