### ISSUE TITLE
D2-GetProfile: Talent Grid Nodes Empty for Subclasses

### ISSUE THREAD

**Issue by yagottahavehart** [Bungie-net/api#119]
Following Sept 12's maintenance, when requesting **ItemTalentGrids**(306) from GetProfile, all item instances, including subclasses, have an empty **nodes** array.

`{
  "id1":{"talentGridHash":3745224476,"nodes":[],"isGridComplete":false},
  "id2":{"talentGridHash":3774745298,"nodes":[],"isGridComplete":false},
  "id3":{"talentGridHash":2307176982,"nodes":[],"isGridComplete":false}
}`

Note: Calling GetItem directly also yields an empty talent grid nodes array.

**Comment by vthornheart-bng** [comment]
Good info, thanks!  I will look into this.

**Comment by v-fedorov** [comment]
Possibly related to #94

**Comment by vthornheart-bng** [comment]
Aye, very possible/probable.  I'll keep this one open for now just in case there's different root causes, but my suspicion is there won't be.

**Comment by yagottahavehart** [comment]
This looks fixed as of Sept 18th maintenance around 12:20PM Eastern.

Thanks!

**Comment by yagottahavehart** [comment]
This looks like it's popped up again: { talentGridHash: 465529128, nodes: [], isGridComplete: false }
The empty nodes array started sometime last week.

Thanks

**Comment by vthornheart-bng** [comment]
Interesting - is this happening intermittently, or consistently?  If it's happening consistently, can you send me the account and character ID that it's happening to?
