### ISSUE TITLE
Expose item instance acquisition time

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#1191]
From https://www.bungie.net/en/Explore/Detail/News/48723

“All items have a timestamp, based on when they were first added to a player’s inventory.”

I would love to have this timestamp exposed via the API for item instances! I think I’ve asked for it before but it’s good to get confirmation that this property exists. Having this would allow us to sort by acquisition time and provide other interesting sorting and display options around item age.

**Comment by jshaffstall-bng** [comment]
oh no, the secret's out!

**Comment by ckhicks** [comment]
Holy wut that could make for some super interesting visualizations. 🤤

**Comment by vthornheart-bng** [comment]
Well, there's good news and bad news.  The bad news is that what they referred to as a timestamp was a bit of a simplification to make it easier to explain to folks.  The truth is that it's a "sequence number" - which is more of an ever-incrementing number assigned when an item or stack first came into your inventory.  Unfortunately, that means you wouldn't be able to determine an actual date from it, but you *would* be able to figure out the order in which items were added to the inventory according to the game.  Would provide some crude ability to sort oldest to newest etc.

Given that there's sorting in the game now that is based off of this, this still may be of some use to you folks!  Would you want this data still?

**Comment by vthornheart-bng** [comment]
(I should also note there may be data inaccessible to Bungie.net with real dates - but the thing they were referring to in the quote above and in the data we can access at this time, it's that sequence # rather than an actual date)

**Comment by floatingatoll** [comment]
Is item instance ID sequential already?

**Comment by ckhicks** [comment]
I think that property is still super interesting, personally. It'd be neat to show your collection sorted by order of acquisition, etc. Might be a small thing but fun to have if it's easy to have accessible on each item.

**Comment by vthornheart-bng** [comment]
@floatingatoll Aye, the difference is that this sequence ID is applied to both instanced and non-instanced items.

Good to know!  Yeah, that's definitely something we could plumb through.

**Comment by bhollis** [comment]
Thanks for the explanation! I think having the sequence ID would be super interesting for us.

**Comment by vthornheart-bng** [comment]
Sweet!  Definitely feasible.

**Comment by bhollis** [comment]
There are definitely a handful of very interesting features we could implement in DIM if we had access to this number - we'd like to do some processing the first time we see an item instance, and with access to this sequence number we could keep a per-account high water mark to keep track of what we'd already seen.
