### ISSUE TITLE
Public milestone endpoint is usually failing

### ISSUE THREAD

**Issue by dcaslin** [Bungie-net/api#1192]
This API call: 

https://www.bungie.net/Platform/Destiny2/Milestones/

fails *most* of the time with the following: 

```
{
    "ErrorCode": 3,
    "ThrottleSeconds": 0,
    "ErrorStatus": "UnhandledException",
    "Message": "We've encountered an error, please try again later.",
    "MessageData": {}
}

```

It very occasionally works (I saved a canned copy of the response as a workaround in my app)

**Comment by jshaffstall-bng** [comment]
Thanks for the report! We're tracking this internally with TFS 873314, and will hopefully have a fix for it soon.
