### ISSUE TITLE
Plans to update "3D Content Documentation" wiki page?

### ISSUE THREAD

**Issue by TiredHobgoblin** [Bungie-net/api#1193]
I noticed that the "3D Content Documentation" page of the wiki is missing a significant amount of information. I'm working on a project that uses shader parameters, but without knowing what each parameter contains, I've hit a wall. Are there currently any plans to finish adding that information to the page?

**Comment by ckhicks** [comment]
There are a few of us who would love this - it didn't make the cut last time everyone was polled, however. See: https://github.com/Bungie-net/api/issues/1158#issuecomment-565621238

Have you taken a look at this? https://lowlidev.com.au/blog/articles/porting-spasm-to-threejs/

**Comment by TiredHobgoblin** [comment]
Thanks for pointing me to the wishlist, I probably should have looked there before asking. I’m a bit frustrated that the wiki page isn’t likely to be updated, but at least I know that it isn’t in the cards for now. 

Regarding the lowlidev blog, I have looked at it. The article itself doesn’t really have much information, but the gear viewer code on his GitHub helped a bit. I was able figure out the specular parameters based on that, but it doesn’t implement any of the other ambiguous multi-parameter arrays, like the PBR parameters.

I guess this means I’ll have to figure it out through trial and error, but at least I won’t lose myself looking for documentation that doesn’t exist. Thanks for pointing me in the right direction.

**Comment by ckhicks** [comment]
You're welcome! It's something I'm super interested in as well - specifically around the idea of 
interpreting Gear Dyes to derive that metal vs plastic look. The official Companion app does _such_ a good job...if you find anything I'd love to learn from your progress! Godspeed.

**Comment by hellosaumil** [comment]
+1
