### ISSUE TITLE
Legal use of the API

### ISSUE THREAD

**Issue by magnusws** [Bungie-net/api#1194]
As i have been looking for documentation for terms of use of the API i have yet to find anything that clarifies what use cases Bungie intend this API to be used for. Is it possible to add something like this in the Wiki? Alternatively add a section for developers in the ToS on bungie.net (it now only refers to content creators).

I am currently in the process of publishing my first iPhone app using the Bungie API, but are having trouble getting it approved by Apple due to the fact that my App Store screenshot show my app displaying items from Destiny 2 and i therefore get flagged for being a possible copycat. I am sure I'm not the first one running in to this issue.

Thank you for creating and maintaining this awesome API. As a computer science student it has been a really great API to use for learning!

Best regards

**Comment by vthornheart-bng** [comment]
Greetings!

Oh yeah, so I can't personally make any legal etc... commentary or decisions, but if it helps the Terms of Service has a section titled "BUNGIE.NET API TERMS AND CONDITIONS".  I've been told to point people over to that! (https://www.bungie.net/7/en/Legal/Terms)

**Comment by floatingatoll** [comment]
I am not a lawyer, nor a Bungie employee. I observe the following highly-relevant block of legalese from that link, which I suspect Apple will most appreciate if you point out:

GAME CONTENT USAGE RULES

**Comment by magnusws** [comment]
Thank you for pointing me in the right direction!
