### ISSUE TITLE
ExpirationInfo filtering

### ISSUE THREAD

**Issue by rraziel** [Bungie-net/api#1195]
Hello,

I want to display a list of records/triumphs, which obviously includes triumphs from past season (e.g. weekly PvP for season 6).
While the `completionInfo` in the record definition mentions that it has an expiration, and while there is a `description` with complete text saying when it was available, I can't seem to find a more programmable way to match a record with either a season or some kind of timeframe/availability.
Is there such a thing available right now, and if so where would that be?

Thanks (and as has been mentioned many times, great work on the API 👍 )

**Comment by vthornheart-bng** [comment]
I'm glad that it's been useful so far!

Unfortunately, there isn't really a hard association between the seasons and the triumphs at the moment that I know of.  These expirations are essentially tied to dates (it's a little more complicated than that, but that's the gist of what it results in), but those dates aren't actually firmly tied to the season itself: it's more or less coincidental that they happen to match based on the folks creating the content.

However, I think that'd be useful - not just in the API, but in the game itself, if it were to provide some hint in the UI as to the season when it will expire based on some more explicit relationship.

I'll bubble it up - if someone on the game side likes that idea too, perhaps it could be become something that we could expose!
