### ISSUE TITLE
Heroku Post Request

### ISSUE THREAD

**Issue by keyute** [Bungie-net/api#1196]
Is there a way to add multiple domains while maintaining the same key? This is because I host my app on heroku but have a custom domain pointed to it. 

My post requests have been giving me error 401.
Code in question:
`
def getAccessToken(request):
	postData = "grant_type=authorization_code&code={}".format(request.GET.get('code'))
	headers = {'X-API-Key': os.getenv('D2_APIKEY'),
	           'Authorization': 'Basic {}'.format(base64.b64encode(
		           '{}:{}'.format(os.getenv('D2_CLIENTID'), os.getenv('D2_CLIENTSECRET')).encode('utf-8'))),
	           'Content-Type': 'application/x-www-form-urlencoded'}
	response = requests.post('https://www.bungie.net/platform/app/oauth/token/', data=postData, headers=headers)
	return response
`

**Comment by keyute** [comment]
Strange code pasted formatting is messed up on my end. https://pastebin.com/gC5wWUHE

**Comment by rraziel** [comment]
As a related issue, I have branches deploying to different domains (*.ci.domain.name) so having the ability to at least use a wild card would be convenient

**Comment by Tetron-bng** [comment]
It is not clear that multiple domains is your problem. There are two places that a domain may come into play: redirect URL and Origin header.  Your redirect URL must be working or else you would not be getting to the point of sending a POST to the token endpoint.  Does the body of the 401 response have any further information?

**Comment by keyute** [comment]
Fixed it, the issue is my authorization header is not properly encoded to ascii

**Comment by hellosaumil** [comment]
@keyute I'm facing the same problem, can you share a snippet of how you gixed it? Thank you.
