### ISSUE TITLE
Missing public milestone info

### ISSUE THREAD

**Issue by rraziel** [Bungie-net/api#1197]
Hello,

The milestones endpoint could use the following little tweaks, if/when possible:
- add the Nightmare Hunts milestone, `2246196133`
- add the Nightmare Hunts Master milestone, `3881226684`
- use the Vanguard icon for the vanguard bounties milestone, `2709491520` (no icon right now)
- use the Crucible icon for the crucible bounties milestone, `2594202463` (no icon right now)
- use the Gambit icon for the gambit bounties milestone, `3802603984` (no icon right now)
- use the Gunsmith(?) icon for the gunsmith bounties milestone, `3899487295` (no icon right now)
- fix the Xur milestone `endDate` (currently `startDate` + 7 days), `534869653`
- a bit late now for the Sundial milestone but it would be nice to have next season's activity

That's about it 👍 

Note: I saw issue #1192 mentions this endpoint usually returns errors, haven't noticed that here so maybe it's fixed (or maybe it's because I'm doing it without being a signed-in player)

**Comment by rraziel** [comment]
Also, I may have missed it but I don't see the legacy nightfalls in there either 🤔

**Comment by justrealmilk** [comment]
you should try `characterActivities` component of the Profile endpoint instead!

**Comment by rraziel** [comment]
Oh I know it's there, but it would be simpler to get it from the milestones as it's global anyway (+ Bungie.net can even cache it)
But yes for signed-in players I also go fetch their character activities
