### ISSUE TITLE
Unknown Medal returned in post game report

### ISSUE THREAD

**Issue by mikechambers** [Bungie-net/api#1198]
https://stats.bungie.net/Platform/Destiny2/Stats/PostGameCarnageReport/5751594268/

If you look at the player "gego", there is an unknown medal passed through the API data:

`
                        "medalUnknown": {
                            "basic": {
                                "value": 1.0,
                                "displayValue": "1"
                            }
                        },
`

Not sure if its an API issue, but I wanted to report it just in case.

**Comment by justrealmilk** [comment]
My theory is that this is returned when whatever generating the reports encounter a medalHash it doesn't recognise

Get it in Gambit a lot
