### ISSUE TITLE
Q: Will this season's progressions be removed from GetProfile next season?

### ISSUE THREAD

**Issue by as-com** [Bungie-net/api#1199]
e.g. will the Fractaline Donated progression remain in the GetProfile response after next Tuesday?

**Comment by vthornheart-bng** [comment]
Ah, I need to look into that!  Unfortunately I'm not sure offhand.  I can give that a peek tomorrow!

**Comment by TorKallon** [comment]
If it drops to zero, don't delete the numbers you have saved?

**Comment by as-com** [comment]
@TorKallon you're making a bold assumption that I already have all the numbers I need saved... which I don't :P 

(I should also mention that while I do keep old data, it's expensive in my design to extract e.g. progressions from said old data)

**Comment by vthornheart-bng** [comment]
I should note that if the game isn't keeping it, it'll be too late to change unfortunately. :(  Unlike the web side, a change like this would've had to happen a few weeks ago in order to prevent the data's destruction.  But hang tight, let me see what I can find out.  What hash are you guys using to find this data?  I've been knee deep in another project and haven't been paying attention to the latest game content changes this season.

**Comment by as-com** [comment]
@vthornheart-bng Progression 2480822985 ("Donated Fractaline")

**Comment by vthornheart-bng** [comment]
Ah shoot, bad news guys.  I went to look in the upcoming release, and it looks like that progression has indeed been removed.

**Comment by TorKallon** [comment]
No sweat -- as long as we have notice we can store it.

**Comment by vthornheart-bng** [comment]
Phew, good deal!

For better or for worse, I think the rule of thumb for seasons going forward will be to assume that it won't exist after the season is over, unless it's something you can still use afterwords (like weapons/armor/etc... that happens to be new for the season).  Sometimes we'll luck out and they'll keep some content, but they're trying to reduce "dead weight" content that's no longer directly needed by the game to keep sizes and content complexity lower.

**Comment by as-com** [comment]
Closing because the question was answered
