### ISSUE TITLE
[Question] Auth flow for programmatic use (e.g. OAuth Implicit)

### ISSUE THREAD

**Issue by rslifka** [Bungie-net/api#12]
I'm working on a Ruby gem (no UI) to wrap some commonly used API calls. Given that there are no credentials for bungie.net proper, is this flow even supported? I.e. what client key and secret do I use to kick off OAuth Implicit with Bungie?

**Comment by vthornheart-bng** [comment]
Aye, unfortunately we don't support OAuth implicit.  Sorry about that!

**Comment by rslifka** [comment]
No worries sir, thanks so much for the quick response! 😄
