### ISSUE TITLE
What is the itemReferenceHash for TransferItem?

### ISSUE THREAD

**Issue by MarkAlmighty** [Bungie-net/api#1200]
When trying to do a TransferItem, what is the itemReferenceHash? Is it [Response][item][data][itemHash] from doing GetItem?

**Comment by vthornheart-bng** [comment]
Ah, yes indeed it is!  It's a throwback from very, very old times.  I should have taken the opportunity to rename it itemHash when we ported code over to Destiny 2, but it was a lost opportunity.

**Comment by MarkAlmighty** [comment]
Noted, thanks!
