### ISSUE TITLE
DestinyActivityModeType: Trials of Osiris 2020

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1202]
Hey! I was wondering and hoping for a new modeType for Trials! 

Due to how the game has changed enormously since 2017, I was hoping for a fresh start. I think it's appropriate.

I've opened an issue because in the past there's been times where modeTypes have been reused

**Comment by jshaffstall-bng** [comment]
Yes, there will be a new activity mode type for Trials of Osiris, separate from ye olde Trials of the Nine modes.

Thanks for asking!
