### ISSUE TITLE
Record progress values

### ISSUE THREAD

**Issue by t3rr11** [Bungie-net/api#1203]
I was just curious on how the records track their progression. More specifically raid records and dungeon records.

I use records to track users activity completions and i noticed that some records continue to keep tracking progress whilst others do not and i was just wondering what defines if one can track after the first time.

If we look at the Last Wish completion record: `2195455623`, It returns (in my case): 
```
"state": 67,
"objectives": [
    {
        "objectiveHash": 4277237076,
        "progress": 102,
        "completionValue": 1,
        "complete": true,
        "visible": true
    }
],
"intervalsRedeemedCount": 0
```
The progression node will continue to go up for each raid completion. But if we look at the shattered throne record: `2314271318`, It returns:
```
"state": 67,
"objectives": [
    {
        "objectiveHash": 944327687,
        "progress": 1,
        "completionValue": 1,
        "complete": true,
        "visible": true
    }
],
"intervalsRedeemedCount": 0
```
No matter how many shattered throne completions a user does this will no longer progress. Is there something that defines whether or not a record can continue to progress and is this the way records are going to be in the future as i assume this is in order to save the amount of requests the game server makes to the api? More just interested tbh.

**Comment by justrealmilk** [comment]
I suspect this is just due to the way "triggers" are set up game-side by whatever team that handles this stuff

**Comment by delphiactual** [comment]
These emblems keep track of those stats:

https://data.destinysets.com/i/InventoryItem:298334061

https://data.destinysets.com/i/InventoryItem:185321778

**Comment by t3rr11** [comment]
You can't get emblem data without O-Auth can you? Otherwise i'd totally be down to use that :/

**Comment by delphiactual** [comment]
No, but this means the data is available somewhere and just needs exposed.

**Comment by t3rr11** [comment]
Oh i see! Hopefully they can just translate it!
