### ISSUE TITLE
Rasputin Vendor(s) missing Daily Bounties

### ISSUE THREAD

**Issue by ttgmpsn** [Bungie-net/api#1206]
Hey, despite unlocking it in-game, the API doesn't report the Daily Bounties for the three Rasputin Vendors. The two Weekly Bounties, rank-up stuff etc shows up, the dailies do not.

Is this a similar issue like Petra being unable to be fetched, where the game requires you to be in a certain state (I could imagine "Daily Vault clearance finished" for the Warmind Bounties), and the API is unable to confirm this with the user offline?

Thanks!

**Comment by JonnyOThan** [comment]
I'm seeing this as well.

**Comment by ttgmpsn** [comment]
The vendor does not exist anymore.
