### ISSUE TITLE
Xur?

### ISSUE THREAD

**Issue by CrunchyWizard47** [Bungie-net/api#121]
I presume he's going to show up as a vendor now, rather than as a milestone, but the Get Vendor(s) endpoints are in preview. Can you confirm where his information will be available? I'm working on a script to make this info available for my clan. Thanks!

**Comment by vthornheart-bng** [comment]
He'll always be both a Vendor and a bnet-only-Milestone, but indeed he'll start returning his items (possibly in both?  I haven't decided the specifics yet) once we get the Vendor implementation working again.

I am hoping that we'll have Vendors working again before November, though the pace of other issues that are popping up and some more immediate game integration tasks have been taking precedent.  When I have a more solid date, I'll share it in the readme!
