### ISSUE TITLE
Add LastSeenDisplayNameType to various endpoints

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1210]
- GetProfile (Profile component)
- GetMembershipDataForCurrentUser

`LastSeenDisplayNameType` is a property of `GetMembersOfGroup`. I'm not sure about the name but it'd be great to be able to consume it elsewhere.

We'd all love it!

**Comment by justrealmilk** [comment]
Less important but I'd also love to see which platform a PGCR was captured from

**Comment by justrealmilk** [comment]
VThorn: we must do what we can to make API calls cheaper and more efficient 🌟
Tom: 📢 ALL THE DATA, 📢 ALL THE PLACES, 📢 ALL THE TIME

**Comment by justrealmilk** [comment]
Cheeky bump. Would be great to see this added to the CharacterActivities Profile component

**Comment by jshaffstall-bng** [comment]
Sorry this got lost, and I don't know if this is feasible for those other APIs, but I've filed TFS 974283 for us to check it out.

**Comment by justrealmilk** [comment]
Now that crossplay is about to go live, it'd be great to see this value added to a super common Profile component such as Profile
