### ISSUE TITLE
Metrics vs Historical Stats Mismatch

### ISSUE THREAD

**Issue by t3rr11** [Bungie-net/api#1224]
I was making something that used the historical stats data to get overall user data and using the new metrics to get seasonal data and noticed a massive data mismatch. 

I was testing with my account which has no deleted characters (4611686018471334813) which makes it great for testing this data mismatch.

The endpoints i was using are: 
`/Platform/Destiny2/${membershipType}/Profile/${membershipId}/?components=1100` 
and
`/Platform/Destiny2/${membershipType}/Account/${membershipId}/Stats/?groups=101`

Under metrics the Total Final Blows hash `2537844000` returns: 929,353 kills.
Under historical stats `mergedAllCharacters.merged.allTime.kills` it returns: 484,095 kills.

This isn't the only mismatch either. 

Under metrics the Final Blows hash for overall crucible kills `811894228` returns 69,129.
But under the historical stats `mergedAllCharacters.results.allPvP.allTime.kills` it returns: 51,065

Let's say that final blows was actually counting assists as well in the metrics, the numbers still don't add up. Something is wrong somewhere.

**Comment by t3rr11** [comment]
There is alot another issue with metrics possibly with it's wording or math. Under the trials of osiris metrics they also have "Final blows" for weekly, seasonal and overall. These are not accurate as they take in to account Kills + Deaths. Not just Final blows.

In-Game:
![image](https://user-images.githubusercontent.com/2139233/78358208-52d22900-75fa-11ea-9ddb-663b6be5fa21.png)

From the API: 
![image](https://user-images.githubusercontent.com/2139233/78358306-83b25e00-75fa-11ea-8f53-d9cbf77bef23.png)

As you can see in this instance if you add the Kills and Assists you get the value shown in-game.

**Comment by vthornheart-bng** [comment]
Thank you, good sleuthing!  I passed this on to folks who are taking a look.

**Comment by t3rr11** [comment]
Thanks heaps as always! :D

**Comment by t3rr11** [comment]
Hey if it helps my point even more, For crucible overall i use HistoricalStats, for Seasonal i grab that from the Metrics. 

This is a hacker (obviously) where their seasonal (metric) says they have more pvp kills than their overall (historical stats) kills. 

![image](https://user-images.githubusercontent.com/2139233/79068469-3757d400-7d06-11ea-8885-70c5b8821e6e.png)

MembershipID: 4611686018501678305 (to verify their stats don't match their metrics)

**Comment by justrealmilk** [comment]
Are you sure the difference isn't one "stat" counts assists where as another is only final blows?

**Comment by t3rr11** [comment]
I don't think so... but possibly, None of the tests i've done other than the trials one shows that  being the case.

**_Overall: (4611686018471334813)_**
Historical Stats - (mergedAllCharacters.results.allPvP.allTime)
Kills: 51,498
Assists: 17,557
Total: 69,055

Career Metric - (metrics.data.metrics[811894228].objectiveProgress.progress). Final blows: 69,684
Record - Fierce Competitor (3015941901) also shows 69,684.

There is no way (that i know of) to track seasonal final blows other than Metrics. So i found an account that is 1 day 20 hours old as of making this post so it can be reasonable to say that this accounts overall would reflect seasonal progress.

**_Account: (4611686018501995493)_**
Historical Stats - (mergedAllCharacters.results.allPvP.allTime)
Kills: 2,365
Assists: 151
Total: 2,516

Career Metric - (metrics.data.metrics[811894228].objectiveProgress.progress). Final blows: 2,582
Seasonal Metric - (metrics.data.metrics[2935221077].objectiveProgress.progress). Final blows: 2,582
Record - Fierce Competitor (3015941901) also shows 2,582.

So i think i can safely say that it's not just kills and assists. Possible mis-adventures added onto that but like i don't have a clue how to track that or do the math with that.
