### ISSUE TITLE
Search request with specific uppercase letters

### ISSUE THREAD

**Issue by JannisCode** [Bungie-net/api#1227]
I have a python programm where you can ask for all the data a player has and is accesible through the Api, but it would be rather nice if i could just write for example: Player, and get Player and not Player **and** player is it possible to do that

**Comment by t3rr11** [comment]
Which endpoint are you using for your search? Also just to make sure i am reading correct are you hoping to just have that search request return a single result or all results that match specific capitalization?

**Comment by JannisCode** [comment]
> Which endpoint are you using for your search? Also just to make sure i am reading correct are you hoping to just have that search request return a single result or all results that match specific capitalization?

Just one specific result for example when i search "Zombey" i just want to see "Zombey" and not "Zombey" and zombey

**Comment by delphiactual** [comment]
filter your results as you see fit (e.g. remove the ones that do no match completely)
