### ISSUE TITLE
Is it possible to have unlimited OAuth Tokens?

### ISSUE THREAD

**Issue by JannisCode** [Bungie-net/api#1231]
And thats the Question^

**Comment by justrealmilk** [comment]
You should join the Discord https://discord.gg/jXmknj

**Comment by Tetron-bng** [comment]
Do you mean unlimited in the sense that an OAuth token and be used for anything?  Or unlimited lifespan?  Or an unlimited refresh without user's additional consent?   The answer in order: no, no, and yes for up to one year with confidential client as long as it is refreshed every 90 days.

**Comment by JannisCode** [comment]
Meant it timewhise, sorry. Thanks
