### ISSUE TITLE
Season of the Worthy End Date

### ISSUE THREAD

**Issue by andyschott** [Bungie-net/api#1236]
Based on [this tweet](https://twitter.com/BungieHelp/status/1254853787316916224), Season of the Worthy ends on June 9 at the weekly reset. However, if you read the season info from the manifest database (hash 4035491417) it says the season ends on June 16 at the weekly reset.

Assuming the tweet is correct, would it be possible to update the manifest database with the correct end date for this season?

**Comment by Achronos-BNG** [comment]
This will be fixed next week.
