### ISSUE TITLE
Impossible to compute "original" investment stats for armor if stat is below zero.

### ISSUE THREAD

**Issue by ArkahnX** [Bungie-net/api#1237]
To clarify, If I have a gauntlet with 2 strength, and apply the mod "protective light" (-10 strength) the API will report the gauntlet as having 0 strength (visually this is the same as in game) however the total strength stat of a guardian will be reduced by the full 10, regardless of what the strength stat says (effectively it's -8, but the game caps it at 0)

Would it be possible to have the raw values of stats, unmodified by armor mods returned in the API? for cases like above, you have a potential 1-10 points in strength that are impossible to guess because the stat is capped at 0 in game and the API, despite having an actual value of -8 as per my example.

A range of 1-10 could be an entire stat tier in game, so lacking that data is fairly significant if you are trying to judge whether an armor is better than another via the API without going in game and unslotting any negative stat mods

**Comment by ryan-rushton** [comment]
I would also be happy with stat values that aren't 0 capped.
