### ISSUE TITLE
bnetMembership returning as JsonNull and is unusable

### ISSUE THREAD

**Issue by TooTallLenny** [Bungie-net/api#1238]
Hello I'm working on a final project using the Bungie API and I'm new to external API stuff so is my group. We were on a roll until we needed the destinyMembershipId for the GetProfile path. I used postman and have found that this path has the bnetMembershipId I need. 

http://www.bungie.net/Platform/Destiny2/2/Profile/4611686018429022888/LinkedProfiles/

I'm running this code to try and get it. We are flip floping between trying two methods(the one that is commented out is what we used to get JsonArray into JsonObject)

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonElement;
import com.google.gson.JsonNull;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.google.gson.JsonPrimitive;

public class GetBungieAccount  {
    private static String apiKey = "blank for confidentiality";

   public static String getBungieAccount(String membershipId, String membershipType) throws Exception{
        String url = "http://www.bungie.net/Platform/Destiny2/"+ membershipType+ "/Profile/" +membershipId+ "/LinkedProfiles/";
        URL obj = new URL(url);
        HttpURLConnection con = (HttpURLConnection) obj.openConnection();
        con.setRequestMethod("GET");
        // Set header
        con.setRequestProperty("X-API-KEY", apiKey);

        //int responseCode = con.getResponseCode();
        // System.out.println("\nSending 'GET' request to Bungie.Net : " + url);
        //System.out.println("Response Code : " + responseCode);

        BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
        String inputLine;
        String response = "";

        while ((inputLine = in.readLine()) != null) {
            response += inputLine;
        }

        in.close();

        /* GsonBuilder builder = new GsonBuilder(); 
        builder.setPrettyPrinting(); 
        Gson gson = builder.create();

        JsonObject ResponseObj = gson.fromJson(response, JsonObject.class);

        JsonElement finalObj =  new JsonObject();
        for(JsonElement value : ResponseObj.getAsJsonArray("Response")){

            finalObj = value;                
        }
        System.out.println(finalObj.toString()); //TEST TO ENSURE THAT FINAL OBJECT GRABS DATA
        JsonObject finalfinalobject = gson.fromJson(finalObj.toString(), JsonObject.class);
        */

        @SuppressWarnings("deprecation")
        JsonParser parser = new JsonParser();
        @SuppressWarnings("deprecation")
        JsonObject json = (JsonObject) parser.parse(response);

        return json.getAsJsonObject("Response").get("membershipId").toString();

    }
}

We get this error:

Exception in thread "main" java.lang.ClassCastException: com.google.gson.JsonNull cannot be cast to com.google.gson.JsonObject –

**Comment by vthornheart-bng** [comment]
Ooh, something useful you should do is see if you can handle that exception and instead log the raw response as a string (and if you can, log the HTTP status code you're getting back).  Unfortunately I don't know much about those Java libraries you're using, but that will be super useful in being able to diagnose what's happening - for instance, whether you got a response at all.

**Comment by TooTallLenny** [comment]
I'm slightly lost but I'm guessing you mean just print the json response instead of trying to turn it into a string. I tried printing that and it gave me null

**Comment by vthornheart-bng** [comment]
Oh, what I mean is (if possible) grab the raw HTTP response body, and print just that - before trying to do any conversion to JSON.  That raw string variable "response".

**Comment by vthornheart-bng** [comment]
If you do that, it'll help with determining whether you got an unexpected type of response, or if your response stream reading has a bug in it, or perhaps if you even got a response at all.  (for the latter, if the "response" string ends up being null, definitely see if you can log the HTTP status code you got back.  Usually even with errors, bungie.net returns some kind of response body)

**Comment by vthornheart-bng** [comment]
Oh, hmm... so the response string itself was null?  That is interesting.  Yes, definitely try to get the status code and let me know what that is.

**Comment by vthornheart-bng** [comment]
If you end up seeing a 200 status code, this is where my ignorance of the libraries/language you're using makes me less useful... but I suspect that would mean that there's something wrong with how you're reading the response body.  Maybe someone with Java experience could chime in if they spot something.

**Comment by TooTallLenny** [comment]
I just got home from work I gotta shower real quick than I can get that. I have code somewhere to print that

**Comment by TooTallLenny** [comment]
Ok so i got a response code of 302 not 200 like the other ones

**Comment by andyschott** [comment]
I'm not a Java expert, but you might try using [Google's HTTP Client Library](https://github.com/googleapis/google-http-java-client) which is a bit higher level than using `HttpUrlConnection` directly. That might make it easier to make the request and get the response back.

**Comment by TooTallLenny** [comment]
its solved the link was http not http**S** i cant describe how upset i am at myslef we have been stuck on this for a day and a half and we were stuck cause of an s ing the string

**Comment by vthornheart-bng** [comment]
Ahh!  That explains it - glad you found it!  I didn't notice either, good catch.

**Comment by vthornheart-bng** [comment]
(also, don't be upset at yourself!  I've done the exact same thing before!)
