### ISSUE TITLE
[spec] activity list is nullable, currentpage is a query parameter

### ISSUE THREAD

**Issue by archived-2f4dd0** [Bungie-net/api#1240]
`Destiny.HistoricalStats.DestinyActivityHistoryResults.activities` is nullable.
instead of containing an empty array, it'll be completely missing if there's no activities to report.

as reported here, https://github.com/DestinyItemManager/bungie-api-ts/issues/2
`GetMembersOfGroup`
`GetAdminsAndFounderOfGroup`
`GetBannedMembersOfGroup`
`GetPendingMemberships`
`GetInvitedIndividuals`
list `currentpage` as a path parameter,
but i am pretty sure it's actually a query parameter.

actually, the latter is partially a duplicate of https://github.com/Bungie-net/api/pull/192 / https://github.com/Bungie-net/api/issues/124

**Comment by sundevour** [comment]
bonus: putting the `stats.bungie.net` requirement
in the comments for `GetPostGameCarnageReport`
would be cool

**Comment by sundevour** [comment]
some other nullable things:
UserInfoCard.applicableMembershipTypes
UserInfoCard.supplementalDisplayName
