### ISSUE TITLE
I’ve been banned for no reason 

### ISSUE THREAD

**Issue by striker101811** [Bungie-net/api#1241]
I love destiny, I have played it for many years. Since year 1 of d1 I have loved this game and I hate the idea of cheating. Today ( Saturday 23rd May ) I ran a trials passage where every game except 1 was sketchy. At least 1 player from the other team was kicked every game. Both of my lfg team mates were certain they weren’t d dossing and for some reason I believed them. I have now been banned from matchmaking ( pvp, etc ) for two weeks when I wasn’t the one doing the hacks. I’m 14 years old, I have no clue where to start with setting up hacks or whatever. I know this post might get hate I just really hope a dev sees this and can help me out or at least give a good response, even if im unable to get my ban recinded. I hope that someone can get back me to soon as, thank you 

My PS4 gamer tag is Striker101811 for those wondering and if anyone needs to know the teammates gamer tags I will get them you if you ask

**Comment by hellocontrol-bng** [comment]
Hi @striker101811 - I'm sorry for your situation! Unfortunately, GitHub is not the place to report such a situation. The proper place to report this would be the Bungie.net forums, or by utilizing the Bungie.net Help pages for more information. 

Thank you for understanding!

**Comment by striker101811** [comment]
> Hi @striker101811 - I'm sorry for your situation! Unfortunately, GitHub is not the place to report such a situation. The proper place to report this would be the Bungie.net forums, or by utilizing the Bungie.net Help pages for more information.
> 
> Thank you for understanding!

I’m so happy someone replied, thank you for your help!
