### ISSUE TITLE
Missing collision in the Well of Flame on Nessus

### ISSUE THREAD

**Issue by Wolverate** [Bungie-net/api#1245]
When going through the portal at the bottom of the Well of Flame, there's an area on the right where the player can jump out of the intended play area. There's also a gap in the collision where the player can hop into the arena.

Here's the link to a video that will demonstrate the issue: https://youtu.be/UFPR1TbNW4A

Platform: PC
Reproduction rate: 5/5

**Comment by delphiactual** [comment]
This is the API github report game troubles at bungie.net
