### ISSUE TITLE
 I have a very, very serious problem with my account 【我的账户出现了非常非常严重的问题】

### ISSUE THREAD

**Issue by 400682** [Bungie-net/api#1247]
My Steam account has been illegally stolen. However, I am restricted to log in when I retrieve it. There is no banned information on steam. My 16 bit ID: 76561198437086976. My name in the game is strong. My binding email is 599959770@qq.com , please check! Thank you thank you thank you very much help me 【我的STEAM账户被非法盗取，然而我找回被限制登录，STEAM上也暂无任何封禁信息，我的16位ID：76561198437086976，在游戏里的名字是Strong，绑定邮箱是 599959770@qq.com ，请排查！谢谢谢谢万分感谢 ，帮助我一下】

**Comment by 400682** [comment]
I love this game very much when I play this game. I don't know the person who stole my number, so I haven't used illegal programs. I just like destiny2 so much. Since I play this game, there is no game to replace it. I spend a lot of money, and I hope to continue to wear it on all planets!

**Comment by 400682** [comment]
I really like destiny2 very, very much. Please make sure to investigate my account in detail and try to find it after it is stolen. But my account has been maliciously bound to cross save. Xboxone has never bound these things since I bought the DLC of this game.

**Comment by 400682** [comment]
Two seasons that have been blocked, I hope to return to destiny2

**Comment by vthornheart-bng** [comment]
Oy, I'm so sorry!  There's unfortunately nothing that the folks on this Github page can do to help you.  We've got no power or ability to resolve those kind of issues, we just work on the API :(

You'll have to hit up the Bungie Help forum.  Sorry that we can't provide more assistance!
