### ISSUE TITLE
Documentation request: SetQuestTrackedState

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1250]
`SetQuestTrackedState` allows for toggling tracking state on quest items. 

Its request body consists of `Destiny.Requests.Actions.DestinyItemStateRequest` and requires an `instanceId` which prevents it from working on some quest items even though they can be tracked in-game.

It returns `DestinyInvalidRequest` for bounties. It does work on other quest items _with_ `instanceIds` though.

**Comment by jshaffstall-bng** [comment]
Thanks for the heads up!

Docs: TFS 912429
Uninstanced items: TFS: 912432

**Comment by jshaffstall-bng** [comment]
`SetTrackedState` is now documented, but we don't yet have an API for tracking items that don't have an `instanceId`.

![image](https://user-images.githubusercontent.com/25537692/86844771-5cd25080-c05d-11ea-9ea1-a5f348febaf3.png)

**Comment by lowlines** [comment]
Tracking only appears to work with quests. Bounties return a 500 invalid request response.
