### ISSUE TITLE
Missing emblem returned when using Beyond Light emblem.

### ISSUE THREAD

**Issue by fegkay15** [Bungie-net/api#1251]
Self explanatory. When a player has the pre-order bonus emblem equipped, the api returns that the emblem is missing as well as emblemBackgroundPath does not appear.

`"emblemPath": "/img/misc/missing_icon_d2.png",`
`"emblemHash": 3639046089,`

**Comment by justrealmilk** [comment]
This is due to the emblem being marked as classified. It will resolve itself when the emblem is declassified.

**Comment by jshaffstall-bng** [comment]
This should be fixed with the Bnet content update released earlier today. Enjoy!
