### ISSUE TITLE
Metric 2262629298 has neither name nor description

### ISSUE THREAD

**Issue by movsesyanpv** [Bungie-net/api#1252]
As stated in the title, the metric [2262629298](https://data.destinysets.com/i/Metric:2262629298) (I assume it is the season 10 rank) has emptyish `displayProperties`:

```
"displayProperties": {
    "description": "",
    "name": "",
    "icon": "/common/destiny2_content/icons/defb8ccfe5438ec63ca4bc4c94e78d8a.png",
    "iconSequences": [
      {
        "frames": [
          "/common/destiny2_content/icons/defb8ccfe5438ec63ca4bc4c94e78d8a.png",
          "/common/destiny2_content/icons/792daed5904f632d5d36812f2cf642d3.png"
        ]
      }
    ],
    "hasIcon": true
  },
```

**Comment by justrealmilk** [comment]
This is the _Season of the Worthy Rank_ metric.

![image](https://user-images.githubusercontent.com/156681/84389927-2a8a2a80-ac3a-11ea-9c68-9eadb9006d00.png)

**Comment by jshaffstall-bng** [comment]
This is a known string issue from the game source content. We don't plan to fix this manually in the API side, so expect it to remain empty until it's fixed in the game.
