### ISSUE TITLE
Before light

### ISSUE THREAD

**Issue by JoshuaRyan757** [Bungie-net/api#1253]
I bought the deluxe edition of before light and have not been granted access to the free rewards please fix this

**Comment by vthornheart-bng** [comment]
Sorry, the folks here just work on the API: we don't have any ability to help with actual in-game, purchasing, rewards etc... issues.  You'll want to hit up the Destiny Help forum on bungie.net!

**Comment by JoshuaRyan757** [comment]
How can I report it

**Comment by vthornheart-bng** [comment]
Ah!  So make a post over on the Destiny Help forum.  Unfortunately they're the only people who can help you: describe the issue you've got there, and which platform you bought it on.  Make sure the account you're using on Bungie.net has that platform linked, so they can see your Destiny information more easily!

The help forum is over here:

https://www.bungie.net/en/Forums/Topics?pNumber=0&tg=Help&tSort=0&tType=0&d=0&lang=en
