### ISSUE TITLE
GetPublicVendors has 2 slashes

### ISSUE THREAD

**Issue by Groovin-Dev** [Bungie-net/api#1254]
[Link to entry](https://bungie-net.github.io/multi/operation_get_Destiny2-GetPublicVendors.html#operation_get_Destiny2-GetPublicVendors)

Look at the path, it shows `/Destiny2//Vendors/ `

**Comment by SungJinWoo-SL** [comment]
[Created PR](https://github.com/Bungie-net/Bungie-net.github.io/pull/5)

**Comment by jshaffstall-bng** [comment]
This should be fixed now.
