### ISSUE TITLE
Destiny.DestinyPartyMemberStates enum value documentation incomplete

### ISSUE THREAD

**Issue by Cytraen** [Bungie-net/api#1256]
Currently the documentation for `PosseMember` and `GroupMember` is:

```
PosseMember: 2
I don't know what it means to be in a 'Posse', but apparently this is it.

GroupMember: 4
Nor do I understand the difference between them being in a 'Group' vs. a 'Fireteam'.
I'll update these docs once I get more info. If I get more info. If you're reading this, I never got more info. You're on your own, kid.
```

I'm fairly certain `GroupMember` is supposed to mean they're in your clan, based on all the clan stuff being labelled `GroupV2`, and `PosseMember` means they're on your friends list.

**Comment by jshaffstall-bng** [comment]
Thanks for the heads up! Filed as TFS 915471.
