### ISSUE TITLE
Umbral engrams

### ISSUE THREAD

**Issue by McMurdorur** [Bungie-net/api#1257]
i am unable to get access to the decoder or dismantle any of my umbral engrams. I'm at the quest step where you talk to the drifter and he gives you an umbral engram, my engram inventory is completely full with umbral engrams and am unable to pick up the engram or dismantle any of my current engrams.

**Comment by delphiactual** [comment]
https://github.com/Bungie-net/api/issues/1247#issuecomment-641633746

**Comment by floatingatoll** [comment]
The API forum is unfortunately unable to provide technical support for the issue you're having. Please read the Destiny 2 Known Issues help article and if it does not answer your question, post on the Bungie Help forums for further assistance.
