### ISSUE TITLE
Vendor reputation progressbar color not present in Vendor displayProperties

### ISSUE THREAD

**Issue by floatingatoll** [Bungie-net/api#1258]
In-game, each vendor that accepts reputation tokens has a progression bar next to their diamond-shaped logo.

Progress completed on that bar is shown in a different color for each vendor; Recaster uses a bright red, Sloan (Titan) uses a Titan-ish shade of blue, Gunsmith uses a shade of grey, etc.

In the API, each DestinyVendorDefinition has a 'displayProperties' containing the property 'icon' which references the diamond-shaped logo — but the displayProperties has no listed property for the color of the progression bar.

Could this be exposed in the API, if it isn't already?

**Comment by floatingatoll** [comment]
An example: ![Recaster progress bar](https://user-images.githubusercontent.com/92684/84701927-b043f980-af0a-11ea-93a2-0e4b8f514ee9.jpg)

**Comment by jshaffstall-bng** [comment]
Interesting request! Filed as TFS 915467.
