### ISSUE TITLE
Incorrect lightLevel (power) in PGCR

### ISSUE THREAD

**Issue by Lalo-ATX** [Bungie-net/api#1259]
PGCR 6449351724 shows player.lightLevel at 303, despite that character entering that activity at 1058 (ish), changed no gear, and had 47 kills, ending the activity with a plain "return to orbit" action.

I haven't looked to see how widespread the issue is, but anecdotally I've run a couple of activities at light >1050 but none seem to have registered. If it would help I could find more PGCRs.

**Comment by floatingatoll** [comment]
To ask a random spot check question (I'm not Bungie), do you have PGCRs on record from the past week that show light levels greater than 1024?

**Comment by Lalo-ATX** [comment]
I went ahead and pulled my last 250 PGCRs (of course embarrassingly lots of Forges in there)

I have PGCRs as high as 1056 (6432016169, 6422946588, 6410680211) (game modes 82 Dungeon, 6 Patrol, 6 Patrol respectively)

These PGCRs all show 303, which would all be incorrect:

period | instanceId | mode
-- | -- | --
6/16/2020   3:19 | 6462456969 | Patrol
6/15/2020   13:12 | 6449351724 | BlackArmoryRun
6/14/2020   3:02 | 6411923976 | BlackArmoryRun
6/14/2020   2:10 | 6411087846 | NightmareHunt
6/14/2020   1:28 | 6410522205 | Raid
6/13/2020   1:45 | 6393026325 | BlackArmoryRun
6/12/2020   23:10 | 6390175422 | BlackArmoryRun

**Comment by mikechambers** [comment]
I am seeing same thing still:

https://stats.bungie.net/Platform/Destiny2/Stats/PostGameCarnageReport/6823749543/

Looking at the player entry for "gego"

`
                "player": {
                    "destinyUserInfo": {
                        "iconPath": "/common/destiny2_content/icons/b9ebe5f4b5362da0f07f7449b6470472.jpg",
                        "crossSaveOverride": 1,
                        "applicableMembershipTypes": [
                            3,
                            1
                        ],
                        "isPublic": true,
                        "membershipType": 1,
                        "membershipId": "4611686018432600842",
                        "displayName": "gego"
                    },
                    "characterClass": "Hunter",
                    "classHash": 671679327,
                    "raceHash": 3887404748,
                    "genderHash": 2204441813,
                    "characterLevel": 50,
                    "lightLevel": 335,
                    "emblemHash": 185321778
                },
                "characterId": "2305843009306854242",
`

Note that lightLevel is listed as 335 which is the incorrect value (not sure if 335 light level is even possible). Looking at the same player across multiple games, the value has different numbers each time.
