### ISSUE TITLE
Quest bug

### ISSUE THREAD

**Issue by BookOfDepravity** [Bungie-net/api#1260]
New light quest can not register power lvl the quest main quest: new light reach light level 950 by completing activities quests and challenges to acquire more powerful gear i have already reach power lvl 987 but the quest wont register i tried putting on some gear to drop power lvl the rise back up and it still does not register
![20200616_044932](https://user-images.githubusercontent.com/66997920/84760013-183b2400-af8d-11ea-8dc8-d5323039b132.jpg)
![20200616_044954](https://user-images.githubusercontent.com/66997920/84760026-1bceab00-af8d-11ea-9036-8543b8d24182.jpg)

**Comment by BookOfDepravity** [comment]
I could not send a video for some reason

**Comment by mattybeard** [comment]
I'm afraid this is the Github for the API only. 

If you have any game issues, you are best directed to go to the Bungie forum directly.
