### ISSUE TITLE
Season of Arrivals mods missing collectible definition records

### ISSUE THREAD

**Issue by Lalo-ATX** [Bungie-net/api#1261]
Season of Arrivals mods do not have entries in DestinyCollectibleDefinition at this time. They do have InventoryItem and SandboxPerk definitions. This causes some popular tools (braytech.org and destinyitemmanager.com for example) to not display whether or not players have any of those mods.

List of mods:

swift charge
lucent blade
font of light
radiant light
sustained charge
argent ordnance
kindling the flame
supercharged
precision charge
surprise attack
energy converter
charge harvester

**Comment by jshaffstall-bng** [comment]
I don't know if these will end up in the Collections in-game, but would a new checklist suffice?

Filed as TFS 919048.

**Comment by justrealmilk** [comment]
@jshaffstall-bng there's a presentation node for mods in and out of game so I'd say we're just looking for them to be added there - not sure if they're in game yet... if they aren't that's a game side fix?

**Comment by jshaffstall-bng** [comment]
Correct, we probably don't want to get in the habit of adding new presentation nodes and collectibles, so we would want this to be fixed in the game content instead.

But we can certainly get a new checklist for you! :P

**Comment by andyschott** [comment]
This seems to be fixed as of Beyond Light.
