### ISSUE TITLE
User.GetMembershipDataById inconsistency when including an Authorization header

### ISSUE THREAD

**Issue by chrisfried** [Bungie-net/api#1266]
![image](https://user-images.githubusercontent.com/422381/86492244-4efd9200-bd22-11ea-98e3-dd30f20f53d9.png)

Without Authorization, `User.GetMembershipDataById` returns a `bungieNetUser.twitchDisplayName` (if the user has linked a Twitch account.)

However, if a valid Authorization header is included with the request, `User.GetMembershipDataById` does not return `bungieNetUser.twitchDisplayName`.

**Comment by jshaffstall-bng** [comment]
Are you seeing the same response fields when the authorization is on behalf of the user being requested, compared to when it's not on behalf of the user being requested?

The 'context' stuff makes sense (regarding the relationship between the two users), but the Twitch display name may be an oversight.

Filed as TFS 921379. Thanks for the heads up!
