### ISSUE TITLE
Fetch current selected Triumph / Seal on character

### ISSUE THREAD

**Issue by ashleypb** [Bungie-net/api#1267]
Sorry this isn't an issue as such just ive been through the API 100 times trying to work out were to find this information.

Im looking to find which seal a character is currently displaying (if any)
i.e Dredgen, Wayfarer, Savior etc...

Could anyone point me in the right direction please :)

**Comment by justrealmilk** [comment]
A reference to the equipped title lives in the [Character component](https://bungie-net.github.io/multi/schema_Destiny-DestinyComponentType.html) of the [Profile endpoint](https://bungie-net.github.io/multi/operation_get_Destiny2-GetProfile.html) 

![image](https://user-images.githubusercontent.com/156681/86500555-4d40d680-bdd5-11ea-92b8-8edef66afa2c.png)

**Comment by AnotherEye** [comment]
there is a way to find out if the title is "gilded"?

**Comment by AnotherEye** [comment]
oops I think I found the parameter .. "gildingTrackingRecordHash" :D
