### ISSUE TITLE
Most efficient way to find player base KD over time to plot data to show effects of changes/balance patches

### ISSUE THREAD

**Issue by re3factor** [Bungie-net/api#1270]
Less of an issue more of a question, I was hoping someone could help me gather a dataset to look at KD over time and plot changes. I noticed that there was a param membershipID, which maps to a user, is there a way to query for the entire player base. I understand that would be very expensive so I was wondering if anyone already had a working dataset or if Bungie could provide one. Sorry if this is the wrong place to ask this question, I just didn't see anywhere else that would be good to ask this question.

**Comment by ckhicks** [comment]
@bnicholas89 Are you in the unofficial Bungie API Discord? Lots of super smart people in there: https://discord.gg/E5uB4BW
