### ISSUE TITLE
Cross Save QoLs

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1271]
- Add LastSeenDisplayNameType to characterActivities component of Profile endpoint
- Add platformType to PGCRs

The members of group endpoint returns responses with `LastSeenDisplayNameType` which appears to be exactly what I'm looking for but there are plenty of use cases where we don't want to lookup and fetch a group's members just to get at it.
```json
{
   "memberType":2,
   "isOnline":true,
   "lastOnlineStatusChange":"1594366921",
   "groupId":"2076652",
   "destinyUserInfo":{
      "LastSeenDisplayName":"tom",
      "LastSeenDisplayNameType":3,
      "iconPath":"/img/theme/bungienet/icons/xboxLiveLogo.png",
      "crossSaveOverride":1,
      "applicableMembershipTypes":[3, 1],
      "isPublic":false,
      "membershipType":1,
      "membershipId":"4611686018449662397",
      "displayName":"justrealmilk"
   },
   "bungieNetUserInfo":{ },
   "joinDate":"2020-06-23T06:29:46Z"
}
```

**Comment by jshaffstall-bng** [comment]
Reasonable requests, not sure about the feasibility, but filed as TFS 922819 and 922820
