### ISSUE TITLE
Socket Type 3267328333 (Seasonal Armor Mods) Has Four Season's Mods Instead of Three

### ISSUE THREAD

**Issue by Dreddnought** [Bungie-net/api#1275]
Hi,
I'm expecting the socket type for the last armor mod slot on Arrivals gear to have three seasons in the plugWhitelist (Worthy, Arrivals and season 12) but it's got four?  It includes enhancements.season_v470 (Dawn) which I don't think should be there.  Is this a bug or am I misunderstanding the API?

https://www.bungie.net/Platform/Destiny2/Manifest/DestinySocketTypeDefinition/3267328333

**Comment by delphiactual** [comment]
From the Patch Notes 

https://www.bungie.net/en/Explore/Detail/News/49313

Added the ability for Season of Arrivals armor to use Charged with Light mods from Season of Dawn.

**Comment by Dreddnought** [comment]
Thanks I missed that!

________________________________

**Comment by Dreddnought** [comment]
I missed that Dawn mods are allowd too.  Thanks!
