### ISSUE TITLE
Shattered Throne Completions Metric (1339818929)

### ISSUE THREAD

**Issue by t3rr11** [Bungie-net/api#1276]
Sooo uhh.. I created a leader board system for clannies to use that lists the amount of completions each member of the clan has for each specific dungeon and someone alerted me to the fact that the shattered throne was wrong. After further digging i soon realized that the metric for shattered throne completions (1339818929) which can be found under metrics.data.metrics["1339818929"] changes when swapping between characters.

This has caused a consistency issue as Pit of Heresy Completions (1451729471) and Prophecy Completions (3719033237) metrics are account based, whilst the Shattered Throne Completions is character based.

Is there any way this could be updated to where Shattered Throne Completions accounts for all characters rather than the specific currently played character as the leader boards are completely wrong at this point and will most likely need to be removed as people swap between characters it will continuously update and there is also no way to grab separate character metrics as far as i am aware so i cannot possible add them up myself.

**Comment by jshaffstall-bng** [comment]
Thanks for the heads up! Filed as TFS 928763

Unfortunately, if this is a game-side issue, we might not be able to fix this metric data in the API.

**Comment by t3rr11** [comment]
Hey @jshaffstall-bng do you happen to know if this was actually a game-side issue? I'm getting people asking about why their completions are lower than expected and explaining that it's due to the metric changing due to last played character?

**Comment by rentalhost** [comment]
You still don't have an answer to this question? The difference is sometimes too big, and I am thinking of removing this information because of the inconsistency.

Has anyone got any alternative to count this value, without having to analyze all the player's data?

**Comment by t3rr11** [comment]
I have not found one sadly, I just added a note saying it's inconsistent to the command.
