### ISSUE TITLE
Way to access loot pool for Pinnacle drops per activity (question)

### ISSUE THREAD

**Issue by sylphia-nox** [Bungie-net/api#1277]
I am currently working on trying to add a command to my discord bot to help players optimize their pinnacle grind by recommending the pinnacle activity with the highest probability of dropping an item that will increase their power level.  I am trying to figure out how to get the loot pool for activities and am not sure where to go.  I was able to get the RewardsItemHash but that seems to be a value all of the powerful and pinnacles share.  Is this info available in the API or is it restricted?   If someone can point me in the right direction that would be great.
Side note: does the loot for pinnacles pick a category and then an item or is it a random item from the loot pool?  If it just picks a category then I can easily create a manual table for this info.

**Comment by joshhunt** [comment]
The API does not contain loot pools. Some activities will have reward item hashes indicating whether you get a powerful or pinnacle drop from it, but not the specific item.

> does the loot for pinnacles pick a category and then an item or is it a random item from the loot pool? If it just picks a category then I can easily create a manual table for this info.

reddit or bungie forums is probably a better avenue for this question, but only some activities have predefined loot tables. e.g. the Pinnacle drop from Pit of Heresy will always be a masterworked armour piece, and each encounter in Garden of Salvation has  [three items that can drop](https://www.niris.tv/blog/gardenloot). Iron Banner pinnacles are IB gear, so the drops will be influenced by what IB gear is available. Other than that, i think most pinnacle drops are just RNG and can be pretty much anything.

**Comment by andyschott** [comment]
Not sure if it helps, but I have a website that does basically what you're looking for: https://destiny2utils.com. I don't have any sort of Discord integration though.
