### ISSUE TITLE
Which OAuth endpoint to use

### ISSUE THREAD

**Issue by alexanderwe** [Bungie-net/api#128]
Currently I am trying to implement the OAuth flow from the Bungie API. And I find myself struggling with two different OAuth endpoints documented but I do not know which of those to use. 

The first one https://www.bungie.net/Platform/App/GetAccessTokensFromCode explained in [https://www.bungie.net/en/Help/Article/45481](https://www.bungie.net/en/Help/Article/45481).

The second one https://www.bungie.net/platform/app/oauth/token/ documented in [https://github.com/Bungie-net/api/wiki/OAuth-Documentation](https://github.com/Bungie-net/api/wiki/OAuth-Documentation)

While the first one seems to respond with the typical API schema:

```
{
     "Response": {
           "accessToken": {
                "value": "",
                "readyin": 0,
                "expires": 3600
           },
           "refreshToken": {
                "value": ",
                "readyin": 1800,
                "expires": 7776000
           },
           "scope": 129,
           "membershipId": "1234"
     },
     "ErrorCode": 1,
     "ThrottleSeconds": 0,
     "ErrorStatus": "Success",
     "Message": "Ok",
     "MessageData": {          
     }
}
```
(from: https://www.bungie.net/en/Help/Article/45481)

Unfortunately I can not get it work with the documentation. I am always getting:
```
{ ErrorCode: 2106,
  ThrottleSeconds: 0,
  ErrorStatus: 'AuthorizationCodeInvalid',
  Message: 'Authorization code is invalid.',
  MessageData: {} }
```
With the following request:
```
{ body: { code: 'access_code' },
  headers:
   { 'User-Agent': 'agent',
     'X-API-Key': 'myAPIKey'},
  json: true,
  method: 'POST',
  uri: 'https://www.bungie.net/Platform/App/GetAccessTokensFromCode/' }
```

With the help of the documentation of the second one I got the second endpoint to works as intended but it seems to be responding with a slightly different schema which is the following:
```
{ access_token: '',
  token_type: 'Bearer',
  expires_in: 3600,
  refresh_token: ',
  refresh_expires_in: 7776000,
  membership_id: '' }
```

In total I have two questions:

1. Which of those endpoints should be used for the OAuth
2. If the first one is a valid endpoint, is there something missing or wrong with my request ? 

Thanks in advance :)

**Comment by vthornheart-bng** [comment]
Use the second one - the first is no longer recommended, it's deprecated in favor of real oauth support!

**Comment by alexanderwe** [comment]
Thank you very much for the fast response and the clarification.

**Comment by vthornheart-bng** [comment]
No prob, glad to be of help!
