### ISSUE TITLE
Problems Making Access Token Request: "Missing required parameter grant_type"

### ISSUE THREAD

**Issue by nikita-sh** [Bungie-net/api#1280]
Hey all,

I'm fairly new to the API and I'm trying to get through authorization right now. I've been able to successfully make authorization requests with nodejs but when I start querying for access/refresh tokens I always get a response telling me I'm missing the `grant_type` parameter despite having added it. Here's my current request:

```
const data = process.env.CLIENT_ID + ":" + process.env.CLIENT_SECRET;
const X = (new Buffer(data)).toString('base64');

axios({
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        'X-API-Key': process.env.API_KEY,
        'Authorization': 'Basic ' + X
    },
    method: 'POST',
    url: process.env.TOKEN_URL,
    data: {
        grant_type: 'authorization_code',
        client_id: process.env.CLIENT_ID,
        code: `${requestToken}`
    }
}).then(response => {
    console.log(response);
    // do stuff
}).catch(err => {
    console.error(err);
});
```

Here's the response body I'm getting:

```
data: {
  error: 'invalid_request',
  error_description: 'Missing required parameter grant_type'
}
```

I've tried a couple of solutions/suggestions from some other threads on here to no avail. I would appreciate any input!

Thanks.

**Comment by andyschott** [comment]
Have you tried following the example
Es on [this wiki page](https://github.com/Bungie-net/api/wiki/OAuth-Documentation)?

One thing I can see off hand is that the authorization header should include your client secret, not your API key.

**Comment by nikita-sh** [comment]
Oh my bad, that's a typo, it is actually the client secret. As far as I can tell, my request is the same as the one on the page you linked. I've tried including the grant type, client id and code as parameters in the url instead and I get the same result. Removing the authorization header and instead using the client secret in the body results in the error becoming: 

```
data: {
      error: 'invalid_request',
      error_description: 'Cannot parse client_id'
    }
```

**Comment by andyschott** [comment]
One other difference: you're sending JSON, but it's expecting `form-urlencoded`. Maybe try setting the body to this:

    `grant_type=authorization_code&code=${code}`

Also, I think the `code` isn't the `requestToken`, but the same code that you passed in on the authorization request (this is to prevent forgery of requests, I think).

**Comment by nikita-sh** [comment]
I tried both of those and it didn't work, but the good new is that I did figure it out! 

Your first point on the data being JSON got me thinking, so I tried something similar I saw on another issue:

```
const createFormParams = (params) => {
    return Object.keys(params)
        .map((key) => `${encodeURIComponent(key)}=${encodeURIComponent(params[key])}`)
        .join('&')
}

const data = process.env.CLIENT_ID + ":" + process.env.CLIENT_SECRET;
const X = (new Buffer(data)).toString('base64');

axios({
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        'X-API-Key': process.env.API_KEY,
        'Authorization': 'Basic ' + X
    },
    method: 'POST',
    url: process.env.TOKEN_URL,
    data: createFormParams({
        grant_type: 'authorization_code',
        client_id: process.env.CLIENT_ID,
        code: requestToken
    })
}).then(response => {
    console.log(response);
}).catch(err => {
    console.error(err);
 });
```

Thanks for you help!
