### ISSUE TITLE
Nascent Dawn 

### ISSUE THREAD

**Issue by windscar71** [Bungie-net/api#1281]
I did the entire Nascent Dawn quest and never got the Polaris Lance exotic weapon all I got was the catalyst for it, any help on getting my exotic weapon would be great. I really do not want to do any of that over.

**Comment by t3rr11** [comment]
Sorry to hear! But this Github is only for the API and requests associated to the API.
If you have any in-game related bugs or questions the Bungie Forums would be your best place to post.
[https://www.bungie.net/en/Forums/Topics?tg=Help](https://www.bungie.net/en/Forums/Topics?tg=Help)
