### ISSUE TITLE
Mod icon semi-transparent background layer issue

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1283]
Bonjour.

![image](https://user-images.githubusercontent.com/156681/88887698-41cfb680-d280-11ea-8cd1-9c2bc3f1c73c.png)
_A mod icon demonstrating the semi-transparent background layer issue_

90% of mod and perk icons appear to have a semi-transparent layer that sits behind them. This doesn't appear in-game and the assets in the game files themselves also don't suffer from this ailment. 

Is there anything you can do to fix them for the next time they're prepared for a deployment?

**Comment by floatingatoll** [comment]
See also #117 for a previous instance where we requested transparent PNGs and some backend work occurred to make that happen.
