### ISSUE TITLE
My account with covered by PS4 not normal game

### ISSUE THREAD

**Issue by gy891128** [Bungie-net/api#1288]
My PC account is covered by PS4 account can't normal game, because I can't again the game top-up normal time to remove the binding,Cancel the PS4 end to the PC binding request

**Comment by ckhicks** [comment]
This system is for reporting issues/requests related to the Bungie API - for account or in-game issues you should post on the Bungie Help Forum: https://www.bungie.net/en/Forums/Topics/?tg=Help

Good luck!

**Comment by gy891128** [comment]
If you deactivate, you cannot re-activate for 90 days.
