### ISSUE TITLE
Split up character and profile collectibles and records.

### ISSUE THREAD

**Issue by t3rr11** [Bungie-net/api#1289]
So currently you can hit the GetProfile endpoint with the component 800 and 900 and get both Profile and Character records and collectibles. Is there any chance these could be split up into respective 801,802 and 901,902. 

They are quite large responses and i personally don't use the Character records or collectibles so i would like to just request the Profile records and collectibles to minimise my fetch times.

As Marvin grows in population is has become quite a struggle to keep his scan times to a reasonable 2-3 minutes given the 30 req/s limit for this endpoint. So anything you could do to these components would be greatly appreciated by myself and the people using Marvin.

**Comment by t3rr11** [comment]
Or even better, how about an endpoint that just returns recently obtained collectibles? Since i check for value changes, if there was an endpoint that just returned recently obtained items, that'd make things much quicker and lighter? 
![image](https://user-images.githubusercontent.com/2139233/90837547-82a78080-e391-11ea-8654-fa98d032190b.png)

**Comment by joshhunt** [comment]
> I personally don't use the Character records or collectibles

For what it's worth, you probably should. Some Triumphs and Collectibles are character-scoped, so ignoring these on the Character basis will give you incomplete data sometimes.

**Comment by t3rr11** [comment]
Whilst I agree that I should use them for data checking and confirmation, if I continue to request this data the time per user remains too high and won't be sustainable at 30req/s. 

I don't mind implementing a random check that will run once a day to check and verify data, but for the 2-5 minute interval scans per user I require lighter responses.

**Comment by floatingatoll** [comment]
Are you performing 2-5 minute interval scans per user 24/7/365 for all users, or are there limits already in place (such as "for all users active in your app or site")?

**Comment by t3rr11** [comment]
So currently, the only variable factor is the rate limit. I have it set to vary based on the amount of users online. If there are 800/33k users online (peak down time) then scans are around 2 minutes long. If there are 4k/33k players online then scan times are 8-10 minutes long. 

My fear is come this new DLC launch that more players will come back rasing this number to somewhere near the 10k mark. Which means estimated scan times of around 18-20 minutes. 

So to answer your question, it usually takes between 2-5 minutes for the queue to reach the player again and rescan them, on the basis that they are online. If not they are skipped. 

Yes 24/7/365.
