### ISSUE TITLE
Iron Banner stats

### ISSUE THREAD

**Issue by ubergeeks2020** [Bungie-net/api#1290]
Is there a way to pull Iron Banner stats, k/d, assists, # matches played, weapons used, etc?

Any help would be appreciated.

**Comment by mikechambers** [comment]
Uber, you would need to pull all of their iron banner games, and calculate the stats yourself. Not too difficult for one player.

Check out the Destiny API Discord. You would probably get a better response there.

https://discord.gg/UEKzQU

**Comment by ubergeeks2020** [comment]
Thank you for the response. Discord says the invitation is invalid or expired. Can I please get another invite?

Thanks
