### ISSUE TITLE
Wrong description in SoA Flawless seals record hash

### ISSUE THREAD

**Issue by t3rr11** [Bungie-net/api#1293]
The Season of Arrivals flawless seal presentation node references the recordHash: `1547272082` which seems to be the right completion record hash for the season of arrivals flawless seal, but the description is wrong on that record. 

On the Seals Presentation Node: `1617497214` it says: Complete all Season of Arrivals flawless Triumphs.
On the Seals Completion Record Hash: `1547272082` is has last seasons description: Complete all Season of the Worthy flawless Triumphs.

Easy work around for me, I'll just use the presentation nodes description, but the record will still be wrong. Out of all the seals in the game i can confirm this seems to be the only one with the wrong description. Conqueror was fine.

**Comment by justrealmilk** [comment]
seal completion records are _under the hood_ records that typically aren't visible in the same way as others. they're often copy-pasted I bet

**Comment by t3rr11** [comment]
The reason i bring it up is due to having a feeling that they are going to continue to duplicate Conqueror and Flawless each season going onward. Which means it's not too late to quickly pop in and fix the description issue at the same time, or as you say, they're under the hood records, not visible, so it reaaaaaaly doesn't matter that much. Just could cause issues for debugging issues with seals down the line.
