### ISSUE TITLE
Destiny 2 | Solstice of Heroes Error! (Really Serious!!!)

### ISSUE THREAD

**Issue by Fachidiot** [Bungie-net/api#1295]
hello I'm a big fan of ur game. I just want you to fix the game bug I found.

During the majestic quest for the Solstice of Heroes, My male Warlock character's fit was not good, so I changed it to a female character.
In the process, I reset my Warlock character.
However, the Solstice of Heroes Quest began at the renewed quest.
I was a little annoyed, but I started again from the renewed quest.
But when I went to meditate with a renewed guard, my defense disappeared. The quest also not continue.
I started the quest again, crying and making a respirator.
But this time there is not meditating icon. I can't handle it by myself!

Reference : https://www.youtube.com/watch?v=fo-qdtfVhhI&t=12s (Korean)
https://youtube.com/video/RPTKdGMIzNc (English)

**Comment by floatingatoll** [comment]
Unfortunately, this is the API GitHub, and so there's no one here that can offer support for this issue. You'll need to submit your issue to the Bungie Help forums to receive assistance: https://www.bungie.net/en/Forums/Topics/?tg=Help

**Comment by Fachidiot** [comment]
got it. thx for notice me

2020년 9월 3일 (목) 오전 6:53, floatingatoll <notifications@github.com>님이 작성:
