### ISSUE TITLE
Vendor interactions lack a unique identifier

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#1296]
Behind the scenes in Bungie-land, do vendor interactions have a somewhat unique identifier to... identify each interaction? Are you able to supply this in the definitions?

 - The interaction index changes with each content update (it looks like new interactions are added to the top of the list), so using the index in a URL is rough for pointing to the same interaction over time
 - The title of the interaction (`interaction.headerDisplayProperties.name`)  is duplicated across multiple interactions, so that's unable to be used

The current best approach I've thought of was to  use both `interaction.headerDisplayProperties.name` and hashing `interaction.flavorLineOne` to create a semi-unique identifier within each vendor, but still, vendors sometimes have interactions where that content is the same. 

It would be great if the definitions themselves had a semi-stable identifier for vendor interactions :)

**Comment by baxter** [comment]
+1 for this!
