### ISSUE TITLE
데스티니 가디언즈 영웅의 지점 후광 오류 (destiny2 bug)

### ISSUE THREAD

**Issue by Linfrik** [Bungie-net/api#1300]
![20200920200338_1](https://user-images.githubusercontent.com/71590694/93709886-0f09b680-fb7d-11ea-8816-1935a159f8b9.jpg)

![20200920200342_1](https://user-images.githubusercontent.com/71590694/93709891-14670100-fb7d-11ea-968d-14813ec36df3.jpg)

![20200920200332_1](https://user-images.githubusercontent.com/71590694/93709882-0618e500-fb7d-11ea-9e7f-2e727783b3a8.jpg)

워록 경이 아이템인 펠윈터의 투구를 착용하고 영웅의 지점 세트와 후광을 착용하면 시공 하위직업의 색이 나오는 버그가 있는 것 같습니다. (다만 공허 하위직업 일 땐 문재 없었습니다. 태양,전기만 해당합니다. ) 라벨을 할줄 몰라요!

**Comment by jshaffstall-bng** [comment]
Thanks for your report, but this is a known game issue and not part of the D2 API, so this issue is being closed.

Google translate:
신고 해 주셔서 감사합니다. 이는 알려진 게임 문제이며 D2 API의 일부가 아니므로이 문제는 종결됩니다.
