### ISSUE TITLE
Allow specifying multiple modes for GetActivityHistory

### ISSUE THREAD

**Issue by mikechambers** [Bungie-net/api#1301]
https://bungie-net.github.io/multi/operation_get_Destiny2-GetActivityHistory.html#operation_get_Destiny2-GetActivityHistory

Currently, in order to pull activities for multiple mode types, you must make multiple API calls to getActivityHistory, as you can only specify one mode per call. This complicates development, requires additional calls and delay for the user, and puts additional strain on the API server.

The request is to allow multiple modes to be specified when calling GetActivityHistory. This could be in the form of a "modes" parameter, that takes a comma separated list of node IDs / DestinyActivityModeType.

This would be similar to how GetHistoricalStats takes a modes parameter.

https://bungie-net.github.io/multi/operation_get_Destiny2-GetHistoricalStats.html#operation_get_Destiny2-GetHistoricalStats

**Comment by jshaffstall-bng** [comment]
Sorry that we're late responding to this request. It's filed as TFS 957353.
