### ISSUE TITLE
DestinyActivityModeType that includes public and private crucible matches

### ISSUE THREAD

**Issue by mikechambers** [Bungie-net/api#1302]
Request to create a DestinyActivityModeType that includes all pvp matches, public and private. It could be named AllPvPWithPrivate.

Currently, in order to pull ALL pvp matches (public and private), you must make two API calls to GetActivityHistory.

https://bungie-net.github.io/multi/operation_get_Destiny2-GetActivityHistory.html#operation_get_Destiny2-GetActivityHistory

This is because private matches are not included in AllPvP. Instead you must make two calls, one for AllPvP and one for PrivateMatchesAll.

This complicates working with all matches, requires additional API calls, and puts additional strain on the API server.

This is related to #1301

**Comment by floatingatoll** [comment]
Do these two API calls contain data that is not present in the PGCR records themselves? Or do they return exclusively a list of PGCR IDs and nothing else of value.

**Comment by mikechambers** [comment]
I am using the API calls to:

1. Get summary data for the member / character for all pvp activities (public and private), including their performance in the match and a list of all of their PVP activities.
2. To get the ids for the PGCR to get more detailed match info (weapons, medals) (if the user chooses to view it).

**Comment by Marruk** [comment]
I would love this as well!

My goal is to show a chronological list of PVP matches of a player, both public and private. Needing six calls to achieve that goal (two per character) is not really worth it for me at the moment.
