### ISSUE TITLE
Tracker stats don't appear to sync with parsed stats

### ISSUE THREAD

**Issue by neilmcgibbon** [Bungie-net/api#1306]
I am processing data from my own Destiny 2 career, and I am having trouble syncing up some basic stats.  For example, Crucible Opponents Defeated...

When I look at my in-game tracker (e.g applied to my emblem) I see this figure as `30,718` opponents defeated.  I can't make this number match up with my own processed data.  I have downloaded all my activities (using `Destiny2.GetActivityHistory` endpoint, for all. 3 of my characters), and then downloaded each of the Post Game Carnage Reports. When I aggregate where the Activity Mode = 5 ("All PVP"), and sum on `values.opponentsDefeated.basic.value`, I get a value of `30655`, which is `63` less than the in-game tracker.

I have tried (and discounted) the following:
 - Adding Private PVP opponents defeated - but this gives a total above the in-game tracker, so that can't be it.
 - Adding my Gambit / Gabmit Prime `invaderKills` or `invasionKills`, but this gives a total far above the in-game tracker, so that can't be it.

I have checked all carnage reports are valid, so none have been missed, but I can't reconcile those `63` opponents defeated.  Is there something I am missing?

Thanks in advance!

**Comment by floatingatoll** [comment]
Have you been playing for a long time? I believe there are a couple of known gaps in the PGCR data and so it’s possible those are missing.

You may also want to look at similar issues open, such as #789 or #1224.

**Comment by neilmcgibbon** [comment]
@floatingatoll Thanks for those references, I will take a look.  I think my earliest PGCR was from around March '18 - so if there are gaps then I guess its possible I'm part of the missing-data cohort...! I've run the stats for 4 people in my clan, and we all seem to have a slight different (where my generated stats are less than the in-game tracker. by around 0.1 - 0.8%)
