### ISSUE TITLE
raid time metrics are returned in milliseconds, not seconds

### ISSUE THREAD

**Issue by nev-r** [Bungie-net/api#1307]
### docs
https://bungie-net.github.io/#/components/schemas/Destiny.DestinyUnlockValueUIStyle
> TimeDuration: 7
> Show the number as a time duration. The value will be returned as seconds.

### in-game
![image](https://user-images.githubusercontent.com/68782081/97266850-6cc99800-17e6-11eb-85cd-ae556190a25a.png)

### api response
```
"1835852368": {
  "invisible": false,
  "objectiveProgress": {
    "objectiveHash": 2962797189,
    "progress": 835400,
    "completionValue": 5400000,
    "complete": true,
    "visible": true
  }
},
```

### the facts of life
![image](https://user-images.githubusercontent.com/68782081/97266719-2ffda100-17e6-11eb-8c8d-8914f170d7b0.png)
![image](https://user-images.githubusercontent.com/68782081/97266652-13616900-17e6-11eb-9c5a-0e369df94dee.png)

**Comment by jshaffstall-bng** [comment]
Good catch, filed as TFS 955529
