### ISSUE TITLE
Recommended way to get the manifest?

### ISSUE THREAD

**Issue by jlhume** [Bungie-net/api#1312]
Hiya,

I wanted to ask if there was a recommended/most efficient method of fetching the manifest (I'm aware of [this page](https://github.com/Bungie-net/api/wiki/Obtaining-Destiny-Definitions-%22The-Manifest%22) but wanted to ask about the "best" way to go about it).
My thought process for what I'm working on is the server "fetches" the manifest in one form or another, then "cuts the fat", so to speak, reducing it to only information that it cares about. The server will maintain its own copy of the manifest and only update it when it detects the version has changed.
This would essentially be to front-load manifest JSON processing so fetching any info about items, etc, would be quick and easy for processing user requests, rather than just grabbing the SQLite database and using it as-is (and processing the JSON column each time).

I'm aware of using the [GetDestinyManifest](https://bungie-net.github.io/multi/operation_get_Destiny2-GetDestinyManifest.html#operation_get_Destiny2-GetDestinyManifest) endpoint to actually find out where to get the manifest, but then it comes down to consuming it. I have a couple of criteria here:
* I only care about the DestinyInventoryItemDefinition (for now anyway).
* Not all information is desired, so only a subset will be consumed.

From a glance, seems it'd be best to fetch the relevant JSON file under jsonWorldComponentContentPaths as per [Destiny.Config.DestinyManifest](https://bungie-net.github.io/multi/schema_Destiny-Config-DestinyManifest.html#schema_Destiny-Config-DestinyManifest) and just consume the JSON as necessary.
But I'm skeptical about doing that given the documentation for it states:
> WARNING: This is unsafe and subject to change - do not depend on data in these files staying around long-term.

So, would it be better for me (in the long run) to fetch entire manifest as JSON as per jsonWorldContentPaths instead, and consume it that way?
What's actually unsafe about the components JSON files? Are they just subject to not being maintained?

In similar vain, are there any hidden gotchas between getting the manifest as a SQLite database or as JSON?
eg. if one isn't updated as often/quickly

Note that I've largely been talking about getting it as JSON as, from what I said before, if I wanted to consume the information about items, etc, from the SQLite database provided by mobileWorldContentPaths, the download might be cheaper but the processing would be a little heavier (ie. need to go through the database, then process the JSON of each item) - I'd prefer to front-load the JSON processing so manifest loading is heavy but fetching of information is quick and easy.

Admittedly, I would need to do some benchmarking to see what actual differences there are between getting and processing raw JSON, vs getting a SQLite database and processing JSON on row-by-row basis, but I digress.

**Comment by mikechambers** [comment]
For Redrix, we download the SQLLite manifest, create a smaller JSON version that only contains the data we want, and then upload to our servers for the app to sync with.

I don't remember the details off the top of my head, but there was some data not available in the JSON manifest versions from Bungie.
