### ISSUE TITLE
Add Europa "Secret" Collectibles to Checklists

### ISSUE THREAD

**Issue by lowlines** [Bungie-net/api#1313]
Much like cat statues in the Dreaming City and Jade Rabbits on the Moon, Europa has some collectibles hidden throughout the destination. It would be good to get these added as checklists.

2322553724 - Reuniting the Eventide Rookery (9 Penguin Souvenirs)
2322553724 - Studying Darkness (9 Entropic Shards)
2322553724 - Salvage the Past (9 Dead Exos)

**Comment by jshaffstall-bng** [comment]
Tracked with TFS 944873

**Comment by justrealmilk** [comment]
Entropic Shards

**Comment by jshaffstall-bng** [comment]
These were added a little while ago now.
