### ISSUE TITLE
Could Armor screenshots use the 'space' model instead of generic armor?

### ISSUE THREAD

**Issue by NigelBreslaw** [Bungie-net/api#1315]
In game go to Collections -> Armor. Now inspect some armor on a class that is different to the one you are using. Instead of generic armor a cool 'galaxy space body' is used. It doesn't attract as much attention from the real armor piece and also looks super cool. Could armor screenshots be like this?
![Destiny 2_20201111143814](https://user-images.githubusercontent.com/1957186/98812224-c4911180-242a-11eb-936f-762193598f1d.jpg)

**Comment by jshaffstall-bng** [comment]
Maybe! Tracking with TFS 957656.
