### ISSUE TITLE
Typo in "A Guardian Rises" quest step "Advent"

### ISSUE THREAD

**Issue by alex-keller** [Bungie-net/api#1316]
Typo: "Talk To Commnder Zavala" -> "Talk To Commander Zavala"

![tiger_release_final_20201111_143600_highlighted](https://user-images.githubusercontent.com/18578728/98856413-81836e00-242b-11eb-9874-7b171aa8cba2.png)

**Comment by justrealmilk** [comment]
This is a game side issue that won't be resolved here

**Comment by alex-keller** [comment]
Is there a game-side bug report form somewhere? I couldn't find it.

**Comment by jshaffstall-bng** [comment]
Not an API issue, but I appreciate the report! I've filed a bug on the game side, and I'm closing this issue.
