### ISSUE TITLE
[3.0.0.1] The Ordeal Nightfall activity definitions

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1318]
I've made some observations.

- All current ordeal definitions have an `activityLightLevel` of `0`
  - `activityLightLevel` is a very useful means for programmatically distinguishing between the different difficulties. The alternative is by sorting by modifier array length
    - This is problematic for the point that follows. That said, I'm personally using the public milestones endpoint to cache the current weeks modifiers so this doesn't affect me
- Some master difficulty ordeals have a greater number of modifiers than their grandmaster counterparts - it's as though their names were accidentally switched.
  - Lake of Shadows: 3109193568, 3109193569
  - The Corrupted: 2416314393, 2416314392
  - The Scarlet Keep: 1495545956, 1495545957

I thought there was more to say but I'm very tired so this may be it

**Comment by jshaffstall-bng** [comment]
Thanks for these reports!
- `activityLightLevel` filed as TFS 958069
- Ordeal modifiers filed as TFS 958070

**Comment by jshaffstall-bng** [comment]
Are these still an issue? I think they should be fixed by now. Feel free to comment if they're not.
