### ISSUE TITLE
[3.0.0.1] Relevant progressions no longer return seasonResets property

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1319]
This was _super_ useful for a bunch of reasons. Due to the changes with records, there aren't any effective ways to get this data anymore. I thought trackers would be my saving grace (they weren't).

It was an array that returns an object of resets integer and season integer and I loved it very much.

**Comment by jshaffstall-bng** [comment]
Interesting! It's possible that this data is no longer preserved on the game side, but I've filed TFS 957679 to investigate.

**Comment by afpac** [comment]
Any update on this? With the Trials reputation rank 10/16 rewards changing every time your rank is reset, knowing how many times a profile has reset their rank would be helpful when trying to display all the possible rewards available on a given weekend.
