### ISSUE TITLE
Wrong Stats shown for the gun Hailing Confusion in the official app

### ISSUE THREAD

**Issue by andyschott** [Bungie-net/api#1321]
The stats for the gun Hailing Confusion are different in game and in the official app (see screenshots below).

In game:
![Hailing Confusion In Game](https://user-images.githubusercontent.com/3392920/98974646-2614b700-24e3-11eb-8f25-3e29152d9fc4.png)
Official app:
![Hailing Confusion Official App](https://user-images.githubusercontent.com/3392920/98974656-29a83e00-24e3-11eb-9846-260886628271.png)

**Comment by andyschott** [comment]
After further investigation, this seems to be due to the Elemental Capacitor perk. It looks like the API is showing the buff for each subclass as active.

**Comment by jshaffstall-bng** [comment]
I think this is a part of the long-standing differences between API stat values and the game.

I'm closing this as such, but feel free to comment if you think there's something else we could do here.

**Comment by andyschott** [comment]
Probably the only thing that could be done is to show the stats as if no subclass is active, instead of them all being active. Not sure if that's possible or not based on what the API can access, though.

**Comment by floatingatoll** [comment]
(I wonder if the perk is implemented as two nerfs rather than one buff in the backend? That might explain why this is weird, too.)
