### ISSUE TITLE
Meteoric Descent ornament for Pyroclastic Flow is missing an icon

### ISSUE THREAD

**Issue by nev-r** [Bungie-net/api#1322]
https://data.destinysets.com/i/InventoryItem:2416805974

https://www.bungie.net/common/destiny2_content/icons/a2ca0f5066ae751326e9db0c7bc6ff20.jpg
![image](https://user-images.githubusercontent.com/68782081/98989945-a8e74300-24de-11eb-8ee4-317a442a339d.png)

the icon for this ornament is just a purple background

**Comment by jshaffstall-bng** [comment]
Thanks for the report! This is filed as TFS 958062.

**Comment by nev-r** [comment]
looks fixed in recent deploy. thank you!

**Comment by jshaffstall-bng** [comment]
🤷‍♂️
