### ISSUE TITLE
legacy mod placeholders count as leg mods

### ISSUE THREAD

**Issue by nev-r** [Bungie-net/api#1323]
i'm assuming because they have "leg" in the item type name now??

affected items:
720857
2357307006
2620967748
2655746324
3625698764
4106547009
4153634494

incorrect itemCategoryHash:
3607371986

**Comment by jshaffstall-bng** [comment]
You seem to be correct in that assumption! Filed as TFS 958064.

**Comment by jshaffstall-bng** [comment]
This should now be fixed.
