### ISSUE TITLE
[3.0.0.1] Consider adding potential triumph score to ProfileRecords component

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1324]
![image](https://user-images.githubusercontent.com/156681/99025555-ec14d680-251d-11eb-8e39-bdb012515cc6.png)

My function says the number should be `16,350` so like 🤷🏼‍♂️

**Comment by jshaffstall-bng** [comment]
That value is constant in the content, and you can get it from the `maxCategoryRecordScore` of the 'Active Triumphs' root presentation node hash (`1866538467`).

**Comment by jshaffstall-bng** [comment]
Also this value takes into account all Triumphs that are redacted from the Bnet content. But once everything is un-redacted, let us know if you see any difference from the total you're calculating.
