### ISSUE TITLE
Medal Descriptions Corrupted in Manifest

### ISSUE THREAD

**Issue by mikechambers** [Bungie-net/api#1326]
stateName and stateDescription properties for medals appear to be corrupted / wrongly formatted. Output is now:

```
    "statName": "###medals_strings_com01.pvp_medal_ib_super_shutdown###",
    "statDescription": "###medals_strings_com01.pvp_medal_ib_super_shutdown###",
```

Where as previously it was a more human readable string.

Seeing this for all medals in DestinyHistoricStatDefinitions

Can view an example here:
https://data.destinysets.com/i/HistoricalStats:Medals_pvp_medal_ib_super_shutdown

**Comment by jshaffstall-bng** [comment]
Filed as TFS 958687.

**Comment by jshaffstall-bng** [comment]
Good news: this latest Bnet content update should have the old medals strings working again. Hopefully you see that coming through!

Bad news: there are still some new historical stats strings that are missing localized strings. I don't have an ETA to fix these, but it's on our radar.

**Comment by mikechambers** [comment]
Yes. Can confirm I am seeing them fixed. Thank you! Really appreciate the work you all do on the API.

**Comment by mikechambers** [comment]
fyi, this has been fixed since March and issue can be closed.
