### ISSUE TITLE
Widow's Court Activity Definition returns wrong map image

### ISSUE THREAD

**Issue by mikechambers** [Bungie-net/api#1327]
The new activity definitions for Widow's Court returns the wrong map. It currently points to the map for Altar of Flame. It should point to:

https://www.bungie.net/img/destiny_content/pgcr/crucible_widows_court.jpg

The hashes from DestinyActivityDefinition with incorrect info are: 427041827, 2399854375, 906046314

Can view here:
https://data.destinysets.com/i/Activity:427041827

**Comment by jshaffstall-bng** [comment]
Good catch, files as TFS 958682.

**Comment by mikechambers** [comment]
fyi, Legion's Gulch is also wrong. Issue here: https://github.com/Bungie-net/api/issues/207

**Comment by jshaffstall-bng** [comment]
This is now fixed for Widow's Court. The Legion's Gulch activity is no longer in the game, so it's a lower priority for us to address.

**Comment by mikechambers** [comment]
Confirmed. Thanks!
