### ISSUE TITLE
DestinyEnergyType enum wasn't updated with new Energy Types

### ISSUE THREAD

**Issue by nev-r** [Bungie-net/api#1328]
Ghost (enumValue:4)
and
Subclass (enumValue:5)

were added to defs, and appear on items, but weren't added to the DestinyEnergyType enum

**Comment by jshaffstall-bng** [comment]
Yep sorry, we'll be updating the API docs later this week.

**Comment by jshaffstall-bng** [comment]
The API spec and docs should now be updated.
