### ISSUE TITLE
[3.0.0.1] Interval records can now have rewards but definitions are empty

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1330]
With Beyond Light, interval records with rewards have been added to the game.

Single steps record definitions have a `rewardItems` array.

This array isn't populated for interval records. This might be because some records offer a reward (lore book page) at each interval itself. I can't remember - it's been a time.

![image](https://user-images.githubusercontent.com/156681/99360091-e93f1c00-2864-11eb-9010-e162f5ebde83.png)

**Comment by jshaffstall-bng** [comment]
Filed as TFS 959252 to investigate.
