### ISSUE TITLE
[Question] What's your stance on "overlays" to be used while Destiny 2 is running?

### ISSUE THREAD

**Issue by AryToNeX** [Bungie-net/api#1331]
I am looking to develop small overlays that open on top of a borderless fullscreen Destiny 2 client to offer more info to the player through this API. To be clear, I am not looking into injecting code into the game at run time; I was thinking about making my own separate application that will just display content on top of everything else in the desktop (including the client window). Looking at your policies, I found that only overlays that inject themselves into the game to render in the same context are bannable; so, what about all the other ones? Is it a gray area or is it safe to develop and use such overlay?

**Comment by jshaffstall-bng** [comment]
I don't have a specific answer for you here, but I can point you at the policies - https://www.bungie.net/en/Help/Article/46101

**Comment by AryToNeX** [comment]
I read that article and my idea doesn't fall in any of the bannable third party apps, so I assume I am safe to develop it. Thanks!
