### ISSUE TITLE
Destination/Place definitions different between localizations

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#1332]
I've gotten some reports that in non-English manifests, the hashes for certain destination or place definitions are different. This means we can't easily rely on stable hashes to do things like show Xur's location localized or categorize bounties by place.

**Comment by justrealmilk** [comment]
> there are hashes that persist between localisations, i.e. english has many duplicates while others have fewer, or just one. so if you visit italy, you can grab its set of valid destination hashes, and they'll work everywhere

697502628 edz
3990611421 cosmo
677774031 moon
1729879943 europa
3607432451 arcadian valley
3821439926 tangled
1416096592 dreaming

**Comment by jshaffstall-bng** [comment]
With the Beyond Light release, many old definitions were removed from content, or had their content ID change, which also changed the hash value.

We tried to preserve all of the legacy definitions for activities, activity types, destinations, and places to maintain backwards compatibility for game history and PGCRs, but it sounds like we have some missing pieces here.

Filed as TFS 959243 to investigate.

**Comment by bhollis** [comment]
Awesome. I think if we could consolidate down to one ID per location that's consistent across localizations, that'd help.

**Comment by nev-r** [comment]
these places exist in EN manifest but not in any other language:
```
1590276 // "Deep Six"
330251492 // "Nessus Orbit"
386951460 // "Titan Moon of Saturn"
484311295 // "Gambit"
541863059 // "European Aerial Zone"
662472328 // "Strike Playlist"
897844116 // "Gambit Prime"
975684424 // "The Tangled Shore"
1122149715 // "Cathedral of Scars"
1134775813 // "Unknown Space"
2096719558 // "The Menagerie"
2315564210 // "Legion's Folly"
2426873752 // "Mars"
2555959872 // "The Almighty"
2642884869 // "Kell's Grave"
2877881518 // "The Dreaming City"
3004560036 // "New Arcadia"
3019314578 // "Prison of Elders"
3074334404 // "Emerald Coast"
3325508439 // "The Moon"
3526908984 // "Nessus"
4148998934 // "The Reckoning"
4251857532 // "Io"
```

these destinations exist in EN manifest but not in any other language:
```
1590276 // "Deep Six"
123491860 // "Legion's Folly"
126924919 // "Arcadian Valley"
159602672 // "undefined"
290444260 // "The Moon"
308080871 // "Hellas Basin"
308974318 // "The Derelict"
329262012 // "undefined"
333456177 // "The Last City"
357679773 // "The Reckoning"
359854275 // "The Tangled Shore"
366956745 // "IX Realms"
620798773 // "Cathedral of Scars"
684141231 // "undefined"
897844116 // "Gambit Prime"
1072559238 // "undefined"
1199524104 // "European Dead Zone"
1229692670 // "Emerald Coast"
1402606356 // "Unknown Space"
1621667531 // "Kell's Grave"
1775713152 // "undefined"
1890123761 // "undefined"
1976362504 // "undefined"
1993421442 // "Mercury"
2038451695 // "Prison of Elders"
2073151843 // "The Cosmodrome"
2155983995 // "Nessus Orbit"
2158693219 // "The Last City"
2218917881 // "Echo Mesa"
2341115919 // "undefined"
2388758973 // "New Pacific Arcology"
2512542997 // "Strike Playlist"
2612139675 // "The Last City, Earth"
2616293043 // "undefined"
2709666235 // "undefined"
2777041980 // "The Crucible"
2779202173 // "The Dreaming City"
3004560036 // "New Arcadia"
3031909699 // "undefined"
3093898507 // "Nessus Orbit"
3158922420 // "European Aerial Zone"
3507009564 // "undefined"
3536553558 // "undefined"
3669933163 // "undefined"
3670157546 // "undefined"
3989677910 // "undefined"
4161571679 // "The Almighty"
4188263703 // "The Farm"
```

**Comment by nev-r** [comment]
as far as i can tell these hashes are just leftovers? it looks like the places & dests that *aren't* these, are intended to be the right ones at this point.

these leftovers have bubble/activity information for vaulted planets, which maybe isn't supposed to be available anymore

**Comment by jshaffstall-bng** [comment]
The difference in these definition tables between languages should now be fixed. Let us know if you run into other discrepancies.
