### ISSUE TITLE
Equipped weapons in PGCR

### ISSUE THREAD

**Issue by landervervaeke** [Bungie-net/api#1335]
Hi all,

I'm parsing PGCRs of Nightfall Ordeal completions.
My goal is to get the equipped weapons for each PGCR.
But my experience is that these weapon ids are only sometimes present.

I'm getting data by using `/Platform/Destiny2/Stats/PostGameCarnageReport/{{ pgcr_id }}`.
Weapons are sometimes present under: `Response.entries[].extended.weapons[].referenceId`
A good PGCR example: `7078887436`
A PGCR with only limit weapon `referenceIds`: `7236705904`

Any idea why we aren't always getting 3 weapons per player?
Is there a better way to get the equipped weapons of activity completions?

Thanks in advance!

Cheers,
Lander

**Comment by ats** [comment]
That data shows kills by weapon, so it will only show details for weapons that the player used and recorded kills with. (This means if they change weapons in activities that don’t lock gear it may show more than three records, too.)
