### ISSUE TITLE
Where's the twitch prime loot

### ISSUE THREAD

**Issue by platinumSoldier** [Bungie-net/api#1336]
Been checking every day and still no twitch prime loot it's states clearly tht there are ten drops a month. Not maybe ten drops not we will think abt ten drop says ten drops every month. So where are they less then ten days in the month now so how is tht gonna work........ dono why I'm paying a monthly fee to be lied too.

**Comment by floatingatoll** [comment]
Hi, this is the Bungie API developer issues forum. The API team cannot respond to your question about Bungie Rewards, and when they see this they will instruct you to post your question on the Bungie Help forum.
