### ISSUE TITLE
Auth errors on non-Auth endpoints

### ISSUE THREAD

**Issue by BlazeBoss17** [Bungie-net/api#1337]
Many PGCRs (7302212868 for example) (and 46,000+ others) are currently returning ErrorCode 12, ErrorStatus InsufficientPrivileges.  This started happening around 10 AM Saturday Nov 21.

**Comment by delphiactual** [comment]
Raid pgcrs are offline until worlds first is officially declared by bungie

**Comment by justrealmilk** [comment]
![image](https://user-images.githubusercontent.com/156681/99888609-ecd6f800-2c02-11eb-84dd-36abf5f0e43e.png)
 not bad

**Comment by ChaseMalik** [comment]
@jshaffstall-bng I noticed you agreed with @delphiactual's comment - was this communicated beforehand anywhere?

**Comment by double051** [comment]
Yeah, sorry. We gave a heads up in the DIM developer slack chat, but we probably should have started a thread here as well.

We expect to start returning Deep Stone Crypt raid PGCRs once the World First is announced on Monday.

**Comment by jshaffstall-bng** [comment]
Yeah, sorry. We gave a heads up in the DIM developer slack chat, but we probably should have started a thread here as well.

We expect to start returning Deep Stone Crypt raid PGCRs once the World First is announced on Monday.

**Comment by jshaffstall-bng** [comment]
The winners have been announced, so the Deep Stone Crypt raid activities are now available with Game History and PGCRs.
