### ISSUE TITLE
The Dark Priestess Empire Hunt PGCR Image is missing

### ISSUE THREAD

**Issue by JpDeathBlade** [Bungie-net/api#1338]
All Dark Priestess activities, like 2205920677, are missing their PGCR images. It should be this one: https://www.bungie.net/img/destiny_content/pgcr/empire-hunt-goulash.jpg

**Comment by jshaffstall-bng** [comment]
Good catch! Filed as TFS 960329.

**Comment by jshaffstall-bng** [comment]
This has been fixed in content.
