### ISSUE TITLE
Wrong Mode Type returned for private control matches for getprofile

### ISSUE THREAD

**Issue by mikechambers** [Bungie-net/api#1339]
Calling getProfile (component 204) when in a private crucible match:

https://www.bungie.net/Platform/Destiny2/1/Profile/4611686018429783292/?components=204

Data returned for active player includes:

```
                    "currentActivityHash": 1867152431,
                    "currentActivityModeHash": 3199098480,
                    "currentActivityModeType": 10,
                    "currentActivityModeHashes": [
                        3199098480,
                        1164760504
                    ],
                    "currentActivityModeTypes": [
                        10,
                        5
                    ],
                    "currentPlaylistActivityHash": 3959500077,
                    "lastCompletedStoryHash": 0
```

Note, that currentActivityModeType returns 10 (Control) and currentActivityModeTypes return 10 (Control) and 5 (AllPvp)

They should return 53 (PrivateMatchesControl) for both, and not 10.

currentActivityModeHash may also be incorrect (although I could not find private control in the manifest)

**Comment by jshaffstall-bng** [comment]
Good catch! Filed as TFS 961142.
