### ISSUE TITLE
Raid manifest item type has wrong index

### ISSUE THREAD

**Issue by mikechambers** [Bungie-net/api#1340]
https://data.destinysets.com/i/Activity:910380154/ActivityType:2043403989

Manifest DestinyActivityTypeDefinition table for Raid (2043403989) lists index as 7 (AllPVE), it should be listed as 4 (Raid).

(I am assuming that index maps to the analogous mode type)

**Comment by jshaffstall-bng** [comment]
Perhaps I'm mistaken, but I don't think that index maps onto any enum values. Instead, that's just the index for this definition in the table of activity type definitions. As such, these indices are subject to change and shouldn't be relied upon for consistency.
