### ISSUE TITLE
currentActivityModeType missing from Raid when calling getprofile API

### ISSUE THREAD

**Issue by mikechambers** [Bungie-net/api#1341]
Calling getprofile with component 204

https://www.bungie.net/Platform/Destiny2/1/Profile/4611686018429783292/?components=204

While character is in Deep Stone Crypt raid:

Data returned for active character includes:

```
"currentActivityHash": 910380154,
"currentActivityModeHash": 2166136261,
"currentPlaylistActivityHash": 910380154,
```

It is missing mode type data fields, including currentActivityModeType, and currentActivityModeTypes.

It should include:

```
currentActivityModeType: 4
```

and probably

currentActivityModeTypes :[4, 7];

Note, data is also missing from Nightmare hunts.

**Comment by jshaffstall-bng** [comment]
Interesting! Filed as TFS 961145.
