### ISSUE TITLE
Arc DamageType icon has the wrong color

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#1343]
Arc got recolored in Beyond Light - e.g. https://data.destinysets.com/i/SandboxPerk:3279433214

However the actual damage type icon didn't: https://data.destinysets.com/i/DamageType:2303181850

**Comment by jshaffstall-bng** [comment]
Don't believe your lying eyes! :P

Filed as TFS 961160.

**Comment by jshaffstall-bng** [comment]
This should be fixed now.

**Comment by bhollis** [comment]
Thanks!
