### ISSUE TITLE
Player Vault and Inventory

### ISSUE THREAD

**Issue by rjkelleh** [Bungie-net/api#1347]
Hi, I have a question regarding accessing a user's vault and inventory. I know that I can access them through this get request:

```
GET https://www.bungie.net/Platform/Destiny2/0/Profile/{destinyMembershipId}/?components=102
X-API-Key: {your-api-key}
Authorization: Bearer {your-access-token}
```

While I can access this information just fine, I was wondering if there is any value on an item that indicates that it is in the player's vault vs their inventory. I'd imagine there would be but I'm just not sure what that is.

Also, when transferring items to and from the vault using the transferItem request, how are the parameters set up? When transferring to, i'd imagine the transferToVault parameter is true and all of the other parameter are filled in, but when transferring from the vault, does it work the same way or is there something specific that needs to be done?

Thank you!

**Comment by andyschott** [comment]
> While I can access this information just fine, I was wondering if there is any value on an item that indicates that it is in the player's vault vs their inventory.

It's been a long time since I looked at that part of the API, but I think if you look at the `DestinyItemComponent`, it either has a bucket or or location that you can determine where the item is located.
