### ISSUE TITLE
Checklist for Augmented Obsession triumph's real world objectives

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1348]
![image](https://user-images.githubusercontent.com/156681/100529737-5cb72680-319f-11eb-9341-b80f0620b304.png)

I did a poll and it's very desired.

Only one location may be completed a week and they are currently being released at a weekly cadence.

**Comment by jshaffstall-bng** [comment]
Can do. Filed as TFS 961141.

**Comment by justrealmilk** [comment]
Not to be a bother but we are running out of time 🥵

**Comment by justrealmilk** [comment]
Alright I'm gonna write this one off
