### ISSUE TITLE
Empire Hunt PCGRs are missing from activity history

### ISSUE THREAD

**Issue by ats** [Bungie-net/api#1349]
Are Empire Hunts excluded from activity history or included only when meeting certain conditions? I wanted to run my stats for the Cloudstrike grind from this weekend and see that there are no PCGRs for them, either when run independently or as a step in an Empire Hunt quest/bounty (I don't see them either in my home-brew stats tool or in more reputable places like Braytech or my game history at Bungie.net). Seeing issue #1338 it appears that they do exist, so I wonder if there's a bug preventing them from appearing my history -- Xbox account originally, enabled to Cross Play, and I ran those games all on PC.

**Comment by jshaffstall-bng** [comment]
Good find. I think it's just the higher-difficulty versions of the Empire Hunts that aren't showing up in Game History. For example, this one here for 'Legend' is showing the 'All' category.

Filed to TFS 961129 to investigate,

**Comment by ats** [comment]
Do you mean the higher level difficulty versions *are* showing up? If so, would match with my experience, as all the runs I did were at Adept and Hero and none appear in my history. Thanks!

**Comment by jshaffstall-bng** [comment]
Rather, that the original versions of the Empire Hunts seem to be showing up in game history, but the versions with a difficulty selection seem to be missing.

**Comment by jshaffstall-bng** [comment]
New Empire Hunt and Nightmare Hunt activities (in Adept, Hero, Legend, and Master modes) should be coming through in Game History now, under the 'Story' category.

Older instances of these activities will probably not show up still, so stay tuned for an update on those later.

**Comment by jshaffstall-bng** [comment]
No ETA yet for a fixup of these activities from before the fix was applied, but I'm closing this issue, and I can update when I have more info.

**Comment by jshaffstall-bng** [comment]
Unfortunately, it sounds like the unmapped activities won't be getting fixed up after all.

Sorry for the delay here, and I wish it were better news, but I still wanted to let you all know.
