### ISSUE TITLE
404 crucible-related icon

### ISSUE THREAD

**Issue by nev-r** [Bungie-net/api#1351]
activities
585322760, 917887719, 952904835, 1151331757, 1219083526, 1276739382, 1457072306, 1746163491, 2274172949, 2303927902, 2304691867, 3011324617, 3176544780, 3239164160, 3243161126, 3243244011, 3646079260, 3780095688, 4209226441

and activitytypes
96396597, 158362448, 517828061, 1472571612, 1522227381, 2410913661, 3252144427, 3268478079, 3610972626, 3954711135, 3956087078, 3956381302, 4141415314

reference the image
https://www.bungie.net/common/destiny2_content/icons/47ef0cd932668fe44f23e8b1b659458f.png

which sssssssseems to be 404 from everywhere

**Comment by nev-r** [comment]
see also:
https://www.bungie.net/common/destiny2_content/icons/843744b6902d8672635e3232984cbe29.png
referenced in ~66 crucible-related definitions

**Comment by jshaffstall-bng** [comment]
Probably related to how we're preserving ye olde activity definitions that no longer exist in Beyond Light content. Filed as TFS 962650 to investigate.
