### ISSUE TITLE
post BL launch, mayhem matches are weird in a few ways

### ISSUE THREAD

**Issue by nev-r** [Bungie-net/api#1352]
new mayhem
```
example instanceId: 7343884704
directorActivityHash: 3847433434
mode: 0
modes: [5]
```

old mayhem
```
example instanceId: 7046469670
directorActivityHash: 1102379070
mode: 25
modes: (2) [5, 25]
```

the AllMayhem activity filter doesn't work because they are missing mode 25,
teams array is empty in mayhem PGCRs, it treats them sort of like 12 player free for alls, except also with no standing info

**Comment by lauriys** [comment]
same thing is happening to Rumble, only mode 5 (AllPvP) is present

**Comment by jshaffstall-bng** [comment]
Yep, this is tracked with TFS 965070.

**Comment by jshaffstall-bng** [comment]
This should be fixed now for new Mayhem activities the next time it comes around. Older Mayhem instances since Beyond Light won't be correct unless we perform some kind of fixup, but that won't be happening soon.
