### ISSUE TITLE
Lost Sector Challenges and PGCRs

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1353]
**Problem description**
So as they're built upon the Scored Nightfall Strikes type in some way, Lost Sector Challenges come through the API as such. as they're going to be sticking around (I think as they're a great addition even though I fracking suck at soloing them) something might need to be done at whatever level to distinguish them from strikes because when I pull `/Platform/Destiny2/1/Account/4611686018449662397/Character/2305843009260574394/Stats/Activities/?page=0&mode=18&count=20` I really don't want to see Lost Sectors haha

**Problem example**
![image](https://user-images.githubusercontent.com/156681/100848901-a3727e00-3436-11eb-87f8-f7ec02f3e645.png)

**Proposed solution**
Strip modeType 18 from Lost Sector Challenges and create a set of types and modes for them.

**Comment by jshaffstall-bng** [comment]
Would be nice! Filed as TFS 962643.
