### ISSUE TITLE
Several Gambit-specific stats are broken in PGCRs.

### ISSUE THREAD

**Issue by lauriys** [Bungie-net/api#1354]
**Motes Deposited**, **Motes Lost**, **Primeval Healing** are some of the stats stuck at 0.
It's very clearly visible on Bungie.net too:
![image](https://user-images.githubusercontent.com/330645/100898603-3952eb00-34c1-11eb-958f-9652bcda1f8a.png)

**Comment by jshaffstall-bng** [comment]
Good catch, filed as TFS 962642 to investigate.
