### ISSUE TITLE
(Local) Korean chat is broken with Win10 v2004 (20H1)

### ISSUE THREAD

**Issue by kagneww** [Bungie-net/api#1355]
Korean chat in 데스티니 가디언즈 (Destiny 2 in Korea) is broken and only English chat is working now with Win10 v2004 (20H1).
Cause: Game client is incompatible with the new version CJK IME introduced by 20H1

https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-wip-at-home-20h1#east-asian-microsoft-input-method-editor-ime-improvements-build-18875

Every Korean player who installed 20H1 (manually or auto-updated by Microsoft), experience inconvenience and forced to roll-back to 19H2.

I'm using several apps and games but Destiny 2 is the only case that still suffer from this problem.

BUNGiE should contact with Microsoft to fix this problem.

**Comment by jshaffstall-bng** [comment]
Thanks for your report! I've passed this along to the D2 game team.
