### ISSUE TITLE
Rumble has incorrect Mode type when pulling activities

### ISSUE THREAD

**Issue by mikechambers** [Bungie-net/api#1357]
Calling /Activities/

https://www.bungie.net/Platform/Destiny2/1/Account/4611686018429783292/Character/2305843009264966985/Stats/Activities/?mode=5&count=250&page=0

(search for the id below to see it, as my activity history will change)

Rumble has mode set to 0, and not 48. The modes Array is also incorrect, as it only includes 5, and not 5 and 48.

```json
"period": "2020-12-05T21:45:51Z",
"activityDetails": {
    "referenceId": 2081877020,
    "directorActivityHash": 2259621230,
    "instanceId": "7468591574",
    "mode": 0,
    "modes": [
        5
    ],
    "isPrivate": false,
    "membershipType": 3
},
```

This also means it is not currently possible to retrieve recent activities by Rumble:

https://www.bungie.net/Platform/Destiny2/1/Account/4611686018429783292/Character/2305843009264966985/Stats/Activities/?mode=48&count=1&page=0

Shows the last rumble activity at 2020-09-07T18:44:39Z, when it should be 2020-12-05T21:45:51Z (see above json snippet).

**Comment by jshaffstall-bng** [comment]
Related to some other issues reported for Rumble. Tracked with TFS 965070.

**Comment by jshaffstall-bng** [comment]
This should be fixed for new Rumble activities now. I don't have an ETA for fixing up older Rumbles since the start of Beyond Light, but I can give an update when we have one.
