### ISSUE TITLE
Phase completion information for the raid isn't correct

### ISSUE THREAD

**Issue by JonnyOThan** [Bungie-net/api#136]
In the milestones section of the progressions component, for the raid entry there is an array of phases.  One of my characters has completed the entire raid, but every phase says complete : false.  Another one of my characters has only completed the gauntlet phase, and the 4th (and only the 4th) phase says complete: true.

**Comment by floatingatoll** [comment]
Does the "phases" array precisely match each character's current raid
checkpoint (if any)? Completion would be 'no checkpoint', so all 'false',
under that theory.

**Comment by JonnyOThan** [comment]
Ah, I think you are right!  Still the field name should be something like "isCurrentCheckpoint" and it would still be useful to know which phases have been looted like we could see in D1.

**Comment by floatingatoll** [comment]
No argument there. I'm just offering a potential clue as to what it means
in case that helps them fix it.

**Comment by vthornheart-bng** [comment]
Finally, finally coming back and fixing this.

This is slated to be released October 2nd, though I welcome any and all bugs you can give.  I'm giving what I perceive in the data to be phases, but if there's additional steps you feel ought to be there or steps that don't seem right, let me know and I can do some more digging.

The Last Wish raid's weekly completion status will also start being returned on that date in Milestones.
