### ISSUE TITLE
currentlyCanRoll - Never True

### ISSUE THREAD

**Issue by afpac** [Bungie-net/api#1360]
Mentioned in the dev Slack, but the new currentlyCanRoll attribute on PlugSetDefs exists on all 2036 PlugSets, but none of them are set to true. 

I've got the code ready to display current vs retired perks differently, but since everything shows as retired right now, I can't really turn it on.

Just wanted to bring it up here in case it was intended to be fully functional in today's API update and the wires got crossed on the way out the door. Will there be another API update next week along w/ Dawning launch with the attribute properly populated?

**Comment by jshaffstall-bng** [comment]
Sorry about this. Filed as TFS 963977, and we hope to have a fix on Monday, 12/14.

**Comment by jshaffstall-bng** [comment]
This property should now be working correctly in the latest Bnet content from this morning. Let us know if it's not!
