### ISSUE TITLE
How to purchase items with apiPurchasable = true?

### ISSUE THREAD

**Issue by robbiet480** [Bungie-net/api#1361]
Dug through the API and can't seem to find a way to actually purchase vendor items. Any pointers to the method I'm missing?

**Comment by delphiactual** [comment]
3rd party cannot at the moment

**Comment by jshaffstall-bng** [comment]
Yes sorry, only the official D2 Companion apps are able to purchase vendor items at the moment. Hopefully this will be extended to 3rd party apps in the future!
