### ISSUE TITLE
Iron Banner Activities not included in Activity History

### ISSUE THREAD

**Issue by mikechambers** [Bungie-net/api#1362]
https://www.bungie.net/Platform/Destiny2/1/Account/4611686018429783292/Character/2305843009264966985/Stats/Activities/?mode=5&count=250&page=0

Retrieving AllPVP games (mode 5) via /Activity is not returning IronBanner matches.

Currently, the call above returns:

```json
        "activities": [
            {
                "period": "2020-12-06T04:07:15Z",
                "activityDetails": {
                    "referenceId": 2296512046,
                    "directorActivityHash": 1717505396,
                    "instanceId": "7471951818",
                    "mode": 73,
                    "modes": [
                        5,
                        70,
                        10,
                        73
                    ],
                    "isPrivate": false,
                    "membershipType": 3
                },
```

showing my last match from 2 days ago, and ignoring the approximately 10 Iron Banner matches I played today.

I suspect this is related to Issue #1357

**Comment by jshaffstall-bng** [comment]
Thanks for the heads up! This is tracked with TFS 963943.

**Comment by vtubelsky** [comment]
@jshaffstall-bng Iron Banner games started showing up in the API response yesterday (12/14) around 5pm Eastern time. But only new games, not prior ones. Will the missing games from the start of Iron Banner until 12/14 5pm EST eventually show up or are they lost for good?

**Comment by jshaffstall-bng** [comment]
Yep, the newer Iron Banner activities should be coming through now, but there's some additional work that would need to happen to get the older activities to show up in the same way.

It's on our radar, but I don't have an ETA for that.

**Comment by jshaffstall-bng** [comment]
The ETA for any kind of activity fixup won't be for a while, if ever. So I'm closing this issue now, but will update when we hear more about that.

**Comment by jshaffstall-bng** [comment]
Unfortunately, it sounds like the unmapped activities won't be getting fixed up after all.

Sorry for the delay here, and I wish it were better news, but I still wanted to let you all know.
