### ISSUE TITLE
Adept Mods & Scout Rifle missing Collectibles

### ISSUE THREAD

**Issue by afpac** [Bungie-net/api#1364]
None of the Adept mods currently have related collectibles. They also do not appear in the in-game collectibles section or under the weapons PresentationNode in the API, but it seems odd to have all mods **but** the Adept mods show up there. Could be a bug?

https://www.light.gg/db/legend/3839307707/ for the PresentationNode

https://www.light.gg/db/all?f=10(mod),12(adept) for a list of the items - they would have a "Related Collectible" section if one existed.

The Scholar (Adept) is also missing its collectible where the other Adept weapons appear to have one:

https://www.light.gg/db/items/2386979999/the-scholar-adept/

versus

https://www.light.gg/db/items/3514144928/the-summoner-adept/

**Comment by jshaffstall-bng** [comment]
Looks like a game-side content issue, but I've filed TFS 965063, and will check if this is already being tracked.

**Comment by jshaffstall-bng** [comment]
It looks like the Adept mods were added to Collections in this latest D2 update, but Adept version of The Scholar won't be in Collections until later this season.

Thanks again for the heads up!
