### ISSUE TITLE
Cosmodrome Explore/Patrol activity PGCR image 404s

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#1365]
Cosmodrome patrol activity has a `pgcrImage` URL of `https://bungie.net/img/destiny_content/pgcr/europa-explore.jpg` which a) seems wrong (europa?) and b) 404s

https://data.destinysets.com/i/Activity:1928961926

**Comment by jshaffstall-bng** [comment]
Good find, filed as TFS 965056.

**Comment by jshaffstall-bng** [comment]
This was fixed a couple weeks ago :)
