### ISSUE TITLE
2020 Dawning Ghosts missing "eyes" in API image.

### ISSUE THREAD

**Issue by JpDeathBlade** [Bungie-net/api#1369]
4088827200 - Emberwick Shell
4088827201 - Little Helper Shell
4088827202 - Tangled Shell

![Emberwick Shell](https://user-images.githubusercontent.com/1441829/102234044-e153b580-3ebe-11eb-9029-e085024bc61b.jpg)

**Comment by justrealmilk** [comment]
they are dead #wontfix

**Comment by jshaffstall-bng** [comment]
Oops! Tracked with TFS 965797.

**Comment by jshaffstall-bng** [comment]
This is fixed now, but may require a hard refresh.
https://www.bungie.net/common/destiny2_content/screenshots/4088827200.jpg
https://www.bungie.net/common/destiny2_content/screenshots/4088827201.jpg
https://www.bungie.net/common/destiny2_content/screenshots/4088827202.jpg
