### ISSUE TITLE
Prophecy not appearing in milestones

### ISSUE THREAD

**Issue by fremgenc** [Bungie-net/api#1372]
Hash: 4148187374 (DestinyActivityDefinition)

Not appearing in milestones. I believe it should be, please correct me if I'm wrong.

It's currently possible to fetch this by paginating Activities to see if the user has completed. However, this still doesn't provide the ability to know the completion status of each individual checkpoint, only the final boss.

**Comment by fremgenc** [comment]
New Prophecy hash: 

1077850348

Status exists in characterActivities

**Comment by jshaffstall-bng** [comment]
Sorry for the delay here. Filed as TFS 967901.

**Comment by jshaffstall-bng** [comment]
The challenge for the Prophecy dungeon should be showing up now.
