### ISSUE TITLE
Deep Stone Crypt weekly challenge status unavailable

### ISSUE THREAD

**Issue by fremgenc** [Bungie-net/api#1377]
The modifier exists 

![image](https://user-images.githubusercontent.com/12090308/103044607-2d51ca80-454f-11eb-82b0-38c46f7b4265.png)

But there is no `complete` flag like other phases (checkpoints)

**Comment by jshaffstall-bng** [comment]
Hmm was there a completion flag for the challenge in the API for other raids in the past? Filed as TFS 967906.

**Comment by justrealmilk** [comment]
> Hmm was there a completion flag for the challenge in the API for other raids in the past? Filed as TFS 967906.

not to my knowledge
