### ISSUE TITLE
Symphony of death, i.e. Death singers mission

### ISSUE THREAD

**Issue by SieniMahonen** [Bungie-net/api#1378]
Here is another bug. When you die in death singer mission you return at the beginning of hallways. The door is closed and you can not go further.

**Comment by floatingatoll** [comment]
If this is a bug about in-game, then you'll need to submit it to the Bungie Help forums with the appropriate tag and, if possible, a short video showing the problem. This is the API issue tracker, and the API team can't do anything to help with gameplay bugs. (I'm not Bungie.)

**Comment by SieniMahonen** [comment]
ok
