### ISSUE TITLE
Mega issue with last wish raid

### ISSUE THREAD

**Issue by megabloodmoon** [Bungie-net/api#1381]
The mouth of the beast (riven) that is used as a starting point for the queens walk final encounter in the last wish raid is far too small for more than one person to pass through and causes issues with finishing the raid and needs to be expanded in order to keep the consumer having an enjoyable time and increase sales in dlcs as it will be more widely talked about if solved thank you if you read this :)

**Comment by floatingatoll** [comment]
Unfortunately, this is the API github issues tracker, and only API issues are discussed here. You'll need to take gameplay suggestions such as you describe to the official Bungie.net community forums for it to be seen by the gameplay teams at Bungie, as the API issues tracker is not monitored for such things and no consideration will be given to game suggestions posted here. (I am not Bungie.)

**Comment by megabloodmoon** [comment]
Oh terribly sorry about that my mistake
