### ISSUE TITLE
User request to unvault sword

### ISSUE THREAD

**Issue by megabloodmoon** [Bungie-net/api#1382]
A few users I’ve come across have requested the unvaulting of the quickfang sword

**Comment by floatingatoll** [comment]
Vaulting of content is controlled by the gameplay team, and the API team can only implement what is required of them by the gameplay team. As noted in the previous issue, your feedback about gameplay issues and suggestions needs to be directed to the official Bungie.net feedback forums, as it will not be viewed or considered here in the API issues forum. (I am not Bungie.)

**Comment by megabloodmoon** [comment]
Yup my mistake I thought this was the place sorry about that you guys
