### ISSUE TITLE
OAuth 2.0 Python example

### ISSUE THREAD

**Issue by BeppeTemp** [Bungie-net/api#1384]
Happy New Year everyone, can anyone kindly provide an example of authentication via OAuth 2.0 in Python?

**Comment by zoltaroth** [comment]
All the relevant examples can be found here: https://github.com/Bungie-net/api/wiki/OAuth-Documentation

As a CS grad student, this should be a fairly easy exercise for you to convert to code.

**Comment by joshhunt** [comment]
@BeppeTemp I would recommend you check out https://lowlidev.com.au/destiny/authentication-2

It steps through all the HTTP requests you need to make for oauth
