### ISSUE TITLE
activity history for private matches all (32) does not include specific game mode

### ISSUE THREAD

**Issue by mikechambers** [Bungie-net/api#1386]
https://www.bungie.net/Platform/Destiny2/1/Account/4611686018429783292/Character/2305843009264966985/Stats/Activities/?mode=32&count=250&page=0

Returns all private pvp activities. However, it does not include the specific game mode type:

```
                "activityDetails": {
                    "referenceId": 247771251,
                    "directorActivityHash": 3076038389,
                    "instanceId": "7714686824",
                    "mode": 32,
                    "modes": [
                        32
                    ],
                    "isPrivate": true,
                    "membershipType": 3
                },
```

The directoryActivityHash does point to the correct rumble manifest entry:

https://data.destinysets.com/i/Activity:3076038389

but modes does not contain the correct data. mode and modes should be:

```
                    "mode": 57,
                    "modes": [
                        32, 57
                    ],
```

Since PrivateMatchesAll also appears to include private Gambit matches, not having the correct mode data makes it more difficult to get only crucible private matches. (its possible by hardcoding private gambit hashes and checking directorActivityHash, but that fails if new hashes are added).

**Comment by jshaffstall-bng** [comment]
Good catch, filed as TFS 969115 to investigate.

**Comment by mikechambers** [comment]
fyi, as a workaround for anyone who needs the data, you can use directActivityModeHash to figure out the type of private match played.

i.e. the example above is rumble:

https://data.destinysets.com/i/Activity:3076038389
