### ISSUE TITLE
Stats endpoint failing for a guy with 560+ deleted characters

### ISSUE THREAD

**Issue by BoofLord** [Bungie-net/api#1387]
URL: https://stats.bungie.net/platform/Destiny2/3/Account/4611686018506923014/Stats/?groups=1
Secondary website that is failing too: https://wastedondestiny.com/3_4611686018506923014

I hit that endpoint to get a list of deleted characters for users.  I have data for him in my database so this call had to have worked at least once.

It seems perfectly fair to have timeouts here...  It times out after about 1 minute 40 seconds regardless of what I set my internal timeout value to.

When it fails it gives this error:
```
<html>
<head><title>524 Origin Time-out</title></head>
<body bgcolor="white">
<center><h1>524 Origin Time-out</h1></center>
<hr><center>cloudflare-nginx</center>
</body>
</html>
```

For the data that loaded into my db, 313 characters only have 1 activity. 112 have 2 activities. 

i changed it to group=2 and it returns in about 78 seconds. set group = 3 and it was about 12 seconds.  for shits and giggles i set it to a 19 and it was very fast. no real data but it still has the deleted characters so it works for me.

**Comment by jshaffstall-bng** [comment]
Strange! Filed as TFS 967902 to investigate.
