### ISSUE TITLE
Future of crossplaying support

### ISSUE THREAD

**Issue by rentalhost** [Bungie-net/api#1390]
Maybe it's a little early to talk about it, but after Bungie finally announced that we will have Crossplaying later this year, I was concerned about the changes that would be necessary in using the API to make it work properly.

I imagine that there is already a draft or some brief information that we may have at the moment, or at least a "more likely" way forward.

**My main doubts at the moment is:** should we worry about any sudden changes in the API in relation to player profiles? Today, we have several endpoints that depend on the platform specification. How would these endpoints be affected?

I question this because I have a project that currently reads the player's activities depending on the specification of the platforms that the player himself makes or has ("automatic mode"). Quite similar to the well-known [raid.report](https://raid.report). These changes could leave the project unavailable until the changes are made on both sides, and I imagine that this would only be available after some time after the update that will allow Crossplaying.

Thanks in advance!

**Comment by jshaffstall-bng** [comment]
We don't have any API guidance yet for upcoming cross play changes. It's still a ways out, but we will be communicating the changes here on github when we can.
