### ISSUE TITLE
Dark subclasses missing Subclass item category hashes.

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#1391]
Light subclasses (with traidId `item_type.light_subclass`) are granted the "Subclasses" itemCategory https://data.destinysets.com/i/InventoryItem:3481861797

Dark subclasses (with traidId `item_type.dark_subclass`) not https://data.destinysets.com/i/InventoryItem:3291545503

**Comment by jshaffstall-bng** [comment]
Good catch! Filed as TFS 967913.

**Comment by jshaffstall-bng** [comment]
Good catch! Filed as TFS 967925.
