### ISSUE TITLE
Checklist of player who recently opened region chests isn't updating

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1392]
Member 4611686018489556778 recently opened various region chests in the Dreaming City (past few days) and their checklist is not updating.

Could be related to other checklist/game item visibility issues.

Apparently, they were binging checklists and items in other locations did correctly reflect their new status.

**Comment by jshaffstall-bng** [comment]
Interesting! Filed as TFS 969112 to investigate.

**Comment by justrealmilk** [comment]
Today's game update - 3.1.1:

> Fixed an issue where region chest icons would remain on the map after finding the chest.  

Unfortunately, this is only a game-side user-facing fix. Checklists passed through the API still remain broken and outdated.

**Comment by dcaslin** [comment]
Just got a similar report of this from a user re: Dreaming City chests: for 3-4611686018487784763 

https://www.d2checklist.com/3/4611686018487784763/checklist

**Comment by justrealmilk** [comment]
Had another report of this issue so I tested it on one of my own accounts and it's just Dreaming City chests. Some sort of internal mapping issue maybe?

**Comment by kierenpitts** [comment]
I think that has been bugged for at least a couple of years:
https://www.bungie.net/en/Forums/Post/257846218

I finished up the Dreaming City region chests (finally) at the end of last season, none of the ones I did are marked as completed for me though.

**Comment by justrealmilk** [comment]
Seems the bug cropped up with Beyond Light
