### ISSUE TITLE
Iron Banner faction engram item is missing from manifest

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#1393]
Iron Banner faction: https://data.destinysets.com/i/Faction:1761642340

This lists reward item 1762796941, which doesn't exist in InventoryItems.

**Comment by nev-r** [comment]
87221.20.09.10.1506-27 is the last set of defs containing that item

**Comment by jshaffstall-bng** [comment]
Good catch, I think we need to point at a different engram now. Filed as TFS 969111.
