### ISSUE TITLE
I want to get `Lost Sector Legend/Master` Information

### ISSUE THREAD

**Issue by kdeun1** [Bungie-net/api#1395]
Hello. 

Lost sector information is not visible in characterActivities. (e.g. /Destiny2/${membershipType}/Profile/${membershipId}/Character/${characterId}/?components=204)

How can I get the lost sector (legend, master) information? (e.g. Concealed Void: Legend (DestinyActivityDefinition hash: 912873277)

```
jshaffstall-bng commented on 17 Nov 2020
Hopefully this is feasible. Filed as TFS 958683.
```
ref) https://github.com/Bungie-net/api/issues/1325

Does this mean that the above comment is expected to be applied in the future?

If this information is being provided, how should it be obtained?

In the future, the legend/master difficulty level is likely to be added on the lunar planet. Do you support this information as well?

**Comment by jshaffstall-bng** [comment]
Sorry, I meant 'hopefully it's feasible for us to add this to the Activities API.'

Closing this as a duplicate, and we can keep this open in the original thread.

**Comment by kdeun1** [comment]
Thanks for your kind response.

Have a good day!
