### ISSUE TITLE
Get characterId for get vendor request

### ISSUE THREAD

**Issue by BeppeTemp** [Bungie-net/api#1396]
Hello everyone.

I am trying to get the inventory of the gunsmith, through the getvendor request, at the moment I have all the necessary parameters except characterId, which if I understand correctly can be obtained through the getProfile request, but when I go to compose the request I get this error:

{"ErrorCode":18,"ThrottleSeconds":0,"ErrorStatus":"InvalidParameters","Message":"The input parameters were invalid, please enter valid input, and try again.","MessageData":{"membershipType":"TigerXbox","membershipInfo.membershipType":"BungieNext","membershipId":"4392828"}}

my code is:
![image](https://user-images.githubusercontent.com/55873294/104905182-49942c00-5982-11eb-878d-e016aa4d33c3.png)

**Comment by jshaffstall-bng** [comment]
The membershipId is basically an account ID, and your BungieNext membership is your Bungie.net account, which won't work for Vendors and other D2 APIs.

I assume that you want the membership ID from your TigerXbox account (which should be a longer number that starts with 4611...), and then you can get your character ID from a character on that account.

**Comment by BeppeTemp** [comment]
thanks a lot. Now it work.

**Comment by hellosaumil** [comment]
Hello, I'm also new to Bungie API and facing similar error.

```{"ErrorCode": 18, "ThrottleSeconds": 0, "ErrorStatus": "InvalidParameters", "Message": "The input parameters were invalid, please enter valid input, and try again.", "MessageData": {"membershipType": "TigerStadia", "membershipInfo.membershipType": "BungieNext", "membershipId": "XXXXXXXX"}}```

My primary account is with Stadia with a `5` so I provided URL as follows `https://www.bungie.net/platform/Destiny2/5/Profile/XXXXXXXX/?components=200`

**Comment by justrealmilk** [comment]
> Hello, I'm also new to Bungie API and facing similar error.
> 
> 
> 
> ```{"ErrorCode": 18, "ThrottleSeconds": 0, "ErrorStatus": "InvalidParameters", "Message": "The input parameters were invalid, please enter valid input, and try again.", "MessageData": {"membershipType": "TigerStadia", "membershipInfo.membershipType": "BungieNext", "membershipId": "XXXXXXXX"}}```
> 
> 
> 
> My primary account is with Stadia with a `5` so I provided URL as follows `https://www.bungie.net/platform/Destiny2/5/Profile/XXXXXXXX/?components=200`
> 
> 
> 
> Specifically, @jshaffstall-bng, how do I obtain the long membershipId? Thank you.

Use the unofficial Discord server for API help at https://discord.gg/v2PZNj4t3Q
