### ISSUE TITLE
Known Issue: endDate missing from Season 12 definition and startDate missing from Season 13 definition

### ISSUE THREAD

**Issue by jshaffstall-bng** [Bungie-net/api#1397]
Heads up everybody, the latest D2 content released on Bnet this morning has an issue with some dates missing from season definitions.

- endDate is missing from Season 12 definition
- startDate is missing from Season 13 definition

Filed as TFS 970354. We're hoping to fix this with new content later this week. Sorry for the inconvenience!

**Comment by jshaffstall-bng** [comment]
This is now fixed.

**Comment by joshhunt** [comment]
Is it?

**Comment by jshaffstall-bng** [comment]
@joshhunt If you're still running into this problem, let us know!
