### ISSUE TITLE
Missing Destiny membership for user

### ISSUE THREAD

**Issue by Aioros** [Bungie-net/api#1398]
I have an unexpected situation with some users of my app, where /User/GetMembershipsById/ is returning an empty `destinyMemberships` array. Here's an example:

```
    {
        "destinyMemberships": [],
        "bungieNetUser": {
            "membershipId": "6736624",
            "uniqueName": "6736624",
            "displayName": "SpiniestGnu40",
            //...
            "successMessageFlags": "32",
            "isDeleted": false,
            //...
            "firstAccess": "2014-09-15T03:36:25.027Z",
            "lastUpdate": "2021-01-15T20:44:04.305Z",
            //...
            "showActivity": true,
            //...
        }
    }
```
Normally, I would consider this to be a Bungie.net user with no Destiny accounts linked. However, the user provided me with a screenshot of his profile, showing that he has a linked Xbox account (and also that he authorized my app).

![](https://user-images.githubusercontent.com/62850073/104853222-04f68b00-58c5-11eb-854a-eb02edf5b085.png)

If I search for that Xbox user I can find it, but it doesn't show any associated BungieNext membership. This makes it impossible for me to link the original BungieNext id that I get from the auth process to the Destiny account. Any idea what I might be missing?

**Comment by jshaffstall-bng** [comment]
It looks like that Destiny account linking is hidden from unauthenticated requests. For example, if you visit that profile page while not signed into Bungie.net, you won't see the Xbox account there - https://www.bungie.net/en/Profile/254/6736624/SpiniestGnu40

As a workaround, you could use OAuth to authenticate with your Bnet account, and then make those requests with your app.

**Comment by Aioros** [comment]
Thank you for the reply, John. It doesn't seem that I can see their linked account while using my own credentials, so I assume that I would need to use the user's access token in my request.

**Comment by jshaffstall-bng** [comment]
Now that I'm reading this again more closely, you could ask this user to display the Xbox account publicly, in the Accounts & Linking settings on Bungie.net.
