### ISSUE TITLE
Openapi-2.json with Swagger-Client resolves to incorrect protocol

### ISSUE THREAD

**Issue by theoperatore** [Bungie-net/api#14]
Using the newest [swagger-client](https://www.npmjs.com/package/swagger-client) for node, which seems to only support 2.0 specs, I kept getting an error for the server field. the client seems to be adding an extra `http` beofre the `host` field so requests become:

```
http://https://bungie.net/Platform/...
```

If I removed the `https://` at the beginning of the `host`, it all works correctly and resolves to using `https` correctly.

I'm not 100% sure if this is a quirk with swagger-client, or an error with the codegen used; just reporting so it's known!

At the very least, thanks for all of the documentation! It's super great to see these endpoints in a documented manner and so organized too! Wondrous! I'm also super pumped for the amount of stats and granularity that can be returned! Let the analytic creativity FLOW!

here is a snipped of the `openapi-2.json` file that is relevant to this issue:

```json
{
  "swagger": "2.0.0",
  "info": {
    "title": "Bungie.Net API",
    "description": "These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.",
    "termsOfService": "https://www.bungie.net/en/View/Bungie/terms",
    "contact": {
      "name": "Bungie.net API Support",
      "url": "https://github.com/Bungie-net/api",
      "email": "support@bungie.com"
    },
    "license": {
      "name": "BSD License 2.0",
      "url": "https://github.com/Bungie-net/api/blob/master/LICENSE"
    },
    "version": "2.0.0"
  },
  "host": "https://bungie.net",
  "basePath": "/Platform",
  "paths": {}
```

**Comment by vthornheart-bng** [comment]
Ah, thanks for the info!  I will have to look into it - our service requires https, so perhaps there is an alternative way for us to define it in the spec.

**Comment by vthornheart-bng** [comment]
Ah, sure enough!  Apparently OAuth 3.0 requires a full URL, and 2.0 requires you to separate out the host and scheme(s) supported.  I'll have that fixed up for the next deployment.

**Comment by theoperatore** [comment]
Mmm fair enough! Is this the sort of thing you'd want a PR for? Or is
raising an issue the preferred way to contribute?

**Comment by vthornheart-bng** [comment]
Should be fixed as of this version - grab the latest now!  In this case, it's straightforward enough that we don't need a PR - a PR would be helpful for us to see things like the typo issue that was recently filed, where a PR would let us do a diff to see where the typos are.  Other types of bugs (like this one) are ones that we can fix either in the config for our swagger generator or in the generator code itself, so a PR's less useful in that situation.
