### ISSUE TITLE
Javascript "connect ECONNREFUSED 127.0.0.1:443"

### ISSUE THREAD

**Issue by BeppeTemp** [Bungie-net/api#1400]
Hi all I'm getting this error when I go to run the example script for http calls with javascript, can anyone help me?

![image](https://user-images.githubusercontent.com/55873294/105576820-c0ac3480-5d75-11eb-839b-f48c86a06171.png)

![image](https://user-images.githubusercontent.com/55873294/105576827-ca359c80-5d75-11eb-844b-26ee594d9f48.png)

**Comment by justrealmilk** [comment]
You should join the official unofficial API community discord server at https://discord.gg/fnDPxB3
