### ISSUE TITLE
High quality render of the seasonal artifact

### ISSUE THREAD

**Issue by baxter** [Bungie-net/api#1403]
Hi there! I've been maintaining a [list of artifacts](https://www.ishtar-collective.net/items/artifacts) on the Ishtar Collective since TTK.

Since D2 I've been able to get a high-quality image for the seasonal artifact from the bungie website, but the Fang of Xivu Arath did not have one.

Ideally, I wouldn't need to go to the website and the API would include high-quality transparent PNG renders of the artifacts that I could use on the artifacts page :)

Is this something you can consider?

Thanks,

— baxter

**Comment by jshaffstall-bng** [comment]
As in, you would go to a season promotional page and find a high-resolution render of the artifact on a transparent background? Or did you remove the background manually?

**Comment by baxter** [comment]
> As in, you would go to a season promotional page and find a high-resolution render of the artifact on a transparent background?

Yes, exactly that.
