### ISSUE TITLE
Iron Banner Matches not showing up in Activity History

### ISSUE THREAD

**Issue by mikechambers** [Bungie-net/api#1404]
Seems like the same issue as #1362 .

Last two iron banner matches I played over the past two hours have not showed up in activity history:

https://www.bungie.net/Platform/Destiny2/1/Account/4611686018429783292/Character/2305843009264966985/Stats/Activities/?mode=5&count=5&page=0

(tried AllPvp, IronBanner, and None)

Last registered one was at 2021-02-04T19:19:43Z.

Just to follow up on this a couple of hours later and about 5 more games played, to confirm that no Iron Banner matches are showing up in Activity history API anymore.

**Comment by ash3825** [comment]
Can confirm.  Last IB match logged by my application was at 2021-02-04T 20:56:36Z (PGCR 7891893773)

**Comment by jshaffstall-bng** [comment]
Thanks for the report, we're looking into this now.

**Comment by jshaffstall-bng** [comment]
This should be fixed for new activities now. Thanks again, and please let us know if you come across other activities that don't show up Game History.
