### ISSUE TITLE
How to determine user's destiny expansions ? Shadowkeep, Forsaken, Beyond Light...

### ISSUE THREAD

**Issue by WolandRoot** [Bungie-net/api#1406]
Hi,
I'm integrating api with discord bot and want to know how to collect information about specified player expansions (using membershipId). I've got information about season ownership but one can acquire a season without acquiring an expansion.
For example it's possible you own Season of The Hunt but haven't got the access to Deep Stone Crypt activity as a result of not having Beyond Light expansion.

My problem is:
How to determine if a player owns a specific expansion using bungie net API?

**Comment by joshhunt** [comment]
GetProfile with `?components=100` It's as `versionsOwned`. It's a flag/bitwise enum, so you'll need to do the checks for each version.

https://data.destinysets.com/api/Destiny2.GetProfile?destinyMembershipId=4611686018469271298&membershipType=2&components=100

https://bungie-net.github.io/index.html#/components/schemas/Destiny.Entities.Profiles.DestinyProfileComponent

**Comment by WolandRoot** [comment]
Thank You
