### ISSUE TITLE
How can I get items that located in Postmaster?

### ISSUE THREAD

**Issue by jhchoi123** [Bungie-net/api#1407]
I tried to get Postmaster's Item List by using both endpoint "Destiny2.GetCharacter" and "Destiny2.GetProfile"

I sent request
```
// components 102 == ProfileInventories
/Destiny2/{MY_MEMBERSHIP_TYPE}/Profile/{MY_DESTINY_MEMBERSHIP_ID}/?components=102

// components 201 == CharacterInventories
/Destiny2/{MY_MEMBERSHIP_TYPE}/Profile/{MY_DESTINY_MEMBERSHIP_ID}/Character/{MY_CHARACTER_ID}/?components=201
```

with header

```
Content-Type: application/json
X-API-Key: {MY_API_KEY}
Authorization: Bearer {MY_OAUTH_TOKEN}
```

and tried to find items where located in Postmaster 

```typescript
// Response of /Destiny2/{MY_MEMBERSHIP_TYPE}/Profile/{MY_DESTINY_MEMBERSHIP_ID}/?components=102
const items = Response.profileInventory.data.items;

for(const item of items) {
    if(item.location == 4) {
        // some process with Postmaster's Item
        // but there is no items that location value is 4 (Destiny.ItemLocation.Postmaster)
    }
}
```
```typescript
// Response of /Destiny2/{MY_MEMBERSHIP_TYPE}/Profile/{MY_DESTINY_MEMBERSHIP_ID}/Character/{MY_CHARACTER_ID}/?components=201
const items = Response.inventory.data.items;

for(const item of items) {
    if(item.location == 4) {
        // same result
        // there is no items that location value is 4
    }
}

```

Of course, I have some items in Postmaster like ENHANCEMENT PRISM and SPOILS OF CONQUEST and more...

but there no items where located Postmaster

Is there any way to get Postmaster's items?

**Comment by nev-r** [comment]
to figure out where an item "is", in terms of game concepts,
you need to use a combination of information:
- which API call the item was found in
- the item's `location` property
- the item's `bucketHash` property

you're looking for items in the `characterInventory`, which are currently in the Lost Items bucket (215593132)
so you want something like `if (item.bucketHash == 215593132)`
