### ISSUE TITLE
Duplicate plugs in PlugSetDefinitions with different currentlyCanRoll values

### ISSUE THREAD

**Issue by afpac** [Bungie-net/api#1409]
See https://data.destinysets.com/i/PlugSet:2744704843

Index 1 is Quickdraw 706527188 and has currentlyCanRoll set to false
Index 5 is also Quickdraw and has currentlyCanRoll set to true

Is there a rule here that I'm just missing? Should whichever shows up in the list last be authoritative, or is this just a bug?

**Comment by afpac** [comment]
[Apostate](https://www.light.gg/db/items/2164448701/apostate/) is the item that led me down this path, by the way.

**Comment by jshaffstall-bng** [comment]
Interesting! I suspect that this is a consequence of 'sunsetting' all of the older socket rolls, but then Quickdraw got added back as a possible roll in the newer item version.

So I don't think this is really an issue. On your site, you can show 'older versions could roll Quickdraw, AND newer versions can roll it too.'

I'm going to close this, but feel free to comment or file a new issue if you find anything else that might be broken.
