### ISSUE TITLE
Season of the Hunt end date was set back a year

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#1410]
Season of the Hunt end date was changed from 2021 to 2020. The end date is now before the beginning.

https://archive.destiny.report/version/4498a160-bf34-466f-ab2f-c81849526feb/DestinySeasonDefinition/modified/2809059427

**Comment by jshaffstall-bng** [comment]
lol oops

**Comment by jshaffstall-bng** [comment]
Filed as TFS 976815. This will be fixed with the Bnet content update on Feb 16. Thanks for the heads up!

**Comment by jshaffstall-bng** [comment]
This should be fixed with new content now.

**Comment by joshhunt** [comment]
It is!

I see also start/end dates were added to Season 14 `2809059429`, but the end date is `2022-08-11` making the season 15 months long. It is an upcoming season, so I'm not sure how concerned you are about this...

**Comment by jshaffstall-bng** [comment]
It's a looooooong season.

Long.
