### ISSUE TITLE
All new items are missing at least part of their 3D content.

### ISSUE THREAD

**Issue by TiredHobgoblin** [Bungie-net/api#1412]
Nearly all new items from Season of the Chosen have missing data. Armor items have geometry and primary textures, but no detail textures or material properties. Items of other types are missing geometry and primary textures alongside the missing tilemaps and material properties.

## Items missing all content:
Sparrows: `397043529,774879414,2056426001,2056426000,2056426003,2056426002,2056426005,2056426004`

Weapons:
`1313528549,2448907086,2496242052,1481892490,3836861464,47772649,3075224551,3473290087,893527433,409551876,2121785039,4156253727,432476743,2527666306,2351180975,1046651176,2060863616,3258665412,2481881293,3460122497,2147010335,2633186522,1097616550,1173780905,3658188704,3260753130`

Weapon Ornaments:
`2528315727,568877018,3802742250,3925195811,4231724739,2267660625,4074521886,287295296,1132740485,1132740487,1132740486`

Ships: `1018723385,1018723384,1018723387,1018723386,1018723389,1953632753,397043529,2710956576`

Ghost Shells: `1249788648,970919108,758112594,2635366068,2012043037,2012043036,2012043039,2012043038,2012043033,2012043032`

Other:
`1645521766`, the dummy item that carries the DestinyGearAssetsDefinition for the “Fang of Xivû Arath” seasonal artifact.

## Items missing dye/material data and tilemaps:
Armor Ornaments: `3592193383,32123025,2227552940,2388099734,2344999081,2250029820,1044330340,2212617913,1597467149,1252957702,2942529901,1916301843,251217994,4111701460,3188871471,48380374,2956050458,2179943275,2188215631,1260659632,999504644,1813208572,3099145329,2365135029,2547166766,3154888563,3721737629,888758224,3149327402,2889842501,3951784665,3049004864,46563601`

Armor:
`2321120637,1935198785,3301944824,4003170632,1260563064,3350504921,1724366537,412014143,2671565007,1947723211,2016308379,1659172686,48110686,505747572,1001798188,3673119885,197672677,3100185651,2540765499,48951631,120441703,1010644330,1322042322,3311198527,4161591237,3245065734,605724052,2166974634,2304861612,2804094976,469005214,2803792315,708549601`

Shaders: `2320367075,2320367074,726145097,647195977,117960780,1854244374,1854244375,179465689,4166922308`

**Comment by jshaffstall-bng** [comment]
Thanks for digging into this, and sorry for the inconvenience. I don't have an ETA for a fix, but I've filed TFS 976944 to investigate.

**Comment by jshaffstall-bng** [comment]
Actually, I do have an ETA for you - this should be fixed with new Bnet content on Feb 16.

**Comment by jshaffstall-bng** [comment]
This should be fixed now.
