### ISSUE TITLE
Gambit progression (2772425241) has vanished

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1413]
It’s no longer returned as part of characterProgressions component progression property although it does appear under factions

**Comment by jshaffstall-bng** [comment]
Sorry, how do you mean? It looks like the Infamy progression is working in the API.

**Comment by fremgenc** [comment]
They're there.

3448738070 = Weekly gambit (Complete 3 matches)

3802603984 = Complete bounties for drifter

**Comment by jshaffstall-bng** [comment]
Those look like Gambit 'Challenges' though, and not Infamy progression. Filed as TFS 977013 to investigate.

**Comment by jshaffstall-bng** [comment]
With the update on 2/16, the 'Infamy' progression and all other 'faction' progressions will be added to the 'progressions' dictionary, in addition to already being in the 'factions' progression dictionary.

**Comment by jshaffstall-bng** [comment]
This should be fixed now.
