### ISSUE TITLE
Can I get Seasonal Challenges information from API?

### ISSUE THREAD

**Issue by unitymind9** [Bungie-net/api#1414]
Season of the Chosen is started, and seasonal challenges are added. can I get information of seasonal challenges? (challenge name, icon, rewards, etc.)

**Comment by joshhunt** [comment]
Seasonal Challenges, from the API's perspective, are just the same as Triumphs. They use the same PresentationNodes and Record entities.

There is a PresentationNode for the "root" Seasonal Challenges category, https://data.destinysets.com/i/PresentationNode:3443694067, and all the challenges are organised underneath them.

Player's progress in the live API, again it is identical to Triumphs - request GetProfile with component 900 and you'll find them under profileRecords and/or characterRecords (it looks like they're actually just under characterRecords annoyingly enough, despite them supposedly being account-wide) https://data.destinysets.com/api/Destiny2.GetProfile?destinyMembershipId=4611686018469271298&membershipType=2&components=900

**Comment by unitymind9** [comment]
Thanks a lot! :)
