### ISSUE TITLE
Battleground not available in milestones

### ISSUE THREAD

**Issue by fremgenc** [Bungie-net/api#1415]
I cannot find battlegrounds status in milestones, and couldn't find a related hash in DestinyMilestoneDefinition

![image](https://user-images.githubusercontent.com/12090308/107552894-15d3ad00-6ba2-11eb-8984-a8f224ca3385.png)

For comparison, here's the weekly strikes, which can be tracked using hash: 1437935813

![image](https://user-images.githubusercontent.com/12090308/107552971-2d129a80-6ba2-11eb-8ca9-402a922742ce.png)

**Comment by jshaffstall-bng** [comment]
Yep, and after 3 completions, it looks like you get a second challenge for 6 completions. Filed as TFS 976809.

**Comment by jshaffstall-bng** [comment]
This should be available now.
