### ISSUE TITLE
Path to Power Triumph

### ISSUE THREAD

**Issue by t3rr11** [Bungie-net/api#1416]
So last season i was looking for a way to grab someones highest power without O-Auth and since triumphs are public I found this triumph "Path to Power" (added with beyond light) showed their highest obtained power. It worked great (last season) but now it is in-accurate.

The best assumption is that come this new season the triumph was bumped up to reflect the power increase from this season. But will keep it's claimed status. For example, previously the highest tier (4) of the triumph was for hitting 1250. This season it is now 1300, but since i obtained the highest tier last season it thinks i've already hit 1300 this season, whilst i have not.

That's one problem but not the main problem i am having. I use this triumph to create rankings and leaderboards for the highest obtained power, but i have been getting reports that it's not showing peoples highest power.

![chrome_2021-02-12_12-05-39](https://user-images.githubusercontent.com/2139233/107721334-4fd0ba80-6d2c-11eb-857f-911a4e3b6434.png)

In the image above you can see that their highest power according to the triumph is 1271, But they clearly have 1295 power listed under their name (using braytech.org as it's neater to read than looking at raw data, thanks tom). Even if the triumph was changed to reflect someone's power level minus the artifact at 31 season rank there is no way they've obtained enough power bonus to get 1295. 

I know this is most likely a game issue, but i was looking for insight into what changed with the triumph and is there another way of obtaining someone's highest obtained light level publically as i've run out of ideas of where to look?

**Comment by fegkay15** [comment]
This is still an issue in 2025. Is there anything that can be done for this? An example is of this player being at 178 light level, but the triumph reports as 73:
https://www.bungie.net/Platform/Destiny2/3/Profile/4611686018520200613/?components=200,900

<img width="1044" height="429" alt="Image" src="https://github.com/user-attachments/assets/038b8e84-64c4-4fc3-88e7-5c6ed20b6f6d" />
