### ISSUE TITLE
Hunter's shining night. No decorations.

### ISSUE THREAD

**Issue by chocream** [Bungie-net/api#1418]
Hunter's shining night Guntlet Universal Decoration appears in the collection, but not in the appearance change screen.

![tiger_release_final_20210213_223010](https://user-images.githubusercontent.com/79010679/107851531-1001f400-6e4e-11eb-916d-1c2ecefd9dc7.png)
![tiger_release_final_20210213_223023](https://user-images.githubusercontent.com/79010679/107851532-11332100-6e4e-11eb-88b6-6ca598631be6.png)

**Comment by jshaffstall-bng** [comment]
Interesting, this looks like a game-side issue. Could you link us to your Bungie.net account, so that we can investigate your Destiny account state?

**Comment by chocream** [comment]
It's connected to Bunginet.
