### ISSUE TITLE
DestinyItemComponent#tooltipNotificationIndexes never populated

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#1419]
`DestinyInventoryItemDefinition#tooltipNotifications` says:

> Tooltips that only come up conditionally for the item. Check the live data
> DestinyItemComponent.tooltipNotificationIndexes property for which of these
> should be shown at runtime.

However, `DestinyItemComponent#tooltipNotificationIndexes` is never populated as far as I can tell. Also, the actual `DestinyItemTooltipNotification` objects' `displayStyle` property is always an empty string, making it impossible to tell whether to apply the "expires at end of season" styling. This is especially weird since some items have random junk in their `tooltipNotificationIndexes`, such as https://data.destinysets.com/i/InventoryItemLite:1340460623 having only the string "Exotic".

**Comment by jshaffstall-bng** [comment]
Interesting! Filed as TFS 978252.

**Comment by jshaffstall-bng** [comment]
What if these indices were always being computed, but never got added to the responses?

hahaha that would be crazy

**Comment by jshaffstall-bng** [comment]
Thanks for this report. The current plan is to deploy the fix on Tuesday, 2/23.

**Comment by bhollis** [comment]
Thanks!
