### ISSUE TITLE
Cartesian Coordinate lore has 'Tarantula' title

### ISSUE THREAD

**Issue by baxter** [Bungie-net/api#1420]
Hi there! It looks as though the item [Cartesian Coordinate (2481881293)](https://data.destinysets.com/i/InventoryItem:2481881293) points to a loreHash with the name [Tarantula (2481881293)](https://data.destinysets.com/i/Lore:2481881293). But the item [Tarantula (3335343363)](https://data.destinysets.com/i/InventoryItem:3335343363) points to a different loreHash that also has the name [Tarantula (3335343363)](https://data.destinysets.com/i/Lore:3335343363).

I think the lore entry [Tarantula (2481881293)](https://data.destinysets.com/i/Lore:2481881293) is the lore for Cartesian Coordinate, but it has the wrong name.

**Comment by baxter** [comment]
Hello, an update to this, it has been pointed out to me that the lore entry for [Extraordinary Rendition (1097616550)](https://data.destinysets.com/i/Lore:1097616550) is practically identical to the lore hash for [Tarantula (2481881293)](https://data.destinysets.com/i/Lore:2481881293), so I don't know what is going on.

Thanks!

**Comment by jshaffstall-bng** [comment]
Thanks for catching this! I've filed TFS 979794 on the game side, but I'm closing this out as it's not an API issue.
