### ISSUE TITLE
Tess's Bright Dust shaders API doesn't match in game store

### ISSUE THREAD

**Issue by dcaslin** [Bungie-net/api#1421]
DIM is the easiest place to screenshot this from. Here's what Tess shows for my account (Xbox, 4611686018434964640) there
![image](https://user-images.githubusercontent.com/16437968/107885848-6b71c780-6eca-11eb-931b-97ebdc3690d7.png)

Meanwhile in game: 
![image](https://user-images.githubusercontent.com/16437968/107885869-99efa280-6eca-11eb-9ca6-8cc9e7232dee.png)

What specifically caught my attention is the fact that the API reports that Tess is selling Laguna cruiser, which is a shader I don't have in my collections (oddly the API reports that I've already purchased it). 

![image](https://user-images.githubusercontent.com/16437968/107885886-b7247100-6eca-11eb-8373-40ea3c0da6aa.png)

**Comment by jshaffstall-bng** [comment]
Thanks for the report! I could be some kind of Bnet content mismatch with the game, so the vendor item indices might not be totally correct.

**Comment by jshaffstall-bng** [comment]
Filed as TFS 978272.

**Comment by nev-r** [comment]
to expand on this a smidge,
season 13 week 2, weekly offerings look like this in game:
![image](https://user-images.githubusercontent.com/68782081/108172300-82bed980-70b1-11eb-91c8-2f4421d95e12.png)

here's api:
![image](https://user-images.githubusercontent.com/68782081/108176061-607b8a80-70b6-11eb-8101-8564842c626f.png)

tertiary objective exotic ornament is in API response twice (it should be, it's under seasonal and weekly in game)
```
"41": {
  "saleStatus": 3,
  "failureIndexes": [],
  "augments": 0,
  "vendorItemIndex": 41,
  "itemHash": 287295296,
  "quantity": 1,
  "costs": [{ "itemHash": 3147280338, "quantity": 700 }],
  "overrideNextRefreshDate": "2021-02-23T17:00:00Z"
},
"263": {
  "saleStatus": 2,
  "failureIndexes": [],
  "augments": 0,
  "vendorItemIndex": 263,
  "itemHash": 287295296,
  "quantity": 1,
  "costs": [{ "itemHash": 3147280338, "quantity": 500 }],
  "overrideNextRefreshDate": "2021-02-23T17:00:00Z"
},
```

however, one claims to be for 500 silver and one for 700. in game they're both 700.
following vendorItemIndex to defs data shows the correct price (700) for both

in all cases i spot checked, itemHash matched the item found at that vendorItemIndex, so if it's an index mismatch, DestinyVendorSaleItemComponent must be deriving itemHash from the same wrong data

also, these **4** are marked as being on "Daily Sale" according to their augments.
![image](https://user-images.githubusercontent.com/68782081/108176019-4fcb1480-70b6-11eb-9c94-b0b1d1581ef1.png)

does that seem right? as far as i know, which isn't *that* far, this was normally just 1 item, from checking my historical vendor responses

**Comment by jshaffstall-bng** [comment]
This was a slight vendor content mismatch with the game, and we are planning to deploy new content to fix this tomorrow morning, before Trials starts.
