### ISSUE TITLE
Manifest description for Moon Master Lost Sector Activities incorrectly ends with ":Legend"

### ISSUE THREAD

**Issue by dcaslin** [Bungie-net/api#1422]
Effects the following 4 hashes: 

'567131519', // K1 Log
'2829206720', // K1 communion
 '184186578', // K1 Crew
 '3911969238', // K1 Revelation
 
 
For example: 

"name": "K1 Revelation: Legend"  should be "name": "K1 Revelation: Master"

**Comment by t3rr11** [comment]
Just noticed this myself whilst going through, good catch!

**Comment by justrealmilk** [comment]
Thankfully, the descriptions are correct

**Comment by t3rr11** [comment]
Yup, which is how i could tell the difference :'D

**Comment by jshaffstall-bng** [comment]
Curious, I wonder if this is a game-side content bug? Filed as TFS 978254.

**Comment by jshaffstall-bng** [comment]
Did this fix itself at some point? This one says 'K1 Revelation: Master' now, which I assume is correct.

https://data.destinysets.com/i/Activity:3911969238
