### ISSUE TITLE
Hrafnagud has the wrong screenshot

### ISSUE THREAD

**Issue by baxter** [Bungie-net/api#1425]
[Hrafnagud](https://data.destinysets.com/i/InventoryItem:2549526496) appears to have the wrong screenshot. It looks like the screenshot is of Celestial Nighthawk without any ornament, but with a different shader.

**Comment by jshaffstall-bng** [comment]
Good catch! I bet this screenshot was taken in a pre-release game build before the ornament content was wired up. Filed as TFS 978279.

**Comment by jshaffstall-bng** [comment]
Fixed after a refresh - https://www.bungie.net/common/destiny2_content/screenshots/2549526496.jpg
