### ISSUE TITLE
THE SWARM (Machinegun) currently has duplicate instances of Killing Wind

### ISSUE THREAD

**Issue by aundrekerr** [Bungie-net/api#1428]
The plug set for THE SWARM has two instances of Killing Wind listed. There's no difference in them aside from their array position. Both have `currentlyCanRoll` as true. 

https://data.destinysets.com/i/InventoryItem:47772649/PlugSet:2557190660

![swarn](https://user-images.githubusercontent.com/8964981/108603787-fabe2580-7377-11eb-959e-335ab63d072c.png)

**Comment by jshaffstall-bng** [comment]
Thanks for the heads up! I've filed TFS 980355 for the game team, but I'm closing this issue as it's not a Bnet content bug.

**Comment by jshaffstall-bng** [comment]
It sounds like this is a proper bug in the content, and will be addressed in a future game release. Thanks again for the report!
