### ISSUE TITLE
One of this seasons artefact mods has no icon

### ISSUE THREAD

**Issue by NigelHietala** [Bungie-net/api#1429]
Well technically it has a grey *.PNG file https://data.destinysets.com/i/Collectible:1100348073

**Comment by jshaffstall-bng** [comment]
Curious! Filed as TFS 980320.

**Comment by jshaffstall-bng** [comment]
What if the icon file path length was exactly one character over the 260-character limit on Windows?

hahaha that would be crazy

**Comment by jshaffstall-bng** [comment]
This will be fixed with new Bnet content next week on March 2nd. Thanks for this report!
