### ISSUE TITLE
Season pass level

### ISSUE THREAD

**Issue by WolandRoot** [Bungie-net/api#1430]
Hi, 
How to determine user's season pass level via api? Right now I'm trying to use wastedondestiny.com but they still have previous season pass level.

**Comment by Parisito1234** [comment]
[Destiny2.GetProfile](https://bungie-net.github.io/#Destiny2.GetProfile) records should have the info you're looking for.

Here's the endpoint that I was able to find it under
`/Destiny2/{membershipType}/Profile/{destinyMembershipId}/?components=900` 
Season of the Chosen pass level hash is `1661195512` and you can grab the objective data from there. OAuth not required.

I didn't really dig around too much to see if it's able to be found elsewhere, but it's possible.
