### ISSUE TITLE
Banshee-44 inventory

### ISSUE THREAD

**Issue by WolandRoot** [Bungie-net/api#1432]
Hi,
For some time I'm trying to understand how to determine currently available items at Banshee-44. Is there any flag or indicator that can be used for this case?
How to gather information about this week's mods, materials and their prices in Banshee? (For example: if Banshee is selling Lucent Blade). I found DestinyVendorDefiniton and GetVendors endpoint but I cannot determine how to extract needed data. Please provide some example about that.

**Comment by joshhunt** [comment]
@WolandRoot You will need to use the GetVendors endpoint along with some [components](https://bungie-net.github.io/index.html#/components/schemas/Destiny.DestinyComponentType) (I think ?components=402 should be enough?). Note that vendor endpoint requires an authenticated user, so you'll need to implement Bungie OAuth also. You'll probably want to reference the data the API returns with both DestinyVendorDefiniton and DestinyInventoryItemDefinition to get the names of items.

You might find it helpful to use the API Explorer to explore and understand the API a bit more https://data.destinysets.com/api/Destiny2.GetVendors?components=402
