### ISSUE TITLE
Public Milestones endpoint returns error 500 since 2-23 Maint completion

### ISSUE THREAD

**Issue by dcaslin** [Bungie-net/api#1433]
https://www.bungie.net/Platform/Destiny2/Milestones

```
{
    "ErrorCode": 3,
    "ThrottleSeconds": 0,
    "ErrorStatus": "UnhandledException",
    "Message": "We’ve encountered an error, please try again later.",
    "MessageData": {}
}
```

I recall something like this happening in the past where the Public milestones endpoint failed frequently, as I have a commented out hack in D2Checklist code where I saved a canned response and fell back on it.

**Comment by jshaffstall-bng** [comment]
Thanks for the heads up! Filed as TFS 980686, and I'm looking into this now.

**Comment by dcaslin** [comment]
One of my test requests actually succeeded, so I'm restoring the hack. FWIW the old hack had a note about "Feb 12th" though I'm not sure what year =)

**Comment by jshaffstall-bng** [comment]
We're going to try and resolve this over the next hour or so.

**Comment by dcaslin** [comment]
Looks like you got it, I'm not seeing the error anymore. Thanks for the quick turnaround!
