### ISSUE TITLE
DSC node progressValue in not affected by flawless triumph completion.

### ISSUE THREAD

**Issue by Horodep** [Bungie-net/api#1435]
DSC node
https://data.destinysets.com/i/PresentationNode:1726708384
has an objective to complete 18 triumphs. 

The counter of completed triumphs does not increase in player completes flawless run record:
https://data.destinysets.com/i/Record:3560923614

This behavior is unexpected as there is no data indicating on that in the manifest or in the profile api data.

**Comment by Horodep** [comment]
Example.
API node progress:
![image](https://user-images.githubusercontent.com/8913017/109839624-58941c80-7c58-11eb-9400-e840224a9619.png)
List of completed triumphs:
![image](https://user-images.githubusercontent.com/8913017/109839663-66e23880-7c58-11eb-821b-37d47912b554.png)

**Comment by jshaffstall-bng** [comment]
Could it be that this is intentional, so that players can acquire the DSC seal without having a flawless run?

**Comment by Horodep** [comment]
Well, but I'm not talking about seal. That node is EUROPA // ACTIVITIES // DEEP STONE CRYPT.

**Comment by jshaffstall-bng** [comment]
Oh gotcha. My bad!
