### ISSUE TITLE
"Call of the Cryptolith" lore node is dublicated

### ISSUE THREAD

**Issue by Horodep** [Bungie-net/api#1439]
Subject in title.

https://data.destinysets.com/i/PresentationNode:4077680549/PresentationNode:3188244430

PresentationNode [ **3188244430** ] .children.presentationNodes: []
![image](https://user-images.githubusercontent.com/8913017/111060431-e6b8a000-84ad-11eb-8ec1-437c0f85d115.png)

**Comment by jshaffstall-bng** [comment]
Yep, this is a dupe of #1411
