### ISSUE TITLE
Question: Will modifiers icons be provided when they are declassified?

### ISSUE THREAD

**Issue by benedfit** [Bungie-net/api#144]
Currently all very top secret over here https://destiny.plumbing/2/en/raw/DestinyActivityModifierDefinition.json, I assume because we are awaiting the Prestige Raid? But once they are declassified, will the icon for each modifier be returned?

**Comment by vthornheart-bng** [comment]
Yes - indeed, unfortunately, I've been told to wait on releasing modifiers until after they actually appear in-game.  But when they come back, there should be icons!
