### ISSUE TITLE
Request with invalid bearer token leads to a 500 (internal server error) response instead of a 400 or 403

### ISSUE THREAD

**Issue by ghost** [Bungie-net/api#1440]
Hi, I'm making a GET request to https://www.bungie.net/Platform/User/GetBungieNetUserById/11721413/ and getting what looks to be a Cloudflare 500 error in return

![image](https://user-images.githubusercontent.com/159567/111068831-78f88c80-851e-11eb-8b0f-a06598dddae1.png)

`11721413` is the ID I got back in `membership_id` from the OAuth response after I exchanged a token.
I'm passing headers (details redacted, I can provide them to staff if needed) and CORS is working as the XHR request goes through
```
Authorization: Bearer yyy
X-API-Key: xxx
```

Am I doing something completely wrong here?

**Comment by lowlines** [comment]
Just double checking, but are you polling www.bungie.net or bungie.net?

**Comment by voltagex** [comment]
Definitely www.bungie.net

**Comment by voltagex** [comment]
Leaving this open - should be a 400 or 403 instead of a 500, but the issue was that the Bearer token was getting URL Encoded (e.g. `/` becomes `%2F`)

Once I decoded this and passed the correct Bearer token it works fine!

**Comment by jshaffstall-bng** [comment]
Filed as TFS 985857 for the improper response error code. Updating the title as well.
