### ISSUE TITLE
Garden of Salvation Milestone missing phase info

### ISSUE THREAD

**Issue by lowlines** [Bungie-net/api#1441]
The milestone for Garden of Salvation is currently not returning any phase info and looking at the milestone definition, it seems to also be missing the associated activity.

https://data.destinysets.com/i/Milestone:2712317338

Looking at Last Wish, there's a phases section under each activity which lines up with what is returned from GetProfile[202]
https://data.destinysets.com/i/Milestone:3181387331

**Comment by jshaffstall-bng** [comment]
Sounds related to #1370

**Comment by jshaffstall-bng** [comment]
This issue is filed separately as TFS 985851.
