### ISSUE TITLE
Missing Milestone for Weekly Presage

### ISSUE THREAD

**Issue by lowlines** [Bungie-net/api#1443]
Like Harbinger, this weekly pinnacle should have a milestone for it. It does show up under available activities though.

https://data.destinysets.com/i/Activity:2124066889
https://data.destinysets.com/i/Activity:4212753278

**Comment by jshaffstall-bng** [comment]
Good catch! Filed as TFS 985848 for us to add, but it won't be there for the 3.1.1 release tomorrow.

**Comment by jshaffstall-bng** [comment]
This challenge was added last week. Enjoy!
