### ISSUE TITLE
API call for purchasing bounties

### ISSUE THREAD

**Issue by Wolftousen** [Bungie-net/api#1445]
Just started tinkering around and was curious if there is an API call for purchasing bounties from vendors or if that is something that is planned to be allowed through the API at some point.

I know it's possible from the D2 companion app, but I'd like to be able to do it through DIM or Ishtar since I use those far more often.

**Comment by broady** [comment]
https://github.com/Bungie-net/api/issues/810

**Comment by jshaffstall-bng** [comment]
The BuyItem API is not available for 3rd-party apps, and we don't have a timeline for when it might become available.

But maybe someday!
