### ISSUE TITLE
DestinyProfileTransitoryPartyMember is missing membership type

### ISSUE THREAD

**Issue by broady** [Bungie-net/api#1446]
https://bungie-net.github.io/#/components/schemas/Destiny.Components.Profiles.DestinyProfileTransitoryPartyMember

provides membershipId but not membershipType

**Comment by jshaffstall-bng** [comment]
Interesting! Filed as TFS 988117.

**Comment by jshaffstall-bng** [comment]
Unfortunately the membership type isn't easily accessible there, so this isn't trivial to include in the API. But this is on our list now and hopefully it won't be too long before we can add it.
