### ISSUE TITLE
How to get the present progression of the lore ?

### ISSUE THREAD

**Issue by lclbm** [Bungie-net/api#1447]
I encountered a problem, I cannot get the completion progress of the specific lore.
Such as this one:   "name":"Fideicide I","hash": 428936653
![image](https://user-images.githubusercontent.com/54730982/111892351-a751fc80-8a35-11eb-9844-ad254cdc4e97.png)
I can't find it in GetProfileAPI
Can u help me?

**Comment by joshhunt** [comment]
The completable lore entries are actually just Trumphs in disguise. You'll find them in the Profile API under Records.

**Comment by lclbm** [comment]
> The completable lore entries are actually just Trumphs in disguise. You'll find them in the Profile API under Records.
Yes I know, but how can know this lore is completed ?
![image](https://user-images.githubusercontent.com/54730982/112193865-46980f00-8c43-11eb-917c-f2b1b220e331.png)
Just like this one, the data in the Profile API under Records only shows state and intervalsRedeemedCount.
![image](https://user-images.githubusercontent.com/54730982/112193896-4d268680-8c43-11eb-8c3f-588b3d6f77d0.png)
Thank you for your help 👍

**Comment by joshhunt** [comment]
state is a bitwise/flags enum that tells you the state of that record for
the player/character, including whether it’s completed or not.

You’ll need to do a bitwise AND with state the value you’re testing and
check the result.
