### ISSUE TITLE
Glykon/Presage Smuggler compartment and scannable tracking

### ISSUE THREAD

**Issue by dcaslin** [Bungie-net/api#1448]
Would be awesome if we could get these in a checklist (or wherever they best fit)

**Comment by jshaffstall-bng** [comment]
Agreed! Filed as TFS 988118.

**Comment by jshaffstall-bng** [comment]
We added a new checklist for the Glykon clues in the new content update today. Enjoy!

https://data.destinysets.com/i/Checklist:3975225462
