### ISSUE TITLE
Manifest reverted back to 91966.21.03.02.2023-2-bnet.36361

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#1449]
👋 I'm having trouble getting the latest definitions.

[At 8:09 UTC I saw](https://twitter.com/destinyDefs/status/1374453393813467147) a new manifest with a version of 92539.21.03.17.1630-3-bnet.36521 , however downloading one of the jsonWorldContentPaths 404ed and it errored out. Now, requesting the Manifest only returns the previous 91966.21.03.02.2023-2-bnet.36361 version.

See latest log https://github.com/joshhunt/destiny-definitions/runs/2178859474?check_suite_focus=true#step:5:20 - The id `aec69088-d246-4c61-b4fc-cd92fd2bd63b1` refers to the GUID in the jsonWorldContentPaths URLs

**Comment by joshhunt** [comment]
I cannot get the new Manifest to return either in Github Actions (so, on Github's servers/network) or locally for me in the UK, so I think that would rule out local POP caching.

**Comment by joshhunt** [comment]
I'm cache busting (`?bust=${Date.now()}`) the Manifest URL and I'm still getting old manifest https://github.com/joshhunt/destiny-definitions/runs/2179014130?check_suite_focus=true#step:5:21

**Comment by jshaffstall-bng** [comment]
Thanks for the heads up, we're investigating.

**Comment by jshaffstall-bng** [comment]
Looks like we only had the new content on a handful of servers for a short period of time. We've reverted back to only the old content, and we're planning to deploy the new content later today.

Thanks again, and sorry for the confusion!

**Comment by jshaffstall-bng** [comment]
The new content is being deployed now, and we should be all set soon.
