### ISSUE TITLE
D2 - exotic armor perk -- double title

### ISSUE THREAD

**Issue by thezoggy** [Bungie-net/api#145]
the title for the exotic armor perk is repeated again in the description, this affects apps like DIM:

![dim2](http://zoggy.net/firefox_2017-09-18_12-48-56.png)

per DIM author: 
> This is a Bungie data issue. For only some items, the perk description includes its name.

**Comment by vthornheart-bng** [comment]
I'll look into what we can do to cleanse that.

**Comment by duckmanBR** [comment]
Why close this?  It's still an ongoing issue...

**Comment by thezoggy** [comment]
just was closing out old GI that havent had any activity

**Comment by bhollis** [comment]
What's an example of an item that still shows this? The one in #232 seems to be fixed now, and the screenshot has expired.

**Comment by thezoggy** [comment]
photo expired after a year, i've reuploaded it.

**Comment by bhollis** [comment]
Not seeing it for Raiden Flux anymore.
