### ISSUE TITLE
Bug: ActivityHash 3965063488 Can't be found

### ISSUE THREAD

**Issue by lclbm** [Bungie-net/api#1450]
directorActivityHash:3965063488 Can't be found.
membershipId:4611686018494486609
membershipType:3
characterId:2305843009539975259
When I try to query the activity of this character, the directorActivityHash can not be found in DestinyActivityDefinition.
![image](https://user-images.githubusercontent.com/54730982/112727652-748c9480-8f5e-11eb-8c52-59129b96dd90.png)
Just like this, no result.
![image](https://user-images.githubusercontent.com/54730982/112727694-ac93d780-8f5e-11eb-908d-f7c32c73f25c.png)
![image](https://user-images.githubusercontent.com/54730982/112727696-b0275e80-8f5e-11eb-94fc-93649ff0ee3e.png)
And Braytech will crash too.
![image](https://user-images.githubusercontent.com/54730982/112727706-be757a80-8f5e-11eb-9656-54910cb44d7e.png)
Cannot read property 'hash' of undefined.

**Comment by justrealmilk** [comment]
Thanks for the indirect bug report!

The definition is in fact missing.

**Comment by jshaffstall-bng** [comment]
Do we know what this activity hash used to be? I can't find it in my initial pass, even when looking through old activity definitions.

**Comment by floatingatoll** [comment]
If it helps any, it was published to us on March 9th, 2020. I can't load the full release notes for some reason but:

Destiny 2 API Change Summary - Monday, March 9, 2020 - light.gg

[...]

Mar 9, 2020 — <Unnamed #3965063488>. History. ADDED. <Unnamed #4031266743>. History. ADDED. <Unnamed #4144264547>. History [...]

**Comment by nev-r** [comment]
it says it takes place in Echo Mesa/Io,
appeared starting in the season of the worthy,
and seems pretty rare/bug, since i couldn't find it in the histories of several very busy d2 accounts

march 2020 version of this def (claims to be Story/AllPVE)
```json
{
  "displayProperties": { "description": "", "name": "", "icon": "/img/misc/missing_icon_d2.png", "hasIcon": false },
  "originalDisplayProperties": { "description": "", "name": "", "icon": "/img/misc/missing_icon_d2.png", "hasIcon": false },
  "releaseIcon": "/img/misc/missing_icon_d2.png",
  "releaseTime": 0,
  "activityLevel": 1,
  "completionUnlockHash": 0,
  "activityLightLevel": 0,
  "destinationHash": 2218917881,
  "placeHash": 4251857532,
  "activityTypeHash": 1686739444,
  "tier": -1,
  "rewards": [],
  "modifiers": [],
  "isPlaylist": false,
  "challenges": [],
  "optionalUnlockStrings": [],
  "inheritFromFreeRoam": false,
  "suppressOtherRewards": false,
  "playlistItems": [],
  "matchmaking": { "isMatchmade": false, "minParty": 1, "maxParty": 3, "maxPlayers": 3, "requiresGuardianOath": false },
  "directActivityModeHash": 1686739444,
  "directActivityModeType": 2,
  "activityModeHashes": [1686739444, 1164760493],
  "activityModeTypes": [2, 7],
  "isPvP": false,
  "insertionPoints": [],
  "activityLocationMappings": [{ "locationHash": 2049601857, "activationSource": "lz", "activityHash": 3965063488 }],
  "hash": 3965063488,
  "index": 273,
  "redacted": false,
  "blacklisted": false
}
```

april 2020 version of this def (claims to be Social. weird.)
```json
{
  "displayProperties": { "description": "", "name": "", "icon": "/img/misc/missing_icon_d2.png", "hasIcon": false },
  "originalDisplayProperties": { "description": "", "name": "", "icon": "/img/misc/missing_icon_d2.png", "hasIcon": false },
  "releaseIcon": "/img/misc/missing_icon_d2.png",
  "releaseTime": 0,
  "activityLevel": 1,
  "completionUnlockHash": 0,
  "activityLightLevel": 0,
  "destinationHash": 2218917881,
  "placeHash": 4251857532,
  "activityTypeHash": 1686739444,
  "tier": -1,
  "rewards": [],
  "modifiers": [],
  "isPlaylist": false,
  "challenges": [],
  "optionalUnlockStrings": [],
  "inheritFromFreeRoam": false,
  "suppressOtherRewards": false,
  "playlistItems": [],
  "matchmaking": { "isMatchmade": false, "minParty": 1, "maxParty": 3, "maxPlayers": 3, "requiresGuardianOath": false },
  "directActivityModeHash": 1589650888,
  "directActivityModeType": 40,
  "activityModeHashes": [1589650888],
  "activityModeTypes": [40],
  "isPvP": false,
  "insertionPoints": [],
  "activityLocationMappings": [{ "locationHash": 2049601857, "activationSource": "lz", "activityHash": 3965063488 }],
  "hash": 3965063488,
  "index": 275,
  "redacted": false,
  "blacklisted": false
}
```

pretty clear cut case of just really old pgcrs/activity data, referring to now-removed activity defs
