### ISSUE TITLE
Daily Lost Sectors

### ISSUE THREAD

**Issue by genbaguettson** [Bungie-net/api#1451]
Hi,

I have been going through different mobile dbs and JSONs trying to figure out how to get the currently active Master and Legend lost sector, but I'm having some trouble finding the relevant information.

I don't think there's a route for daily milestones (they aren't milestones anyway), and I'd like some help in finding the information I want.

I'm having the same problem with the current Altar of Sorrow weapon for example, really all the information that is _important_ but not a _milestone_ per se. Maybe the doc could use a few more examples for that now crucial but not evidently exposed data ? :) Or maybe they exist and I missed them.

Have a great day !

**Comment by joshhunt** [comment]
Generally speaking, rotations are not defined in the API or definitions - they've been reverse engineered by the community and hard-coded into apps.

**Comment by genbaguettson** [comment]
Thanks a lot for the answer !

That's too bad though, I feel like it'd be a neat feature to add these informations on a route somewhere, especially since more and more are appearing, and it's pretty useful data.
