### ISSUE TITLE
Issue: [PS4] Bug in boss battle of Beyond Light

### ISSUE THREAD

**Issue by MasonT8198** [Bungie-net/api#1455]
Seems there isn't a check for if the person returned to first person, so you can permanently be stuck in Third Person if knocked off and revived, rather unsettling

**Comment by ashakoor** [comment]
This is not the place to report Destiny game issues, this is only for the Bungie API. Nobody here can help you, your best bet is to go to the ["Game Issues" section of the Bungie.net forums.](https://www.bungie.net/en-US/Forums/Topics?pNumber=0&tg=Help%20Gameplay)
