### ISSUE TITLE
Season of Chosen Conqueror Seal problem with strike records

### ISSUE THREAD

**Issue by dcaslin** [Bungie-net/api#1460]
The Season of chosen conqueror seal here: https://data.destinysets.com/i/PresentationNode:3776992251

Points to this Arms dealer strike: https://data.destinysets.com/i/PresentationNode:3776992251/Record:3176422761

I have a user that has completed that GM Nightfall this season, but that record shows as incomplete for him. https://www.bungie.net/Platform/Destiny2/1/Profile/4611686018435686415/?components=Profiles,Characters,CharacterProgressions,CharacterActivities,ProfileProgression,ItemObjectives,PresentationNodes,Records
```

                  "3176422761": {
                        "state": 20,
                        "objectives": [
                            {
                                "objectiveHash": 3464088010,
                                "progress": 0,
                                "completionValue": 1,
                                "complete": false,
                                "visible": true
                            }
                        ],
                        "intervalsRedeemedCount": 0
                    },

```
That said, he shows completion of the other Season of Chosen Arms dealer triumph: https://data.destinysets.com/i/Record:1404404279
```

                     "1404404279": {
                        "state": 67,
                        "objectives": [
                            {
                                "objectiveHash": 2851691012,
                                "progress": 2,
                                "completionValue": 1,
                                "complete": true,
                                "visible": true
                            }
                        ],
                        "intervalsRedeemedCount": 0
                    },


```

My guess is that either: 

1. The seal is pointing to the wrong triumphs, 3176422761 should be 1404404279, or 

2. 3176422761 isn't updating properly

I used Arms dealer as a specific value, but this seems to be true across all the GM Nightfalls.

**Comment by SolidKalium** [comment]
This doesn't look like a bug.

On the node for that record you can see that it has forTitleGilding: true. These triumphs for gilding a seal are only available after finishing the seal. So if this is your first season earning Conqueror, you need to do all 6 ordeals, and then to gild the seal you need to do all 6 again.

D2 Checklist links: [[Seals](https://www.d2checklist.com/1/4611686018435686415/triumphs/seals)] [[This season's strikes](https://www.d2checklist.com/1/4611686018435686415/triumphs/tree/636644708)]
This player still needs 1 unique ordeal and a stasis run to earn the seal. So they can choose to do either Warden of Nothing or Proving Grounds once if they want to complete both the seal and the gilding.

I'm in a similar boat and it's not very fun, but the data is being shown accurately.

**Comment by dcaslin** [comment]
Got it, so the user in question probably did the GM strike prior to acquiring the seal, then didn't do it again. Bonus points for using my own site to point out to me that the bug I'm reporting isn't a bug! Thanks!

**Comment by SolidKalium** [comment]
I didn't even notice it was your site! I mainly just like it and find it very helpful. I'm building a webpage to compare which seal triumphs different members of my clan have and I've used your site as a reference during that process.

I see that you've added an indicator for gilding, which is great! But as a nitpick: gild != guild.
