### ISSUE TITLE
Is it possible to change/equip subclasses?

### ISSUE THREAD

**Issue by jamesmenera** [Bungie-net/api#1461]
I would love to be able to change/equip light subclasses and trees and stasis fragments and aspects, etc through the api

**Comment by jshaffstall-bng** [comment]
The official D2 Companion apps can change Stasis subclass aspects and fragments, as those are just 'sockets' under the hood.

D2 Light subclasses use 'talents' (an older system from D1) and the API doesn't support changing talents.

But if and when we expand the 'socket' write action APIs, we could also consider allowing 'talent' write actions as well.

**Comment by jamesmenera** [comment]
With this being closed without any tags, should I not get my hopes up?

**Comment by jamesmenera** [comment]
Or did I file this issue wrong, I suppose this is future wishlist item
