### ISSUE TITLE
Is there anything in the static item definitions that can help denote what season an item is from?

### ISSUE THREAD

**Issue by ace51689** [Bungie-net/api#1464]
I've been trying to see if there's anything in an item's static definition (from the Manifest) that can help me pinpoint what season it's from. The closest I've gotten is using an item's index but that's not quite accurate as I've found some items from season of the hunt/Beyond Light (season 12) have lower indexes than things from season of arrivals (season 11). Is it a scenario where I need to figure out the range of indexes that belong to each season and use those ranges to filter my list? Or is there (hopefully) a much simpler way that I've missed?

**Comment by delphiactual** [comment]
iconOverlay

or 

https://github.com/DestinyItemManager/d2-additional-info/blob/master/data/seasons/seasons_unfiltered.json

**Comment by ace51689** [comment]
Thanks for the help! I really didn't even think of using the watermarks to sort by season.
