### ISSUE TITLE
TrialsOfOsiris Stats

### ISSUE THREAD

**Issue by nabsboss** [Bungie-net/api#1465]
Hi,

I building a pvp app but for Trials of Osiris i get somes issues.

I use this API request and it works fine:
https://www.bungie.net/Platform/Destiny2/2/Account/4611686018434393088/Character/2305843009263055439/Stats/?modes=84

But for some account, I get 0.0 for killsDeathsRatio because I have no data, like this one:
https://www.bungie.net/Platform/Destiny2/2/Account/4611686018429091154/Character/2305843009738834595/Stats/?modes=84

if check the AggregateActivityStats, i get all the Trials match but not the global KD:
https://www.bungie.net/Platform/Destiny2/2/Account/4611686018429091154/Character/2305843009738834595/Stats/AggregateActivityStats/?modes=84

If I check destiny trials Reports, we can see the KD and activities:
https://destinytrialsreport.com/report/2/4611686018429091154

How it is possible ? Anyone know how to get this stats on Trials like trials report do ? Or maybe it is a buf from the API for some accounts  !

Thanks for your help !

**Comment by delphiactual** [comment]
Dupe https://github.com/Bungie-net/api/issues/1380

**Comment by nabsboss** [comment]
Thanks ! So there is no update :(
Do u think it will be resolved soon ? 

So how Trials Report get these stats ?

**Comment by Helloimdisco1212** [comment]
there is any solution? i have same trouble
