### ISSUE TITLE
Season 14 Emblem Icons Are Incorrect

### ISSUE THREAD

**Issue by Jansten** [Bungie-net/api#1467]
It appears that all of the emblems added in today's API update (2021-05-11) have incorrect icons for emblems.  They appear to be streched horizontally instead of being a square.

Example emblem: 3953403250

**Comment by jshaffstall-bng** [comment]
Yep, this is being tracked with TFS 1001637.

**Comment by jshaffstall-bng** [comment]
This is now fixed with the latest content this morning.

https://data.destinysets.com/i/InventoryItem:3953403250

**Comment by Jansten** [comment]
Looks perfect, thank you so much! :D
