### ISSUE TITLE
"Past Challenges" PresentationNode lacking icon

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#1468]
Hi 👋

The "PastChallenges" PresentationNode 3759694843 has a white PNG for the icon in the definitions. In game it shows as 

![image](https://user-images.githubusercontent.com/46142/117982042-815a2180-b32d-11eb-9311-87a2824cc1d5.png)

**Comment by jshaffstall-bng** [comment]
This might be related to other icon issues we're having with recent emotes and white backgrounds. Filed as TFS 1002825.
