### ISSUE TITLE
Destiny.Components.Profiles.DestinyProfileTransitoryPartyMember no longer returns displayName

### ISSUE THREAD

**Issue by ash3825** [Bungie-net/api#1469]
https://bungie-net.github.io/multi/schema_Destiny-Components-Profiles-DestinyProfileTransitoryPartyMember.html#schema_Destiny-Components-Profiles-DestinyProfileTransitoryPartyMember

When looking up the Transitory component in the Destiny2.GetProfile endpoint, the partyMembers objects no longer returns the displayName attribute

```
"profileTransitoryData": {
            "data": {
                "partyMembers": [
                    {
                        "membershipId": "4611686018439055244",
                        "emblemHash": 2166136261,
                        "status": 3
                    },
                    {
                        "membershipId": "4611686018428807753",
                        "emblemHash": 2166136261,
                        "status": 11
                    }
                ],
```

**Comment by jshaffstall-bng** [comment]
Thanks for the heads up! Sounds like it could be related to Cross Play changes.

Filed as TFS 1002818, but I don't have an ETA for a fix.
