### ISSUE TITLE
How to filter out duplicate items in DestinyInventoryItemDefinition?

### ISSUE THREAD

**Issue by karmazogs** [Bungie-net/api#1470]
As I'm scrolling through a list of all the weapons in the game, I found no less than 6 copies of Jade Rabbit and 8 copies of Trust. There's gotta be a way of trimming these duplicates outside of doing it manually.

**Comment by delphiactual** [comment]
ItemCategoryHash: you don't need `Dummies` the game does though

**Comment by jshaffstall-bng** [comment]
As delphi mentioned, items like that are usually dummy placeholder items or some other kind of vestigial content.

Examples like that don't show up very often, but I don't have a good solution for you besides filtering out some duplicates manually.
