### ISSUE TITLE
DestinyCollectibleDefinition has some errors in documentation

### ISSUE THREAD

**Issue by EndGameGl** [Bungie-net/api#1471]
https://bungie-net.github.io/multi/schema_Destiny-Definitions-Collectibles-DestinyCollectibleDefinition.html#schema_Destiny-Definitions-Collectibles-DestinyCollectibleDefinition

Definition description states: "Defines a"
I guess there is more that just that so here you go.

**Comment by jshaffstall-bng** [comment]
Fill in the blank! :P

Filed as TFS 1002794.
