### ISSUE TITLE
I cant unlink my xbox account 

### ISSUE THREAD

**Issue by rustyxcat** [Bungie-net/api#1473]
I what to unlink my new xbox account and use my old one but the unlink but is grayed out and wont work I don't know how to fix it 
![Web capture_13-5-2021_14174_www bungie net ](https://user-images.githubusercontent.com/84149834/118168870-4ff95880-b3f6-11eb-8c0d-8348a39b6b89.jpeg)

**Comment by floatingatoll** [comment]
Your question is outside the scope of the Bungie API team that operates this GitHub (I am not Bungie). Bungie's Help site and forums are the best bet for getting a resolution: I encourage starting here:

https://help.bungie.net/hc/en-us/articles/360049498031-Contact-Form-Cross-Save-Issues
