### ISSUE TITLE
Shaders no longer appear in the assets database

### ISSUE THREAD

**Issue by TiredHobgoblin** [Bungie-net/api#1474]
Shader items no longer appear in the assets database, which means dye data for them can't be retrieved. Dye data for all other item types appears to still be accessible. This is causing issues in both the companion app and third-party applications, as gear with shaders applied retains its default appearance in the 3D viewer:

![](https://cdn.discordapp.com/attachments/592622294988357645/842502160084369408/Screenshot_20210513-154236_Destiny_2.jpg)

The mobile asset CDN now has `/common/destiny2_content/geometry/platform/mobile/shaders` added to it, which is presumably the new location for shader dye data, but there's nothing in any shader's item definition that can be used to access it.

**Comment by jshaffstall-bng** [comment]
Thanks for this report! Filed as TFS 1002789, but I don't have an ETA for a fix.

**Comment by Dcai169** [comment]
Any update on this?

**Comment by TiredHobgoblin** [comment]
Any ETA on this yet? I don’t mean to rush, but with Secret Servitor coming up I’d like to be able to let the 3D artists know in advance whether they’ll need to recreate shaders by hand.

**Comment by golfIII** [comment]
Hi, any ETA on this? My team would like to know, as their presence in the database is something we'd need for our project.

**Comment by jshaffstall-bng** [comment]
Hey we finally fixed this today. Sorry for the delay!
