### ISSUE TITLE
Metric for fresh raids

### ISSUE THREAD

**Issue by rentalhost** [Bungie-net/api#1476]
Hello, I would like to suggest a metric that can return the complete number of completed raids or activities that support save (like Prophecy).

We currently have the conclusion metrics. However, these metrics can only consider conclusions from the last step. If a player makes 10x the boss of an activity, it will be completed 10x.

In my case, and I believe that it would even help raid.report, I really need to know how many times the player has completed the activity in full, as this indicates the experience he has in a given activity.

It would be possible by analyzing the user's Carnage, but it is somewhat complex, especially if the user base is large. And it seems that there is a bug related to fresh, and I don't know if it has already been fixed. A metric would help that information a lot.

**Comment by ashakoor** [comment]
Take a look at #1320
