### ISSUE TITLE
Banshee Rolls updating more frequently than nextRefreshDates / overrideNextRefreshDate indicate

### ISSUE THREAD

**Issue by afpac** [Bungie-net/api#1477]
As the title says, Banshee's rolls are changing more frequently than the API seems to indicate they should.

The rolls Banshee is offering today (5/21) are different than those offered on 5/18. The weapons offered are unchanged - just the perks are different.

The result from the Vendors endpoint never indicated that a refresh would happen prior to the next weekly reset on 5/25. 

Not sure if this is an API issue or a game issue, but wanted to bring it up regardless. I want to be able to tell people when they can expect the rolls/weapons to disappear, and based on previous information in TWABs I've been saying things update weekly. Hopefully we can get some clarity on what the actual schedule is so as not to inadvertently mislead anyone.

https://twitter.com/lightdotgg/status/1395785690244423680 describes the whole scenario with screenshots etc.

**Comment by jshaffstall-bng** [comment]
Interesting, could these roll changes have been caused by a mid-reset game patch? Or are these weapon rolls changing consistently at the same time each week (not just at the weekly reset)?

I haven't been paying close attention to know for myself, so more details would be appreciated. Thanks!

**Comment by afpac** [comment]
Not sure as of yet. I modified my process that pulls the rolls down daily to compare to the previous day and call out when they're different. That should give more concrete timings on when the "reroll" is happening. I'll update once I know more

**Comment by jshaffstall-bng** [comment]
This video from Mesa Sean claims some of these rolls might change on Wednesdays?
https://www.youtube.com/watch?v=9pJnCf_mnl8

So let's check again tomorrow!

**Comment by afpac** [comment]
Appears to happen on the Thursday reset. https://twitter.com/lightdotgg/status/1397962025452675074

**Comment by afpac** [comment]
For what it's worth, people are reporting that the change happened in-game **yesterday**, but the API did not reflect new perks until today's reset.
