### ISSUE TITLE
Allow HTTP for localhost redirect urls

### ISSUE THREAD

**Issue by HazelTheWitch** [Bungie-net/api#1478]
Bungie currently does not allow HTTP for redirect urls for authorization. This severely limits non-web app applications by disallowing the use of HTTP with local urls. I'm personally trying to allow users to authenticate for a desktop application which will do armor stat optimizations, a task not suited for a browser considering people can have millions of combinations of armor and gear.

HTTP wouldn't need to be allowed in every situation as requested in #311, as I can see the hesitance there, but what security risk would allowing local connections to use HTTP pose? Any workarounds provided in that issue either directly goes against what Bungie encourages or is only suitable for developers and is not easily deployable.

**Comment by jshaffstall-bng** [comment]
Instead of using HTTP/HTTPS, you should be able to use a custom URI scheme that opens your desktop app after the user's browser completes the OAuth flow.
https://stackoverflow.com/questions/60545581/oauth-2-0-authorization-for-windows-desktop-application-using-httplistener
Would something like this work for you instead?

**Comment by HazelTheWitch** [comment]
That is an option, however it obviously requires the registration of the URI scheme and proper handling of it. This seems like a lot of overhead for something that small. This does work for me, since I was already planning on using a custom URI scheme, but it seems excessive for smaller projects.

**Comment by Wolftousen** [comment]
I got around this by setting up a static page in an AWS S3 bucket and CloudFront, was very simple to do (and as far as I can tell, this is free up to a certain point).  That static page then opens up an iframe to the localhost ip:port i'm listening on and i get the auth code that way so i can go get tokens.
