### ISSUE TITLE
Milestones - Vault of Glass not returning phases

### ISSUE THREAD

**Issue by fremgenc** [Bungie-net/api#1481]
VoG Milestone:
![image](https://user-images.githubusercontent.com/12090308/119548107-dfdac300-bd63-11eb-8fa6-59570d46bdad.png)

For comparison, here's the DSC Milestone:
![image](https://user-images.githubusercontent.com/12090308/119548177-f08b3900-bd63-11eb-8c75-4b2bd7d57570.png)

This is useful to track completion status by checkpoint for Raids. If there is some other way, please let me know!

**Comment by floatingatoll** [comment]
Is this related to #1320?

**Comment by jshaffstall-bng** [comment]
Nah, these phase completion configurations are separate from the 'startingPhaseIndex' issue.

Good catch! Filed as TFS 1005008.

**Comment by dcaslin** [comment]
I'm also seeing a weird behavior where the milestone seems to disappear for all chars on the account if one completes it.
