### ISSUE TITLE
PGCR contains two membership types

### ISSUE THREAD

**Issue by rentalhost** [Bungie-net/api#1484]
Hello!

I don't know if it is normal, but the [PGCR 8600963599](https://stats.bungie.net/Platform/Destiny2/Stats/PostGameCarnageReport/8600963599/) contains six players, five is `membershipType` 1 (that is correct), one of them is 3.

```
"membershipType": 1,
"membershipId": "4611686018448930551",
"displayName": "***"

"membershipType": 1,
"membershipId": "4611686018436381818",
"displayName": "***"

"membershipType": 1,
"membershipId": "4611686018453101617",
"displayName": "***"

"membershipType": 1,
"membershipId": "4611686018439354451",
"displayName": "***"

"membershipType": 3, <-- But actually have played on XBOX, not PC
"membershipId": "4611686018489647738",
"displayName": "***"

"membershipType": 1,
"membershipId": "4611686018491236802",
"displayName": "***"
```

**Comment by jshaffstall-bng** [comment]
Yes, this will be expected as we continue to test Cross Play features.

**Comment by rentalhost** [comment]
@jshaffstall-bng but it is an error? Because this activity was played only on XBOX (all players).

**Comment by jshaffstall-bng** [comment]
Could just be Cross Save in action as well, not certain.

Worth looking into, but I don't think it's an error.
