### ISSUE TITLE
PlugSet data conflict

### ISSUE THREAD

**Issue by kj415j45** [Bungie-net/api#1485]
In `4071704055 <PlugSet>` (`3164743584 <InventoryItem "Eye of Sol">.sockets.socketEntries[4].randomizedPlugSetHash`), perk `1546637391 <InventoryItem "Vorpal Weapon">` duplicated at `reusablePlugItems[0]` and `reusablePlugItems[7]`. And one of them has a property `currentlyCanRoll:false`, while another is `currentlyCanRoll:true`.
![](https://cdn.discordapp.com/attachments/532696111773909040/853580770069184522/unknown.png)

Reference: https://data.destinysets.com/i/InventoryItem:3164743584/PlugSet:4071704055

**Comment by jshaffstall-bng** [comment]
I believe this is a consequence of having two versions of the weapon. The first version and the new version both have vorpal weapon available, but old versions would have index 0, and new versions would have index 7.

**Comment by darkelement1987** [comment]
Same problem for astral horizon

https://data.destinysets.com/i/InventoryItem:1697682876/PlugSet:334979453

(Celerity: 1264398905)

**Comment by floatingatoll** [comment]
Astral Horizon has two versions as well, which puts it into the same bucket as the earlier reply.

**Comment by jshaffstall-bng** [comment]
Yeah with weapons that have multiple versions, it's OK for them to have two of the same perk in the same column.

**Comment by joaopmarquesini** [comment]
@jshaffstall-bng can we assume that higher indexes will always have the more recent info in these cases ?
