### ISSUE TITLE
trying to get post carnage report

### ISSUE THREAD

**Issue by fermraz** [Bungie-net/api#1486]
Hello!
 I'm new using the bungie API and I'm trying to get information from the postgamecarnagereport. I'm using this piece of code but it returns me an empty string.  According to the API documentation, an authorization is not needed to view the information. 
Is something else required?

  
                    $QUERYStats='https://www.bungie.net/Platform/Destiny2/Stats/PostGameCarnageReport/8504968165/';
                   $ch = curl_init();
                    curl_setopt($ch, CURLOPT_URL, $QUERYStats);
                    curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
                    curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);
                    curl_setopt($ch, CURLOPT_HTTPHEADER, array('X-API-Key: ' . $apiKey));
                 
                    var_dump(curl_exec($ch));
                    
                    curl_close($ch);

**Comment by ashakoor** [comment]
It's most likely returning a `301: Moved Permanently` as you should be using `https://stats.bungie.net/` as the base address for PGCRs.

**Comment by fermraz** [comment]
thanx!  it's working now!
