### ISSUE TITLE
Invalid PGCR Image link in DestinyActivityDefinition 3075674397

### ISSUE THREAD

**Issue by EndGameGl** [Bungie-net/api#1487]
Title
Link is:
https://www.bungie.net/img/destiny_content/pgcr/season_14_expunge_torrupted_tartarus.jpg
Should be :
https://www.bungie.net/img/destiny_content/pgcr/season_14_expunge_corrupted_tartarus.jpg
Second one actually exists.

While checking, also noticed that 1655431815 and 1774824719 share the same pgcr image, which is /img/destiny_content/pgcr/mission_bridge.jpg
It seems that it is also in the wrong place
1655431815 pgcr is: /img/destiny_content/pgcr/season_14_expunge_labyrinth.jpg
1774824719 pgcr is: /img/destiny_content/pgcr/season_14_expunge_corrupted_labyrinth.jpg

**Comment by jshaffstall-bng** [comment]
Oops, good catch!

**Comment by jshaffstall-bng** [comment]
These issues are filed as TFS 1010411 and should be fixed the next time we update Bnet game content, but I don't know when that'll be.

Thanks for this report!
