### ISSUE TITLE
Does Destiny2.GetVendor require OAuth?

### ISSUE THREAD

**Issue by zmtq05** [Bungie-net/api#1489]
Hi.

I apologize for my poor English. I got help from a translator.

I'm making a discord bot that notify list of Banshee's sales(without authentication).

First, I checked the response in [Destiny Data Explorer](https://data.destinysets.com/api/Destiny2.GetVendor?characterId=2305843009460104810&destinyMembershipId=4611686018484776953&membershipType=3&components=402&vendorHash=672118013).
Then, I requested same url with X-API-Key in Postman. But I received error.(status 500)
```json
{
    "ErrorCode": 12,
    "ThrottleSeconds": 0,
    "ErrorStatus": "InsufficientPrivileges",
    "Message": "You lack the privileges to read or write this data.",
    "MessageData": {}
}
```
---
- Is it impossible to get data without OAuth?
- Can I get a response in any other way?

Thank you.

**Comment by soren42** [comment]
Unfortunately, that endpoint does require OAuth, as what's available at certain vendors changes depending on user progress.

**Comment by zmtq05** [comment]
Thank you soren42.
