### ISSUE TITLE
How to pull weapon name ect from PGCR

### ISSUE THREAD

**Issue by makozort** [Bungie-net/api#1492]
i have no idea how to get a specific weapons name from "referenceId"

**Comment by dcaslin** [comment]
Consider this random PGCR: https://www.bungie.net/Platform/Destiny2/Stats/PostGameCarnageReport/8777409209

with this snippet for one of the entries: 

```
{
                            "referenceId": 599895591,
                            "values": {
                                "uniqueWeaponKills": {
                                    "basic": {
                                        "value": 13.0,
                                        "displayValue": "13"
                                    }
                                },
```

That reference id `599895591` is in the `DestinyInventoryItemDefinition` section of the Manifest. You can get a handy look at that here: 

https://data.destinysets.com/i/InventoryItem:599895591

Now acquiring a copy of the Manifest DB (either in JSON or SQLite form) is a complicated topic that I've skipped over here, but once you have it, that's what you'd do with it.

**Comment by makozort** [comment]
Cheers! I’ll look into grabbing that manifest, your a legend mate

**Comment by makozort** [comment]
thanks so much! ill have to look into this manifest DB thing, you've helped a young/confused dev move forward.
thanks - makozort
P.S where would I learn about acquire a copy of the manifest?

**Comment by makozort** [comment]
closing cause i figured it out
