### ISSUE TITLE
Master Vault of Glass completions don't count towards milestone in API

### ISSUE THREAD

**Issue by dcaslin** [Bungie-net/api#1497]
Until next reset consider this user: 

https://www.bungie.net/Platform/Destiny2/3/Profile/4611686018482896020/?components=Profiles,Characters,CharacterProgressions,CharacterActivities,ProfileProgression

PGCR 8827018640 shows a master completion on their titan, character ID 2305843009472554381. Yet their profile shows the weekly completion objective as incomplete: 

`"2279677721": {
                            "milestoneHash": 2279677721,
                            "activities": [
                                {
                                    "activityHash": 3881495763,
                                    "challenges": [
                                        {
                                            "objective": {
                                                "objectiveHash": 3214312537,
                                                "activityHash": 3881495763,
                                                "progress": 0,
                                                "completionValue": 1,
                                                "complete": false,
                                                "visible": true
                                            }
                                        }
                                    ],`

**Comment by lieuweberg** [comment]
I'd like to bump this!
