### ISSUE TITLE
Special Grenade objective icon hints are still a unicode character and not a [weapon] style hint

### ISSUE THREAD

**Issue by NigelHietala** [Bungie-net/api#1498]
https://data.destinysets.com/i/InventoryItem:820034616/Objective:3282218650

Here the special grenade launcher objective is represented as unicode character \uE155 

Could it be something like [Special Grenade Launcher]?

**Comment by delphiactual** [comment]
#1174

**Comment by jshaffstall-bng** [comment]
Thanks for this report. We'll have a fix as '[Special Grenade Launcher]' the next time we update D2 content on Bnet, which may be as late as 9/16, but could be sooner.
