### ISSUE TITLE
OAuth2 Scope Enums Missing

### ISSUE THREAD

**Issue by lowlines** [Bungie-net/api#15]
As the title states. Also might be handy to have a link to the [Official Help Article](https://www.bungie.net/en/Groups/Post?groupId=39966&postId=227773391&sort=0&page=0&path=0&showBanned=0) (which probably needs to be pulled out of the BNet Group)

**Comment by vthornheart-bng** [comment]
Ah, good call!  Though you may want to get that info from:

#/securitySchemes/oauth2/flows/authorizationCode/scopes

But I'll add the enum equivalent as well to the #/components/schema.

I'm also going to add the help article - I just put it into a wiki page over here, so I'll have it point there.
