### ISSUE TITLE
Question: Is it possible to get higher-res activity or item icons

### ISSUE THREAD

**Issue by benedfit** [Bungie-net/api#150]
Any plans to make available larger versions of activity or item icons? Or even provide then in a vector such as SVG? I redrew the ones for D1 to get that extra smooth hidpi display lovelyness. But I feel like that leans into copyright infringement territory some what, it would be great to get them from the source (I'm aware that you now use an icon font in some places that contains some of the icons, but knowing the problems that they bring, and that hot-linking from Bungie.net isn't a crest idea)

**Comment by vthornheart-bng** [comment]
I am unsure - this is something I need to find the time to look into.  Currently I'm grabbing the highest res icons I can find in our content, but there may be alternatives.  I unfortunately don't know how feasible it will be to return, but when I get time I will investigate!

**Comment by floatingatoll** [comment]
@vthornheart-bng this may dupe #33 ?

**Comment by benedfit** [comment]
It is indeed. Closing
