### ISSUE TITLE
Destiny Tracker Matches in Trials of Osiris / ELO not tracking as of July 16th 2021

### ISSUE THREAD

**Issue by lol29011** [Bungie-net/api#1500]
Hey there noticed all my matches after July 16th 2021 12:44pm have not been tracked. My elo has only been negatively affected and all the matches prior have not been accounted for. Just wondering you are aware of the problem. Also when fixed would they be updated accordingly?? thanks in advance.

https://destinytracker.com/destiny-2/pgcr/8842969336

Here is the last match that was recorded.

**Comment by bladefist** [comment]
@lol29011 this is the bungie api, destiny tracker is a 3rd party api.  I'm the owner of it, can you reach out to me on twitter?  
https://twitter.com/htr_xorth

I'll look into your situation.  thanks.
