### ISSUE TITLE
Stasis armor is missing the 'energy' dictionary in the itemComponent

### ISSUE THREAD

**Issue by NigelHietala** [Bungie-net/api#1503]
It isn't possible to know armor has the stasis energyType and how much it has been upgraded as the itemComponent json is missing the 'energy' dictionary. I attached an example json. I can see the official app also shows zero values and no energyType.

[stasis.json.zip](https://github.com/Bungie-net/api/files/7045692/stasis.json.zip)

**Comment by jshaffstall-bng** [comment]
Oops good catch

**Comment by jshaffstall-bng** [comment]
This should be fixed now as of this morning's deployment.
