### ISSUE TITLE
`Destiny2.SearchDestinyPlayer` always returns an empty array.

### ISSUE THREAD

**Issue by nxtlo** [Bungie-net/api#1505]
Hello. Not really sure if this issue has been mentioned yet or no but. it looks like the `Destiny2.SearchDestinyPlayer` endpoint returns an empty array. I tried making multiple requests with different user names. but is still returns an empty array.

An http response example

```http
GET https://www.bungie.net/Platform/Destiny2/SearchDestinyPlayer/3/Fate#1111

HTTP/1.1 200 OK
Access-Control-Allow-Origin: https://www.bungie.net
Content-Type: application/json; charset=utf-8

{
    "ErrorCode": 1,
    "ErrorStatus": "Success",
    "Message": "Ok",
    "MessageData": {},
    "Response": [],
    "ThrottleSeconds": 0
}
```

**Comment by Achronos-BNG** [comment]
I don't recall off the top of my head, but you not including the www will likely cause undefined effects especially for authenticated requests.  Please include the full domain.
