### ISSUE TITLE
Private APIs usage

### ISSUE THREAD

**Issue by Zekfad** [Bungie-net/api#1509]
Suppose I found API endpoint which is not documented in this docs, am I allowed to use it?
Please clarify it on that help page: [Destiny Account Restrictions and Banning Policies](https://help.bungie.net/hc/en-us/articles/360049517431-Destiny-Account-Restrictions-and-Banning-Policies).
Currently it only says:

> Accessing the publicly-facing Bungie.net and Companion web APIs in a manner that does not create an unreasonable load on these services.

Also Terms of Use says:

>Your application must not attempt to sign in to Bungie.net using HTTP authentication cookies. This includes reverse engineering the sign-in flow used by Bungie.net or the companion apps or by using authentication cookies extracted from a user’s session.

> You may not otherwise reproduce, modify, distribute, decompile, disassemble or reverse engineer any portion of the Bungie.net API or API Data.

But I'd like to clarify if I'm allowed to use the undocumented APIs?
Also what does it mean to "reverse engineer Bungie.net API or API Data"? Does it mean pen-testing the API server?

**Comment by jshaffstall-bng** [comment]
/user/search/prefix/ is now documented and public. /DismantleItem/ doesn't work for any clients so avert thine eyes.
