### ISSUE TITLE
tess's sales are wrong again 

### ISSUE THREAD

**Issue by nev-r** [Bungie-net/api#1513]
looks like a recurrence of #1421 . she's selling the same item (3951356827) for 2 different prices, selling the wrong shaders, etc. weirdly it was all correct on tuesday. some time between then and now, it changed.
![image](https://user-images.githubusercontent.com/68782081/131229642-5fb5f7eb-c089-49ac-8bb0-e7b6c2db971d.png)

**Comment by jshaffstall-bng** [comment]
Thanks for the heads up, we might be slightly out of sync with eververse content.

**Comment by jshaffstall-bng** [comment]
This should be fixed now with new content.
