### ISSUE TITLE
bungieGlobalDisplayNameCode is not zero-padded

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#1514]
For users who have a `bungieGlobalDisplayNameCode` of only three digits (like me!), the API returns their `bungieGlobalDisplayNameCode` as an int, without the leading 0 to pad it out to a four digit.... string as displayed in game.

This is problematic because the player search in game _requires_ that leading 0 (which is different behaviour from the from the `SearchDestinyPlayer` endpoint which will happily accept `joshhunt#664`) to return results.

I guess there is kind of two or three related issues here (where solving one would mitigate the others):
 - The API does not return the Bungie Name in the same format as displayed in game, dropping the leading 0.
     - IMHO I think it would be preferred if instead of returning the code, the API just returned the "fully qualified bungie name" as its own field - `"joshhunt#0664"` - as displayed in the game
  - The in-game player search does not work without the leading zero for names with a three digit code
  - The API search behaviour differs from the in-game behaviour.

**Comment by jshaffstall-bng** [comment]
@Achronos-BNG should comment here as well, but Bnet API clients should display the Bungie Names with 4-digit codes and leading zeroes.

And we can consider adding new properties for `bungieGlobalDisplayNameWithCode` as you described for convenience.

**Comment by joshhunt** [comment]
I think that if the code is not (semantically) an int, and we should _always_ treat it as a string when using it by zero-padding it, then it should be returned by the API as a string with the leading zeros.

**Comment by rentalhost** [comment]
Another option is that the game itself allows you to locate players with three digits. Currently zero is mandatory.

**Comment by Achronos-BNG** [comment]
The intended behavior is that the code portion just has to convert to a int16 - the leading zero shouldn't matter.  When printing it out in string form, the leading zero is always added.  So, any place where you're typing a code in (like search) should work both with and without a leading zero, and if it doesn't work like that, it should be considered a bug.

**Comment by rentalhost** [comment]
@Achronos-BNG 

Still not works with 3 digits:

![image](https://user-images.githubusercontent.com/421851/132788058-50985b6b-d827-4b4e-abd2-11c591896f9b.png)

> "Bungie nicknames require the player's name, the hash symbol (#) and a 4-digit numeric suffix (1234)"

But works with 4 digits:

![image](https://user-images.githubusercontent.com/421851/132788214-05c2d821-0499-4a25-a45e-73742fc7e31f.png)

The API itself works with 3 or 4 digits.

**Comment by Achronos-BNG** [comment]
I can't really speak to the game's UI requiring it, just the API.  The game is probably just applying a client validator that is a little too strict.  However, it is true that you should always include in the leading zero when showing a string version of the code, which generally will ensure that your users include it when they use the search box in the game.

**Comment by justrealmilk** [comment]
> I think that if the code is not (semantically) an int, and we should _always_ treat it as a string when using it by zero-padding it, then it should be returned by the API as a string with the leading zeros.

I agree with this sentiment. Unsure of the status 🫠
