### ISSUE TITLE
Ghosts Shells think they are Sparrows

### ISSUE THREAD

**Issue by JpDeathBlade** [Bungie-net/api#1515]
For the last two weeks some Ghost Shells have been returning with 160 "Speed".

![ghost1](https://user-images.githubusercontent.com/1441829/131552358-49d58331-2882-43e2-bb0a-1befc9de22ea.PNG)
![speed](https://user-images.githubusercontent.com/1441829/131552371-02940c70-9521-48ca-80e3-b75d092d2773.PNG)

**Comment by nev-r** [comment]
if it's just the ones at tess it's probably https://github.com/Bungie-net/api/issues/1513#issuecomment-907682646

:crossed_fingers: soon

**Comment by jshaffstall-bng** [comment]
Yep, this should be fixed now with new content.
