### ISSUE TITLE
SearchDestinyPlayer (and User Search Prefix) not returning all platforms for specific player

### ISSUE THREAD

**Issue by ChaseMalik** [Bungie-net/api#1517]
There is a player with Bungie name `[BS] Fei#5889` that has an unused playstation account (4611686018449535891) and a pc account (4611686018467381147)

I believe cross save is **not** enabled.

When searching using, SearchDestinyPlayer - https://www.bungie.net/Platform/Destiny2/SearchDestinyPlayer/-1/%5BBS%5D%20Fei%235889/
Only a single result is found (the unused playstation account)
![image](https://user-images.githubusercontent.com/8572974/131934936-aa6d7972-da09-4c23-9547-e59f8a534704.png)

Similarly, searching using the Search Prefix endpoint - https://www.bungie.net/Platform/User/Search/Prefix/%5BBS%5D%20Fei/0/ - A single result, with a single destinyMembership is returned (once again, the playstation account)
![image](https://user-images.githubusercontent.com/8572974/131934962-7b918a36-0570-4075-9330-ec2491765ac8.png)

The only way to find the PC account is to search by steam id - 
https://www.bungie.net/Platform/User/GetMembershipFromHardLinkedCredential/12/76561197960518505/

Edit: It looks like `Dare#9848` might have a similar issue.

**Comment by Achronos-BNG** [comment]
This looks like it is an odd interaction with a linked account being marked as "private".  Unfortunately, the fix for this is more complex than it would first appear.  Good news is that we're already working a fix for a related problem in the friends code that will be able to help with this problem too.

**Comment by rentalhost** [comment]
It also is happending with the player `Z o o m e r a n g#4385`.

The Playstation account is returned, but no Steam account. The ironic part is that his Bungie ID was generated from the Steam Name (`Z o o m e r a n g`), and that's exactly what not finding through the API.

It is possible to find the Steam `membershipId` by searching the member's current clan. However, the clan needs to be known. So I look for the member on [Bungie.net](https://bungie.net), see which clan he's a part of, use the `GroupV2/<groupId>/Members` API, and find his `membershipId`. If he's not in a clan, he needs to join.

![image](https://user-images.githubusercontent.com/421851/132962847-f25aab81-75a8-4d42-9319-f42e49bd482e.png)
