### ISSUE TITLE
SearchDestinyPlayer returns overridden memberships

### ISSUE THREAD

**Issue by ChaseMalik** [Bungie-net/api#1518]
According to the new docs, SearchDestinyPlayer "will hide overridden memberships due to cross save."

But this is not the actual behavior. Overridden memberships are currently returned.

Example with Datto:
https://www.bungie.net/Platform/Destiny2/SearchDestinyPlayer/-1/datto%236446/

![image](https://user-images.githubusercontent.com/8572974/131935227-30fb9201-354b-48e4-9794-91df631a102c.png)

**Comment by Achronos-BNG** [comment]
I'll get a bug filed on this, thanks.
