### ISSUE TITLE
Astral Alignment Activities Returned with Stats/Activities Call Return Negative/non-numeric PlayerCount Values

### ISSUE THREAD

**Issue by dreadmute** [Bungie-net/api#1519]
Some Astral Alignment activities seem to return bad data.
I have built a clan activity tracking bot and was getting errors when attempting to parse in playercounts from these bugged activities.
This is also reflected on Bungie.net through the activities:
- Examples of bugged instances: [9032102640](https://www.bungie.net/en/PGCR/9032102640) [9031230832 _Output Below_](https://www.bungie.net/en/PGCR/9031230832)
- Example of intended instance: [9098597148](https://www.bungie.net/en/PGCR/9098597148)

Data returned by the bugged instances has the following:
```
{'directorActivityHash': 2178562902,
 'instanceId': '9031230832',
 'isPrivate': False,
 'membershipType': 3,
 'mode': 2,
 'modes': [7, 2],
 'referenceId': 2178562902}
{'activityDurationSeconds': {'basic': {'displayValue': '5h 54m',
                                       'value': 21289.0},
                             'statId': 'activityDurationSeconds'},
 'assists': {'basic': {'displayValue': '2', 'value': 2.0}, 'statId': 'assists'},
 'averageScorePerKill': {'basic': {'displayValue': '0.00', 'value': 0.0},
                         'statId': 'averageScorePerKill'},
 'averageScorePerLife': {'basic': {'displayValue': '0.00', 'value': 0.0},
                         'statId': 'averageScorePerLife'},
 'completed': {'basic': {'displayValue': 'No', 'value': 0.0},
               'statId': 'completed'},
 'completionReason': {'basic': {'displayValue': 'Unknown', 'value': 255.0},
                      'statId': 'completionReason'},
 'deaths': {'basic': {'displayValue': '0', 'value': 0.0}, 'statId': 'deaths'},
 'efficiency': {'basic': {'displayValue': '30.00', 'value': 30.0},
                'statId': 'efficiency'},
 'fireteamId': {'basic': {'displayValue': '-2147483648',
                          'value': 1.3098910161374797e+18},
                'statId': 'fireteamId'},
 'kills': {'basic': {'displayValue': '28', 'value': 28.0}, 'statId': 'kills'},
 'killsDeathsAssists': {'basic': {'displayValue': '29.00', 'value': 29.0},
                        'statId': 'killsDeathsAssists'},
 'killsDeathsRatio': {'basic': {'displayValue': '28.00', 'value': 28.0},
                      'statId': 'killsDeathsRatio'},
 'opponentsDefeated': {'basic': {'displayValue': '30', 'value': 30.0},
                       'statId': 'opponentsDefeated'},
 'playerCount': {'basic': {'displayValue': '-7', 'value': -7.0},
                 'statId': 'playerCount'},
 'score': {'basic': {'displayValue': '0', 'value': 0.0}, 'statId': 'score'},
 'startSeconds': {'basic': {'displayValue': '2h 36m', 'value': 9361.0},
                  'statId': 'startSeconds'},
 'team': {'basic': {'displayValue': '', 'value': 0.0}, 'statId': 'team'},
 'teamScore': {'basic': {'displayValue': '0', 'value': 0.0},
               'statId': 'teamScore'},
 'timePlayedSeconds': {'basic': {'displayValue': '3m 37s', 'value': 217.0},
                       'statId': 'timePlayedSeconds'}}
```

I'm currently bypassing processing of these activities by doing a check on numeric values passed in the playerCount value and skipping those that aren't numeric.

Apologies if this isn't the proper format/ doesn't include all necessary information.

**Comment by justrealmilk** [comment]
Why are you using playerCount (from a player entry) rather than just grabbing the length of entries for player count?

**Comment by dreadmute** [comment]
> Why are you using playerCount (from a player entry) rather than just grabbing the length of entries for player count?

It's an attempt to filter out activities that I don't care about, since I'm only looking for player entries that have at least two players.
What length of entries are you referring to?

**Comment by justrealmilk** [comment]
> > Why are you using playerCount (from a player entry) rather than just grabbing the length of entries for player count?
> 
> It's an attempt to filter out activities that I don't care about, since I'm only looking for player entries that have at least two players.
> What length of entries are you referring to?

Well, entries is an array with a length, each entry a player

**Comment by dreadmute** [comment]
> > > Why are you using playerCount (from a player entry) rather than just grabbing the length of entries for player count?
> > 
> > 
> > It's an attempt to filter out activities that I don't care about, since I'm only looking for player entries that have at least two players.
> > What length of entries are you referring to?
> 
> Well, entries is an array with a length, each entry a player

I'm not really sure what you're referring to still. 
Process is as follows for my particular use case:

1. Find every member of a given clan
2. Find all character IDs associated with them
3. Find all activities each character participated in during a given time frame
4. Determine which of those were done with other members of the clan

Even if there was an array of player entries in another query or this one, I've already running it tight as far as efficiency. Having the number of players in a call I'm already using for my model is easier/more efficient than determining the length on a retrieved array.

**Comment by dreadmute** [comment]
I'm all for improving my process/logic for my project, but from what I can tell there is something in how these activities are being generated from the game that is incorrect. Based on my testing when building this and verifying activity data, this field used to be accurate and should always be >0. However I'm finding entries that are <0 which also doesn't align with what I assume the intent of the field is.

**Comment by jshaffstall-bng** [comment]
Yeah thanks for the report here. That field shouldn't have a bad value, but it sounds like we have a workaround until this is fixed.
