### ISSUE TITLE
tooltipNotificationIndexes on live itemComponents seems to be bugged

### ISSUE THREAD

**Issue by NigelBreslaw** [Bungie-net/api#1520]
This year a bunch of seasonal items are using tooltipNotificationIndexes. For example this seasons 'Shifting of the ley lines' quest. Or last seasons Splicer Gauntlet (itemHash: 264891313). All the possible toolTipNotifications are in the itemDefinition.

However the live itemComponents just repeat every possible index. So the splicer gauntlet has 15 possible options. The live item say show them all! 0-14. I attached the live data. As far as I can tell whatever the total tooltips an item has, the live data will always match that. But like it should only be one or two of the items, not all of them. Be awesome if this worked as the extra info is really useful. 

[liveItem.json.zip](https://github.com/Bungie-net/api/files/7110578/liveItem.json.zip)

**Comment by jshaffstall-bng** [comment]
Interesting. It's possible that this is a consequence of unlock flags, values, or expressions being redacted for the various weekly quest steps.

We can take a closer look on Tuesday. Thanks for the report!
