### ISSUE TITLE
Inconsistent seal icons for seal records

### ISSUE THREAD

**Issue by t3rr11** [Bungie-net/api#1521]
So someone raised an issue to me today where a seal was not showing an image associated with the seal record and digging deeper and found that's it's quite inconsistent whether seal records have images at all, have seal images or have other images.

For example;
The Last wish [record hash (1384029371)](https://data.destinysets.com/i/PresentationNode:616318467/PresentationNode:1486062207/Record:1384029371) shows a raid seal image under `displayProperties.icon`
The Deep stone crypt [record hash (540377256)](https://data.destinysets.com/i/PresentationNode:616318467/PresentationNode:2960810718/Record:540377256) shows an image under `displayProperties.icon` but it's not the raid seal image
The Garden of salvation [record hash (2909250963)](https://data.destinysets.com/i/PresentationNode:616318467/PresentationNode:1827854727/Record:2909250963) has no image, name or description under `displayProperties`

Lets look at more recent titles;
The Realmwalker [record hash (2991743002)](https://data.destinysets.com/i/PresentationNode:616318467/PresentationNode:1321008456/Record:2991743002) has no image, but does have a description and name under `displayProperties`
Whilst the Deadeye [record hash (1438167672)](https://data.destinysets.com/i/PresentationNode:616318467/PresentationNode:361765966/Record:1438167672) seal does have a seal icon?

Both seals came out in the same season, one has a seal icon and one does not. What's going on? Also possible fix please <3

**Comment by justrealmilk** [comment]
Seal completion records are never displayed in game like other triumphs are so I guess there's never been a reason to make em look cute

**Comment by t3rr11** [comment]
But... I want them to look cute. If there was a parentNodeHash in the `parentNodeHashes` object then I'd just use that parents icon but sadly there is no way to get the parent without getting the parents parent hash and look at the children and matching the records to find the parent presentation hash for that record so that I can use that image instead, which honestly sounds like such a pain to do, even then now seals are split into 2 different sections legacy seals and seals, so i'd need to get both progression hashes, concat them together and then search for the record within those children presentation nodes.

Even saying all that had my head spinning. Please make the records look cute.
