### ISSUE TITLE
SearchDestinyPlayer returns an empy response

### ISSUE THREAD

**Issue by jpoff22** [Bungie-net/api#1524]
I am following along the tutorial for the introduction to the API here: https://github.com/vpzed/Destiny2-API-Info/wiki/API-Introduction-Part-1-Setup and when I use the request they have: "https://www.bungie.net/Platform/Destiny2/SearchDestinyPlayer/-1/dattowatto/" I am getting an empty response, but it returns as a success. Is there a new way this is done or what am I doing wrong?
![image](https://user-images.githubusercontent.com/58572285/132894666-00a96824-eb45-46b8-a179-72b19d949493.png)

**Comment by delphiactual** [comment]
Search has changed recently use https://www.bungie.net/Platform/User/Search/Prefix/{username} for all your searching needs

**Comment by jpoff22** [comment]
> Search has changed recently use [https://www.bungie.net/Platform/User/Search/Prefix/{username}](https://www.bungie.net/Platform/User/Search/Prefix/%7Busername%7D) for all your searching needs

Thanks!
