### ISSUE TITLE
Impossible to search for players that have not played in Season 15

### ISSUE THREAD

**Issue by ChaseMalik** [Bungie-net/api#1529]
With the breaking change (https://github.com/Bungie-net/api/issues/1506#issuecomment-906608103) of removing platform search functionality from the SearchDestinyPlayer endpoint it is only possible to search for players that have a BungieGlobalDisplayName - which is not `"all players"` as stated in that comment, but only those that have played in Season 15.

**Comment by floatingatoll** [comment]
How does the breaking change described interfere with your app? Or, phrased differently, why does your app need to find Destiny players who haven't logged in for a few weeks?
