### ISSUE TITLE
BnetWrite: required to Social API

### ISSUE THREAD

**Issue by rentalhost** [Bungie-net/api#1532]
Hello!

I have a LFG bot for Telegram called **Nessus**, and it is used for some brazilian clans, inclusive my own clan. I am developing a new feature that allows the activity leader to add all players that subscribed to this activity in a single click. So he does not needs add one-by-one, mainly because some names are very difficulty to input on console for instance (eg. `Λndy†#1234`).

![image](https://user-images.githubusercontent.com/421851/133956466-5bae857e-025a-47bf-8fe5-cac87210258a.png)

So it basically will shows a button like "request friendship" and will move to this page:

![image](https://user-images.githubusercontent.com/421851/133956449-b039ebc7-24b0-43f6-acdb-75ac86716bed.png)

The problem is that I reached to the point to implements the "issue friend" and discovered that it requires a permission not available to 3rd applications called BnetWrite.

Is there anything I can do about it? While I am aware that this feature can be abused, at least issuing and accepting friendship requests would be a viable option. At least in a small amount, especially since the user needs to approve the application's access to their account first.

**Comment by RandMBNG** [comment]
Hiya!  Indeed at this time write permissions on the friends APIs are restricted for use and not currently available to 3rd party applications for a variety of reasons.  That said, we can review the ask with our social teams and discuss options for a future update.
