### ISSUE TITLE
Missing currentActivityModeHash for Astral Alignment

### ISSUE THREAD

**Issue by lieuweberg** [Bungie-net/api#1534]
Hello from #910 

As I was told in the Destiny API Discussion discord server I should create a new issue for every occurrence of a missing ActivityModeType in CurrentActivity, here is the first of such a streak.

Astral Alignment has a currentActivityModeHash of 2166136261 instead of the normally used Story.

**Comment by justrealmilk** [comment]
you should use activityTypeHash (263019149 // <ActivityType "Seasonal Arena">)

**Comment by t3rr11** [comment]
Hello from #910 also! Jeez that was a long time ago...
