### ISSUE TITLE
PGCR Scraping Help

### ISSUE THREAD

**Issue by sledsworth** [Bungie-net/api#1539]
Hello 👋

I'm working on creating a feature to show the current weapon meta, which requires scraping the `/Platform/Destiny2/Stats/PostGameCarnageReport/${id}/` endpoint, at least from my understanding (if there is a better way, or another endpoint to get multiple activities at once, I'm all ears).

The issue I'm running into is that more activities are played a second than the rate limit allows for (only 25 requests can be made a second). 

I could just grab ever 4th game or so and be able to keep up–I imagine the law of large numbers would be on my side and the subset average would be fairly close to the actual average. I'd much rather have the complete set of data if possible, but this could work if no one has a better idea.

Does anyone know what other websites like Destiny Tracker are doing to scrape all the PGCR data?

Thanks in advance!

**Comment by joshhunt** [comment]
Completely unrelated, but it's really cool how Digital Ocean gives you 16 IPv6 addresses! https://docs.digitalocean.com/products/networking/ipv6/ 🙂
