### ISSUE TITLE
DestinyEquipmentSlotDefinition missing entity markup in spec

### ISSUE THREAD

**Issue by vthornheart-bng** [Bungie-net/api#154]
DestinyEquipmentSlotDefinition is a first-order Entity in the Destiny Manifest definitions, but it's not marked up as such.  I should give a pass through other definition contracts as well and make sure they have the appropriate markup to indicate that they're definition entities.

**Comment by vthornheart-bng** [comment]
Sounds like the missing metadata may also be causing it to not be returned in SQLite.

**Comment by afpac** [comment]
Definitely missing from the SQLite database as of 9/30:

![image](https://user-images.githubusercontent.com/32434371/31055496-b04db6c0-a691-11e7-8fbc-be83d783f500.png)

Thought I was losing my mind :)

**Comment by vthornheart-bng** [comment]
Ah!  Yes, I still haven't had a chance to loop back around to this.  But I see it and am assigning it to myself so it will end up getting done!
