### ISSUE TITLE
Manifest Outdated

### ISSUE THREAD

**Issue by TheLLaw** [Bungie-net/api#1541]
So I was trying to pull data, more specifically the DestinyInventoryItemDefenition from the sqlite3 database when I figured out most data I tried to access returned a KeyError (using python) but weapons such as Ace of Spades didn't. Please inform me on what is going on and if I'm doing something wrong. 
![image](https://user-images.githubusercontent.com/81530706/136651762-896587e0-47b7-476f-b11f-341d2da7b0c4.png)

Btw I'm using the build_dicts function from the documentation for testing.

obj["itemHash"] returns a normal item hash

**Comment by joshhunt** [comment]
There's extremely little context here to understand what's happening - all you show is retrieving a value from the dictionary which looks fine I guess 😅 

My guess is however you're not converting the `key` column from the SQLite database. See [Converting hashes for the SQLite DB](https://github.com/vpzed/Destiny2-API-Info/wiki/API-Introduction-Part-3-Manifest#converting-hashes-for-the-sqlite-db)

> In the API, hashes (like item hashes) are can be represented as an "unsigned 32 int". However, in the SQLiteDB, these hashes are represented as a "signed 32 int". The unsigned 32 int overflows what can be stored in SQLite's signed 32 int, so the majority of items in the DB will have negative ids. For example, the item "Vigil of Heroes" with item hash 2592351697 has an ID value of -1702615599 in the definitions SQLite database.

**Comment by TheLLaw** [comment]
Sorry I forgot to close the issue. I was requesting data from Destiny not Destiny2. Literally 1 character lol.

Anyways thank you for your help.
