### ISSUE TITLE
SearchDestinyPlayer: broken if Bungie ID contains slash ("/")

### ISSUE THREAD

**Issue by rentalhost** [Bungie-net/api#1543]
Some **Bungie IDs** contains slash for players that have set the Steam with the Twitch. For instance, the following player will buggy:

> JellyFish - twitch.tv/doch#8495

The SearchDestinyPlayer cannot found this player, even if the slash is URL encoded. For instance:

> https://www.bungie.net/Platform/Destiny2/SearchDestinyPlayer/All/JellyFish%20-%20twitch.tv%2Fdoch%238495

But the player actually exists, if you list the group members where this play is joined:

> https://raid.report/pc/4611686018492731528

![image](https://user-images.githubusercontent.com/421851/137219807-224fc1cb-8c00-4eab-b7e0-25b5c8c47ac1.png)

**Comment by delphiactual** [comment]
#1528

**Comment by floatingatoll** [comment]
As best as I can remember from likely-duplicate #1528, users with certain special characters in their names will only be able to look themselves up by OAuth, and will be difficult/impossible for others to look up by name at all, and that this is an inflexible restriction from Bungie at this time.

**Comment by rentalhost** [comment]
@delphiactual Very similar, but in this case it returns a 404 error, as the API controller can't even be triggered, as it confuses the "slash" with a URL slash, in fact. But I will comment this directly on this topic. Thanks!
