### ISSUE TITLE
Missing mappings in Destiny2CoreSettings

### ISSUE THREAD

**Issue by EndGameGl** [Bungie-net/api#1558]
https://bungie-net.github.io/multi/schema_Common-Models-Destiny2CoreSettings.html#schema_Common-Models-Destiny2CoreSettings

Only seasonalChallengesPresentationNodeHash has mapped definition type, would be nice to have those for other hashes

**Comment by justrealmilk** [comment]
Such as which?

**Comment by EndGameGl** [comment]
Lets see:
- collectionRootNode is DestinyPresentationNodeDefinition
- badgesRootNode is DestinyPresentationNodeDefinition
- recordsRootNode is DestinyPresentationNodeDefinition
- medalsRootNode is DestinyPresentationNodeDefinition
- metricsRootNode is DestinyPresentationNodeDefinition
- activeTriumphsRootNodeHash is DestinyPresentationNodeDefinition
- activeSealsRootNodeHash is DestinyPresentationNodeDefinition
- legacyTriumphsRootNodeHash is DestinyPresentationNodeDefinition
- legacySealsRootNodeHash is DestinyPresentationNodeDefinition
- medalsRootNodeHash is DestinyPresentationNodeDefinition
- exoticCatalystsRootNodeHash is DestinyPresentationNodeDefinition
- loreRootNodeHash is DestinyPresentationNodeDefinition
- currentRankProgressionHashes is DestinyProgressionDefinition[]
- insertPlugFreeProtectedPlugItemHashes is DestinyInventoryItemDefinition[]
- insertPlugFreeBlockedSocketTypeHashes is DestinySocketTypeDefinition[]
- currentSeasonalArtifactHash is DestinyArtifactDefinition or DestinyInventoryItemDefinition (idk)
- currentSeasonHash is DestinySeasonDefinition
- seasonalChallengesPresentationNodeHash is mapped (DestinyPresentationNodeDefinition)
- futureSeasonHashes is DestinySeasonDefinition[]
- pastSeasonHashes is DestinySeasonDefinition[]

**Comment by justrealmilk** [comment]
Ah I misunderstood your query. Carry on

**Comment by jshaffstall-bng** [comment]
Good catch. Can do

**Comment by jshaffstall-bng** [comment]
Sorry for the delay here - filed as TFS 1054128 for tracking. Not sure about an ETA though.

**Comment by jshaffstall-bng** [comment]
We just pushed updates to the Bnet API spec and docs to add more of the hash-to-definition-type mapping annotations. I'm closing this out, but please file a new issue when you find more we can add.
