### ISSUE TITLE
searchDestinyPlayerByBungieName: UserCannotResolveCentralAccount 

### ISSUE THREAD

**Issue by xgerhard** [Bungie-net/api#1559]
For visibility I created a new issue, it's similar to #1516 however we're using a different endpoint now.

Some players/accounts can't be found when using exact search.

Example `/Platform/Destiny2/searchDestinyPlayerByBungieName/all/`: 

``` 
[
  "displayName" => "nocalfjones",
  "displayNameCode" => 3637
]
```

Results in:
```
"ErrorCode": 217,
"ThrottleSeconds": 0,
"ErrorStatus": "UserCannotResolveCentralAccount",
```

Get profile: `/Platform/Destiny2/3/Profile/4611686018468074858/?components=100`
```
displayName:"Nocalfjones"
bungieGlobalDisplayName:"Nocalfjones"
bungieGlobalDisplayNameCode:3637
```

**Comment by xgerhard** [comment]
Another one: `aquaCJA#4689`

**Comment by axsLeaf** [comment]
any chance you were able to find a workaround? I have it so that people can input their profile url and get their destiny profiles from the BungieNext ID, but i was hoping for a cleaner solution...

**Comment by axsLeaf** [comment]
Adding to this to hopefully bump it.

Player `Kurumi#8423` returns the same error, yet the profile is here: https://www.bungie.net/7/en/User/Profile/3/4611686018482978970

**Comment by mikechambers** [comment]
Another account hitting it:

danielej2k#2330

(User has active account, and all other API calls work.
