### ISSUE TITLE
Player cannot equip or transfer items.

### ISSUE THREAD

**Issue by SunburnedGoose** [Bungie-net/api#156]
Have a player that can see their characters and view all their items, but is unable to equip or transfer.  Here is the error response.

![screen shot 2017-09-20 at 1 33 38 pm](https://user-images.githubusercontent.com/984608/30661884-eccf91ac-9e0a-11e7-9d26-b7335855ce16.png)

![screen shot 2017-09-20 at 1 33 31 pm](https://user-images.githubusercontent.com/984608/30661936-11253732-9e0b-11e7-856e-5ae490b5cd5e.png)

![screen shot 2017-09-20 at 1 33 12 pm](https://user-images.githubusercontent.com/984608/30661943-1ad7b584-9e0b-11e7-83ef-8b10b5c1dc13.png)

**Comment by SunburnedGoose** [comment]
![screen shot 2017-09-20 at 1 34 33 pm](https://user-images.githubusercontent.com/984608/30661996-448043d8-9e0b-11e7-8bbc-d757a608930c.png)

![screen shot 2017-09-20 at 1 33 58 pm](https://user-images.githubusercontent.com/984608/30662021-5aba76dc-9e0b-11e7-8027-c4f91448dd1b.png)

**Comment by floatingatoll** [comment]
Is there any useful error message under the Response tab of the latest screenshot?

**Comment by vthornheart-bng** [comment]
Aye, if you can get it I'd love to see the specific error code they're getting back when this happens!

**Comment by SunburnedGoose** [comment]
I'll reach out and get the response.

**Comment by vthornheart-bng** [comment]
Thank you!  Yeah, it's a bit of a mystery, I don't see anything particularly troubling in our logs for this user.  We'll see if the response code gives any hint as to what's up.

**Comment by vthornheart-bng** [comment]
Is the user still experiencing this?

**Comment by bhollis** [comment]
I haven't seen anything like this in years.
