### ISSUE TITLE
Cannot equip armor ornaments via InsertSocketPlugFree

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#1561]
We've found that armor ornaments do not work when you try to insert via InsertSocketPlugFree:

`{"ErrorCode":1663,"ThrottleSeconds":0,"ErrorStatus":"DestinyItemActionForbidden","Message":"This action can only be done in-game.  I know, we're bummed about it too.","MessageData":{"request.plug":"Wrong item type or subtype for action."}}`

For example, here's an armor ornament and its material requirements - you can see it's free:
https://data.destinysets.com/i/InventoryItem:1967684865/MaterialRequirementSet:1657777515

I wonder if the issue has something to do with the fact that the ornament InventoryItem is also armor (they do double duty).

For DIM we'd like this to be able to create "look loadouts" that customize the style of all your armor in one go.

**Comment by jshaffstall-bng** [comment]
Do you have specific examples of armor ornaments that don't work with `InsertSocketPlugFree`? The ones I've checked seem to be working when I try them.

**Comment by jshaffstall-bng** [comment]
Rather, the `InsertSocketPlugFree` actions seem to work fine for 'Universal Ornaments' but not for transmog'd armor pieces. Thanks for the heads up!

**Comment by bhollis** [comment]
Awesome, that was the distinction I hadn't figured out!

**Comment by jshaffstall-bng** [comment]
TFS: 1053411 for tracking. This should be fixed on 12/16, but I don't know if we'll have a fix sooner than that,

**Comment by jshaffstall-bng** [comment]
This is also related to why 'Empty Aspect Socket' and 'Empty Fragment Socket' can't be applied on Stasis subclass sockets. The Aspects and Fragments have a 'Mod' item type, but the 'Empty' items don't. This will also be fixed on 12/16 or before.

**Comment by ryan-rushton** [comment]
> This is also related to why 'Empty Aspect Socket' and 'Empty Fragment Socket' can't be applied on Stasis subclass sockets. The Aspects and Fragments have a 'Mod' item type, but the 'Empty' items don't. This will also be fixed on 12/16 or before.

@jshaffstall-bng I was just playing around with aspects and fragments and it appears as though you cannot equip a fragment/aspect if the empty plug is currently in the socket. 

I would assume your comment is the same issue but figured I would point out the use case in the event it's useful.

**Comment by jshaffstall-bng** [comment]
This should be fixed now, enjoy!

@ryan-rushton I don't think I had a repro for that, and all aspects and fragments seem to work for me now too.
