### ISSUE TITLE
Linking account from 2015

### ISSUE THREAD

**Issue by Eyecrosser** [Bungie-net/api#1562]
I am having an issue with linking my very first destiny accounts to destiny 2. When I started up destiny 2 for the first time it showed me all my accolades from 2015 but never gave me any of my stuff back. ![image](https://user-images.githubusercontent.com/95922021/145584271-146024d5-3a6c-4647-8200-c5605ea5da72.jpeg)

**Comment by jshaffstall-bng** [comment]
Hey welcome back to the game, we hope you like it!

Destiny 2 is a fresh start and only your characters are carried forward from Destiny 1.

You can still go back and play D1, but you won't have any of that gear when you start playing D2.
