### ISSUE TITLE
Send Clan Invites via API?

### ISSUE THREAD

**Issue by aescolastico** [Bungie-net/api#1563]
Is there an endpoint available for this action? official or otherwise ;)

**Comment by delphiactual** [comment]
no

**Comment by soren42** [comment]
Not as such.  The "workaround" (which is really dependant on your application) is to have the user auth their own account, (approve your app, if they haven't done so already), request to join the clan, and then (optionally) automate the acceptance on the backend (using a clan admin account).  It's kludgy and doesn't work for every scenario, but maybe it'll get you thinking of how do it for yourself, too.

Unfortunately, there's a risk of invite spam if they unlock the endpoint you're referring to for external use.  A malicious user or buggy application could spam invites to tons of users or spam a single user tons of invites.

**Comment by jshaffstall-bng** [comment]
Yeah sorry, clan invites and other clan admin actions are not available to 3rd party apps.

**Comment by justrealmilk** [comment]
clan admin actions such as approving join requests and managing member ranks **are** available! 😛
