### ISSUE TITLE
Missing hash type mappings fixing.

### ISSUE THREAD

**Issue by EndGameGl** [Bungie-net/api#1566]
In addition to https://github.com/Bungie-net/api/issues/1558
I can search through api and write down all missing mappings, but that's a lot of work, so I'm asking in advance:
Will this be used and fixed or it'll be a pointless thing to do?

**Comment by EndGameGl** [comment]
Any comments on this one? It already hangs like for 17 days, would really like to hear anything back

**Comment by jshaffstall-bng** [comment]
Sorry for the delay, we're back now.

Yes, if you can show us all the places that aren't mapped to definition types correctly, we will make an effort to add the appropriate mappings. Thanks!

**Comment by jshaffstall-bng** [comment]
We just pushed updates to the Bnet API spec and docs to add more of the hash-to-definition-type mapping annotations. I'm closing this out, but please file a new issue when you find more we can add.
