### ISSUE TITLE
Dares Power-ups Objective misnamed

### ISSUE THREAD

**Issue by nev-r** [Bungie-net/api#1569]
the objective [2588042065](https://data.destinysets.com/i/Metric:2588042065/Objective:2734273826) seems misnamed.
it doesn't correspond to its parent metric [2588042065](https://data.destinysets.com/i/Metric:2588042065)

it's instead a dupe of [1270510989](https://data.destinysets.com/i/Metric:4036641132/Objective:1270510989)
which correctly mirrors the description of its parent metric [4036641132](https://data.destinysets.com/i/Metric:4036641132)

here's the two in-game:
![image](https://user-images.githubusercontent.com/68782081/146718634-10ae319c-1f6b-4c6b-9967-d30a1a2dc4af.png)![image](https://user-images.githubusercontent.com/68782081/146718650-3ab4535f-fafc-4f8a-a023-9da911c404ae.png)

**Comment by jshaffstall-bng** [comment]
Interesting - is that incorrect objective progress description field ever shown in-game? It looks like the UI is showing other (correct) string instead.

If the incorrect string is not shown in-game, I don't know how likely it'll be to get fixed on the game content side.

**Comment by nev-r** [comment]
yeah it's probably game content. i think the displays in-game are driven off the metric description instead of the objective
