### ISSUE TITLE
Trouble with Destiny2.GetItem

### ISSUE THREAD

**Issue by ChemDataFarmer** [Bungie-net/api#157]
I'm hitting the endpoint below which should correspond to data for the Mida Multi Tool. However, I keep getting the error "Item Not Found".

"/Destiny2/2/Profile/4611686018460847890/Item/1331482397/?components=304"

I have tried other weapons this user has and I have also tried other components, all of which return the same result.

Either this is a bug, or I'm doing something wrong. In either case I'd appreciate being pointed in the right direction.

**Comment by vthornheart-bng** [comment]
Ah, no worries!  The situation here is that you're passing an itemHash rather than an itemInstanceId.  GetItem will only return instanced items, and it needs to know the instance ID of the item you desire.  (for example, you could have 2 Mida Multi Tools in theory: only the instance ID can distinguish between them, as it is globally unique across all items)

Try the instance ID, and let me know if you run into any other issues!

**Comment by ChemDataFarmer** [comment]
Thanks for the quick reply! That makes sense. How do I get gun data if given the itemHash? The PGCR gives itemHash data and I'd like to use that to look up the name of the gun, its stats, and the type of weapon it is.

**Comment by ChemDataFarmer** [comment]
I think I figured out that I can use the manifest for this, but I haven't figured out how to decompress the .content file holding the manifest. I've made a separate question post to ask about this.

**Comment by yergi** [comment]
Despite the `.content` suffix, it's actually a sqlite file.

**Comment by NullRoz007** [comment]
You could also use [Destiny2.GetDestinyEntityDefinition](https://bungie-net.github.io/#Destiny2.GetDestinyEntityDefinition). 
It takes an item hash and an entity type as parameters, which for your case would be DestinyInventoryItemDefinition, Much easier than dealing with the manifest, at least in my experience.

**Comment by floatingatoll** [comment]
Note that the rate-limiting will make using that endpoint for item queries
relatively slow to use without caching, compared to the sqlite manifest. I
would actively encourage against using it when processing PGCR data if at
all possible to use the manifest, due to the 'bulk' nature of the queries.

**Comment by nine13tech** [comment]
If you ware working, please close the issue. Also, find the dev community on discord for faster assistance. https://discord.gg/gfvPBZ9
