### ISSUE TITLE
How to get the Season related to an equipment?

### ISSUE THREAD

**Issue by YUMEYA** [Bungie-net/api#1570]
e.g. The Number auto rifle has two versions, one was introduced in Year 1 and another was reproduced in Season of the Splicer. I looked into the JSONs in manifest database but I can't find any clue on how to link the Season and the equipment together. Any suggestions?

**Comment by delphiactual** [comment]
You can do it by making a list based off the season icon, but you will have to manually curate it or check out https://github.com/DestinyItemManager/d2-additional-info/blob/master/output/watermark-to-season.json

**Comment by YUMEYA** [comment]
> You can do it by making a list based off the season icon, but you will have to manually curate it or check out https://github.com/DestinyItemManager/d2-additional-info/blob/master/output/watermark-to-season.json

I get it , thank you very much!
