### ISSUE TITLE
difficult lost sectors not showing up in GetActivityHistory

### ISSUE THREAD

**Issue by D217696** [Bungie-net/api#1571]
Normally I was able to get legend and master lost sector runs from the endpoint `GetActivityHistory` using mode 46, but now im not able to find them anymore, even using no mode at all, they wont show up.

edit: Older runs show up, but new ones wont

**Comment by jshaffstall-bng** [comment]
Curious - does this repro for all Legend and Master lost sectors? Or could this somehow be limited to only the handful of new ones in Season 15?

**Comment by nev-r** [comment]
this applies to all Legendary and Master Lost sectors, including ones that existed before S15

some time between Dec 3 and Dec 15 (obvious candidate Dec 7) they stopped being added to activity history or are no longer flagged with an appropriate game mode or something. old runs are still there in history, but new runs no longer appear, much like iron banner, trials, and rumble, etc have stopped showing up before.
