### ISSUE TITLE
Stasis aspects have canInsert set to false when the user has unlocked them.

### ISSUE THREAD

**Issue by ryan-rushton** [Bungie-net/api#1572]
We are seeing an issue where a user has `canInsert` set to false on all their aspects for their warlock, even though they have said they have unlocked them.

I tried recreating this on my own character by emptying all my aspect and fragment sockets but it didn't recreate the issue.

We are surfacing the `canInsert` data from the users profile response, specifically `profileResponse.profilePlugSets.data.plugs` using the using a PlugSet hash of `3327280946`.

An example of a single non empty object is 
```
{
  canInsert: false,
  enabled: true,
  insertFailIndexes: [1],
  plugItemHash: 668903196,
}
```

Edit: Further investigation has shown that the `insertionRule` failing is index 1 which is "You haven't unlocked this ability".

User profile id is 4611686018430296626.

Edit 2: The users experiencing this are only seeing it on one of their three characters. For the two cases we saw it's only their warlock that is experiencing the issue.

**Comment by jshaffstall-bng** [comment]
Did we get a better understanding of this issue? I was curious if `canInsert` being false was appropriate after an account played on a platform where the Beyond Light entitlement was not owned.

**Comment by ryan-rushton** [comment]
Sorry this slipped off my todo list. Yeah I did chat with the users a bit more. The interesting condition that happened to both users is that it was only their warlock that was effected, the other characters were fine.

I asked one users about platforms and such. They only played on xbox and owned beyond light on xbox too, so I don't think that is the issue.

**Comment by robojumper** [comment]
I (4611686018483139177) am also hitting this on Hunter and Titan Void 3.0 subclasses and have been for a while. Warlock works fine for me. Some other DIM users are also reporting this issue.

For reference, the profile plug set `3153258569` (Warlock aspects) reports all entries with `enabled` and `canInsert` set to `true`, but the plug set `564264626` (Titan aspects) reports all entries (except the empty one) with something like

```json
{
    "plugItemHash": 1602994568,
    "canInsert": false,
    "enabled": false,
    "insertFailIndexes": [1],
    "enableFailIndexes": [1]
}
```

The fail indexes correspond to "Not Yet Unlocked".

**Comment by robojumper** [comment]
An additional observation I made while testing if Strand is affected too -- all Fragment and Aspect sockets of all subclasses include `ProfilePlugSet` in their `plugSources`, but not `CharacterPlugSet`, and Bungie.net always reports the plugs in `profilePlugSets`, not the `characterPlugSets` of the GET Profile response. This is definitely incorrect for Strand and 3.0 Fragments, as these are unlocked per-character (while Stasis is unlocked profile-wide). It could also be the reason Aspects are affected -- different character classes have access to different sets of Aspects anyway, so it could make sense for these to be reported in `profilePlugSets`, but maybe Bungie.net erroneously reports the availability of one character as profile-wide, resulting in the two other characters not getting the correct unlock status.
