### ISSUE TITLE
[openapi spec] titlesByGender object keys are wrong

### ISSUE THREAD

**Issue by nev-r** [Bungie-net/api#1573]
spec claims the titlesByGender dictionary is keyed by the DestinyGender enum
```json
"Destiny.Definitions.Records.DestinyRecordTitleBlock": {
  "type": "object",
  "properties": {
    "hasTitle": {
      "type": "boolean"
    },
    "titlesByGender": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      },
      "x-dictionary-key": {
        "type": "integer",
        "format": "int32",
        "x-enum-reference": {
          "$ref": "#/components/schemas/Destiny.DestinyGender"
        },
        "x-enum-is-bitmask": false
      }
    },
```

but it's actually keyed by two string keys named `Male` and `Female`

**Comment by jshaffstall-bng** [comment]
Looks like the JSON serialization turns the enum value key into the enum name instead of the int32 value.

would a change to the API spec and docs make the most sense here? Filed as TFS 1055852.

**Comment by nev-r** [comment]
a spec/doc change feels kindest for existing consumers of the data,
and if it were keyed by DestinyGender, it would need 3 values, one for `2` (Unknown)

**Comment by jshaffstall-bng** [comment]
We don't have titles for that value, and in this case we don't need the map to be exhaustive for the enum.
