### ISSUE TITLE
DestinyItemInstanceEnergy.energyUsed is incorrectly calculated when mods are deactivated

### ISSUE THREAD

**Issue by nev-r** [Bungie-net/api#1574]
in-game this item reports as having all 10 energy consumed
![image](https://user-images.githubusercontent.com/68782081/147909810-7fa668c7-c301-4bd4-9d02-17e80f47e698.png)

but API reports
```
"energyCapacity":10,
"energyUsed":7,
"energyUnused":3
```

the 3 energy mod on the left is currently `"isEnabled":false`
(due, in-game, to no longer being unlocked for the character)
and bnet seems to interpret "not enabled" as "does not consume energy", but this is incorrect

the 3 energy are still "spent" here, and no mod with a cost can be plugged into the remaining empty sockets.
`energyUsed` should be `10`

**Comment by jshaffstall-bng** [comment]
Good catch - filed as TFS 1055854.
