### ISSUE TITLE
Can't invoke API '/User/GetMembershipsForCurrentUser/'

### ISSUE THREAD

**Issue by FreeZhang61** [Bungie-net/api#1577]
I'm follow this [OAuth-DOC](https://github.com/Bungie-net/api/wiki/OAuth-Documentation)  and already get access token by code successfully,  but  when I use this token and API-KEY invok API '/User/GetMembershipsForCurrentUser' just like 
` curl --request GET 'https://www.bungie.net/platform/User/GetMembershipsForCurrentUser/' \
--header 'X-API-Key: $key' \
--header 'Authorization: Bearer  $Token' 
`     get 500 code as responded,  so what's wrong with this curl and what is the correct invoke?

**Comment by dswistowski** [comment]
The endpoint works just fine for me:

```
$ curl -H "X-Api-Key: $API_KEY" -H "Authorization: Bearer $TOKEN" https://www.bungie.net/Platform/User/GetMembershipsForCurrentUser/ | jq ".Response.destinyMemberships[].displayName"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2144    0  2144    0     0   7172      0 --:--:-- --:--:-- --:--:--  7292
"the-the-whistler"
"damian"
"thethethe#3895"
```

1. Do you use the same API_KEY for token generation 
2. How did you generated your token?

**Comment by FreeZhang61** [comment]
> The endpoint works just fine for me:
> 
> ```
> $ curl -H "X-Api-Key: $API_KEY" -H "Authorization: Bearer $TOKEN" https://www.bungie.net/Platform/User/GetMembershipsForCurrentUser/ | jq ".Response.destinyMemberships[].displayName"
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  2144    0  2144    0     0   7172      0 --:--:-- --:--:-- --:--:--  7292
> "the-the-whistler"
> "damian"
> "thethethe#3895"
> ```
> 
> 1. Do you use the same API_KEY for token generation
> 2. How did you generated your token?

I didn't do anything with the token, the token is real long, here is my real curl cmd
`
curl -H "X-Api-Key: $token" -H "Authorization: Bearer CJXnAxKGAgAgKFCUBk8TmKmh1hA+iBm2d5U78cfwgZLXIOUp9PSQLw/gAAAAwjQ1GOYi/Tn4f2jQdbZ0ky5wk8FHEFmj/q7juH3QNZ/e2H+pSwNn2XgooQnjA+39oTW/NfHacTPsAMVVnGC6UC53Y0tQg+82UTq5mOGc/zRMUJ8jYbVD5e/Pl5A2t+iMQrnVRVegIbaLvM//1OgOOnyoFGf0wWdM5ViYltYDS0OwOmMnN39OORLLPUtJDUh21vgIIxKaiIlvuJs5LekomDU4EGW95sL5DBtaYJAhkBwfmPILx95h0t1042YN9IiXGOrMtQlK6Vdirq+CkTkiLCc5unYE+cDJuE85+NXJuNk=" https://www.bungie.net/Platform/User/GetMembershipsForCurrentUser/
`
so,   whether the token looks normal?

**Comment by dswistowski** [comment]
Your token looks fine, the API key should be 32 long hex string from https://www.bungie.net/en/Application

You should generate your Authorization token with the same application (the API key should be the same). It token was generated with a different application you cannot use it for your request. 

My question was how you generated/obtained the token.

**Comment by FreeZhang61** [comment]
> Your token looks fine, the API key should be 32 long hex string from https://www.bungie.net/en/Application
> 
> You should generate your Authorization token with the same application (the API key should be the same). It token was generated with a different application you cannot use it for your request.
> 
> My question was how you generated/obtained the token.

I have not generated the token,  the token was got by API `https://www.bungie.net/platform/app/oauth/token/` which return json just like `{
    "access_token":"2YotnFZFEjr1zCsicMWpAA",
    "token_type":"Bearer",
    "expires_in":3600,
    "refresh_token":"tGzv3JOkF0XG5Qx2TlKWIA",
    "refresh_expires_in": 7776000
    "membership_id":"4352344"
}` , than I use this access_token as Bearer token and API-Key pass them to API `https://www.bungie.net/platform/User/GetMembershipsForCurrentUser/` but got code 500.

**Comment by dswistowski** [comment]
The way you do it looks correct

To call `https://www.bungie.net/platform/app/oauth/token/` you need `authorization_code ` or `refresh_token` and `auth_token` created by you with `client_id` and `client_secret`. Is the client id from the application you are using api-key later?

From my experience with bungie.net platform API - 500 is in lots of places when one would expect 400 or 401 - or 404 (when you put not expected value to path parameters). I would suggest treating this 500 as 401 - and trying to find out why it can be 401 (i would guess you are mixed app credentials somewhere during the flow)

**Comment by Achronos-BNG** [comment]
It isn't clear from your text, but the access token (the thing after "bearer") is not the same thing as your API key.  I've seen people confuse the two or send the access token as the API key. A poorly formatted API key could return a 500 in certain request constructs.
