### ISSUE TITLE
Issue with Gambit on Destiny 2

### ISSUE THREAD

**Issue by Thraxx01** [Bungie-net/api#1579]
There is an issue in the gambit game mode on Destiny 2 where sometimes the spawn point for enemies will get stuck in one spot after killing all the enemies that spawn there, and will not switch to a new location. This results in no new enemies spawning, causing you to be unable to win. I have 2 short videos of this, in this particular situation we went from being up 50 motes on the enemy team to losing because we could not acquire any more motes due to this bug.

I've linked 2 the videos showcasing this.

https://youtu.be/cdEzOpRKn-4
https://youtu.be/hZabMcDm5Ag

**Comment by Achronos-BNG** [comment]
This github is for reporting issues related to the bungie.net api.  Game issues should be reported to the appropriate help forum on bungie.net - posts about game bugs are monitored (even if you don't get a reply).
