### ISSUE TITLE
Overwrite Shaders and Mods that are uncollectible (e.g. have a cost)

### ISSUE THREAD

**Issue by delphiactual** [Bungie-net/api#1580]
Currently you can overwrite `Sweaty Confetti` with an Empty Mod Slot.

Sweaty Confetti should just be in the API insertPlugFreeProtectedPlugItemHashes list because it essentially behaves like the Trandescendent Blessing/Riven's Curse mods that are already in there

You can also overwrite `Cobalt Clash` with any other shader via the API, which is not available in collections.
XrayAlfaVictor did this as a test for us. bungie.net profile is linked [here](https://www.bungie.net/7/en/User/Profile/254/14931404/XrayAlfaVictor)

![unknown](https://user-images.githubusercontent.com/4798491/151628217-1231c129-daca-4c1a-9d5f-743e81f7fff7.png)

**Comment by jshaffstall-bng** [comment]
Sorry for the delay, but good finds! Filed as TFS 1070777.

**Comment by nev-r** [comment]
the above examples seem fixed
