### ISSUE TITLE
How to tell if a record has been completed?

### ISSUE THREAD

**Issue by aescolastico** [Bungie-net/api#1581]
Can't seem to find any reference for this so I thought I'd ask here. 
For the "Destiny.Components.Records.DestinyRecordComponent" object, what exactly determines its completion status? Is it the "state" property? And if so, what value or values refer to a "completed" record.

Thanks in advance

**Comment by nev-r** [comment]
- its state property
- https://bungie-net.github.io/#/components/schemas/Destiny.DestinyRecordState
- read up on "bitwise flags" for more info on how to interpret

**Comment by joaopmarquesini** [comment]
@aescolastico just a heads up, some records can be misleading by returning both `ObjectiveNotCompleted` and `RecordRedeemed` at the same time (from what I checked, mostly from Legacy Seals).
to make sure, check for `RecordRedeemed` and then for the negative `ObjectiveNotCompleted` if you just looking for completion.
