### ISSUE TITLE
DESTINY 2 GAME HINTS ARE STUCK ON SCREEN

### ISSUE THREAD

**Issue by BUNGIESUKS0116** [Bungie-net/api#1585]
No official support anywhere to be found and honestly going to start a campaign of NOT playing this game. the UI is stuck on game hint display with no fix WHATSOever.

**Comment by jshaffstall-bng** [comment]
You can look for troubleshooting steps on the Bungie Help site - https://help.bungie.net/

Or ask for support on the Help forums - https://www.bungie.net/en/Forums/Topics?tg=Help

**Comment by BUNGIESUKS0116** [comment]
> No official support anywhere to be found and honestly going to start a campaign of NOT playing this game. the UI is stuck on game hint display with no fix WHATSOever.

there is no help there so unless YOU have any answers this is completely inadequate
