### ISSUE TITLE
Destiny.Components.Profiles.DestinyProfileTransitoryPartyMember status property

### ISSUE THREAD

**Issue by Samsinite** [Bungie-net/api#1587]
Hi,

When fetching [DestinyProfileTransitoryPartyMember](https://bungie-net.github.io/multi/schema_Destiny-Components-Profiles-DestinyProfileTransitoryPartyMember.html#schema_Destiny-Components-Profiles-DestinyProfileTransitoryPartyMember) and looking at the player's status, I am expecting the enum to be equivalent to the [DestinyProfileTransitoryPartyMember](https://bungie-net.github.io/multi/schema_Destiny-DestinyPartyMemberStates.html#schema_Destiny-DestinyPartyMemberStates) enum (integers 0, 1, 2, 4, and 8) as specified in both the documentation and [openapi specification](https://raw.githubusercontent.com/Bungie-net/api/master/openapi-2.json). I'm seeing unexpected values such as  3 and 11, what do these values represent?

**Comment by delphiactual** [comment]
1+2=3
8+2+1=11

**Comment by floatingatoll** [comment]
It's a binary bitfield, so you need to process the enum integers as binary:

enum 0 = 00000000 = 0
enum 1 = 00000001 = 2^0
enum 2 = 00000010 = 2^1
enum 4 = 00000100 = 2^2
enum 8 = 00001000 = 2^3
etc.

And then interpret the returned values 3 and 11 in the same way:

3 = 00000011 = 2^1 + 2^0 = multiple enums: 2, 1
11 = 00001011 = 2^3 + 2^1 + 2^0 = multiple enums: 8, 2, 1
