### ISSUE TITLE
currentpage parameter mischaracterized in GroupV2.GetMembersOfGroup endpoint

### ISSUE THREAD

**Issue by pylaligand** [Bungie-net/api#159]
At https://github.com/Bungie-net/api/blob/master/openapi-2.json#L2253, `currentpage` should be a query parameter, not a path element. The description of the endpoint path does not include it:
```
"/GroupV2/{groupId}/Members/"
```
(https://github.com/Bungie-net/api/blob/master/openapi-2.json#L22440)

**Comment by gitFurious** [comment]
Similar to issues #124 and #102?

**Comment by pylaligand** [comment]
Looks like it.
