### ISSUE TITLE
beyond the light - exotic, vendor (2209308523) not found

### ISSUE THREAD

**Issue by AnotherEye** [Bungie-net/api#1592]
Hi all, 
as title's says, no data sales is found for the beyond the light - exotic vendor at the tower, this is the endpoint that i call:
https://www.bungie.net/Platform/Destiny2/2/Profile/{myProfileId}/Character/{myCharId}/Vendors/2209308523/?components=300,302,304,305,400,401,402,600
the response is 
{
    "ErrorCode": 1627,
    "ThrottleSeconds": 0,
    "ErrorStatus": "DestinyVendorNotFound",
    "Message": "The Vendor you requested was not found.",
    "MessageData": {}
}

am i wrong somewhere?

**Comment by jshaffstall-bng** [comment]
Good catch! I don't think this vendor is configured to be returned by the API.

We can add that soon.

**Comment by AnotherEye** [comment]
:LOVE:

**Comment by AnotherEye** [comment]
other question...
there is any way to grab the response in the local language, on the endpoint of Destiny2.SearchDestinyEntities (/Destiny2/Armory/Search/{type}/{searchTerm}/) ?

**Comment by jshaffstall-bng** [comment]
Should be there now.

**Comment by AnotherEye** [comment]
yes there is!

**Comment by AnotherEye** [comment]
and what about Ikora's void stuff?

**Comment by jshaffstall-bng** [comment]
Those void subclass ability subscreens are being returned with the Vendor APIs. You should be able to see the state in the D2 Companion apps and DIM.

**Comment by AnotherEye** [comment]
awsome, I hadn't noticed!
