### ISSUE TITLE
How do I get the identifier hash of a weapon?

### ISSUE THREAD

**Issue by zero0neError** [Bungie-net/api#1594]
The problem I have is that I don't know how to obtain the hash of a weapon to make a request and bring me the weapon data, in the bungie getting started it gives you an example of how to request the gjallarhorn one, but I would like to know where it came from has pulled that hash, so I can make my own requests.

**Comment by kramrm** [comment]
Not really an issue with the API.  Might be better asked in the unofficial API Discord server https://discord.gg/E5uB4BW
