### ISSUE TITLE
all new world drop weapons are incorrectly reporting tooltips 0 and 1

### ISSUE THREAD

**Issue by nev-r** [Bungie-net/api#1598]
aside form the crafted glaive, so far every single new weapon is reporting
`This weapon has active Deepsight Resonance that can be progressed.`
and
`This weapon has Resonant Elements available to be extracted. Open the details screen of the weapon to extract.`
this is definitely incorrect. some don't have that, some it's already been expended

**Comment by nev-r** [comment]
actually almost every weapon is reporting this, old and new... don't know why the string was even added to so many weapon defs

**Comment by jshaffstall-bng** [comment]
Very strange! Filed as TFS 1070772.
