### ISSUE TITLE
Element currencies missing/being misreported

### ISSUE THREAD

**Issue by nev-r** [Bungie-net/api#1604]
#### Neutral/Ruinous/Adroit/Mutable/Energetic Element
in `characterInventories` and `characterCurrencyLookups`,
the api seems to report only what's in the forbidden/dummy bucket `2422292810`, i.e. what's been dropped recently
it's an unrelated, much lower number than you actually have, which fluctuates up and down as you play.

it seems like the right place to find this info, unfortunately, is to hand-correlate the var/hash in profileStringVariables or characterStringVariables, to its respective material, and get the currency count from there

- can we get these currency amounts (Neutral Element, Energetic Element, etc) properly threaded through to `profileCurrencies` or `characterCurrencyLookups`? (ideally the former)
- it's weird to have these in there now, but incorrect

**Comment by jshaffstall-bng** [comment]
Yeah I think these are 'virtual' currencies, which aren't being returned by the Bnet API yet. TFS 1069450 for tracking, but we don't have an ETA.
