### ISSUE TITLE
Incorrect foundry traitIds/traitHashes on items.

### ISSUE THREAD

**Issue by chrisfried** [Bungie-net/api#1605]
I'm not sure how widespread this issue is, but I've found at least one instance of an Omolon weapon with a `foundry:hakke` trait: https://data.destinysets.com/i/InventoryItem:2888266564

```json
"hash": 2888266564,
"displayProperties": {
  "name": "Crisis Inverted" // Omolon hand cannon
},
"traitIds": [
  "foundry.hakke"
  "item_type.weapon"
  "weapon_type.hand_cannon"
],
"traitHashes": [
  2210483526 // matches "foundry.hakke"
  4021177463
  2463632503
]
```

**Comment by chrisfried** [comment]
![image](https://user-images.githubusercontent.com/422381/155854942-ef6cd4aa-144c-4381-be66-0868b9a1cc48.png)
- Left: weapons filtered by "foundry.hakke"
- Right: weapons filtered by the URL for the Hakke secondaryIcon

**Comment by jshaffstall-bng** [comment]
Weird! Filed as TFS 1071903.

This is going to require game-side content changes. I think it'll happen at some point, but it probably won't be released until a couple months from now at the earliest.

**Comment by chrisfried** [comment]
New season, so I thought I'd check in on this issue. Still present 😢

Has Hakke secondaryIcon, but lacks `foundry.hakke` traitId:
| Name | Hash |
| --- | --- |
| Herod-C | 1788603939 |
| Legal Action II | 3409645497 |
| The Title | 294129361 |

Has `foundry.hakke` traitId, but lacks Hakke secondaryIcon:
| Name | Hash |
| --- | --- |
| Acantha-D XK8434 | 1757129747 |
| Atalanta-D XG1992 | 2422664927 |
| Bad News XF4354 | 2824241403 |
| Baligant XU7743 | 3461377698 |
| Crisis Inverted | 2888266564 |
| Pyroclastic Flow | 1289324202 |
| Show of Force XF4865 | 4148143418 |
