### ISSUE TITLE
Void 3.0 subclass sockets singleInitialItemHash

### ISSUE THREAD

**Issue by robojumper** [Bungie-net/api#1606]
We're (DIM Loadouts) seeing some inconsistencies in the `singleInitialItemHash` of some socket entries for [Nightstalker](https://data.destinysets.com/i/InventoryItem:2453351420), [Sentinel](https://data.destinysets.com/i/InventoryItem:2842471112), [Voidwalker](https://data.destinysets.com/i/InventoryItem:2849050827) (definition links):

The aspect and fragment sockets have the `singleInitialItemHash` of the empty stasis aspect / fragment plugs, and subclasses in-game are initially created with these plugs, but their plug sets include a *different* empty plug that's the correct one for emptying a socket again, so it's very difficult for us to tell whether an aspect/fragment socket is empty or not and which entry of the plug set is the empty one, since it also means there are two different ways the sockets can be empty.

The grenades sockets (4) have a `singleInitialItemHash` of 0. We are working around this by choosing the first entry of the plug set as a default and the workaround is fine, I just thought I'd bring it up.

**Comment by jshaffstall-bng** [comment]
Yeah socket content can be weird like this sometimes.

I'm not going to lobby for a change to this on the game content side, so I think we're going to have to live with this.
