### ISSUE TITLE
Milestone definition incorrect for hash 2595878741

### ISSUE THREAD

**Issue by fremgenc** [Bungie-net/api#1607]
DestinyMilestoneDefinition, hash: 2595878741

displayProperties.name shows "###DestinyMilestones.MILESTONE-MILESTONE_WEEKLY_WITCH_QUEEN_CAMPAIGN_PARTICIPATION-NAME###"

![image](https://user-images.githubusercontent.com/31008811/155888880-7b99abd3-9266-4fe8-bf22-20a0f989408b.png)

Edit:

These two others as well: 
363309766
2321298069

**Comment by jshaffstall-bng** [comment]
Good catch! Filed as TFS 1071902.

**Comment by andyschott** [comment]
I don't have the hash, but the other milestone for the weekly Witch Queen mission also has a similar friendly name.

**Comment by cfremgen** [comment]
Yup, these two others as well:

363309766

2321298069
