### ISSUE TITLE
Manifest question

### ISSUE THREAD

**Issue by ChemDataFarmer** [Bungie-net/api#161]
Hi all,

I'm trying to use the referenceId (hashIdentifier) for guns reported in the PGCR to look up information on the guns used in various games. However, I can't quite get the manifest figured out. I can get the information I want through the API endpoint "/Destiny2/Manifest/{entityType}/{hashIdentifier}/", but I trying to be a good steward and not abuse this feature since it wasn't intended for repeated, automated queries. I've figured out how to get the .content file from the "/Destiny2/Manifest/" endpoint that holds the path to the manifest database, but I can't figure out how to access the information inside it once I download the .contents file. If I understand correctly, the .content file is a compressed file that's holding an SQLite database. I'm familiar with handling SQLite files, but I don't know how to decompress a .content file.

I'm currently working in Python 2.7 and would really appreciate it if someone could point me in the right direction here. Programming is a hobby for me and I'm still fairly new to it.

**Comment by vpzed** [comment]
The file you download from the path in the Manifest endpoint response is a zip file so you can use the builtin zipfile utility in Python.

**Comment by ChemDataFarmer** [comment]
Thanks for the help!
