### ISSUE TITLE
Nova Warp plug item has perk for Landfall

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#1611]
Nova Warp: https://data.destinysets.com/i/InventoryItem%3A2870169846:undefined/NodeStepSummary:194702279

Its `perkHashes` references this perk: https://data.destinysets.com/i/InventoryItem%3A2870169846:undefined/SandboxPerk:4087094734

Which is "Landfall" from the Stormtrance super.

**Comment by jshaffstall-bng** [comment]
Yuck
