### ISSUE TITLE
Playlist bonus modifiers

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1613]
So y'all added modifiers for double vanguard rank and double nightfall drops... should there be similar modifiers for other activities too? They don't appear to exist yet - at least, not in the manifest

**Comment by justrealmilk** [comment]
Uh oh, this week is _Double Crucible Rank_ but the _Double Vanguard Rank_ modifier is being used and applied to the Control activity

**Comment by jshaffstall-bng** [comment]
This should be fixed now.
