### ISSUE TITLE
Entries in Witch Queen Lore Books redacted when they should be un-redacted

### ISSUE THREAD

**Issue by baxter** [Bungie-net/api#1615]
Hello!

With the API update today I expected to see a number of entries from the Witch Queen lore books be un-redacted, but it looks like they are almost all still redacted.

For example, "Pickman", the first entry in "Lucent Tales", is available in-game but [still has the name "Classified" in the API](https://data.destinysets.com/i/Record:741597464) and is missing all content.

Entries that I think should be present but aren't are:

* Lucent Tales
  * Pickman
  * Three-Oh-Three
* Quintessence
  * Devotion
* Mnemosyne
  * Altars of Reflection—Dispatch
  * Altars of Reflection—Assessment
  * Altars of Reflection—Control
  * Altars of Reflection—New Input
  * RE: Altars of Reflection—New Input
  * Altars of Reflection—Conclusion [Draft]
* Martian Missives
  * Osiris I
  * Eris I
  * Ikora I
  * Caiatl I
  * Ikora II
  * Toland I
  * Zavala I
  * Eris II

There could be others that I'm missing.

I can provide hashes and/or screenshots for any of these if that's necessary!

**Comment by jshaffstall-bng** [comment]
Thanks! We can try to have more of these unredacted for Tuesday 3/8 when we unredact raid content as well.

**Comment by jshaffstall-bng** [comment]
It looks like all of these examples are unredacted now and available in the Bnet D2 content.

Closing this issue, but please file a new issue if there are more lore redactions that are available in the game.
