### ISSUE TITLE
Question About Aphelion's Rest Legend/Master in the Manifest

### ISSUE THREAD

**Issue by Techman** [Bungie-net/api#1618]
Hello,

(To begin, I just want to say that this is my first time making an issue for the Bungie API, so I am mostly following previous tickets as an example. Apologies if I am doing something wrong.)

The Legend/Master Lost Sector for 2022-03-07 is Aphelion's Rest, but some of the modifiers appear to be incorrect when looking up the activity in the manifest?

The description of the Lost Sector mentions Overload and Unstoppable Champions, which is correct, but the Champion Foes modifier mentions Anti-Barrier and Unstoppable. Shielded Foes mention all shield types instead of just Void.

References:
* Legend activity hash: 1898610132
* Master activity hash: 1898610131
* Champion activity modifier: 3649753063
  * For some reason, this modifier is listed twice in the manifest on both activities.
  * "You will face [Shield-Piercing] Barrier and [Stagger] Unstoppable Champions. You must equip Anti-Barrier and Anti-Unstoppable mods to your arms armor to defeat them. These mods come from the Seasonal Artifact."

Now...I am pretty new to the API, but I know stuff like Nightfalls will always show all possible modifiers in the manifest, requiring an API call to get the active modifiers. However, since these activities are pretty specific (and have Legend/Master separate), shouldn't the modifier list already be what was intended in the first place?

**Comment by justrealmilk** [comment]
#1602

**Comment by jshaffstall-bng** [comment]
The root caused here is related to issue 1602 linked by Mr. Braytech. We should have a fix available in Bungie.net content on 3/22.

**Comment by Techman** [comment]
Okay, thank you! I will close this since it is a duplicate.
