### ISSUE TITLE
Return phase data for Vow raid milestone via Profile endpoint characterProgressions endpoint

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1619]
As is done for Last Wish, Vault of Glass, europa descent whatever it's called, also do for `1925223180`. The only other raid that's missing this data (_and_ a milestone) is Garden but she old so heh

Allows us to do cool useful stuff like this to tell the player what their progress is for the week
![image](https://user-images.githubusercontent.com/156681/157345292-3cd346b9-5922-4391-9bdf-6bb5a404247b.png)

**Comment by jshaffstall-bng** [comment]
Filed as TFS 1075056
