### ISSUE TITLE
`enhancements.raid_v600` Vow of the Disciple raid mods have no `itemTypeDisplayName`

### ISSUE THREAD

**Issue by robojumper** [Bungie-net/api#1620]
All other plugs with a `enhancements.*` `plugCategoryIdentifier` have one (e.g. "Vault of Glass Armor Mod", "Activity Ghost Mod", "Nightmare Mod") indicating which kind of mod it is (or in case of the empty mod socket, what kind of mod could go there).

This is Vault of Glass for example: 
![grafik](https://user-images.githubusercontent.com/14299449/157746737-695294c8-dd49-4488-afb4-b30effa4fc97.png)

However, all the new raid mods (`enhancements.raid_v600`) just have an empty string here:
![grafik](https://user-images.githubusercontent.com/14299449/157746809-73c056f6-c02b-4345-9c4b-02f048a1a75a.png)

Ideally the `enhancements.raid_v600` plugs would say "Vow of the Disciple Armor Mod" or "Vow of the Disciple Raid Mod" here.

**Comment by jshaffstall-bng** [comment]
Good catch, filed as TFS 1075408 for the game side. Not sure if this will be fixed, but maybe!

**Comment by robojumper** [comment]
This appears to have been fixed. Thanks!
