### ISSUE TITLE
No ItemCategoryHash entry for new perks and Origin Traits

### ISSUE THREAD

**Issue by Mijago** [Bungie-net/api#1622]
Hi! 

The new Perks (like Hafts) and Origin Traits have just the "Mod" Category 59, but no dedicated CategoryHash in the itemCategoryHashes field. I'd expect something like `2411768833` (type_weapon_scope) or `3708671066` (type_weapon_frame) in there to make it easily recognizeable.
![image](https://user-images.githubusercontent.com/3903469/157907930-5b34750f-447e-4630-8402-9e415d743bfe.png)

Example for Hafts: https://data.destinysets.com/i/InventoryItem:580685494
Example for Origin Traits: https://data.destinysets.com/i/InventoryItem:3363267119

**Comment by jshaffstall-bng** [comment]
Filed as TFS 1075407.

Are there other new mod categories besides Hafts and Origin Traits?

**Comment by Mijago** [comment]
Another one I know about is the Striga Catalyst. I will have a look later or tomorrow.

**Comment by robojumper** [comment]
This also affects all enhanced traits:

[Headstone](https://data.destinysets.com/i/InventoryItem:124408337)
![grafik](https://user-images.githubusercontent.com/14299449/160101387-fa934f49-bddb-4692-b16a-a94ec9bb2c8d.png)

[Enhanced Headstone](https://data.destinysets.com/i/InventoryItem:1171887445)
![grafik](https://user-images.githubusercontent.com/14299449/160102136-6ddcc06c-83e5-4baa-b017-ba90f02dd0b2.png)

Wasn't sure whether to post as a a separate issue.
