### ISSUE TITLE
Feature Request: Identifiers for vendor source on applicable inventory items.

### ISSUE THREAD

**Issue by brendanprice2003** [Bungie-net/api#1624]
For example a response from the definitions could expose an identifier in the form of a hash that denotes the items respective vendor. 

Mainly for the use of bounties, where repeatable bounties are not included in the `itemList` from a vendors' `DestinyVendorDefinition` response.

**Comment by jshaffstall-bng** [comment]
Sorry, I don't think this is really feasible with the complexity of these systems, and with the possibility of unintentionally leaking vendor/item relationships in new content.

Closing this issue, but maybe there is a possibility for more targeted vendor/item relationships, like with the repeatable bounties you mentioned. Either way, probably won't be a priority for us.
