### ISSUE TITLE
Craftable weapons are twice in the manifest

### ISSUE THREAD

**Issue by Mijago** [Bungie-net/api#1625]
Hi!
Craftable weapons exist twice in the manifest. Example for the enigma:

+ An entry that contains the normal weapon data, just like every other weapon: https://data.destinysets.com/i/InventoryItem:2595497736
+ An entry that tells us what Memento trackers can fit on it: https://data.destinysets.com/i/InventoryItem:757218923

I assume that the 2nd entry is the pattern itself, but these patterns are represented like normal weapons, with the exception of their weapon type, categories, missing description etc.
At this point I'd a different `itemTypeAndTierDisplayName` and a specific item category hash in `itemCategoryHashes` that represents those as "Weapon Pattern".

**Comment by jshaffstall-bng** [comment]
Filed as TFS 1075661.

I think we can just add a new item type enum value and item category for 'recipe' items.

**Comment by jshaffstall-bng** [comment]
This change should be live now.
