### ISSUE TITLE
Emblem "The Flow, the Metal" has no name in French

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#1626]
https://data.destinysets.com/i/InventoryItem:3752071771 (select french manifest)

**Comment by jshaffstall-bng** [comment]
Faut-il un nom en français ?  Je ne suis pas si sûr. 🇫🇷🗼🥖🍷

**Comment by jshaffstall-bng** [comment]
Reported as a bug on the game side. No ETA for a fix but hopefully soon!
