### ISSUE TITLE
Missing DestinyActivityModeType 87

### ISSUE THREAD

**Issue by dswistowski** [Bungie-net/api#1627]
`Destiny.HistoricalStats.Definitions.DestinyHistoricalStatsDefinition` response from api have `DestinyActivityModeType`  value `87` which is not defined in api schema.

<img width="705" alt="image" src="https://user-images.githubusercontent.com/197861/158500473-385903ef-851b-40d7-9972-1b5219b52641.png">

https://github.com/itemmanager/bungieapi/runs/5531934841?check_suite_focus=true

**Comment by jshaffstall-bng** [comment]
Yes, that's the new value for `LostSector` 'Legend' and 'Master' activities.

We'll be updating the API spec and docs tomorrow for recent API updates. Sorry for the delay!
