### ISSUE TITLE
PlugSets do not contain CraftingRequirements for Hafts, Magazines, etc

### ISSUE THREAD

**Issue by Mijago** [Bungie-net/api#1629]
Hi!

The Manifest contains "CraftingRequirements" for craftable weapon perks with enhanced versions, but not for perks that are not available in an enhanced version. 

I'd expect to also see the required levels for the first two columns in the manifest.

----------

Example for `The Enigma`:

The magazines for `The Enigma` are capped behind levels, but these are not represented in the Manifest:
https://data.destinysets.com/i/InventoryItem:2595497736/PlugSet:1846203733
![image](https://user-images.githubusercontent.com/3903469/158577468-13c90e50-c755-497b-8156-38c2b3f8c71c.png)

----------

The next PlugSet shows the first weapon perk column, which *contains* the CraftingRequirements:
https://data.destinysets.com/i/InventoryItem:2595497736/PlugSet:645104429
![image](https://user-images.githubusercontent.com/3903469/158577657-8ef791bb-039f-4ad8-86bc-73de2a684267.png)

**Comment by jshaffstall-bng** [comment]
I think you'll _haft_ to look at the `inventory.recipeItemHash` reference to the 'Pattern' version of 'The Enigma' item definition - https://data.destinysets.com/i/InventoryItem:757218923

That definition has sockets with different plug set references, and those plug items do show the proper required levels.

https://data.destinysets.com/i/InventoryItem:2595497736/InventoryItem:757218923/PlugSet:3763479842

![image](https://user-images.githubusercontent.com/25537692/159363580-f0dab464-aceb-4820-8390-2cf9553902e9.png)

Hopefully that makes sense!
