### ISSUE TITLE
Record "Path to Power" has a completionValue of 100,000

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1630]
https://data.destinysets.com/i/Record:3241995275

![image](https://user-images.githubusercontent.com/156681/158956310-3e4c6b5e-9de1-4887-ae0f-a791bedf29f8.png)
![image](https://user-images.githubusercontent.com/156681/158956334-7327ad94-5781-4b7e-bd5d-4dbca24a4dc3.png)

**Comment by nev-r** [comment]
all four of its interval objectives

**Comment by jshaffstall-bng** [comment]
This is caused by in-game logic to 'reduce the completion value' for these objectives.

The 'reduced' values are returned in the `DestinyObjectiveProgress` `completionValue` property.
