### ISSUE TITLE
Expose collectible acquisition timestamp

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#1635]
If there is, hypothetically speaking, a `acquireTimestampUnlockValue` that is reliably populated with when the player first obtained a collectible, it would be very useful and interesting if you could provide this in the Collectibles API response :)

**Comment by justrealmilk** [comment]
Also, #1160

**Comment by t3rr11** [comment]
Yes please as well. Really want both of those.

**Comment by jshaffstall-bng** [comment]
Sorry, this isn't tracked for collectibles or records (triumphs).
