### ISSUE TITLE
Evidence Board Quests have no names

### ISSUE THREAD

**Issue by TheBrenny** [Bungie-net/api#1637]
Ref: https://data.destinysets.com/i/InventoryItem:771946386/InventoryItem:771946386

It appears as if some of the Witch Queen quests are not providing their name in the Database. The Evidence Board quests are an example.

(I feel like this has prbably been reported already, but I couldn't find any)

**Comment by TheBrenny** [comment]
Other than the absence of the name, is there anything to indicate that a quest won't have a name? (Ie different hash category or something?)

**Comment by jshaffstall-bng** [comment]
Sorry, not really. I don't think there's a consistent heuristic besides "missing or empty `displayProperties?.name`? try the `setData?.questLineName` instead."
