### ISSUE TITLE
help: what is the string {var:NUMBER} in db?

### ISSUE THREAD

**Issue by AnotherEye** [Bungie-net/api#1639]
i found some vendor/item with this param inside some details data on db, for example vendor 3442679730, in italian, have:
"flavorLineOne": "Competi nelle Sfide dell'Eternità per ottenere strano favore. Sali di grado per ottenere diverse ricompense. Il tuo grado può essere ripristinato altre {var:365343461} volte."
where i can find what "var 365343461" is?
tnx.

**Comment by jshaffstall-bng** [comment]
From the history in the readme:

## 2021-05-11 Update for the Season of the Splicer

Includes reward item visibility and string variables.
- String variable placeholders (formatted as {var:1234567890}) are found in Destiny definition localized strings.
- D2 Profile API clients can request the new StringVariables component to get per-character integer values by hash.
- Clients can then replace the {var:(hash)} placeholders with the corresponding integer values.
- String variables are currently used in the following places:
  - Armor Synthesis bounties from Ada-1 (descriptions, reward names, tooltips, failure strings)
  - A single Seasonal Challenge record description
