### ISSUE TITLE
[HELP] could someone explain me what is the way to find the season rank?

### ISSUE THREAD

**Issue by AnotherEye** [Bungie-net/api#1640]
i can't find out any endpoint about that, i use the 900 component to retrieve the records, on profile call or character call, but can't find any reference to the season rank/grade.
can someone help me?

**Comment by jshaffstall-bng** [comment]
The season definition has a `seasonPassHash` to a 'season pass' definition, which has two progression hashes for looking up progression state and definitions.

- `rewardProgressionHash` for ranks 1-100
- `prestigeProgressionHash` for tracking prestige rank progression beyond rank 100

So you'll find the season rank state in the `profileProgression` and/or `characterProgressions` components of the `DestinyProfileResponse` with `ProfileProgression` and `CharacterProgressions` components requested.

Relevant definitions:
- Season of the Risen definition - https://data.destinysets.com/i/Season:2809059431
- Season pass definition - https://data.destinysets.com/i/Season:2809059431/SeasonPass:971660532
- Rewards progression definition - https://data.destinysets.com/i/Season:2809059431/SeasonPass:971660532/Progression:2069932355
- Prestige progression definition - https://data.destinysets.com/i/Season:2809059431/SeasonPass:971660532/Progression:1787069365

Hopefully this helps!

**Comment by AnotherEye** [comment]
Awsome!  it took me a while to understand all the rounds to do to get the rank but it works.. thanks !!
