### ISSUE TITLE
Legal terms and monetization

### ISSUE THREAD

**Issue by lucasnpazini** [Bungie-net/api#1641]
As stated in the API terms: "You may not use the Bungie.net API for commercial purposes unless you obtain Bungie’s prior written permission."

Someone can tell me if a new project can get this permission? How? (Just want to show ads in the app/site)

**Comment by soren42** [comment]
Send an email with the details of your project and what you're looking to use to licensing@bungie.com.

See https://help.bungie.net/hc/en-us/articles/360049201911-Intellectual-Property-and-Trademarks for more information.

**Comment by lucasnpazini** [comment]
Didn't get a response yet, is there any developer who have gone through this? Would love to hear your experiences.
