### ISSUE TITLE
PostGameCarnageReport endpoint timing out

### ISSUE THREAD

**Issue by Mijago** [Bungie-net/api#1645]
Hi!

The endpoint `/Destiny2/Stats/PostGameCarnageReport/{activityId}/` is currently timing out for every user/page.
This is probably a temporary issue, but I wanted to bring it to your attention nonetheless, and this is the only place I could think of.

Example URLs that show that it's not working on multiple pages right now:
- https://raid.report/pgcr/10604309011
- https://destinytracker.com/destiny-2/pgcr/10604309011

Small edit: 3 hours later it is still down, so probably not just a hiccup.

**Comment by Mijago** [comment]
Interestingly it works with some entries, like https://raid.report/pgcr/10604668806

**Comment by AnotherEye** [comment]
i've this problem too.

**Comment by AnotherEye** [comment]
as i can see, the timeout seems is coming from 
https://stats.bungie.net/Platform/Destiny2/Stats/PostGameCarnageReport/{activityId}/

**Comment by TorKallon** [comment]
Charlemagne is also severely impacted by this issues.
