### ISSUE TITLE
No name for "lighthouse gift"

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#1646]
https://data.destinysets.com/i/InventoryItem:3377778206 has no name or description

**Comment by jshaffstall-bng** [comment]
Is this item still relevant? I assume not.

It's from the Curse of Osiris expansion, and it doesn't have a name or description in-game either.

**Comment by bhollis** [comment]
Not sure how, but people do have it in their inventory still. Didn't realize it has no name in game.
