### ISSUE TITLE
Missing or wrong URL in World SQL DB

### ISSUE THREAD

**Issue by kenwolter** [Bungie-net/api#165]
I was looking at the images for crucible when I tried to load the pgcrImage for "The Dead Cliffs" and I received a 404 error. Is the image missing or is it the wrong path in the tag?
It says that the url should be: http://www.bungie.net/img/destiny_content/pgcr/crucible_cliffside.jpg

**Comment by vthornheart-bng** [comment]
Should be fixed now!
