### ISSUE TITLE
DestinyItemTranslationBlockDefinition.weaponPatternHash not mapped to DestinySandboxPatternDefinition in API spec

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#1652]
Most of the hashes in the API spec are mapped to their definition table. e.g. `bucketTypeHash` is correctly mapped in `DestinyEquipmentSlotDefinition`

![image](https://user-images.githubusercontent.com/46142/164971713-dfb725fb-3fc6-48fc-bff8-0f0f78a65fc7.png).

However, `weaponPatternHash`  on `DestinyItemTranslationBlockDefinition` is not mapped to `DestinySandboxPatternDefinition`, which prevents Data Explorer from being able to link through to the SandboxPattern definition.

![image](https://user-images.githubusercontent.com/46142/164971733-b6b171f1-252c-4a05-83bd-7c84de148184.png)

**Comment by joshhunt** [comment]
Oh. DestinySandboxPatternDefinition just isn't documented at all in the spec. Huh.

**Comment by jshaffstall-bng** [comment]
The API spec and docs have been updated to include this mapping and `DestinySandboxPatternDefinition`.
