### ISSUE TITLE
/Platform/Destiny2/Vendors/?components=402 only returns xurs inventory items for titans

### ISSUE THREAD

**Issue by lulamae12** [Bungie-net/api#1656]
As far as I can tell when I call this endpoint it only shows xurs legendary armor items for titans. is there a way to see all 3 that i am missing?

im calling it like this:

url = https://www.bungie.net/Platform/Destiny2/Vendors/?components=402
res = requests.get(url, headers=headerParameters)

Thanks!

**Comment by soren42** [comment]
As this is an OAuth endpoint, the vendor inventory you'll see is based on the account and character you poll it with.

If you have characters of other classes, poll the endpoint with their characterId, instead, and it'll appear for that class.

**Comment by lulamae12** [comment]
oh i was calling that pure endpoint. I tried the other way but kept getting resposne [500] errors. im hoping its just taking time for my oauth key to be set up or something

**Comment by soren42** [comment]
Well, I'll be damned.  Yeah, I hadn't realised you could call it that way without OAuth.

I _suspect_ you'll need to use the OAuth endpoint I mentioned to see other character classes, as nothing in that URL, or the query string, includes information on character class.

Typically, you have to auth, and check vendor inventory for a specific account and character, as some items are locked to certain classes or behind story progression, etc.

**Comment by lulamae12** [comment]
ok! thanks so much!

**Comment by soren42** [comment]
Actually, if I read this correctly, I suspect @vthornheart-bng created the specific endpoint you're asking about explicitly for Xûr as a result of this thread.

However, he alludes to **reasons** for which using a non-auth endpoint to get any vendor data is ill-advised.  He indicates that there's a deeper explanation, but if he told us, he'd have to kill us.

Perhaps now, there's years later, he may be able to shed more light.  Or, indeed, he may have already in the intervening years, already explained.

[https://github.com/Bungie-net/api/issues/502#issuecomment-450059562](https://github.com/Bungie-net/api/issues/502#issuecomment-450059562)
