### ISSUE TITLE
Without Remorse and Firefright are missing CollectibleHash and source

### ISSUE THREAD

**Issue by darkelement1987** [Bungie-net/api#1663]
See title.

**Comment by AnotherEye** [comment]
it seems that even all the items in the category 1423951670 (identifier: "category.vendor_saint_engram_purchase") don't have the collectibleHash, I don't know if it's a bug.

**Comment by darkelement1987** [comment]
> it seems that even all the items in the category 1423951670 (identifier: "category.vendor_saint_engram_purchase") don't have the collectibleHash, I don't know if it's a bug.

I think those are intentional, if you search through the api data explorer you'll find some other entries (2x adept, 2x normal)

The ones without a collectibleHash are for display purposes only afaik.

For example, the collectible of Burden of Guilt (Adept) is linked to itemhash 2002522739 while the one that's in Saint's inventory has hash 933455006.

![image](https://user-images.githubusercontent.com/21128187/181203758-65c268a8-b4d7-4314-8ba1-1ee0ea74ed4e.png)

**Comment by AnotherEye** [comment]
and this is the exact problem i have, i use the collectible hash to set an alert if some vendor sell it, but without it i cannot do the right controls...
