### ISSUE TITLE
Tess Everis (3361454721) issue, returning DestinyVendorNotFound

### ISSUE THREAD

**Issue by AnotherEye** [Bungie-net/api#1665]
Hi all, i'm trying to get the Everversum vendor, but it respond with the DestinyVendorNotFound error.
https://www.bungie.net/Platform/Destiny2/2/Profile/4611686018430872273/Character/2305843009269823926/Vendors/3361454721/?components=300,302,304,305,400,401,402,600

**Comment by jshaffstall-bng** [comment]
Eververse is hidden in the vendor APIs to prevent content mismatch issues until ~5/31.

**Comment by AnotherEye** [comment]
ah..it seemed like a mistake!
it could be great if we have any warning messages about it! thanks anyway!
