### ISSUE TITLE
Perk images for some legendary mods show rare mod

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#167]
When listing out the perks for some legendary mods, the perk image (not the mod InventoryItem image, but the SandboxPerk image) is blue instead of purple:

![](https://camo.githubusercontent.com/047b8fbd4e80f90bf3f647f68625e03eca4fe252/687474703a2f2f7a6f6767792e6e65742f66697265666f785f323031372d30392d32335f30312d32362d32302e706e67)

Is it just that they use the same perk under the covers? Is there some way to have a different image here?

**Comment by vthornheart-bng** [comment]
Hmm, I will have to look into it - what do you see when you hover over it in-game?  It could be that the perk's icon is misconfigured in the game itself, but I would have to dig in to find out.  (it could also be that they refer to the same Perk, but I"m not sure yet)

**Comment by bhollis** [comment]
With the new mod economy this is obsolete.
