### ISSUE TITLE
New solar subclasses missing itemType 16 in API

### ISSUE THREAD

**Issue by darkelement1987** [Bungie-net/api#1670]
https://data.destinysets.com/i/InventoryItem:3941205951
https://data.destinysets.com/i/InventoryItem:2550323932
https://data.destinysets.com/i/InventoryItem:2240888816

**Edit:**
Also missing some itemCategoryHashes

**Comment by justrealmilk** [comment]
#1661

**Comment by darkelement1987** [comment]
> #1661

thanks i'll close.
