### ISSUE TITLE
3.0 Subclass talentGrid data location

### ISSUE THREAD

**Issue by ashleypb** [Bungie-net/api#1674]
Can anyone point me in the right direction to get the active 3.0 Subclass the guardian has activated, along with the selected Jump, Grenade, Ability lar lar lar

I use to find the info in...
```
Subclass > ['Response']['characterEquipment']['data'][''.$characterId.'']['items']['11']['itemInstanceId']
telentGrid > ['Response']['itemComponents']['talentGrids']['data'][''.$SubclassId.'']['talentGridHash']
perks > ['Response']['itemComponents']['talentGrids']['data'][''.$SubclassId.'']['nodes']
```

but since the 3.0 i'm not sure where to be looking ???

Any help would be appreciated!

**Comment by jshaffstall-bng** [comment]
3.0 subclass abilities use sockets and plug items, not talents.

Arc is the only subclass still using talents.

**Comment by nsmith31415** [comment]
@ashleypb I'm still trying to figure out how to read/access this data, now that it looks like you've closed the issue, could you help me understand where I find the currently activated subclass nodes?

**Comment by nsmith31415** [comment]
@jshaffstall-bng Could you show me an example of how I can access this?

**Comment by justrealmilk** [comment]
> @jshaffstall-bng Could you show me an example of how I can access this?

The same way you do for items. Every subclass item has an itemInstanceId. Use it to access the item's properties from other data blocks such as sockets under ItemComponents.

**Comment by nsmith31415** [comment]
Thank you! So correct me if I'm wrong please (or if there's an easier way):
It looks like I should use the itemInstanceId to call [Destiny2.GetItem](https://bungie-net.github.io/multi/operation_get_Destiny2-GetItem.html#operation_get_Destiny2-GetItem), with component 305 to get the sockets, and then for each of the sockets that is enabled I can use the plugHash to call [Destiny2.GetDestinyEntityDefinition](https://bungie-net.github.io/#/components/schemas/Destiny.Definitions.DestinyInventoryItemDefinition) and get the details of each plug?
