### ISSUE TITLE
Can't search by destiny name players

### ISSUE THREAD

**Issue by hugos** [Bungie-net/api#1677]
I'm using this GET request https://www.bungie.net/Platform/Destiny2/SearchDestinyPlayer/-1/itheomars

However I always get this response besides having my api key:

```
{
    "Response": [],
    "ErrorCode": 1,
    "ThrottleSeconds": 0,
    "ErrorStatus": "Success",
    "Message": "Ok",
    "MessageData": {}
}
```

**Comment by soren42** [comment]
I did some digging and some testing.  That endpoint doesn't appear in the documentation anymore.  I could still get it to work, but only with exact matches.  (For example, searching for "Soren#9399".)  A couple things on that one: 1) it seems to require a trailing /, and 2) the search term needs to be URL encoded.

Regardless, it *looks* like that endpoint has been deprecated in favour of [this one](https://www.bungie.net/platform/destiny2/help/HelpDetail/POST?uri=SearchDestinyPlayerByBungieName%2F%7BmembershipType%7D%2F) (SearchDestinyPlayerByBungieName).  That's the only search endpoint in the current documentation, so the deprecation is an assumption on my part... but it seems to be the case.

Hopefully this helps!

**Comment by hugos** [comment]
> I did some digging and some testing. That endpoint doesn't appear in the documentation anymore. I could still get it to work, but only with exact matches. (For example, searching for "Soren#9399".) A couple things on that one: 1) it seems to require a trailing /, and 2) the search term needs to be URL encoded.
> 
> Regardless, it _looks_ like that endpoint has been deprecated in favour of [this one](https://www.bungie.net/platform/destiny2/help/HelpDetail/POST?uri=SearchDestinyPlayerByBungieName%2F%7BmembershipType%7D%2F) (SearchDestinyPlayerByBungieName). That's the only search endpoint in the current documentation, so the deprecation is an assumption on my part... but it seems to be the case.
> 
> Hopefully this helps!

Yup, it did!! Cheers mate

**Comment by supercarp** [comment]
@soren42 Thank you for the response. I'm still getting a 404 in the response so I think there's an issue with my request format or content. Is the oauthID required in this request? I will try to figure out how to add that in. Many thanks and also apologies, I'm new to web development.
