### ISSUE TITLE
Some itemSubTypes are missing

### ISSUE THREAD

**Issue by designker** [Bungie-net/api#168]
The following new items have an itemSubType of zero

Trace rifle (Cold heart)
Grenade Launchers
Submachine Gun (SMGs)

It would be nice if they had one

**Comment by vthornheart-bng** [comment]
Yes, definitely!

**Comment by vthornheart-bng** [comment]
Part of needed item type fixes.

**Comment by vthornheart-bng** [comment]
Including this in #319 as a blanket fix for item types that are missing (some like this from the long, long ago)

**Comment by vthornheart-bng** [comment]
Crapload of new item categories incoming.
