### ISSUE TITLE
Config.ClanBanner.ClanBannerSource documentation.

### ISSUE THREAD

**Issue by Aryathel** [Bungie-net/api#1684]
It appears that the [ClanBannerSource](https://bungie-net.github.io/multi/schema_Config-ClanBanner-ClanBannerSource.html#schema_Config-ClanBanner-ClanBannerSource) model is entirely missing any documentation. Is there a reason for this?

If not, might I recommend a docs update to at least explain the basics of the endpoint? I am not sure how to actually offer any meaningful change suggestions since the contributing guidelines state not to make any pull requests, but the fields seem to be something like the following:

```
clanBannerDecals - Options for the main symbol that appears on the banner.
    - A mapping of clan banner decal hashes to Config.ClanBanner.ClanBannerDecal objects.

clanBannerDecalPrimaryColors - Color options for the primary color on a banner decal.
    - A mapping of clan banner decal hashes to Destiny.Misc.DestinyColor objects.

clanBannerDecalSecondaryColors - Color options for the secondary color on a banner decal.
    - A mapping of clan banner decal hashes to Destiny.Misc.DestinyColor objects.

clanBannerGonfalons - The possible basic banner shapes. Currently only one exists.
    - A mapping of clan banner gonfalon hashes to image path strings.

clanBannerGonfalonColors - Color options for the base banner color.
    - A mapping of clan banner gonfalon hashes to Destiny.Misc.DestinyColor objects.

clanBannerGonfalonDetails - Options regarding the pattern to place on the banner's background.
    - A mapping of gonfalon detail hashes to icon path strings.

clanBannerGonfalonDetailColors - Color options for the gonfalon detail.
    - A mapping of gonfalon detail hashes to Destiny.Mist.DestinyColor objects.

clanBannerDecalsSquare - Options for the main symbol that appears on the banner, cropped to a smaller square.
    - A mapping of clan banner decal hashes to Config.ClanBanner.ClanBannerDecal objects.

clanBannerGonfalonDetailsSquare - Options for the pattern for place on the banner's background, cropped to a smaller square.
    - A mapping of clan banner detail hashes to icon path strings.
```

I was able to figure this out by testing the [GetClanBannerSource](https://bungie-net.github.io/multi/operation_get_Destiny2-GetClanBannerSource.html#operation_get_Destiny2-GetClanBannerSource) endpoint, but it would be nice to have proper documentation on this.

As a follow-up note to this, the [ClanBannerDecal](https://bungie-net.github.io/multi/schema_Config-ClanBanner-ClanBannerDecal.html#schema_Config-ClanBanner-ClanBannerDecal) object seems to have an unused `identifier` field in the documentation, unless the model is used somewhere other than just with this request (I was unable to find other usages).

**Comment by enrikayso** [comment]
This would be lovely
