### ISSUE TITLE
`scope` field in GetApplications is sent as a string, not an int

### ISSUE THREAD

**Issue by PyroTechniac** [Bungie-net/api#1700]
According to [the Application docs](https://bungie-net.github.io/#/components/schemas/Applications.Application), scope should be sent as an i64, according to my testing however it seems to be sent as a String, causing confusion.

Would appreciate some clarification on whether this is intended or not

**Comment by jshaffstall-bng** [comment]
I think the idea here is that 64-bit precision values cannot always be stored correctly in JavaScript with 53-bit precision number types.

As such, the Bnet API serializes 64-bit integers as strings.

**Comment by PyroTechniac** [comment]
So should anything stating it's return value as `int64` be serialized as a String?
