### ISSUE TITLE
<bug me if you see me>

### ISSUE THREAD

**Issue by 42A7C5** [Bungie-net/api#1703]
Is this copy intentional? Looks like it might be an internal identifier.

<img width="353" alt="Screen Shot 2022-08-15 at 2 21 59 PM" src="https://user-images.githubusercontent.com/25871560/184720769-863e0a55-0c67-4785-91cd-7b4d5b07e47a.png">

**Comment by ckhicks** [comment]
Priceless

**Comment by nev-r** [comment]
https://github.com/Bungie-net/api/issues/1675
