### ISSUE TITLE
Season of Plunder showing end date as a Wednesday

### ISSUE THREAD

**Issue by kramrm** [Bungie-net/api#1707]
DestinySeasonDefinition for Season of Plunder (Hash 2809059433)

endDate:"2022-11-23T17:00:00Z"

Nov 23, 2022 is not a Tuesday, which is different from normal reset schedules.

**Comment by ashakoor** [comment]
The date is also off by a couple of weeks - in-game shows the end date as Dec 6th

**Comment by jshaffstall-bng** [comment]
Yep, this should be fixed with new Bnet game content on Tuesday, 8/30.

**Comment by kramrm** [comment]
I see the updated date.  Thanks.
