### ISSUE TITLE
new shaders have HUGE icons

### ISSUE THREAD

**Issue by nev-r** [Bungie-net/api#1710]
they are 1440p and >2MB.
as cool as this is (and it is!!), it deviates pretty majorly from usual setup
caused a script expecting little icons to choke on their sheer size

examples:
https://data.destinysets.com/i/InventoryItem:1869315389
![076e000a4e10fb2ee0662ea661515f08](https://user-images.githubusercontent.com/68782081/186481773-fb997210-0810-4d95-aeb7-5c218953e5f8.png)

https://data.destinysets.com/i/InventoryItem:1869315388
![90bfc1efa5b2b25ffbb6293c596d3896](https://user-images.githubusercontent.com/68782081/186482039-3316b916-9255-4ca4-b6b3-1b98b5cfde2a.png)

**Comment by jshaffstall-bng** [comment]
You're welcome

**Comment by jshaffstall-bng** [comment]
It looks like this will be fixed with new Bnet content tomorrow.

**Comment by nev-r** [comment]
seems good here. though still weirdly high res in-game

**Comment by jshaffstall-bng** [comment]
We do a little overriding on the Bnet side
