### ISSUE TITLE
Expedition Not Showing Up In Activity History

### ISSUE THREAD

**Issue by HunBurry** [Bungie-net/api#1711]
After querying several users, it seems that, when querying the Activity History endpoint (Destiny2.GetActivityHistory), all Expeditions (the new season 18 activity) are not showing up. I haven't tested whether or not this is the case when querying by specific modes, but at default, they don't show up, although Pirate Hideouts and Ketchcrashes are. 

I've tested using a Python library for interacting with the API, as well as Postman and the Destiny API explorer.

**Comment by jshaffstall-bng** [comment]
Thanks for filing this, hopefully this can be fixed soon, today or tomorrow.

**Comment by jshaffstall-bng** [comment]
This should be fixed now, assuming you can get Game History calls to succeed.

Expeditions will show up as Offensives and the Eliksni Quarter should no longer show up at all (was a blank Explore activity).
