### ISSUE TITLE
Incorrect description for hash 73143230

### ISSUE THREAD

**Issue by fremgenc** [Bungie-net/api#1713]
Hash:
73143230

Description: 
Complete Dares of Eternity with a score of {var:3648290880} or higher.

**Comment by delphiactual** [comment]
this is not incorrect

**Comment by fremgenc** [comment]
Compare to hash: 363309766

Description gives fully formatted number:
"Get a team score of 100,000 or better."

**Comment by delphiactual** [comment]
It is a variable that they did not want to hardcode

goto https://data.destinysets.com and search deep:{var

**Comment by delphiactual** [comment]
https://github.com/Bungie-net/api/issues/1639#issuecomment-1087493263
