### ISSUE TITLE
When D1 API is disabled, we can't detect it

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#1714]
The D1 API appears to be disabled at the load balancer rather than at the service - this means that the CORS header isn't set, and the error is a generic 503 HTML page (which we can't detect because of the aforementioned CORS header being missing). This means we can't tell the difference between the API being blocked and being down for maintenance. This means users continually ask us why D1 doesn't work, instead of seeing a message saying Bungie has disabled the API. Would it be possible to allow requests into the service and fast-return with a normal SystemDisabled API response instead?

**Comment by jshaffstall-bng** [comment]
I think this came from there whole D1 service being taken offline, rather than disabled.

Typically, the service will just be disabled and you should be able to tell as usual.

If this happens again, feel free to file a new issue.
