### ISSUE TITLE
Account with linked Epic account can't load D1 characters (ErrorCode 1618)

### ISSUE THREAD

**Issue by ChaseMalik** [Bungie-net/api#1716]
It seems to be the latest iteration of #1151 

Calling `https://www.bungie.net/d1/Platform/Destiny/2/Account/4611686018433569897/Summary/`
Returns 
```
{"ErrorCode":1618,"ThrottleSeconds":0,"ErrorStatus":"DestinyUnexpectedError","Message":"An unexpected error has occurred while trying to grab Destiny information.  Let us know if you see this.","MessageData":{}}
```

**Comment by delphiactual** [comment]
https://twitter.com/BungieHelp/status/1563330863471165442

**Comment by ChaseMalik** [comment]
This is not related to that downtime.
This error occurred before the downtime and is still happening after it. The same call works for other players, without linked epic accounts.

**Comment by jshaffstall-bng** [comment]
Filed as TFS 1120041. No ETA on a fix for the D1 APIs, but hopefully we can take care of this sooner than later.

**Comment by im-L0r3** [comment]
Ah, this post calms me and explains.
`array(5) { ["ErrorCode"]=> int(1618) ["ThrottleSeconds"]=> int(0) ["ErrorStatus"]=> string(22) "DestinyUnexpectedError" ["Message"]=> string(104) "An unexpected error has occurred while trying to grab Destiny information. Let us know if you see this." ["MessageData"]=> array(0) { } }`

**Comment by sipso** [comment]
Is there any update on this issue?

**Comment by jshaffstall-bng** [comment]
Yes, the fix for this was deployed yesterday. Sorry for the delay!
