### ISSUE TITLE
D1 Character Lookup

### ISSUE THREAD

**Issue by pacificdune** [Bungie-net/api#172]
I was using the following endpoint to pull D1 characters for a given user:

https://www.bungie.net/Platform/User/GetBungieAccount/<membershipId>/TigerPSN/

After the update the D1 characters are no longer there, and I'm unable to figure out a new way to pull D1 characters.  I was running a competition in my clan to see who had helped the most people get a 390 raid clear.  People put in a lot of work, but I did not run the final tally before the API was changed so I am trying to fix it.

Any advice would be helpful!

Thanks,

John

**Comment by delphiactual** [comment]
https://www.bungie.net/Platform/D1/User/GetBungieAccount//TigerPSN/

**Comment by nine13tech** [comment]
The getBungieAccout endpoint was deprecated. You need to use the Account endpoint.
```python
url = "https://www.bungie.net/platform/destiny/" + str(platform) + "/Account/" + str(membership_id) + "/Character/" + str(character_id) + "/"```

**Comment by pacificdune** [comment]
Got it thank you.
