### ISSUE TITLE
"Ordeal" tag still exists for Nightfalls in the Destiny 2 Companion App.

### ISSUE THREAD

**Issue by SapphicMoe** [Bungie-net/api#1722]
Just a small nitpick, but "Ordeals" for Nightfalls no longer exist now so thought that by removing it from the title, it would clear up confusion.
![Screenshot_20220908-205617_ea74b818d78c225eb6f58f7a40f10180](https://user-images.githubusercontent.com/22654782/189199612-a021408c-fa3f-4603-a714-509ad3ddcde9.jpg)

**Comment by jshaffstall-bng** [comment]
Thanks for the heads up! Filed as TFS 1122420, but I don't have an ETA for a fix.
