### ISSUE TITLE
A question regardin the API

### ISSUE THREAD

**Issue by MiguelBeitia** [Bungie-net/api#1723]
Hello, I am doing a data analysis project and I would like to know if there is the possibility of obtaining the percentage of players that have X weapon or armor through the API. thanks for the help in advance.

**Comment by SolidKalium** [comment]
There is no Bungie API that directly returns that.
You can estimate it by loading a lot of profiles and calculating it yourself.

That's what Braytech does, as [explained on its FAQ](https://bray.tech/addendums/faq).
If you just want to see the values in machine-readable form, the site loads these from Tom's server: https://b.vlsp.network/Common
For your analysis, I would recommend crediting Tom and not making more calls to his API than necessary.

So for the most part you are on your own.
