### ISSUE TITLE
Missing Activities in activity history endpoint

### ISSUE THREAD

**Issue by CaptnBlubber** [Bungie-net/api#1729]
I already noticed this a few times, this week however I was able to finally track down a specific Timewindow.

It seems like the Activity History endpoint sometimes is lacking completed activities.

I was able to track down the missing timeframe in between `period:"2022-10-07T19:13:35Z"` and  `period:"2022-10-07T21:10:20Z"`  so its roughly a timewindow of 2 hours.

I additionally checked the Activity history for all members of the fireteam I was playing with and they all seem to be missing that activity. Therefore I cannot give you an pcgr instanceId unfortunately.

The Activity missing is a (Fresh) Kingsfall (Normal) run which was successfully completed.

The account in question:
```
membershipId: 4611686018461534588
characterId: 2305843009260665578
membershipType: 2
```

**Comment by Cr3aHal0** [comment]
I'm bumping your thread as  I also felt like activities were missing (but thankfully appearing on dungeon.report to claim my point) until I realized several instances of the same activity (ie. Shattered Throne) are tagged under different mode ! More recent ones are  tagged [7, 82] meanwhile some of them in 2021 are labeled [2,7]. Don't know if this could be fixed on Bungie's end for consistency purpose but could you check that the activity you're looking for in under the proper mode ?
