### ISSUE TITLE
Maintenance mode isn’t shown at Oauth login page

### ISSUE THREAD

**Issue by bondjw07** [Bungie-net/api#173]
As the title suggests, during maintenance we only see a message that says to select your platform, but no platforms are listed.  Confusing if you don't realize that maintenance going on.
![image](https://user-images.githubusercontent.com/5480627/30822153-d8f736c8-a1f5-11e7-9fed-9b4b4bf16040.png)

**Comment by ckhicks** [comment]
+100 on this.

**Comment by Tetron-bng** [comment]
This is fixed.
