### ISSUE TITLE
Ada-1 Hash Returning Not Found

### ISSUE THREAD

**Issue by dano1066** [Bungie-net/api#1735]
If i use the hash for banshee-44 my request works fine, so the query seems good. The [hash for Ada-1 is listed as 2917531897](https://www.light.gg/db/vendors/2917531897/ada-1/). So I have used this in the request but I get back a response to say its not a valid vendor. I have seen from the Xur thread that a vendor will return as not found when it does not currently exist in the world. Since Ada-1 is always in the tower, I don't understand why this would happen. She definitely exists in the games world. How come I can get back information about Banshee-44 but not Ada-1 when they exist in the same place?

`https://www.bungie.net/platform/Destiny2/2/Profile/4611686018468993418/Character/2305843009986524149/Vendors/2917531897?components=402,401,400`

```
{
    "ErrorCode": 1627,
    "ThrottleSeconds": 0,
    "ErrorStatus": "DestinyVendorNotFound",
    "Message": "The Vendor you requested was not found.",
    "MessageData": {}
}
```

**Comment by nev-r** [comment]
that's the Ada who sold black armory stuff. you want 350061650
