### ISSUE TITLE
Calling Profile for specific user results in ErrorCode 1618 : DestinyUnexpectedError

### ISSUE THREAD

**Issue by mikechambers** [Bungie-net/api#1738]
Calling:

https://www.bungie.net/Platform/Destiny2/1/Profile/4611686018434260916/?components=100,200

results in:

```
{"ErrorCode":1618,"ThrottleSeconds":0,"ErrorStatus":"DestinyUnexpectedError","Message":"An unexpected error has occurred on Bungie's servers while trying to grab Destiny information.","MessageData":{}
```

Checking other sites, it appears they are hitting same issue:

https://destinytrialsreport.com/report/1/4611686018434260916
https://destinytracker.com/destiny-2/profile/bungie/4611686018434260916/overview

Here are the response headers:

```
HTTP/1.1 500 Internal Server Error
date: Sun, 04 Dec 2022 17:40:29 GMT
content-type: application/json; charset=utf-8
content-length: 201
cache-control: private
expires: -1
vary: Origin
x-bungienext-mid2: 122
x-bungienext-renderer: Frog Blast the Ventcore
x-ua-compatible: IE=edge
x-ventcore-status: 1618
p3p: CP="ALL DSP COR PSD PSA TAI ADM CUR SAM OUR IND UNI COM INT CNT PRE"
access-control-allow-origin: https://destinytrialsreport.com
access-control-allow-credentials: true
x-selfurl: https://www.bungie.net/Platform/Destiny2/1/Profile/4611686018434260916/?components=1000
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
bnetlb: LB01
cf-cache-status: DYNAMIC
server: cloudflare
cf-ray: 774653d56818fa92-SJC
X-Firefox-Spdy: h2
```

**Comment by delphiactual** [comment]
https://twitter.com/BungieHelp/status/1595515590160306176?s=20&t=QR7Rs7weMwzTfO2YtTArSg

**Comment by mikechambers** [comment]
@delphiactual Yeah, I thought that issue had been resolved, which is why I logged this again.

**Comment by jshaffstall-bng** [comment]
Yeah sorry, there won't be a game-side fix to this until after the season 19 release, and probably not until Dec 13th.

The combination of timing (Thanksgiving, right before the next season), no game-side impact, and having an available workaround (log into the game with each other character) all contributed to this outcome.

Sorry again for the inconvenience!

**Comment by mikechambers** [comment]
@jshaffstall-bng Thanks for confirming. Sorry for the noise.

**Comment by mikechambers** [comment]
@jshaffstall-bng can you confirm whether this was ever fixed? Just need to know if I need to consider this as a possible situation that I need to account for in code.
