### ISSUE TITLE
Kiosk indexes not all returning

### ISSUE THREAD

**Issue by mattybeard** [Bungie-net/api#174]
Good day,

Playing about with the kiosk & vendor information but the kiosk part of GetProfile is not returning all the indexes.
The missing indexes appear to all be related to emblems bought or redeemed, rather than earned (i.e. Confluence Of Light).
My kiosk (MemberhipId: 4611686018431904749 [Xbox]) starts with 
"622587395": [
            {
              "index": 20,
              "canAcquire": true
            },
            {
              "index": 21,
              "canAcquire": true
            },
...
]

but I do have Confluence of Light, which is  "vendorItemIndex": 3

A second example of missing emblem is Emperor's Shadows which is again, a collectors edition emblem.

Happy to help provide more details if needed.

**Comment by vthornheart-bng** [comment]
Interesting, thank you for reporting this!

Do you find that you see them properly if you use the API while actively logged into the game?  Just out of curiosity.

**Comment by ArkahnX** [comment]
[Image of collections page](https://imgur.com/a/4DpDQ)

[Link to gist containing modified response from getProfile](https://gist.github.com/ArkahnX/f9d3a4103d2d44d0264fca8072255639) (I've added itemHashes to the profileKiosk response)

[Missing item references](https://gist.github.com/ArkahnX/47b47169739b934a5b0a71ca2a57de55) (names, hashes, and vendor index)

My guess is emblems redeemed via promo code aren't showing up in the API response for the profileKiosk. This doesn't seem to apply to emotes as those values match up with my in game collection.

**Comment by vthornheart-bng** [comment]
Ah, I believe I have found the root cause of this problem - thanks for reporting it!  We should have a fix in our next deployment in early November.
