### ISSUE TITLE
Regarding the primary `mode` on "Team Quickplay" and "Competitive" PGCRs

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1742]
Currently, matches played in these playlists have a `mode` which corresponds with the specific Crucible activity type. Unfortunately, this value is how the most important endpoint, Destiny2.GetActivityHistory, works (for the majority who can't run PGCR scrape farms!) to filter a player's activity history by.

Without setting the primary mode to the playlist mode, there's no way to distinguish between, for example, a friendly Rift game and a competitive Rift game.

So, if a dev builds a system based around DestinyActivityModeType, they end up in an awkward situation:

![image](https://user-images.githubusercontent.com/156681/206183686-f76f5a61-5855-478a-9eeb-d541c6b08512.png)

Without changes, it's now extremely difficult to see only "Team Quickplay" or "Competitive" activity history as it mixed in with other types of games.

![image](https://user-images.githubusercontent.com/156681/206184312-b1969b11-b06b-40d5-8fcc-db84776c6a7b.png)

**Comment by mikechambers** [comment]
Just for reference, this completely breaks the ability to view competitive matches in Redrix, as well as DARCI and dcli.

**Comment by jshaffstall-bng** [comment]
Sorry for the delay on these Competitive Crucible game history issues. The good news is that this should be a Bungie.net-only fix that applies retroactively, and we plan to ship in tomorrow (Friday) morning.

**Comment by mikechambers** [comment]
@jshaffstall-bng Any update on these? All of the comp issues don't appear to have been fixed yet. (i.e. wrong / missing mode data, no team data, etc...). (I can provide the exact bug #s if needed).

**Comment by justrealmilk** [comment]
For me, no rush if all the reports get regenerated 🤷🏼
