### ISSUE TITLE
New Competitive DestinyActivityDefinition manifest entry has isPvp incorrectly set.

### ISSUE THREAD

**Issue by mikechambers** [Bungie-net/api#1746]
Looking at the new DestinyActivityDefinition definitions for Competitive and Freelance : Competitive, isPvp is set to false. It should be set to true.

https://data.destinysets.com/i/Activity:2607135461
https://data.destinysets.com/i/Activity:2754695317

For reference, here is the previous competitive DestinyActivityDefinition:
https://data.destinysets.com/i/Activity:1481972458

which shows isPvp as true.

**Comment by jshaffstall-bng** [comment]
Sorry for the delay on these, hopefully we can ship a fix soon.
