### ISSUE TITLE
Am I allowed to save and serve images from the api on my server?

### ISSUE THREAD

**Issue by KaineDesign** [Bungie-net/api#1748]
Hallo there!

I want to work with destiny's api and create high performance applications with it.

For something like an item manager i woud have to send a request for every item image per user to bungie.net , thus putting a lot of stress on your end and at the cost of loading performance on my end.

i would love to cache / save images and other assets from bungie.net (links i can get through the api) at my end to avoid the issues above.

due to copyright and other possible permissions i dont know about, i wanted to ask if i am allowed to do so.

Thank you

**Comment by delphiactual** [comment]
the images are already cached via CF, and can change, filename, each deployment.

**Comment by Aryathel** [comment]
I currently cache images in memory for up to 60 minutes at max, just to avoid the need of fetching the same image again, even if it is cached on Bubgie's side. There are a few images outside of things like weapons and equipment that I actual save locally in addition to this. Things like class icons, energy type icons, and the little icon that shows next to "light" numbers.

**Comment by delphiactual** [comment]
so you are making a server side item manager? not client side?

**Comment by Aryathel** [comment]
Currently I am working on more of an item "viewer" that runs through a Discord bot, so it has to be server side.
