### ISSUE TITLE
ctype of Content.SearchContentWithText

### ISSUE THREAD

**Issue by ZxFrankxZ** [Bungie-net/api#1750]
What ctype exist?
I want to do requests to `Content.SearchContentWithText` but dont know what ctype exist.

And one more thing, how can i get the new Hotfix (6.3.x)?
For last hotfix/updates i was using this `https://www.bungie.net/Platform/Content/Search/es?ctype=News&searchtext=hotfix&currentpage=1` but dont show nothing for 6.3

**Comment by joshhunt** [comment]
They should add these to the documentation (or give a supported way to discover them), but I believe the possible values are

 - `destiny`
 - `bungie`
 - `tech`
 - `community`
 - `updates`
 - `none`

**Comment by Aryathel** [comment]
I believe `news` is also a valid ctype.

However, for getting hotfixes, I would recommend using the RSS feed endpoint. It was much more consistent for me, you just filter by "hotfix" being in the article title for the response.

**Comment by ZxFrankxZ** [comment]
> I believe `news` is also a valid ctype.
> 
> However, for getting hotfixes, I would recommend using the RSS feed endpoint. It was much more consistent for me, you just filter by "hotfix" being in the article title for the response.

Yeah, now i'm using RSS, in the past i dont use this because i dont know how to get the RSS in spanish but now i get a way thanks to people of the bungie api discord :)
