### ISSUE TITLE
`hasMore` attribute return true at the last page

### ISSUE THREAD

**Issue by Abdulhakiem** [Bungie-net/api#1760]
User.SearchByGlobalNamePost API has a weird issue, when searching for a global name and going to the last page of the response it returns `hasMore: true` even though there is no next page for this name
`
example:
search for the global name "shadow", the response of the last page (number 5) is:

`"Response": {
        "searchResults": [ ...
        ],
        "page": 5,
        "hasMore": true
    },`

when going to the next page it returns `ErrorCode: 217`

I don't know if this is an issue or not, or even someone else noticed it but I think it should be fixed

thanks in advanced

**Comment by ChaseMalik** [comment]
#1530
