### ISSUE TITLE
New Iron Banner game mode Fortress only appears under mode 91 in GetActivityHistory endpoint

### ISSUE THREAD

**Issue by ArkahnX** [Bungie-net/api#1761]
Sample api query: `Destiny2.GetActivityHistory?characterId=2305843009265193659&destinyMembershipId=4611686018435648983&membershipType=2&count=5&mode=0&page=0`

Modes 0 (None), 5 (AllPvP), and 19 (IronBanner) do not return the new Iron Banner game mode, but it does show up under mode 91 (IronBannerZoneControl)

Pulling up the PGCR shows that it only has mode 91 listed `GetPostGameCarnageReport?activityId=12191155278`

As mentioned by Mike and Tom, the modes array should be [5, 19, 91]
The activities are currently listed as the correct mode (91) but they are missing additional less specific modes

**Comment by mikechambers** [comment]
Just to be really clear modes should be:

[5, 19, 91]

and mode should be 91

**Comment by mikechambers** [comment]
This appears to still be broken after the Tuesday (Today) update.

https://stats.bungie.net/Platform/Destiny2/Stats/PostGameCarnageReport/12224674089

```
            "mode": 91,
            "modes": [
                19,
                91
            ],
```

Mode 5 should be included in Modes.

**Comment by jshaffstall-bng** [comment]
Yeah sorry, the fix for this was supposed to go live today, but now it looks like it'll wait to release until Wednesday, Jan 18th.

**Comment by mikechambers** [comment]
@jshaffstall-bng Thank you for the update. That is really helpful. And thank you for fixing the other issues retroactively. Really appreciate the work you all put into the API.

**Comment by mikechambers** [comment]
This appears to be fixed now:

https://stats.bungie.net/Platform/Destiny2/Stats/PostGameCarnageReport/12224674089

```
            "mode": 91,
            "modes": [
                5,
                19,
                91
            ],
```

Thank you!

**Comment by jshaffstall-bng** [comment]
Cool beans
