### ISSUE TITLE
Entries in Season of the Seraph redacted when they should be un-redacted

### ISSUE THREAD

**Issue by baxter** [Bungie-net/api#1763]
Hello!

It looks like the following lore is available in-game but not in the API.

- Hunter Armor
  - Warmind's Avatar Mask
  - Warmind's Avatar Vambraces
  - Warmind's Avatar Vest
  - Warmind's Avatar Legguards
  - Warmind's Avatar Cloak
- Titan Armor
  - Warmind's Avatar Legplates
- Warlock Armor
  - Warmind's Avatar Headpiece
  - Warmind's Avatar Gloves
  - Warmind's Avatar Robes
  - Warmind's Avatar Pants
  - Warmind's Avatar Bond
- Persona Lore Book
  - Identity
  - Ana
  - First Fear
  - Lone
  - Filicide Ellipses
- Other
  - Archangel's Refit (Sparrow)
  - Dawn Chimes Shell
  - Disparity
  - Fire and Forget
  - Gallant Ward Shell
  - Infiltrator Shell
  - Intercepted Transmission (Sparrow)
  - Judgement of Kelgorath
  - Path of Least Resistance
  - Retrofit Escapade
  - Revision Zero
  - Spirit of the Warmind (Ship)
  - Tripwire Canary
  - Warsat Shell

Thanks!

**Comment by jshaffstall-bng** [comment]
Thanks for the list! I think these should all be unredacted on Tuesday, Jan 10th.

**Comment by baxter** [comment]
Perfect, thank you!
