### ISSUE TITLE
ErrorCode 8 on IndividualGroupInvite endpoint

### ISSUE THREAD

**Issue by soares-daniel** [Bungie-net/api#1764]
Hi I have an issue with the IndividualGroupInvite endpoint. Here is my code:
       

        payload = {
            "GroupApplicationRequest": {
                "message": "",
            }
        }

        headers = {
            "X-API-Key": BUNGIE_API_KEY,
            "Authorization": f"Bearer {admin_token['access_token']}"
        }

        response = requests.post(url=url, json=payload, headers=headers)
        response = response.json()

It worked before when inviting users but now it gives me the error:

`{'ErrorCode': 8, 'ThrottleSeconds': 0, 'ErrorStatus': 'ParameterInvalidRange', 'Message': 'One or more parameters are outside the range of valid values.  Please correct them, and try again.', 'MessageData': {}}`

I already tried `{message: ""}` and so on but still get the same error...
Does anyone have any other suggestions?

**Comment by soren42** [comment]
Is it this spare "f" in your code? 😏![image](https://user-images.githubusercontent.com/326903/211101021-f2852af6-0974-411e-9e08-483042b0f5ee.jpeg)

**Comment by soares-daniel** [comment]
> Is it this spare "f" in your code? 😏![image](https://user-images.githubusercontent.com/326903/211101021-f2852af6-0974-411e-9e08-483042b0f5ee.jpeg)

Maybe I should have mentioned it but it is written in python and that is not a spare "f" but used for formatting strings.

**Comment by soren42** [comment]
Ah, sorry.  My Python is quite rusty, so it looked like a syntax issue being outside the "".

I'm happy to independently test the endpoint for you, but it won't be until I'm home several hours from now.  Hopefully, someone else will have some insights before then.

Good luck!
