### ISSUE TITLE
Error 1665 DestinyPrivacyRestriction on PGCRs

### ISSUE THREAD

**Issue by CrunchyWizard47** [Bungie-net/api#177]
Probably a dumb question, but I'm running into this while scanning through my clan's PGCRs; I don't know where to find this setting to tell the clan member how to change it. Anybody know?

**Comment by delphiactual** [comment]
bungie.net, user icon, settings, privacy

**Comment by CrunchyWizard47** [comment]
Awesome, thank you delphiactual!
