### ISSUE TITLE
Tripwire Canary crafted InventoryItemDefinition 'itemType' incorrectly set to 0 instead of 30

### ISSUE THREAD

**Issue by rslifka** [Bungie-net/api#1774]
https://data.destinysets.com/i/InventoryItem:2287240026

**Comment by delphiactual** [comment]
you are looking at the wrong itemhash

https://data.destinysets.com/i/InventoryItem:3849444474

**Comment by rslifka** [comment]
Every item with a `crafting` node has `itemType:30` (Pattern) except for the Tripwire Canary that I linked. You're saying that's not an issue?

**Comment by delphiactual** [comment]
actually it looks like all weapons from this season that are craftable are missing the Pattern ICH

Paste this into the console for data.destinysets.com
`$InventoryItem.filter(v => v.crafting && !v.itemCategoryHashes.includes(3726054802)).show()`

**Comment by rslifka** [comment]
I had no idea destinysets could do that!! I've written so many Ruby scripts to answer questions like this 😅 Thanks!!
