### ISSUE TITLE
Need help with getting perks for weapon tooltip

### ISSUE THREAD

**Issue by niklod** [Bungie-net/api#1776]
Hi there! I'm trying to reproduce in-game weapons tolltip. Especially for exotic weapons.  
Exotic weapons has two perks in tooltip.  
All that I have managed to collect so far is a curated roll. Question is how to grab two special perks from that roll? (Represented on screenshot)

![image](https://user-images.githubusercontent.com/50237145/214003594-1cb281e4-03f2-4d5c-85b2-ae134fd0412c.png)

For example, weapon 2357297366 (WITHERHOARD) has curated roll like:
1. PRIMEVAL'S TORMENT
2. COUNTERMASS
3. BLACK POWDER
4. BREAK THE BANK
5. COMPOSITE STOCK

How are PRIMEVAL'S TORMENT and BREAK THE BANK selected from API?

**Comment by konradgithuup** [comment]
Hi,
To find the "special perks" you need to go over each perk definition and determine what type of perk you are looking at. Below is a table showing different perk properties you could use on the example of Witherhoard:

| Perk | itemTypeDisplayName | itemCategoryHashes |
|---|---|---|
| Primeval's Torment | "Intrinsic" | [Weapon Mods: Intrinsic, Weapon Mods, Mods] |
| Countermass | "Launcher Barrel" | [Weapon Mods: Launch Tubes, Weapon Mods, Mods] |
| Black Powder | "Magazine" | [Weapon Mods:  Magazines, Weapon Mods, Mods] |
| Break the Bank | "Trait" |[ Weapon Mods: Frame, Weapon Mods, Mods] |
| Composite Stock | "Stock" | [Weapon Mods: Stocks, Weapon Mods, Mods] |

If you use the `itemTypeDisplayName` you are looking for "Intrinsic" denoting an intrinsic perk and "Trait" denoting a main perk (like Kill Clip, Rampage, etc; perks you'd find in the 3rd and 4th column on the average legendary weapon or unique perks on an exotic)
