### ISSUE TITLE
User.SearchByGlobalNamePost - Receiving of pageResults based on prefix not working

### ISSUE THREAD

**Issue by cweinwurm** [Bungie-net/api#1778]
Hi, I am trying to implement an inputView for my app where the user starts entering the desired display name and I would like to provide some suggestions during typing by using the endPoint above. The documentation of the endpoint says `Given the prefix of a global display name, returns all users who share that name.`?! What is then the definition of `prefix`?

So atm I am just receiving results when I enter a complete display name, should it work only this way? Or should it provide some kind of auto completion functionality by providing paged results based on user input?

Br, Chris

**Comment by Aryathel** [comment]
I believe in this case the "prefix" of a global display name could be considered the part that comes before the `#`. While the complete "global display name" might look like `Aryathel#7877`, and "prefix" would be `Aryathel`. So in this case, this endpoint is really intended as a case insensitive way to search Bungie users by their text name. I can see where the mixup could be made though.
