### ISSUE TITLE
Potential erroneous emblems returned by the API

### ISSUE THREAD

**Issue by benedfit** [Bungie-net/api#178]
The below 9 emblems, which all share names with the D1 class emblems, are returned via the API. Some of them appear to be erroneous in the fact that they share images. Are you able to confirm if whether they are entirely erroneous, or whether it's just a case of the wrong images being returned

![screen shot 2017-09-27 at 11 40 46](https://user-images.githubusercontent.com/580859/30909396-d3cc2756-a378-11e7-9e3e-21f83e88759a.png)

**Comment by vthornheart-bng** [comment]
Hmm, I'll have to look into it!

**Comment by vthornheart-bng** [comment]
These do appear to be technically valid items in that they actually exist in the game data, and as far as I can tell this is their real content.  Whether you can actually earn them in the game is another thing - and just on a cursory look it appears that they're not earnable.  I'm pretty certain that they are debris from someone doing testing or internal design experimentation and who never cleaned up after themselves!  You can see a few similar things in other areas, particularly sections like Activities and Activity Graphs where there are many test/experiment nodes that don't actually point to real things.  They are the leftover refuse of designer experiments that never got fully cleaned up.
