### ISSUE TITLE
Getting a weapons season/source

### ISSUE THREAD

**Issue by chushaa** [Bungie-net/api#1781]
Hello!

Have a quick question here!

I am creating a local application to track my clan members and I crafted weapon progress and storing it in a graphical desktop application. I'm looking to find either what season a weapon comes from(i.e. calus mini tool is from season of the haunted vs ikelos smg 1.0.3 is from season of the sereph) or a weapons source (cataclysmic being from vow of the deciple while heritage is from deep stone crypt). Is there a proper way to access a value like that? Closest I've been able to get is from the requirements.entitlementunavailablemessage getting me a string such as "requires Destiny 2 season 17" in thr DestinyRecordDefiniton endpoint of the Manifest

Thanks!

**Comment by niklod** [comment]
You can find source trought `collectibleHash` relation.
For example Funnelweb (3341893443) has `collectibleHash` as `3247834922`. You can find this collectible in `DestinyCollectibleDefinition` table.  It will contain `sourceString` field with `Source: Open Legendary engrams and earn faction rank-up packages.`

**Comment by iamorlovsky** [comment]
But is it possible to see during what season the item was introduced?

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/d2ai-module/blob/master/seasons.json
https://github.com/DestinyItemManager/d2ai-module/blob/master/watermark-to-season.json
