### ISSUE TITLE
Activity additions to GetActivityHistory response

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1782]
Two requests:
1. Would it be possible to add Shattered Throne to the activity history endpoint under `DestinyActivityModeType.Dungeon`? The activity itself is wired up as a story but it's the only exception to the response for dungeons so I just had to ask
2. Similarly for Lost Sectors (`DestinyActivityModeType.LostSector`), activities which occurred before the mode type was added to the API are omitted from the response.

I know it's unlikely that it would be as easy as adding some hashes to a list but please keep in mind that most consumers of the API can't do a Trials Report and crawl every PGCR with which to power a private API! You could also make the argument that the endpoint's usefulness is diminished due to its incompleteness. 

Ty

**Comment by jshaffstall-bng** [comment]
I believe I saw that Shattered Throne is changing to be a proper Dungeon in Lightfall content, but I'll have to double-check.

And I don't think it's feasible for ye olde Legend and Master Lost Sector activities from before the mode type change to get cleaned up, sorry.
- Sometimes the game history bug fixing can be retroactive, if the game-side data is good but the Bnet-side is misconfigured.
- We haven't gone back to correct game-side activity history data after bugs get fixed there, and while I won't say it's impossible, I don't think it's a risk we're willing to take unless there's a really compelling case for it.
