### ISSUE TITLE
Higher resolution icons

### ISSUE THREAD

**Issue by dano1066** [Bungie-net/api#1783]
I see that there is a high res icon property inside most display objects but its frequently blank. The icon is always set but the icons are 98x98 and look quite ugly when they are larger. Is there any way to obtain a larger version using the hash or something or is 98x98 all there is for a lot of records? I am specifically talking about things like mods, weapons and armor.

**Comment by jshaffstall-bng** [comment]
Unfortunately, the 96x96 icons available for most items is the same resolution used by the game, so we don't have a good way to offer higher-resolution icons for these.

The 'highResIcon' is specifically for Eververse sale item tile displays.
