### ISSUE TITLE
How to determine if a raid activity was started from the beginning and was completed flawlessly?

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1784]

**Comment by Cr3aHal0** [comment]
@justrealmilk IIRC there are two flags on PGCR entity :
- startingPhaseIndex starting at 0 (apparently only reliable for activities launched before Witch Queen, read the doc on the matter)
- activityWasStartedFromBeginning which is a boolean but only usefull for activities post Witch Queen

Hope it helps :)
