### ISSUE TITLE
Sailspy Pitchglass missing from Collections

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#1786]
Sailspy Pitchglass isn't one of the collectibles in the Linear Fusion Rifles node: https://data.destinysets.com/i/PresentationNode:690633563

**Comment by nev-r** [comment]
to be fair this is the case in-game too
![image](https://user-images.githubusercontent.com/68782081/218932105-a875be7c-3c2d-4836-9d03-9254e6f9729d.png)
