### ISSUE TITLE
A little help for a newb

### ISSUE THREAD

**Issue by kingram6865** [Bungie-net/api#1788]
I'm accessing this endpoint `https://www.bungie.net/Platform/Destiny2/1/Profile/24300038?components=PROFILES`
and the response is 
{
      ErrorCode: 18,
      ThrottleSeconds: 0,
      ErrorStatus: 'InvalidParameters',
      Message: 'The input parameters were invalid, please enter valid input, and try again.',
      MessageData: [Object]
}

What am I missing here?

**Comment by KaineDesign** [comment]
Hey there,

like the "Message"-field tells you, your parameters are invalid. I think you confused the "destinyMembershipId". You can find the right ID in the response JSON (`Response.profile.data.userInfo.membershipId`) of this endpoint:
`https://bungie-net.github.io/#Destiny2.SearchDestinyPlayerByBungieName`

Beware to use a POST request with a request body like:
```json
{
    "displayName": "YOURNAME",
    "displayNameCode": 1234
}
```

Where did you get the id from?

**Comment by kingram6865** [comment]
I got the id from `https://www.bungie.net/Platform/User/GetMembershipsById/${userId}/254`

**Comment by kingram6865** [comment]
I found an older reference to membership id (2017 https://www.bungie.net/en/Forums/Post/231976065?sort=0&page=0 ) 

Using that solution I'm trying this link
https://www.bungie.net/Platform/Destiny2/3/Profile/4611686018514174613/?components=100

The response:
```
data: {
      ErrorCode: 1601,
      ThrottleSeconds: 0,
      ErrorStatus: 'DestinyAccountNotFound',
      Message: 'We were unable to find your Destiny account information.  If you have a valid Destiny Account, let us know.',
      MessageData: {}
    }
```

**Comment by KaineDesign** [comment]
> You can find the right ID in the response JSON (`Response.profile.data.userInfo.membershipId`) of this endpoint: `https://bungie-net.github.io/#Destiny2.SearchDestinyPlayerByBungieName`

**Comment by kingram6865** [comment]
Thanks. That worked. I had to go through the Stadia account to get info.
With Stadia no longer available I thought it was not viable, but that's how I started playing.
