### ISSUE TITLE
Shaping Date objective def showValueOnComplete is a little weird

### ISSUE THREAD

**Issue by nev-r** [Bungie-net/api#1789]
https://data.destinysets.com/i/Objective:3947811849

this is a unix date so its `progress` value looks a little something like this:
`1676895809190`

so: `completionValue:1`
sure. fine. it's arbitrary because you can't complete a date.
this makes the objective always look "completed" unless the weapon was crafted before 1970.
that's fine.

`allowOvercompletion:true` this makes sense because the number has to go higher than it completion value.
again, that's barring the possibility of time travel.

however:
`showValueOnComplete:false`
mmmmmm, but these look complete. in fact, the API sends their live data back as
`"complete": true`
if the shaping date should **never** be shown, shouldn't it be set to hidden?
and if it **should** be shown, shouldn't it be shown even when "complete"?

this is probably back end game data and nothing can be done here but it's a weird value and felt like the quirk should be documented

**Comment by jshaffstall-bng** [comment]
I think this comes down to the Crafting system being 'special' in general, and having custom UI for how these objectives are displayed in the game UI.

Ultimately, I think you can ignore most of the usual flags on the Crafting objective definitions, and try to match what the game UI goes instead.
