### ISSUE TITLE
ActivityHistory for trials no longer working

### ISSUE THREAD

**Issue by rale** [Bungie-net/api#179]
GetActivityHistory no longer works on mode 39.   Doesn't return anything on the new modes 41 or 42 either.

Side note, I saw 43/44/45 were added for each iron banner mode.  Will there be a combined iron banner mode for listing all 3 as well?

**Comment by v-fedorov** [comment]
PGCR for trials matches is broken as well #180
Could be related

**Comment by vtubelsky** [comment]
Sorry I just posted a duplicate issue about the same problem. Will appreciate any help with this.

**Comment by vtubelsky** [comment]
Trials games are back but they now have mode 41 and 42 instead of 39.

Some instanceId examples:
573828810
573679926
671532860
671264779

They have modes=[5, 39, 41] or [5, 39, 42] and mode=41 or 42.

**Comment by floatingatoll** [comment]
Are modes 41 and 42 "Trials - Game Type One" and "Trials - Game Type Two"?

**Comment by vtubelsky** [comment]
Yes, seems like 41 is Countdown and 42 is Survival, though they are not defined in DestinyActivityModeType.

> Are modes 41 and 42 "Trials - Game Type One" and "Trials - Game Type Two"?

**Comment by azazael13** [comment]
39 is giving information again as well.  my guess is 39 is all of trials wrapped into one, 41 is Countdown, and 42 is Survival.

**Comment by vthornheart-bng** [comment]
Hmm, were the DestinyActivityModeDefinitions for those not coming through?  Indeed, they should all have their own Activity Modes now and aggregated together into the trialsCountdown as azazael mentioned.  I think it should be good to go now - I see the definitions in the latest content.  Let me know if you're still experiencing issues!

**Comment by vthornheart-bng** [comment]
Oh, it's the documentation that doesn't have them - I totally dropped the ball on that.  I have not re-published the documentation since I made it back home.  I can't publish it tonight, but I will get it published on Monday.  My apologies!
