### ISSUE TITLE
difference between similar DestinyInventoryItemDefinition entrys

### ISSUE THREAD

**Issue by KaineDesign** [Bungie-net/api#1790]
Greetings,

can you guys tell me what the difference between those two items is?

https://data.destinysets.com/i/InventoryItem:1245809812
https://data.destinysets.com/i/InventoryItem:193869522

All I could imagine is, that the "1245809812" one could be from before armor 2.0 patch.
Anyway, if I want to display perks, descriptions, mod slots and other metadata, which one should I pick and how can I distinguish between them.

Thank you!

**Comment by jshaffstall-bng** [comment]
Sorry for the confusion, as there are many seemingly 'duplicates' of various inventory item definitions, for many various reasons.

In this case, it looks like 1245809812 is the 'original' version from the initial Destiny 2 release, and 193869522 is the Armor 2.0 version from Shadowkeep.

**Comment by KaineDesign** [comment]
@jshaffstall-bng all good. Thanks for the answer! Thought so. Is there an intended way to distinguish between them?
