### ISSUE TITLE
EquipLoadout API should return updated items

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#1792]
For applications like DIM, which update an internal model from action responses, it'd be great if `equipLoadout` would return an updated `DestinyItemResponse` for each item involved in the loadout, giving the updated mod state. We can simulate this, but since we already have code for handling the response from `insertSocketPlugFree`, it'd be easy to hook it up to a response like this and would leave room for the API to make "surprising" side-effect changes as part of applying loadouts.

**Comment by jshaffstall-bng** [comment]
I agree that it would definitely be better for the Loadout API write actions to return the actual saved Loadout state and equip results / failures.

Filed as TFS 1172342, but I don't have an ETA on when we would prioritize this.

**Comment by bhollis** [comment]
This would still be very helpful
