### ISSUE TITLE
Lightfall: Neomuna checklists

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1794]
Usual suspects
- Add the 3 new lost sectors to the lost sectors checklist
- Add the 9 new region chests to the region chests checklist

Potential candidates
- 9 "unique action figures" - "They're Not Dolls" record
  - basically the same as the last 3 expansions
- Apogee Repeaters - "Strange New Heights" record
  - each of these has 3 components for each "repeater"/location

**Comment by jshaffstall-bng** [comment]
Filed as TFS 1172341

**Comment by justrealmilk** [comment]
Completed
