### ISSUE TITLE
Plugsets missing singleInitialItemHash in the plug set 

### ISSUE THREAD

**Issue by D217696** [Bungie-net/api#1798]
heres an example: 
socketEntries -> index 11, as you can see the singleInitialItemHash isnt listed in the reusablePlugItems (instead its plugItemHash 4173924323)
https://data.destinysets.com/i/InventoryItem:587312237/PlugSet:4285066582
https://data.destinysets.com/i/InventoryItem:587312237
seems to affect all of these armor pieces (artifice)
[
    145651147,
    286271818,
    399065241,
    420895300,
    436695703,
    498918879,
    587312237,
    708921139,
    833653807,
    1148597205,
    1349399252,
    1756483796,
    1951355667,
    2057955626,
    2244604734,
    2341879253,
    2499351855,
    2565015142,
    2649394513,
    2663987096,
    2694773307,
    2724719415,
    2797334754,
    2819810688,
    2885497847,
    2935559305,
    3048458482,
    3171090615,
    3260781446,
    3267969345,
    3270955774,
    3326914239,
    3344225390,
    3511740432,
    3685276035,
    3715136417,
    3870375786,
    3871537958,
    3933500353,
    3946384952,
    4039955353,
    4047213660,
    4050474396,
    4177293424,
    4288623897
]

**Comment by robojumper** [comment]
My recommendation: *Never* trust the `singleInitialItemHash`. If you need an "empty" plug for purposes of resetting a socket, DIM has some significant logic to correctly identify the empty plug https://github.com/DestinyItemManager/DIM/blob/b9ea013803131eb6d58bfd1e9eb39cd7c9107d87/src/app/inventory/store/sockets.ts#L517-L595
