### ISSUE TITLE
Spelling errors in Destiny.Definitions.Milestones.DestinyMilestoneType

### ISSUE THREAD

**Issue by ArkahnX** [Bungie-net/api#18]
Another case of rogue spacebars!

**Tutorial: 1**
One-time milestones that are specifically oriented toward teaching players about new mechanics and gameplay modes.

**Weekly: 3**
Milestones that repeat/reset on a weekly basis. They need not all reset on the same day or time, but do need to reset weekly to qualify for this type.

**Special: 5**
Special indicates that the event is not on a daily/weekly cadence, but does occur more than once. For instance, Iron Banner in Destiny 1 or the Dawning were examples of what could be termed "Special" events.

**Comment by vthornheart-bng** [comment]
Thanks for taking a look at these!  I'll mark these issues as bugs.  Admittedly, its hard to see here what the difference is - I'll have to do a diff.

**Comment by ArkahnX** [comment]
Sorry for that! Since the json files are auto generated I didn't want to pull against those as I assumed it would make more work.

My Hope was that somewhere down the line these could be copy/pasted back into the source, but let me know if there is a format that works better for you!

**Comment by vthornheart-bng** [comment]
Hmm, I'm not entirely certain either what the best course of action would be.  I think it'd be okay if you want to pull: because of the codegen we won't bring the pull in, but it could be useful at least for being able to see diffs!  If someone has a better suggestion, I'm all ears: otherwise, I'd be fine with that approach!

**Comment by floatingatoll** [comment]
This would be a terrific use for diffs, as I’d like to review them too (for fun!).

**Comment by hellocontrol-bng** [comment]
Merged with https://github.com/Bungie-net/api/issues/20
