### ISSUE TITLE
Add 'Focused Decoding' Vendors to Vendor Sales response

### ISSUE THREAD

**Issue by afpac** [Bungie-net/api#1804]
As of Lightfall, Focused Decoding options from Saint-14 and other vendors are now rolled up into sub-vendors:

```
683678992 	crucible
654952868 	gambit
502095006 	trials
3388267042 	iron banner
2232145065 	vanguard
```

Unfortunately, these vendors are not appearing in a Profile request with components 400,401,402 requested. The standard vendors that these sub-vendors belong to all populate as normal and show their Focused Decoding item (that you can then follow the previewVendorHash to get to the above list), but that's where the party ends.

It would be great to be able to see what's available from these sub-vendors in order to be able to pull what the weekly Adept is for Trials and Nightfall purely through the API. 

It's also currently kind of confusing in tools like DIM to click on the Focused Decoding option under a vendor and it just show everything that's possible under there. Without being able to see what the vendor is actually selling that week, I'm not sure how they'll be able to make it any less confusing without manual intervention every week.

**Comment by jshaffstall-bng** [comment]
Good catch, I think we can add these with new Bnet content next week.

**Comment by afpac** [comment]
Thanks for this - working great as of today's API update!
