### ISSUE TITLE
Recorded subclass data at end of activity?

### ISSUE THREAD

**Issue by FelixJochems** [Bungie-net/api#1808]
I'm currently indexing class usage for raids and other higher level content and I can find which class they're playing but not the subclass. I saw the subclass is technically an item that is equipped but can't find historical data for let's say world's first raids. Is this data available or is this not publicly disclosed?

If this is available I'm sorry in advance for not finding it.

**Comment by nsmith31415** [comment]
I've been looking into something similar recently. As far as I'm aware there's not historical data for loadouts/equips/etc in an activity
