### ISSUE TITLE
Entries from Season of the Seraph and Lightfall redacted when they should not be redacted

### ISSUE THREAD

**Issue by baxter** [Bungie-net/api#1810]
The following entries from Season of the Seraph and Lightfall are redacted, but are available in-game and should not be redacted.

* Persona
  * - (https://data.destinysets.com/i/Lore:4114501650)
  * - (https://data.destinysets.com/i/Lore:4114501661)
* Cloud Strider Legacies
  * The Stargazer (https://data.destinysets.com/i/Lore:3935354265)
  * Laminak Li (https://data.destinysets.com/i/Lore:3935354266)
  * The Bluejay (https://data.destinysets.com/i/Lore:3935354267)
  * Conrad Jain (https://data.destinysets.com/i/Lore:3935354268)
  * The Maelstrom (https://data.destinysets.com/i/Lore:3935354269)
  * Sedderik Assur (https://data.destinysets.com/i/Lore:3935354270)
  * The Strider (https://data.destinysets.com/i/Lore:3935354271)
  * Mikaela Julaha (https://data.destinysets.com/i/Lore:3935354256)
* Guardians and Ghosts
  * What It Means... (https://data.destinysets.com/i/Lore:1871947245)
  * A Guardian's Best Friend (https://data.destinysets.com/i/Lore:1871947246)
  * The Traveler (https://data.destinysets.com/i/Lore:1871947247)
* Last Days
  * Mr. Che (https://data.destinysets.com/i/Lore:2164211400)
  * Sehrish (https://data.destinysets.com/i/Lore:2164211403)
  * Tino (https://data.destinysets.com/i/Lore:2164211402)
  * Cais (https://data.destinysets.com/i/Lore:2164211405)
  * Adinew (https://data.destinysets.com/i/Lore:2164211404)
  * Magnolia (https://data.destinysets.com/i/Lore:2164211407)
  * Rihk (https://data.destinysets.com/i/Lore:2164211406)
  * Gwinnith (https://data.destinysets.com/i/Lore:2164211393)
  * Hazeema (https://data.destinysets.com/i/Lore:2164211392)
  * Phot0n (https://data.destinysets.com/i/Lore:3654276328)
* Warp and Weft
  * Strand Log I (https://data.destinysets.com/i/Lore:1729973944)
  * Carding (https://data.destinysets.com/i/Lore:1729973947)
  * Strand Log II (https://data.destinysets.com/i/Lore:1729973946)
  * Roving (https://data.destinysets.com/i/Lore:1729973949)
  * Strand Log III (https://data.destinysets.com/i/Lore:1729973948)
  * Spinning (https://data.destinysets.com/i/Lore:1729973951)
  * Strand Log IV (https://data.destinysets.com/i/Lore:1729973950)
  * Weaving (https://data.destinysets.com/i/Lore:1729973937)

**Comment by jshaffstall-bng** [comment]
Thanks for this list! I think we can unredact these with new Bnet content on Thursday.

**Comment by baxter** [comment]
Thanks @jshaffstall-bng ! There may be a few more available now but I wanted to post this before I forgot. I'll update the list if I confirm any others.

**Comment by jshaffstall-bng** [comment]
Most, if not all, off these should be unredacted as of today.
