### ISSUE TITLE
I'm a bit lost when it comes to membership types

### ISSUE THREAD

**Issue by LuMiSxh** [Bungie-net/api#1811]
Title. 
I fetched my profile using the api and I'm now trying to retrieve some character components but I dont know what membership type to use (I have all platforms linked to my bungie account via cross-save and this is reflected in the api request for my user profile). I've tried every single one but always get a response like the following:
`{"ErrorCode":18,"ThrottleSeconds":0,"ErrorStatus":"InvalidParameters","Message":"The input parameters were invalid, please enter valid input, and try again.","MessageData"{"membershipType":"TigerSteam","membershipInfo.membershipType":"BungieNext","membershipId":"23327300"}}`

My biggest problem is that in the most resources I've found the api gives you a membership type with the request for your profile information but thats not the case.
Here is the data from fetching my user profile:
```
    "Response": {
        "membershipId": "23327300",
        "uniqueName": "Drageast#7432",
        "displayName": "Drageast",
        "profilePicture": 70637,
        "profileTheme": 1136,
        "userTitle": 0,
        "successMessageFlags": "0",
        "isDeleted": false,
        "about": "",
        "firstAccess": "2019-10-19T09:45:34.324Z",
        "lastUpdate": "2023-03-10T23:30:12.573Z",
        "context": {
            "isFollowing": false,
            "ignoreStatus": {
                "isIgnored": false,
                "ignoreFlags": 0
            }
        },
        "psnDisplayName": "LuMiSxh",
        "xboxDisplayName": "Drageast",
        "showActivity": true,
        "locale": "de",
        "localeInheritDefault": true,
        "showGroupMessaging": true,
        "profilePicturePath": "/img/profile/avatars/cc06.jpg",
        "profileThemeName": "d2_36",
        "userTitleDisplay": "Newbie",
        "statusText": "",
        "statusDate": "0001-01-01T00:00:00Z",
        "steamDisplayName": "Drageast",
        "stadiaDisplayName": "Drageast#5449",
        "cachedBungieGlobalDisplayName": "Drageast",
        "cachedBungieGlobalDisplayNameCode": 7432
   }
```
If needed I can provide more information.

**Comment by delphiactual** [comment]
https://discord.gg/d3v29pgmry join the API discord
