### ISSUE TITLE
Lost Sector activity definitions report incorrect activity modifiers

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1815]
# Specific example: Thrilladrome says it's Solar, Strand, **and Void** Surge when in game it is only the first two of the three.

**Comment by nev-r** [comment]
no those 3 are all possible (and therefore *must* be on the definition) and live data (if it were available for LLS) would show which two are active

**Comment by justrealmilk** [comment]
I am yet to see void surge active @nev-r

**Comment by nev-r** [comment]
it has been void every other week this season, it matches whatever is the surge on nightfalls

**Comment by nev-r** [comment]
it is void right now
![image](https://user-images.githubusercontent.com/68782081/229972480-29575c13-1fe9-4282-857f-33243568b5b5.png)
