### ISSUE TITLE
Strand missing from DestinyEnergyType

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1819]
https://bungie-net.github.io/multi/schema_Destiny-DestinyEnergyType.html#schema_Destiny-DestinyEnergyType

Also missing from DestinyEnergyTypeDefinition

**Comment by nev-r** [comment]
there is no strand energy type

**Comment by justrealmilk** [comment]
Update the type and def for completeness or remove all unused values. I will not compromise on this @nev-r.

**Comment by nev-r** [comment]
completeness is not am appropriate concept here. completeness covers what exists. strand energy does not.

**Comment by Apoc101** [comment]
armor 2.0 does include strand as well now that lightfall releases, and with Stasis in there it would only make sense to include Strand. please fix
