### ISSUE TITLE
Clan Leaderboard Stats endpoint is returning "disabled for maintenance" error

### ISSUE THREAD

**Issue by vpzed** [Bungie-net/api#182]
The /Stats/Leaderboards/Clans/ endpoint is returning an error like it was not switched back on after the maintenance on Monday.  I've tried it with multiple clan groupIds and query parameter options and always get the same result as shown below.

    https://www.bungie.net/Platform/Destiny2/Stats/Leaderboards/Clans/80491/?maxtop=5&modes=5

    {
      "ErrorCode": 5,
      "ThrottleSeconds": 0,
      "ErrorStatus": "SystemDisabled",
      "Message": "This system is temporarily disabled for maintenance.",
      "MessageData": {}
    }

**Comment by vthornheart-bng** [comment]
Oops, closed the wrong one - we'll use this one to track it.

**Comment by Tetron-bng** [comment]
This will be enabled next week.
