### ISSUE TITLE
Question: How to get a list of (ideally recent) activities that are all one type (Ex. Just raids, just dungeons, etc..)

### ISSUE THREAD

**Issue by nsmith31415** [Bungie-net/api#1820]
I'd like to sift through specific recently-completed activities. Whether that be sorted by type (raid/dungeon/nightfall/etc) or by activity name (Root of Nightmares, Vow of the Disciple, Spire of the Watcher, The Arms Dealer, etc...) would be helpful. 

The best way I can do that so far (to my knowledge) is to simply loop through activities based on their ID and then check what activity it was. That requires several API calls per raid/dungeon - activity I'm interested in. I would like to only need to send one request to get a list of activities I'm interested in, and then one request per activity to get the additional details. Is this possible? Possible in the future? If this isn't something I can do now, is it possible if I learn the openAI details on the [README](https://github.com/Bungie-net/api#swaggeropenapi-specs-or-how-to-generate-your-own-clients-for-the-bnet-api)?

Any advice is greatly appreciated!

**Comment by nsmith31415** [comment]
After reading [this issue](https://github.com/Bungie-net/api/issues/1017#issuecomment-525928951), it seems like the activity IDs aren't generated until several minutes after activity completion, which counteracts the use I'm looking for. 

Is there a better way to access guardian info mere seconds after they complete an activity?

**Comment by Mijago** [comment]
No, sadly you have to wait.

The only Info you can get right away is https://bungie-net.github.io/multi/schema_Destiny-Components-Profiles-DestinyProfileTransitoryComponent.html#schema_Destiny-Components-Profiles-DestinyProfileTransitoryComponent, which you get from the GetProfile endpoint.

**Comment by nsmith31415** [comment]
Any chance you know how to get the membership ID from the display name? I've seen applications that do this, like https://raid.report, but I haven't figured out what they're doing to convert that display name into bungie membership ID

**Comment by Mijago** [comment]
Raid report has their own elastic api that solves it for them, even with 

There's a Bungie endpoint, but as far as I know you need to know the entire name, including the #1234 part.

Probably this one: https://bungie-net.github.io/multi/operation_post_Destiny2-SearchDestinyPlayerByBungieName.html#operation_post_Destiny2-SearchDestinyPlayerByBungieName

(currently on my phone).

Check out https://data.destinysets.com - they have an api browser to play around with :)

**Comment by nsmith31415** [comment]
Do you know how to grab someone's current subclass information? (Current subclass, aspects, fragments, etc) I haven't been able to find the right API endpoint to call for this. I was able to access the "Loadouts" information through the get profile/get character endpoint, but I was only receiving information about the armor equips. Nothing about the subclass info.

**Comment by levscaut** [comment]
I encounter this bug again. Could anyone check if this bug happens again? the path i query: https://www.bungie.net/Platform/Destiny2/3/Account/4611686018491983000/Character/2305843009521296002/Stats/AggregateActivityStats/
