### ISSUE TITLE
This week in Destiny proves the characters are unbalanced. 

### ISSUE THREAD

**Issue by WhyIsBungieNotDoingThis** [Bungie-net/api#1823]
Titans need a nerf, and in the same respect hunters need more. My suggestion is to nerf the movement speed of the titan to make them feel more tankish. Hunters need the ability to feel more agile, evasive, and true invisible. It is extremely annoying to be a hunter have over 100 mobility and still be out manuved by both titans and warlocks. The dodge is just an opening for anything to auto track and kill you. Being invisible is a joke and needs to be better. The enemies in PVE have better invisibility. Lastly, when will hunters get a one hit killing melee?

**Comment by jshaffstall-bng** [comment]
Cool story bro

**Comment by D217696** [comment]
Try hitting the `GetProfile` endpoint with the components 205, 300 and 305 and are you adding a valid api key to your request?
