### ISSUE TITLE
Entries from Lightfall redacted when they should not be redacted

### ISSUE THREAD

**Issue by baxter** [Bungie-net/api#1827]
The following entries from Lightfall are redacted, but are available in-game and should not be redacted.

* A Guardian's Ideals
  * Guiding Light (https://data.destinysets.com/i/Lore:2286676114)
* A New Age
  * The Tower (https://data.destinysets.com/i/Lore:3030405822)
* Entities of Sol
  * Unanswered Questions (https://data.destinysets.com/i/Lore:1459720646)
* Guardian Directives
  * Raids and Dungeons (https://data.destinysets.com/i/Lore:2839921974)
* Inspiral
  * The Habitable World (https://data.destinysets.com/i/Lore:1398645392)
  * A Sword, an Edge (https://data.destinysets.com/i/Lore:1398645395)
  * The Art of Symbiosis (https://data.destinysets.com/i/Lore:1398645394)
  * The Dark Below (https://data.destinysets.com/i/Lore:1398645397)
  * Brass Gardeners (https://data.destinysets.com/i/Lore:1398645396)
  * Dark Glass (https://data.destinysets.com/i/Lore:1398645399)
  * Irae (https://data.destinysets.com/i/Lore:1398645398)
  * The Cave (https://data.destinysets.com/i/Lore:1398645401)
  * Meaning (https://data.destinysets.com/i/Lore:1398645400)
  * Winnowing (https://data.destinysets.com/i/Lore:3429296256)

**Comment by jshaffstall-bng** [comment]
Thanks for this list, and sorry for the delay. Are there any more that you know of that we can unredact for you?

We can plan to have these available on Tuesday, May 30th.

**Comment by jshaffstall-bng** [comment]
Nevermind, it looks like these all got unredacted with new content for Season 21.

**Comment by baxter** [comment]
Yes, they all got unredacted yesterday, thank you ❤️
