### ISSUE TITLE
Cannot insert shaders using InsertSocketPlugFree, Item definitions for all Shaders now missing Shaders ItemCategoryHash

### ISSUE THREAD

**Issue by robojumper** [Bungie-net/api#1829]
E.g. https://archive.destiny.report/version/d5dfde8d-41a3-4a7b-903a-c67fea16a7d6/DestinyInventoryItemDefinition/modified/3818755493

The full list of unused ICHs is

```
Shaders = 41
Blueprint = 51
Aura = 57
ArmorModsClassHunter = 1037516129
ArmorModsClassTitan = 1650311619
ProphecyOfferings = 2005599723
GagPrizes = 2150402250
ProphecyTablets = 2250046497
TreasureMaps = 2253669532
InfusionMaterials = 2266591099
ArmorModsClassWarlock = 2955376534
ChallengeCards = 3041770480
AdventureTokens = 3134521018
TicketMods = 3448069192
StoryPrizes = 3747263590
```

of these, Shaders seem like the only relevant thing that went missing entirely from items.

**Comment by jshaffstall-bng** [comment]
Good find, thanks for the heads up! I hope to have this fixed with new Bungie.net D2 API content on Tuesday, May 30th.

**Comment by CaptainDapper** [comment]
I'm not sure if this is related, but it feels like it, so I thought I'd mention it. Several times today while applying other loadouts in-game, the ornaments and shaders for the headpiece and the class item wouldn't change to the saved configurations. The class item would revert to unshaded and unornamented sometimes too. I couldn't find a way to reproduce either reliably, unfortunately. Thank you for all you do <3

**Comment by robojumper** [comment]
Thanks for the quick fix!
