### ISSUE TITLE
Carnage report complete

### ISSUE THREAD

**Issue by rentalhost** [Bungie-net/api#183]
Hello, as from D1, we will have a complete carnage report? I mean, with data about the number of killed enemies, which enemy, so on? Example:

```php
'killsCalus' => 1,
'killsPsionics' => 289
```

**Comment by floatingatoll** [comment]
I was going to ask if this was in a PVE context, but SRL lets you
sparrow-kill enemies on the track in D1, so technically in a PVP context we
would either have or not-have these values, too!

**Comment by rentalhost** [comment]
I mean, the `Destiny2.GetPostGameCarnageReport` have a lot info, but don't have the specific enemies killed like the D1 API.

**Comment by floatingatoll** [comment]
There was discussion back at the end of D1 where they considered removing
those statistics, so it's possible they went forward with that. It could
also be a bug.

**Comment by rentalhost** [comment]
Ah, right. So maybe it just tell the important events on activity. For instance, currently is not possible to know if "Guardens" was complete on a specific activity, just "Calus", or if you have done a Public Event normal or heroic (and if completed it).

I need it be available because I have a clan that will use this stats to check if members are active and helpful with another clan members. We have a not of "leechers" that just are in clan to get Hawthorme rewards, and never help us in fact, and is hard to identify it.

**Comment by floatingatoll** [comment]
There are other, Raid-specific PGCR-ish issues, being tracked in #132,
#136, #158.

**Comment by sgtfrankieboy** [comment]
Enemy data has officially been removed.

**Comment by vthornheart-bng** [comment]
Yeah, sorry guys - we lost enemy data toward the end of D1, and I don't think we're ever going to get it back unfortunately.  It is a bummer, but our hands (and data) are tied on this issue. :(
