### ISSUE TITLE
All Last Wish weapon collectibles reference elderly item versions

### ISSUE THREAD

**Issue by irons** [Bungie-net/api#1831]
Similarly to #1825, the [collectible for Chattering Bone](https://data.destinysets.com/i/Collectible:4274523514) references [item hash 568515759](https://data.destinysets.com/i/InventoryItem:568515759?lang=en), which is the version from Forsaken. Seems like it should reference [the new one from S21, item hash 501329015](https://data.destinysets.com/i/InventoryItem:501329015?lang=en). 

Searches for weapons with a given perk currently omit the revised Chattering Bone, as they do for The Title in the other case.

**Comment by irons** [comment]
I realized shortly after writing this up that other Last Wish weapons were similarly affected. I put together a script to look for weapon-items released in a later season than that weapon's latest collectible, and got this output, still current as of today's definitions:

| Item | Latest season | Latest collectible season |
| -----|---------------| -------------------------|
| Apex Predator     | 21 | 4 |
| Tyranny of Heaven | 21 | 4 |
| The Supremacy     | 21 | 4 |
| The Title         | 20 | 16 |
| Techeun Force     | 21 | 4 |
| Transfiguration   | 21 | 4 |
| Nation of Beasts  | 21 | 4 |
| Age-Old Bond      | 21 | 4 |
| Chattering Bone   | 21 | 4 |

Items with no collectible: Rebuke AX-GL, Bushwhacker, Presto-48, Timecard

**Comment by justrealmilk** [comment]
While this is a game-side issue, I'd also like it "fixed"
