### ISSUE TITLE
Fishing Tackle's "Bait Collected" objective has visible dummy icon, companion app doesn't expand string vars

### ISSUE THREAD

**Issue by robojumper** [Bungie-net/api#1832]
https://data.destinysets.com/i/InventoryItem:1607610663/SandboxPerk:3056678280

bonus bug report: D2 companion app doesn't expand the string variables

![grafik](https://github.com/Bungie-net/api/assets/14299449/70065616-4611-44f5-8c3f-c47fd99e7cef)

![grafik](https://github.com/Bungie-net/api/assets/14299449/3e3c793e-f176-4f7d-8a89-fd21f6fbb9e6)

**Comment by jshaffstall-bng** [comment]
Good find, thanks for the heads up!

**Comment by jshaffstall-bng** [comment]
The perk icons are better now (though they do have a baked in background color).

We'll be updating the D2 Companion apps to resolve the string variables there.
