### ISSUE TITLE
Vendor interactions redacted

### ISSUE THREAD

**Issue by baxter** [Bungie-net/api#1835]
Currently almost all the vendor interactions relating to this season's stories are redacted. (The same was true of Lightfall/Season of Defiance although they seem to be unredacted now).

Specifically I'm interested in the "Sonar Station" (3841825912) and its interactions.

We're missing out on some really useful lore. Is there any way that this could please be unredacted?

Thank you <3

**Comment by jshaffstall-bng** [comment]
Unfortunately, we don't have a good way to target individual vendor 'flavor lines' for redaction, so our current approach is 'all of nothing' for any of the vendors that may have spoilers for the current season.

I'm tracking the request to redact individual flavor lines, but I'm not confident that we'd prioritize this in the near term.

**Comment by baxter** [comment]
Thanks for your reply. I understand, I suspected that might be the case! 🙂

**Comment by baxter** [comment]
@jshaffstall-bng it looks as though the vendor interactions from last season were not un-redacted today. Is this something that could be done soon? Thanks!
