### ISSUE TITLE
Some weapon sockets have the plugSources property set to 0 on manifest

### ISSUE THREAD

**Issue by joaopmarquesini** [Bungie-net/api#1838]
For example, the `3849444474` Tripwire canary have the socket at index `1` (Bowstrings) plugSources set to 0 when it should be `2`(ReusablePlugItems ? not sure if 2 or 6 `ReusablePlugItems + ProfilePlugSets`).

**Comment by kj415j45** [comment]
Sample code could runs on [Destiny Data Explorer](https://data.destinysets.com/) for inspecting the issue.
```javascript
$InventoryItem.filter((e) => e.itemType === 3).filter(function (e) {
    var sockets = e.sockets?.socketEntries ?? [];
    if(sockets.lenth == 0) return false;
    sockets = sockets.filter((s) => s.plugSources === 0) // Init potential buggy sockets
    weaponPerks = 4241085061;
    sockets = sockets.filter((s) => $SocketType[s.socketTypeHash].socketCategoryHash === weaponPerks); // Only consider weapon perks
    originTraits = 3993098925; 
    sockets = sockets.filter((s) => s.socketTypeHash !== originTraits); // Exclude origin trait
    return sockets.length != 0;
}).show();
```
![Code runs result image](https://github.com/LittleLightForDestiny/littlelight/assets/18349191/495b4471-4767-4b98-b484-d54723adf3f6)
It may unrelated but I have to say that all origin trait has the plugSources set to 0 too, so I exclude them in above code.
