### ISSUE TITLE
Crafted legendary items not returning masterwork status when they should

### ISSUE THREAD

**Issue by joaopmarquesini** [Bungie-net/api#1839]
ItemState won't include ItemState 4 on masterworked crafted legendary weapons.

**Comment by jshaffstall-bng** [comment]
To be more specific, are you referring to crafted legendary weapons with 2x 'Enhanced Trait' perks, which get the Masterwork icon treatment in-game?

**Comment by joaopmarquesini** [comment]
hmmmm probably ?
I got that as a feedback from an user, but the only example that I could reproduce in my inventory is a [The Enigma](https://www.light.gg/db/items/2595497736/the-enigma/) which indeed have 2 enhanced traits and displays as a masterwork in-game, but returns 8 when unlocked and 9 when locked instead of 12 and 13.

**Comment by robojumper** [comment]
I also reported this in #1662.

**Comment by joaopmarquesini** [comment]
Closing as it's a duplicate of #1662
