### ISSUE TITLE
CurrentResetCount property missing for seasonal vendors

### ISSUE THREAD

**Issue by MoonieGZ** [Bungie-net/api#1840]
Similar issue to #1669 and #1544 but those issues were fixed down the line with the vendor refresh.

Currently, seasonal vendors don't expose the CurrentResetCount property, which is a minor inconvenience for apps tracking reset counts.

![image](https://github.com/Bungie-net/api/assets/1693101/77a228fc-ec6f-401f-a1ab-cf3851a547f0)

Found vendors with the issue:
- War Table from S20 (1629742958)
- Sonar Station from S21 (3841825912)

EDIT: Reset count is available via GetProfile with CharacterProgressions with ID 3661731483 (called "Prestige") for War Table.

**Comment by jshaffstall-bng** [comment]
These reset counts should be available for S20 and S21 vendor progressions now, enjoy!
