### ISSUE TITLE
Icarus Dash, Weavewalk perks show [###DestinyNamedSubstitutions.ui_player_action_air_dodge_button###] [###DestinyNamedSubstitutions.ui_player_action_air_dodge_verb###] in their description

### ISSUE THREAD

**Issue by robojumper** [Bungie-net/api#1845]
For [Icarus Dash](https://data.destinysets.com/i/SandboxPerk:3694014520), this used to be `[Air Move]`. [Weavewalk](https://data.destinysets.com/i/SandboxPerk:1000136554) was added this Season and I think it should be `[Air Move]` too.

As shown in DIM 
![grafik](https://github.com/Bungie-net/api/assets/14299449/e51d3c53-9dce-4647-8d59-61653e6b9345)

and the Companion App
![grafik](https://github.com/Bungie-net/api/assets/14299449/c9307dfe-7223-44d8-a991-b8938fd26c00)

**Comment by jshaffstall-bng** [comment]
This will be fixed with new D2 API content tomorrow.

**Comment by robojumper** [comment]
Thanks for the fix!
