### ISSUE TITLE
Missing Mode Types in API Docs

### ISSUE THREAD

**Issue by mikechambers** [Bungie-net/api#1851]
https://bungie-net.github.io/multi/schema_Destiny-HistoricalStats-Definitions-DestinyActivityModeType.html#schema_Destiny-HistoricalStats-Definitions-DestinyActivityModeType

Looks like its just missing Relic, Mode 92

**Comment by jshaffstall-bng** [comment]
The 'Relic' mode 92 is the only new one in Season 22. We can try to get the API spec and docs updated soon.
