### ISSUE TITLE
Crota's End - missing unredactions

### ISSUE THREAD

**Issue by nev-r** [Bungie-net/api#1852]
crota's end activities (4179289725, 4103176774, 156253568, 1507509200)
triumphs (3702810582, its siblings, its parent)
milestone(s?) (540415767)
etc. are all still redacted

**Comment by nev-r** [comment]
also the crota's end collections badge (48971793 and child records)

**Comment by nev-r** [comment]
also Word of Crota (Record:1741156110) under the patterns progress checklist
and Word of Crota (Collectible:4017656006) under collections

**Comment by defultnaem** [comment]
The quests steps 4284902391 and 4284902389 have also not been unredacted yet, but the quest step between them (4284902390) has been

**Comment by nev-r** [comment]
also Record:503301272, the necrochasm catalyst

**Comment by jshaffstall-bng** [comment]
Thanks for this list of things to double check. We had some inconsistent unredaction dates, but I've confirmed that all of these will be unredacted with new D2 API content deploying tomorrow, September 7th.

**Comment by jshaffstall-bng** [comment]
Should be all good now
