### ISSUE TITLE
Redacted lore as of 2023-10-03

### ISSUE THREAD

**Issue by baxter** [Bungie-net/api#1858]
The following pages are redacted in the API but fully available in game. Please could they be un-redacted? Thank you! 💙 

| Book | Entry # | Entry name |
| ---- | ---- | ---- |
| Rites of Passage | 1 | Process |
| Rites of Passage | 2 | A Matter of Distrust |
| Rites of Passage | 3 | Auspices |
| Rites of Passage | 4 | An Invocation |
| Rites of Passage | 5 | A Big Fan |
| Rites of Passage | 6 | Contingency Plans |
| Rites of Passage | 7 | A Deal's a Deal |
| Sororicide | 1 | I - Eris Morn - Prolegomenon |
| Sororicide | 2 | II - Savathûn - Imago Unfurl |
| Sororicide | 3 | III - Xivu Arath - Battlesong |
| Sororicide | 4 | IV - Eris Morn - Evocate Desire |
| Sororicide | 5 | V - Eris Morn - Mimesis |
| Sororicide | 6 | VI - Xivu Arath - κατολοϕύρομαι |
| Sororicide | 7 | VII - Xivu Arath - Deathless |
| Sororicide | 8 | VIII - Savathûn - Swords and Lanterns |
| Sororicide | 9 | IX - Xivu Arath - Antigone Drowns |
| Sororicide | 10 | X - Eris Morn - The Augur Casts Her Bones |
| Sororicide | 11 | XI - Eris Morn - They Drink Strong Poison |
| Sororicide | 12 | XII - Savathun - Love |

**Comment by jshaffstall-bng** [comment]
Thanks for this list! These will be unredacted with the next Bnet API content deployment.
