### ISSUE TITLE
Activity History Truncated?

### ISSUE THREAD

**Issue by ChemDataFarmer** [Bungie-net/api#186]
Hi all,

I'm having a bit of a problem when getting the activity history. It appears to be returning truncated results. I know this was a problem a while ago (#52), but it had apparently resolved itself . Perhaps the current problem is related to #179 and/or  #180? Either way, here is what's happening. I'm hitting the following endpoint.

"/Destiny2/2/Account/4611686018460847890/Character/ 2305843009262423284/Stats/Activities/?mode="+mode+"&count=" + games + "&page=0"

If mode=5 and games=50, which should correspond to the last 50 pvp games regardless of their mode, I'm only getting 21 games returned. I thought this was weird since I know this player should have many more than 21 games in all pvp, so I filtered by mode = 37 and games = 50. This returned 29 games. This still seemed low, but it's notable that the all pvp filter had less games than the survival only filtered results.

If this is a user error on my part, please let me know :).

**Comment by ChemDataFarmer** [comment]
Great news! Not sure if you pushed a patch, but this appears to be fixed!

Thanks for all the hard work on your end, Bungie.

**Comment by vthornheart-bng** [comment]
Phew, glad to hear it!  It was a combination of Stats bugs and redacted content that was causing this issue, and now both have been resolved!
