### ISSUE TITLE
Bungie.net does not display Report/Block buttons on private profiles.

### ISSUE THREAD

**Issue by MoonieGZ** [Bungie-net/api#1867]
Not sure if here is the correct place but wanted to report that the Report and Block buttons do not appear on player profiles if they have privacy settings enabled.

Example of a cheater who came to disrupt our service, who has a private profile:
![image](https://github.com/Bungie-net/api/assets/1693101/2c9e990a-4b43-4770-84a7-5e498b03a3e0)

And their friend, who does not have a private profile:
![image](https://github.com/Bungie-net/api/assets/1693101/ede9e6ea-f239-47b2-8a35-16ae9aa1264b)

Makes sense for the add friend / message / invite to clan to be linked to privacy but reporting should always be public...

**Comment by camohiddendj** [comment]
![image](https://github.com/Bungie-net/api/assets/11087140/3ffac9fc-0b7e-45b0-8500-a5246db9f9fa)

Another one that one-shot Taniks, We really shouldn't have to rely on figuring out unpublished endpoints to be able to block bad actors like this.

**Comment by leanderson-bng** [comment]
Thank you for bringing this to our attention. I've captured the issue for the team to review. 

For future reference, you can post these type of issues in our help forum and the player support team will bring it to our attention.
[https://www.bungie.net/en/Forums/Topics?pNumber=0&tg=Help&tSort=3&tType=0&d=0&lang=en](https://www.bungie.net/en/Forums/Topics?pNumber=0&tg=Help&tSort=3&tType=0&d=0&lang=en)
