### ISSUE TITLE
incorrect magazine sizes

### ISSUE THREAD

**Issue by defultnaem** [Bungie-net/api#1873]
idk if it's just Wicked Implement (940371471) but the magazine size in the API is showing as 16 in the API, but is actually 15 in game

**Comment by cowgod** [comment]
Bungie has called this out as a known issue with no planned fix. There are transformations performed on the MAgazine stat in the game, which the API doesn't have access to, so these values can't be 100% correct. At one point they asked whether we'd rather have a "close but not 100% accurate" value vs eliminating it entirely, and the decision was made that it was still valuable to have it, even if it's sometimes slightly off.

See the note on this entry: https://bungie-net.github.io/#/components/schemas/Destiny.Definitions.DestinyItemStatBlockDefinition
