### ISSUE TITLE
Cant extract perk 1  and 2 slot from instance id

### ISSUE THREAD

**Issue by WillHeather18** [Bungie-net/api#1875]
I am developing a destiny 2 software and using the API and manifest i have succesfully got a list of weapons in a players inventory. I am able to identify the last 2 perks using the hash codes and comparing them to the manifest. However when i try to compare the other hashcodes to the manifest i cant find what barrel and magazine the weapon has rolled with. Does anyone know where i can find this information? I have attatched an example of a weapon object from a players inventory.
[example object.txt](https://github.com/Bungie-net/api/files/14351365/example.object.txt)

**Comment by nev-r** [comment]
![image](https://github.com/Bungie-net/api/assets/68782081/3127f665-2676-4ac0-9b83-1ab204030a38)
