### ISSUE TITLE
CORS/ Access Control Allow Origin

### ISSUE THREAD

**Issue by AndretheG** [Bungie-net/api#1876]
I've been constantly running into an issue with "The 'Access-Control-Allow-Origin' header has a value 'https://www.bungie.net' that is not equal to the supplied origin." Error. Whenever I try to make requests via the frontend of my app. I don't understand since I put *
In the Origin Header of my developer portal. I've even tried explicitly listed the domain for my frontend and included the origin header in all of my requests. I've also tried including the origin header while still setting it to * in the developer portal. For reference, I built my backend using NodeJs and the frontend in React. All the requests originating from the backend work when I type my endpoints in the address bar, but it isn't the case when I access from my frontend. I have read multiple forums and posts all of which implement some sort of workaround that doesn't seem feasible for my project. Please provide some sort of feedback.

**Comment by jshaffstall-bng** [comment]
We can help you to troubleshoot if you include more details about the exact requests you're making and the exact responses you're getting back.

Also, you can try to get more immediate help and feedback from the community in the Destiny API Discussion discord - https://discord.gg/ezRXpgPt
