### ISSUE TITLE
Problem with teams in Collision game mode

### ISSUE THREAD

**Issue by gmcbay** [Bungie-net/api#1877]
The PGCR data for the new Collision game mode doesn't segment teams.  

The teams collection is empty and players do not get a team value attached to them.

**Comment by gmcbay** [comment]
* This also applies to Clash in the 3v3 Quickplay node

**Comment by jshaffstall-bng** [comment]
This should be resolved now, sorry for the delay.

For new PCGRs starting today, Collision falls into the Zone Control category, and Clash 3v3 falls into the Clash category.

**Comment by gmcbay** [comment]
@jshaffstall-bng

Not a big deal, but while the modes do now write as documented in the PGCRs after a game is completed (thanks!), Collision identifies as mode 12 (Clash) in currentActivityModeType under profile/character component 204 when trying to discover what current activity a player is engaged in.
