### ISSUE TITLE
Redacted lore as of 2024-03-19

### ISSUE THREAD

**Issue by baxter** [Bungie-net/api#1878]
Hello 😃 the following books and their pages are redacted in the API but fully available in the game. Could you please un-redact them?

Thanks!

- Gifts and Bargains
  - First Gift
  - Second Gift
  - Third Gift
  - Last Bargain
- Dragonslayers
  - Valus Forge's Prologue
  - The Iron Lord's Tale
  - The Hermit's Tale
  - The Bone-Trader's Tale
  - The Wise-Woman's Tale
  - Valus Forge's Epilogue

**Comment by jwshaffstall** [comment]
Thanks for the heads up! These should be unredacted with the next batch of D2 content we deploy to Bungie.net, hopefully next week.
