### ISSUE TITLE
Determining current faction rally milestone?

### ISSUE THREAD

**Issue by lordmortis** [Bungie-net/api#189]
I'm wondering if i'm doing the right thing: 

I'm querying `/Destiny2/Milestones/` to get all the public milestones, and while there's faction rally information in there - it seems to return all the activities/quests for the entire week - i'm not sure how to get the current one? (I'm looking for a milestone with the friendly name of `FactionRally` and inside that it's got all the Activities/Quests for the week - but the first one in the list is EDZ, but today is Nessus (for example) )

**Comment by vthornheart-bng** [comment]
Ah yes, this was a bug discovered while I was away - I have not yet had time to investigate the root cause of why this came about.  But I'll be certain to resolve the issue before the next Faction Rally comes around.

**Comment by vthornheart-bng** [comment]
Should be fixed now.
