### ISSUE TITLE
8.0.0.1 Update checklists with new region chests and lost sectors

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1891]
A single checklist for "feathers of light" would also be cool (55 items)

**Comment by jshaffstall-bng** [comment]
Any other new kinds of collectibles we want checklists for as well?

**Comment by justrealmilk** [comment]
- Visions of the Traveler
- Paracausal Geometries

**Comment by Jarvichi** [comment]
Is it possible to see which Lost Encryption Bits as a checklist? The ones for the Khvostov quest?

**Comment by D217696** [comment]
if the prismatic fragment chests could also be a checklist that would be awesome!!

**Comment by justrealmilk** [comment]
> Is it possible to see which Lost Encryption Bits as a checklist? The ones for the Khvostov quest?

Isn't this the same as collecting all 9 region chests?

**Comment by delphiactual** [comment]
That's what I thought too, but there are 6 more chests inside each of the cysts.

**Comment by justrealmilk** [comment]
Then perhaps we should ask for a cyst checklist rather. Then we can combine them as consumers of the API

**Comment by justrealmilk** [comment]
I've learnt more about how Khvostov pursuit works and as the completion of a cyst isn't what rewards the required item, I now think it's definitely best for it to have its own checklist.

Summary:
- Append to **Region Chests** checklist
- Append to **Lost Sectors** checklist
- Create **Feathers of Lights** checklist
- Create **Visions of the Travelers** checklist
- Create **Paracausal Geometries** checklist
- Create Khvostov "**Lost Encryption Bits**" checklist

**Comment by jshaffstall-bng** [comment]
This looks like a good list, thanks! We won't have any updates here for the 18th, but hopefully we can for the 25th at the latest.
________________________________
