### ISSUE TITLE
Redacted TFS Lore, updated 2024-06-15

### ISSUE THREAD

**Issue by baxter** [Bungie-net/api#1894]
Hello again 😄 the following pages are redacted in the API but fully available in the game.

Could you please un-redact them?

Thanks!

baxter

<table role="table">
  <thead>
    <tr><th colspan="4">Requiring un-redaction</th></tr>
    <tr><th>Book</th><th>№</th><th>Entry</th><th>Un-redacted?</th></tr>
  </thead>
  <tbody>
    <tr><td colspan="4">None</td></tr>
  </tbody>
  <thead>
    <tr><th colspan="4">Already un-redacted</th></tr>
    <tr><th>Book</th><th>№</th><th>Entry</th><th>Un-redacted?</th></tr>
  </thead>
  <tbody>
    <tr><td>Chirality</td><td>1</td><td>Foreword</td><td>✅</tr>
    <tr><td>Chirality</td><td>2</td><td>Symmetry</td><td>✅</tr>
    <tr><td>Chirality</td><td>3</td><td>Omnivorous</td><td>✅</tr>
    <tr><td>Chirality</td><td>4</td><td>Transformations of Matter</td><td>✅</tr>
    <tr><td>Chirality</td><td>5</td><td>Preservation</td><td>✅</tr>
    <tr><td>Chirality</td><td>6</td><td>Old Friend, Beloved</td><td>✅</tr>
    <tr><td>Chirality</td><td>7</td><td>Empty-Handed</td><td>✅</tr>
    <tr><td>Chirality</td><td>8</td><td>Cacosmia</td><td>✅</tr>
    <tr><td>Chirality</td><td>9</td><td>Collective</td><td>✅</tr>
    <tr><td>Chirality</td><td>10</td><td>Bird in the Hand</td><td>✅</tr>
    <tr><td>Companions</td><td>1</td><td>He Wakes</td><td>✅</tr>
    <tr><td>Companions</td><td>2</td><td>She Rises</td><td>✅</tr>
    <tr><td>Companions</td><td>3</td><td>He Sees</td><td>✅</tr>
    <tr><td>Companions</td><td>4</td><td>She Falls</td><td>✅</tr>
    <tr><td>Dynasty</td><td>1</td><td>Chapter 1 – A Step Leads. A Step Follows.</td><td>✅</tr>
    <tr><td>Polyphony</td><td>1</td><td>I. Impact</td><td>✅</tr>
    <tr><td>Polyphony</td><td>2</td><td>II. Isolated Incidents</td><td>✅</tr>
    <tr><td>Polyphony</td><td>3</td><td>III. Heart-Truth</td><td>✅</tr>
    <tr><td>The Rubicon</td><td>1</td><td>Acheron I</td><td>✅</tr>
    <tr><td>The Rubicon</td><td>2</td><td>Acheron II</td><td>✅</tr>
    <tr><td>The Rubicon</td><td>3</td><td>Styx I</td><td>✅</tr>
    <tr><td>The Rubicon</td><td>4</td><td>Styx II</td><td>✅</tr>
    <tr><td>The Rubicon</td><td>5</td><td>Phlegethon I</td><td>✅</tr>
    <tr><td>The Rubicon</td><td>6</td><td>Phlegethon II</td><td>✅</tr>
    <tr><td>The Rubicon</td><td>7</td><td>Lethe</td><td>✅</tr>
    <tr><td>The Rubicon</td><td>8</td><td>Eunoe</td><td>✅</tr>
  </tbody>
</table>

**Comment by jshaffstall-bng** [comment]
Thanks for this list. These will be unredacted with the next content update on Tuesday, June 11th.

Do you want to keep this issue open and add more lore as it becomes available in-game?

**Comment by baxter** [comment]
Yeah I can do that. In that case I might reformat this a bit so that it is better suited for that :+1:

**Comment by baxter** [comment]
@jshaffstall-bng I've reformatted the comment, hopefully it makes sense. Let me know if you'd like it formatted differently.

I've also added new entries that are available in the game and not yet in the API. Thanks!

**Comment by jshaffstall-bng** [comment]
I don't think any of the new ones will be unredacted with the new content today, but we can get them and more new ones for next week.

**Comment by jshaffstall-bng** [comment]
Any new ones we can unredact this week as well?

**Comment by baxter** [comment]
Hey @jshaffstall-bng, I've updated the table, I think all of "Rubicon" is available now and should be un-redacted. There's also at least one entry in Companions. I'll double check with the community to see if there are any others.

**Comment by jshaffstall-bng** [comment]
Those new Lore entries and their Record definitions should be unredacted now.
