### ISSUE TITLE
Exotic Class Items DestinyInventoryItemDefinition Missing randomizedPlugSetHash

### ISSUE THREAD

**Issue by afpac** [Bungie-net/api#1899]
Exotic Class Items are randomly rolled but the sockets which reference the randomly rolled perks do not contain a randomizedPlugSetHash. Currently only a singleInitialItemHash is visible.

This is just on the definition. I haven't gone digging for what comes back for an instanced copy in itemComponents.reusablePlugs yet

Warlock class item for example:

https://data.destinysets.com/i/InventoryItem:2273643087

![image](https://github.com/Bungie-net/api/assets/32434371/70882b8e-4fbf-4280-a48e-f01fa6d5e3ed)

**Comment by jshaffstall-bng** [comment]
Unfortunately these random rolls were implemented in-game outside of this randomized plug set system, so this won't be feasible. Best to manually show the relationships instead. Sorry!
