### ISSUE TITLE
Contest Instances Missing

### ISSUE THREAD

**Issue by owens1127** [Bungie-net/api#1900]
There are missing Contest Salvation's Edge instances from several players. There is no record of incompletion or completion, yet these players have the contest emblem unlocked and clearly cleared the raid.

One such instance is player `4611686018467296201`. They cleared the raid approximately 27 hours after contest mode began. They have no other clears, and yet it is obvious they did finish the raid within 48 hours because they have the emblem.

Other members of the fireteam expected to be in the clear should be: `4611686018467263845`, `4611686018467301583`, `4611686018471329884`, `4611686018472629626`, `4611686018484346567`

This is one specific case, but I know there are more like it.

I understand that instances have been lost in the past, but I would appreciate the extra effort into digging into the cause for the lost contest mode instances because they are some of player's most prized clears.

My discord is _newo if you need to  reach out in the api discord!

**Comment by gavin-kemp** [comment]
Seconding this as my team had this experience as well. We finished roughly 1d 18hr and 43m after the raid launched. We all have the contest emblem equipped. My steam id is: `76561198035649568`

**Comment by WyWyFe** [comment]
I am also experiencing this issue, and completed the raid with gavin-kemp above. 
My steam ID is `76561198063035356`

**Comment by owens1127** [comment]
Closing because this resolved naturally a month and a half later, something is obviously broken though
