### ISSUE TITLE
Prismatic subclasses `screenshot` fields missing

### ISSUE THREAD

**Issue by joaopmarquesini** [Bungie-net/api#1901]
The definitions do have an url for the prismatic subclasses screenshot, but they return 404:
https://www.bungie.net/common/destiny2_content/screenshots/1616346845.jpg
https://www.bungie.net/common/destiny2_content/screenshots/4282591831.jpg
https://www.bungie.net/common/destiny2_content/screenshots/3893112950.jpg

**Comment by jshaffstall-bng** [comment]
Thanks! I think we can add these soon.

**Comment by jshaffstall-bng** [comment]
These new screenshots are now live!
