### ISSUE TITLE
Text conversation does not change from disabled to enabled

### ISSUE THREAD

**Issue by cg1218ja** [Bungie-net/api#1903]
![2024-06-16 145853](https://github.com/Bungie-net/api/assets/61230078/efd01578-74ca-4e14-8a10-a1895560a813)
From Destiny 2 Text conversation does not change from disabled to enabled

The text conversation settings are set like this     Text Conversation : off(Defaults)= 텍스트 대화 : 끄기(기본값)

**Comment by cg1218ja** [comment]
![Uploading 2024-06-16 153108.png…]()

**Comment by justrealmilk** [comment]
If this is regarding the profanity filter, it's a known issue.

Also, this is a repository for the API, not the game itself.
