### ISSUE TITLE
A means of seeing the total number of kills of each weapon used for a given character.

### ISSUE THREAD

**Issue by admpsktt** [Bungie-net/api#1905]
There exists an endpoint for unique (Exotic) [weapon history](https://bungie-net.github.io/multi/operation_get_Destiny2-GetUniqueWeaponHistory.html#operation_get_Destiny2-GetUniqueWeaponHistory).

Can we have the same for other weapons, too? The data is all there but we currently have to scrape it from all PGCRs (bearing in mind the [activity history](https://bungie-net.github.io/multi/operation_get_Destiny2-GetActivityHistory.html#operation_get_Destiny2-GetActivityHistory) endpoint is capped at 250 records) and sum.

**Comment by jshaffstall-bng** [comment]
Sorry, this is not something we're planning to do.
