### ISSUE TITLE
Question: Pathfinder quests via API

### ISSUE THREAD

**Issue by kuleshov-aleksei** [Bungie-net/api#1906]
Hello!

Is there any way to get active pathfinders (for pale heart destination and ritual activities) using API?

**Comment by delphiactual** [comment]
From elsewhere:
```
There are two root Presentation Nodes to look at:

The Pale Heart Pathfinder - https://data.destinysets.com/i/PresentationNode:1062988660
Rituals Pathfinder - https://data.destinysets.com/i/PresentationNode:622609416

You should be able to use Presentation Node visibility states to determine which child nodes of these root Pathfinder nodes are active for an account.
```

**Comment by kuleshov-aleksei** [comment]
Thank you! This is exactly what I was looking for

Btw, I'm not sure, but seems like I can track progress using `Destiny2.GetProfile` endpoint (`/Platform/Destiny2/{membershipType}/Profile/{destinyMembershipId}/?components=700,900`)
