### ISSUE TITLE
Missing Item after Transfer

### ISSUE THREAD

**Issue by XZero3** [Bungie-net/api#1907]
Hello, 

So I transferred the raid SMG from my Warlock to my Hunter to activate a deepsight on it, however it never arrived onto my character or into my vault.

What I did afterwards:

1- Save gameplay recording on my PS5 to make sure I didn’t accidentally delete it, which I definitely did not as the item never showed up ingame after I transferred it.

2- Restarted the game, and the applications, and re-verified all my characters and vaults. 

3- I went into the App Action History and found this, attached in the image, as you can see the transfer failed from my Warlock to my vault (as every item goes to the vault first before going to the other character.) This was the only action attempted/performed on this item.

Would greatly appreciate some help, really sucks to lose a raid item.
Bungie ID: Zero#3250

![image](https://github.com/Bungie-net/api/assets/173401305/13825739-cbc2-42a0-9ced-05e40bb9a25d)

**Comment by jshaffstall-bng** [comment]
I see an Imminence SMG on your Hunter. Is that the one?

**Comment by XZero3** [comment]
> I see an Imminence SMG on your Hunter. Is that the one?

Thank you for the quick response!

Nope that's 100% a different one.

The one that is lost was power 2000 and had strategist as one of its perks. It absolutely vanished.

I double checked all characters, vaults, post-masters. It just failed to move from my Warlock to my Vault, nowhere to be found. 
No other actions were performed with it. 
![image](https://github.com/Bungie-net/api/assets/173401305/207f5366-ca90-4fdd-9781-3fabd7f35483)

**Comment by jshaffstall-bng** [comment]
Are you able to share your gameplay recording?

**Comment by XZero3** [comment]
> Are you able to share your gameplay recording?

I would love to and would have shared it already but unfortunately I deleted it right away because I didn't think it would be helpful in anyway whatsoever, the reason being is that it showed nothing but my ship in orbit.

I was using my Iphone for the item transfer, I simply wanted to double check if I had actually gotten the item and did anything with it before seeking help. 

And once you restart the game application on PS5 you can't record gameplay from before suspension of the application.

**Comment by joaopmarquesini** [comment]
@jshaffstall-bng from what @XZero3 explained to me earlier, he wasn't playing the character where the affected weapon was (he was playing hunter and the weapon was on his warlock), so the video wouldn't show anything as the weapon was going from an offline character to the vault.

**Comment by XZero3** [comment]
> @jshaffstall-bng from what @XZero3 explained to me earlier, he wasn't playing the character where the affected weapon was (he was playing hunter and the weapon was on his warlock), so the video wouldn't show anything as the weapon was going from an offline character to the vault.

That is the case yes. 
The item left my inactive character (Warlock) towards the Vault so it can then be transferred to my active character (Hunter), but it disappeared on its way to the Vault and it never returned to my Warlock's inventory.

**Comment by jshaffstall-bng** [comment]
Closing the loop on this:
As of 6/20, we can see you earned three Imminence SMGs from the new raid, and then you infused two of them into other weapons shortly after they dropped.

Since then, you've earned two more and now have three Imminence SMGs in your inventory.

There is no API gear transfer issue here. This was likely a matter of seeing cached gear data in the app, and the transfer failing from that SMG no longer existing once it was infused into another weapon.
