### ISSUE TITLE
DestinyActivityInteractableDefinition is missing from sqlite definitions

### ISSUE THREAD

**Issue by EndGameGl** [Bungie-net/api#1915]
[DestinyActivityInteractableDefinition](https://bungie-net.github.io/multi/schema_Destiny-Definitions-Activities-DestinyActivityInteractableDefinition.html#schema_Destiny-Definitions-Activities-DestinyActivityInteractableDefinition) is documented, but not present in sqlite definitions
Quick search reveals that those definitions DO exist if searched through API `/Platform/Destiny2/Manifest/DestinyActivityInteractableDefinition/3839772983/`
Can those definitions either be removed from documentation or be added to sqlite/json definitions to match up documentation and content?

**Comment by jshaffstall-bng** [comment]
Spoiler - these will be added with the next Bnet D2 API content update on Tuesday, July 16th.
