### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by EricCacciavillani** [Bungie-net/api#1921]
I have no idea if I am allowed to write here or wether or not my tired mind is completely wrong but I am worried I found a security bug with the Bungie.net system and would love to dm someone about this....I dont want to put this in a public setting as it could be harmful to people.

**Comment by leanderson-bng** [comment]
Hi @EricCacciavillani, you can use HackerOne to report a vulnerability. Details can be found here: [https://secure.sony.com/](https://secure.sony.com/)
