### ISSUE TITLE
Redacted Lore, as of 2024-12-09

### ISSUE THREAD

**Issue by baxter** [Bungie-net/api#1931]
Hello 😃 the following lore pages are redacted in the API but not in the game. Could they please be un-redacted?

Thanks!

baxter

<table role="table">
  <thead>
    <tr><th colspan="4">Requiring un-redaction</th></tr>
    <tr><th>Book</th><th>№</th><th>Entry</th><th>Un-redacted?</th></tr>
  </thead>
  <tbody>
    <tr><td>Garden-Way</td><td>1</td><td>Judgment</td><td>❌</tr>
    <tr><td>Garden-Way</td><td>2</td><td>Fields</td><td>❌</tr>
    <tr><td>Garden-Way</td><td>3</td><td>Light</td><td>❌</tr>
    <tr><td>Garden-Way</td><td>4</td><td>War</td><td>❌</tr>
    <tr><td>Garden-Way</td><td>5</td><td>Monsters</td><td>❌</tr>
    <tr><td>Garden-Way</td><td>6</td><td>Return</td><td>❌</tr>
  </tbody>
</table>

**Comment by jshaffstall-bng** [comment]
These are unredacted now, thanks for the reminder! https://data.destinysets.com/i/PresentationNode:1575985352
