### ISSUE TITLE
Question: Where can i find the icon paths to gear items?

### ISSUE THREAD

**Issue by Mikeks81** [Bungie-net/api#195]
I have been looking though endpoints and i can't seem to locate an icon path for the item itself. I have found the icons for the perks but not the actual item.

**Comment by hellocontrol-bng** [comment]
Each item has an [itemHash](https://bungie-net.github.io/multi/schema_Destiny-Entities-Items-DestinyItemComponent.html#schema_Destiny-Entities-Items-DestinyItemComponent) you can use to look up the item definition.

**Comment by hellocontrol-bng** [comment]
Accidentally hit the close button while typing! You can use the itemHash to map to the [DestinyInventoryItemDefinition](https://bungie-net.github.io/multi/schema_Destiny-Definitions-DestinyInventoryItemDefinition.html#schema_Destiny-Definitions-DestinyInventoryItemDefinition), which has `displayProperties`, which contains an `icon` property.

**Comment by Mikeks81** [comment]
Thats a huge help! Thanks for the all the hard work put into this api
