### ISSUE TITLE
Most of one player's past matches missing from ActivityHistory 

### ISSUE THREAD

**Issue by chrisfried** [Bungie-net/api#196]
PlayStation user argot__ contacted me on Twitter complaining all PvP matches were missing from Guardian Theater.

Comparing argot__'s [history on Destiny Tracker](http://destinytracker.com/d2/profile/psn/argot__) with [results from the API](http://proxy.guardian.gg/Platform/Destiny2/2/Account/4611686018434024678/Character/2305843009264145598/Stats/Activities/?mode=None) revealed many activities present in the former missing in the latter, seemingly not limited to any particular activity type.

**Comment by vthornheart-bng** [comment]
Hmm, has this been resolved for you since the last round of un-redactions, and the fixes made to Stats?  let me know if it's still an issue!

**Comment by chrisfried** [comment]
I asked the user. Response: "I think they’re back."
