### ISSUE TITLE
Spelling issues in various files

### ISSUE THREAD

**Issue by ArkahnX** [Bungie-net/api#20]
Note: Also includes 
https://github.com/Bungie-net/api/issues/19
https://github.com/Bungie-net/api/issues/18
https://github.com/Bungie-net/api/issues/17

These are ones that weren't large enough for their own issue.

# User.UserMembership and User.UserInfoCard
**displayName**
Display Name the player has chosen for themselves. The display name is optional when the data type is used as input to a platform API.

# User.UserInfoCard
This contract supplies basic information commonly used to display a minimal amount of information about a user. Take care to not add more properties here unless the property applies in all (or at least the majority) of the situations where UserInfoCard is used. Avoid adding game specific or platform specific details here. In cases where UserInfoCard is a subset of the data needed in a contract, use UserInfoCard as a property of other contracts.

# Partnerships.PartnershipType
Representing external partners to which BNet users can link accounts, but that are not Account System credentials: partnerships that BNet uses exclusively for data.

# Queries.SearchResult and SearchResultOfPostResponse and Forum.PostSearchResponse
**useTotalResults**
If useTotalResults is true, then totalResults represents an accurate count. If False, it does not, and may be estimated/only the size of the current page. Either way, you should probably always only trust hasMore. This is a long-held historical throwback to when we used to do paging with known total results. Those queries toasted our database, and we were left to hastily alter our endpoints and create backward-compatible shims, of which useTotalResults is one.

# GroupsV2.GroupResponse
**currentUserMemberMap**
This property will be populated if the authenticated user is a member of the group. Note that because of account linking, a user can sometimes be part of a clan more than once. As such, this returns the highest member type available.
**currentUserPotentialMemberMap**
This property will be populated if the authenticated user is an applicant or has an outstanding invitation to join. Note that because of account linking, a user can sometimes be part of a clan more than once.

# GroupsV2.GroupFeatures
**maximumMembershipsOfGroupType**
Maximum number of groups of this type a typical membership may join. For example, a user may join about 50 General groups with their Bungie.net account. They may join one clan per Destiny membership.

# GroupsV2.RuntimeGroupMemberType
The member levels used by all V2 Groups API. Individual group types use their own mappings in their native storage (general uses BnetDbGroupMemberType and D2 clans use ClanMemberLevel), but they are all translated to this in the runtime api. These runtime values should NEVER be stored anywhere, so the values can be changed as necessary.

# Destiny.DestinyProgression
Information about a current character's status with a Progression. A progression is a value that can increase with activity and has levels. Think Character Level and Reputation Levels. Combine this "live" data with the related DestinyProgressionDefinition for a full picture of the Progression.
**currentProgress**
This is the total amount of progress obtained overall for this progression (for instance, the total amount of Character Level experience earned)
**levelCap**
This is the maximum possible level you can achieve for this progression (for example, the maximum character level obtainable)
**stepIndex**
Progressions define their levels in "steps". Since the last step may be repeatable, the user maybe at a higher level than the actual Step achieved in the progression. Not necessarily useful, but potentially interesting for those cruising the API. Relate this to the "steps" property of the DestinyProgression to see which step the user is on, if you care about that. (Note that this is Content Version dependent since it refers to indexes)
**progressToNextLevel**
The amount of progression (i.e. "Experience") needed to reach the next level of this Progression. Jeez, progression is such an overloaded word.

# Destiny.Definitions.DestinyDefinition and Destiny.Definitions.DestinyProgressionDefinition
**redacted**
If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!

# Destiny.Definitions.DestinyProgressionDefinition
A "Progression" in Destiny is best explained by an example. A Character's "Level" is a progression: it has Experience that can be earned, levels that can be gained, and is evaluated and displayed atvarious points in the game. A Character's "Faction Reputation" is also a progression for much the same reason. Progression is used by a variety of systems, and the definition of a Progression will generally only be useful if combining with live data (such as a character's DestinyCharacterProgressionComponent.progressions property, which holds that character's live Progression states). Fundamentally, a Progression measures your "Level" by evaluating the thresholds in its Steps (one step per level, except for the last step which can be repeated indefinitely for "Levels" that have no ceiling) against the total earned "progression points"/experience. (for simplicity purposes, we will henceforth refer to earned progression points as experience, though it need not be a mechanic that in any way resembles experience in a traditional sense). Earned experience is calculated in a variety of ways, determined by the Progression's scope. These go from looking up a stored value to performing exceedingly obtuse calculations. This is why we provide live data in DestinyCharacterProgressionComponent.progressions, so you don't have to worry about those.
**steps**
Progressions are divided into Steps, which roughly equate to "Levels" in the traditional sense of a Progression. Notably, the last step can be repeated indefinitely if repeatLastStep is true, meaning that the calculation for your level is not as simple as comparing your currentprogress to the max progress of the steps. These and more calculations are done for you if you grab live character progression data, such as in the DestinyCharacterProgressionComponent.
**factionHash**
If the value exists, this is the hash identifier for the Faction that owns this Progression. This is purely for convenience, if you're looking at a progression and want to know if and who it's related to in terms of Faction Reputation.

# Destiny.Definitions.Common.DestinyDisplayPropertiesDefinition
Many Destiny*Definition contracts - the "first order" entities of Destiny that have their own tables in the Manifest Database - also have displayable information. This is the base class for that display information.

# Destiny.Definitions.DestinyProgressionDisplayPropertiesDefinition
**displayUnitsName**
When progressions show your "experience" gained, that bar has units (i.e. "Experience", "Bad Dudes Snuffed Out", whatever). This is the localized string for that unit of measurement.

# Destiny.DestinyProgressionScope
There are many Progressions in Destiny (think Character Level, or Reputation). These are the various "Scopes" of Progressions, which affect many things:* Where/if they are stored* How they are calculated* Where they can be used in other game logic

# Destiny.Definitions.DestinyProgressionStepDefinition
**stepName**
Very rarely, Progressions will have localized text describing the Level of the progression. This will be that localized text, if it exists. Otherwise, the standard appears to be to simply show the level numerically.
**displayEffectType**
This appears to be, when you "level up", whether a visual effect will display and on what entity. See DestinyProgressionStepDisplayEffect for slightly more info.
**progressTotal**
The total amount of progression points/"experience" you will need to initially reach this step. If this is the last step and the progression is repeating indefinitely (DestinyProgressionDefinition.repeatLastStep),this will also be the progress needed to level it up further by repeating this step again.

# Destiny.DestinyItemQuantity
Used in a number of Destiny contracts to return data about an item stack and its quantity. Can optionally return an itemInstanceId if the item is instanced - in which case, the quantity returned will be 1. If it's not... uh, let me know okay? Thanks.
**itemInstanceId**
If this quantity is referring to a specific instance of an item, this will have the item's instance ID. Normally, this will be null.

**Comment by jakelauer** [comment]
Merging https://github.com/Bungie-net/api/issues/19

**Comment by jakelauer** [comment]
https://github.com/Bungie-net/api/issues/18

**Comment by jakelauer** [comment]
https://github.com/Bungie-net/api/issues/17

**Comment by hellocontrol-bng** [comment]
Merging:
https://github.com/Bungie-net/api/issues/19
https://github.com/Bungie-net/api/issues/18
https://github.com/Bungie-net/api/issues/17
