### ISSUE TITLE
Expose Random Mods on Ghosts

### ISSUE THREAD

**Issue by lowlines** [Bungie-net/api#200]
I've been testing the rolls on Ghosts bought directly from Eververse and it seems that they each have a specific subset of possible Random Mods that are tied to a specific Destination such as Honeycomb Shell being for EDZ and the Half-Submerged Shell for Titan. Having all possible roles exposed in the definitions would allow ppl to make more informed decisions on buying the featured ones each week as they might choose to re-roll a given ghost to get the most desired perks if they know its not just totally random.

**Comment by vthornheart-bng** [comment]
I consulted with our designers, and unfortunately we aren't allowed to expose that information at this time.  Sorry about that!

**Comment by wickles** [comment]
Been a year, how about now?
