### ISSUE TITLE
Trials of the Nine games not returned by GetActivityHistory

### ISSUE THREAD

**Issue by vtubelsky** [Bungie-net/api#202]
Hi there,

Looks like Destiny2.GetActivityHistory endpoint (/Destiny2/{membershipType}/Account/{destinyMembershipId}/Character/{characterId}/Stats/Activities/) ignores all TrialsOfTheNine (mode=39) games.

They are not returned neither by &mode=TrialsOfTheNine requests nor by general &mode=AllPvP requests.

Still, it looks like they are there somewhere because if, for example, a character had played 10 quickplay games, then 10 trials games and then again 10 quickplay games, "&mode=AllPvP&count=20&page=0" will return only 10 quickplay games.

Appreciate any advice/insight on this.

**Comment by floatingatoll** [comment]
This might be a dupe of #179.

**Comment by Tetron-bng** [comment]
This should be fixed now.
