### ISSUE TITLE
I would like to prohibit an application from accessing my public API data.

### ISSUE THREAD

**Issue by floatingatoll** [Bungie-net/api#204]
Currently, Bungie offers public API data to anyone with a valid API key.

I have objections to one of the applications and how they use public data. The application's privacy policy offers no recourse for 'opting out' of having my API-collected information displayed.

Does Bungie wish to offer any further recourse, or is it simply that if I play Destiny, I do so publicly and with no recourse?

**Comment by iBotPeaches** [comment]
Bungie already allows a fair amount of redaction, if you wish - https://www.bungie.net/en/Profile/Settings?category=Privacy

Outside of that no. Personally, I don't see how a 3rd application that you don't have to use is causing problems.

**Comment by vpzed** [comment]
In addition to unchecking all "allows" on the Privacy tab, a Destiny player can also uncheck "Display on public profile" for all platforms at https://www.bungie.net/en/Profile/Settings?category=Accounts

**Comment by floatingatoll** [comment]
Thank you; those are valid existing features. However, they do not speak to
the request I'm making here. I expect only Bungie can usefully reply.

**Comment by vpzed** [comment]
I'm interested in the topic but I'm unclear on the specifics of your question.  So I can better understand, what you are saying is that even with all Privacy and Account settings "unchecked" there is still data available in the API for your characters - and your question is can a given player's data be made unavailable in the API as a whole?  Or can it be made unavailable to a specific API key?  I'm unclear on the specifics and the scope.

To me it would be more clear if you provided an example of what is available with all Privacy and Account settings unchecked, and an example of the scope of the "privacy" request you are requesting.  As someone who has to work with business and technology, with the information given I would not know how to write up a case for this issue.

**Comment by floatingatoll** [comment]
I'd like to prohibit specific API applications, as registered at
Bungie.net, from accessing my account for any reason, whether to query
public or private information.

**Comment by vpzed** [comment]
Interesting.  Thanks for the clarification!

**Comment by floatingatoll** [comment]
Yep. I'm happy to discuss privately specific cases where this is of
interest to me, but in general, I wanted to get the request on the record
for due consideration.

**Comment by vpzed** [comment]
Are you on the "Destiny API Discussion" Discord server?  If so I could send you a DM to learn more.

**Comment by floatingatoll** [comment]
Nope. I'm on Bungie.net under my Github handle though.

**Comment by Tetron-bng** [comment]
We are not planning for a mechanism to block a specific application from accessing otherwise publicly available data.  From a technical perspective, this would be easy for a determined developer to circumvent.  Additionally,  we place no prohibitions on an API key since that would provide motivation for developers to steal API keys. At the moment, there is no advantage to using one API key over another, and thus no reason for a developer not to use their own assigned API key.

**Comment by floatingatoll** [comment]
Thank you!
