### ISSUE TITLE
Some Item Categories are missing

### ISSUE THREAD

**Issue by sgtfrankieboy** [Bungie-net/api#206]
According to reports the following categories are missing:
- Submachine Gun
- Grenade Launcher
- Shader

**Comment by vthornheart-bng** [comment]
Ah!  Thanks!

**Comment by rexcell99** [comment]
I believe there is a machine gun category (12) but machine guns are listed down as auto rifles (1 not 12)

**Comment by sgtfrankieboy** [comment]
I also got reports about missing the Grenade Launcher and Shader categories.

**Comment by rexcell99** [comment]
There is no Category for grenade launchers just checked 
I have written a script to down load all images from Bungie but not validated it yet to check what images if any are missing :(

**Comment by ArkahnX** [comment]
Just updating this, shaders have a category of 41, however there is no category for Trace Rifles (1345867571), Submachine Guns (2517599010) and Grenade Launchers (2168486467).

I'm not sure if this should be its own category, but Linear Fusion Rifles (2502422775) are only classified as Fusion Rifles (9) despite getting their own itemTypeDisplayName

**Comment by vthornheart-bng** [comment]
I'm going to add this to the winter wishlist - these item categories are, unfortunately, manually maintained and use some pretty jank heuristics to determine what belongs to which category.  And indeed, those categories are not returning everything accurately!  I'll try to get to this in December.

**Comment by ArkahnX** [comment]
would it help to have a itemHash list of the current set of gear that fulfills those categories?

**Comment by vthornheart-bng** [comment]
If you've already got one handy, sure!  Though don't worry about compiling one if you don't have it already: I'll end up looking through a good amount of the data as part of trying to fix the heuristics anyways.

**Comment by ArkahnX** [comment]
I'll leave it be then. Odds are by the time you would have time to get around to this, DLC2 will be out and there will be more gear

**Comment by vthornheart-bng** [comment]
Aye, more gear incoming for sure! (spoiler alert ;) )

**Comment by taralx** [comment]
FYI DIM is using InfusionCategory in the mean time, but that doesn't work for non-infusable items (like uncommon).

**Comment by vthornheart-bng** [comment]
Crapload of new item categories incoming.
