### ISSUE TITLE
Possible to get weekly Xur items?

### ISSUE THREAD

**Issue by mattbaker** [Bungie-net/api#209]
Am I correct in understanding that there's currently no way to get a list of what Xur is selling via the API? Thought I'd ask before I go down the rabbit hole.

**Comment by jgayfer** [comment]
@mattbaker Yes, that's correct, or at least was several weeks ago. As far as I know, that hasn't changed.

**Comment by mattbaker** [comment]
Great, thanks, closing.

**Comment by gaara87** [comment]
Did you manage to find an API which does this? @mattbaker

**Comment by mattbaker** [comment]
Nope, sounds like the vendor API is still in the works according to the
latest update in the README

**Comment by vthornheart-bng** [comment]
Aye, this is true.  I've had less time to work on it than I would like, and currently I still can't give a reasonable ETA for when it will be finished unfortunately.

**Comment by mattbaker** [comment]
I appreciate all your work, it’ll come when it comes :)

**Comment by gaara87** [comment]
Thanks for the update. I can help if you like, in building the api
