### ISSUE TITLE
Destiny.TierType Enums don't match in-game terminology

### ISSUE THREAD

**Issue by lowlines** [Bungie-net/api#21]
I think this is something I think has been in the APIs since D1, but now that we are all official and all, might be worth naming these to match in-game before anyone starts using them. :)

Identifier | Value | Description
-- | -- | --
Unknown | 0 |  
Currency | 1 |  
Basic | 2 |  
Common | 3 |  
Rare | 4 |  
Superior | 5 |  
Exotic | 6 |  

There might be other Enums that are still using internal development names that while most of us know what they are, other might go whaat? New item level!!

**Comment by vthornheart-bng** [comment]
Oh yeah, that thing is ancient.  Good eye!

**Comment by vthornheart-bng** [comment]
Bah, my window of opportunity closed on this, it's already out and being used.  I don't think I'm going to mess with it for now.
