### ISSUE TITLE
Feature Request: Manifest File Checksums

### ISSUE THREAD

**Issue by nine13tech** [Bungie-net/api#210]
I think I asked about this before... For some of us, it would be very nice to be able to check a downloaded .content file for completeness by verifying a checksum (like md5) and have this included as a value in the manifest endpoint.  
 I foresee something like this:
```JSON
"mobileWorldContentPaths": {
            "en": "/common/destiny2_content/sqlite/en/world_sql_content_6bc14cc5650f6485f655e5028b3cda26.content",
            "enMD5": "91380328719f1363349daf43951cfbe3", 
            "fr":...
```

**Comment by sgtfrankieboy** [comment]
The filename is the MD5 hash of the decompressed sqlite database.

**Comment by nine13tech** [comment]
Closing because of dork moment in opening this.
thanks FM.

**Comment by vpzed** [comment]
Nice!  I didn't know that the name included the md5 hash.  That is cool.

$ md5sum world_*
**ba29b7be2cdaea1cd067daa193e58ef6** world_sql_content_**ba29b7be2cdaea1cd067daa193e58ef6**.content
