### ISSUE TITLE
[Question] Get all items ?

### ISSUE THREAD

**Issue by Mandragora2** [Bungie-net/api#213]
Hi, I have tried to search how to get all items for Destiny 2 without having any profile but I do not found anything.
Anyone have a clue to do this ?

Thanks for your answer.

(PS : the search needs a term but I really want to do this very simple)

**Comment by sgtfrankieboy** [comment]
All game information is available in the Manifest file.

Information on how to read the manifest is [here](http://destinydevs.github.io/BungieNetPlatform/docs/Manifest). It's for Destiny 1 but not much has changed.

**Comment by Mandragora2** [comment]
Perfect ! Thanks for your answer @sgtfrankieboy ;)

**Comment by vthornheart-bng** [comment]
I still need to find some time to put that information up on our wiki.  But I'll close this for now as it sounds like your particular question has been resolved!
