### ISSUE TITLE
[Question]: CORS on localhost?

### ISSUE THREAD

**Issue by KrisCoulson** [Bungie-net/api#216]
I looked through the issues on here and found [issue](https://github.com/Bungie-net/api/issues/43) but I was just wondering if I am doing something wrong. I am just trying to do a small request to the API from `http://localhost:3000` is this possible the linked issue above seems like he is doing it on a local host but using some kind of proxy? Im just wondering if I actually have to go through all the trouble to make the request or if I am just missing something.

Mine doesn't fail on Access-Control-Allow-Origin it fails 
![image](https://user-images.githubusercontent.com/6943688/31481765-f03bedce-aed9-11e7-95d8-2b9dd0dec51f.png)

```
fetch('https://bungie.net/Platform/Trending/Categories/', {
      method: 'GET',
      headers: new Headers({
       'Content-Type': 'application/json; charset=utf-8',
       'X-API-Key': api_key_here,
     }),
      mode: 'cors',
      cache: 'default'
    })
      .then(res => res.json())
      .then(json => console.log(json))
      .catch(err => console.log(err.response))
```

Under browser based apps am I able to put my local pathname http://localhost:3000 I saw that the answer that helped the issue above was adding the `www` just not really sure how to approach it.

**Comment by ckhicks** [comment]
Try making your request to this URL: `https://www.bungie.net/Platform/Trending/Categories/`

**Comment by KrisCoulson** [comment]
@ckhicks  okay now that works thank you so much! I think its confusing because the documentation says the root path is `https://bungie.net/Platform`. Thanks again!

**Comment by KrisCoulson** [comment]
For anyone in the future that might see this issue adding `www` to the root path solved the problem 
`https://www.bungie.net/Platform/`
