### ISSUE TITLE
{Results}{ThrottleSeconds}

### ISSUE THREAD

**Issue by CrunchyWizard47** [Bungie-net/api#217]
I can't find a reference to this anywhere - do I need to monitor this field to delay my next call, or is this a flag telling me that Bungie is going to delay my next call?

**Comment by rking788** [comment]
There are error code values that will be returned and the error status string will indicate you are being throttled. In my experience I have not seen this throttle seconds field with anything useful in it. Here is a link to the list of error codes you can search for all containing “throttle”: https://bungie-net.github.io/multi/schema_Exceptions-PlatformErrorCodes.html#schema_Exceptions-PlatformErrorCodes

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by CrunchyWizard47** [comment]
Thanks, I'm sure I'm one of their smaller sources of traffic but I want to make sure I'm hitting them responsibly as I go through 100 clan members, their activities and PGCRs.

**Comment by rking788** [comment]
I think the general rule of thumb from my testing has been approximately 10 requests to the same endpoint per second. I'm not sure that is official so just use it as a guideline maybe.

**Comment by CrunchyWizard47** [comment]
Looks like the value is an average of 25 requests per second over ten seconds, per this [link](https://github.com/Bungie-net/api/issues/26#issuecomment-334900673)

**Comment by rking788** [comment]
I was actually just coming back to this issue to link to that issue. I finally made it further down my github notifications ;)
