### ISSUE TITLE
PerEndpointRequestThrottleExceeded

### ISSUE THREAD

**Issue by afehners** [Bungie-net/api#218]
More a question than an issue. I sometimes get PerEndpointRequestThrottleExceeded returned when making a large set of requests, but I also sometimes get it back when not making that many.

I've got some rate limiting client side for times when I need to make a lot of calls. Sometimes I see this returned for 50 requests in a 1 second window. Other times it will happily return results for 80 requests in a 1 second window. 

Is this throttling per endpoint as the error suggests? Does each endpoint have a different limit? Is there a way to find out the limits so we know which endpoints should be used sparingly? Is the limit per client IP or per API key?

**Comment by ckhicks** [comment]
Not sure about per-resource limits, but there's some great info in this thread about rate limiting in general: https://github.com/Bungie-net/api/issues/26#issuecomment-334900673

**Comment by afehners** [comment]
Thanks @ckhicks, that explains why I couldn't figure out a concrete per second threshold as its 25/second but averaged over a 10 second window. it also seems per Endpoint is not the API endpoint being called by refers to the client making the calls..
So its 25 calls per second per IP over a 10 second period.

**Comment by Tetron-bng** [comment]
@afehners nailed it.

**Comment by afehners** [comment]
Thanks for confirming @Tetron-bng 

I guess this can be closed, but maybe this info could be added to the docs so others can find it?
