### ISSUE TITLE
Proposal: Add metadata about generics

### ISSUE THREAD

**Issue by vthornheart-bng** [Bungie-net/api#22]
The following issue has spun up into a separate subject that's worth addressing:

https://github.com/Bungie-net/api/issues/6

Right now, Swagger doesn't seem to have good conventions for relaying information about generics: info that would be useful for developers.

The current proposal is that we add metadata about generic properties - which would also imply that we should add schema for the base generic classes.

I'm not opposed to this idea, though I don't know if we'll have time to do it before launch.

Please discuss here: and if you have insight into the OpenAPI spec that you'd like to share for common patterns of addressing information such as generics (or if you just have an opinion about how you'd like this data to be conveyed), lay them on us!

**Comment by lowlines** [comment]
So an example would be...
```javascript
"DictionaryComponentResponseOfint32AndDestinyItemInstanceComponent": {
    "x-generic-key": {
        "type": "integer",
        "format": "int32"
    },
    "x-generic-value": {
        "$ref": "#/components/schemas/Destiny.Entities.Items.DestinyItemInstanceComponent"
    },
    "properties": {
    ...
    }
}
```

**Comment by vthornheart-bng** [comment]
(oy, I just cut out like 2 pages of thoughts about how we ought to do this, I now think it's a bad idea so I'm not even going to bring it up)

I just had a thought, perhaps we're attempting to fix the wrong problem.  If the useful gain we get is mostly in the base class properties that they have in common, perhaps we can forsake this metadata and my generator could instead just strip those out and make it a non-generic base class, and any generic properties get defined on these actual contracts.  So in the DictionaryComponentResponse example above, the base DictionaryComponentResponse class could be defined in the schema with the "privacy" property, and inheritors would define the "data" property independently.  Similarly, ResponseContainer could be a base class defining everything but "Response", and we'd leave it up to the various response contract classes themselves to define Response independently.  That would be *slightly* less convenient, in theory, for languages that support generics: but it'd be more useful in the general case, and our schema would basically be doing the job that the compiler currently does for the generic anyways.  Benefits of generics - like compile-time type safety - aren't really relevant here, because we're already guaranteeing type safety to you by generating separate classes for every variant that we actually use.  

Hmm... yes, I think I've talked myself out of this.  I think what I really need to do is make it output base classes, and if those base classes happen to be generic then the generic properties of those base classes would instead be defined on the concrete contract classes.  It would be a neat trick to return generic information, but I'm less convinced now that it would actually be *useful*.

Thoughts?

**Comment by lowlines** [comment]
I haven't really felt they are all that useful at all. They are only there as an extra declaration as to what is inside them. I'm just trying to understand what that extra information is and how it should be represented if its going to be in the API spec. I've been stuck thinking about these for the last couple of days, which has kinda slowed any progress I was making with the Unofficial docs. Removing them entirely would make my life easier, I'm just not sure about others and how they intend to use the spec.

**Comment by vthornheart-bng** [comment]
Yeah, don't let the generics bog you down: just treat them as-is for now.  I think the generics concept as a whole is definitely not worth it: eventually when I get time I'll add in support for inheritance in the responses I send down, and ideally at that point you can just re-run whatever generator you're making (potentially with support for the "oneOf" property if you don't already have it) and then it should work without having to worry about new extension properties.  

But I don't know when I'm going to be able to get to that, so feel free to just keep moving forward and don't concern yourself with the generics nor with potential base classes.  That can be a future enhancement for us both!

**Comment by vthornheart-bng** [comment]
After sitting on this for a bit, I decided that I definitely don't think they're useful enough to add a ton of metadata and do a lot of work to get them properly exposed.  I'm going to mark this one as won't fix, and we can revive it if anyone comes up with a really useful reason why the generic metadata would be handy.
