### ISSUE TITLE
Mod Image files

### ISSUE THREAD

**Issue by rexcell99** [Bungie-net/api#226]
Can anyone point me to the section of the manifest that  has consumbels icons and mod icons

I have looked through but cant seem to find them
Thanks in advance

**Comment by vpzed** [comment]
Search in DestinyInventoryItemDefinition for entries with an itemCategoryHashes array which includes 56 (Mods) or 35 (Consumables).  Then look at the displayProperties.icon field of those records.

**Comment by vpzed** [comment]
If you are using the SQLite file and have a SQLite client with the JSON1 extensions enabled you can use a query like this one.  This is for Mods.

    SELECT json_extract(DestinyInventoryItemDefinition.json, '$.displayProperties.name'), 
    json_extract(DestinyInventoryItemDefinition.json, '$.displayProperties.icon')
    FROM DestinyInventoryItemDefinition, 
    json_each(DestinyInventoryItemDefinition.json, '$.itemCategoryHashes')
    WHERE json_each.value LIKE '56';

I just tested it in DB Browser for SQLite.

**Comment by rexcell99** [comment]
Thanks for that a great help 

Looks like there a few missing icons though no sure if they are used or not.
but that is for another day 

One again thanks for the help vpzed
