### ISSUE TITLE
Destiny2.GetCharacter endpoint not returning DestinyCharacterNotFound when Account does not own the Character ID passed

### ISSUE THREAD

**Issue by maciek134** [Bungie-net/api#240]
Noticed this today, I've not been using this endpoint in a while, now with this CURL:
``` curl -L -A "test" -H "X-API-Key: REDACTED" https://www.bungie.net/Platform/Destiny2/2/Profile/4611686018459911023/Character/2305843009262888206/\?components\=200,204```
I get this (useless) response:
```{"Response":{"itemComponents":{}},"ErrorCode":1,"ThrottleSeconds":0,"ErrorStatus":"Success","Message":"Ok","MessageData":{}}```
It was working before and I think it's properly written according to the documentation. Did something break or was changed and not reflected in the docs?

**Comment by vthornheart-bng** [comment]
Hmm, it seems to be that the root cause is that the Profile ID does not have a character with that ID.

The API really should be passing a DestinyCharacterNotFound in this situation - I'm going to log a bug for that.  But just to note the only characters I see on that account are:

2305843009278436012
2305843009278478629
2305843009293444745

**Comment by maciek134** [comment]
Sorry about that, that's an id of a character I deleted, forgot to update as this is a scratchpad script with hardcoded values. Now it makes sense.

**Comment by vthornheart-bng** [comment]
No worries!  You still found a good bug, so it's all good - it definitely would have been more obvious had we passed back DestinyCharacterNotFound.

**Comment by JakobHartman** [comment]
Still getting this bug, although I don't understand why i'm getting it when i'm passing the characterids retrieved with that player ID

**Comment by JakobHartman** [comment]
Actually i think i figured it out, didnt understand that the components returns certain things and i maybe using the wrong one

**Comment by vthornheart-bng** [comment]
Ah, understandable - let me know if there's anything in the future we can help with!
