### ISSUE TITLE
How To

### ISSUE THREAD

**Issue by rexcell99** [Bungie-net/api#247]
Not really an  issue more a question

I have been working a phone app and really for load outs to be honest but i have a design question

is it ok for the phone to directly request the data from Bungie 
Phone -> Nungie
or should it be 
Phone -> Myserver - Bungie ?

the reason I ask is using the second method you cant control the amount of request to Bungie

Hope the question makes sense

**Comment by kbreit** [comment]
I think most Destiny applications go directly to Bungie. If you need to store special information, such as loadouts for synchronization, you may need to have some server contact. But my application goes to Bungie and has no intermediary system.

**Comment by Tetron-bng** [comment]
Yup.  Going directly to Bungie.net is fine.
