### ISSUE TITLE
Raid rotation

### ISSUE THREAD

**Issue by kbreit** [Bungie-net/api#249]
How do I glean the raid encounter order from the API?

**Comment by vthornheart-bng** [comment]
Ah, I've been meaning to ask around about this!  I'll try to get an answer about whether we'll be allowed to return that info soon.

**Comment by kbreit** [comment]
vt - Have you heard back about whether we'll have this information in the medium term?

Disclaimer: Medium term means whatever we want it to :)

**Comment by vthornheart-bng** [comment]
Ah, thank you for circling back on this, I had neglected to update!  I was told that we can for the current Raid, but if/when other Raids come up in a future there will be a period of time where they will not allow me to reveal that information... so just as a heads up, this lag between when the game does it and when we expose it in the API is unfortunately likely to continue as a policy. :(

I need to find some time to work on actually exposing it now that I've gotten the all-clear for the current raid, but unfortunately it is a low priority at this time.  I'm hoping that there will be some time toward the end of the year for me to work on some lower priority data exposure asks, I'm going to tentatively flag this as one of those so I know to loop back on!

**Comment by kbreit** [comment]
My $.02...

I expect that if/when new raids are released there will be a lag between release and all the data being exposed in the API. Once content has been out for a while I would like to see it in the API, but that's after it's well known and there are no surprises.

**Comment by vthornheart-bng** [comment]
Aye, that was the design team's sentiment as well.  Good deal.  I just have to find some time to get it exposed at this point!

**Comment by v-fedorov** [comment]
If it helps, each raid order has its own activity instanceId in the manifest.
thats probably the only way to check atm
