### ISSUE TITLE
OAuth Token Endpoint "Cannot parse client_id"

### ISSUE THREAD

**Issue by BobaFetters** [Bungie-net/api#25]
I'm trying to get OAuth up and running using a public client type, I get my authorization code from the Authorization endpoint but when trying to send a request to the Token endpoint I always get a "400 - Cannot parse client_id".

I am setting client_id, grant_type, and code in the body of my POST request with "application/x-www-form-urlencoded" as the Content-Type. Can anyone point me in the right direction here?

**Comment by lowlines** [comment]
Have you had a look at the Unofficial Wiki documentation for it yet? I also make an interactive tool for testing as well (link in the wiki)
https://destinydevs.github.io/BungieNetPlatform/docs/Authentication

**Comment by BobaFetters** [comment]
Yea I have checked that stuff out already as well as the Official OAuth doc page to no avail, was trying to figure out if anyone else was experiencing the issue or if I am doing something wrong with passing the client_id in the form body of the POST request

**Comment by ascendancyy** [comment]
Maybe just omit client_id and client_secret from the post body and use authentication?  
[HTTP Authentication](https://www.ietf.org/rfc/rfc2617.txt). See Section 2.  

Basically just add an Authorization header.
`Authorization: Basic base64(client_id:client_secret)`

**Comment by BobaFetters** [comment]
@ascendancyy Thanks for the tip, moving the client id and secret both in the Authorization header along with a small tweak to the format of my Post body resolved my issues

**Comment by floatingatoll** [comment]
Could you describe with before/after examples what your POST body looked like structurally, so that others may learn from it?

**Comment by BobaFetters** [comment]
@floatingatoll yea sure thing, basically the issue stemmed from trying to take a dictionary of key value pairs and convert them into data to be used as the form body so originally I had something similar to the following pseudocode:

dict["grant_type"] = "authorization_code"
dict["code"] = (code)
formBody = dict.convertToData()

what I ended up needing to do to get this to work for me was build a string of parameters to convert to form data instead like:

string = "grant_type=authorization_code&code=(code)
formBody = string.convertToData()

**Comment by Pandazaur** [comment]
Hello, I had the same issue and solved it in Javascript

```javascript
static async postAuthorizationCode (code) {
        const response = await fetch(CONFIG.bungie.tokenUrl, {
            method: 'POST',
            headers: {
                 'X-API-Key': CONFIG.bungie.apiKey,
                 'Content-Type': 'application/x-www-form-urlencoded'
            },
            body: this.createFormParams({
                grant_type: 'authorization_code',
                client_id: CONFIG.bungie.oAuthClientId,
                code,
            })
        })
        console.log(await response.json())
        return await response.json()
    }

   static createFormParams (params) {
        return Object.keys(params)
            .map((key) => `${encodeURIComponent(key)}=${encodeURIComponent(params[key])}`)
            .join('&')
    }
```

First, I tried to post data with `axios` npm module but it failed. Don't forget to add your "Origin" to the settings of yout Bungie app
