### ISSUE TITLE
[Question] Can't find a reference for all post game carnage report stats.

### ISSUE THREAD

**Issue by JAMeador13** [Bungie-net/api#251]
I'm trying to build my own database of previous activities for my clan, but I can't find an efficient way of setting it up. The only solution I've had so far is to just create the fields as I go through the data, but that would cause issues down the line that are just not worth the headache. 

Basically, I'm just asking if there's something I've overlooked in the documentation or in the manifest that has all of the possible stat names and IDs already aggregated together.

**Comment by vpzed** [comment]
The manifest has the DestinyHistoricalStatsDefinition table with has a mapping of stat names to other stat information.  Does this not have what you need?

**Comment by JAMeador13** [comment]
Ahh, for some reason I had looked at that table and thought it was deprecated. *crawls under rock*
