### ISSUE TITLE
Historical Stats aggregate data is incomplete or incorrect 

### ISSUE THREAD

**Issue by Tomalaya** [Bungie-net/api#252]
I run a stats bot for my clan, and pull stats for comparative analysis.  After the 1.08 Destiny upgrade, we're seeing errors in stat reporting for the aggregate activities game mode, like AllPvE (7).

For instance, running the query 
https://www.bungie.net/Platform/Destiny2/2/Account/4611686018444733778/Character/2305843009261741213/Stats/?modes=6&groups=General

Show that for just Patrol (6) Activites, the character has 6512 Auto Rifle kills, but switching Game mode 6 (Patrol) to 7 (AllPvE):

https://www.bungie.net/Platform/Destiny2/2/Account/4611686018444733778/Character/2305843009261741213/Stats/?modes=7&groups=General

The AutoRifles kill field show a total of only 300.  This should be at least the same as Patrol, a PvE activity, and most likely a greater number

This is not happening with all clan members, but is happening to a certain set, in both the the AllPvE and AllPvP mode categories, and had been working prior to to 1.08 time frame.

**Comment by vthornheart-bng** [comment]
Ah, try again in an hour or so - this just happens to be exactly the reason why we're releasing a hotfix as we speak this morning!  Hang tight and try again once this deployment finishes (give it an hour or so from now).

**Comment by Tomalaya** [comment]
Thx, numbers seem to back inline now.  Fix looks good
