### ISSUE TITLE
Converting 3d units to real world units

### ISSUE THREAD

**Issue by lowlines** [Bungie-net/api#254]
As suggested by @vthornheart-bng I've posted this here. I want to know how to scale 3d models to real world units (metres) so when they are rendered in something like an AR project, they are to scale. IIRC they are stored in the tgx files in the range of -1.0 to 1.0 units.

**Comment by ckhicks** [comment]
Have you seen the STL converter from D1? It was pretty accurate in the various tests I ran, when going from TGX > STL > OBJ > threejs/aframe. I wonder if we could render some out without the middleman and do some real-world calculations in AR?

**Comment by lowlines** [comment]
My TGX Loader converts TGX > three.js directly.
https://lowlidev.com.au/destiny/gear-viewer

Source code is on github too. I've added basic support for D2 models but I haven't pushed that to the repo yet.
https://github.com/DestinyDevs/BungieNetPlatform/tree/master/three-tgx-loader

**Comment by ckhicks** [comment]
Haha, I was using it the other day! Appreciate your work there. 
Definitely something I'm trying to solve as well - I wasn't sure if the 
measurements to STL would help at all, but I suppose the extra step 
isn't needed. Have you worked on full armor sets yet? That's what I'm 
working on right now...

**Comment by lowlines** [comment]
The version on the github right now should already support loading full armor sets. Not shaders though. I was previously working on trying to get animations working, but was struggling to convert them to work with three.js.

**Comment by vthornheart-bng** [comment]
Okay, so what I've been told is:

"In the metadata associated with the render models, there should be an array of ‘render_meshes’, and each render mesh should have a vec3 for scale (position_scale), and another vec3 for translation (position_offset)."

Apparently this is located in the .tgxm files, and their units equate to approximately 1 unit = 1 meter.

**Comment by ckhicks** [comment]
Man, this is excellent info for those of us playing with AR. :D Thanks 
so much!

**Comment by vthornheart-bng** [comment]
No prob!

**Comment by lowlines** [comment]
I can't remember if I applied those values or not. Knowing the unit conversion rate is exactly what I was after though! 👍
