### ISSUE TITLE
Clan Banners

### ISSUE THREAD

**Issue by mikewojtkiewicz** [Bungie-net/api#255]
I am trying to make sense of Clan Banners in the api. Perhaps I don't remember my html as well as I thought, but does anybody have any ideas as how to implement them on to an html page? I'm using php, and getting the data from the manifest, but I don't understand how the primary / secondary / gonfalon colors are supposed to work. And further, how would one layer these images on top of each other to get it to look similar to the Clan Banners on bungie.net or in game? I know how to layer images, but I can't seem to find the base banner image (the image that holds the decal and all of it's colors). Any help would be appreciated.

**Comment by xlxCLUxlx** [comment]
Hi,

You will probably want to use an HTML5 Canvas to display the different layers.  I believe this is what Bungie is doing for the Clan Banner Editor.  However, for the main clan page they use a base64 image that is decoded using the css `<url>` data type is specified using the `url()` functional notation.

You can also refer to [Issue 125](https://github.com/Bungie-net/api/issues/125).  I did my best to explain the clanbanner_sql_content database  as well as how colors get applied.  I will be revisiting this issue in a few days to add some images that show the process.

**Comment by mikewojtkiewicz** [comment]
Thanks, I think I have a grasp on using a HTML canvas, but I'm still unsure about how the color content works. Do you have any advice for how I would apply the these rgb values to the decal and gonfalon ids? I'm using php and trying to do this the function called putImageData, but I don't think I'm doing it correctly.

**Comment by xlxCLUxlx** [comment]
This function seems to do the trick (credit can be found in the link below).  I did a quick test from the command line and it filled the image color properly.

[Php - replace base color of transparent png image](https://stackoverflow.com/a/26792716)

```php
function colorizeBasedOnAplhaChannnel($file, $targetR, $targetG, $targetB, $targetA, $targetName) {
	$im_src = imagecreatefrompng($file);

    $width = imagesx($im_src);
    $height = imagesy($im_src);

    $im_dst = imagecreatefrompng($file);

    // Turn off alpha blending and set alpha flag
    imagealphablending($im_dst, false);
    imagesavealpha($im_dst, true);

    // Fill transparent first (otherwise would result in black background)
    imagefill($im_dst, 0, 0, imagecolorallocatealpha($im_dst, 0, 0, 0, 127));

    for ($x=0; $x<$width; $x++) {
        for ($y=0; $y<$height; $y++) {
            $alpha = (imagecolorat( $im_src, $x, $y ) >> 24 & 0xFF);

            $col = imagecolorallocatealpha( $im_dst,
                $targetR - (int) ( 1.0 / 255.0 * (double) $targetR ),
                $targetG - (int) ( 1.0 / 255.0 * (double) $targetG ),
                $targetB - (int) ( 1.0 / 255.0 * (double) $targetB ),
                (($alpha - 127) * $targetA) + 127
            );

            if (false === $col) {
                die( 'sorry, out of colors...' );
            }

            imagesetpixel( $im_dst, $x, $y, $col );
        }
    }

    imagepng( $im_dst, $targetName);
    imagedestroy($im_dst);
}
```

So if you have the following JSON for example:

```json
{
   "colorHash":3396165378,
   "red":213,
   "green":131,
   "blue":55,
   "alpha":255
}
```

You could call `colorizeBasedOnAplhaChannnel($file, $targetR, $targetG, $targetB, $targetA, $targetName);`

$file = the file you want to apply the color to.
$targetR = 213 from our JSON snippet above.
$targetG = 131 from our JSON snippet above.
$targetB = 55 from our JSON snippet above.
$targetA = 1 which represents 255 from our JSON snippet above.
$targetName = the name of the new file to save as

**Comment by mikewojtkiewicz** [comment]
Thanks. This is a good start to get me going.

**Comment by mikewojtkiewicz** [comment]
On second thought, this solution isn't working either. I don't think the coloring is happening correctly. Everytime the png file is saves, it saves as black instead of the proper color. The issue is happening on this block of code:
`                          $col = imagecolorallocatealpha( $im_dst,
                              $targetR - (int) ( 1.0 / 255.0 * (double) $targetR ),
                              $targetG - (int) ( 1.0 / 255.0 * (double) $targetG ),
                              $targetB - (int) ( 1.0 / 255.0 * (double) $targetB ),
                              (($alpha - 127) * $targetA) + 127
                          );`
Do you have any thoughts?

**Comment by mikewojtkiewicz** [comment]
Wait...the I found the issue. The alpha channel coming from the bungie server has a range of 0-255, but this code is expecting 0-1. I changed this, and we're good to go.

**Comment by xlxCLUxlx** [comment]
Hi @mikewojtkiewicz,

You can actually just ignore the alpha channel from Bungie.  This will always be 255 except for one color that is transparent.  The reason you will see these as all 255 (opaque) is because they build the colors for users to select through there web interface when editing their banner.  You will also notice an order column in the tables that the JSON is coming from in regards to colors.  This is the order in which they display the colors in their drop down picker.

You are correct on the range for that function would be 0-1 (in case you would want to use 1).  Glad you got it working.
