### ISSUE TITLE
Meditations refresh hours after weekly reset

### ISSUE THREAD

**Issue by kbreit** [Bungie-net/api#256]
I've noticed Meditations change, both in the API and game, a bunch of hours after the weekly reset. Is this intentional or an open bug? If it's intentional, when is the time it's set to refresh?

**Comment by floatingatoll** [comment]
It’s almost certainly 8 hours after reset, aligned with Bungie’s usual approach to “wait until daytime” launches.

**Comment by floatingatoll** [comment]
See also: https://www.reddit.com/r/DestinyTheGame/comments/76xamn/reminder_you_can_do_ikora_missions_twice_a_week/

**Comment by vthornheart-bng** [comment]
Aye, I believe this is intentionally designed this way: either way, it's out of the API's control.  We're just doing what the game tells us.  If the game ever changes it, it'll change for us too!
