### ISSUE TITLE
Destiny2.SearchDestinyPlayer - PC users - Nothing found

### ISSUE THREAD

**Issue by ashleypb** [Bungie-net/api#259]
Im trying to find PC players including myself using the same endpoint thats working fine for both Xbox & PS4, obviously replacing (1 - Xbox, 2 - PS4, 4 - Blizzard)

`www.bungie.net/Platform/Destiny2/SearchDestinyPlayer/4/'.$player.'/`

Nothing is being returned?

Ive tried the in game name as displayed also with the blizzard number `#0000` after but nothing?

If i replace '4' with '-1' for all, i get the error `DestinyInvalidMembershipType`

Can someone point me it the right direction.

**Comment by dad2cl3** [comment]
Try this https://github.com/Bungie-net/api/issues/258

**Comment by vthornheart-bng** [comment]
Did that work out for you @ashleypb ?
