### ISSUE TITLE
Proposal: Response header indicating "you'll be rate-limited soon"

### ISSUE THREAD

**Issue by floatingatoll** [Bungie-net/api#26]
Please consider adding a response header to API requests that indicates something like "We would appreciate it if you make this request less frequently, and will rate-limit you if you ignore us; please wait at least X seconds before sending it again".

I've seen this done *after* a rate-limit event occurs, and it's invaluable in that scenario *as well*, where you say "Your rate limit will expire in X seconds", so that clients can schedule a timer and stop bothering the server.

It also provides several opportunities:

- By randomizing X slightly (+/- 1%) you ensure a more even distribution of API clients over time, whether in reaction to an outage or simply load.
- You can yourself and cellular users a lot of pointless requests during partial outages by including X=300 +/- seconds in your *downtime* responses, so that well-implemented clients override their native retry interval (which will always be the minimum permitted).
- Clients that frequently make expensive requests can be assigned a higher X due to the cost of the queries.

So, this would (I'm making this up on the fly) look something like:

`X-Rate-Limit: pause=67`

Long-term, there's another interesting point. If you simply declare this a header that's mandatory to support, then you also gain the ability to stop advertising hard limits and can instead calibrate your rate limits dynamically, based on server load and all that jazz, using X-SDP headers:

`X-Rate-Limit: pause=0, interval=31` (30 +/- randomized)

There's probably months of work possible down these lines of thinking to make a rockstar-grade API with server-autotuned refresh intervals granular to endpoints, so I'm going to pause here and let you consider the idea in general first :)

**Comment by floatingatoll** [comment]
Note that at bare minimum, my request can be boiled down to these two assertions:

When someone is rate limited, they should receive an indication of when the limit will expire - and that indication should be a # of seconds that's been random fuzzed by +0..1% or so to prevent lockstep problem.

When someone is on the verge of being rate limited, they should receive an indication that this is so, and given an opportunity to backoff for the stated # of seconds on their own before triggering the actual rate limit. By setting this to occur at about 80% of the actual limit, it gives "automated" farming modes a chance to keep themselves in check, while leaving the remaining 20% for user-initiated transfers and quest progress and so on.

**Comment by vthornheart-bng** [comment]
I definitely like the idea!  When we get some time, I'd like to see this - or some variant of this - become a reality.  It'd definitely be nice to have.

**Comment by floatingatoll** [comment]
X-Rate-Limit: waitfor=37, interval=45, endpoint=/pgcr/

Would be pretty stellar, if you want to customize the refresh intervals
*per endpoint*. Much more applicable to /show/me/my/engrams/, less
applicable to /transfer/something/, more applicable to /pgcr/forever/, less
applicable for /pgcr/recent/, etc.

Have fun!

**Comment by floatingatoll** [comment]
(And obviously clients can just ignore it if they want to, and get rate
limited like everyone else, and be happy with that.)

**Comment by ascendancyy** [comment]
I know the reddit api uses:  

```
X-Ratelimit-Used (Requests used in this period)
X-Ratelimit-Remaining (Requests left in this period)
X-Ratelimit-Reset (Time until period resets)
```

A set number of requests per period is allocated to the client (In reddit's case I think it's 600 requests per period with each period lasting 10 minutes. Making it equal to 1 req/s). This allows for clients to send as fast or as slow as they need within their period. And it allows the server to possibly change the request amount per period based on server loads.  

The per-endpoint idea would be interesting. Could help with endpoints that are more intensive on the server or are hit frequently.

**Comment by Tetron-bng** [comment]
Our current mechanism averages requests over a rolling 10 second window.  When an endpoint (identified by source IP address) exceeds (currently) 25 requests per second we block that request. Requests will continue to be blocked until the average drops below 25 requests per second.  With this info, it should be possible for a client to avoid exceeding the limit and quickly recover from being limited (by waiting a few seconds).

Our objective is to protect our servers from over zealous, or malfunctioning clients. Would a finer grain of control and feedback help us achieve that goal?

**Comment by floatingatoll** [comment]
Not that I can think of. Reporting "25 average requests per second" and
"rolling window of 10 seconds" in a response header would let motivated app
authors code against the limits dynamically rather than hard-coding 25/10,
but I honestly don't think this matters much to most API use cases, so I
understand if you choose not to report that.

**Comment by vpzed** [comment]
@Tetron-bng That is some really good information on the specifics of rate limits.  Thank you!

**Comment by floatingatoll** [comment]
Oh, I didn’t realize this was the first time we knew that. Thank you also! The replies are really appreciated.

**Comment by afehners** [comment]
"25 average requests per second" and "rolling window of 10 seconds" is gold. 
I've been trying to figure out the current per second rate limit but knowing its over a 10 second window allows me to tune my rate limiting client side rather than a finger in the air guess based on past observations
