### ISSUE TITLE
Best way to get Destiny profile from Bungie.net profile?

### ISSUE THREAD

**Issue by HittmanA** [Bungie-net/api#262]
I am trying to get the Destiny profile based off of a user's Bungie.net profile. Unfortunately, I don't know how to get their membership type (PC, PS4, Xbox) based off of their Bungie.net profile. What would be the best way of doing this?

**Comment by floatingatoll** [comment]
Keep in mind that they may have anywhere from 1 to 3 membership types, not just “always 1 only”.

**Comment by HittmanA** [comment]
What do you recommend doing? Asking the user what membership type they want to use?

**Comment by Tetron-bng** [comment]
https://bungie-net.github.io/multi/operation_get_User-GetMembershipDataById.html#operation_get_User-GetMembershipDataById

**Comment by HittmanA** [comment]
@Tetron-bng what membership type do I input? All?

**Comment by HittmanA** [comment]
Ok thanks, this is exactly what I needed!

**Comment by HittmanA** [comment]
Hmmm. It's not returning the destiny memberships. When I make the request I get:
```
{
	"Response": {
		"destinyMemberships": [],
		"bungieNetUser": {
			"membershipId": "7883748",
			"uniqueName": "7883748",
			"displayName": "HittmanB",
			"profilePicture": 0,
			"profileTheme": 0,
			"userTitle": 0,
			"successMessageFlags": "0",
			"isDeleted": false,
			"about": "",
			"firstAccess": "2014-10-06T04:21:27.928Z",
			"lastUpdate": "2014-10-06T04:21:27.928Z",
			"showActivity": true,
			"locale": "en",
			"localeInheritDefault": false,
			"showGroupMessaging": true,
			"profilePicturePath": "/img/profile/avatars/default_avatar.gif",
			"profileThemeName": "d2cover",
			"userTitleDisplay": "Newbie",
			"statusText": "",
			"statusDate": "0001-01-01T00:00:00Z"
		}
	},
	"ErrorCode": 1,
	"ThrottleSeconds": 0,
	"ErrorStatus": "Success",
	"Message": "Ok",
	"MessageData": {}
}
```
Why doesn't it return anything in the destinyMemberships when I know I have a ps4 membership?

**Comment by dad2cl3** [comment]
@HittmanA I searched for you on bungie.net and no results returned for Destiny. Have you linked your psn to your Bungie.net account?

**Comment by HittmanA** [comment]
@dad2cl3 my Bungie.net name is HittmanB not HittmanA. Yes, I am sure I have linked my accounts.

**Comment by dad2cl3** [comment]
I searched HittmanB per the json above. Here's what I found.
![screen shot 2017-10-25 at 12 08 38 pm](https://user-images.githubusercontent.com/25552783/32009522-5d5ffcb2-b97d-11e7-8ca7-31f56d240e1c.png)

**Comment by dad2cl3** [comment]
Searching myself
![screen shot 2017-10-25 at 12 08 53 pm](https://user-images.githubusercontent.com/25552783/32009538-6921e7fe-b97d-11e7-8176-8d77064ce399.png)

**Comment by dad2cl3** [comment]
Next I would check your permissions in your account on bungie.net

**Comment by HittmanA** [comment]
My PSN name is different from my bungie.net name as well (so many different usernames).

**Comment by HittmanA** [comment]
I have also confirmed I gave all permission to the application in my account settings.

**Comment by dad2cl3** [comment]
The setting on bungie.net removes my Destiny information from my bungie.net results

![screen shot 2017-10-25 at 12 10 39 pm](https://user-images.githubusercontent.com/25552783/32009646-a174e5fc-b97d-11e7-873c-e8ee34234f24.png)

**Comment by dad2cl3** [comment]
Before

{
  "Response": {
    "destinyMemberships": [
      {
        "iconPath": "/img/theme/destiny/icons/icon_psn.png",
        "membershipType": 2,
        "membershipId": "4611686018444413962",
        "displayName": "dad2cl3"
      }
    ],
    "bungieNetUser": {
      "membershipId": "10071956",
      "uniqueName": "10071956",
      "displayName": "dad2cl3",
      "profilePicture": 70496,
      "profileTheme": 11,
      "userTitle": 0,
      "successMessageFlags": "0",
      "isDeleted": false,
      "about": "",
      "firstAccess": "2015-03-01T04:20:24.8Z",
      "lastUpdate": "2017-07-05T23:06:32.464Z",
      "psnDisplayName": "dad2cl3",
      "showActivity": true,
      "locale": "en",
      "localeInheritDefault": true,
      "showGroupMessaging": true,
      "profilePicturePath": "/img/profile/avatars/Destiny05.jpg",
      "profileThemeName": "d2cover",
      "userTitleDisplay": "Newbie",
      "statusText": "",
      "statusDate": "0001-01-01T00:00:00Z"
    }
  },
  "ErrorCode": 1,
  "ThrottleSeconds": 0,
  "ErrorStatus": "Success",
  "Message": "Ok",
  "MessageData": {}
}

**Comment by dad2cl3** [comment]
After

{
  "Response": {
    "destinyMemberships": [],
    "bungieNetUser": {
      "membershipId": "10071956",
      "uniqueName": "10071956",
      "displayName": "dad2cl3",
      "profilePicture": 70496,
      "profileTheme": 11,
      "userTitle": 0,
      "successMessageFlags": "0",
      "isDeleted": false,
      "about": "",
      "firstAccess": "2015-03-01T04:20:24.8Z",
      "lastUpdate": "2017-10-25T16:10:55.46Z",
      "showActivity": true,
      "locale": "en",
      "localeInheritDefault": true,
      "showGroupMessaging": true,
      "profilePicturePath": "/img/profile/avatars/Destiny05.jpg",
      "profileThemeName": "d2cover",
      "userTitleDisplay": "Newbie",
      "statusText": "",
      "statusDate": "0001-01-01T00:00:00Z"
    }
  },
  "ErrorCode": 1,
  "ThrottleSeconds": 0,
  "ErrorStatus": "Success",
  "Message": "Ok",
  "MessageData": {}
}

**Comment by HittmanA** [comment]
Hmmm. I thought the request was supposed to show even hidden accounts.

**Comment by dad2cl3** [comment]
Pretty sure GetMembershipsById is a public request.

**Comment by HittmanA** [comment]
Maybe is it because I don't have an auth header?

**Comment by dad2cl3** [comment]
Let me grab a token for my account and I'll test

**Comment by HittmanA** [comment]
Ok, thanks

**Comment by HittmanA** [comment]
I just tested an yes, you need an auth token to get hidden accounts. I just discovered my token wasn't being sent properly so it messed everything up.

**Comment by dad2cl3** [comment]
Cool because I can't find my test script for authenticated calls! :-)

**Comment by HittmanA** [comment]
:) Thanks for helping by the way.
