### ISSUE TITLE
How to get Milestone data?

### ISSUE THREAD

**Issue by HittmanA** [Bungie-net/api#265]
I have a list of milestones via /Destiny2/Milestones/ but all I have is a milestone hash. I need to get information like the name, about, rewards, etc. I saw [this](https://bungie-net.github.io/multi/schema_Destiny-Definitions-Milestones-DestinyMilestoneDefinition.html#schema_Destiny-Definitions-Milestones-DestinyMilestoneDefinition) in the docs but I am not sure how to get that data with the milestone hash. How can I do that in nodejs?

**Comment by vthornheart-bng** [comment]
Ah, you're about to get knee deep in it!  I apologize as it's a bit of a pain, but the reward once you get your pipeline figured out for acquiring and maintaining this data is that you'll have access to the giant ocean of localized content that is the Destiny Manifest databases!

Read here for more info, the guide that Lowlines wrote back in the D1 days still applies and is still the most authoritative subject on what the Manifest Database is and some good techniques for acquiring and updating it.  It's a bit of a doozy, but give it a read through and feel free to ask questions here!

http://destinydevs.github.io/BungieNetPlatform/docs/Manifest

Once you get that, the "Milestones" table will be the one that has the data you seek!

**Comment by vpzed** [comment]
You can also check out some additional Manifest tips here:

https://github.com/vpzed/Destiny2-API-Info/wiki/Manifest-Introduction

The DestinyDevs stuff has a lot more code examples, but there are some additional items at that link.

**Comment by HittmanA** [comment]
Cool, thanks @vpzed

**Comment by HittmanA** [comment]
Hmmm if I go to `http://www.bungie.net/common/destiny2_content/sqlite/en/world_sql_content_4a0f279aaf9e1914bfcd210a1edea4a4.content` I get a 404 page.

**Comment by vpzed** [comment]
That is the link from the article which is just an example.  You need to actually use the Manifest API endpoint to get the current link as it describes in the article.

**Comment by HittmanA** [comment]
Oh ok

**Comment by HittmanA** [comment]
How often does the manifest update?

**Comment by vpzed** [comment]
When ever something in the game changes.  It could change more than once in one day, or change once in a whole week.  You never know.

**Comment by HittmanA** [comment]
What would be the best way of ensuring the latest data? Updating it every day?

**Comment by HittmanA** [comment]
Also, I get an error when I try to unzip the manifest file.

**Comment by vpzed** [comment]
I check every day for my application.  It depends on your use of the Manifest.  Some things don't change often.  Like if all you need is to lookup the classHash then those will likely never change.  But if you want to say display Nightfall information and right now many of the modifiers are Redacted, you might want to check regularly to see if they were un-Redacted so you could actually display a useful result.

I just tried it and it works fine - you just be doing something wrong when you are unzipping it.  Maybe look at the D2 project list on my Wiki to see if there is a project in your language you can use for guidance.

https://github.com/vpzed/Destiny2-API-Info/wiki/Destiny-2-Open-Source-Projects

This API is pretty complicated to use so you might also consider messing with some simpler API's first to get down the common code patterns before trying this one.  That's what I did and it helped a lot.

**Comment by HittmanA** [comment]
I will definitely look at those projects. One a side note, I am not sure what I could be doing wrong. I get the latest manifest endpoint, download the manifest, and try to unzip it. Here is my console's output:
```
Manifest URL: https://www.bungie.net/common/destiny2_content/sqlite/en/world_sql_content_45fb36a2be633296cce89b8f42c5f523.content
Downloading manifest.
Downloaded and saved Manifest
Unzipping Manifest file.
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: invalid block type
    at Zlib._handle.onerror (zlib.js:355:17)
```
The zip file is included (Warning it crashed the application that tried to unzip it)
[english.zip](https://github.com/Bungie-net/api/files/1416842/english.zip)
.

**Comment by vpzed** [comment]
This isn't really the forum to discuss debugging your code.  That is better suited for a more a Javascript developer forum, StackOverflow or similar.  Maybe check thetraveler package link on the project list for guidance.

**Comment by HittmanA** [comment]
Yeah, I decided to just use the traveler to download the manifest. Thanks for your help :)
