### ISSUE TITLE
HistoricalStats is returning "Machine Gun" Stats?

### ISSUE THREAD

**Issue by sgtfrankieboy** [Bungie-net/api#269]
I got a report from someone that he has kills done by a Machine Gun (statId: `weaponKillsMachinegun`), I was wondering which weapon those kills belonged to?

Here is a profile with them, at the bottom in the weapons section:
http://destinytracker.com/d2/profile/psn/ToxXicViper/detailed

**Comment by Tetron-bng** [comment]
Turns out that is a Fusion Line Rifle.  The correctly named stat will be returned by B.net in a future update.

**Comment by Tetron-bng** [comment]
Aka, "Trace Rifle" Currently the Exotic "Coldheart" is the only weapon in this category.

**Comment by Tetron-bng** [comment]
This should be fixed now.  Trace Rifle is a new weapon category.
