### ISSUE TITLE
Clan info guidance

### ISSUE THREAD

**Issue by vpzed** [Bungie-net/api#27]
I'm moving my question over from the Bungie group per your post:

My D1 "Clan Leaderboards" app is currently broken because I can't figure out how to retrieve a user's clan groupId after these changes. 

* The old method of /User/GetBungieAccount/ no longer returns the clans block. 
* The earlier recommended method of /Groups/MyClans/ returns Endpoint not found.

I looked at the new D2 spec and see endpoints that require the clan groupId but don't see what provides it. So now I'm stuck. I don't know how to get the clan groupId that is required for the Clan Leaderboards endpoint for either D1 or D2

Can you provide some direction on how to get the clan groupId for D1 and D2 after the Aug 28 changes?

**Comment by nine13tech** [comment]
+1. The ChWt Warmind is in the same situation.

**Comment by adherrling** [comment]
There are references to group-related data in the Content-Entities section of the API: GroupsV2.GroupResponse and GroupsV2.GroupV2ClanInfo. I'm assuming they just haven't updated the documentation to include the actual endpoints themselves.

**Comment by vthornheart-bng** [comment]
Indeed, we'll be adding the documentation for them soon.  For now, use:

/platform/GroupsV2/User/{membershipType}/{membershipId}/{filter}/{groupType}/

Where groupType =1(Clan)
And Filter = 0 (all)

The paging on the new service will return 100 entries at a time, which happens to be the max # of members in a Clan!

**Comment by vpzed** [comment]
@vthornheart-bng  I tried your suggestion with:

https://www.bungie.net/Platform/GroupsV2/User/1/4611686018431245918/0/1/ 

and got Endpoint not found.

**Comment by vpzed** [comment]
It is pluralized in the spec too.  For example:

`
"GroupsV2.GroupResponse": {
      "properties": {
        "detail": {
          "$ref": "#/definitions/GroupsV2.GroupV2"
        },
        "founder": {
          "$ref": "#/definitions/GroupsV2.GroupMember"
`

**Comment by vthornheart-bng** [comment]
Yeah, those are the namespaces for our response objects.  Unfortunately, I think it may be too late now to pluralize the endpoint itself without making some undesirable waves, our apps and site are already pointing at it.  If I had my druthers it'd be pluralized though.

When we release the documentation for it, the spec will properly refer to the endpoints by the non-pluralized form, so at least that will be somewhat less confusing at that point.

**Comment by nine13tech** [comment]
Could you not add a second endpoint pointing to the same internal endpoint that is pluralized for later deprecation in future releases? This could be on your WAF.
