### ISSUE TITLE
HistoricalStats feature for weekly stats

### ISSUE THREAD

**Issue by Tomalaya** [Bungie-net/api#270]
Feature request: 

Currently in the HistoricalStats call, you can request periodTypes for allTime and Daily.  As a convenience, it would be nice if there was a 'weekly' value too, so you could get stats since the last weekly reset, without having to calculate and call back through the daily method.

**Comment by vthornheart-bng** [comment]
I'll ask around about it!

**Comment by Tetron-bng** [comment]
No plans for this in the near future.  It is possible to get daily stats 7 days at a time.
