### ISSUE TITLE
Refuse requests to “bungie.net” when X-API-Key present?

### ISSUE THREAD

**Issue by floatingatoll** [Bungie-net/api#273]
Please consider refusing, rather than redirecting, requests to Bungie.net that have an X-API-Key header.

**Comment by vthornheart-bng** [comment]
Yeah, I dig that.

**Comment by Tetron-bng** [comment]
This redirect happens at a very low level. Not easy to insert additional logic here, so going to punt this one.

**Comment by floatingatoll** [comment]
See also #499.
