### ISSUE TITLE
 PerEndpointRequestThrottleExceeded(51) inaccurate rate limit counting

### ISSUE THREAD

**Issue by afehners** [Bungie-net/api#276]
Might be as designed, might be a bug, but I notice the rate limiting for endpoints is not being applied per the rule of 25 request per second, averaged over a 10 second window per source IP.

I had a small number of users of my app Light Speed raise an issue with certain items not appearing. On closer inspection I can see they are getting rate limited getting item instance details. I have client side rate limiting which follows the rate limiting rules, except I only allow 20 request per second to give myself some breathing space, I have confirmed through testing this correctly limits the number of calls allowed. 

I have noticed that the call I make the most is to fetch an items details. If I artificially raise the number of item requests I can easily become rate limited. If I rate limit to half the documented limit at 12 calls per second I never get rate limited, at 13 I always get rate limited at some point!

The call I make is something like this:
https://www.bungie.net/Platform/Destiny2/2/Profile/{profile}/Item/{itemId}/?components=ItemInstances,ItemCommonData

My outsiders guess is that because I have two components listed it means the backend is making two calls on my behalf and putting the results together, and therefore double counting my call?

**Comment by vthornheart-bng** [comment]
Greetings!  Hmm... I get the strong feeling that there may be a better way to do it in this situation.

With the changes in D2, you should be able to get any info that you're seeking from GetItem on GetProfile: so if you're making a bunch of calls to get the fine details of an item like you had to in Destiny 1, you no longer have to do that!  Calling GetProfile will get you everything across all the user's items at once, and you can pass any components to GetProfile that you can to GetItem: which means, for your purposes, taking down what's probably hundreds of GetItem calls into a single GetProfile call.

The only situation I could ever think of where GetItem would be useful these days is if you're on a screen that is specifically focusing on that single item, and you want to update its information for the user without getting the other items on the profile.  In D2, it's almost certainly not worth calling GetItem if you find that you need to call it for more than one item at a time for a single Profile.

Does that help in your situation?

**Comment by Tetron-bng** [comment]
Also, I looked at our analytics for your app, and it does seem like you are getting throttled closer to 16 RPS rather than 25 but our analytics are only down to a minute. So I can't be sure that  for me to be sure that you didn't have a 25 RPS spike during that 60 second window.  But taking Alex's advice will likely work great for you.

**Comment by afehners** [comment]
> so if you're making a bunch of calls to get the fine details of an item like you had to in Destiny 1, you no longer have to do that!

I totally missed that when porting to D2! I'll switch over to getting it all from GetProfile instead of GetProfile followed by lots of GetItem calls! 

Thanks @vthornheart-bng that will make things much faster and easier than combining the results of hundreds of GetItem calls to return to the UI.
