### ISSUE TITLE
Can't access my apps on bungie.net/en/Application

### ISSUE THREAD

**Issue by jgayfer** [Bungie-net/api#277]
I was fiddling with my bot's setting, and must have done something wrong. I see a message that says `Origin header does not match the provided API key` whenever I navigate to https://bungie.net/en/Application and sign in. Any ideas on how to fix this?

**Comment by floatingatoll** [comment]
"bungie.net" isn't generally a valid URL endpoint for Bungie API-related
stuff. Switch to "www.bungie.net" everywhere and see if your Origin header
problems go away. (They might or might not, but either way, always only use
"www.bungie.net".)

**Comment by jgayfer** [comment]
Opening an incognito window seemed to remedy this.
