### ISSUE TITLE
Clan members guidance

### ISSUE THREAD

**Issue by vpzed** [Bungie-net/api#28]
Also after the Aug 28th changes I am now getting Endpoint not found from the Group ClanMembers endpoint. 

So even with a known clan groupId I'm uncertain how to retrieve D1 clan membership information to be able to use that to pull other stats for the clan. 

Do you have any guidance on how to retrieve clan membership information for D1 and D2 after the Aug 28th changes?

**Comment by nine13tech** [comment]
+1. The ChWt Warmind is in the same situation.

**Comment by floatingatoll** [comment]
Does v1 api access break for clans that have not yet converted to Destiny 2 clans as well as ones that have?

**Comment by vthornheart-bng** [comment]
We'll be releasing the GroupV2 endpoint documentation soon, but for the time being use:

/platform/GroupsV2/User/{membershipType}/{membershipId}/{filter}/{groupType}/

**Comment by floatingatoll** [comment]
GroupV2, that is.

**Comment by vthornheart-bng** [comment]
Aye, pluralization issues!
