### ISSUE TITLE
A lot of errors using PGCR since maintenance.

### ISSUE THREAD

**Issue by v-fedorov** [Bungie-net/api#280]
At least i think there was a maintenance.

Random activities are failing, example

this one is broken
`https://www.bungie.net/Platform/Destiny2/Stats/PostGameCarnageReport/937516201/`

but the one prior and after are fine
`https://www.bungie.net/Platform/Destiny2/Stats/PostGameCarnageReport/937516200/`
`https://www.bungie.net/Platform/Destiny2/Stats/PostGameCarnageReport/937516202/`

**Comment by Tetron-bng** [comment]
Many Destiny systems are offline for maintenance. That endpoint should be returning System Disabled instead of DestinyUnexpectedError.
