### ISSUE TITLE
RFC: Improvements/Changes to Milestone data

### ISSUE THREAD

**Issue by vthornheart-bng** [Bungie-net/api#282]
This is specifically oriented toward returning better data for the Trials of the Nine milestone, but should also help any future events that have a similar setup.

Right now, we return the Playlist as the quest's activity if the milestone is pointing at a playlist, even if that Playlist can only serve up one possible entry.  For instance, in Trials of the Nine we point to a playlist of all possible combinations of Trials events, even though only one will be picked a week.

My proposed solution to this problem is:

1) In the event that a playlist only has a single active entry, we will return the active entry as both the conceptualActivityHash and the sole variant in the DestinyMilestone/DestinyPublicMilestone contracts.  This should let you start showing, for example, the current Trials of the Nine map.

2) I will add an activityModeHash and activityModeType property to both the Milestone quest's Activity, and to all variants.  Most of the time, it will be identical to the definition of whatever Activity it's pointing at: but in the case of chosen playlist entries such as will happen in (1), it will let you know the specific mode that is being played on that chosen playlist map.  This should let you start showing, for example, the current Trials of the Nine Activity Mode.

The (hopefully extremely minor) downside to this proposal is that Milestones with this behavior will no longer point to their Playlist in the returned data, and the activity that they *do* point to won't be defined in the DestinyMilestoneDefinition.  I think this is a small price to pay for the benefit, and I can't imagine anyone was getting useful information out of that Playlist activity that wouldn't be conveyed in the more specific activity.  But I'd be interested in hearing your thoughts.

**Comment by vthornheart-bng** [comment]
Hmm, no comments over the weekend - I'm going to move forward with this plan for an upcoming release.

**Comment by michabbb** [comment]
@vthornheart-bng i still have exact the same problem as mentioned in #287. this issue and #287 are closed but the map-location for trails is till missing in `/Platform/Destiny2/Milestones/` - did i miss anything ? where do i get the map from or is there another open issue ? *thanks*
