### ISSUE TITLE
Weasel error

### ISSUE THREAD

**Issue by GeorgiBerchev** [Bungie-net/api#284]
Hello!
So even after bungie said they fixed the WEASEL error i still get it. I cant play anything , cant do the strike missions nor raid or something that needs more than 20 mins. Im really sad i bought the game and I really like it and I wanna play it. Please help me resolve this issue!
Things I tried : Turning off my avast and firewall , turning off 3rd party programs , reinstalling the game
Thanks in advance!

**Comment by dad2cl3** [comment]
I would encourage you to visit https://www.bungie.net/en/help if you have not done so already.

**Comment by floatingatoll** [comment]
This github forum is for API and app developers and does not provide support for in-game error codes such as WEASEL, BUTTERFLY, or OCELOT.

**Comment by GeorgiBerchev** [comment]
When there is no answer to my question nor provided email to write. Do you guys have an email for BUNGIE SUPPORT. I mean every other game has atleast support tickets.

**Comment by vpzed** [comment]
That is what the Help site is for https://www.bungie.net/en/Forums/Topics/?tg=Help

**Comment by nine13tech** [comment]
Georgi,
    This site is for the Bungie API - Application Programming Interface. This is where programs like Destiny Item Manager, Destiny Tailor, and Destiny Tracker interface with the game to get their data.
The Bungie employees that run this GitHub have nothing to do with the operational support of Destiny. They do not open tickets to Operations. Take a minute and read through the tickets you see here. You will find that there are tickets about data pulls. you will NOT find tickets about Weasle and Beetle and Viper errors. 
   Destiny is NOT open source, so the game designers are not here on github, nor is the game's code. The path to help for GAME ISSUES is through the link that vpzd gave you. Unless you are a software developer that has created an application that pulls data from the game's API that has a problem... you are in the wrong place. Please close your ticket here and post on the help forum.
