### ISSUE TITLE
Please consider creating an issue template.

### ISSUE THREAD

**Issue by floatingatoll** [Bungie-net/api#285]
Per https://github.com/blog/2111-issue-and-pull-request-templates please consider an issue template for the “api” repository, so that you can inform users filing new issues of the intended scope of issues here m.

**Comment by Tetron-bng** [comment]
With the exception of the one person looking for game help, I feel like the questions are fairly well formulated.  Do you have a template in mind you think will improve matters?

**Comment by floatingatoll** [comment]
Nothing specific yet. It was a general consideration only; if the stars are low, I’d just skip it.

**Comment by vthornheart-bng** [comment]
I didn't know this was a thing - good to know about!  I think in particular I'd like to add an PULL_REQUEST_TEMPLATE to warn people not to do a bunch of manual work editing the swagger files, since they get generated anyways which means I'm not ever going to merge their manual changes.

**Comment by xlxCLUxlx** [comment]
If you could move the PULL_REQUEST_TEMPLATE to CONTRIBUTING.md that would be cool.  Good to know this though.  I will delete my pull request to remove clutter :).

**Comment by vthornheart-bng** [comment]
Ah, good to know about that as well!  Yeah, will do.  Sorry that you did all that manual changing work!  Hopefully this'll save other people that pain in the future.

**Comment by xlxCLUxlx** [comment]
No biggie!  It is a journey for us all!
