### ISSUE TITLE
Getting 'active' data about Trials of the Nine

### ISSUE THREAD

**Issue by tuzonghua** [Bungie-net/api#287]
In the D1 API, the Advisors endpoint gave status information regarding the status of trials (as well as the trials map). This included whether Trials was 'active' and if so, the 'startDate' and 'expirationDate'. In the Milestones endpoint (https://bungie.net/Platform/Destiny2/Milestones/), I see some milestones (like Xur and weekly milestones) have startDate and endDate. 

Any way these can be added for Trials of the Nine?

**Comment by tuzonghua** [comment]
As a note, it gives "location" data, but the location is simply "The Crucible" in the place/destination hashes.

**Comment by v-fedorov** [comment]
oof don't do that.
just use https://api.trialsofthenine.com/week/0/

**Comment by kbreit** [comment]
v-fedorov

This URL looks pretty interesting. Do you maintain it? If so, I'm noticing week 6's JSON data has an incorrect start and end date. It ends before it starts.

**Comment by tuzonghua** [comment]
@v-fedorov Thanks! Much better than Selenium scraping! ^_^ Still, my question stands to @vthornheart-bng.

**Comment by kbreit** [comment]
One last question to @v-fedorov. You said you update this manually. Do you normally do it at Trials release on Friday or is it normally a bit after (ex. hours)? Just trying to set expectations for my testing since I'm going to be using this until the official API has Trials information.

**Comment by v-fedorov** [comment]
@kbreit usually between 5-7 minutes after trials release

**Comment by vthornheart-bng** [comment]
Related to #282 

There will be improvements coming for giving the actual location, see #282 for further details!  You also should be able to get at that data currently through the Milestone data - either for the particular profile/character that you request, or via the GetPublicMilestones endpoint!

**Comment by tuzonghua** [comment]
@vthornheart-bng Unfortunately, the location data being returned is just "The Crucible". This comes from the activity hash returned being the same (3799743268) both from the GetPublicMilestones endpoint and the GetCharacter endpoint with CharacterActivities component. This particular activity is "Trials of the Nine" but doesn't specify a map.

**Comment by vthornheart-bng** [comment]
Yeah, take a read of #282 - that's what I'm talking about here, the future improvements (where I mentioned "There will be improvements coming for giving the actual location, see #282 for further details!").  Right now it returns the playlist activity, and when #282 goes live it will start to return the actual map, plus some additional data that will tell you the mode.

**Comment by tuzonghua** [comment]
Ah, understood. Read your comment as meaning I was missing something in the two endpoints mentioned to get relevant map data. Closing for now.

**Comment by vthornheart-bng** [comment]
Ah, yeah no worries!
