### ISSUE TITLE
Grenade kills returned as weaponKillsGrenadeLauncher instead of weaponKillsGrenade in PGCR

### ISSUE THREAD

**Issue by v-fedorov** [Bungie-net/api#288]
~So far out of all the trials matches played, these were are the totals of the ability medals~

~weaponKillsSuper: 2948013,~
~weaponKillsMelee: 2440296,~
~weaponKillsAbility: 45260,~
~weaponKillsGrenade: 0~

@vtubelsky was able to determine that grenade kills were being listed as weaponKillsGrenadeLauncher instead of weaponKillsGrenade

Im _**still**_ not really sure what weaponKillsAbility is

**Comment by Tetron-bng** [comment]
Are these from the PGCR endpoint?

**Comment by v-fedorov** [comment]
@Tetron-bng 
Yeah pgcr. Not sure about others

**Comment by vtubelsky** [comment]
@v-fedorov grenade kills seem to be returned as weaponKillsGrenadeLauncher

**Comment by v-fedorov** [comment]
@vtubelsky are you sure those are not kills by grenade launcher?

**Comment by vthornheart-bng** [comment]
Should be coming through now.
