### ISSUE TITLE
Cannot get faction rallies milestone content

### ISSUE THREAD

**Issue by hskrasek** [Bungie-net/api#289]
Trying to update my code to handle the faction rallies milestone for tomorrow (Tues. Nov. 7th), and digging into the sqlite file (version 60480.17.10.23.1314-2) I can see the two faction rallies under DestinyMilestoneDefinition.

However if I try to lookup the two milestone ID's using the Milestone Content API, I just the following response for both:

```javascript
{
  "ErrorCode": 1,
  "ThrottleSeconds": 0,
  "ErrorStatus": "Success",
  "Message": "Ok",
  "MessageData": {}
}
```

ID's I'm checking are `1718587363` and `3624239606`. One for Hear out Arach Jalaal, and the other for Pledge your loyalty to one of the City Factions.

Am I doing something wrong? Or is the API not returning this data until after the reset tomorrow?

**Comment by vthornheart-bng** [comment]
Ah, so the truth of that endpoint is that it only exists to expose content that we provide when we show a milestone as a "live event" in the frontpage of the website, or in the mobile apps.

In an ideal world, every Milestone would have this related data: but in practice we only have it for the ones that we expose in those areas of our site.

As a result, though there are many Faction Rally-related milestones, only two Faction Rally-related milestones actually have content:

3205009061 = "FactionRallies" (the milestone representing when you have already pledged and are earning rewards during the week)

364880304 = "FactionRallyWinAnnouncement" (the milestone representing your ability to go grab the winning faction's item)

**Comment by hskrasek** [comment]
@vthornheart-bng Ahh gotcha, yea I was missing those because I was running the following:

```sql
select case when id < 0 THEN id + 4294967296 ELSE id END AS id, json_extract(json, '$.displayProperties.name'), json_extract(json, '$.displayProperties.description') from DestinyMilestoneDefinition;
```

But since both of those Milestones don't have displayProperties, was overlooking them. 

May or may not be able to answer this question then, but which of those ID's would be the best to key off of to sorta match the Director's milestone list after reset to fit in with something like this?

![screenshot 2017-10-31 16 17 09](https://user-images.githubusercontent.com/787487/32468965-1ff824ba-c316-11e7-941b-c829b4cd12ab.png)

Would `showInExplorer` or `isInGameMilestone` be a good place to start?

**Comment by hskrasek** [comment]
Actually it seems as if every single milestone at the moment has a value of `isInGameMilestone: false`, so probably can't use that key for now.

**Comment by vthornheart-bng** [comment]
Whoops!  Good eye, I'll get that fixed up - we don't really use the property, and as such I'd not even noticed it wasn't populating!

When I get that populating, indeed my suggestion would be to use all the ones where isInGameMilestone is true if you want it to exactly match the in-game milestones.  Note that many milestones are "intro" milestones: ones that you only get, for example, the first time you ever do that type of activity.  You can filter those out by DestinyMilestoneType if you care to!

**Comment by hskrasek** [comment]
@vthornheart-bng Awesome, thanks a lot for the quick turn around and responses. Glad to see attentive Bungie is to the API! Managed to get everything setup in time for my little Slack bot, now to mess around with the API on other adventures.. which I'm sure I'll sooner or later open issues asking questions about.

**Comment by vthornheart-bng** [comment]
Should be good to go now, let me know if you run into any further issues!
