### ISSUE TITLE
profileInventory (vault items) occasionally returns with no data

### ISSUE THREAD

**Issue by designker** [Bungie-net/api#290]
Every now and then no vault items are returned for an account. Looking at the attached json 'profileCurrencies' is also missing data 
[myJson2.json.zip](https://github.com/Bungie-net/api/files/1451488/myJson2.json.zip)

**Comment by vthornheart-bng** [comment]
Ah, interesting - does it happen consistently with some people/accounts vs. others?  Or is it intermittent within an individual account/person?

**Comment by designker** [comment]
If it is like my account it is intermittent. Happens for like 20 mins then goes away. But when I say for 20mins I mean I have to refresh like crazy and maybe 1 in 10 refreshes have no vault. Maybe even 1 in 20. I have had very few reports, but it could be because it goes away. 

My account is 254/10213132 and it is happening right now

**Comment by kbreit** [comment]
I saw this problem over the weekend with both DIM and IC. The problem did go away, but as Nigel said, it probably took 20+ minutes. My estimate is it was less than 1 in 10 refreshes which worked, but I didn't keep track. I didn't report it as I took it as a temporary blip with Bungie but it appears to be more less than temporary.

**Comment by vthornheart-bng** [comment]
Yuck, not great.  My suspicion at the moment is something going awry with our caching if someone accesses a profile with/without the right permissions to see that kind of info (i.e. accessing it anonymously vs. logged in, or perhaps logged in but your auth token has expired).  But I will have to look into it.

**Comment by kbreit** [comment]
vt - I'm mrkdog on PSN if you want to use me as a second test case. I don't know my membershipID or characterIDs though.

**Comment by vthornheart-bng** [comment]
Hmm, I'll have to loop back to this, I don't see a smoking gun root cause at the moment.

**Comment by vthornheart-bng** [comment]
I believe I have found the smoking gun and resolved this issue.  If you continue to experience this problem, please let me know!
