### ISSUE TITLE
Different Origin Headers per API Key

### ISSUE THREAD

**Issue by krestaino** [Bungie-net/api#291]
It would be fantastic to allow different origins per key. I'd like to have a dev key and production key, one with localhost set as the header and one with my production origin. Currently, I would have to register 2 different apps to do this.

**Comment by ckhicks** [comment]
Ha, this is exactly what I'm doing right now. I have one that's wiiiiide 
open I use for testing and another that I used for a public-facing 
codebase.

**Comment by krestaino** [comment]
I guess it's really not a big deal to register 2 apps, but it would be nice!

**Comment by Tetron-bng** [comment]
My intention is you would have two versions of the app in flight.  One for testing and one for production.

**Comment by krestaino** [comment]
@Tetron-bng Ok, sounds good! Thanks.

**Comment by dfsoeten** [comment]
Alright, I know this is a million years too late but this is one of the first helpful links that show up in Google. 

Adding multiple origins seperated by a comma seems to work. Ie: `https://mylivewebsite.com,http://localhost:8080`.

**Comment by floatingatoll** [comment]
While comma-delimeted multiple origins are supported by the original CORS specification, in practice browsers generally do not support multiple origins — and if they did, they _ought_ to have required space-separated origins, per the definition:

`Access-Control-Allow-Origin = "Access-Control-Allow-Origin" ":" origin-list-or-null | "*"`

`origin-list         = serialized-origin *( SP serialized-origin )`
