### ISSUE TITLE
DefaultShader itemHash?

### ISSUE THREAD

**Issue by lowlines** [Bungie-net/api#292]
Just wondering if the inventoryItemDefinitions currently specify what is the default shader hash being applied to an item. An example is how all the raid weapons use Calus's Selected by default. If not, can this information be added, or is it something the designers did that would require a lot of manual work to add (thus not worth the effort)?

**Comment by vthornheart-bng** [comment]
Shoot, I did a little digging and unfortunately it looks like those colors are baked into the weapon's default model data itself: they're not associated with a shader item in any way that we can get at at least.  Sorry about that, there's not much we can do to give you that info that wouldn't involve a lot of fragile or manual configuration.

**Comment by lowlines** [comment]
I had an inkling that was the case. Oh well :)
