### ISSUE TITLE
Search User

### ISSUE THREAD

**Issue by Mom0aut** [Bungie-net/api#301]
Hey guys i just wanna Search my User Shiro
Battlenet Account
API KEY is in the header and there is no error code showing

i tried following requests:
"https://www.bungie.net/Platform//Destiny2/SearchDestinyPlayer/4/Shiro/"
"https://www.bungie.net/Platform//Destiny2/SearchDestinyPlayer/4/Shiro#2192/"
"https://www.bungie.net/Platform//Destiny2/SearchDestinyPlayer/4/Shiro-2192/"

but the response is always empty any suggestions or i am missing something?

TY

Mom0

**Comment by bladefist** [comment]
Encode the name.  # = %23

**Comment by Mom0aut** [comment]
ty it worked
