### ISSUE TITLE
Mode 17 Returns Empty for GetHistoricStats Endpoint

### ISSUE THREAD

**Issue by mistahj67** [Bungie-net/api#304]
Mode 17 is labeled as HeroicNightfall and returns nothing for all cases:
Example of endpoint used: 
https://www.bungie.net/Platform/Destiny2/2/Account/4611686018428814901/Character/0/Stats/?groups=0&modes=17&periodType=2
Example return:
{
    "Response": {
        "heroicNightfall": {}
    },
    "ErrorCode": 1,
    "ThrottleSeconds": 0,
    "ErrorStatus": "Success",
    "Message": "Ok",
    "MessageData": {}
}

**Comment by dad2cl3** [comment]
Have you tried the endpoint including a valid characterId?

**Comment by floatingatoll** [comment]
Are you authenticated as the Account ID below when this occurs, or anonymous?

**Comment by mistahj67** [comment]
Yes valid characterId returns the same.

**Comment by cortical-iv** [comment]
Just chiming in to vote that I would **love** to have this endpoint functional for my site. :) My current roll-your-own approach is pretty ugly when it comes to prestige nightfalls, and they are changing the rules for nightfalls soon in terms of completions, so it would be oh-so-convenient to just have the 'activitiesCleared' stat returned!

**Comment by vthornheart-bng** [comment]
Ah, yes - I still need to investigate this, I have not yet done so.  Thanks for bringing it back to my attention!

**Comment by cortical-iv** [comment]
Cool thanks!

**Comment by Tetron-bng** [comment]
BUG 612572

**Comment by Tetron-bng** [comment]
I think I found the cause.  The fix will be deployed soon!

**Comment by cortical-iv** [comment]
Thanks so much! (insert dancing party emoji here)

**Comment by Tetron-bng** [comment]
This fix is deployed now.
