### ISSUE TITLE
Upcoming Vendor API Enhancement - Map Location of Vendors (Xur)

### ISSUE THREAD

**Issue by mistahj67** [Bungie-net/api#310]
With the upcoming Vendor API addition, it would be great to be able to view the location of the vendor in the API call. My thoughts are geared towards Xur in particular but any vendor's location would be an added benefit for display purposes. 
My thoughts:
In D1, xur's location was randomized and never disclosed on the map making this request a bit too revealing then, but in D2, xur is displayed on the map for all to see. Adding it to the API would be a great enhancement for third-party and possibly the companion app as well.

**Comment by vthornheart-bng** [comment]
Ah, good call!  I've been working on vendors on-and-off for a little bit now, but I'd not done any work on returning Xur's location - I'll have to look into it!

**Comment by bhollis** [comment]
@vthornheart-bng I've noticed that vendors include a `vendorLocationIndex` and the definition includes `locations`... but Xur only has a single location ("The Last City").

**Comment by vthornheart-bng** [comment]
Yeah, that was a placeholder - he should have more location data in the next release!

**Comment by bhollis** [comment]
Now that Xur doesn't even show up on the in-game map does this make sense?

**Comment by vthornheart-bng** [comment]
Indeed, I neglected to follow up here after I found out that we can't actually return Xur's location for the forseeable future.  Sorry about that!
