### ISSUE TITLE
Daily quests disappeared from the API after hotfix, but returned today

### ISSUE THREAD

**Issue by floatingatoll** [Bungie-net/api#317]
Perhaps they came back due to daily reset?

**Comment by vthornheart-bng** [comment]
Ah, thanks for the report!  Your associate Nigel sent me some of the data from yesterday.  It does look like something went awry.  I will have to investigate further, thank you!

**Comment by vthornheart-bng** [comment]
I found the root of the problem - it will not be fixed in tomorrow's release, but will be fixed in the next release after that!
