### ISSUE TITLE
Many of my shared-inventory items have no particular types

### ISSUE THREAD

**Issue by floatingatoll** [Bungie-net/api#319]
It seems like, in the JSON at least, that a lot of my shared-inventory items (like treasure maps) have no particular itemType, which makes it impossible to distinguish between them using JSON alone. Could you consider adding distinct item types for the various things in this bucket?

**Comment by vthornheart-bng** [comment]
Definitely a good idea!  We're definitely in need of updating these.  I'm going to add this to the winter wishlist(tm)!

**Comment by designker** [comment]
This a millions times. I have so much horrible code to try and guess what certain items are.

**Comment by floatingatoll** [comment]
See also #329.

**Comment by designker** [comment]
Please consider also adding subtypes for the different types of armor. Helms, gauntlets, chest, etc are all subType 0

**Comment by vthornheart-bng** [comment]
Ah, I will look into that as well!

**Comment by vthornheart-bng** [comment]
My proposal for new types.  Let me know if you see any missing from this that you were wanting:

- (Consumable already exists, but adding sub-categories)
 - Consumable: Reputation Token
 - Consumable: Gag Gift
 - Consumable: Journal Fragment
 - Consumable: Infusion Material
 - Consumable: Prophecy Tablet
 - Consumable: Adventure Token
 - Consumable: Treasure Map
- (Mods already exists, adding sub-categories)
 - Armor Mod
  - Armor Mod: Gameplay
  - Armor Mod: Gauntlet
  - Armor Mod: Chest
  - Armor Mod: Class Item
   - Armor Mod: Titan Class Item
   - Armor Mod: Warlock Class Item
   - Armor Mod: Hunter Class Item
  - Armor Mod: Helmet
  - Armor Mod: Leg
 - Ghost Mod
  - Ghost Mod: Perk
  - Ghost Mod: Tracker
 - Ship Mod
  - Ship Mod: Transmat Effect
 - Weapon Mod
  - Weapon Mod: Intrinsic
  - Weapon Mod: Frame
  - Weapon Mod: Ornament
  - Weapon Mod: Barrel
  - Weapon Mod: Sword Blade
  - Weapon Mod: Battery
  - Weapon Mod: Sword Guard
  - Weapon Mod: Magazine
  - Weapon Mod: Stock
  - Weapon Mod: Launch Tube
  - Weapon Mod: Grip
  - Weapon Mod: Scope
  - Weapon Mod: Sight
 - Armor Mod
  - Armor Mod: Ornament
   - Armor Mod: Hunter Ornament
   - Armor Mod: Titan Ornament
   - Armor Mod: Warlock Ornament
 - Vehicle Mod
  - Vehicle Mod: Speed
  - Vehicle Mod: Functional
- (Weapon already exists, adding sub-categories)
 - Weapon: Submachine Gun
 - Weapon: Grenade Launcher
 - Weapon: Linear Fusion Rifle
 - Weapon: Trace Rifle
- Package
- Clan Perk
- Clan Staff

**Comment by vthornheart-bng** [comment]
Note that I am not going to add the sub-categories as SubItemTypes or ItemTypes... but I will add "higher level" categories that are missing.  This is my proposal for new values on the ItemType/ItemSubType enums:

Type:
    Dummy = 20,
    Ship = 21,
    Vehicle = 22,
    Emote = 23,
    Ghost = 24
SubType:
    Ornament = 21,
    FusionLineRifle = 22,
    GrenadeLauncher = 23,
    SubmachineGun = 24,
    HelmetArmor = 25,
    GauntletsArmor = 26,
    ChestArmor = 27,
    LegArmor = 28,
    ClassArmor = 29

**Comment by ArkahnX** [comment]
Just chiming in, will these types be reflected in the "itemCategoryHashes" array? My understanding is that the above two comments refer to the item type and subtype properties exclusively

**Comment by vthornheart-bng** [comment]
Ah, understandable concern - the first comment would be new Item Categories, and the second would be the changes to item type and subtype.  I dont' want item type and subtype to be as... fine grained... as item categories, partly because I don't really want those two properties to even exist anymore, but they're very convenient.  So I only want to add coarse-grained type information to those enums.

**Comment by vthornheart-bng** [comment]
Crapload of new item categories incoming.
