### ISSUE TITLE
There are 6 Jade Rabbit entries in the manifest

### ISSUE THREAD

**Issue by mowchan** [Bungie-net/api#322]
Hashes: `2896466320` `2978016230` `3229272315` `3844694310` `460724140` and `546372301`

Just an observation but I haven't seen this happen with other exotics yet.

**Comment by vthornheart-bng** [comment]
Oh, gross - yeah, those other ones are all "preview" versions of the item.  All the more reason for us to improve and increase the item types and categories being returned... that will help filter the other ones out.  The real one you'll want to look at is 3844694310.

**Comment by vthornheart-bng** [comment]
Actually, let me not close it until I've actually resolved it.

**Comment by vthornheart-bng** [comment]
Going to wrap this in with #319 for more general fixes of item types.  I will add "dummy" as a type.

**Comment by vthornheart-bng** [comment]
Ah, to note this did not make the boat for v2.1.1 releasing today.  It will come in the next release.

**Comment by vthornheart-bng** [comment]
Crapload of new item categories incoming.
