### ISSUE TITLE
GetActivityHistory count parameter limit

### ISSUE THREAD

**Issue by danreynol** [Bungie-net/api#323]
The maximum limit for the count parameter in GetActivityHistory is 250 (at least it seems to be in my testing). Is there a way to increase that, or is it set that way for performance reasons?

**Comment by vthornheart-bng** [comment]
Yes, unfortunately that is the current limit of our system.

**Comment by danreynol** [comment]
Thanks. FYI, your advice on mining PGCRs works well.
