### ISSUE TITLE
AggregateActivityStats returning ErrorCode 3

### ISSUE THREAD

**Issue by ChaseMalik** [Bungie-net/api#327]
For all AggregateActivityStats calls I have tried since reset, I've gotten ErrorCode 3 `UnhandledException`

Example calls:
`https://www.bungie.net/Platform/Destiny2/2/Account/4611686018428388138/Character/2305843009290285234/Stats/AggregateActivityStats/`
`https://www.bungie.net/Platform/Destiny2/2/Account/4611686018428397359/Character/2305843009260703958/Stats/AggregateActivityStats/`

**Comment by vthornheart-bng** [comment]
Good deal - I plan on investigating this in the morning! Thank you for the info!

**Comment by Tetron-bng** [comment]
I just deployed a fix for this.
