### ISSUE TITLE
itemCategoryHash for ornaments

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#329]
It appears that Ornaments don't have their own itemCategory. Looking up an Ornament, such as `907775118 (VEIST Silver)` , shows that it has itemCategoryHashes of `56 (Mods)`, `59 (Mods)`, `52 (Inventory)`, which is the same set of itemCategoryHashes that other Weapon/Armour mods have (like 145499294).

It would be really handy if Ornaments had their own itemCategoryHash so we could easily distinguish them. [Right now I'm looking at the itemTypeDisplayName](https://github.com/joshhunt/destinySets/blob/f0de61b/src/views/DataExplorer/filterItems.js#L199-L202) and judging based on that, which isn't very localisable

**Comment by vthornheart-bng** [comment]
Yes, I want this as part of the overall fixes we need to make to item types, that have fallen behind terribly.

**Comment by vthornheart-bng** [comment]
Crapload of new item categories incoming.
