### ISSUE TITLE
Would it be possible to get higher res icons in the API

### ISSUE THREAD

**Issue by NigelBreslaw** [Bungie-net/api#33]
Destiny in-game has larger icons for gear now the game is 4K. The API still provides icons at the Destiny 1 size. Now phone screens are so highres people have started to comment the icons look blurry. It would be great if it was possible to get higher res versions of the icons.

**Comment by vthornheart-bng** [comment]
I will look into it when I get time to do so!  I am not certain it is possible, but I will try to find out.

**Comment by lowlines** [comment]
There are also OTF fonts used for the UI that are sitting somewhere on a designer's desktop. Examples are the different weapon types, subclass abilities, platform specific button graphics etc. Adding these to the bunglefont would be awesome!

**Comment by vthornheart-bng** [comment]
Oh, yeah that'd be nice.  We couldn't release the font itself, as in the text portion: I don't believe we are legally allowed to, as it is licensed.  But I could investigate into whether those images embedded in the font would be something we'd be allowed to distribute.

**Comment by floatingatoll** [comment]
If naming it and who it's licensed from is permissible, as an app
developer, I would be happy to independently investigate the cost of a
license.

On Thu, Aug 31, 2017 at 4:55 PM, Vendal Thornheart <notifications@github.com

**Comment by vthornheart-bng** [comment]
I'll ask!

**Comment by hellocontrol-bng** [comment]
@lowlines A couple of things - the images that appear inline with text in-game are not necessarily font-based (and some of them include color, which is not possible with webfonts at the moment). 

Also, we will have to determine what the license for bunglefont is as well, as that is out in the open right now.
