### ISSUE TITLE
Destiny2.ReportOffensivePostGameCarnageReportPlayer OAuth scope

### ISSUE THREAD

**Issue by vpzed** [Bungie-net/api#332]
I was looking at the new endpoints and noticed Destiny2.ReportOffensivePostGameCarnageReportPlayer lists Required Scope(s):  oauth2: BnetWrite and I don't think that is a scope we get via the Applications page.  I know the documents contain other endpoints with scopes that are currently not allowed for Applications so I was wondering if this was also one of those.  It could be a "for Bungie use only" endpoint for Bungie.net or the Companion app for example.

Can you clarify is this endpoint was meant for us to be able to access or not?

**Comment by vthornheart-bng** [comment]
Ah, yes - I have to talk to some folks about it.  I neglected to think about that fact when I exposed it in the API - for now it is in a "bungie use only" state, but that is subject to change.  I need to chat with people on the subject, which I'll kick off right now.

Worst case, in the next release there will be a page you can direct people to in order to do their reporting right on BNet.  But I'll see if we can loosen these restrictions!

**Comment by vpzed** [comment]
Sounds good.  Some people asked me if in the future they'd be able to report someone from a "match history" view.  You get network jacked by some cheater(s) so your modem locks up and you are disconnected from the internet with no chance to report anyone.  When you finally get everything rebooted, re-connected, and so on - to be able to go back into your match history, find the game and report the players. Or something like that. 

Last time I looked Bungie.net and the Companion had removed play history so it would be up to a third party site/app to provide that history and to enable that type of functionality - and that is even assuming if that is within the realm of what Bungie intended for the endpoint.  There is still the option to use the form on Bungie.net for that kind of thing, or the in-game system for things that don't involve network jacking like inactivity, quitting, etc.

**Comment by vthornheart-bng** [comment]
Yeah, we're in the midst of re-enabling it as a feature on Bnet and the companion - our hope is that, even if we don't end up being allowed to expose the API for your guys' direct use, we'll at least have a page you can redirect them to where, if you pass their PGCR ID and the "offending" character ID in the URL, it will show them a screen on BNet with everything populated and ready for them to choose report reasons and hit submit.

**Comment by vpzed** [comment]
I can definitely see worries about enabling it for direct use.  Any kind of thing that could spam player reports has a downside.  In any event I thought I'd ask about it since some folks were asking me.  Maybe if people search Issues this will also help others with similar questions on that endpoint.

**Comment by vthornheart-bng** [comment]
Aye, that's the big debate here... one way or another, we'll have some solution for you, even if it's this less integrated "pop up a browser window to finish on BNet" experience!

**Comment by vthornheart-bng** [comment]
Aye, sounds like it's just going to be the redirect to page for now.  Sorry about the misleading API update!

**Comment by vthornheart-bng** [comment]
Closing for now since we can't actually open it up at this time.  But those watching at home, rest assured there will be a place for you to redirect people very soon(tm).
