### ISSUE TITLE
AdminGroups scope

### ISSUE THREAD

**Issue by rentalhost** [Bungie-net/api#340]
Hello. I am developing a clan manager, but in my application I cannot found the "AdminGroups" scope checkbox. How I can request this scope?

**Comment by floatingatoll** [comment]
What specific list of actions would you like to perform using that scope once it is enabled?

**Comment by rentalhost** [comment]
**Important:**
- `GroupV2.GetPendingMemberships`
- `GroupV2.ApprovePending`
- `GroupV2.KickMember`
- `GroupV2.IndividualGroupInvite`

With that I could check the pending subscription requests, approve, kick existing members and send individual invites to users that requests it directly on page.

Note: I do not found on API a way to deny a specific membership subscription requests. Is it done by `GroupV2.KickMember` too?

**Interesting:**
- GroupV2.EditGroupMembership: it will allow the admin management on group
- GroupV2.GetInvitedIndividuals: it will allow to check who was invited...
- GroupV2.IndividualGroupInviteCancel: ...then I could cancel it, if need
- GroupV2.GetBannedMembersOfGroup: it will allow to check if some member was banned previously...
- GroupV2.UnbanMember: ...then I could unban
- GroupV2.BanMember: it will allow to ban a member (but I still prefer just kick)

**Comment by nine13tech** [comment]
I believe the actions you would want to take is to banMember, then editGroupMembership to remove them.
Bans are temporary and do not change the clan join date.
Kicks are permanent and when/if the member comes back, their join date is reset. I do not know if your clan uses join date seniority or not, I know a few do. Just something to think about.

**Comment by rentalhost** [comment]
Oh, thanks for explain. In my case, the join date is not important.

**Comment by Tetron-bng** [comment]
I just added the scope for another developer.  Send me  your application ID (from the application/detail/xxxx) and I will grant you the scope.  If there is enough interest, we can make this scope generally available.

**Comment by rentalhost** [comment]
@Tetron-bng great to hear it! My app ID is 24027 (_"Nessus"_).

**Comment by Tetron-bng** [comment]
Done!

**Comment by Tetron-bng** [comment]
This scope will be exposed to the world by the end of this month.

**Comment by rentalhost** [comment]
@Tetron-bng oh, it doesn't works. I have sent my app ID from the URL (`https://www.bungie.net/en/Application/Detail/24027`), but maybe you need the `client_id` (that is _21022_)?
