### ISSUE TITLE
How Do I Search For Blizzard (PC) Player?

### ISSUE THREAD

**Issue by Xero-Vortex** [Bungie-net/api#344]
I'm looking to use the Destiny2.SearchDestinyPlayer endpoint to search for PC (Blizzard) players, but I haven't been able to get anything in the Response value of the returned json.

I presume that I am not using the diaplsyName parameter correctly. For example, my Battle.net (Blizzard/PC) name is Xero#1415 so I tried:
`https://bungie.net/Platform/Destiny2/SearchDestinyPlayer/4/Xero#1415/`

This gives the response:
`{
    "Response": [],
    "ErrorCode": 1,
    "ThrottleSeconds": 0,
    "ErrorStatus": "Success",
    "Message": "Ok",
    "MessageData": {}
}`

I have seen that my data is somehow accessible by searching for "Xero#1415" without any other authentication with this site:
https://www.wastedondestiny.com/search/xero%241415

I tried using the URL encoded version of my name like the above URL (`xero%241415`) with SearchDestinyPlayer and that gave the same results as above.

I also tried using the membershipType -1, but that didn't work either.

**How can I use SearchDestinyPlayer to find my PC/Blizzard/Battle.net player data?**

Thank you!

**Comment by floatingatoll** [comment]
Try Xero%24 instead - Blizzard search may be case-sensitive.

**Comment by Xero-Vortex** [comment]
I tried that and get the same results. Things I tried with the same results (all with membershipType of 4):
- Xero#1415
- xero%241415
- Xero%241415
- Xero1415
- Xero-1415

**Comment by vthornheart-bng** [comment]
Ah, I see the problem!  It's that # encodes to %23, so you'll want to do:

https://www.bungie.net/Platform/Destiny2/SearchDestinyPlayer/4/Xero%231415/

Try that out, that gives results!

**Comment by Xero-Vortex** [comment]
That was it! Jeeeez, I even URL encoded the string myself but didn't notice the 3, so I kept what I had copied and pasted from the website I linked. Not sure why they had a 4 in there though.

Thanks for being another set of eyes!

**Comment by vthornheart-bng** [comment]
No problem - I have done the same thing before!
