### ISSUE TITLE
Mayhem Mode in  API

### ISSUE THREAD

**Issue by bladefist** [Bungie-net/api#348]
With the new Mode that came out in the winter update, need to have a mode for it (like 39 for trials).

Thanks.

**Comment by vthornheart-bng** [comment]
Aye - we'll keep you all posted on it!

**Comment by bladefist** [comment]
Also that mode needs to be aggregated under mode `5` for AllPvP

**Comment by bladefist** [comment]
@vthornheart-bng thanks man, appreciate it.  Can you give me some insight if that is gonna be a hot-fix you can push soon or going to take a while to push? Trying to decide how to handle it on my end.  Thanks again.

**Comment by vthornheart-bng** [comment]
Talking to folks about it now - we have an Activity Mode, 1264443021, that should be taking it in - but something is going awry with that process.  I'll let you know if we'll be able to hotfix or if we'll have to wait until a subsequent release.

**Comment by vthornheart-bng** [comment]
It looks like we're not going to be able to provide a hotfix for it at this time, it will have to go out with our next release in the new year.  Sorry about that - definitely feel free to filter them out and/or add messaging that this is broken on Bungie's side.

**Comment by bladefist** [comment]
@vthornheart-bng Did this make it out today?  Still seeing the issue.

**Comment by vthornheart-bng** [comment]
Nay, unfortunately the deployment today didn't have any code changes, just very minor content updates.

**Comment by vthornheart-bng** [comment]
Mayhem should now be behaving correctly.

**Comment by vtubelsky** [comment]
Does Mayhem have its own constant in DestinyActivityModeType? I see that CrimsonDoubles has been added, but not Mayhem.

**Comment by rentalhost** [comment]
Seems that was not documented, but should be 25 https://github.com/Bungie-net/api/issues/367#issuecomment-356027934

**Comment by vthornheart-bng** [comment]
Yes, let me reopen this - indeed it is 25.  I'm going to file a bug to get this fixed.

**Comment by vthornheart-bng** [comment]
Filed as TFS 608157.

**Comment by vtubelsky** [comment]
GetActivityHistory with mode=25 does return Mayhem games, but they still seem to be excluded from AllPvP (mode=5).

**Comment by vthornheart-bng** [comment]
Ah, interesting - could you spin that off as a new Issue?  I think I'm layering too many different problems into this same issue, it'll make it harder for us to track (I should have split the activity mode type into its own issue in retrospect, but #mistakesweremade)
