### ISSUE TITLE
Milestone 'Titan Challenges' ends up with 9 challanges, some from a nightfall??

### ISSUE THREAD

**Issue by designker** [Bungie-net/api#349]
[getProfile.json.zip](https://github.com/Bungie-net/api/files/1573074/getProfile.json.zip)
I attached the json, but the milestone with a hash of "383198939" has 9 challenges instead of 3 and some come from a nightfall

**Comment by vthornheart-bng** [comment]
Ah, barf - thanks for reporting this, I think I see why this is happening.  We're inferring related challenges in a way such that those Nightfalls are being improperly wrapped into it.  I will see what we can do for the next time we deploy in the new year.

**Comment by vthornheart-bng** [comment]
Challenges in general should be greatly improved now, including these!
