### ISSUE TITLE
Would it be possible for the ItemDefinition to have details of which foundry (viest, hakke, etc) a weapon belongs to?

### ISSUE THREAD

**Issue by NigelHietala** [Bungie-net/api#355]

**Comment by floatingatoll** [comment]
I remember seeing a super cool Hakkë banner on the left side of the in-game weapon inspection screen when looking at one such gun. If that banner image is available as an asset to the API team, that might help the API publish foundry data as well.

**Comment by vthornheart-bng** [comment]
Hmm, I will have to investigate that.  At least in D1, there was nothing other than geometry, textures, and flavor that indicated whether a gun was from a given foundry.  There may be something more reasonable for us to work with in D2 in order to return such data, but I have not had a chance to look into it.

**Comment by bhollis** [comment]
https://data.destinysets.com/i/InventoryItem:2700862859

The `secondaryIcon` often has the banner image for each foundry.

**Comment by floatingatoll** [comment]
Whoah! Thorn, is that universal, or only for post-Forsaken, or...?

**Comment by floatingatoll** [comment]
(However, one note here — does that include somewhere the string "HAKKE" or
"Omolon" or whatever?)

**Comment by vthornheart-bng** [comment]
The truth is that I didn't realize that was even in there!  At some point, someone must have added it into the game data and it just started coming down to us automatically as a result.  I will have to do some investigation to determine if there's any other data!

**Comment by ckhicks** [comment]
Anyone feel like building an image-diff-to-enum tool for D2 icons? 😂
