### ISSUE TITLE
Some referenced responses are missing required description field

### ISSUE THREAD

**Issue by vpzed** [Bungie-net/api#36]
In the v3 spec, some Path object Response objects are missing the required [Response object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#responseObject) "description" property:

For example with /User/GetBungieNetUserById/

        "responses": {
          "200": {
            "$ref": "#/components/responses/User.GeneralUser"
          }
        }

and 

    "responses": {
      "User.GeneralUser": {
        "content": {
          "application/json": {
            "schema": {
              "properties": {
                "Response": {
                  "$ref": "#/components/schemas/User.GeneralUser"
                },
                "ErrorCode": {
                  "$ref": "#/components/schemas/Exceptions.PlatformErrorCodes"
                },
                "ThrottleSeconds": {
                  "type": "integer",
                  "format": "int32"

**Comment by adherrling** [comment]
Adding in the extra description property and running swagger on the v3 spec seems to work. This does not solve all the issues with the v3 spec, though.

**Comment by vthornheart-bng** [comment]
Hmm, interesting - what validator are you guys using?  I couldn't find a validator that actually supported v3 yet, so I have only run a validator against v2.  Hit me up with a link!

**Comment by adherrling** [comment]
I don't actually have a validator - I'm just looking at the output of the openapi and openapi-2 both run through swagger-codegen.

**Comment by vthornheart-bng** [comment]
Hmm, I'm surprised swagger-codegen worked at all for our v3 openapi spec - I tried it before, and it didn't appear to load v3 files at all.  But that was a week ago and I know they're actively working on it, I'll have to give it another shot when I get time.  In the meantime, v2 should be validating correctly: give that a shot for your codegen needs!

**Comment by adherrling** [comment]
The change on line 2 is all that's necessary to get it initially working. It doesn't output completely correct data, but it does output enough to actually build the endpoints (not the components yet).

**Comment by vthornheart-bng** [comment]
hmm, interesting and good to know!  Thanks - I'll see if I can spin up the latest version of swagger-codegen and see if I can get it running with the v3 spec when time allows.

**Comment by vpzed** [comment]
@vthornheart-bng 

I found the problems I reported using [this site](https://openapi-converter.herokuapp.com/) which has a validation option (on the Validate tab).

That site is based on [this project](https://github.com/mermade/swagger2openapi) which I found in the [Open-API Implementations](https://github.com/OAI/OpenAPI-Specification/blob/master/IMPLEMENTATIONS.md) document.

I'm currently trying to figure out how to use this code but modify it to not stop on the first error it finds.

**Comment by vthornheart-bng** [comment]
Interesting!  Good find.  Yeah, if you end up modifying it to return all the errors: (1) publish that on Github so everyone can benefit, as apparently the internet is sorely lacking a working v3 validator at the moment, and (2) let me know and I'll run our spec through and fix up whatever I can when I get the time!
