### ISSUE TITLE
AdminGroups scopes availability?

### ISSUE THREAD

**Issue by Shockishock** [Bungie-net/api#360]
Hey,

I was trying to get a list of the pending request my clan has in an android app.
So I used that endpoint :
https://www.bungie.net/Platform/GroupV2/1841924/Members/Pending/?currentpage=1

and the response is :
{"ErrorCode":2108,"ThrottleSeconds":0,"ErrorStatus":"AccessNotPermittedByApplicationScope","Message":"Access not permitted by application scope","MessageData":{"RequiredScope":"AdminGroups"}}

I then suppose this is something we aren't allowed to do in third party app as this scope isn't available in the application settings ?

I'm I right ?

Regards

Kris

**Comment by Tetron-bng** [comment]
Hey Kris,

Currently that scope is not generally available.  We reduced the number of scopes primarily to prevent exposing a bunch of APIs nobody was interested in using, and then being unable to make changes to them.

What is your application ID?  I can grant you access to that scope.  Let's talk about your scenario, maybe it is time to expose that scope in general.

Paul

**Comment by Shockishock** [comment]
Hey Paul!

Thanks for that very fast answer !

Well I created an android App called Arcadia one of its aim is to ease the clan management when founders do have multiple clans to administrate.
The idea there is to get every pending request for each clan of the alliance in a simple view and not being forced to logout / login in each different profile.

The App Id is : 20948 (for the android app)
And : 13990 (for the web version)

Kris

**Comment by Tetron-bng** [comment]
Can you confirm those numbers are the ones that appear in the URL like this:
xhttps://www.bungie.net/en/Application/Detail/**_24900_**

**Comment by Shockishock** [comment]
Oups nope sorry that was client_ids :
The url are : 
https://www.bungie.net/fr/Application/Detail/16543
https://www.bungie.net/fr/Application/Detail/23979

So 23979 and 16543

**Comment by Tetron-bng** [comment]
Excellent.  Check the page now, you should have the needed scope.  Do not uncheck that scope as you make changes to settings in the portal or else you will need me to add them back for you (until we make these generally available).

**Comment by Shockishock** [comment]
just saw you added the scopes ! Many thanks !

**Comment by nine13tech** [comment]
Anyway I can get in on that? I have not built that functionality yet - but it's on my roadmap.

**Comment by Tetron-bng** [comment]
Send me your app id!

**Comment by Tetron-bng** [comment]
BTW, we have decided to expose this to the general public by the end of this month.

**Comment by nine13tech** [comment]
CHWT WARMIND (3778)
CHWT WARMIND (22750)

**Comment by Hennamann** [comment]
I realize that we are close to the end of the month now, but I could really use the access for a future project of mine, and I'd like to start work as soon as possible.
Here's my project id: 24373
