### ISSUE TITLE
API Throttling rate?

### ISSUE THREAD

**Issue by ArielSaldana** [Bungie-net/api#362]
Is there a specific number of requests you can make per second?

**Comment by vpzed** [comment]
This has been answered in previous issues here:

https://github.com/Bungie-net/api/issues/26#issuecomment-334900673

and 

https://github.com/Bungie-net/api/issues/244

If you use the Search feature in Issues you can find other threads on this topic but these are the main ones I remember.

**Comment by ArielSaldana** [comment]
@vpzed Thanks! Pretty much answered my question.
