### ISSUE TITLE
Getting Xur's Inventory

### ISSUE THREAD

**Issue by hskrasek** [Bungie-net/api#363]
Alright I've done some digging but I've drawn a blank, so maybe someone here can help out. Is it currently possible to get Xur's inventory from the API?

**Comment by Shockishock** [comment]
As far as I know this isn't available yet.

**Comment by vthornheart-bng** [comment]
Keep an eye out on the GetVendor/GetVendors endpoints, I've been working on them on the side as time allows, and they are currently returning at least the correct items for a given vendor (though all the other info on them is wrong).  They're available to use in early preview, and still subject to change - but I'm getting closer to finalizing them.

https://bungie-net.github.io/multi/operation_get_Destiny2-GetVendor.html#operation_get_Destiny2-GetVendor

Keep an eye out here, I'll hopefully have more info soon.

**Comment by vthornheart-bng** [comment]
What URL are you hitting specifically?

**Comment by hskrasek** [comment]
Here's an example with my MembershipID and one of my Characters, with Xur's Vendor hash

https://www.bungie.net/Platform/Destiny2/TigerXbox/Profile/4611686018429963408/Character/2305843009260880385/Vendors/2190858386?components=None

This one also gives the same response though

https://www.bungie.net/Platform/Destiny2/TigerXbox/Profile/4611686018429963408/Character/2305843009260880385/Vendors/?components=None

**Comment by vthornheart-bng** [comment]
Hmm, I'll have to investigate later.  I believe people have been able to pull data from this endpoint already even in its preliminary state, but if we're having problems out there it's good to know.

**Comment by hskrasek** [comment]
@vthornheart-bng I figured the DTG_BOT on the subreddit was using some form of this, but I've always gotten the following response to both endpoints, which I just figured was related to the "Preview not ready for release" tags that the docs show. 

```json
{
  "ErrorCode": 12,
  "ThrottleSeconds": 0,
  "ErrorStatus": "InsufficientPrivileges",
  "Message": "You lack the privileges to read or write this data.",
  "MessageData": {}
}
```

Me and my ability to break things strikes again

**Comment by hskrasek** [comment]
@vthornheart-bng You may be able to close this after all. I didn't realize that the endpoints needed an OAuth access token to get the vendor list or specific vendors inventory. 

Just tried again after creating an access token and boom, suddenly data.

**Comment by vthornheart-bng** [comment]
Ahh, sweet - that'd explain it!

What I would like to do is have a "public" API for Vendors that have data that's commonly true across all users (like Xur) and that wouldn't require OAuth access as a result, like we did in D1.  I think that's covered in another existing Github issue though, I'll have to dig around for it when I get a minute.

**Comment by hskrasek** [comment]
@vthornheart-bng That'd be super awesome, then we wouldn't have to do a fun server side OAuth dance + hard coded values setup. Or y'all wouldn't have to support the client credentials grant for OAuth so we could do server-to-server auth.

**Comment by vthornheart-bng** [comment]
Aye, totally.  It is definitely a feature that's on my mind!

**Comment by bhollis** [comment]
Just an update, we're (DIM) able to successfully get Xur info from these endpoints.

**Comment by vthornheart-bng** [comment]
Thanks for the update!  The info you get back should be more robust and accurate this upcoming release!

**Comment by TangoJoker** [comment]
@bhollis @vthornheart-bng Hey there, I'm a bit confused on last update. Do we still need to run through OAuth process to get Xur's info?

**Comment by bhollis** [comment]
I'm not sure - we only get it through `GetProfile`.

**Comment by adampatterson** [comment]
> Ahh, sweet - that'd explain it!
> 
> What I would like to do is have a "public" API for Vendors that have data that's commonly true across all users (like Xur) and that wouldn't require OAuth access as a result, like we did in D1. I think that's covered in another existing Github issue though, I'll have to dig around for it when I get a minute.

To be clear, providing the API token in the header will not work for this call?

I just tried to get an oAuth token using Postman and the connection between Bungie and Sony seems to not work.

![image](https://user-images.githubusercontent.com/31537/80925738-83b79200-8d4f-11ea-8dfc-02c4276004d5.png)

I am new to the Destiny API and am finding it a lot more confusing to navigate than I had thought.
