### ISSUE TITLE
Sending message to destiny player through the API?

### ISSUE THREAD

**Issue by Shockishock** [Bungie-net/api#365]
Hi!

Titel says it all, is this possible to end a message to a destiny player with the API?
I guess no as I haven't seen any related endpoint.

Regards

Kris

**Comment by vthornheart-bng** [comment]
Just for clarification purposes - do you mean directly to them on the platform, like as a Destiny player on PS4 I could receive a PS4 message from someone using the BNet API?

We don't provide that option unfortunately - I don't think it's something we'll likely add anytime soon, as it would require us to allow arbitrary messaging via our API through the platforms (Sony, Microsoft etc...) which could open the door for spamming on their platforms.  I'm not entirely sure if there's mechanisms in our platform partner's APIs to actually do it either - I've not checked, but even if there is I don't picture us supporting it through our API.

We do have APIs that support messaging entirely on Bungie.Net, but that is from Bungie.Net user to Bungie.net user: they'd only see it if they go to the site or use the companion, and if they're a registered Bungie.net user.

**Comment by Shockishock** [comment]
Hey thanks for the reply!
No sorry, maybe I wrongly express myself.

I meant from bnet user to bnet user, I couldn't find the endpoint in the guide, that's why I supposed it wasn't release to third party App and only available in the companion?

**Comment by vthornheart-bng** [comment]
Ahh, okay - indeed, we have an endpoint for it, but I went to check and it's not publicly available at this time.

**Comment by Shockishock** [comment]
Okay! well thanks for checking !
Hopefully one day ! :)

Thanks for all your support guys !

**Comment by vthornheart-bng** [comment]
No problem, and thank you!  Yes, stay posted here!

**Comment by RecursiveHook** [comment]
Just wondering what the status was of the above for Battle.net messaging? 

Additionally, what is the current endpoint for sending messages on Bungie.net, as per:
>We do have APIs that support messaging entirely on Bungie.Net, but that is from Bungie.Net user to Bungie.net user: they'd only see it if they go to the site or use the companion, and if they're a registered Bungie.net user.
