### ISSUE TITLE
Not all nullable properties are marked nullable

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#366]
This is a general problem I'm running into as I'm writing a bespoke TypeScript generator from the API docs. It looks like fairly often, when there's an array or dictionary property defined in the schemas, they are not marked "nullable" but the server will omit empty arrays/dictionaries. I bring this up only in hopes that it's a property of the serializer on the server and that we can just update the openapi JSON to mark all array properties as nullable or something.

**Comment by 48klocs** [comment]
With the 11/27 release, a number of folks are tripping over `PresentationNode`, hash `756584948` - it's redacted and there seem to be a number of null properties on it (`DestinyPresentationNodeChildrenBlock` is one of the problem children).
