### ISSUE TITLE
SearchDestinyPlayer autocomplete?

### ISSUE THREAD

**Issue by vtubelsky** [Bungie-net/api#368]
Is there a way to get results from SearchDestinyPlayer even if I don't know the numerical part of a player's battle.net tag (i.e. #12345)?

I thought it was not possible, but some websites like destinystatus.com and trials.report can do that (although I suspect they might be implementing their own autocomplete by caching previous search results).

**Comment by vthornheart-bng** [comment]
Indeed, my suspicion is that they are finding the information through other methods.  There's unfortunately no way to do SearchDestinyPlayer with a Battle.Net tag when you don't have the number.

You may find a coincidental match - for instance, say you searched for that tag but with the Bungie.Net user membership type, and the user just happened to use the same name for both their Bungie.Net account and their Blizzard account - but that would be a coincidence not worth relying on unfortunately.

**Comment by vtubelsky** [comment]
Got it, thank you for confirming that.
