### ISSUE TITLE
Mobile Manifests

### ISSUE THREAD

**Issue by rexcell99** [Bungie-net/api#37]
I am looking into the design of my IOS app with PHP back end and the possibility of holding the basic data on the device by trimming down the manifest to only the info I require for my app and using a cache for a lot of the images,
limiting the need to request data

The question I have is how often is the manifest updated, is it just a reset day thing and what are the main areas that change. If it is possible to answer that ?

This questions apply's to D1 & D2 , but I assume they both run on a similar principle

Thanks In Advance

**Comment by vthornheart-bng** [comment]
Ideally, the D1 manifest should change extremely rarely from this point on, if ever.  It'll be a once in a blue moon scenario.

The D2 manifest will update whenever the game itself does.  Expect more frequent updates (weekly or bi-weekly) right after major releases such as the game's launch itself, and less frequent updates in-between (bi-weekly to monthly).  But definitely write your system with the expectation that, at any time, the manifest could be updated: you should have something that regularly checks whether there's a new manifest, or at least that does so when your app first starts up!

**Comment by rexcell99** [comment]
When you say manifest changes I assume  you mean the data inside the end points will change.

For a simple example :

A new weapon may be added 
A description of a weapon and its roles may change 

Things like that 

But the basic structure will remain the same

**Comment by rexcell99** [comment]
Ok thanks for the info
That gives me enough info I think to set the direction I want to go

Thanks once again

**Comment by vthornheart-bng** [comment]
No prob, anytime!
