### ISSUE TITLE
Data offline?

### ISSUE THREAD

**Issue by bladefist** [Bungie-net/api#373]
For about 4-5 hours now, there has been no stats updating or activity history flowing.

Hope this helps in case bungie is unaware.

**Comment by mconnervt** [comment]
Also seeing this. I completed a prestige raid about an hours ago and it wasn't showing up on raid report, so I checked destiny tracker and it was also missing, so it seems like an API issuem

**Comment by vthornheart-bng** [comment]
Hmm, good to know.  Hang tight - the game is in the midst of maintenance at the moment.  Let's see if it comes back online when maintenance ends.

**Comment by mconnervt** [comment]
Fwiw the raid stats were showing up on the raid report website as of this morning (9ish eastern time).
