### ISSUE TITLE
D1 ActivityHistory Timeouts

### ISSUE THREAD

**Issue by BlazeBoss17** [Bungie-net/api#378]
Currently, the D1 ActivityHistory endpoint is returning DestinyShardRelayProxyTimeout errors, such as in the following request: 
https://www.bungie.net/d1/Platform/Destiny/Stats/ActivityHistory/2/4611686018428397359/2305843009225608891/?page=0&mode=raid&count=250

This has been happening for a while now.

**Comment by vthornheart-bng** [comment]
Hmm, the performance specifically for D1 should have been improved somewhat since then: though you may still periodically experience timeouts.  Has the situation improved for you?

**Comment by BlazeBoss17** [comment]
It has not improved at all. Still times out every request.

**Comment by vthornheart-bng** [comment]
Hmm, good to know - I will bring this up to some folks tomorrow!

**Comment by vthornheart-bng** [comment]
Can you send me a link to your Bungie.Net profile page?  That'll let me see what applications you have created, which will help me run some diagnostics for the requests you've been making.

**Comment by vthornheart-bng** [comment]
We're doing some investigation, but for the time being try limiting your returned entry count to 100 instead of 250.  That should circumvent the issue for the time being.

**Comment by BlazeBoss17** [comment]
Thanks for looking into this issue. I tested getting only 100 raids at a time but that also times out, although less frequently.

I've mainly been testing on the production raid.report site. 

https://d1.raid.report/ps/Dattowatto

**Comment by vthornheart-bng** [comment]
Hmm, while they're still looking into it, try scaling it down further if you're getting intermittent timeouts.  Try hitting for 50.  Folks are looking into the issue, but I have not been given an ETA for when it might be fixed.

**Comment by vthornheart-bng** [comment]
Okay, try it now - I've been told that the issues being encountered have been mitigated, and your call should succeed consistently once more.
