### ISSUE TITLE
Clarification around instanced reusablePlugHashes data

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#379]
The [documentation for `reusablePlugHashes`](https://bungie-net.github.io/index.html#/components/schemas/Destiny.Entities.Items.DestinyItemSocketState) suggests pretty strongly that item hashes in it are able to be used

> If the item supports reusable plugs, this is the list of plug item hashes that are currently allowed to be used for this socket. (sometimes restrictions may cause reusable plugs defined on the item definition to not be valid, so you should trust the instanced reusablePlugHashes list rather than the definition's list) A Reusable Plug is a plug that you can *always* insert into this socket, regardless of whether or not you have the plug in your inventory

However what I've discovered in reality is that items that show up in here may still not able to be activated, due to incomplete objectives.

For example, here's my socket/plug data for Xenos Vale IV Warlock Arms (2378296024, item instance ID 6917529039296467955 FWIW):

```
[
  ...,
  {
    "plugHash": 702981643,
    "isEnabled": true,
    "reusablePlugHashes": [
      702981643, // Default Ornament
      137367657 // Xenos Shore Ornament
    ]
  },
  ...
]
```

Which, from reading the documentation, suggests to me that I have unlocked Xenos Shore Ornament. However when I go in game, I am not yet able to use Xenos Shore Ornament as I have not completed the required objectives.

![https://i.imgur.com/YEy9hp1.jpg](https://i.imgur.com/YEy9hp1.jpg)

Is this a bug, or should the documentation be updated to clarify that items in reusablePlugHashes might still be gated behind objectives?

Preferably, the documentation should be true (and that the current behaviour is a bug) - if a plug is not able to be inserted into a socket, it should not be listed in `reusablePlugHashes`. I believe this makes more sense and is more usable given the upcoming InsertSocketPlug API...

#winter-wishlist 🤞🏼

**Comment by joshhunt** [comment]
Related: https://github.com/Bungie-net/api/issues/339

**Comment by vthornheart-bng** [comment]
Indeed, there is more to it these days: originally there was no modifiers on whether these could be applied, but that changed recently.  With the upcoming deployment, you should start getting the information that you need through a new property, reusablePlugs.  reusablePlugHashes will be deprecated in favor of using reusablePlugs, which will have objective etc... information.
