### ISSUE TITLE
WebView sign authentication support

### ISSUE THREAD

**Issue by thisbarker** [Bungie-net/api#38]
I am aware of the topic: [Question: OAuth Client Type for native apps](https://github.com/Bungie-net/api/issues/24), but I thought it was needed to create an issue for this specific alternate authentication mode.

Can it be assumed you have completely dropped this support, including for Destiny 1? If it is still possible to use WebView authentication, am I missing something that has changed?

I ask because end points to retrieve game data are limited to public information only. Even though I was able to successfully authenticate and am passing all of the proper cookies along.

Request headers:
```
GET https://www.bungie.net/d1/Platform/Destiny/1/MyAccount/Vault/ HTTP/1.1
X-CSRF: ***
X-API-Key: ***
Host: www.bungie.net
Cookie: bungleatk=***; bungled=***; bungledid=***; bunglefrogblastventcore=***; bungleloc=lc=en&lcin=true; bungleme=***; bunglemsa=***; bungles=WebView=True&UserFlowMode=SignIn&UserICT=None&UserSCT=None&UserForce=False&UserIDN=; sto-id-sg_live.bungie.net=***; __cfduid=***
```

Response:
```
{"ErrorCode":99,"ThrottleSeconds":0,"ErrorStatus":"WebAuthRequired","Message":"Please sign-in to continue.","MessageData":{}}
```

**Comment by vthornheart-bng** [comment]
We don't officially support the cookie-passing approach to authentication, but functionally that hasn't changed since Destiny 1.  Try re-authenticating on the website and making sure you grab the new cookies that come from that: perhaps you are trying to use old and expired cookies.

**Comment by thisbarker** [comment]
I am not entirely sure that is true. I have had an application published for a couple years now, but after the updates on August 23rd users can no longer authenticate. This is primarily due to the fact that the /mobi/../SignIn/... path now redirects from https to http then back to a different https url without /mobi/. iOS by default blocks this unless you specifically make an exception in the Info.plist file. Working around that issue then gives the response I put above. For iOS for example the application gets cookies from NSHTTPCookieStorage.

**Comment by vthornheart-bng** [comment]
Hmm, can you put the specific URL that you hit here?  It sounds like the real problem is this redirection you're experiencing, perhaps we can help with that!

**Comment by hellocontrol-bng** [comment]
Additionally, you should now be able to avoid the /mobi/ path altogether by simply using the normal links used in the site (because the desktop ones have been made mobile-friendly).

But like @vthornheart-bng said, we really do want to encourage the OAuth flow instead :)

**Comment by thisbarker** [comment]
```
HTTP POST: https://www.bungie.net/Mobi/en/User/SignIn/Xuid
First Redirect: http://www.bungie.net/en/User/SignIn/Xuid?flowStart=1
Final Redirect: https://www.bungie.net/en/User/SignIn/Xuid?flowStart=1
```
As informational I have even gone so far as to intercept a request before it is sent from the new Destiny 2 Companion application and change the URL to `https://www.bungie.net/d1/Platform/Destiny/1/MyAccount/Vault/` and I receive the same error. It may be an issue with /d1/ endpoints and Cookie validation.

**Comment by vthornheart-bng** [comment]
Hmm, interesting - I'm going to be OOO during most of PAX, but if I get the chance to loop back into the office I'll give it a shot.

**Comment by vthornheart-bng** [comment]
After thinking about this on the weekend, we really don't want to support this auth flow.  If you could move over to using OAuth, that would be the ideal situation!  We made it a policy to not support the overriding/hijacking auth flow in D1, and particularly now that we have proper OAuth support I can't provide support for that flow now.  Sorry about that - if you need any help moving your app over to using OAuth, we would be happy to point you to some resources and answer any questions you may have!

**Comment by thisbarker** [comment]
@vthornheart-bng I am interested to see how the official companion application works with the comments related to public vs confidential oauth2 in #24 . I will work on using OAuth2 confidential, like the other apps do, until a decision comes in.

**Comment by vthornheart-bng** [comment]
Good deal - aye.  We'll keep you all posted here once decisions are made on that subject, but I think that's a prudent step.
