### ISSUE TITLE
Iron Banner control PGCR not returning zones captured

### ISSUE THREAD

**Issue by benedfit** [Bungie-net/api#386]
When compared to regular control, Iron Banner control PGCRs do not return all the same stats: 

IB: https://www.bungie.net/platform/Destiny2/Stats/PostGameCarnageReport/1456629688/
Regular: https://www.bungie.net/platform/Destiny2/Stats/PostGameCarnageReport/1400060440/

**Comment by vthornheart-bng** [comment]
Hmm, I'll have to look into that, thanks for letting me know!

**Comment by benedfit** [comment]
Somewhere along the line this was solved
