### ISSUE TITLE
Are there plans to update the OpenApi JSON files?

### ISSUE THREAD

**Issue by syndia** [Bungie-net/api#387]
Are there any plans to update the OpenAPI files?

**Comment by vthornheart-bng** [comment]
Ah, yes indeed - we'll update with the next real BNet deployment.  Over the holidays and through January, we've only been doing game content updates so there hasn't been anything in terms of new documentation, endpoints etc.

However, the work we've done over the holidays/in January will be released soon (our target is midweek next week), and at that time we'll update the OpenAPI specs and the generated documentation as well!

**Comment by syndia** [comment]
Ok that would be great. Thanks.
