### ISSUE TITLE
How do you get the player's clan ?

### ISSUE THREAD

**Issue by JulesRx** [Bungie-net/api#389]
Is there a method to do this ? I'm trying `/Destiny2/{membershipType}/Profile/{membershipId}/?components=100` but there isn't anything usefull in the response...

**Comment by nine13tech** [comment]
You need Group V2 User memberships and filter for clans with the 1 at the end.

https://www.bungie.net/Platform/GroupV2/User/{membershipType}/{membershipId}/0/1/

**Comment by JulesRx** [comment]
That's it thank you 👍
