### ISSUE TITLE
Application Not Found for App Owner?

### ISSUE THREAD

**Issue by ckhicks** [Bungie-net/api#39]
I'm working through suuuuper basic authentication via Auth0.com and standard OAuth flow. When I'm signed in with my own account, I can't auth with my public app. However, when I'm signed out I can hit it just fine. Is this because I'm already "authenticated" with the app as the owner?

**Comment by vthornheart-bng** [comment]
What endpoint in particular were you trying to hit that you could hit anonymously but not while authenticated?  Just to get clarification on my side.

**Comment by ckhicks** [comment]
Actually it was just the OAuth endpoint for initial Authorization - I get that I was already authed and logged in to Bungie.net, but I’m not sure why it reported that the application couldn’t be found. Perhaps I’m missing something simple, haha.

**Comment by vthornheart-bng** [comment]
Hmm - could I get an example of your request and response that's failing?  (include all of the headers)  You can email it to amola@bungie.com - that'll be helpful for diagnosing the issue!

**Comment by ckhicks** [comment]
I wonder if it had something to do with my redirect URL. 🤕  I just tried again after setting that and catching the responses more sanely, which seems to have resolved the issue. I'm going to assume it was user error and mark this closed unless I hit it again - thanks much!
