### ISSUE TITLE
For PvE.activitiesEntered, what counts as an activity?

### ISSUE THREAD

**Issue by cortical-iv** [Bungie-net/api#391]
In GetHistoricalStats for PvE, I'm extracting _activiviesEntered_, and I am not sure what counts as an **activity**. I am having trouble adding up individual activities to yield that number. The sum of strikes, adventures, and story activities doesn't yield the number, for instance.

This is not particularly important, I'm just trying to make sure I understand the statistic before I start using it for leaderboards. Until then I will just report individual activities I understand

**Comment by vthornheart-bng** [comment]
Good question!  There's definitely situations where it's not at all apparent.

Activities consist of *anything* you do in the game other than being in orbit.  This includes when you go into the Tower, when you play a PVP match, when you play a story mission, when you're "free roaming" on a planet, even when you're watching a cinematic outside of a mission that launches one (for instance, the "Credits" of the game are a cinematic Activity)!

Stats don't return free roam activity data, but it will return (if you ask for it) data from any of those other types of activities.

Take a look inside of the Activities definitions in the manifest database if you've set that up already.  Those are instances of DestinyActivityDefinition if you want to follow along with it in the documentation - and each of those that you see in there represent something that the game considers to be an activity.  For each of those other than free roam, you can get stats back. (IIRC at least the last time I checked, you even get stats for cinematics.  Don't ask me why)

**Comment by cortical-iv** [comment]
Cool thanks that is helpful I didn't appeciate how broad a category it was. Basically if it has an activity hash type, and it is not PvP, then it is part of that stat?

**Comment by vthornheart-bng** [comment]
Oh, I apologize - I just realized I was going on a tangent about what constitutes an activity in *Destiny* vs. what counts as an activity specifically when looking at the PvE stat.  Sorry about that!

In this case, what will count specifically as PvE is indeed anything that is not flagged as isPvp in the Activity definitions if I recall correctly.  I will attempt to dig up more specific information in case my memory is incorrect, but I wanted to reply quickly to make sure I don't lead you too far off base with my tangent!

**Comment by vthornheart-bng** [comment]
Yes, any activity that's not specifically PVP is being treated as if it is a PVE activity: so indeed, the counts may not be what you expect as a result, because of it counting things like Cinematics, Free Roam, etc...
