### ISSUE TITLE
Armour Ornaments missing itemCategoryHashes

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#393]
On brief inspection, it appears that _legendary_ armour ornaments are missing their itemCategoryHashes.

For example, here are some ornaments I've noticed missing  itemCategoryHashes:

 - Leviathan Raid Armour ornaments:
   - Hunter: 3346055334, 2519280691, 3179514973, 2899660517, 1928662068
   - Titan: 3036703920, 3093970453, 2380365371, 1815512839, 3991114670
 - Warlock Dead Orbit Armour Ornament: 1575996367, 467764322, 3377623014, 3352318036, 2798463723

While the list is no means comprehensive, it was what i was able to quickly see.

**Comment by vthornheart-bng** [comment]
Good find!  Yep, the heuristics on these broke.  Fun times - thanks for reporting it!  I'll fix it up, let me know if you run into any more!

**Comment by vthornheart-bng** [comment]
Tracking in TFS bug 607931

(I'm trying to get better at associating these issues with actual TFS bugs, so you guys can refer to them and we'll have reminders of our internal work items... I'll try to find some time to do this for the rest of the backlog.  We'll get better at this incrementally ;) )

**Comment by joshhunt** [comment]
👍 

Fantastic turnaround time! 🎉 

On a similar note, ghosts used to have the ARMOR category (20), but now they just have GHOST (39). Is it intentional that they've been changed?

**Comment by vthornheart-bng** [comment]
Ah, yes - it felt odd that we were categorizing them as armor.  Was that useful for you all to have it as armor?

**Comment by joshhunt** [comment]
I agree, it's not exactly obvious that they're lumped in with Armour. I just mentioned it as it _was_ a change that I was unsure whether it was intentional or not.

It's not particularly useful itself, it's just as easy to change my stuff to use the ghost category itself.

**Comment by vthornheart-bng** [comment]
Ah, aye, totally a good point!  I should have mentioned it in the API version changelist overview - hopefully it'll be better in the long run as its own category.

**Comment by vthornheart-bng** [comment]
To clarify with these mod issues, I've made some fixes to at least get these marked as mods: but there are known places where they're not getting their *specific* category correct.  This is going to be an ongoing fight, and we'll be working soon on some ways to try and detect these failures in a more automated way, but I have my doubts as to how reliable that will/can be for some of these situations until we can get more reliable type data from the game itself.  So if you see more situations where the mod ended up not being of the type you expected, let us know!
