### ISSUE TITLE
Transfer between char x vault returning error for some item types

### ISSUE THREAD

**Issue by duckmanBR** [Bungie-net/api#394]
Shaders/Mods/Consumables are returning "The Vendor you requested was not found" when trying to transfer from char to vault and "The item requested was not found." when going back.

Examples:

Solar Paragon Mod Rare - From char to vault
{"characterId":"2305843009266992358","membershipType":2,"itemId":"0","itemReferenceHash":522105398,"stackSize":1,"transferToVault":true}
{"Response":0,"ErrorCode":1627,"ThrottleSeconds":0,"ErrorStatus":"DestinyVendorNotFound","Message":"The Vendor you requested was not found.","MessageData":{}}

Gunsmith Materials - From char to vault
{"characterId":"2305843009266992358","membershipType":2,"itemId":"0","itemReferenceHash":1305274547,"stackSize":18,"transferToVault":true}
{"Response":0,"ErrorCode":1627,"ThrottleSeconds":0,"ErrorStatus":"DestinyVendorNotFound","Message":"The Vendor you requested was not found.","MessageData":{}}

Callus Treasured Shader - From vault to char 
{"characterId":"2305843009266992358","membershipType":2,"itemId":"0","itemReferenceHash":1422712819,"stackSize":7,"transferToVault":false}
{"Response":0,"ErrorCode":1623,"ThrottleSeconds":0,"ErrorStatus":"DestinyItemNotFound","Message":"The item requested was not found.","MessageData":{}}

**Comment by vthornheart-bng** [comment]
Ah, thank you!  Hang tight, I'll look into it momentarily.

**Comment by vthornheart-bng** [comment]
Confirmed, tracking TFS 607948

**Comment by vthornheart-bng** [comment]
Tracking for hotfix tomorrow morning, pending test approval.
