### ISSUE TITLE
The daily strike milestone claims to have 48 challenges! instead of 3

### ISSUE THREAD

**Issue by designker** [Bungie-net/api#395]
Json attached 
[StrikeMilestone.json.zip](https://github.com/Bungie-net/api/files/1706465/StrikeMilestone.json.zip)

**Comment by vthornheart-bng** [comment]
Phew, holy cow!  Good eye, I'll have to take a look.

**Comment by vthornheart-bng** [comment]
Tracked as 608174.

Let me check a few things.  It's possible that this is actually the legitimate set of all possible challenges on strikes, but there may either be an error or I am misinterpreting what should constitute qualifying challenges for the purpose of the milestone.

**Comment by designker** [comment]
Right, but shouldn't the milestone data on the character only have the 3 of them that are relevant that day? That JSON was not the definition, but the progress/milestone data for a character

**Comment by vthornheart-bng** [comment]
Ah, I see the problem - so to complete this milestone, you can technically complete any 3 challenges on any strikes or nightfalls... but I'm actually returning every possible nightfall as if they're all active, even though only one nightfall is active at a time.

When I fix this, there will be more than 3 possible challenges to complete that will still be returned, but I'll cease returning it for nightfalls that aren't actually active.  With this fix, you'll get challenges only on the active nightfall, the strikes playlist, and any possible strikes that can be played in the playlist.  Which may be more than 3, but will be less than 48!

**Comment by designker** [comment]
Oh! The normal strike ones are class specific. So if you know the character is a hunter you can filter out the titan and warlock ones? Nightfall is different, that has generic challenges irrespective of class. Err I think?

**Comment by vthornheart-bng** [comment]
Ah, good to know!  So this is a bit embarrassing, but I didn't realize that!  I'll see what I can do to account for that.  So this is character specific milestone data you're looking at and not the public ones right?

**Comment by designker** [comment]
Sorry I just realised there are 2 issues here? 1 is too many items, the other is this is the daily strike challenge. It should not have any of the nightfall challenges in it at all. But it does have nightfall ones in the 48

**Comment by designker** [comment]
Yes I can see from this tweet a user sent me https://twitter.com/Shaken_K1W1/status/961533783412375552
Zero strike challenges are showing. They are all nightfall challenges

**Comment by vthornheart-bng** [comment]
Hmm - I'll need to hit up some designers.  It looks in the content like this milestone should complete regardless of if you do Nightfall or regular Strike challenges... but I'll have to get back to you on it, I could be misinterpreting the data.

Only nightfall challenges showing is unexpected - I do see in the result set you returned that there's challenges coming down from the normal strike playlist, but they're *way* at the end of the list after all of this bad Nightfall data!

Hang tight, I will do some more digging!

**Comment by vthornheart-bng** [comment]
Ah, yes - looking at your screenshot, towards the bottom is "Hat Trick" - that's an example of one of them that is actually coming from the normal strikes playlist.

I'm double checking with the designer now just in case there's more to it, but looking at the content it appears that it's going to count both Nightfall and non-Nightfall Strike challenges.  So when I fix this up, I'll return just the challenges for:

* The actually active Nightfall
* any non-Nightfall strikes that you can play

**Comment by vthornheart-bng** [comment]
Cool, fixed it up for next release!
