### ISSUE TITLE
Battle.net ID is gone from userInfo in GetProfile response

### ISSUE THREAD

**Issue by vtubelsky** [Bungie-net/api#396]
GetProfile endpoint (aka /platform/Destiny2/{ platformId }/Profile/{ membershipId }/?components=Profile) used to have the full battle.net username as profile.userInfo.displayName.

Now displayName is just the name without the numerical part of the battle.net ID.

Was this change intentional?

It makes sense for displayName to be just that, but now there's no way to find the user's battle.net tag. Would be nice to have another field, like fullName, next to displayName.

**Comment by floatingatoll** [comment]
This might be related to Tetron’s comment about these:

https://github.com/Bungie-net/api/issues/281#issuecomment-341800309

**Comment by vthornheart-bng** [comment]
Aye - we were asked to make it so that the numerical portion of the ID is not revealed any more, neither in the site nor in the API.  Sorry guys.

**Comment by vthornheart-bng** [comment]
Just in case people aren't doing it, I highly suggest any info you store about users is using the combination of membership Type and membership ID rather than gamertag.  The former is immutable: the latter is potentially highly mutable, and thus not really ideal even before this change.

**Comment by vtubelsky** [comment]
Thank you for the clarification.

I used full user names to link to individual player profiles from PGCRs. I'm going to use membershipIds instead though it doesn't feel right to expose them in a URL.

**Comment by vthornheart-bng** [comment]
No worries - yeah, it's a bit uglier to use the membershipId + membershipType in the URL, but it is the canonical representation (and remember, you'll want to save both!).  Our URLs also use these ugly numbers: it's not great, but it'll give you immutable accessibility!  (you could add the display name as you know it to the URL as something to "prettify" it a bit if it helps, as long as you're not using it as the primary key for accessing the user's data)
