### ISSUE TITLE
Weapon Mods with empty itemCategoryHashes

### ISSUE THREAD

**Issue by duckmanBR** [Bungie-net/api#399]
Similar to #393 (I believe), all weapon mods are returning an empty itemCategoryHashes.

Example: Legendary Kinetic (4207478320)
![image](https://user-images.githubusercontent.com/32077894/36007714-b6260ae8-0d2a-11e8-92f1-a1302caad16a.png)

Couldn't find a faulty armor one, so I believe it's only the weapons ones.
Example: Empty Armor Mod
![image](https://user-images.githubusercontent.com/32077894/36007753-db762d1e-0d2a-11e8-893d-15b1f26cbdc0.png)

PS: Used destinysets just to get readable data

**Comment by JonnyOThan** [comment]
Some (but not all!) titan class item mods have this problem as well.  
1949257483, 3640622194 - void impact mod
145766606, 2291847593 - solar ordnance mod
Interestingly, the ones that have this issue have an itemTypeDisplayName of "Class Item Mod" while the ones that are set correctly have an itemTypeDisplayName of "Titan Mark Mod"

**Comment by floatingatoll** [comment]
I believe those "Class Item Mod" variant items *also* have incorrect
class-specific items in-game when using L2 to preview the type icons in
Inventory, so there may be some bug upstream of the API to inspect here as
well.

**Comment by vthornheart-bng** [comment]
Ah, good info, thank you!  I'll check all this out.

**Comment by vthornheart-bng** [comment]
Tracking under TFS 608921
