### ISSUE TITLE
GroupsV2.GroupFeatures.membershipTypes missing "type" property

### ISSUE THREAD

**Issue by lowlines** [Bungie-net/api#4]
All other instances of schemas with the "items" property explicitly specifies a type of "array". Not sure if this is a required thing or not but its the only one I've come across.

**Comment by lowlines** [comment]
Actually it looks like quite a number of components where a type isn't specified. There are also some objects with "properties" or "additionalProperties" that aren't explicitly declared as of type "object".

**Comment by vthornheart-bng** [comment]
Thanks!  I'll give that a peek as I'm revising the generator!

**Comment by vthornheart-bng** [comment]
Thanks for reporting this!  I found the problem - a codepath where the type wasn't being explicitly set for some List and Dictionary types.  Should be fixed up next time we deploy documentation/specs!
