### ISSUE TITLE
Trying to (un)lock items on vault returns not found

### ISSUE THREAD

**Issue by duckmanBR** [Bungie-net/api#400]
Item (Sweet Business) on one of the chars:
{"characterId":"2305843009266992358","membershipType":2,"itemId":"6917529051282052556","state":true}
{"Response":0,"ErrorCode":1,"ThrottleSeconds":0,"ErrorStatus":"Success","Message":"Ok","MessageData":{}}

Same Item, now on Vault.
{"characterId":"2305843009266992358","membershipType":2,"itemId":"6917529051282052556","state":false}
{"Response":0,"ErrorCode":1623,"ThrottleSeconds":0,"ErrorStatus":"DestinyItemNotFound","Message":"The item requested was not found.","MessageData":{}}

**Comment by vthornheart-bng** [comment]
Ah, good to know!  Thank you, we'll look into this.

**Comment by vthornheart-bng** [comment]
Tracking TFS 608920

**Comment by vthornheart-bng** [comment]
Ah, yes - this has been fixed and should be getting deployed as we speak!
