### ISSUE TITLE
Help Needed: Forum Thread API End-points with Boolean path parameters

### ISSUE THREAD

**Issue by GrayWulf25** [Bungie-net/api#403]
Hi. For a project I need to extract many Forum threads from B.net. I can get posts and their parents already. But when trying to get whole threads I am hitting issues with Boolean path parameters and there are no suitable examples for these Forum end-points:

/GetPostsThreadedPaged/{parentPostId}/{page}/{pageSize}/{replySize}/{getParentPost}/{rootThreadMode}/{sortMode}/

/GetPostsThreadedPagedFromChild/{childPostId}/{page}/{pageSize}/{replySize}/{rootThreadMode}/{sortMode}/

{getParentPost} and {rootThreadMode} are Boolean. When I try  I get "One or more parameters are outside the range of valid values' every time. I have tried: true, false, 'true', 0,1,-1, null, default all give the same error. 

Do these end-points actually work, and if so can you give me an example URL with values in all path parameters?

**Comment by vthornheart-bng** [comment]
Try:

https://www.bungie.net//Platform/Forum/GetPostsThreadedPaged/243004315/0/10/10/true/true/Default/

**Comment by GrayWulf25** [comment]
Thank you so much, that works. So the issue was sortMode which per the API guide should be 0 or 1?

**Comment by vthornheart-bng** [comment]
Using 0 or 1 works as well - that specific param is an enum, and it will take either the numeric or string identifier version of the values!  I'm not certain what was going wrong in your previous request attempts - I'd have to see a specific example of the full URL you were passing to know for sure.
