### ISSUE TITLE
The plugCategoryIdentifier for mods that can go on any character class claim to be a specific class

### ISSUE THREAD

**Issue by designker** [Bungie-net/api#404]
For example mod itemHash 2407848812 claims to be enhancements.class_hunter but can mod any characters class item

**Comment by vthornheart-bng** [comment]
Hmm, I'm looking at that plug (2407848812, "Solar Impact Mod" of type "Hunter Cloak Mod"), and it looks like it ought to be restricted to the hunter class at least - it's got a plug category of 1425760675, which should be restricting it to only sockets of type 1737884121 (that is, hunter class armor enhancement slots).

Are you actually able to socket it into non-hunter armor in the game?

**Comment by designker** [comment]
You are right there is no issue here. I just got thrown as in game all class items are class specific. However some say 'Class item mod' and others say 'Titan Mark mod'. Even though both of them only work on say a Titan.

**Comment by vthornheart-bng** [comment]
Ah, yes - yeah, unfortunately that's a game content issue for sure. :(
