### ISSUE TITLE
DismantlePermissionGroup not defined

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#405]
The `dismantlePermission` property on `Destiny.Entities.Items.DestinyItemComponent` refers to `#/components/schemas/Destiny.DismantlePermissionGroup`, but that schema doesn't exist (in `openapi.json`).

**Comment by bhollis** [comment]
I suspect this is meant to be `AwaType`?

**Comment by vthornheart-bng** [comment]
Ah, it looks like what we've run into is that the DismantlePermissionGroup enumeration is marked up in such a way that it's not being output by the swagger generator (and thus also by the documentation).

In the next release I'll make sure this gets changed so it'll output the enum definition.

**Comment by vthornheart-bng** [comment]
Ah!  Turns out this was not meant to be in there at all.  I'll be removing it later today.

**Comment by vthornheart-bng** [comment]
Logged as TFS 610196

**Comment by vthornheart-bng** [comment]
The change has been deployed to the docs/swagger specs.  Pay no attention to the man behind the curtain
