### ISSUE TITLE
Crimson Doubles activities not marked with PvP mode

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#409]
Sample PGCR 1483655205.

Crimson Doubles PvP activities should be marked with mode 5 (PvP), but they're just 15 (Doubles) at the moment.

**Comment by vthornheart-bng** [comment]
Good eye, thank you!  We somehow totally missed that in our setup.  Yuck.

**Comment by vthornheart-bng** [comment]
Fixed up in a hotfix today, should be good to go now.
