### ISSUE TITLE
v2 spec responses > schema missing required type property

### ISSUE THREAD

**Issue by vpzed** [Bungie-net/api#41]
The v2 spec requires a type property in the responses > schema object.

So as is this is causing a validation issue:

        <SNIP>
        "responses": {
          "200": {
            "description": "The response for this request.  We don't have documentation for it yet...
            "schema": {
              "properties": {
                "Response": {
                  "$ref": "#/definitions/User.GeneralUser"
                }, 
              <SNIP>

I believe what it's asking for is something like this:

        <SNIP>
        "responses": {
          "200": {
            "description": "The response for this request.  We don't have documentation for it yet...
            "schema": {
              "type": "object",
              "properties": {
                "Response": {
                  "$ref": "#/definitions/User.GeneralUser"
                }, 
              <SNIP>

**Comment by vthornheart-bng** [comment]
Hmm, probably another case of "works in X validator but not Y".  Were you running into that with the online tool linked in the other bug?  Either way, seems reasonable to add in.

**Comment by vpzed** [comment]
@vthornheart-bng 

This was worked out from the [official schema definition for OpenAPI v2.0](https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/schemas/v2.0/schema.json) .  I was trying to work out why I was seeing a lot of "type errors" and I thought it was weird because all the data types looked OK.  Turns out at least some of them were actually trying to tell me about a type property.  Took me a good while to figure out.  Anyway...

If you look at the responses definition and de-reference it to the response definition you can see what is in the attached screenshot.  It is in yaml for easier greater readability.  I've highlighted the important bit with a red box.

The schema object can either be a $ref object OR the an object of the definition shown, and in that definition it shows type as a required property.

![definition-response](https://user-images.githubusercontent.com/30138020/29975108-d5fa29de-8efa-11e7-8488-539ae48031de.png)

**Comment by vpzed** [comment]
Oh, and while I'm thinking about it, a lot of the OpenAPI v2 spec validation engines are based on the specific schema file I linked above.  They are using that as "the law".

One of the reasons that OpenAPI v3 spec validation is up in the air is that a schema file like that doesn't exist yet for v3 - as you can see by [looking here](https://github.com/OAI/OpenAPI-Specification/tree/master/schemas)

**Comment by vthornheart-bng** [comment]
Hmm, interesting!  That's the good stuff, I'll give that a run through when I get the chance.  Thanks for the link!

(yeah, I found out the hard way that 3.0 isn't quite ready for prime time yet.  My swagger spec generator I wrote was against 3.0 spec, but when I finished and went to generate docs I found that nothing was ready yet.  Which is why I made a jury rigged 3.0 to 2.0 shim... that obviously still has some ongoing issues ;) )

**Comment by vpzed** [comment]
Until an official OpenAPI v3 json schema is provided some folks are using this [totally unofficial version created by the Google Gnostic team by parsing the markdown version of the specification document](https://github.com/googleapis/gnostic/tree/master/OpenAPIv3) I figured this out because some of the preliminary v3 tools I've been researching point here.
