### ISSUE TITLE
Forum API: Answered Question flag not working or inconsistent?

### ISSUE THREAD

**Issue by GrayWulf25** [Bungie-net/api#410]
Hi, I'm analyzing Answered Questions starting with Help Forum. I'm unable to detect a consistent marker for the response marked as the answer. Looking at the Forum.Flags.Enum and the "flags" column in results, I have user responses that are marked as the answer with flags=0, and another one answered by a moderator with flags=4. I cannot see any other columns that identify the single marked answer

Can someone advise whether there is a working method for identifying the marked answer to an answered question via columns accessible through the API?

**Comment by vthornheart-bng** [comment]
Okay, so it's a little funky/poorly documented, but here's how you get that data:

When you look at the topic post, it will be of type PostResponse.  (note that all of these *only* get set on the topic, and not on the answer post itself!) That object's category property (a Flags enumeration) will have bit 6/value 32 set (question answered.  Note that bit 7/value 16 is that the topic post was a "question", so it will at least have bits 6 and 7 set at this point).  If answered by Bungie, it will have the flags property set to bit 6/value 32.  If answered by a Ninja, it will have the flags property set to bit 7/value 64.  In addition, the "metadata" property will have the postId of the post marked as the answer!

**Comment by vthornheart-bng** [comment]
Just to note, I heard from someone separately that the flags enumerations are a consistent point of confusion in our API (and understandably so!)  I wrote this tutorial to try and help people in case anyone has run into trouble with them.  I hope it helps!

https://github.com/Bungie-net/api/wiki/FAQ:-Flags-Enumerations,-how-do-they-work%3F

**Comment by GrayWulf25** [comment]
Thanks for your help, very useful
