### ISSUE TITLE
Some items are classified

### ISSUE THREAD

**Issue by baxter** [Bungie-net/api#413]
Hey, one of our readers contacted us to ask why certain lore tabs were missing from the site. After investigation it looks like these lore tabs are visible in game:

* Daring Hunter's Cloak (`1056171153`) https://i.imgur.com/NkFnvws.jpg
* Brave Titan's Mark (`1040474575`) https://i.imgur.com/HGXYpr3.jpg
* Wise Warlock's Bond (`1331814296 `) https://i.imgur.com/nVaaS26.jpg

But within the `DestinyLoreDefinition` table the records for these items are marked as Classified/redacted.

Could you please de-classify these lore definitions, and any other that might be incorrectly classified? 🙂 

Thanks.

**Comment by unisys12** [comment]
Just wanted to share some of my research notes on this subject.

There are currently 15 redacted LoreDefinitions. Of the 15, some are not tied to any items at all and some are tied to multiple items. This could explain the redaction, but could also help out with figuring out what's actually going on as well. 

LoreHash | Associated Item Hash | Associated Item Name 
----------- | ------------------------- | --------------------------
2209865285.0 | | | 
2421406347.0 | | | 
2448010882.0 | | | 
3081865122.0 | | | 
3285934677.0 | | | 
3471587229.0 | | | 
3640744220.0 | | | 
3892423886.0 | | | 
238766140 | | | 
660037107 | | | 
722380134 | | | 
1040474575 | 3302357737.0 | Tattered Titan Mark |
| | 3538928634.0 | Brave Titan's Mark |
| | 1040474575 | Brave Titan's Mark | 
1056171153 | 587276683 | Scorched Hunter Cloak |
| | 1056171153 | Daring Hunter Cloak |
1331814296 | 572122304 | Shattered Warlock Bond |
| | 1331814296 | Wise Warlock Bond |
1961777956 | | | 

Not sure if it's a great way to document what's happening here, but above I have listed each of the redacted LoreDefinition hash ids. Next I list the item hashes and item names associated to that LoreDefintion hash. Where there are multiple associated items to a single lore def, the lore def is left blank and only the associated item info is listed. 

As you can see, many of the LoreDefinitions are not associated with an item. In this case, it makes sense that they are redacted. But the instances where there are multiple items associated with a given LoreDef, might be the reason why that LoreDef is labeled as redacted. Just a guess though. 

Hope this helps the team out in getting this resolved. 

P.S. Yes, the itemHash for second Brave Titan's Mark is the same as the loreDef.

**Comment by vthornheart-bng** [comment]
Good info, thank you!  I'll ask around and see which ones we're allowed to unredact.

**Comment by baxter** [comment]
Hey @vthornheart-bng, any update on this? 🙂

**Comment by vthornheart-bng** [comment]
Oh, yes!  Thanks for the reminder - indeed, we should be able to get this all fixed up.  I need to make a TFS item out of this so I don't lose sight of it - I'll do that when I get in the office.

**Comment by baxter** [comment]
That's great news, thank you 😄

**Comment by vthornheart-bng** [comment]
Just as a quick update - all of those Lore entities above that weren't associated with Items turned out to be totally empty in the game content itself!  Apparently these were test and placeholder items that no one ever bothered to remove from the game content, and they've got nothing in them (no strings, no icons, just empty entities).

The other ones, however, I will push to get unredacted.

**Comment by vthornheart-bng** [comment]
TFS 615932 for the items that actually had real Lore.  It won't be in the minor content update happening this week, but it should come through in next week's more substantive deployment.
