### ISSUE TITLE
GetVendor: Kind of messy data

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#415]
I know this is a beta endpoint, just wanted to make sure you were aware of the issues. I'm working on bringing vendor views into DIM, and here's what Sloane looks like (1062861569):
<img width="465" alt="screen shot 2018-02-18 at 4 40 56 pm" src="https://user-images.githubusercontent.com/313208/36358946-cb4d5b54-14ca-11e8-8a78-4a8a371a25f0.png">

A bunch of the categories have no title (I default them to "Unknown") and the rest are pretty unorganized. I don't see the special weekly sale item.

Here's Zavala:

<img width="507" alt="screen shot 2018-02-18 at 4 45 19 pm" src="https://user-images.githubusercontent.com/313208/36358972-2c8ef54e-14cb-11e8-8f09-1e4d5ca58955.png">

**Comment by vthornheart-bng** [comment]
This is another one that I've fixed up internally, but that won't actually go live for a couple of weeks.

When it does, there's going to be one significant change for those of you using the beta Vendors API: the DestinyVendorCategoriesComponent is now going to be pointing at the index of "displayCategories" (on DestinyVendorDefinition).  The property in question is being renamed to force compliance with the breaking change (and for clarification in the intended use of the index) - it's being renamed to displayCategoryIndex from merely "categoryIndex".  The upside of this is that our category information will finally be correct and will match what you see in game!

**Comment by bhollis** [comment]
<img width="470" alt="screen shot 2018-02-22 at 8 29 46 pm" src="https://user-images.githubusercontent.com/313208/36577944-49c33a7a-180f-11e8-965c-2d3b72d2a0c8.png">

Definitely better as of the latest deployment!

We're already using `displayCategoryIndex`  and `displayCategories` so hopefully we're OK?

**Comment by vthornheart-bng** [comment]
Excellent!  Yeah, that is the good stuff!

There are still issues regarding items that are "limited time", which are fixed internally and be resolved in our next deployment a couple of weeks from now.

**Comment by vthornheart-bng** [comment]
The next major release we do - next week, ideally ~the 7th - should fix this issue.
