### ISSUE TITLE
UnhandledException for Vendors on profile with little/no progress 

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#424]
Just a heads up - during development against the new Vendors APIs, I found the Vendor requests for my Xbox characters are failing, but PS4 is working fine.

```
## Vendors
curl "https://www.bungie.net/Platform/Destiny2/1/Profile/4611686018432128055/Character/2305843009267223210/Vendors/?components=400,402,401" \
     -H 'Cookie: bungled=939348979547082511; bungledid=B+1QxQdUtw1OuFLINR80uziXJSs7sPfUCAAA; \
     -H 'Authorization: Bearer ***** Hidden credentials *****' \
     -H 'X-Api-Key: ***'
```

I suspect this is due to my Xbox profile having very little or no progress at all. I preordered it and maybe played a bit of the beta, but really nothing since.

Note a huge issue, just thought you might like to know :)

**Comment by vthornheart-bng** [comment]
Oh - if you only played the beta, indeed you'd get a failure probably in any request.  What do you get when you hit your normal GetProfile request for that account?

**Comment by joshhunt** [comment]
I get a fairly complete set of data back for GetProfile `https://www.bungie.net/Platform/Destiny2/1/Profile/4611686018432128055/?components=100,102,200,201,204,205,300,307,305,500` - as far as I can tell nothing to indicate this user hasn't done much.

Looking more at this profile's activity, it has [one activity](https://destinytracker.com/d2/pgcr/51688700) on character 2305843009267223208 where it attempted the first story mission but did not finish. I assume this was after beta.

**Comment by vthornheart-bng** [comment]
Ah, okay - I bet this is a scenario then where the user hasn't actually reached a point where there's any Vendor that they can get to in the game, and that we're not handling that well on our backend.  Good stuff!  I'll take a look, thanks for reporting it!

**Comment by vthornheart-bng** [comment]
TFS 615626
