### ISSUE TITLE
Objective progress isn't available in Vendor API

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#425]

**Comment by vthornheart-bng** [comment]
Hmm, for which kinds of objectives?

**Comment by joshhunt** [comment]
Sorry about the _brief_ issue.  You know what, In writing this up further and looking at it again it appears as its actually there now... strange. I'll close this for now and reopen if I have issues. Here's what I originally wrote:

---

I was investigating using the Vendors API as a workaround to https://github.com/Bungie-net/api/issues/339 to check what ornaments the user has unlocked. 

If you provide `ItemPlugStates` you'll get data like 

```
            "2798463723": {
              "plugItemHash": 2798463723,
              "plugObjectives": [
                {
                  "objectiveHash": 1617393936,
                  // "progress": 17, // originally I thought this was missing
                  "complete": true
                }
              ],
              "canInsert": true,
              "enabled": true
            },
```

Which is usefully to see what ornaments are unlocked, but it's lacking the `progress` field on each of the objectives which is useful to show the progress the player has to unlocking it. 

Is there any way we could get this field passed through on objectives on ornament plugs?
