### ISSUE TITLE
Question: CORS using Origin Header for Browser Based Apps

### ISSUE THREAD

**Issue by theoperatore** [Bungie-net/api#43]
Heyo, quick question about how the `Browser Based Apps` are supposed to work.

I assumed that If I filled out this section on https://www.bungie.net/en/Application/:

<img width="848" alt="screen shot 2017-09-01 at 9 04 25 pm" src="https://user-images.githubusercontent.com/395178/29991663-2722184a-8f59-11e7-8816-235c805a9a9a.png">

waited some time, then tried to hit an endpoint via browser only (no proxy), I'd be able to get data back.

However, I am still getting blocked:

<img width="1129" alt="screen shot 2017-09-01 at 9 03 34 pm" src="https://user-images.githubusercontent.com/395178/29991670-48b8acbc-8f59-11e7-8aa1-14958377b82b.png">

Am I doing something wrong? is this functionality just not ready yet?

Thanks!

**Comment by theoperatore** [comment]
just for reference, the browser is sending the same Origin header as I've entered for my app:

<img width="1347" alt="screen shot 2017-09-01 at 9 09 11 pm" src="https://user-images.githubusercontent.com/395178/29991701-e4a4b328-8f59-11e7-8f92-a7523cda5bdf.png">

**Comment by vpzed** [comment]
Double check your x-api-key header and API key value is correct.  When I got that error I had the x-api-key header wrong(copy/paste issue in API key), so the Bungie servers couldn't lookup my app to find the Origin Header setting to match what was being sent.  

[Here is a help article too](https://www.bungie.net/en/Help/Article/45481)

**Comment by lax20attack** [comment]
Looks like you're missing www.bungie. Need that www I believe. Also watch out for the trailing slash in the future.

Check this for detail OAuth info
https://lowlidev.com.au/destiny/authentication-2

**Comment by theoperatore** [comment]
oh man @lax20attack yeah it was the missing `www`. Once I put that in there everything worked as expected. ugh. late nights are rough.
