### ISSUE TITLE
Gunsmith reports the wrong mods for sale

### ISSUE THREAD

**Issue by ttgmpsn** [Bungie-net/api#430]
From CoO up until the patch this Tuesday, the Gunsmith had [a bug](https://www.reddit.com/r/DestinyTheGame/comments/7ri98s/the_two_different_gunsmiths_part_2/dsy18ul/?context=3) where he would have two different sets of legendary mods for sale, depending on [the amount of blue mod stacks in the character inventory](https://www.reddit.com/r/DestinyTheGame/comments/7ri98s/the_two_different_gunsmiths_part_2/). The Vendor API was unaffected by this, and always reported the same set of mods (the "12 or less blue mod stacks" version), independent of the character inventory.

The bug seems to be fixed in-game since Tuesday. However, now the API reports the wrong selection of mods. For example, today, he sells the Arc Damage Mod, Helmet Arc Impact Mod and Leg Void Impact Mod in-game. However, the API reports that he sells the Kinetic Damage Mod, Titan Mark Arc Paragon Mod and Arms Void Impact Mod.

Pure speculation: With fixing this bug, the game now always displays the (former) "13 or more blue mod stacks" set of mods. The API wasn't updated to reflect this, and still lists the (now unavailable) "12 or less blue mod stacks" set of mods, leading to a miss-match between API data and in-game data.

**Comment by vthornheart-bng** [comment]
Interesting - thank you for reporting this!  I'll have to take a peek.

**Comment by vthornheart-bng** [comment]
TFS 619273

**Comment by vthornheart-bng** [comment]
Ah, turns out I already fixed this in TFS 611312.  However, that will not be deployed until next week.  Hang tight, the fix will be coming midweek next week!
