### ISSUE TITLE
Cannot get informations for some users

### ISSUE THREAD

**Issue by predalpha** [Bungie-net/api#431]
Hello i experience issues getting game informations for the following users.

Below the users i cannot retrieve datas :

- DermoFenac ; destinyUserInfo->membershipId = 4611686018467401196 (no bungieNetUserInfo)
- XxXRoGXxXQC ; bungieNetUserInfo->membershipId = 12462211
- AEIS ; bungieNetUserInfo->membershipId = 10176384

**Comment by vthornheart-bng** [comment]
What error results do you get when you try to access them?  Can you send the specific error code(s) you're getting as a response?

**Comment by vthornheart-bng** [comment]
(also if you can send the URL of the request you're making, I'll know which endpoint you're trying to hit that's giving the error)

**Comment by predalpha** [comment]
please apologize for my comment. Its totally my fault. The 2 last accounts have multiple bungie account and i was always getting the first one ...

**Comment by vthornheart-bng** [comment]
Oh no, it's okay!  No need to apologize, it's all good!

Shall I close this for now?  Let me know if you run into any more problems!
