### ISSUE TITLE
Add a way to get the active challenges for an activity

### ISSUE THREAD

**Issue by ttgmpsn** [Bungie-net/api#432]
Currently, there doesn't seem to be a way to get the active challenges for an activity when this activity isn't featured in a milestone.

Simplest example are the daily rotating planetary challenges. If the planet isn't featured as a milestone ("complete 3 challenges on xyz"), you are unable to retrieve them via the API, or at least I didn't found a way. The Manifest lists all *possible* challenges, but not the currently active ones.

There is a "workaround" for this via Bungie.net by parsing the output of `https://www.bungie.net/en/Explore/Detail/DestinyActivityDefinition/<ActivityHash>` ([EDZ Patrol](https://www.bungie.net/en/Explore/Detail/DestinyActivityDefinition/3143798436) as an example), but I don't think this is the way it should work (by the way, [Mercury](https://www.bungie.net/en/Explore/Detail/DestinyActivityDefinition/1073289414) stopped listing the challenges on Feb 22).

I think a nice way to solve this would be by adding the challenges to the CharacterActivities component, and add the (available, unlocked) Planet Patrol activities to that output as well. Currently, only Raid and PvP are listed there, planetary patrols are not.

(I thought I read this feature request here a while ago, but searched around the issue tracker and couldn't find it - if this is a duplicate, sorry!)

**Comment by vthornheart-bng** [comment]
Also a great idea, I dig that!

**Comment by vthornheart-bng** [comment]
TFS 619259

**Comment by ttgmpsn** [comment]
This also includes the new Raid Lair modifiers, that currently can't be fetched via the API :(

**Comment by vthornheart-bng** [comment]
Phew, sorry this has been such a long time coming!  It fell into the deep abyss of our backlog.

This will be in our next deployment, targeted 10/22.  

Added challenges, modifierHashes, booleanActivityOptions and loadoutRequirementIndex to DestinyActivity data.

They will only be returned if there are any values for the respective property.
