### ISSUE TITLE
JsonDeserializationError on GroupV2.ApprovePending/GroupV2.ApproveAllPending

### ISSUE THREAD

**Issue by Javano** [Bungie-net/api#433]
Trying to access these GroupV2 Approve/Deny endpoints and I'm continually getting this same error.

Is there some data I'm supposed to be posting aside from the path params? I'm confused as to why it's asking me to include a GroupApplicationRequest message object, but not providing any values to include therein. 

Request details: 
![image](https://user-images.githubusercontent.com/6813253/36914397-cd473816-1e12-11e8-8296-be4692a789b7.png)

Response details:
![image](https://user-images.githubusercontent.com/6813253/36913895-fbfbca20-1e10-11e8-850e-d72af937d63e.png)

**Comment by vthornheart-bng** [comment]
Oh, yes - so it's kind of trite that it's required in retrospect, but application approve/deny responseds require a post body of the form:

{
"message": "Whatever you want to tell them about being approved/denied, or just a blank string"
}

In an ideal world we'd probably make that optional, but I don't know if or when we're going to get around to that.  So for now, just pass that!

**Comment by floatingatoll** [comment]
Is the message provided here in the API call eventually made available to the user(s) being approved through history or dialogs or whatever? Or is it discarded unseen and unloved?

**Comment by vthornheart-bng** [comment]
Yes, it ends up in the notification that gets sent to the user who is being approved/denied.

**Comment by vthornheart-bng** [comment]
(I'll close this for now unless you end up running into any other snags - let me know!)
