### ISSUE TITLE
Expose Traffic/Statistical Data on Application page

### ISSUE THREAD

**Issue by lowlines** [Bungie-net/api#435]
As part of a discussion had with @Tetron-bng this is a feature request to expand the Application section on Bungie.net to expose traffic and statistical data so app developers can see how their apps are hitting Bungie's servers. Perhaps there could also be a way to see things like which endpoints/services are being hit the most as well as any errors that are getting logged.

**Comment by vthornheart-bng** [comment]
Tetron made sure that at least the API for such information will be exposed in the release after this one (so ~3 weeks from now).  I'll give more details when it comes closer to release!
