### ISSUE TITLE
Difference/relationship between Pending and Invited members?

### ISSUE THREAD

**Issue by heymrcarter** [Bungie-net/api#438]
It wasn't immediately clear to me looking at the docs for the GetPendingMemberships and getInvitedIndividuals what the relationship is between them.

It makes sense that getInvitedIndividuals would only return individuals that have received an invite from a clan admin, but once an individual receives an invitation are they not pending members until they accept the invite?

For my clan GetPendingMemberships returns one individual, while getInvitedIndividuals returns five. In this case is it that one individual requested to join the clan, while an admin sent invites to the five individuals returned in the getInvitedIndividuals response?

**Comment by vthornheart-bng** [comment]
Ah, yes - so the difference is that pending memberships is the list of people who are actively requesting to join the group without being invited to join(and thus an admin has to approve their entry), and invitations are things sent *from* an admin (and thus already approved) and are awaiting response from the person to whom the invitation was sent.

**Comment by ephemeralquark** [comment]
Thanks for the clarification!

**Comment by heymrcarter** [comment]
Thanks for the clarification!

**Comment by vthornheart-bng** [comment]
No prob!
