### ISSUE TITLE
The secondary overlay for this weeks nightfall is the wrong image

### ISSUE THREAD

**Issue by designker** [Bungie-net/api#440]
the itemHash definition for the emblem is 10493725

For the secondaryOverlay is a Jpeg instead of a PNG and the JPEG is just a solid white square https://www.bungie.net/common/destiny2_content/icons/e7462203ff7f308ccf95a79a63f7a107.jpg

**Comment by vthornheart-bng** [comment]
Thanks for letting me know, I'll take a peek!

**Comment by vthornheart-bng** [comment]
Now with a real bug #, 627758

**Comment by vthornheart-bng** [comment]
Finally got around to looking at this, and it looks like the solid white square is coming directly from game content... which means the game is somehow sourcing from other data, or there's more to the story of this overlay data than I realized, but happens to only be used by this emblem.

I'm hitting up the folks who actually make those icons now to see if they can give me more information.  Not sure if we'll be able to provide you a real version of this icon if this ends up requiring a significant amount of work, given that it's the only item running into it.  If we can't, we may end up just turning that icon transparent and this particular item won't show a secondary overlay image.  It at least will look less broken if we do that.  We'll see what they say, but that's my planned worst case.

**Comment by designker** [comment]
Yeah don't worry about it. I now just parse the url for .jpg and don't show them as they should always be a png.

**Comment by designker** [comment]
I'm closing this as it can be easily worked around

**Comment by justrealmilk** [comment]
I was about to post about this emblem issue. Just bumping the issue :)
