### ISSUE TITLE
No reward vendor hash for Benedict 99-40

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#443]
The Leviathan faction character Benedict 99-40 has no associated rewardVendorHash, meaning we can't easily preview his rewards. I think it should be 3231728835 ("Imperial Engram")

**Comment by vthornheart-bng** [comment]
Ah, good eye!  I'll take a peek when I get the chance.

**Comment by bhollis** [comment]
This is true for Ana Bray as well.

**Comment by bhollis** [comment]
This appears to have been fixed!
