### ISSUE TITLE
I don't have enough space in my vault 

### ISSUE THREAD

**Issue by UTAaronSr** [Bungie-net/api#444]
I have to get rid of lots of my items to habe room for my useful items. I sometimes have to get rid of the good stuff to help clear up room. Can you please expand the vault.

**Comment by v-fedorov** [comment]
Neat idea, ill put in a request to increase the vault by 5 more item slots.

**Comment by TorKallon** [comment]
5 would not be enough. I think we need 7 more slots.

**Comment by v-fedorov** [comment]
The magic Bungie number, perfect. Adding 7 instead of 5 will delay the release by an additional 2 months but its worth it.

Feel free to close the issue

**Comment by Tetron-bng** [comment]
Please share game related concerns on the Bungie.net Feedback forums.
