### ISSUE TITLE
Forum API: GetTopicsPaged no way to filter by Forum Category?

### ISSUE THREAD

**Issue by GrayWulf25** [Bungie-net/api#451]
Hi. I am trying apply a filter to GetTopicsPaged request to restrict it to Help forum only (or a user choice of Forum Category e.g Destiny2, Feedback, OffTopic etc)

I have tried adding ?tagstring=Help (and other variations #Help, help, HELP) as a query string but it appears not to work. With Category Filter set to 0 for None (i.e All) , I am getting all the Recruitment topics which I don't want. Questions:

i. Is there a way to filter precisely for Forum Category I am not seeing?
ii. What are valid string values for **tagstring** query parameter?

Example end-point: /GetTopicsPaged/2/0/0/3/4/0/?locales=en?tagstring=Help

**Comment by vthornheart-bng** [comment]
Ah, I think I see the problem: you're passing the correct value "help" for the tagstring, but the querystring portion of the URL itself isn't quite right.  Try this instead, where the second ? is instead replaced with "&":

https://www.bungie.net/Platform/Forum/GetTopicsPaged/2/0/0/3/4/0/?locales=en&tagstring=Help

Give that a shot!

**Comment by GrayWulf25** [comment]
Thanks again. My bad, I missed that typo after a long day in Java and Javascript. Will take my frustration out in Mayhem!

Sent from Mail for Windows 10

**Comment by vthornheart-bng** [comment]
Sweet, glad it worked!  No worries at all, I have done the same thing myself!
