### ISSUE TITLE
Activity Definition PGCR Images link to Bungie.net root

### ISSUE THREAD

**Issue by sgtfrankieboy** [Bungie-net/api#46]
The PgcrImage property is missing `/img/destiny_content/pgcr/`. Adding that will make the images load properly. 

This is not needed for the placeholder images.

**Comment by vthornheart-bng** [comment]
Ah, excellent find!  This was a last minute bug that I fixed... but in the wrong branch!  Ugh!  Next deployment will fix this.  Indeed, if you all want a manual workaround, take those jank URLs and prepend that /img/destiny_content/pgcr/ prefix.
