### ISSUE TITLE
Crimson Doubles Heroic PVE

### ISSUE THREAD

**Issue by TorKallon** [Bungie-net/api#462]
About 800ish PGCRs are currently showing up with mode 50, like so:
-- https://www.bungie.net/en/PGCR/1599189717

These look wrong because they show PVE activityHashes and other data that doesn't look like a Crucible Doubles match. And Doubles shouldn't be up this week at all.

**Comment by vthornheart-bng** [comment]
Ah, thanks!  I'll do a little digging and ask around.

**Comment by vthornheart-bng** [comment]
Found out what's up - these are "Heroic Adventures," but have been improperly labeled as Doubles.  I'll file a bug on our end and get it fixed up for the next deployment.  The fix is on the BNet side, so it should fix them all retroactively once our fix deploys.

**Comment by vthornheart-bng** [comment]
TFS 651683, should be fixed for 5/16 deployment.

**Comment by TorKallon** [comment]
Thanks! We will fail them for now and reparse them after they’re fixed.

**Comment by vthornheart-bng** [comment]
Perfect, good deal.
