### ISSUE TITLE
The TierTypeDefinition mistakenly has the 'Uncommon' tier defined in English as 'common'.

### ISSUE THREAD

**Issue by designker** [Bungie-net/api#464]
I just noticed this in-game and all 3rd party sites show it incorrectly due to the DestinyItemTierTypeDefinition having the wrong text. The hash is "2395677314"

**Comment by vthornheart-bng** [comment]
This is covered in #330, but I'm glad you brought it up because it fell off my radar.  I'll close this one as a duplicate for now, but I'll go back to 330 and add a TFS #
