### ISSUE TITLE
Content Warning for DLC2: Several Activities removed from database, replaced with variants that have only changed identifiers

### ISSUE THREAD

**Issue by vthornheart-bng** [Bungie-net/api#466]
Sorry for the late breaking notice, but I just realized that we haven't given you guys the heads up - I only just recently noticed this had happened in the latest content.

During DLC2 development, the internal identifiers of all of the PVP maps were altered: as such, the hash identifiers that our systems refer to were all changed.  I don't know if this will impact any of you - when this happened in Destiny 1, I wrote mapping logic to make sure that PGCRs could map to the new versions of the Activities, and that mapping logic continues to function correctly in Destiny 2: so you should be safe there.  But if you were directly referring to the hash identifiers of any PVP maps for your logic, you will want to inspect the new content when it goes live and change the hash identifiers that you are using.

I apologize for the tardiness of this warning!  Hopefully not many (any?) people are actually using hard-coded references to Activity hash identifiers.  But just in case, please take a look at the new Activity content carefully and change your references as needed.

**Comment by ckhicks** [comment]
Thanks for the heads up!
