### ISSUE TITLE
Known bug: Nightfall Score Multiplier and Handicap not being returned

### ISSUE THREAD

**Issue by vthornheart-bng** [Bungie-net/api#468]
Just fixed a bug in "display only" objectives - such as Nightfall card objectives - where it was zeroing out the progression value if there was no game logic override on the value.

This will hopefully go out with next week's release, but until then you'll be getting 0 for those values when you look at the Nightfall card's objectives (and anywhere else in objectives where the objective itself is marked as "display only" and is not being driven by complex game logic)

**Comment by floatingatoll** [comment]
Will PGCRs be retroactively corrected or remain zeroed when the fix goes live?

**Comment by vthornheart-bng** [comment]
Oh, it shouldn't be the PGCRs that are failing to return the right data: just the actual modifier item's sockets and the objectives on it.
