### ISSUE TITLE
The new Warmind vendor's (Ana Bray) faction definition is lacking tokenValues property

### ISSUE THREAD

**Issue by serkanbal** [Bungie-net/api#470]
Hello,

The faction definition of the new Warmind vendor (hash: 3859807381) is lacking tokenValues property.   This property tells us how much each material reward reputation when it is returned to the vendor. All other vendors who accept tokens and planetary materials have this property in their definition.

**Comment by vthornheart-bng** [comment]
Ah, good find!  Indeed, this is an oversight on our part.  Thanks for reporting it!  I'll look into this and file a bug shortly.
