### ISSUE TITLE
allPvP is including private matches

### ISSUE THREAD

**Issue by bladefist** [Bungie-net/api#472]
Title says it all.  The `AllPvP` grouping contains private matches which is warping peoples stats.  So far it appears that the mode specific stats are fine, it's just the `AllPvP`

I don't think private matches should show up anywhere except PGCR/PGCR History.

Thanks!

**Comment by vthornheart-bng** [comment]
TFS 654069

**Comment by bladefist** [comment]
@vthornheart-bng was this ever fixed? If yes, it's happen again, if no, please :)

**Comment by vthornheart-bng** [comment]
Private matches will no longer be included with allPvP as of the January release!
