### ISSUE TITLE
VAULT_KIOSK vendor has duplicate items in its itemList

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#480]
The VAULT_KIOSK vendor (hash 622587395) represents all the potential collectibles (exotics, emblems, etc) in the game. Since DLC2, this vendor's `itemList` contains duplicates - for example, index 218 and 219 are both the Prometheus Lens. I can't see any difference between the two, so it seems to be just a bug.

**Comment by bhollis** [comment]
My hypothesis was that these would light up for masterworks versions - is that right? If so, it'd really be helpful to tell which one represented the masterwork and which the normal version.

**Comment by vthornheart-bng** [comment]
Though I'm not able to check it right now to confirm, I'm 99% certain that your hypothesis is correct @bhollis.  I'll put in a backlog item when I get in the office next to see if we can return some info to help distinguish between them.

**Comment by bhollis** [comment]
Closing, this issue is obsolete.
