### ISSUE TITLE
New Warmind items are not appearing in screenshots

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#485]
Some of the new gear in Warmind have 'empty' screenshots. See items

1929278169 // BrayTech Osprey 
2084611899, // Last of the Legion
3416932282 // Turris Shade Mark
4135228483, // Turris Shade Plate
3866356643, // IKELOS_HC_v1.0.1
1723472487, // IKELOS_SMG_v1.0.1
1887808042, // IKELOS_SG_v1.0.1
159056377, // Requiem-45
2556748915, // BrayTech Researcher's Robes
2171006181 // Service Revolver

Further these items have a funky post - the guarian is centred in the middle of the image.

1886868481, // Qiao's Care
2513313400, // Insigne Shade Gloves

**Comment by floatingatoll** [comment]
Are all of the items listed available in-game today from various loot sources?

**Comment by joshhunt** [comment]
BrayTech Osprey at least is, and I have no reason to believe the rest arent.

I know there are a few funky 'test' items in the latest manifest that lack data, but I believe all the above items are obtainable.

**Comment by floatingatoll** [comment]
Ah — I couldn't find any Internet proof that a single person has received Last of the Legion and posted on Reddit, Youtube, or Twitch about it — so that's why I wondered.

But I do have Requiem-45 and IKELOS_HC, so some of them *are* known to drop.

**Comment by joshhunt** [comment]
fair point. It's possible that some of these aren't obtainable in game at the moment, but many of them are.

**Comment by vthornheart-bng** [comment]
Hmm, I'll have to do some digging!  It technically shouldn't matter if you can earn them in game yet, as long as they are *actual* weapons.  This suggests that there may be an issue in the way that our import process identifies which items need screenshots, or it may be that I fucked up the actual new screenshot deployment!  I'll have to investigate.

TFS 658021 for tracking this when I can get to it.  I'm a bit bogged down by other issues that have come up in the last few days, but at least we'll have this tracked now.

**Comment by vthornheart-bng** [comment]
Oh, I see now - it's not that there's no screenshot, it's that there's a screenshot and it's blank.  Ahh.

**Comment by vthornheart-bng** [comment]
Okay, I'm going to try to regenerate those and see if I can get us some better screenshots.

**Comment by vthornheart-bng** [comment]
Okay, I was able to successfully generate screenshots for these.  They should go live later today.
