### ISSUE TITLE
Manifest table ID mismatches

### ISSUE THREAD

**Issue by jamie1192** [Bungie-net/api#486]
I've just managed to download the .content manifest on my Android app, unzip and convert to to a readable/queryable SQLite database.. i've just opened the file in DB Browser to inspect what's going on, and *many, many* rows have a mismatched id values that don't represent the items hash value, therefor making it impossible to query itemHashes within the database..

Sleeper Simulant for example is fine, it's row ID matches it's item hash (136852797), but SUROS Regime's row ID within the DestinyInventoryItem table is -1438283734 (but the items hash value is 2856683562).. so what's the go here?

**Comment by ArkahnX** [comment]
Hey, [give this and further sections](https://github.com/vpzed/Destiny2-API-Info-wiki/blob/master/API-Introduction-Part-3-Manifest.md#manifest-updates) of a community made wiki a read, that should help! by default the values in the manifest dont match the itemHashes (or other types of hashes).

Basically the numbers are signed 32bit integers, whereas you are looking for the unsigned value. There was a conversion formula someone made, but Im having a hard time finding it
