### ISSUE TITLE
Battletags not updating after users change them

### ISSUE THREAD

**Issue by migit128** [Bungie-net/api#488]
Example API call: https://www.bungie.net/platform/User/GetBungieNetUserById/17785635/

That returns: 
```
{{
  "Response": {
    "membershipId": "17785635",
    "uniqueName": "17785635",
    "displayName": "Chunka",
    "profilePicture": 70713,
    "profileTheme": 1101,
    "userTitle": 0,
    "successMessageFlags": "0",
    "isDeleted": false,
    "about": "",
    "firstAccess": "2018-02-10T22:42:32.209Z",
    "lastUpdate": "2018-04-28T18:43:29.712Z",
    "showActivity": true,
    "locale": "en",
    "localeInheritDefault": false,
    "showGroupMessaging": true,
    "profilePicturePath": "/img/profile/avatars/cc000011.jpg",
    "profileThemeName": "d2_01",
    "userTitleDisplay": "Newbie",
    "statusText": "",
    "statusDate": "0001-01-01T00:00:00Z",
    "blizzardDisplayName": "Chunka#11563"
  },
  "ErrorCode": 1,
  "ThrottleSeconds": 0,
  "ErrorStatus": "Success",
  "Message": "Ok",
  "MessageData": {}
}}
```

This is one of my clan members.  He changed his battletag to Infinite#12319 over a week ago.

**Comment by migit128** [comment]
All have logged into the game since changing their names.  

The only way to rely on something other than a battletag is to force the 450 people in my clans to visit a website I'd have to make to link their discord account to their battle.net account(s).  There is no way to guarantee everyone does it and I'd lose members if I have to kick those who dont.

For PSN the display name is unique.  For XB1 the display name is unique.  Why can't it be the same for battle.net?  The numbers are incredibly important from a usability perspective for those using your API.

**Comment by floatingatoll** [comment]
Battle.net required Bungie to withhold it. See #281 and #396.
