### ISSUE TITLE
Battletag does not contain the numbers when calling GetBungieNetUserById

### ISSUE THREAD

**Issue by Akumati1435** [Bungie-net/api#489]
Example API call: https://www.bungie.net/platform/User/GetBungieNetUserById/38450/

That returns: 
```
{{
  "Response": {
    "membershipId": "38450",
    "uniqueName": "BillyBlaze314",
    "displayName": "BillyBlaze314",
    "profilePicture": -7,
    "profileTheme": 1103,
    "userTitle": 0,
    "successMessageFlags": "32",
    "isDeleted": false,
    "about": "",
    "firstAccess": "2007-01-25T19:25:34.907Z",
    "lastUpdate": "2017-09-05T01:14:08.743Z",
    "psnDisplayName": "BillyBlaze314",
    "xboxDisplayName": "BillyBlaze314",
    "showActivity": true,
    "locale": "en",
    "localeInheritDefault": true,
    "showGroupMessaging": true,
    "profilePicturePath": "https://halo.bungie.net/Stats/emblem.ashx?s=90&0=3&1=2&2=21&3=2&fi=3&bi=20&fl=1&m=3",
    "profileThemeName": "d2_03",
    "userTitleDisplay": "Newbie",
    "statusText": "",
    "statusDate": "2017-07-06T20:28:33.733Z",
    "blizzardDisplayName": "MassMan"
  },
  "ErrorCode": 1,
  "ThrottleSeconds": 0,
  "ErrorStatus": "Success",
  "Message": "Ok",
  "MessageData": {}
}}
```

**Comment by floatingatoll** [comment]
It should return the numbers when you query your own account but not anyone else's:

https://github.com/Bungie-net/api/issues/281#issuecomment-341800309

**Comment by migit128** [comment]
@floatingatoll Incorrect.  This API call is there to give you the full battletag.  This person was in my clan until last night and he was the only person out of about 425 people who did not have a full battletag in the blizzardDisplayName field.

**Comment by floatingatoll** [comment]
Based on the comment I linked, it could potentially be considered a bug that you have access to a full battletag. I don’t know for sure though!

**Comment by migit128** [comment]
@floatingatoll It's a different API call.  They removed it from GetProfile but you can still get it from GetBungieNetUserById.

**Comment by vthornheart-bng** [comment]
I'll have to look into it - we were asked to not return the numerical portion of the battletag.  If we're still returning it somewhere, we need to get rid of it unfortunately.
