### ISSUE TITLE
Destiny2/SearchDestinyPlayer/ returns Destiny 1 results

### ISSUE THREAD

**Issue by lax20attack** [Bungie-net/api#49]
As of right now, this user has not played Destiny 2. (This will change in about 3 hours)

https://www.bungie.net/Platform/Destiny2/SearchDestinyPlayer/1/G0dly%2023/

Might be worth noting this user did play the beta.

**Comment by vthornheart-bng** [comment]
Indeed - this is a bummer of an issue, though I'm not positive that we'll have a good workaround for this.  It is very possible that this endpoint will always end up returning users who have played Beta, or joined a Clan, but haven't yet actually played retail Destiny 2.  You'll have to handle the scenario where you get such a user and your query to get their Destiny data fails - at least for the forseeable future.

(by wontfix I mean "I'd like to fix, I just don't know if it will be feasible or when we will")

**Comment by lax20attack** [comment]
How about adding a property to let us know if this account has a proper D2 character? 

My concern is we're going to have to make another call to find out if this character has destiny 2 data, wasting resources on both ends.

**Comment by floatingatoll** [comment]
Are these users likely to be common and frequent? Specifically:

1) D2 clan and/or D2 beta player
2) Not in Destiny 2

**Comment by vthornheart-bng** [comment]
I'm hoping that they'll become significantly less frequent in the coming days - if it does become a more frequent issue, I wouldn't be opposed to adding some metadata specifically to the SearchDestinyPlayer endpoint.  We don't have a good equivalent of what we used to use for this kind of data anymore - GetBungieAccount - but if this ends up continuing to be a frequent scenario I'll give this further consideration.  For now, I'll reopen this as an enhancement suggestion, so we don't lose sight of it.

**Comment by Tomalaya** [comment]
I'm hitting an error when calling Destiny2.Getprofile with the results from Destiny2.SearchDestinyPlayer, saying {"ErrorCode":18,"ThrottleSeconds":0,"ErrorStatus":"InvalidParameters","Message":"The input parameters were invalid, please enter valid input, and try again.","MessageData":{}}

Is this a follow on problem to D1 membership info being returned or is something else for which I should post as a new issue?

**Comment by vthornheart-bng** [comment]
Hmm, it sounds like a different issue - feel free to post a new Issue about that one, and also when you post it give the specific URL that you were hitting.  InvalidParameters means that something in the URL was not interpreted correctly, so I'd like to see what URL you were hitting to discern what component may have had invalid data - or what data we may be interpreting incorrectly!
