### ISSUE TITLE
Duplicated challenges on milestones

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#491]
This is sort of a reprise of #395 - the "Strikes Challenges" milestone seems to give too many challenges out. I see Vanguard Strikes, Heroic Strikes Playlist, and Nightfall twice each. There are a handful of different Activity definitions for things like Vanguard Strikes that seem to differ in which strikes they offer and their description. I'm not sure if they are really something a player could achieve challenges separately in, though.

<img width="261" alt="screen shot 2018-05-18 at 10 15 14 pm" src="https://user-images.githubusercontent.com/313208/40265304-c84b29b6-5aea-11e8-8b2e-2d5af63ce4b6.png">

**Comment by vthornheart-bng** [comment]
I'll give it a look - I think this is due to there being different difficulty levels that each have their own sets of challenges, which means this is right but you'd have to split it up in your UI by difficulty.  But I could be remembering incorrectly - when I get a chance I'll dig in a bit.

**Comment by bhollis** [comment]
No longer relevant :-)
