### ISSUE TITLE
Masterwork objectives don't have the right completion value

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#492]
If you look at the objective definitions for masterwork objectives (such as hash 2579044636), the completionValue is 1 - I'd expect it to be 250 ("Get 250 kills").

**Comment by designker** [comment]
This isn't an issue and is a dupe of #487 where I commented about what is going on

**Comment by bhollis** [comment]
It’s not really a dupe. I already knew all the stuff you mentioned over there, but there remains a data bug - the objective on the masterwork catalyst itself does not state the correct

**Comment by bhollis** [comment]
Unless - maybe I’m looking at the wrong mod? Let me go check. Tha ks for the writeup by the way, its very helpful.

**Comment by designker** [comment]
Hash 2579044636 is the kills the weapon collects after you socket the catalyst. This is separate to the quest to finish the catalyst. For example take Crimson where you need precision kills. You might see progress of 1000 here. But this is just enemies killed. If you look as the reusable plug that will hold the number of precision kills you need and the correct objective with a sensible completionValue

**Comment by bhollis** [comment]
You're totally right! Thank you for helping out with this - I had been filtering out the "Upgrade Masterwork" plugs, and once I stop, everything looks fine (and I can remove the "hacks" I was using to try and force the catalyst to show the right objectives).

I agree that this and #487 are not issues.
