### ISSUE TITLE
Responce  schizophrenia

### ISSUE THREAD

**Issue by TangoJoker** [Bungie-net/api#497]
![image](https://user-images.githubusercontent.com/39468624/40324456-3c9f553c-5d41-11e8-9487-2b9ee141ae8d.png)

 As you can see I were passing grant_type. What's wrong with this request?

**Comment by floatingatoll** [comment]
Is a client_id parameter required here?

**Comment by vtubelsky** [comment]
I'm guessing, since It's a POST request, grant_type and code need to be passed in the request body, not as URL params. In Postman you'd need to specify them on the Body tab.

**Comment by TangoJoker** [comment]
> Is a client_id parameter required here?

Nope, I've figured it out. This parameters should be in body, not in header of the request.

**Comment by TangoJoker** [comment]
> I'm guessing since it's a POST request, grant_type and code need to be passed in the request body, not as URL params. In Postman you'd need to specify them on the Body tab.

Yeah, And now i'm getting 401 error, Not authorized. -_- Any ideas?
