### ISSUE TITLE
Question Oauth Platform Filtering

### ISSUE THREAD

**Issue by predalpha** [Bungie-net/api#507]
Hello,

Im currently playing with oAuth2 to get Player authentication for a future web application.

That application will be for PC players only and i was wondering if it was possible for users to log only if they have a Bungie Battle.net account. However when i ask for authorization url, it redirect to Bungie page with the 3 accounts type (PSN / Xbox / PC).

Have you any idea to filter that page or to only allow PC authorization ?

Regards

**Comment by Tetron-bng** [comment]
There is no mechanism to narrow the list down to a specific authentication type. A user who plays on multiple platforms may sign in with Xbox or PSN and still access their linked Battle.net account. I think the best you can do is after they sign in, pull their list of linked memberships and if you don't find a Battle.net account, let them know the app is not for them.  Or make the app work for all platforms?

**Comment by floatingatoll** [comment]
You could also title the app “XYZ for PC players only”, which would then be shown as the app title during authentication.

**Comment by predalpha** [comment]
I will go on @Tetron-bng solution. It's right that people can connect with any account type if they have at least a battle.net account. 
For the moment i can only focus for PC platform.
Thank you guys for your help !
