### ISSUE TITLE
Item Categories are returning D1 names

### ISSUE THREAD

**Issue by sgtfrankieboy** [Bungie-net/api#51]
The `DestinyItemCategoryDefinition` returns the wrong category names for weapons.

```
2 should be Kinetic (is Primary)
3 should be Energy (is Secondary)
4 should be Power (is Heavy)
```

Might also be happening with other categories, but I haven't checked those.

**Comment by vthornheart-bng** [comment]
Ah, good call!  I never bothered to rename those.
