### ISSUE TITLE
[question] vendors inventory different by account?

### ISSUE THREAD

**Issue by michabbb** [Bungie-net/api#512]
hi, i don´t know if that is a api question at all because it´s very general, so apologize if this it completly wrong here.

because i wanted to notify people in case banshee has the missing mod they need, i came to the question: do we all see the same mods ? every char of my account does, and a few tests with 3 other people show me, that they also see the same mods.

some older postings in the net say "no, it might be the same but they can be different, too".

so i try to get a correct answer here to find out, if i need the users token to check the mods banshee has or if i can query these with my own token so that no oauth for others is necessary here.

thanks a lot!

**Comment by vthornheart-bng** [comment]
Greetings!

I'm glad you asked, this is indeed a problem that could trip people up.  Try to avoid building apps that assume that the perks will be the same on items being sold by vendors.  In many (all?) cases currently this is true, but in the future this will not be the case if it is even the case right now (I actually don't know offhand!  The system was built such that they can vary, and thus so is our API: and it's up to the designers and the game content whether that happens... and I know there's a desire for more variability in this in the future): best to play it safe and assume they will be different!  Theoretically they can be different not only per account but even per character!

**Comment by michabbb** [comment]
Thanks for clarification!
