### ISSUE TITLE
[QUESTION] Date when a player joined a clan

### ISSUE THREAD

**Issue by JulesRx** [Bungie-net/api#517]
I trying to get the date when a player first join a clan but i can't find any information in the api. I tried listing the clan's members but i can't find it anywhere.
Is this in the api, and if yes, how do you get it ?

**Comment by floatingatoll** [comment]
Does the approvalDate response key exist on the endpoints you’re trying? It’s documented on the response for GetJoinedGroupsForMemberV3 and other Group API endpoints.

**Comment by nine13tech** [comment]
To answer the second question from @floatingatoll - I have not seen the approval date.

However, if the clan join date is before the Groups changeover in September of last year, the dates will have been rest to the go-live date of the new Bungie frontend. So please keep that in mind when you see 20 of your clan members all having the same date as the founder and it's 2 years less than the clan age.
