### ISSUE TITLE
Activity History Truncated

### ISSUE THREAD

**Issue by bladefist** [Bungie-net/api#52]
Hitting this url `https://www.bungie.net/Platform/Destiny2/1/Account/4611686018430034191/Character/2305843009260584043/Stats/Activities/?mode=5&count=100&page=0`

This guy according to the AllTime stats has played 18 games. As you can see in the url, I'm asking for mode 5, all pvp, but I'm not getting all 18 games.

**Comment by vthornheart-bng** [comment]
Hmm, also interesting to note here is that if you change the count to a smaller value - say, 5 - you get back 3 responses on page 0, 3 on page 1, 2 on page 2 and 2 on page 3 (and then 0 for subsequent pages).  I'll need to do some investigating, there could be some post-paging filtering happening that's resulting in an undesirable number of results actually being returned.

**Comment by vthornheart-bng** [comment]
Try it out now - I think redaction was playing games with our paging unfortunately.  Now that pretty much every stat-related entity is un-redacted, this is behaving properly again.  However, trials is still redacted until later today, so there will still be some instances of this until that final entity is un-redacted.
