### ISSUE TITLE
[question] howto access fireteams?

### ISSUE THREAD

**Issue by michabbb** [Bungie-net/api#528]
dear api devs,

are there any api calls to access the fireteams i see on the bungie website ?
![08-06-2018-04-10-53](https://user-images.githubusercontent.com/3524595/41162549-860f64d4-6b36-11e8-943b-c452d2a52a31.png)

because all the endpoints in the docu seem to have something todo with clans:

![08-06-2018-04-12-49](https://user-images.githubusercontent.com/3524595/41162654-cb671ee6-6b36-11e8-98f5-b36e2b14d312.png)

thanks a lot !

**Comment by vthornheart-bng** [comment]
Ah, so this is a holdover from the fact that Fireteams were originally going to be a clan only feature, and then were expanded to work beyond clans.

SearchPublicAvailableClanFireteams is the one you'll want to use for getting public Fireteams!  Try that out and let me know if you run into any issues!

**Comment by michabbb** [comment]
@vthornheart-bng thank you so much for this quick reply! does this call show me also the "legacy" teams ?

**Comment by michabbb** [comment]
@vthornheart-bng thanks a lot, good 2 know !

**Comment by michabbb** [comment]
@vthornheart-bng can you please inform the responsible person: as long as i am not able to identify the language the fireteam is speaking, it makes no sense at all to use that for none english speaking players ;-(((
