### ISSUE TITLE
[question] Weeklies Completion Status

### ISSUE THREAD

**Issue by fuzzymath007** [Bungie-net/api#533]
I have been looking through the API documentation to see if it is possible to find out and remind me if I have claimed the weekly nightfall, raid or flashpoint? I can see inventory data for vendors. Does anyone know if this is possible in the API? My other idea was to grab the questItem Hash from Milestones request but I don't know if I can look up a user and link that information.

**Comment by michabbb** [comment]
@fuzzymath007 you can learn a lot from the [DIM](https://github.com/DestinyItemManager/DIM) and its code 😏 if you go to the dim url `/#!/charid-1/d2/progress` you will see a call in the backgrund: [GetProfile](https://bungie-net.github.io/multi/operation_get_Destiny2-GetProfile.html#operation_get_Destiny2-GetProfile) - somewhere in the result you will see [DestinyCharacterProgression](https://bungie-net.github.io/multi/schema_Destiny-Entities-Characters-DestinyCharacterProgressionComponent.html#schema_Destiny-Entities-Characters-DestinyCharacterProgressionComponent) - there you will find a `completed` status.

> .Response.characterProgressions.data[xxxxxxxxxxx].milestones[xxxxxxx].availableQuests["0"].status.completed

and btw, it´s always a good idea to search [existing issues](https://github.com/Bungie-net/api/issues/419) .

**Comment by fuzzymath007** [comment]
@michabbbI did't know about the DIM, that's super useful. I just started to look into the API yesterday after some Clan mates had a request.  Thanks a bunch!
