### ISSUE TITLE
Clan Alliances

### ISSUE THREAD

**Issue by mikewojtkiewicz** [Bungie-net/api#534]
In the GetGroup Response, there is an array object for GroupIds and a enumeration for an allied status. Are these features currently available for clan admins or are they left over objects from D1?

**Comment by nine13tech** [comment]
I believe this to be a holdover from D1. Though it is a feature I would like to see added. My clan is a Dad clan and we have a clan for our kids, an alliance that allowed us to see them in the roster view in game and also as an allied clan on bungie.net would be awesome. *FEATURE REQUEST* @vthornheart-bng will have more info.

That said - I am having my clan founder check for you... when he is done adulting.

**Comment by vthornheart-bng** [comment]
Ah, unfortunately I don't think that Alliances will ever actually make a return.  They had some very awkward edge cases that complicated Group management significantly, and in the end were only used by a handful of people.  Sorry guys!  Indeed, it's an old holdover: but one that I don't think will ever come back.
