### ISSUE TITLE
Add an itemCategory for Exotic Masterwork Catalysts

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#535]
In building features for DIM, I've found the itemCategory system to be very helpful! However, Exotic Masterwork Catalysts (and the Upgrade plug items) only have the "Mods" category, which makes it very difficult to select them apart from other types of mods. It'd be great if they could have their own category.

**Comment by joshhunt** [comment]
Agreed! I found it a bit tricky to figure out what plugs are masterworks, and which type of exotic masterwork plug it is. In the end, I ended up using `itemDef.plug.uiPlugLabel` to differentiate https://github.com/joshhunt/destinySets/pull/124/files#diff-e2d3378f3392b300ef3bf31c55f6374aR266

If there were itemCategory hashes that could be used to identify them, that would help me out a lot!

**Comment by vthornheart-bng** [comment]
Good call.  I'll put that on the list!
