### ISSUE TITLE
Info on what rewards are given when dismantling an item

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#538]
It'd be neat to know what you will get when dismantling an item. For DIM I can imagine using this info to help people find the shaders that dismantle into bright dust, or to calculate how many items they'd have to dismantle to gain a Gunsmith rank.

**Comment by floatingatoll** [comment]
At the very least it would be certainly be really nice to know if an item has a chance of producing glimmer, shards, and/or motes.

**Comment by vthornheart-bng** [comment]
Hmm, I'll have to ask about this one.  Usually we're pretty hesitant to return "reward" data like this... but this seems like a more benign type of reward information.  I'll ask, but I can't promise we'll be allowed to return it.
