### ISSUE TITLE
Destiny2.Profile returning ErrorCode 18 Invalid Parms retrieved via Destiny2.SearchDestinyPlayer

### ISSUE THREAD

**Issue by Tomalaya** [Bungie-net/api#54]
Making the call https://www.bungie.net/Platform/Destiny2/SearchDestinyPlayer/{MembType}/<Gamertag}/

gives back a valid looking response with a membership ID and membership Type.  However, plugging those two values into

https://www.bungie.net/Platform/Destiny2/{MembType}/Profile/{MembID}/

gives back:
{"ErrorCode":18,"ThrottleSeconds":0,"ErrorStatus":"InvalidParameters","Message":"The input parameters were invalid, please enter valid input, and try again.","MessageData":{}}

I tried tacking on "?components=100" but that has zero effect.  How are the parms for the base path invalid if they are returned from the previous call, or am I being dim and missing a step here?

**Comment by vthornheart-bng** [comment]
Can you give an example of a specific URL you're ending up hitting?  for instance:

https://www.bungie.net/Platform/Destiny2/1/Profile/4611686018429306136/?components=100

Is a valid URL for this endpoint, with 1 being the membership type and 4611686018429306136 being a valid Destiny membership ID, and making a request as above succeeds.  To see why you're getting InvalidParameters, I'll have to see the specific URL - that'll be helpful for determining the nature of the problem!

**Comment by Tomalaya** [comment]
Your URL worked for me, and so I re-ran mine and it's working now as well.  I did note that it does fail if I don't have the "?components=XXXX" on the request.  Perhaps that was being dropped in my test rig, though I did try it with cURL on the command line to verify the rig before.  Not sure exactly why, but it's running now.  Thx.

**Comment by vthornheart-bng** [comment]
Hmm, very odd!  Definitely let me know if you run into this again.  If it's some kind of intermittent problem and you happen to snag your "bungled" cookie for the failed request, we can also do a bit more inspecting on our side!
