### ISSUE TITLE
Some weapon perks claim to be isDisplayable: false incorrectly

### ISSUE THREAD

**Issue by designker** [Bungie-net/api#540]
The new IKELOS_HC_v1.0.1 handcannon 'itemHash: 3866356643' claims it has precision perk with a hash of '2362086930'. It claim to be 'visible: false' and the definition says it is 'isDisplayable: false'. However it very much should be shown. Other items that have the correct info such as the Antiope-D 'itemHash: 566976653' have a precision perk with a different hash of '4040885430' which is isDisplayable. I am not sure if there are others

**Comment by vthornheart-bng** [comment]
Ah, interesting!  I'll have to give it a peek, thank you!

**Comment by designker** [comment]
I now think this was just a misunderstanding on my behalf and am closing this
