### ISSUE TITLE
Warmind engram vendor doubles all rewards

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#542]
Each item in the "Warmind Engram" (vendor 3780056901) is doubled - there's two of each item. This doesn't happen for other engrams.

![screen shot 2018-06-23 at 6 13 26 pm](https://user-images.githubusercontent.com/313208/41814937-27f1cbb2-7711-11e8-884f-a5ba80d51e56.png)

**Comment by vthornheart-bng** [comment]
Hmm, interesting!  What do you see in the game?  Just out of curiosity!

**Comment by bhollis** [comment]
Hmm, weirdly when I turn in rep for Ana Bray, I get "Cradle Engrams", not "Warmind Engrams"

**Comment by ArkahnX** [comment]
Warmind engrams I believe you get as a chance from opening data nodes. I tried to get an ingame screenshot, but I didnt get any this week

**Comment by bhollis** [comment]
In that case there are two bugs - one is that Ana's rewardItem is this warmind engram instead of whatever she actually gives out in the game.
