### ISSUE TITLE
Characters disappearing from the bungie API

### ISSUE THREAD

**Issue by migit128** [Bungie-net/api#547]
Not sure what is going on here tbh.  I cache data on everyone in my clan so I can run reports off of their bungie API data without having to wait 30 minutes to pull all the info out of the API.  One of the things I cache is their characters and I keep a running list of their active and deleted characters.

These guys have characters that were previously in the API, but no longer are.  They are not being reported as deleted or active.. They've just vanished.

nanook:
Bungie
member id 4611686018471667688
chars:2305843009359504187,2305843009359504188

TheRedBoy:
Bungie
member id: 4611686018476091047
chars:2305843009359044025

Logs for nanook (Pacific time):
2018-06-28 20:10:50,680; [1]; INFO; - BungieUsers.updateMembers: plat data in db nanOOk. Checking if it needs updating!
2018-06-28 20:10:50,680; [1]; INFO; - BungieUsers.checkUpdatePlat: LastPlayedDate changed from 6/28/2018 5:30:34 PM to 6/29/2018 2:35:09 AM
2018-06-28 20:10:50,696; [1]; INFO; - BungieUsers.checkUpdatePlat: Updated memberId=4611686018471667688
**2018-06-28 20:10:50,696; [1]; INFO; - BungieUsers.updateCharDbData: Found a new character Adding 2305843009359504187
2018-06-28 20:10:50,852; [1]; INFO; - BungieUsers.updateCharDbData: Found a new character Adding 2305843009359504188**

Now if you go to the bungie API and check on his current list of characters, those two are no longer there.

http://destinydevs.github.io/BungieNetPlatform/docs/API-Test#/Destiny2/GetHistoricalStatsForAccount/p:membershipType=4,destinyMembershipId=4611686018471667688/q:groups=84

I put the group as 84 (invalid) so it only returns character info without all the stats.

This is nanook's output:

```
{
    "Response": {
        "mergedDeletedCharacters": {
            "results": {
                "allPvE": {},
                "allPvP": {}
            },
            "merged": {}
        },
        "mergedAllCharacters": {
            "results": {
                "allPvE": {},
                "allPvP": {}
            },
            "merged": {}
        },
        "characters": [
            {
                "characterId": "2305843009359874371",
                "deleted": false,
                "results": {
                    "allPvP": {},
                    "allPvE": {}
                },
                "merged": {}
            },
            {
                "characterId": "2305843009310294278",
                "deleted": false,
                "results": {
                    "allPvP": {},
                    "allPvE": {}
                },
                "merged": {}
            },
            {
                "characterId": "2305843009309947079",
                "deleted": true,
                "results": {
                    "allPvP": {},
                    "allPvE": {}
                },
                "merged": {}
            },
            {
                "characterId": "2305843009309947080",
                "deleted": true,
                "results": {
                    "allPvP": {},
                    "allPvE": {}
                },
                "merged": {}
            },
            {
                "characterId": "2305843009311426065",
                "deleted": true,
                "results": {
                    "allPvP": {},
                    "allPvE": {}
                },
                "merged": {}
            }
        ]
    },
    "ErrorCode": 1,
    "ThrottleSeconds": 0,
    "ErrorStatus": "Success",
    "Message": "Ok",
    "MessageData": {}
}
```

**Comment by vthornheart-bng** [comment]
Hmm, it looks to me like he deleted and re-created new characters.  I am not in the office so I don't have a chance to dig in too deep right now, but check out his profile page:

https://www.bungie.net/en/Profile/4/4611686018471667688/nanOOk

He's got two characters there that look to be brand-spanking new: level 1, light level 100.  My bet is that he (or someone with access to his account) deleted two characters and created two new ones.  The GetProfile API can only return information about the characters you already have: it doesn't have any historical information about characters that you may have previously had.  Through the Stats API you can get this sort of info basically by coincidence: because at the time that data was saved, the character still existed.  But if you hit any endpoints that are looking for "current" data, it will be as if they never existed.

Hit up this person and ask if they did delete and create new characters recently!

**Comment by vthornheart-bng** [comment]
And with the historical stats, we may have to do some more digging there.  I'm curious as to whether these characters actually had performed any activities.  For example, did he create the characters and do nothing with them, and then delete and re-create them?  If so, they might have appeared in GetProfile calls in the interim while not having historical stats data yet.  But we'll have to do some investigating.  If you get the chance, hit up this person and ask him if he's been finagling with his characters lately.

**Comment by migit128** [comment]
That's what I suspected as well so I asked him about it this morning.  Here's the conversation:

https://i.imgur.com/TWkvPYN.png

You'll probably need to look at it from your side to see what really happened.

To me though, it seems like regardless of if there is activity on a character, if they delete a character the bungie API should display that character as deleted.  I changed my code to mark characters in this situation as deleted, but if it turns out they aren't and they randomly come back, my stuff is going to break again. :(

**Comment by floatingatoll** [comment]
Have you previously encountered characters disappearing and then reappearing within a given platform-account, other than in an outage scenario where no characters are present at all?

**Comment by vthornheart-bng** [comment]
I went ahead and dug through some logs, and the only record of this character's existence was when they created it, and then a few hours later deleted it without actually doing anything with the character.

Created June 28th at 19:32 UTC, deleted June 29th at 9:42 UTC!  And at least as far as the logs and our databases are concerned, nothing else ever happened with that character.

These are the only entries in our system that acknowledge the existence of these characters: your system will have to handle the fact that, if someone does this, they can delete their character without a trace!  If they never actually play an activity, the only thing that could theoretically keep data about the character (the Historical Stats system) will never have recorded anything: which means that, for all intents and purposes, that character has been totally purged.

If you ever see a character in that state, you should probably just drop them from your data too: it means that the player basically did nothing with it aside from creating them and deleting them.

**Comment by vthornheart-bng** [comment]
That was for the one ending in 187.  The one ending in 188 was similar: created June 28th @ 19:34 UTC, deleted June 29th @ 9:42 UTC, never having done anything aside from being created.

**Comment by vthornheart-bng** [comment]
Same thing for 2305843009359044025:

Created June 27th @7:41 UTC
Deleted June 28th @18:24 UTC

Never having done anything other than be created and subsequently deleted.

**Comment by migit128** [comment]
Thanks! @vthornheart-bng 

@floatingatoll - My clan system is PC only (except for my ps4 alt) so it'd be extremely unlikely I'd find something on any other platform.  My stuff has been running for months and this is the first time I encountered this.  I just find it extremely strange that I found 3 instances of it within the past few days.

**Comment by vthornheart-bng** [comment]
No prob, glad we got to the bottom of it!  I'll go ahead and close this out for now.
