### ISSUE TITLE
Preview shader endpoint

### ISSUE THREAD

**Issue by floatingatoll** [Bungie-net/api#551]
Hi, is there a one-parameter endpoint somewhere that would allow us to select a shader and, via the API, activate the Preview Shader feature using that shader on whatever item we’re viewing in-game at the time?

This is a long shot, but it would be really cool, so I thought I’d ask.

**Comment by ckhicks** [comment]
Tracking this one closely: I assume you want to pass it the hash for an item with the hash for a shader, ya? Would it return an image or WebGL? I know Destiny Tracker had this working at one point back in D1...

**Comment by floatingatoll** [comment]
Nope, I just want to pass it a hash for a shader, and have that activate the “Preview” shader action _in-game_ for whatever item I am currently previewing, so that I can see in-game on my TV what that shader looks like. No WebGL, no item hash, just “Preview this shader in-game if an item is being inspected”.

**Comment by vthornheart-bng** [comment]
Unfortunately we wouldn't be able to do that with the current architecture of the game and servers.  Previewing is a client-authoritative action, and we don't have any pipeline by which the API can initiate client authoritative actions via the server on a given client.

**Comment by floatingatoll** [comment]
Thanks for taking the time to reply!

On Sun, Jul 29, 2018 at 8:50 AM, Vendal Thornheart <notifications@github.com
