### ISSUE TITLE
Missing ActivityModeDefinition for "In Orbit"

### ISSUE THREAD

**Issue by lowlines** [Bungie-net/api#552]
As the title states, it looks like there is no definition in the manifest for currentActivityModeHash "2166136261" which gets returned from GetProfile[204] when the currentActivityHash is 82913930 (or in orbit).

Also with activity definition, it doesn't have a display name so to return the localised text for when someone is in orbit, you need to grab it off the place definition, which notably has "Orbit" as the name and "In orbit" as the description. Could this be possibly fed through to the activityDefinition to cut back on required calls and/or hard coding checks to display information on this activity?

**Comment by vthornheart-bng** [comment]
Hmm, I'll have to look into this - IIRC, 2166136261 is the "invalid hash" which means that there is no current activity.  But indeed, from what I recall you should technically be "in an activity" even if you're in orbit.  That may have changed, however.

I'll have to look into this: that may also be the reason why it doesn't have a display name.  You may be looking at an activity that was meant to be the "in orbit" activity but it was scrapped, and the activity itself left in.  I won't know for sure until I dig into the data.

**Comment by vthornheart-bng** [comment]
This is intended apparently.  When you're in orbit, you are not in an activity.  There is an "orbit" activity, but as far as I can tell it is going unused.

**Comment by ckhicks** [comment]
Iiiiiinteresting. For checking to see if someone is in orbit, then, is the best strategy to use timestamps and an empty activity value? Does the game ever stop tracking what a player is doing (ala kicking you to orbit when in a social space) or could one remain in that "activity" indefinitely?

**Comment by vthornheart-bng** [comment]
If there were no other bugs I would say that, except that there's another bug (#910) that, if it is indeed happening, means that you may also see an empty activity value when playing Last Wish (or some part(s) of Last Wish?).

I know that the game *can* kick you to orbit in certain situations, so that's definitely something that can happen.  I don't think you can safely rely on being able to be in an activity indefinitely, though I don't know the rules for which you can be kicked out, or if it applies universally.

**Comment by floatingatoll** [comment]
Destinystatus does seem to calculate the time-in-orbit statistic that way,
as seen at e.g. https://destinystatus.com/psn/floatingatoll — almost a
quarter of my gameplay time is in orbit (I've done no more than 4 hours of
raids in D2)

**Comment by floatingatoll** [comment]
Though. Does "waiting for matchmaking" count as Activity: invalidHash or
Activity: whateverIAmMatchmakingForHash? Presumably the former, so keep
that in mind.
