### ISSUE TITLE
Possibly Bugged Objective Progress on Vendor Items

### ISSUE THREAD

**Issue by lowlines** [Bungie-net/api#553]
So I've been working on a live tracker app that does a diff on data returned from the APIs and I noticed today that the objective "Region Chests Opened" (2861058986) on the Hellas Basic Emblem (1210937132) seems to flicker periodically between 1 and 6. Maybe it is somehow mixing with the Titan Emblem, which has 6 region chests?

**Comment by lowlines** [comment]
Actually I'm also seeing bugged behaviour with the Braytech RWP MK.II (73837075) "Enemies Defeated" stat where it seems to copy the value of the currently equipped Masterworked energy weapon both in the API and in-game.

I've noted that the Mars Emblem bug happens when travelling to and from orbit.

**Comment by lowlines** [comment]
Just discovered another quirk with the Exotic Catalyst sold by Faction Vendors. It appears to ghost the "Enemies Defeated" data of the currently equipped Masterwork weapon. It's possible this is due to the fact that the objective (73837075) is listed on its definition ie (Graviton Lance Catalyst 615063266).

**Comment by lowlines** [comment]
I think I've figured out what is going on with the Hellas Basin emblem. It is constantly flicking between the progress of each of my characters. Both my Titan and Hunter have opened 6 Region Chests however my Warlock has only opened 1. This is something you can test in-game, all instances of the emblem, including what is displayed in the vendor screen will only show the lowest "Region Chests Opened" stat. Whenever you start an activity, it seems to try and recalculate this value before settling on 1 again.

**Comment by lowlines** [comment]
Created some videos demonstrating these quirks happening in-game.

Hellas Basin emblem bug.
https://twitter.com/lowlines/status/1016211917742866432

BrayTech RWP Mk. II bug.
https://twitter.com/lowlines/status/1016226781911646209

**Comment by vthornheart-bng** [comment]
I have a fix that I've proposed which should eliminate these character state inconsistencies - I believe we're going to see it go live with the Forsaken release!  So this one's coming, it's just going to be a bit longer of a wait.
