### ISSUE TITLE
Feature Request: Add more customisability to GetProfile

### ISSUE THREAD

**Issue by lowlines** [Bungie-net/api#554]
I'm currently working on a live tracking project that uses the GetProfile endpoint quite heavily and I based on that, I think it'd be useful to have more options to filter out stuff you don't actually need when requesting a large number of components.

Below is a list of components I am currently looking at:
```javascript
var components = [
	//100, // Profiles
	102, // ProfileInventories
	103, // ProfileCurrencies
	104, // ProfileProgression
	200, // Characters
	201, // CharacterInventories
	202, // CharacterProgressions
	204, // CharacterActivities
	205, // CharacterEquipment

	300, // ItemInstances
	301, // ItemObjectives
	//304 // ItemStats
	305, // ItemSockets

	500, // Kiosks
];
```
Here are things that I currently want to know about:

- Changes to the inventory (adding/removing/quantity)
- Changes to currencies
- Changes to the current activity
- Changes to objectives on instanced items (ie Enemies Defeated on masterwork items, and progression on Exotic Catalysts)
- Changes to tracker emblems (requires a separate call to GetVendors to get ones not in your inventory)
- Changes to progression info (ie checklists, profile/character progressions like XP)

It would be good if there was a way to cut out extra component data I won't use but gets returned as a result of combining multiple components into one call. Like instead of returning all the socket info on item instances, I only need the ones with objectives on them. Another thing, would be to be able to specify other vendorHashes as add on kiosks to return progression info on ornaments/unlockables that don't exist in a player's inventory. Again, I'd only be interested in those which have actual objectives on them, but I'll end up requesting a lot more data with GetVendors than I'll likely need.

Would it be possible to return the time in which each set of data was updated on the server? Through discussions with other's, I'm told there is a 30s or so delay with most updates however when you add the fact that API calls will likely be out of sync, that refresh time could be like double that. It'd be good to have timestamps much like the dateActivityStarted on CharacterActivities[204] so one could order changes based on when the server updated rather than when the client app polled the APIs.

Another neat thing to have would be to add the info of the last PGCR each character did added to the CharacterActivities[204] component, but like just an overview so that I could skip polling PGCRs unless there is a new one.

Also, when you inspect another player in your roster, currently playing a match, it shows the current score and number of players. Is it possible to return info like this to CharacterActivities[204] for the current activity? If it were possible to return the character info (or at least the profile which you could use to poll GetProfile[204]) of each player in the activity as well that'd be really useful.

**Comment by vthornheart-bng** [comment]
Hmm, so there's a few issues rolled into this single issue.

For returning just a subset of component data: unfortunately, I don't have any plans to do that presently.  The components-based approach to responses were meant to be a compromise between providing less data from the endpoint and still having the benefits of a reasonable subset of output caching options.  This would be more in the direction of a GraphQL-style query language for our API, which we're not in a position to support anytime in the near future.

For the time that the data was last refreshed: that sounds fantastic, I'm all for that!

For the Last PGCR played: unfortunately doing this would make fetch queries a lot more expensive than they are currently, I'd be hesitant to do this with our current infrastructure.  But I'd like to keep this in mind in case future releases come with a better way for us to get at this data internally.

For inspection-style data, I'm not certain if we can get at that - but I think that'd be worth investigating!

I think it'd be worth us splitting this up into multiple Github issues.  The first one I don't picture us providing anytime soon, but the latter ones I'd like to keep track of for future improvements!

**Comment by vthornheart-bng** [comment]
Split the other ones into:

https://github.com/Bungie-net/api/issues/582

https://github.com/Bungie-net/api/issues/581

https://github.com/Bungie-net/api/issues/580

I'll close this one for now and we can track those with the more specific issues!

Thanks Lowlines, good suggestions all around as usual!
