### ISSUE TITLE
Revoking an application does not immediately expire tokens

### ISSUE THREAD

**Issue by lowlines** [Bungie-net/api#555]
So I'm running some tests on my authorization code at the moment and I discovered that even though I've revoked access for my app from the user settings on bungie.net, I seem to still be able to make calls to GetProfile and am returning data with privacy: 2.

**Comment by Tetron-bng** [comment]
This is expected.  Revocation can take as long as an hour to take effect.  The check for revocation is performed up renewal of the access token. This is a compromise to increase performance and scale. It means the authorization service is not in the loop for every query and is therefore not able to check for revocation until the application tries to replace its expired access token.
