### ISSUE TITLE
Day of Seven Emblem is Classified

### ISSUE THREAD

**Issue by Jakosaur** [Bungie-net/api#556]
Day of Seven Emblem is Classified. This is the emblem currently available on the Bungie Store

[https://db.destinytracker.com/d2/en/items/4132147347 ](https://db.destinytracker.com/d2/en/items/4132147347)

![image](https://user-images.githubusercontent.com/20144356/42521914-cf6ead3a-8461-11e8-8ef0-e7e0c557c50c.png)

**Comment by vthornheart-bng** [comment]
Ah, good call!  I'll see about getting that unredacted the next time we release.
