### ISSUE TITLE
Featured Crucible playlist data

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#560]
Humbly requesting an addition to the call to arms milestone to get featured activities i.e. mayhem active, doubles?

**Comment by vthornheart-bng** [comment]
Hmm, good call - I don't know when I can get around to it unfortunately, but I agree that's a good idea!  Let's keep this on the radar.

**Comment by mistahj67** [comment]
Bump. Would be awesome to be able to get at the Weekly Crucible activity hash or mode perhaps through the milestone endpoint.

**Comment by kramrm** [comment]
This info would be helpful to be able to lookup.

**Comment by vthornheart-bng** [comment]
Sweet, this is good info that many people want this - thank you!  Apparently the last time I looked at this was before I was making TFS bugs for enhancement requests, so let me go ahead and fix this one up by adding a TFS item to our backlog for it!

**Comment by vthornheart-bng** [comment]
TFS 768149

**Comment by justrealmilk** [comment]
I just searched issues to see if a thread existed and it’s... my own 😂
