### ISSUE TITLE
Manifest endpoint returning previous manifest file info

### ISSUE THREAD

**Issue by serkanbal** [Bungie-net/api#562]
The manifest endpoint `https://www.bungie.net/Platform/Destiny2/Manifest/`is not always returning the latest manifest file info.

Sometimes it returns the latest manifest file's info; which is, for instance `/common/destiny2_content/sqlite/en/world_sql_content_48164c159ffdbbc8ab80387793477fd7.content` for `Response.mobileWorldContentPaths.en` property and sometimes an older manifest file's info which is `/common/destiny2_content/sqlite/en/world_sql_content_644ccfb36daeede8aef48d0f23e2d9e9.content` for the same property.

This causes issues since most of the apps check for the current manifest file at launch.

**Comment by joshhunt** [comment]
I've observed this as well.

**Comment by floatingatoll** [comment]
What is the defined behavior for the "version":"64883.18.05.29.1341-14"
property in the manifest — should it be treated as opaque, or should it be
evaluated as a six-segment version string and compared numerically for
"this manifest update is newer"?

**Comment by TorKallon** [comment]
I'm not sure what it's supposed to do, but that version string sometimes doesn't change when the manifest updates. I've been using changes to the filename to decide when the manifest has changed and needs to be redownloaded.

**Comment by vthornheart-bng** [comment]
Did this just start happening to you all today/last night?  If so, I think I know what's up.  We had an error in our deployment, where some of our servers didn't actually get the latest version of both our code and our content.  That should be fixed now however!  Let me know if you're still getting that.

**Comment by serkanbal** [comment]
It started last night, right after the deployment. I think the issue you mentioned is probably the reason. It has been happening for around 12 hours; but did not see that in last 1 - 2 hours or so.

And a (partially) related subject: Some of the screenshot urls for items in the latest manifest file is broken. Just a heads up. An example: BrayTech Winter Wolf (itemHash: 1752585070)

**Comment by vthornheart-bng** [comment]
Sweet - yeah, let me know if it ends up creeping up again, but indeed this should hopefully be the last time this occurs.

For the screenshots... I will have to take a look into that when I get some time, it's possible that some items got unredacted or added and we didn't generate screenshots for them.

**Comment by joshhunt** [comment]
@vthornheart-bng All screenshots are 404-ing at the moment, including those that weren't previously redacted and available. I'm unsure if this has been since Thursday, but I'm not seeing any screenshots across the board.

**Comment by vthornheart-bng** [comment]
Yeah, I haven't had a chance to look into it until just now, but indeed this looks to be an undetected casualty of our new deployment system.  I'm informing our ops folks now, and I'll see if I can get the screenshots re-deployed separately.

**Comment by vthornheart-bng** [comment]
Okay, those screenshots should be live again in about half an hour or so, barring possible delays from our CDN getting the updates properly.  Thanks for reporting this guys!
