### ISSUE TITLE
Yesterdays update broke state property for exotic masterwork weapons

### ISSUE THREAD

**Issue by designker** [Bungie-net/api#563]
I think yesterdays deployment broke exotic weapon masterworks. If you are working on the catalyst it has a state of 4 and if fully upgraded to a masterwork it has a state of zero. The opposite of how item states should behave

**Comment by vthornheart-bng** [comment]
Yep, my bad!  I just did some looking into it, as we were seeing this internally - I fixed it, but in a branch of our content that didn't end up shipping live!  Whoops!

I'm getting the proper fix integrated up now so that it'll be fixed for our next deployment on the 24th.

**Comment by designker** [comment]
I'm closing this as you fixed it
