### ISSUE TITLE
GameVersion attribute appears to be bugged.  API claims 444 out of 446 people in my clans bought the new expansion pass.

### ISSUE THREAD

**Issue by migit128** [Bungie-net/api#564]
The API is telling me Nytur#11475 has bought the expansions, but he has not.  TheMlgCat#1556 also said he did not buy it yet, but the API says he did.  I checked my database and it claims 444 out of 446 people in my clans have bought the expansion pass. 

```
I believe it's hitting this method: /Destiny2/{membershipType}/Profile/{destinyMembershipId}/?components=100
{{
  "Response": {
    "profile": {
      "data": {
        "userInfo": {
          "membershipType": 4,
          "membershipId": "4611686018467948914",
          "displayName": "Nytur"
        },
        "dateLastPlayed": "2018-07-13T21:22:46Z",
        "versionsOwned": 7,
        "characterIds": [
          "2305843009313844971",
          "2305843009319944564",
          "2305843009343285128"
        ]
      },
      "privacy": 1
    },
    "itemComponents": {}
  },
  "ErrorCode": 1,
  "ThrottleSeconds": 0,
  "ErrorStatus": "Success",
  "Message": "Ok",
  "MessageData": {}
}}
```

The two outliers are Vultagee#1994 of whom it says he's got warmind and Paragon#12206 who only has the base game (says he's got the base game so we're good here).

**Comment by migit128** [comment]
I asked on the destiny API discord and someone mentioned you guys use bitwise indicators for things in other places (help doc here: https://github.com/Bungie-net/api/wiki/FAQ:-Flags-Enumerations,-how-do-they-work%3F )

7 would be a 1 for the base game and both of the current DLC's so this make sense.

Once you confirm this I'll update my code.

**Comment by vthornheart-bng** [comment]
Yeah, indeed that's the case!

**Comment by vthornheart-bng** [comment]
I'll close it out for now - let me know if anything else comes up!

**Comment by migit128** [comment]
thanks!
