### ISSUE TITLE
DestinyItemSocketCategoryDefinition references itself

### ISSUE THREAD

**Issue by sgtfrankieboy** [Bungie-net/api#57]
It seems there is an issue with the `DestinyItemSocketCategoryDefinition` class. 

The `socketCategoryHash` property references to itself instead of the actual `DestinySocketCategoryDefinition` in the manifest file. (for which the class is absent from the docs)

**Comment by vthornheart-bng** [comment]
Ah, good catch!  I'll have this fixed up for the next time I generate the swagger docs.
