### ISSUE TITLE
Vendor info provided by API is incorrect

### ISSUE THREAD

**Issue by melange396** [Bungie-net/api#570]
The items available at (at least some) vendors shown in 3rd party applications differ from what is shown in-game.  Both DIM and the official Destiny companion app suffer from this, so I am assuming that the problem lies in the data being served by the API.
![benedict](https://user-images.githubusercontent.com/110998/42964419-f1bab276-8b64-11e8-92ef-196345896868.png)
![banshee](https://user-images.githubusercontent.com/110998/42964420-f1d359fc-8b64-11e8-975a-0c1492888ebb.png)

**Comment by floatingatoll** [comment]
Excluding Gunsmith armor and weapon mods, which other vendors and/or which other items have you identified as affected?

**Comment by vthornheart-bng** [comment]
Okay, getting more info now - it sounds like it's not just restricted to these two vendors.  I'm going to go in and take a closer look.

A solution that should hopefully resolve this issue on a more permanent basis will be coming with Forsaken, but given that it's more than just these vendors I'm going to see if there's anything that can be done in the interim!

**Comment by vthornheart-bng** [comment]
Okay, we should have a hotfix for this on tuesday.  Thanks for your patience with this - hopefully come Forsaken, we'll have some more significant changes on our backend that will make us more resiliant to these types of sync-up failures once more.
