### ISSUE TITLE
Ship Blueprint Name and Description uses Placeholders

### ISSUE THREAD

**Issue by SunburnedGoose** [Bungie-net/api#574]
The name and description of the classified WotW Ship Blueprint quest is using placeholder.  Is this expected?  

![image](https://user-images.githubusercontent.com/984608/43219913-457a91b2-900e-11e8-9dbd-b0486cfa1317.png)

**Comment by vthornheart-bng** [comment]
Oh!  Well that's me fucking up the replacement string for that item when we redacted it.

Let me double check on it - with this deployment we *should* be unredacting it, but let me verify if that is the case.

**Comment by vthornheart-bng** [comment]
Yes, hang tight - it looks like it will be unredacted once this deployment finishes.

**Comment by SunburnedGoose** [comment]
It is unredacted, but going forward, this shouldn't be an issue for classified quest?

**Comment by vthornheart-bng** [comment]
I'm pretty sure I just screwed it up on my end - but I'll keep this in mind the next time we have to redact a quest, so I can do some additional testing!
