### ISSUE TITLE
Error returned from GetMembershipsFromCurrentUser endpoint

### ISSUE THREAD

**Issue by Rking788** [Bungie-net/api#58]
When attempting to hit the GetMembershipsFromCurrentUser endpoint, I'm getting the following response.

```
{
    "ErrorCode": 99,
    "ThrottleSeconds": 0,
    "ErrorStatus": "WebAuthRequired",
    "Message": "Please sign-in to continue.",
    "MessageData": {}
}
```

I am passing the a valid `X-API-Key` header as well as a newly requested access_token in the `Authorization` header. I seem to get the same response if the Authorization header is left off completely.

**Comment by floatingatoll** [comment]
Do other authenticated API endpoints work for you, or are they all broken in this same manner?

**Comment by Rking788** [comment]
ya so if i make a call to the GetMembershipsById endpoint and provide a membership type and the membership ID returned from the tokens endpoint, that request succeeds and i can load membership data.

The problem is my server isn't storing tokens directly (and i'd like to keep it that way) they are handed to me when a request comes in, so that means i'm also not storing the membership ID from the tokens response. I would like a way to get profile data from only the access token.

**Comment by AllynH** [comment]
Hi guys, 
I can confirm that other authenticated endpoints are working but I'm seeing the same issue as described here. GetMembershipsFromCurrentUser is returning WebAuthRequired.

**Comment by Rking788** [comment]
problem solved. I needed to change `https://bungie.net/` to `https://www.bungie.net/` and that fixed the problem. it seems like the redirection that occurs will remove the Authorization header. Probably related to things going on in this issue: https://github.com/Bungie-net/api/issues/55

**Comment by vthornheart-bng** [comment]
Ahhh, sneaky.  Hmm... well I'm glad it's working now!  That's definitely an FAQ-worthy addition - thank you for reporting back about it!

**Comment by AllynH** [comment]
@vthornheart-bng 
Cn you please update the wiki: https://bungie-net.github.io/multi/index.html#about-connecting
Connecting to the API -> Server Endpoint -> API Root Path:
https://bungie.net/Platform
to
https://www.bungie.net/Platform

As this may catch some other people out.

**Comment by vthornheart-bng** [comment]
Good call for sure!
