### ISSUE TITLE
Resplendant Masterwork objectives not returning proper data

### ISSUE THREAD

**Issue by vthornheart-bng** [Bungie-net/api#588]
I was looking into some info about masterwork objectives for the new armor, and stumbled into the fact that we're almost certainly not returning objective data correctly for these specific items.  Adding a task here so I can remember to loop back to this and investigate further.

**Comment by vthornheart-bng** [comment]
I'll try to get a fix for this in our next deployment - but that'll be shortly before Forsaken.  My apologies to those who wanted to use this data.

**Comment by ckhicks** [comment]
Your diligence and detective work is much appreciated!
