### ISSUE TITLE
DISCUSS: Location for Developers to chat/find collaborators/etc?

### ISSUE THREAD

**Issue by vthornheart-bng** [Bungie-net/api#59]
I think we need somewhere other than the Issues section for developers to chat, find collaborators for projects, make announcements, etc... they're good tasks to be done, but I don't want it to clutter up the Issues section (which feels like it's important to keep restricted to issues directly relating to the API itself rather than work being done around the API)

Any suggestions for where people would like to see that live?  I'm open minded on the subject, I've not really thought about it before now.  My gut is perhaps a publicly editable wiki page if Github allows it, but I'm not sure if there's a better solution that wouldn't take too much effort or red tape (perhaps even just a link to some external location hosted by folks in the community who want to see such a location exist?)

**Comment by floatingatoll** [comment]
At some level, this seems to already be the purpose of BungieDev forum at Bungie.net. GitHub isn’t an effective place for a forum, so if the minimum bar is “just a list of projects”, excellent, but otherwise you’ll likely need a forum.

**Comment by vthornheart-bng** [comment]
Yeah, I dig that.  Perhaps that can be the new purpose of the BungieNetPlatform forum.  I'd gladly link back to it here and re-christen its purpose to be the "Looking for Collaborators/announcements group" for projects.  Unless anyone has any better suggestions, let's go with that.

**Comment by sgtfrankieboy** [comment]
One of the possibilities would be to use the Discord that is setup at discord.gg/WJDSUgj. it already has a self promotion channel in which people can ask for contributors. I can also create an extra one specific to it if need be.

I do think that the forums are also a good option for help/contribution requests if people need them.

**Comment by vthornheart-bng** [comment]
Ooh, yeah I dig that even more I think.  I really am not the biggest fan of our forums, and Discord definitely has immediate feedback advantages.

**Comment by floatingatoll** [comment]
Discord is a fine ‘forum’ too.

**Comment by vthornheart-bng** [comment]
^_^

**Comment by vthornheart-bng** [comment]
Cool, added to FAQ.  If anyone else posts here with things not directly related to the API, I'll direct them there.  Thanks guys!
