### ISSUE TITLE
This error says to tell you about it... so I am!

### ISSUE THREAD

**Issue by Akumati1435** [Bungie-net/api#590]
A guy named Relentless#11461 joined my discord.  It triggered my scripts to try and get information on him from the bungie API.

`2018-07-31 02:10:38,798; [1]; INFO; - No mapping found for user.  running regex filters then checking the API for Relentless#11461`
`2018-07-31 02:10:38,798; [1]; INFO; - Destiny2_V1.SearchDestinyPlayers: URL=https://www.bungie.net/platform/Destiny2/SearchDestinyPlayer/4/Relentless%2311461/`
`2018-07-31 02:10:38,882; [1]; INFO; - Destiny2_V1.GetStats: URL=https://www.bungie.net/platform/Destiny2/4/Account/4611686018476342482/Stats?groups=85`
`2018-07-31 02:10:39,256; [1]; ERROR; - APIErrorChecker.CheckErrorCode:Got an unhandled non-successful result from the bungie API.`
`2018-07-31 02:10:39,272; [1]; INFO; - Errored out getting Raid info. 
BungieAPI threw an error.
{"ErrorCode":1601,"ThrottleSeconds":0,"ErrorStatus":"DestinyAccountNotFound","Message":"We were unable to find your Destiny account information.  If you have a valid Destiny Account, let us know.","MessageData":{}}`
`2018-07-31 02:10:39,272; [1]; INFO; - Destiny2_V1.GetStats: URL=https://www.bungie.net/platform/Destiny2/4/Account/4611686018476342482/Stats`
`2018-07-31 02:10:39,569; [1]; ERROR; - APIErrorChecker.CheckErrorCode:Got an unhandled non-successful result from the bungie API.`
`2018-07-31 02:10:39,584; [1]; INFO; - Errored out getting PVP info.  Have they even PVP'ed? check destinytracker.com 
BungieAPI threw an error.
{"ErrorCode":1601,"ThrottleSeconds":0,"ErrorStatus":"DestinyAccountNotFound","Message":"We were unable to find your Destiny account information.  If you have a valid Destiny Account, let us know.","MessageData":{}}`

I tried searching for him on bungie.net and it errors out. 

https://www.bungie.net/en/Profile/4/4611686018476342482 

We've encountered an error, please try again later.

**Comment by EdgarVerona** [comment]
Ah, thank you for letting us know!  Interesting - I'll have to take a look!  So I take it that SearchDestinyPlayers gave you 4611686018476342482 back as a result?  When was the last time they played with that account - and can they get to their own profile page?  Have them try to go to https://www.bungie.net/en/Profile/4/4611686018476342482 while logged in.

**Comment by vthornheart-bng** [comment]
Ah, thank you for letting us know! Interesting - I'll have to take a look! So I take it that SearchDestinyPlayers gave you 4611686018476342482 back as a result? When was the last time they played with that account - and can they get to their own profile page? Have them try to go to https://www.bungie.net/en/Profile/4/4611686018476342482 while logged in.

**Comment by migit128** [comment]
I just sent the guy a message.  We'll see if he response.  He isn't in my clan, so he probably doesnt know who I am.

**Comment by migit128** [comment]
He set his discord server nickname as his overwatch account, so you'd think SearchDestinyPlayers wouldn't come up with anything.  I assumed it was a real account because it redirected me to a profile when searching for the battletag on bungie.net.
