### ISSUE TITLE
Trirang Tox has a blank screenshot

### ISSUE THREAD

**Issue by floatingatoll** [Bungie-net/api#594]
As seen at DestinySets, it's the usual item preview background without a ship shown.

**Comment by vthornheart-bng** [comment]
Hmm, I'll have to check on that - thanks for the info!

**Comment by joshhunt** [comment]
@vthornheart-bng [it was reported to me](https://github.com/Bungie-net/api/issues/594) that a few more weapons have blank screenshots:

 - Basilisk 2928437919
 - Vacuna SR4 1159252500
 - Magnum Shepherd 210065223

**Comment by vthornheart-bng** [comment]
Ah, good find, thank you!

**Comment by vthornheart-bng** [comment]
This is going to be finally fixed in the deployment today - I'm re-generating these 4 screenshots as we speak.

**Comment by vthornheart-bng** [comment]
Deploying now, should be live in just a few minutes!
