### ISSUE TITLE
GetActivityHistory lacks parameter defaults

### ISSUE THREAD

**Issue by xKairu** [Bungie-net/api#60]
Following on from my comment on #47 

When using GetActivityHistory, you *must* specify all three count, mode and page parameters.

Yesterday I was getting a response that was as if the user had their data set to private (same as #47), but revisiting it today, I'm getting error 19 ParameterNotFound. Defaults would be a nice QoL addition.

Working:
`https://www.bungie.net/Platform/Destiny2/2/Account/4611686018452182455/Character/2305843009260713968/Stats/Activities?count=10&mode=0&page=1`

Not working:
`https://www.bungie.net/Platform/Destiny2/2/Account/4611686018452182455/Character/2305843009260713968/Stats/Activities`

**Comment by vthornheart-bng** [comment]
Sounds good to me!  Thanks!

**Comment by Tetron-bng** [comment]
Actually, that endpoint does have defaults. count=25, page=0, and mode=0.  I get the same results for the following:
https://www.bungie.net/Platform/Destiny2/2/Account/4611686018452182455/Character/2305843009260713968/Stats/Activities/
https://www.bungie.net/Platform/Destiny2/2/Account/4611686018452182455/Character/2305843009260713968/Stats/Activities/?mode=0&page=0&count=25
