### ISSUE TITLE
"dismanteled & unlocked in forsaken checklist" 

### ISSUE THREAD

**Issue by nathabba** [Bungie-net/api#601]
why is Destiny sets telling me that items i dismantled back in season 1 are unlocked for forsaken checklist?..

**Comment by ckhicks** [comment]
There's a good read here that might shed a little light: https://github.com/Bungie-net/api/issues/559#issuecomment-408543307

**Comment by vthornheart-bng** [comment]
I'm going to go ahead and close this one for now - let me know if that info explains the situation suitably to you @nathabba!
