### ISSUE TITLE
Is there an endpoint for joining a fireteam?

### ISSUE THREAD

**Issue by kirkhoff** [Bungie-net/api#602]
Looking at the available Fireteam endpoints, this is what I see:
![image](https://user-images.githubusercontent.com/1478680/44277240-0c0ea000-a218-11e8-8cff-dacec08cec44.png)

Is there an endpoint for joining a fireteam with a `fireteamId` retrieved from `Fireteam.SearchPublicAvailableClanFireteams`?

**Comment by vthornheart-bng** [comment]
Greetings!  Unfortunately, we don't have one that's publicly available at this time.  Sorry about that!
