### ISSUE TITLE
Unable to see which boons a character has applied. 

### ISSUE THREAD

**Issue by SunburnedGoose** [Bungie-net/api#603]
I would like to be able to see when a player has any buffs applied to their character. Some of these include, 

Rested XP Buff
Three of Coins
Vanguard and Crucible Boons
Eververse Boons
Dawning Boons
4 Hour XP Buff
...

Having knowledge of what buffs the player has applied to their character will help me avoid redundancy when suggesting buffs based on activities they are playing and what's available in their consumables.

**Comment by floatingatoll** [comment]
I believe this is a dupe of #308.

**Comment by SunburnedGoose** [comment]
I knew I asked it before @vthornheart-bng.

**Comment by vthornheart-bng** [comment]
Ah, you were right!  I forgot!
