### ISSUE TITLE
https://bungie.net/Platform causes a redirect that is missing the auth bearer

### ISSUE THREAD

**Issue by designker** [Bungie-net/api#61]
The docs recommend https://bungie.net/Platform as the server endpoint https://bungie-net.github.io/multi/index.html

However currently this causes a redirect to www.bungie.com that has the api key but not the bearer header so you only can use public end points.

You can make the system work by using 'https://www.bungie.net/Platform' as the baseUrl of the end point.

**Comment by vthornheart-bng** [comment]
Good call - definitely!

**Comment by Tetron-bng** [comment]
Doc has been updated.
