### ISSUE TITLE
Question on "sales" from DestinyVendorItemDefinition in 2.3.0/1

### ISSUE THREAD

**Issue by ckhicks** [Bungie-net/api#610]
Love all the new info in the wiki - this has become one of my favorite parts of the expansion release cycle. :)

Question regarding `redirectToSaleIndexes` via `DestinyVendorItemDefinition`: What would an in-game use case be for this property? Is this sort of a way for a Vendor to say, "sorry you can't get that item anymore, but here's one you should consider" or another interaction entirely? I was trying to visualize the use case here but am blanking/missing the purpose.

As always, THANK YOU @vthornheart-bng for all your work here! 👏Super excited to dig in more.

**Comment by vthornheart-bng** [comment]
So the current use case is Prismatic Matrix, but I imagine it could be used for other things as well.  So when you purchase a prismatic matrix item, it redirects randomly to one of the other sale items in this list that passes whatever validation is on that sale item.

No problem, glad to be of help!  Thank you for always giving good input and info around here!

**Comment by ckhicks** [comment]
Ah, that makes perfect sense. Thanks! Exciting to think about other ways that could be used...
