### ISSUE TITLE
VersionsOwned in GetProfile hasnt updated to forsaken game versions yet

### ISSUE THREAD

**Issue by migit128** [Bungie-net/api#615]
I expected the VersionsOwned to show me who's bought forsaken after today's patch.  Is that coming next week?  I was hoping to have my discord bot send automated notices to my clan members that haven't bought the game yet.   One of our rules is that you own the most recent expansion to stay in the clan.  When will I be able to do this?

**Comment by vthornheart-bng** [comment]
Ah, that'll be coming by next week - and by "that'll be coming next week," I mean "I'm glad you mentioned that, because I neglected to add it and am doing so now." :)

**Comment by vthornheart-bng** [comment]
Fortunately this was a quick enough fix, will be in for 9/4

**Comment by migit128** [comment]
Thanks 😂
