### ISSUE TITLE
Same Emblem secondaryIcon

### ISSUE THREAD

**Issue by Jakosaur** [Bungie-net/api#616]
[Sign of the Gambit](https://data.destinysets.com/i/InventoryItem:2133500861) has the same secondaryIcon as [Answered Call](https://data.destinysets.com/i/InventoryItem:2133500860)

**Comment by vthornheart-bng** [comment]
Let's give it until 2.3.1 before we call this a bug - there was a ton of items, including this one, that were left in content and I believe were still half-baked.  Make a note and loop back around if you still see this as a problem after the release on 9/4!
