### ISSUE TITLE
Tier variable for Last Wish raids is all 0s in the DestinyActivityDefinition manifest.

### ISSUE THREAD

**Issue by migit128** [Bungie-net/api#617]
There are 6 Last Wish entries in the manifest but they all have the same light level and tier variable.  One of them has a guided games section so it's obvious what that one is, but as of now it seems impossible to tell which hashes are normals and which are prestiges.  Was this on purpose?   

Hashes - 
1661734046 - Guided games
2122313384 - ?
2477825419 - ?
2477825420 - ?
2477825421 - ?
2477825422 - ?
2477825423 - ?

**Comment by vthornheart-bng** [comment]
Ah, what you are actually seeing is cruft - junk that was left in game content, and that doesn't actually reflect what's going to come through in 9/4.  These ought to have been redacted or removed from content, but weren't - however most of them are gone as of 9/4.  Hold tight, and let's loop back on this when the real Forsaken content goes live next week.

**Comment by migit128** [comment]
thanks!
