### ISSUE TITLE
Combat bows do not have an itemCategory or itemSubType

### ISSUE THREAD

**Issue by ArkahnX** [Bungie-net/api#618]
As per title. I'm assuming this will be patched in on Sep 4th, but just wanted to bring it up incase!

Trinity Ghoul: 814876685, Wish-ender: 814876684

And I'm guessing the legendary bows are classified at the moment

**Comment by vthornheart-bng** [comment]
Aye - Bows and their related plug items will have item categories up and ready to go on 9/4!
