### ISSUE TITLE
(Some?) Items with Kinetic Damage have damageTypes but empty damageTypeHashes

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#622]
e.g. Midnight Coup 1128225405 https://data.destinysets.com/i/InventoryItem:1128225405 looks like this 

```
damageTypeHashes: [],
damageTypes: [1]
```

**Comment by vthornheart-bng** [comment]
Ah, good info, thank you!  I'll need to do some investigating.

**Comment by vthornheart-bng** [comment]
TFS 706844

**Comment by vthornheart-bng** [comment]
Fixed!  The Github side of this slipped through my fingers, but this should be resolved as of 9/18.
