### ISSUE TITLE
Feature request: collectableHash on items

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#624]
Currently If I want to show the sourceText for any given Collectable item, I have to either recurse through presentation nodes (or just each loop over every Collectable entry), to find all Collectables and then key them by item hash or something like that.

It would handy if, given an itemHash, we could easily find the corresponding Collectable entry. This could be done through adding an optional collectableHash on item definitions.

**Comment by vthornheart-bng** [comment]
Ah, you know - I remember actually thinking the same thing a month ago or so, but I never did it!  I'm totally down for that.

**Comment by vthornheart-bng** [comment]
Okay, this was an easy enough fix, I just added it to the September 18th deployment.
