### ISSUE TITLE
Error Code 3 on specific PGCR

### ISSUE THREAD

**Issue by mattybeard** [Bungie-net/api#625]
Unhandled Exception according to docs - and no one likes them!

PGCR 2095593129

**Comment by mattybeard** [comment]
Looks related to 619 actually. I’ll close this one and leave that one running. Apologies for not reading.

**Comment by vthornheart-bng** [comment]
No worries, it's all good!  (speaking of which, I imagine it's hard for people to see what's already been filed at this point... I really need to clean up the Issues backlog.  I imagine there's a lot of items in there that have either been subsequently fixed and I didn't mark them here, or they're so far down the backlog that I ought to consider them to be effectively tabled.)
