### ISSUE TITLE
Unable to map Daily Heroic Story Mission Activitiy to specific mission

### ISSUE THREAD

**Issue by ttgmpsn** [Bungie-net/api#628]
The Daily Heroic Story Missions can be found by looking at the output of 204 (CharacterActivities) component. However, I'm unable to map the returned activityHash (for todays heroic daily Six, 1602328239) to the actual mission name. While the DestinyActivityDefinition Manifest returns stuff like the destinationHash and placeHash, I didn't find any way to map it back to the mission name Six (except for booting up the game and looking which of the Daily Stories takes place in the Arcadian Valley today).

Sorry if this is something that's about to change with the API update next Tuesday :)

**Comment by lowlines** [comment]
This is the same for Nightfalls as well where the displayProperties are set to the playlist values. The selection UI does contain all the activity specific details however it's obviously referenced differently due to how it's been set up.

**Comment by vthornheart-bng** [comment]
Ah yeah, this has plagued us historically in D1 as well.  In-game, they don't need this relationship - but in the API we do.  I'll have to look into it, there might not be much we can do that won't require some fragile manual configuration, but perhaps there's something that can be done.

**Comment by vthornheart-bng** [comment]
Oh, yes indeed - the fix I proposed for #666 applies here, you'll get some better data come the 18th.  Take a look over there for more info!
