### ISSUE TITLE
Daily Crucible Challenge missing from Milestones when Weekly Flashpoint is completed

### ISSUE THREAD

**Issue by lax20attack** [Bungie-net/api#629]
Character #1 does not have the daily crucible challenge returning in Milestones:
https://www.bungie.net/Platform/Destiny2/1/Profile/4611686018429660408/Character/2305843009261349838/?components=202

Character #2 does have the daily crucible challenge returning in Milestones:
https://www.bungie.net/Platform/Destiny2/1/Profile/4611686018429660408/Character/2305843009268730261/?components=202

Neither character has completed the Milestone, and it is visible in game.

Only correlation I can find is that character 1 DID complete the Flashpoint this week. I spot checked another few accounts and they appear to have the same issue.

Thanks

**Comment by vthornheart-bng** [comment]
TFS 706908

**Comment by vthornheart-bng** [comment]
There was a bug that I thought was unrelated, but turned out to be related to this issue: I think it should be coming through well for you now, give it another shot and let me know!
