### ISSUE TITLE
RSS feed self/next links are broken

### ISSUE THREAD

**Issue by floatingatoll** [Bungie-net/api#63]
https://www.bungie.net/en/rss/News?currentpage=1&category=Destiny

The self/next links (just below webmaster@bungie.net) do not match the request URL, discarding category in one case and providing the wrong category in another.

**Comment by vthornheart-bng** [comment]
Hmm, when I go over there I see:

Self:
https://www.bungie.net/en/rss/News?currentpage=1&category=Destiny

Next:
http://www.bungie.net/en/rss/News?currentPage=2&amp;itemsPerPage=10&amp;category=Destiny

It looks like our next link appends the (I believe, deprecated) itemsPerPage param, but the categories appear to still be correct.

**Comment by floatingatoll** [comment]
Oh. &. I missed a backslash. Sorry. :(

**Comment by vthornheart-bng** [comment]
No worries, it's all good!

(to tell you the truth, I forgot we had an RSS feed... I wrote that so long ago, I'm surprised it's still pointing at valid URLs after all of the redesigns we've done on the site... yay for backcompat-friendly links)

**Comment by floatingatoll** [comment]
Is the RSS feed just https://www.bungie.net/platform/Trending/Categories/
converted into RSS instead of JSON?
