### ISSUE TITLE
Attempting to get Vendor Inventory returns "Temporarily Down for Maintenance"

### ISSUE THREAD

**Issue by hskrasek** [Bungie-net/api#630]
Currently going through all of my integrations with all of the Forsaken changes, and I keep getting the following response when I try to get a vendor's inventory, specifically Xurs:

```
array:5 [
  "ErrorCode" => 5
  "ThrottleSeconds" => 0
  "ErrorStatus" => "SystemDisabled"
  "Message" => "This system is temporarily disabled for maintenance."
  "MessageData" => []
]
```

Nothing has changed in my code, and my access tokens seem to be valid. The last time this happened the fix was to login to all characters on my account and I'd be good to go. Unfortunately that didn't seem to help me this time around.

Not sure if there is a bug, or I missed the note about this being disabled until the next reset.

**Comment by michabbb** [comment]
i guess when it says "This system is temporarily disabled for maintenance" - it really is 😏

**Comment by hskrasek** [comment]
@michabbb well I have to ask because last time it had the same message, but wasn’t actually down for maintenance. 

So is this a for real down for maintenance, or a fake down for maintenance

**Comment by michabbb** [comment]
these are hard times right now, so many changes, if **i** see things like that right now, i guess, i will wait till forsaken is live, because - just my personal thinking - the api guys are working right now, and even it´s a bug or not, everything is getting better the next days.... so we´ll have to wait anyway for some things..... but let´s see what @vthornheart-bng might say 😏

**Comment by ArkahnX** [comment]
In the breaking changes portion of [this wiki article](https://github.com/Bungie-net/api/wiki/2.3.0-and-2.3.1-Changes-(Forsaken-Release)#breaking-changes) it states: **"Vendors will be turned off until 9/4, when the new infrastructure supporting Vendors comes online"**

**Comment by hskrasek** [comment]
@ArkahnX, that’ll be it then. I missed that completely. Didn’t stick out so I just skimmed right over it.

Thanks for the help.
