### ISSUE TITLE
Leviathan challenge

### ISSUE THREAD

**Issue by rentalhost** [Bungie-net/api#631]
Milestones are not displaying the Leviathan challenge anymore. Is it expected? How we can get the week challenge via API now?

**Comment by ArkahnX** [comment]
I think as this milestone no longer shows up in the milestone page in game, and it's not available as an "activity challenge" in game, but give these issues a try, maybe one of them will help. I'd say this is a child issue of #432 if not a duplicate.

See also #473 and #567

**Comment by rentalhost** [comment]
It could be valid for Milestones API, but in this case, we need another method to get this info. Maybe an "activities API" that could returns all available daily activities with perks, challenges, so on.

**Comment by vthornheart-bng** [comment]
There's no challenge anymore, but in the milestones API you should be able to get a "fake" API for the Leviathan raid: it includes the current modifiers and the phases/order of phases (though there's a bug related to completion being tracked elsewhere).  There's no challenge to complete anymore, but you should still be able to get at that info through the Milestones API.

In the long term, I'd like to start including this kind of data on the activities themselves that we return in the GetProfile API, but I don't know when we'll be able to get to that.  For now, take a look through those Milestones and let me know if that provides the data you're looking for.

**Comment by rentalhost** [comment]
After update Milestones API is not returning this info anymore. I still can retrieve the week rotation, but is not possible identify the challenge that is important too.

**Comment by vthornheart-bng** [comment]
Hmm - I think there may be something important I'm missing out on.  As far as I understood, Leviathan doesn't actually have a challenge associated with it anymore.

I just went and double checked in the data - and indeed, there aren't challenges anymore for the old Raids.  Sorry about that - I can't show the challenge if the challenge no longer exists.  It was removed from the game, which means we can't even make a "fake" challenge: whatever was being used to track it is also gone, so there's nothing left to map to.

Unless potentially we're talking about two different things - you're talking challenges as in objectives tracked on an activity that you complete for rewards?  If we're talking that, there's unfortunately none of them left to return to you.

**Comment by rentalhost** [comment]
I could capture this info before by checking the "objectiveHash" array from old Milestone API. If it contains some specific ID from a challenge, it works.

https://pastebin.com/bazyaFtH

The old "objectiveHash" was an array containing some objects that I have used to identify the rotation and the week challenge. Currently I do something similar, but I am able just identify the rotation. I have checked the manifest content to identify new possible IDs related to challenge, but no success.

**Comment by vthornheart-bng** [comment]
Ohhh, I see - yeah, back when the weekly objectives were a more explicitly defined thing.  Hmm... I'll have to take a look, but unfortunately if they moved it from being something explicitly defined as an objective to only something defined in scripted content, we won't have any human readable data to key off of anymore (and wouldn't have that data unless the concept gets revived... maybe for the new Raid there'll be something similar?  But I get the feeling they won't do it for the old Raids if they do end up with a similar concept for the new one)

**Comment by vthornheart-bng** [comment]
TFS 706974 to investigate - but I've got to forewarn you that I think it's very unlikely that this data still exists in any explicitly defined/content-defined form.  If it is, I will be pleasantly surprised!  My hopes are unfortunately low for it though given what I've seen of the content and milestone-related changes.

**Comment by vthornheart-bng** [comment]
Okay, so I see some data that look like they might be what you're looking for, but they lack any sort of human readable data.  I can attempt to return this data, but what I can't give is whatever localized strings they may have once returned (if any?) for them: that data, if it ever existed, doesn't appear to exist anymore.  What I could give is that raw data - basically hash identifiers for the challenges, and whether they are enabled or not - but you'd have to relate those to whatever you want to show users manually unfortunately.

**Comment by vthornheart-bng** [comment]
If you want that, I filed a bug TFS: 708279 to look into returning it.

**Comment by rentalhost** [comment]
@vthornheart-bng I did this manual relation by hash before and it worked fine (based on Manifest database). Just make it available again and it will solve my issue. 😄 Thanks for attention!

**Comment by vthornheart-bng** [comment]
Ahhh, sweet!  In that case, good stuff!  I'll see what can be done.

**Comment by vthornheart-bng** [comment]
The phase fixes are slated to be released October 2nd, though I welcome any and all bugs you can give.  I'm giving what I perceive in the data to be phases, but if there's additional steps you feel ought to be there or steps that don't seem right, let me know and I can do some more digging.

The Last Wish raid's weekly completion status will also start being returned on that date in Milestones.

For the names, on that same release date you should start seeing the more specific information for each variant returned in the displayProperties.name property on the activity definition.  That should be helpful for discerning between them, though you can also use things like the activityLightLevel property as well if you want something more programmatically useful!

**Comment by vthornheart-bng** [comment]
Whoops, I just realized as I was reviewing our TFS items - my fix was for the broken _phases_ data, which also needed to be fixed, but it didn't include challenges.  I'll see about getting the challenges fix in too though, I'm taking a look presently.

**Comment by vthornheart-bng** [comment]
Okay, that is *also* going to come in October 2nd!
