### ISSUE TITLE
Gambit stats using mode=63 returning UnhandledException.

### ISSUE THREAD

**Issue by t3rr11** [Bungie-net/api#633]
So usually to request recent activities i use the endpoint: 
https://www.bungie.net/Platform/Destiny2/4/Account/{member_id}/Character/{character_id}/Stats/Activities/?count=100&mode=4

That will retrieve that last 100 raids done for that character. Working as intended. 

Well when you try and request gambit stats the same way using the mode=63 endpoint: 
https://www.bungie.net/Platform/Destiny2/4/Account/{member_id}/Character/{character_id}/Stats/Activities/?count=100&mode=63

It returns errorcode 3, UnhandledException. 

The work around is to use mode=0 and then filter through pulling all the activities that have a mode of 63. Works fine, but wasn't aware if you knew about this bug.

Also Gambit PGCR's return no data for the Teams[] node either. So i am having to pull the team data from each entities player values. 

I understand you guys are working really hard on the API but i just thought i'd try and help with bug finding. Hoping everything is going alright for forsaken and can't wait to play the new DLC soon!

Thanks Terrii.

**Comment by delphiactual** [comment]
From https://github.com/Bungie-net/api/wiki/2.3.0-and-2.3.1-Changes-(Forsaken-Release)#breaking-changes:
Gambit stats will not be returned during the pre-9/4 Gambit Trial.

**Comment by t3rr11** [comment]
I had a feeling that was the case, though it was returning an UnhandledException, So i thought it would be best to report it here, just incase! :D

**Comment by lax20attack** [comment]
Gambit stats were returned via the "All" mode type, but filtering on Gambit type was returning an error as this issue states

**Comment by t3rr11** [comment]
Alright so since gambit has now been released, I've tried again to return mode=63 stats for gambit. Still getting UnhandledException. Starting to think now i might have been onto something rather than it being a once off for the trial day.

**Comment by vthornheart-bng** [comment]
Hmm, interesting - thanks for the heads up!  I'll give it a look.

**Comment by vthornheart-bng** [comment]
TFS 706842

**Comment by vthornheart-bng** [comment]
Yeah, this is a legit problem for sure.  Glad you followed up on it - I'm seeing what I can do now.  Will try to get a fix for our patch deployment next week.

**Comment by vthornheart-bng** [comment]
Okay, so in our internal environment I have fixed this particular stats issue - I'll try to see it put forth in the 9/12 update.

There is a separate issue affecting stats, tracked in #638, that may end up affecting you as well (depending on if you get aggregate stats or not).  Activity History will be working on 9/12, but aggregate stats for Gambit may require change in a deeper system and I don't have an ETA for it yet.

**Comment by floatingatoll** [comment]
Not intended, but known issue - see #638 and a couple comments up here.

**Comment by xgerhard** [comment]
@vthornheart-bng Thanks for adding Gambit specific stats, really cool! One small thing I noticed when getting historical stats with `modes 63` - gambit, is that the Gambit exclusive medals are included in the `general` group instead of `medals`.

To reproduce, request historicalstats with `modes=63&groups=Medals`, you'll see a nearly empty response.

**Comment by vthornheart-bng** [comment]
TFS 712574
