### ISSUE TITLE
Legendary/Rare Energy/Power with Kinetic Damage Type

### ISSUE THREAD

**Issue by duckmanBR** [Bungie-net/api#637]
Legendary/Rare Energy/Power weapons are returning as having kinetic damage.
Exotic/Uncommon are ok.

Don't know if this affect only Y1 weapons.

**Comment by vthornheart-bng** [comment]
TFS 706844

**Comment by vthornheart-bng** [comment]
Let me defer this into #622

**Comment by vthornheart-bng** [comment]
Hey @duckmanBR, can you send me some examples of items you're seeing that are returning the wrong damage type?  I've been spot checking some legendaries and they're looking correct so far.  But I'm not sure if perhaps this is happening just to some subset of items that I didn't happen to hit in my attempts so far.

**Comment by vthornheart-bng** [comment]
Ah, right after that I think I found one - Curtain Call, legendary rocket launcher.

If you have any others, feel free to send a few examples my way!

**Comment by ArkahnX** [comment]
Just based on my current inventory, heres some hashes 3906942101, 2707464805, 1327432221, 3445437901, 4288031461,  3954531357, 1723472487

disclaimer, these are based on DIM not showing elements for these weapons. It looks like its all of the raid weapons from Y1, as well as a few weapons that have custom elements

**Comment by floatingatoll** [comment]
Does the official companion app show elements for these weapons?

**Comment by vthornheart-bng** [comment]
Nay, from my testing it looks like we're returning the wrong type for these as well.  I think I've hit on the root cause of this, working out a fix presently.

There will be a new property on sockets, isVisible, that you can/should use to check whether we'll show the plug in the UI.  This is being differentiated from the existing isEnabled property, as some sockets (such as these old items' damage type sockets) are set to invisible but are still providing benefits on the item (such as setting the item's damage type).

**Comment by ArkahnX** [comment]
`bindStatus:0
bucketHash:2465295065
dismantlePermission:2
itemHash:3906942101
itemInstanceId:"6917529059256777010"
location:1
lockable:true
quantity:1
state:1
transferStatus:0`

`"damageType": 1,
"damageTypeHash": 3373582085,
"primaryStat": {
	"statHash": 1480404414,
	"value": 380,
	"maximumValue": 0
},
"itemLevel": 38,
"quality": 0,
"isEquipped": false,
"canEquip": true,
"equipRequiredLevel": 28,
"unlockHashesRequiredToEquip": [
	2166136261
],
"cannotEquipReason": 0`

Looks like it comes through as kinetic damage

**Comment by vthornheart-bng** [comment]
This isn't going to make the boat for the 9/12 release though, as our UI also needs to have time to be changed to look for/use this new field before we release.  I'm going to target this fix for 9/18.

**Comment by vthornheart-bng** [comment]
Okay, checked in for the 9/18 hotfix deployment.  Thanks guys!
