### ISSUE TITLE
Need a Forsaken flag in DestinyGameVersions

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#641]
I can guess what it'll be but it'd be nice to have it defined :-)

**Comment by vthornheart-bng** [comment]
Ah, shoot - I forgot that the swagger spec I generated for 2.3.1 was before our discussion about DestinyGameVersions.  Indeed, it should be there as Forsaken = 8, but I'll need to regenerate the swagger spec and docs for you to see it.

**Comment by vthornheart-bng** [comment]
TFS 706837 to remind me once this initial wave of more important bugs are worked on
