### ISSUE TITLE
Some new items have no power level in the API

### ISSUE THREAD

**Issue by designker** [Bungie-net/api#645]
For example the following bow itemHash: 720351794 has no primaryStat in the api to get its power level

**Comment by vthornheart-bng** [comment]
Just to check before I dig in - as in you're not getting power level in live data, or in definitions?  Or both?

Do you have an example of someone you're hitting who has this bow and is in this state?

**Comment by vthornheart-bng** [comment]
TFS 706833

**Comment by designker** [comment]
It is live data as you can increase the power level through infusion. Everyone with this bow has the issue

**Comment by designker** [comment]
Do you need more? This is the first bow the game gives you so you have the item within an hour of playing Forsaken

**Comment by designker** [comment]
OH I am a moron. Ishtar only bug

**Comment by vthornheart-bng** [comment]
Ah, no worries, it's all good!
