### ISSUE TITLE
Forsaken Checklist Updates

### ISSUE THREAD

**Issue by lowlines** [Bungie-net/api#646]
Just make a formal request for seeing the checklists get updated to include new Forsaken content.

- Adventures
- Lost Sectors
- Region Chests

There also appears to be a new Sleeper Node / Latent Memory / Lore collectible that while I understand the desire to keep a secret, should have a roadmap for eventually adding support for these knowing players will want this when they start checking off things to do in the DLC.

**Comment by vthornheart-bng** [comment]
Agreed - I definitely need to add the first three.  I'll have to ask about when we're allowed to show the latter.

**Comment by vthornheart-bng** [comment]
TFS 706830

**Comment by lowlines** [comment]
I reckon some of this info can be pulled from Records, I just haven't sat down to investigate yet.

**Comment by lowlines** [comment]
Linking up Adventures and I've spotted some bugs.

https://data.destinysets.com/i/Checklist:4178338182

- Adventure[16] 1613294042 is pointing to a Survey Mission
- It looks like the bubbleHash is also not being properly set for adventures ie Io Adventures are 577912749 Excavation Site II, which appears to be an issue with the locationRelease data.

**Comment by vthornheart-bng** [comment]
Good find on that adventure!  I'm fixing that up now while I add the new adventures/lost sectors/etc...

Those other two are interesting, in that the Solstice of Heroes' achievement considered them to be Adventures for completion purposes.  I am, admittedly, not sure why.  But I put them in there so that the checklist would match what was being looked for in-game.  Now that Solstice is over, I wouldn't feel bad removing those... but let me hit up some folks internally just in case.

**Comment by vthornheart-bng** [comment]
Will go through on the release for the 18th!

**Comment by lowlines** [comment]
It appears that there is no locationRelease data for this Lost Sector in the Tangled Shore.
![destiny 2_20180908105854](https://user-images.githubusercontent.com/4862548/45253410-d89ddc00-b3a5-11e8-9d16-f4298359f20c.png)

**Comment by lowlines** [comment]
For comparison here's my maps with debug mode enabled. All the other region chests line up with a locationRelease (the red dots). https://lowlidev.com.au/destiny/maps/tangled-shore?debug

![destiny2_maps_missing_chest](https://user-images.githubusercontent.com/4862548/45253464-9f19a080-b3a6-11e8-9bba-81ccf1998374.png)

**Comment by vthornheart-bng** [comment]
It's the most lost lost sector. :) ha  I'll ask about it.

**Comment by vthornheart-bng** [comment]
Where are you getting the info for that chest from?  Does it actually exist if you go there?

**Comment by soren42** [comment]
![image](https://user-images.githubusercontent.com/326903/45260390-b2cc0380-b3b4-11e8-869b-d9c7c0e10d8f.png)
![image](https://user-images.githubusercontent.com/326903/45260393-bb243e80-b3b4-11e8-9a97-e9d6e4e8a2cd.png)
Indeed it does.

**Comment by vthornheart-bng** [comment]
Ah, interesting!  Thanks, good info!

**Comment by lowlines** [comment]
I think I understand why that Region Chest was missed. There's no bubble setting info for the High Plains!

**Comment by vthornheart-bng** [comment]
I sent a message over to folks on the game side.  Unsure if you're going to be provided this data, I think the jury's still out.  I'd say go ahead and do your own override for now.  If they do decide to include this data, it probably wouldn't be until a later build and would require game-side content changes, so we're looking at a long period before it makes its way into production (and thus into our content).

**Comment by lowlines** [comment]
Looks like Lost Sectors in the Dreaming City are missing from the checklists data.

- Bay of Drowned Wishes [1291818945]
- Chamber of Starlight [1149052883]
- Aphelion's Rest [373809891]

Pretty much everything linked up automatically with the manifest update. All that's missing from checklists is linking up useful Triumphs/Records like the lore collectibles, though that component pretty much does the job already so I suppose it isn't needed.

**Comment by vthornheart-bng** [comment]
TFS 712654, ready for release on october 2nd.

**Comment by lowlines** [comment]
So now that the Wish Ender is obtainable in game and folks have discovered it can destroy Corrupted Eggs around the Dreaming City, can we get a checklist made for them? I'm going to hold off collecting these on my account as these will likely be Sleeper Nodes / Latent Memories all over again and there's the added fact some of these are locked inside weekly rituals that in some cases, have a 6 week rotation.

Another thing I think that is worth investigating are the Cat Statues as I have reason to believe they are also tracked to your account and reward you with an emblem when you do them all.
