### ISSUE TITLE
sourceString hash for collectibles

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#649]
It would be _extremely_ helpful if collectibles with sourceString also had a complimentary sourceString hash that could be used to group Collectibles together. Alternately, having a presentationNode for each sourceString would be helpful, but I understand if this isnt used in-game then this might not be possible.

This, more or less, blocks me from using Collectibles in a helpful way on Destiny Sets, as I have no stable way to address a set of items from the same source.

**Comment by marquesinijatinha** [comment]
I would have a good use for this for the same reasons @joshhunt  stated.
It would be really useful to have one of these:
a unique hash for source strings or presentation nodes that groups the weapons by source, just like the armor sets are.

**Comment by vthornheart-bng** [comment]
Oh!  Yeah!  Not only do I dig that, but I can also actually provide it pretty easily.  The thought didn't occur to me about how useful that'd be!  I'll see if I can get it in for the 18th while I'm digging around in Collectibles code anyways.

**Comment by vthornheart-bng** [comment]
TFS: 708274

**Comment by vthornheart-bng** [comment]
Just note that it's only going to be as accurate as the consistency of the game designers.  If someone, for example, made two strings for the same conceptual source but that are actually two different strings, the identifiers are going to be different and I'll have no way of knowing that they should be the same.
