### ISSUE TITLE
Triumphs DestinyRecordState...67?

### ISSUE THREAD

**Issue by ckhicks** [Bungie-net/api#653]
I was messing around with some Triumphs data and found a bunch of `state: 67` entries [on my account](https://destinydevs.github.io/BungieNetPlatform/docs/API-Test?code=2e2ccc1be751f3ad37cc46cfebc45e1e#/Destiny2/GetProfile/p:membershipType=1,destinyMembershipId=4611686018435819655/q:components=900).

I looked through [the definitions](https://bungie-net.github.io/multi/schema_Destiny-DestinyRecordState.html#schema_Destiny-DestinyRecordState) and only see `64` as a valid `DestinyRecordState`. Am I missing something?

**Comment by lax20attack** [comment]
You need to bitwise AND these values most likely.

Ex:
```
const state = 77

const collectibleState = {
    None: !!(state & 0),
    NotAcquired: !!(state & 1),
    Obscured: !!(state & 2),
    Invisible: !!(state & 4),
    InventorySpaceUnavailable: !!(state & 16),
    UniquenessViolation: !!(state & 32),
    PurchaseDisabled: !!(state & 64),
}

```

**Comment by vthornheart-bng** [comment]
Aye - indeed this is another Flags Enumeration field, which means you'll have to evaluate it with the kind of bitwise logic that @lax20attack is using!

**Comment by ckhicks** [comment]
Gotcha, thanks much!

**Comment by aescolastico** [comment]
> 

Im not sure I understand the bitwise logic. Im trying to filter triumphs by those that are "NotAcquired" but no matter what value I feed this expression: 
```
!!(state & 1)
```
I get true. Am I missing something? 

I have a state value of 67 for the triumph "Pearl of Glass" and that value returns true for NotAcquired given the logic supplied. But I very much do have this triumph claimed on my test profile.
