### ISSUE TITLE
Vendors (esp. Spider): wrong RefreshDate

### ISSUE THREAD

**Issue by ttgmpsn** [Bungie-net/api#654]
Hey! Vendors, especially the Spider, seem to report a wrong RefreshDate. For example, the Spider (863940356) right now reports it's refresh date as 2018-09-11T17:00:00Z - despite the Bounties changing daily (so next time at 2018-09-08) and materials exchange even changing more often than that!

**Comment by vthornheart-bng** [comment]
Oh, are you talking about the vendor's nextRefreshDate?  Unfortunately, this date doesn't apply to items that are controlling their own refresh timing, like Bounties.

The history of this is that, until very recently (Solstice of Heroes if I recall correctly?), Vendors had their entire inventory controlled by a single refresh date where, if they had the ability to cycle what they sell, it would cycle.  But a feature was added to allow individual items within their inventory to control their own cycling.  nextRefreshDate still returns that overall inventory cycling time, but it has no effect on such self-controlling items, such as bounties and material exchange.

I took a look, and unfortunately I'm not returning those per-item overrides yet.  But I think that would be a very useful thing to return!  I'll look into that.

**Comment by vthornheart-bng** [comment]
Sweet, got it in for 9/18!  Sale Items that have their own "nextRefreshDate" will have "overrideNextRefreshDate" populated in their sale item component.

Note that, as with all refresh dates, it doesn't guarantee that the item won't be picked in the next rotation: just that this is the next time when it will be *possible* for the item to move out of rotation.  The game shows this time as if it's the time when the item will disappear, but they don't mention this caveat.
