### ISSUE TITLE
Junk values in DestinyInventoryItemDefinition.value.itemValue

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#658]
Here's an example: https://data.destinysets.com/i/InventoryItem:1705009261

I see a lot of items that have a bunch of entries in `DestinyInventoryItemDefinition.value.itemValue` that have `itemHash: 0` and `quantity: 0`. I can filter them out easily, but it seems like they shouldn't be in the manifest in the first place.

**Comment by bhollis** [comment]
I don't know if this is the right place to have this discussion, but I've noticed that the manifest generally has a lot of either junk data, or less-than-useful data (for example, a `backgroundColor` value with all zeroes). I mention this mostly because there's an overhead to parsing the JSON, and also because the manifest for D2 is now larger than the D1 manifest - over 61MB uncompressed! Anything we could do to slim that down would really help.

**Comment by ArkahnX** [comment]
What about the ability to acquire parts of the manifest? maybe for instance all you want is DestinyInventoryItemDefinition, but just to get that you also need 23.9MB of additional files since it only comes as one package

**Comment by vthornheart-bng** [comment]
For sure that's something we can do as well - at least with the JSON definitions!
