### ISSUE TITLE
Expiration time for items (bounties)

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#659]
I may be just missing something, but it doesn't seem like there's any information in a bounty's `DestinyItemComponent` about when they will expire. With the introduction of expiring bounties, that'd be really nice to be able to display.

**Comment by vthornheart-bng** [comment]
Sweet, got it in for 9/18!

**Comment by vthornheart-bng** [comment]
It'll be an optional "expirationDate" property on DestinyItemComponent.

**Comment by bhollis** [comment]
You’re the best!

**Comment by lowlines** [comment]
This is going to be super useful to a lot of projects!! ❤️

**Comment by bhollis** [comment]
This works great!

**Comment by vthornheart-bng** [comment]
Sweet, I am glad to hear it!
