### ISSUE TITLE
Supremacy stats not available

### ISSUE THREAD

**Issue by bladefist** [Bungie-net/api#66]
According to the manifest it's mode 40.  But mode 40 is tower.   I can't find any mode for Supremacy.  

Also:  AllPvP > control + countdown + survival.   I think they should be same.

**Comment by vthornheart-bng** [comment]
Hmm, where are you seeing that?  What area of the manifest is referring to Supremacy?

**Comment by bladefist** [comment]
@vthornheart-bng It's not in there. But it's active in-game.  From D1, Supremacy would be mode 40.  But Mode 40 is Tower.  (0 in D1). 

Also, if someone were to download every match played (I would never) they would see supremacy isn't showing up.  It's showing up.  But it appears in `AllPvP` for ActivityStats.

**Comment by v-fedorov** [comment]
Here to confirm, these are the only modes I am seeing

'0'
'2'
'3'
'6'
'10'
'16'
'17'
'37'
'38'
'40'

**Comment by vthornheart-bng** [comment]
Oh - just to clarify, you're saying Destiny 1 has Supremacy active, but it's not defined in Destiny 2 Manifest?  Or is it missing in the Destiny 1 manifest?

**Comment by bladefist** [comment]
@vthornheart-bng I edited my response, I realized I was being super confusing.

**Comment by vthornheart-bng** [comment]
Hmm, hang tight.  I'll ask the stats folks about this.

**Comment by vthornheart-bng** [comment]
Ah, just got the word back, that was quick - there was a miscommunication on my part, this should have been in the API but isn't.  I'll file a bug for us to get it re-added!

**Comment by v-fedorov** [comment]
Also, supremacy and clash matches are being mislabeled as mode 0.
ex: Platform/Destiny2/stats/postgamecarnagereport/66236/

the activityHash is for Javelin-4 with mode being 0

**Comment by vthornheart-bng** [comment]
Probably the same root cause, but I'll investigate that while I'm fixing this issue!

**Comment by vthornheart-bng** [comment]
I'm pretty confident that we've found and are fixing the root cause for this.  It's being triaged and final testing going through as we speak, should be able to deploy later this week if that goes well.
