### ISSUE TITLE
How do I allow my users to sign out of my app authenticated with the Bungie api

### ISSUE THREAD

**Issue by mikewojtkiewicz** [Bungie-net/api#661]
Like the title asks, I need to have the ability to have the users who logged into my application be able to log out if they ever wish to log into a different Bungie account. The authentication happens at the Bungie account level, and not on my app. Is there a way to accomplish this?

**Comment by bhollis** [comment]
Have them visit the "Authorize" page, but add the parameter `reauth=true` to the URL. That'll force the page to present a new login/authorization page.

**Comment by vthornheart-bng** [comment]
Hmm, that's a good tidbit for the wiki - I'm going to close this question here and link it in our how-to.
