### ISSUE TITLE
Year 1 weapons always have kinetic damage type

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#662]
In the API, instance definitions for Year 1 weapons that are in the special and heavy slots report damage type 1 (Kinetic), even though in game they have elemental damage. Their definitions have a defaultDamageType that is generally correct, unless the legacy damage mod is different.

**Comment by ArkahnX** [comment]
Dupe of #622 I believe

**Comment by vthornheart-bng** [comment]
Aye, true.  I should have this fixed up for the 9/18 release!
