### ISSUE TITLE
PGCR Returning Mode 0 

### ISSUE THREAD

**Issue by bladefist** [Bungie-net/api#665]
I played a game this weekend:

Competitive Playlist,  and it was control.

The ID: 2240448373

It's coming up as Mode 0.  

Furthermore, is there a plan to determine between competitive and quickplay control?

**Comment by vthornheart-bng** [comment]
I'll check it out!

There's no timeframe yet to support differentiating between competitive and quickplay for any modes that end up being shared between them, but I'd like to add support for that.  It's on the ever growing backlog.

**Comment by vthornheart-bng** [comment]
Ah, I took a look - it looks like we had some configuration issues on our side preventing these from being returned properly.  They will be fixed with the 9/12 deployment, and will fix retroactively!

**Comment by bladefist** [comment]
@vthornheart-bng thanks, I see this is live.  

Is there any plans to put Control-Competitive on it's own mode instead of 10?

**Comment by vthornheart-bng** [comment]
Ah, good question - I just went digging, as I'd made myself a task to put in our backlog to loop back to adding that.  It got buried toward the bottom of the priority queue, I'm going to see about giving it a bump so we can do it sometime in October.  Seems like a reasonable thing a lot of people would want to be able to use.

**Comment by bladefist** [comment]
@vthornheart-bng thanks. Absolutely. The competitive crowd wants to see that data kept broken out separately.  Thanks for your efforts

**Comment by vthornheart-bng** [comment]
No prob, and definitely good to know!  Thank you!

**Comment by vthornheart-bng** [comment]
The mode has been added, but we should track having it as its own mode separately.
