### ISSUE TITLE
Nightfalls' (et al) manifest displayProperties.name is just "Nightfall"

### ISSUE THREAD

**Issue by VeraxonHD** [Bungie-net/api#666]
When using the manifest to get the name of a Nightfall, the `[hash].displayProperties.name` is just simply "Nightfall" which isn't very useful! Unless I'm missing a patch note, can we get this fixed please? Else, the only way to find the nightfall name is comparing the description!
Thanks.

**Comment by ArkahnX** [comment]
This matches in game, as the nightfall is called "nightfall" with the description providing details of which strike

**Comment by VeraxonHD** [comment]
So, there's no way of finding the actual name of the nightfall anymore? That's highly irritating.

**Comment by ArkahnX** [comment]
For reference @vthornheart-bng this weeks nightfall milestone hash is 2853331463 with activities 3108813009, 936308438, 3145298904

In the director, the selected activity shows up as 

```
Strike
NIGHTFALL
Prison of Elders
```
However there is a "difficulty selector" UI button that provides options to the three different nightfalls, and shows them by name and power

```
WARDEN OF NOTHING 540
A GARDEN WORLD 540
THE ARMS DEALER 540
```

In the API, there is none of these strikes at 540 power, by name at least. only strikes at 500 (1360385767), 400 (1360385764), and 300 (1360385765) which matches how the new strike playlist works

So it looks like the reference between the name and nightfall exists, but hopefully its not scripted and unable to bring to light

**Comment by vthornheart-bng** [comment]
Indeed, that's a question that I have to do more digging into.  I've never seen those strings that the game is showing in the content that we can access.  I'm going to have to find out where those are and what sort of relationships we might be able to use to trace them back to their Activity definitions.  Whether those exist in a content-driven form vs. a scripted form will most likely be the determinant between whether we'll return them in the API or not.

**Comment by vthornheart-bng** [comment]
Okay, so after taking a closer look at some of these strings, I'm going to return them as their own set of properties so you can choose when and whether to use them.  In some situations, they provide information that's very different from the activity's title: for instance, playlist activities return the required level as a string in the title for these selection screens.  I'll return both to you, and in doing so let you choose the circumstances in which you choose to use one versus the other.

**Comment by vthornheart-bng** [comment]
TFS 708558

**Comment by vthornheart-bng** [comment]
Will come in on 9/18, it was pleasantly accessible in ways that it wasn't in D1!

**Comment by ArkahnX** [comment]
It'd be nice if there was an easy list you could use to see all of the new changes coming in each major expansion so you could have some idea of what the designers changed without having to find out from us!

**Comment by vthornheart-bng** [comment]
Aye, I'd love that as well.  I think it comes down to the communications problem of having hundreds of people working on a single game (and focusing on/thinking about the way their changes affect the game itself rather than whether changes might affect the API), along with the problem that generic content structures can be used in new and novel ways without it being apparent to someone using the data downstream.

**Comment by ArkahnX** [comment]
As is, stuff gets missed in the player facing patch notes. So many moving parts!

**Comment by vthornheart-bng** [comment]
Player facing patch notes won't cover things like "we're changing where we're sourcing strings for activities when they're shown in a selection screen" for example.

**Comment by VeraxonHD** [comment]
Oh shit, nice one @vthornheart-bng you're my favourite, but don't tell the others. Thanks for seeing to this, it was doing my nut 👍

**Comment by vthornheart-bng** [comment]
<3 Glad to be of help!  Sometimes working on the API feels a little like playing whack-a-mole, and unfortunately you guys get screwed when I miss one of said moles. :)  I appreciate your patience and understanding!

**Comment by VeraxonHD** [comment]
No worries, and thanks. I'm just glad this means I can (easily) carry on with my coursework lol

**Comment by vthornheart-bng** [comment]
Okay, one last idea.  How about, if the selection screen's version of the title isn't in the display properties' string already, I will append it to the end of the string with a colon so you don't have to do any appending logic... and then I'll add an "originalDisplayProperties" field as well so you can choose which of the three variants you want to use.

**Comment by floatingatoll** [comment]
Can you show us a single complete example?

**Comment by VeraxonHD** [comment]
> 
> 
> Okay, one last idea. How about, if the selection screen's version of the title isn't in the display properties' string already, I will append it to the end of the string with a colon so you don't have to do any appending logic... and then I'll add an "originalDisplayProperties" field as well so you can choose which of the three variants you want to use.

So, like, `Nightfall: Tree of Probabilities`? As well as the two available separately that could definitely be useful!

**Comment by vthornheart-bng** [comment]
Good call!
