### ISSUE TITLE
Manifest Content for Many Objectives has Empty Datasets

### ISSUE THREAD

**Issue by nine13tech** [Bungie-net/api#675]
In trying to work through a number of records, I have found that we have a large number of name: "" description: "" empty objectives. These appear to only have skeleton data in them.
In taking a look at Get Profile, with the 900 component for Triumphs as called from `https://www.bungie.net/Platform/Destiny2/<platform>/Profile/<membershipId>/?components=900`
with a [truncated] response of:
```json
{
    "Response": {
        "profileRecords": {
            "data": {
                "score": 0,
                "records": {
                    "20431832": {
                        "state": 0,
                        "objectives": [
                            {
                                "objectiveHash": 3138177461,
                                "progress": 1,
                                "completionValue": 1,
                                "complete": true,
                                "visible": true
                            }
                        ]
                    },
```
the record hash returns:
`DestinyRecordDefinition  //  The Inverted Spire  //  Redeemable`
with the objectiveHash:
`DestinyObjectiveDefinition  // 3138177461`
```json
{
    "displayProperties": {
        "description": "",
        "name": "",
        "hasIcon": false
    },
    "unlockValueHash": 0,
    "completionValue": 1,
    "scope": 3,
    "locationHash": 0,
    "allowNegativeValue": false,
    "allowValueChangeWhenCompleted": false,
    "isCountingDownward": false,
    "valueStyle": 0,
    "progressDescription": "",
    "perks": {
        "perkHash": 0,
        "style": 0
    },
    "stats": {
        "style": 0
    },
    "minimumVisibilityThreshold": -2147483648,
    "allowOvercompletion": false,
    "showValueOnComplete": false,
    "isDisplayOnlyObjective": false,
    "completedValueStyle": 0,
    "inProgressValueStyle": 0,
    "hash": 3138177461,
    "index": 3058,
    "redacted": false,
    "blacklisted": false
}
```

**Comment by floatingatoll** [comment]
Is this meant to be shown to us in the API at all?

**Comment by floatingatoll** [comment]
Ugh, I'm sorry, I didn't mean to send that, and when I went to cancel it, I
sent it. Please ignore.

**Comment by vthornheart-bng** [comment]
Indeed, this is unfortunately a limitation of the data we receive.  There are many objectives where they don't elaborate in the objective definition itself on what to do, relying on you using whatever data is attached to the entity (for instance in this case, the record) to infer the objective's purpose.

This is not ideal, but it saves the game-side designers and our localization team a lot of work that wouldn't be necessary for them in order to show the objectives properly in-game.  I've voiced my opinion internally before on the subject, but ultimately we're not going to receive human-readable data for objectives unless they happen to need them on the game side itself.  Sorry about that, it's all we've got.

**Comment by nine13tech** [comment]
It's no problem if this is expected behavior, do we have that documented obviously in the component endpoint return data? I did not see it or I would have not posted. I could very well have missed it.

**Comment by vthornheart-bng** [comment]
Aye - the fact that the empty strings as name/description means that we don't have string data for those objectives.  I could add some notes to the documentation to forewarn others, but empty strings themselves would be the indicator at runtime that we don't have strings.

**Comment by nine13tech** [comment]
now understood! thank you for your time today.
