### ISSUE TITLE
Ingame: 3 Nightsfalls - but api shows me 4 activityHashes

### ISSUE THREAD

**Issue by michabbb** [Bungie-net/api#678]
hi there and sorry if i missed an existing issue to that, it´s a little bit hard right now to find something in all that open issues 🙈 

so i can choose from 3 nightfalls ingame, but the milestones show me right now:

```
"2171429505": {
            "milestoneHash": 2171429505,
            "activities": [
                {
                    "activityHash": 4259769141,
                    "challengeObjectiveHashes": [
                        1435165976
                    ],
                    "modifierHashes": [
                        939324719
                    ]
                },
                {
                    "activityHash": 272852450,
                    "challengeObjectiveHashes": [
                        1435165976
                    ],
                    "modifierHashes": [
                        939324719
                    ]
                },
                {
                    "activityHash": 3701132453,
                    "challengeObjectiveHashes": [
                        1435165976
                    ],
                    "modifierHashes": [
                        939324719
                    ]
                },
                {
                    "activityHash": 322277826,
                    "challengeObjectiveHashes": [
                        1435165976
                    ]
                }
            ],
            "startDate": "2018-09-11T17:00:00Z",
            "endDate": "2018-09-18T17:00:00Z",
            "order": 5000
        },
```

so why do isee `"activityHash": 322277826` here ❓ 

thanks

**Comment by vthornheart-bng** [comment]
Ah, good question!  The reason why it's there is because it's (apparently) the current "Guided Games" variant of Nightfall, at least according to the data.  I will have to check on that and see if it's actually what's being seen in game, but from the data side that's what you'll play if you choose Nightfall Guided Game: and that's also a variant you can play in order to complete the challenge!

**Comment by michabbb** [comment]
@vthornheart-bng thank you, that makes sense. but still, i see this a little bit tricky to differ this - right now, i do this by checking, if "modifierHashes" exists or not. 😏 maybe it´s an idea to add new key like `isguided=1` 🤔 ❓

**Comment by vthornheart-bng** [comment]
Ah, yes - in the DestinyActivityDefinition, take a look at the guidedGame property.  If it is not null, it is a guided game.

**Comment by michabbb** [comment]
perfect, thanks a lot ! 👍
