### ISSUE TITLE
`motesGenerated` stat for Gambit showing zero for all players

### ISSUE THREAD

**Issue by yergi** [Bungie-net/api#681]
See Instance ID 2221665002 for an example. 11 players in and out of that Gambit match before it ended, and all 11 have their `motesGenerated` stat as 0.

**Comment by vthornheart-bng** [comment]
Ah, interesting!  Aye, I'll take a peek.

**Comment by vthornheart-bng** [comment]
TFS 710262

**Comment by vthornheart-bng** [comment]
Looks like it is a problem on the game side - we're having them take a look, but if it's not been getting saved correctly in our backend we're going to end up with a couple of issues:

1) We won't have any retroactive data
2) The fix might not be for some time, as the game build deployment iterations tend to be much slower than BNet.

So just a heads up on these potential difficulties.

**Comment by vthornheart-bng** [comment]
Unfortunately, after talking with the folks working on the underlying stats system, we discovered that we cannot get the following properties:

* motesGenerated
* motesStolen

We'll be removing them from the API on the October 2nd BNet release.  Bummer, but we just don't have the data in order to show it.  Sorry about that!

**Comment by yergi** [comment]
Bummer! I'm guessing there's little to no possibility of it being released some time in the future? Having motesGenerated vs. motesDeposited would be a great comparison to have.

**Comment by vthornheart-bng** [comment]
Yeah, I think that would be awesome too - unfortunately we were told it won't be possible to grab that data.  I'll let them know that folks would like to see it: I do think that'd be a useful stat.  I'm unfortunately unsure of the specific limitations that they're facing that make it impossible currently, and how much work it would take/whether it would ever be feasible to get it.
