### ISSUE TITLE
Class Hash from DB and Api aren't matching

### ISSUE THREAD

**Issue by BaileyMillerSSI** [Bungie-net/api#691]
I feel like I am missing something but I went and downloaded the latest Destiny 2 Manifest for `en` and then I loaded it into a viewer. I ran an api call to my accounts character listing. 
Everything seems fine for the Hunter class but what is going on with my other two characters, should be a Titan, Warlock.
Character Hashes:

- 671679327

- 2271682572

- 3655393761

Values from the database:
![bug](https://user-images.githubusercontent.com/14271740/45722045-9d0acb00-bb78-11e8-98e2-f6cbb57dad3a.PNG)

**Comment by michabbb** [comment]
in case you mean the negative ids, may [this](https://github.com/vpzed/Destiny2-API-Info/wiki/API-Introduction-Part-3-Manifest#manifest-lookups) helps.

**Comment by BaileyMillerSSI** [comment]
Oh god it's getting late... I was comparing the id column value against the hash value thinking they'd be the same.

**Comment by vthornheart-bng** [comment]
No shame in that!  It is unfortunately extremely unintuitive that our hashes are uints and the database stores them as ints.  If I had it to do over again from the very, very beginning, I think I would have made them all ints.  But the amount of work to do that all the way up to the core game infrastructure itself would be too terrible of a cost at this point.

**Comment by BaileyMillerSSI** [comment]
The super misleading part was the hunter row in the database that id equals the hash value. 😛

**Comment by vthornheart-bng** [comment]
Yes, for sure!  It just happened to be the same as a uint as it is as an int, oy!  Definitely a good example of why the fact that they're different totally sucks.

**Comment by vthornheart-bng** [comment]
I'll go ahead and close this one for now - feel free to post a new issue if anything comes up!
