### ISSUE TITLE
Region chest missing region name/incorrect bubbleHash (19/09 manifest)

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#693]
Found a region chest missing its region checklistHash `1997430677`. Specified bubbleHash `1519764506` not found in destinationHash `359854275`'s bubbles array.

![image](https://user-images.githubusercontent.com/156681/45728083-d5a6b500-bc09-11e8-90dd-f764067b309c.png)

**Comment by lowlines** [comment]
This is related to https://github.com/Bungie-net/api/issues/646.
There's actually a number of bubble locations missing from both the Tangled Shore and the Dreaming City.

**Tangled Shore**
- High Plains

**Dreaming City**
- The Confluence
- Ascendant Plane (likely multiple)
- Ouroborea
- Forfeit Shrine
- the other 4 Ascendant Challenge locations

I suspect a lot of the Dreaming City locations are redacted (ie the raid) but the bubbles should probably still get returned with a "Redacted" display name.

**Comment by vthornheart-bng** [comment]
Aye, Raid-related content still needs to be unredacted: however, I'm not sure if that's necessarily related to the missing bubbles.  I'll have to look into it!

**Comment by vthornheart-bng** [comment]
TFS 712521
