### ISSUE TITLE
Record Objective bugs

### ISSUE THREAD

**Issue by lowlines** [Bungie-net/api#694]
So I've hooked up my session tracker to watch record objectives and it looks like these records seem to fluctuate whenever you start a new activity. A +1 means the value increased by one since the last time it was checked. The subclass one in particular is interesting because I was running my hunter at the time but the Titan and Warlock records were also updating their progress value.

![screen shot 2018-09-19 at 5 55 08 pm](https://user-images.githubusercontent.com/4862548/45743051-71501980-bc3a-11e8-9940-cd5f4efa60e5.png)

**Comment by lowlines** [comment]
Here's another one. It looks like the Orb generation record for Gambit is getting count while doing other activities. I spotted it changing while doing PvE and Iron Banner today.
![screen shot 2018-09-19 at 6 43 46 pm](https://user-images.githubusercontent.com/4862548/45743810-128b9f80-bc3c-11e8-93da-5fffa2c01093.png)

**Comment by lowlines** [comment]
I'm happy to filter out recordObjectives with unexpected behaviour. After a full evening of play, it was pretty much just those couple I mentioned that were firing off unexpectedly. There are a good number of records though that have useful overflow stats like the Baron challenges such as "Trick or Treat" where you have to kill 5 enemies with a single engram explosion, it continued to track this after the initial completion so the community could set up daily/weekly challenges where you have to do 10 of these and track the value before and after.

Perhaps what I might do, is do some research and come back with a list of objectives that have useful information but have the showOvercompletion value set to false and you could pass that on to the designers who can decide whether these should be shown or not. I'm sure there'd be a lot of players that would like to see some of these stats in-game so they can brag about it to their friends like those crazy folks who got 10,000 snowball kills!

The Rogue Light one is definitely happening in non-gambit activities, however it is another one of those instances where it hide the value once you've completed it, in this case 1000 orbs. I'm currently 4x that number right now due to the fact that it is counting while doing other activities.

**Comment by lowlines** [comment]
Here's an interesting one. There are 3 records tied to finding 10 chests during each phase of the Taken Curse in the Dreaming City. I'm pretty sure it was counting past 10 perhaps due to there being 2 weeks, but it looks like since reset, this objective has reset. I'm guessing this is intentional because it tasks you with finding all the chest during that period? I'll need to check this when I get home as I know I found all 10 chests last week!

![destiny2_maps_chests_i](https://user-images.githubusercontent.com/4862548/45790809-c422e300-bcc5-11e8-93bc-d99016e83ffc.png)

![screen shot 2018-09-20 at 11 14 59 am](https://user-images.githubusercontent.com/4862548/45790931-7d81b880-bcc6-11e8-8fb8-016b55bf8009.png)

**Comment by lowlines** [comment]
Hmm interesting! I'm guessing the companion app is checking the `state` flag for completion as the objective progress is definitely being returned as zero from the APIs!
![img_5a65324c710d-1](https://user-images.githubusercontent.com/4862548/45791211-daca3980-bcc7-11e8-911c-4d00ac66c773.jpeg)

**Comment by lowlines** [comment]
Working in game, so maybe it's an API bug?
![ap_db22dd7b-d38a-487b-adb9-8a0002191825](https://user-images.githubusercontent.com/4862548/45804631-d0299780-bcfb-11e8-82a2-0bc70fd342ee.JPEG)

**Comment by lowlines** [comment]
Just checked the Rogue Light record in-game, it looks like it is showing the overflow value as well.
![destiny 2_20180921005526](https://user-images.githubusercontent.com/4862548/45831593-f3296b00-bd3e-11e8-999c-f1d0e23b3028.png)

**Comment by vthornheart-bng** [comment]
Good info, thanks lowlines!

I think I'm going to have to report the Orbs Generated one over to the game side.  If you're seeing it happen in non-gambit activities, something is likely amiss.  I'll have to look into the other ones on our side!

**Comment by vthornheart-bng** [comment]
TFS 715493 on the Hidden Riches issue.  The others appear to be game side issues that we can't do much about other than forward them on for others to look at.

**Comment by vthornheart-bng** [comment]
Ah, I have finally had a chance to loop back to this.  Turns out there was a bug that was causing this value to be reset at the end of the week even if you completed the objective, but that has since been fixed in content.

I'm going to go ahead and add a workaround so that, if the record has been redeemed already, then we'll pass the minimum value needed to complete the objective if the game server says the objective is at less than that.

**Comment by vthornheart-bng** [comment]
Fixed as of v2.3.3 deployment (12/11)!
