### ISSUE TITLE
Clan rewards vendor challenge

### ISSUE THREAD

**Issue by Anonymous123428** [Bungie-net/api#698]
My clan says I'm at 5,000 personal xp. But the challenge says I'm at 90%. Why is this happening? Can you either fix this or explain what's wrong? Plus, i can't get another thing that give 750 clan xp until tomorrow. If it is a bug, could you please make it completed on my account because I've been trying to complete this since forsaken came out

**Comment by ArkahnX** [comment]
Please make a post in the Bungie Help forum, as this site is only for the Bungie API, we cannot help resolve in game issues.

Link to the Bungie Help forum: https://www.bungie.net/en/Forums/Topics?pNumber=0&tg=Help
