### ISSUE TITLE
OAuth2 Signing users out

### ISSUE THREAD

**Issue by thisbarker** [Bungie-net/api#70]
Is there an example how to do this and redirect back to our applications, including mobile?

**Comment by iBotPeaches** [comment]
This page (by lowlines) has a little demo for using OAuth2 - https://destinydevs.github.io/BungieNetPlatform/docs/Authentication

It walks through the steps from both a developer and user standpoint.

**Comment by thisbarker** [comment]
Thanks for your response, but I am not sure where it calls out logging a user out. Technically you could drop your reference to their auth tokens, but the next time the user hits the OAuth2 endpoint for authorization they are automatically redirected back without the option to enter a different Xbox/PSN/Blizzard account.

**Comment by ArkahnX** [comment]
There is no api endpoint for signing users out, you can delete your local store of credentials, then direct users to `https://www.bungie.net/en/Profile/Settings?category=Accounts` to remove authentication of your application

**Comment by Tetron-bng** [comment]
Signing out is accomplished by deleting your access token and refresh token.  If you want the user to have a chance to reauthorize your application, and thus potentially change accounts, you may add the query string parameter "reauth=true" to the authorization URL.
