### ISSUE TITLE
Gunsmith rep tokens not showing the right rep value?

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#701]
We got a report that the XP value for the Gunsmith vendor was incorrect - in DIM we use `DestinyFactionDefinition.tokenValues` to compute how many rep levels you could gain by turning in tokens, and a user reported to us that this was still using the old "40 tokens per level" version instead of the new "100 tokens per level" value.

**Comment by vthornheart-bng** [comment]
Found and fixed for the next release!

**Comment by vthornheart-bng** [comment]
TFS 715432

**Comment by bhollis** [comment]
Awesome!
