### ISSUE TITLE
Some Records for Triumphs are not coming down in the GetProfile ProfileRecords data

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#702]
As I've been using more of the Triumphs data in the API, I've noticed that some records do not return their progress/state in the GetProfile API.

For example, there is the [Curious (4026489705)](https://data.destinysets.com/i/Record:4026489705) record, under the PresentationNodes Triumphs > Account > Character > Warlock. This shows as completed in game, but I'm not getting any data returned for it in the API. Curiously, the Bungie app does show it marked as completed. Is there something I'm missing?

The API call I'm making is `https://www.bungie.net/Platform/Destiny2/1/Profile/4611686018432128055/?components=100,102,200,201,205,301,305,104,202,800,900`

**Comment by vthornheart-bng** [comment]
Hmm, let me go take a peek

**Comment by vthornheart-bng** [comment]
I'm going to go ahead and close this bug for now, as I do see the data coming down - let me know if this isn't working for you with this suggestion!
