### ISSUE TITLE
`DestinyStatsGroupDefinition.uiPosition` is always zero

### ISSUE THREAD

**Issue by adtennant** [Bungie-net/api#706]
I'm trying to make use of the `uiPosition` in `DestinyStatsGroupDefinition` but it's always zero.

I guess that's what the "Something's being lost in translation with this value." refers to in the documentation.

```
"uiPosition": {
    "type": "integer",
    "description": "This apparently indicates the position of the stats in the UI? I've returned it in case anyone can use it, but it's not of any use to us on BNet. Something's being lost in translation with this value.",
    "format": "int32"
}
```

**Comment by floatingatoll** [comment]
What are you hoping to use it for?

**Comment by adtennant** [comment]
Displaying stats, in the right order.

**Comment by adtennant** [comment]
Thanks for the in-depth answer @vthornheart-bng. I think the reality is that I will have to keep my own list of stat in some capacity, but if I could derive the ordering I would prefer that. The order in DestinyStatDefinition is fine for now, is that with any particular ordering applied?

**Comment by floatingatoll** [comment]
Would it be possible to re-order the StatGroup's JSON array to match the
StatDefinition ordering on the API side?

**Comment by vthornheart-bng** [comment]
It *looks* like that.  But the game UI infrastructure is extremely opaque, so I can't guarantee that this is the final word on how they get ordered.  I hit up a UI Designer, hopefully we'll have some answers eventually when they get around to it!

And indeed, if this ends up being the definitive answer, my gut response would be to change our StatGroup definition to reflect the ordering, such that you only have to enumerate through that list.  But we'll see what they say.

**Comment by vthornheart-bng** [comment]
Okay, got some confirmation - this is indeed how it's sorting in game now.  That means I can modify our import process as well with that approach so that StatGroups' stats are naturally ordered in that fashion.  A bit late right now though - this is more of a reminder to myself to add a bug in the morning for it.

**Comment by vthornheart-bng** [comment]
TFS 717472
