### ISSUE TITLE
API and screenshots that take ornaments into account

### ISSUE THREAD

**Issue by floatingatoll** [Bungie-net/api#709]
Someone noted that changing the ornament on a weapon does not change the screenshot in the API. Could you extend the API to take that cosmetic property into account when offering item screenshots?

**Comment by vthornheart-bng** [comment]
I dig this idea, it was on my mind as a potential improvement back when D2 first launched but we never had time to loop back to it.

My thought is that I'd attach the screenshot of the item with its alternative ornament on the ornament plug's DestinyInventoryItemDefinition, which should give people the freedom to swap out to that screenshot if they'd like.

I also would like to do something similar with Shaders, giving a screenshot on the shader's Item Definition with some example item shaded with that shader.

Let's keep this on the radar for future improvements!

**Comment by ArkahnX** [comment]
For shaders, currently when you preview them it applies the shader to all currently equipped items and shows you that. You could probably generate a screenshot for that using similar steps to how gear screenshots are generated.

Then maybe attach that screenshot to the shader item, just as a gear screenshot would be?

**Comment by NigelHietala** [comment]
This could be closed as it's now in :D

**Comment by vthornheart-bng** [comment]
Phew, back in the day!  Thanks @jshaffstall-bng !
