### ISSUE TITLE
Add encounters played/wishes used to Last Wish raid PGCR

### ISSUE THREAD

**Issue by BlazeBoss17** [Bungie-net/api#710]
The recent addition of startingPhaseIndex is great, but in its current form it is not very useful for the new Last Wish raid. 

A player can load into a fresh Last Wish (startingPhaseIndex=0) then enter a code on the wish wall to skip ahead to any checkpoint, including final boss. As a result of this, it is impossible to distinguish full raids with all encounters played vs raids where players skipped around and only played some encounters. 

I imagine adding a variable like this would be a lot of work, but it would be super useful for many different app creators.

**Comment by vthornheart-bng** [comment]
TFS 717489

**Comment by BlazeBoss17** [comment]
Hi, I know you are probably really busy with lots of issues right now, but any update on this issue?  Thanks

**Comment by vthornheart-bng** [comment]
Good call, I'm glad you pinged on this!  I hadn't gotten an update in a while.  Checked with the Wizard and his crew just now on it.  It had to get punted out from the December release unfortunately.  It's still being looked at as far as if it will be possible/when they'd be able to get it in if it is possible.

**Comment by vthornheart-bng** [comment]
Aye, I'd like to see it too - I don't know when it's going to come about though unfortunately.  I'll try to keep you all posted once I get more information on both if they'll be able to do it and when it'll be done (if they can).

**Comment by vthornheart-bng** [comment]
I just got word back about this - unfortunately it's not possible for us to get that data in the PGCRs.  Sorry guys.
