### ISSUE TITLE
Some weapon show not available masterwork Tier upgrades

### ISSUE THREAD

**Issue by mistral13** [Bungie-net/api#714]
Hi

Some of my weapon show wrong upgrade and/or to many masterwork Tier.
Example 1: full Masterwork show Tier 2 available

![98a3531e-5b26-4ffa-83dc-18c4ed80b52c](https://user-images.githubusercontent.com/5049663/46262980-7437ed80-c509-11e8-8387-0913fc0e0781.png)

Example 2: Tier 3 show Tier 4 and Tier 2 available
![244a3605-f6c5-4dff-b633-93c196bdde17](https://user-images.githubusercontent.com/5049663/46263002-b3fed500-c509-11e8-9404-8a65bfeebb4f.png)

Same Problem with other apps:
![dd05d115-2d07-403e-9a3c-cb4630ea5220](https://user-images.githubusercontent.com/5049663/46263018-e577a080-c509-11e8-846f-6c2809298732.png)

**Comment by vthornheart-bng** [comment]
Ooh, yuck.  Filed as TFS 717180, I'll give it a look!

**Comment by vthornheart-bng** [comment]
Glad you reported this, and I wish I had gotten the chance to look into it earlier!  I'm finally looping back to this, and it's a doozy.

There's a very subtle bug happening right now, and it's pretty sneaky.  If you take a look, I bet you'll find another item somewhere on that character that has a level 2 masterwork of the identical type (handling in this example) available in its reusablePlugs.  The state of *that* weapon is falsely transferring in the API into the state of the *other* weapon.

I'm going to see what I can do to prevent this from happening.  Thanks for reporting this!

**Comment by mistral13** [comment]
That’s correct. I have identical type of masterwork on different levels on that character

**Comment by vthornheart-bng** [comment]
There we go, this should be finally fixed in the upcoming bnet release!

**Comment by vthornheart-bng** [comment]
Just a heads up, because it came so close to our deployment it may have missed the window, which would mean it'll be a couple of weeks before it goes live.  Hang tight, checking with folks now.

**Comment by mistral13** [comment]
Ok no problem

**Comment by vthornheart-bng** [comment]
Fixed as of v2.3.3 deployment (12/11)!
