### ISSUE TITLE
Motes Generated Not Calculated Correctly

### ISSUE THREAD

**Issue by RobertMcCoy** [Bungie-net/api#718]
Currently the `motesGenerated` field returned from `Character/0/Stats/?groups=0,0&modes=63&periodType=0` is returning a value of `0`. Other values are populating (deposited, lost, etc.) but this one has not changed. I presume this is motes generated from monster kills, if it's not then maybe I'm wrong with this issue.

**Comment by vthornheart-bng** [comment]
Unfortunately we discovered that this data is not only incorrect, but that it's impossible for us to get at in our backend.  #681 for some more details.  We're releasing the new version of Bungie.net tomorrow, at which time motesGenerated will no longer exist as a stat.  Sorry about that, it's a bummer :(

**Comment by vthornheart-bng** [comment]
(closing this one as it's covered in #681)

**Comment by RobertMcCoy** [comment]
@vthornheart-bng Noooooo I was a bit scared that might be the case if it was never storing correctly, to begin with. Thanks for looking into this (and sorry for the dupe, couldn't find it when searching) and the response!

**Comment by vthornheart-bng** [comment]
Aye, sorry about that!  I wish I had better news for it! :(
