### ISSUE TITLE
Hawthorne's bounty items are not returned

### ISSUE THREAD

**Issue by JonnyOThan** [Bungie-net/api#719]
In the GetVendors endpoint, Hawthorne's bounty items are not present - but her weapons and armor are.  This might be similar to #704 where the items are dependent on some other unlock state (e.g. being in a clan) that is not reflected when gathering data.  But in this case, it's specific to certain items instead of the vendor as a whole.

**Comment by vthornheart-bng** [comment]
Aye, unfortunately it's the same as #704, though there may be something BNet can do more proactively in that situation unlike the Petra situation.  I have a bug on that, I'm covering that in #677 - I'll close this one for now so that one's the tracker for it!
