### ISSUE TITLE
Destiny2.GetProfile - does this require auth?

### ISSUE THREAD

**Issue by waferbaby** [Bungie-net/api#721]
Hello! I'm not sure if the `GetProfile` method requires authentication (the docs don't seem to be labelled re: that).

I can search for my profile via `Destiny2.SearchDestinyPlayer`, and get my membership ID and type, but if I then try `GetProfile` with those values, I get back:

```
{
    "ErrorCode": 18,
    "ErrorStatus": "InvalidParameters",
    "Message": "The input parameters were invalid, please enter valid input, and try again.",
    "MessageData": {},
    "ThrottleSeconds": 0
}
```

This is with a membership type of '2' (I'm on PS4.) I would have assumed I'd get 401 if it was an auth thing, but maybe I'm wrong?

Thank you! <3

**Comment by ArkahnX** [comment]
get profile needs to be called with some components attached on to it see [This document](https://bungie-net.github.io/multi/schema_Destiny-DestinyComponentType.html#schema_Destiny-DestinyComponentType)

Otherwise if you provide the URL you used we can help debug what might have gone wrong

**Comment by waferbaby** [comment]
@ArkahnX Ooh, I totally missed that as a requirement! Thank you :)

**Comment by waferbaby** [comment]
(I guess I'd hope the error message would have let me know `components` was missing, f'instance.)

**Comment by ArkahnX** [comment]
that has been brought up before as well!

**Comment by vthornheart-bng** [comment]
Aye, that error result is extremely crappy and unhelpful: sorry you ran into that!  Thanks for the assist @ArkahnX !

**Comment by waferbaby** [comment]
@vthornheart-bng All good, I know how it goes. Long-time (long-suffering) API developer over here. I wish I worked on the Destiny API (I love APIs, and I love Destiny, so I'm very jealous.)
