### ISSUE TITLE
Leviathan in Milestone Endpoint returns 2 normal and 2 GG hashes

### ISSUE THREAD

**Issue by mistahj67** [Bungie-net/api#742]
Looking for the reason for the two normal modes:
2693136601 and 2693136603,
There is also 2 guided games: 287649202 and 4039317196
Example for week 59 (10/15-10/22)
 "3660836525": {
            "milestoneHash": 3660836525,
            "activities": [
                {
                    "activityHash": 2693136601,
                    "challengeObjectiveHashes": [],
                    "phaseHashes": [
                        2188993306,
                        3847906370,
                        1431486395,
                        4231923662
                    ],
                    "booleanActivityOptions": {
                        "2035588273": true
                    }
                },
                {
                    "activityHash": 2693136603,
                    "challengeObjectiveHashes": [],
                    "phaseHashes": [
                        3847906370,
                        2188993306,
                        1431486395,
                        4231923662
                    ],
                    "booleanActivityOptions": {
                        "2035588273": true
                    }
                },
                {
                    "activityHash": 3446541099,
                    "challengeObjectiveHashes": [],
                    "phaseHashes": [
                        3847906370,
                        2188993306,
                        1431486395,
                        4231923662
                    ],
                    "booleanActivityOptions": {
                        "2035588273": true
                    }
                },
                {
                    "activityHash": 287649202,
                    "challengeObjectiveHashes": [],
                    "booleanActivityOptions": {
                        "2035588273": true
                    }
                },
                {
                    "activityHash": 4039317196,
                    "challengeObjectiveHashes": [],
                    "booleanActivityOptions": {
                        "2035588273": true
                    }
                }
            ],
            "startDate": "2018-10-16T17:00:00Z",
            "endDate": "2018-10-23T17:00:00Z",
            "order": 9000
        },

**Comment by mistahj67** [comment]
Update for week 60 10/23- 10/ 29
It appears that the 2693136601 and 287649202 are non-changing static. 
Normal modes: 2693136601 and 2693136600
GG: 287649202 and 89727599
"3660836525": {
            "milestoneHash": 3660836525,
            "activities": [
                {
                    "activityHash": 2693136601,
                    "challengeObjectiveHashes": [],
                    "phaseHashes": [
                        2188993306,
                        3847906370,
                        1431486395,
                        4231923662
                    ],
                    "booleanActivityOptions": {
                        "3796634159": true
                    }
                },
                {
                    "activityHash": 2693136600,
                    "challengeObjectiveHashes": [],
                    "phaseHashes": [
                        2188993306,
                        1431486395,
                        3847906370,
                        4231923662
                    ],
                    "booleanActivityOptions": {
                        "3796634159": true
                    }
                },
                {
                    "activityHash": 2449714930,
                    "challengeObjectiveHashes": [],
                    "phaseHashes": [
                        2188993306,
                        1431486395,
                        3847906370,
                        4231923662
                    ],
                    "booleanActivityOptions": {
                        "3796634159": true
                    }
                },
                {
                    "activityHash": 287649202,
                    "challengeObjectiveHashes": [],
                    "booleanActivityOptions": {
                        "3796634159": true
                    }
                },
                {
                    "activityHash": 89727599,
                    "challengeObjectiveHashes": [],
                    "booleanActivityOptions": {
                        "3796634159": true
                    }
                }
            ],
            "startDate": "2018-10-23T17:00:00Z",
            "endDate": "2018-10-30T17:00:00Z",
            "order": 9000
        },

**Comment by vthornheart-bng** [comment]
Thanks for this info!  I've not yet had a chance to look into this, but I'll get it logged.

**Comment by vthornheart-bng** [comment]
Looping back to this, as I just noticed it's still active: I'm looking into this presently!

**Comment by vthornheart-bng** [comment]
Oh, I see what's happening.  That's both super annoying and interesting.

So, if you look in the DestinyActivityGraphDefinitions you'll see a bunch of old trash in there that no one cleaned up - old versions of the Director that no longer apply.  One of them is the original D2 launch version of the main view in the Director: and in that old no longer applicable view, the original Leviathan raid's original incarnation (and its original Guided Game variant) are technically "visible"... but there's no way to actually reach that old Activity Graph, because it's no longer shown in the Director.

I am not effectively culling old Activity Graphs from my test for visibility of activities, which due to this is causing the original Leviathan raid's Activity to always be returned in this milestone.  Barf.

I'll fix this up for the December release - thanks for reporting it, and I'm sorry that it took so long to get back to it!

**Comment by vthornheart-bng** [comment]
https://www.youtube.com/watch?v=6N-_RIVpZvY

**Comment by vthornheart-bng** [comment]
There we go - this will be fixed not in the upcoming 11/27 release which is too late, but the one tentatively scheduled for 12/11.

**Comment by vthornheart-bng** [comment]
Fixed as of v2.3.3 deployment (12/11)!

**Comment by michabbb** [comment]
@vthornheart-bng you said it´s fixed: can you tell me where inside the api result i can search for the challange, please ?
