### ISSUE TITLE
Spaces url-encoded as '+' no longer work.

### ISSUE THREAD

**Issue by superhawk610** [Bungie-net/api#746]
This definitely isn't a breaking change, but I didn't see it documented and it took me a bit to track down so I figured I'd open an issue in case anyone else ran into it.

Until recently, I was using

```
https://www.bungie.net/Platform/GroupV2/Name/Charlie+Company+337/1/
```
to fetch info on our clan. However, this page now 404s, as the `+` appear to be treated as literal `+` characters instead of a url-encoded space. Using `%20` instead works as intended.

```
https://www.bungie.net/Platform/GroupV2/Name/Charlie%20Company%20337/1/
```

**Comment by floatingatoll** [comment]
FWIW, + is only supposed to be translated to whitespace in the ?query=args+segment or in a form-encoded request body. That it ever worked at all is more likely a bug than that it stopped working.

Depending on it to be translated in the path is not going to work reliably anywhere, as it’s a reserved character in the path (where you’re using it) and is not guaranteed to be translated to whitespace at all in that location.

Consider using %20 instead. (Or: If you’re encoding your data with a form data encoder, use a URI encoder instead.)

**Comment by superhawk610** [comment]
Ah, good point. I've switched to `%20`.

**Comment by floatingatoll** [comment]
I did some digging and older Python encoders had a bug where they encoded the path with the form encoder rather than the URI encoder, so for future people finding this thread, try upgrading your encoding library or your Python.
