### ISSUE TITLE
titles on Seal records not populated

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#753]
I'm trying to determine the user's current equipped title, but it doesnt not seem like its possible to get the title string, like 'Dredgen' or 'Wayfarer' that shows in game. This data does not seem to be populated in the definitions.

Here's what I've investigated:

- I (`membershipType: 2, membershipId: 4611686018469271298`) have equipped the 'Dredgen' Gambit  title on my Hunter and Warlock (`characterID: 2305843009358866365 `).
 - I see that `ProfileResponse.characters.data[2305843009358866365].titleRecordHash` is populated with `3798931976`
 - `3798931976` is [the record](https://data.destinysets.com/i/Record:3798931976) representing that seal, so I am able to identify that I have equipped the Gambit seal
 - However, `titleInfo.titlesByGender.male` and `titleInfo.titlesByGender.female` is both null, despite `titleInfo.hasTitle` being true.

**Comment by vthornheart-bng** [comment]
Hmm, good find - I'm surprised that slipped through the cracks!  TFS 732196

**Comment by vthornheart-bng** [comment]
Fixed as of v2.3.3 deployment (12/11)!
