### ISSUE TITLE
genderedRace/ClassNames not filled in correctly for Polish

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#76]
Not sure about other languages, but in the Polish world DB, the strings are "Awoken Male", "Hunter", etc.

**Comment by bhollis** [comment]
Same with Russian. In the Chinese database, the characters have localized info but all the items and stats and such are in English.

**Comment by vthornheart-bng** [comment]
Yes, unfortunately this is a known issue - any strings that were not sourced by the game itself, but rather by Bungie.net string content, are still in the process of translation.  We have no ETA for when this translation will be completed, but the process is ongoing.

**Comment by bhollis** [comment]
Hmm, what about the Chinese item info though? I'd expect those would come from game content?

**Comment by vthornheart-bng** [comment]
Hmm, I'll have to look into that further.

**Comment by vthornheart-bng** [comment]
Ah, I see what's going on.  We've got some fixing to do on our end for that, specifically for Chinese languages.  It's not going to fix everything, but it should at least fix non-BNet-sourced strings for Chinese (simplified and Traditional).  I unfortunately don't have any good news for BNet sourced strings other than to say that they should eventually come around.

**Comment by vthornheart-bng** [comment]
Chinese support has been fixed - check out the latest deployment today, and let me know if you run into any other issues!  Polish and other languages will still, unfortunately, have gaps that will continue to be filled as the localizers get to Bungie.net specific content, but at least the game-driven data should be good for all supported languages now.
