### ISSUE TITLE
Decryption key ID in token envelope is unknown

### ISSUE THREAD

**Issue by michabbb** [Bungie-net/api#765]
hi, i don´t know why, but suddendly i get this error. i changed nothing on my side. this error appears when i want to refresh my token.
did the api changed lately ??? thanks.

**Comment by vthornheart-bng** [comment]
What endpoint are you hitting, and could you provide the full request and response body?  Also, can you provide your bungled cookie value?

**Comment by floatingatoll** [comment]
If your original authentication was one year ago, it will be necessary to reauthorize your application to your Bungie.net account. (If that _is_ the case, this isn’t necessarily a great error message; I’m only guessing at the cause.)

**Comment by michabbb** [comment]
@vthornheart-bng my endpoint is `App/OAuth/Token`

my params are:

```php
array (2) [
    'form_params' => array (2) [
        'refresh_token' => string (360) "xxxxxxxxxxxx=="
        'grant_type' => string (13) "refresh_token"
    ]
    'headers' => array (4) [
        'Authorization' => string (74) "Basic xxxxxxxxx=="
        'X-API-KEY' => string (32) "xxxxxxxxxxxxx"
        'Accept' => string (16) "application/json"
        'Content-Type' => string (33) "application/x-www-form-urlencoded"
    ]
]
```

http return code is: `400` with:

error: `server_error`
error_description: `Decryption key ID in token envelope is unknown`

@floatingatoll how do i know if my app is older than one year ? i don´t see a date anywhere 😕

**Comment by michabbb** [comment]
super strange... i was able to fix this by getting a complete new refresh-token: `https://www.bungie.net/en/OAuth/Authorize?client_id=xxxx&response_type=code` - but anyway, @vthornheart-bng: would be good to know what this error really means 😏
