### ISSUE TITLE
11/27 - Destiny endpoints will begin returning DestinyThrottledByGameServer in periods of high traffic

### ISSUE THREAD

**Issue by vthornheart-bng** [Bungie-net/api#771]
Heads up folks: starting on 11/27, if the game servers experience sufficiently high workload, they're going to begin throttling us more aggressively in the past.  They'll be passing us a new error that we'll be passing down to you: if you receive a DestinyThrottledByGameServer response from us, this means that it's the game server itself throttling us (and you by extension).  Please treat it as you would treat other throttling errors, and scale back your requests until service resumes.

Thank you!

**Comment by Akumati1435** [comment]
Got an error code for that?

**Comment by BlazeBoss17** [comment]
I’d also like to know what HTTP status code and Bungie errorCode these responses have.

**Comment by vthornheart-bng** [comment]
Ah, yes - the error code will be 1672 (DestinyThrottledByGameServer in https://bungie-net.github.io/multi/schema_Exceptions-PlatformErrorCodes.html#schema_Exceptions-PlatformErrorCodes)

The http status code will still be 200 for now, reflecting the bug mentioned earlier that we're going to have a longer delay before we can support non-200 error codes in the API.  But when we enable that, it will begin returning 503.

**Comment by vthornheart-bng** [comment]
Fixed as of v2.3.3 deployment (12/11)!
