### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by SarKurd** [Bungie-net/api#774]
The API always returns CORS issue when i make requests

```javascript
//ERROR
ErrorCode: 2107
ErrorStatus: "OriginHeaderDoesNotMatchKey"
Message: "Origin header does not match the provided API key."
MessageData: {Origin: "http://localhost:3000"}

```

```javascript
//CODE
axios
      .get(
        `https://www.bungie.net/Platform/Destiny2/SearchDestinyPlayer/-1/${id}/`,
        {
          headers: {
            "X-API-Key": process.env.REACT_APP_API_KEY
          }
        }
      )
```
```
//Bungie.net 
```

![screen shot 2018-11-14 at 14 28 15](https://user-images.githubusercontent.com/13942717/48485600-936caf00-e819-11e8-99ee-9d9b255a44a8.png)

**Comment by SarKurd** [comment]
Worked, thanks

**Comment by bgarbitt** [comment]
Hello. I'm currently having the same issue here and I would like to see if this solution would work for me, but I'm a bit confused by what you two mean using the `*`. Is this related to the Access-Control-Allow-Origin header?

**Comment by SarKurd** [comment]
In the origin header for local testing use `*`, you need to change this to the root url for production or other people can use your key

![screen shot 2018-11-16 at 10 33 02](https://user-images.githubusercontent.com/13942717/48613233-70620c80-e98b-11e8-814a-68dc3b0dc0d0.png)
