### ISSUE TITLE
What are the endpoints for progressions like infamy, valor and glory?

### ISSUE THREAD

**Issue by SarKurd** [Bungie-net/api#778]
I have a hard time understanding the API, i can't seem to figure out endpoint or query for progressions like Infamy 

The only one that i use now is this one with query `modes`
```
Path: /Destiny2/{membershipType}/Account/{destinyMembershipId}/Character/{characterId}/Stats/
```
It returns all the gambit related stats but Infamy

also `modes=4` return how many raids i have completed but not which one

Sorry if the question is a little stupid :D

**Comment by nine13tech** [comment]
Hey, Welcome to the group if someone has not said before....

You are asking for Progression.. it's technically a faction rank.
you want the Bungie Profile for that; as documented here:
`https://bungie-net.github.io/multi/operation_get_Destiny2-GetProfile.html#operation_get_Destiny2-GetProfile`
This would be your REST call:
`https://www.bungie.net/Platform/Destiny2/<platform (xbox psn etc)>/Profile/<destiny membershipId>/?components=100,202`
100 is the basic profile info and characters, 202 is the progressions.. this is a comma separated no whitespace list of the components you wish to return.

* Profiles: 100
* CharacterProgressions: 202
as documented:
`https://bungie-net.github.io/multi/schema_Destiny-DestinyComponentType.html#schema_Destiny-DestinyComponentType`

**Comment by SarKurd** [comment]
Thanks for your help I fetched the infamy progress, but i can't seem to be able to find overall infamy a player has or how many times he rested it, how do you calculate that?

That's the response i got 
```javacript
"2772425241": {
                            "progressionHash": 2772425241,
                            "dailyProgress": 0,
                            "dailyLimit": 0,
                            "weeklyProgress": 1895,
                            "weeklyLimit": 0,
                            "currentProgress": 6200,
                            "level": 10,
                            "levelCap": 16,
                            "stepIndex": 10,
                            "progressToNextLevel": 850,
                            "nextLevelAt": 1000
```
