### ISSUE TITLE
Include a generic icon in results marked as "classified" or "redacted"

### ISSUE THREAD

**Issue by ArkahnX** [Bungie-net/api#78]
There is already basic information included such as `description: "Keep it secret.  Keep it safe.", name: "Classified"` but having an icon would prevent applications from having to source their own.

Relevant since D2 is a new release and there is bound to be classified items for quite some time.

Old icon: https://www.bungie.net/img/misc/missing_icon.png

**Comment by vthornheart-bng** [comment]
Definitely!  Yeah, that's a good plan.

**Comment by ArkahnX** [comment]
Actually looks like there is a new icon for D2 already https://www.bungie.net/img/misc/missing_icon_d2.png

**Comment by vthornheart-bng** [comment]
Ah, sweet - good find!  I'll modify the redaction accordingly.

**Comment by vthornheart-bng** [comment]
These items now point to the default blank icon.
