### ISSUE TITLE
Leviathan Challenge data gone? ¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by vthornheart-bng** [Bungie-net/api#783]
Judging by the Twitters, the Leviathan Challenge data disappeared and/or broke a few weeks ago.  I'll have to find out what's up - this is what happens when you don't dogfood your own challenge data. #whoops #alsoiprobablyshouldhavewrittenanautomatedtestforit #tenthousandthousandfruittotouchcherishinhandliftdownandnotletfall

**Comment by vthornheart-bng** [comment]
Ah, after investigating and digging up an old bug I see what's going on here.  We are returning this data, but as implied in #631 we don't have *human readable* data for these challenges.  What I neglected to do was loop back to inform you where you can get the data that you then can associate yourself with the challenges.

In the results we return, there's a property called "booleanActivityOptions".  Any hashes returned in there equate to special states in the game mode: in the case of Raids, these are the "Challenges".  We unfortunately have no human-readable data for these hashes however, so it's up to you to determine which hash equates to which "challenge" and then what you want to display to the user based on that.  See #631 for more details - I wish we had more data to give, but that's all we've got.

**Comment by vthornheart-bng** [comment]
Ah, son of a biscuit.  I haven't updated the API docs in a while, the version that's up is old enough that it doesn't have that property mentioned.  My apologies!  I'll see about updating the documentation before I leave for thanksgiving.

**Comment by nine13tech** [comment]
@vthornheart-bng Happy Thanksgiving! Not trying to speak for everyone, but we are thankful for you. At least, I know I am!

**Comment by vthornheart-bng** [comment]
Related - there is a problem where too many Leviathan activities are being returned.  I've found the fix, and it's a stupid problem that I'll try to get in for the first deployment in December.  More info here: #742

**Comment by vthornheart-bng** [comment]
Thank you @nine13tech!  You have a Happy Thanksgiving as well!
