### ISSUE TITLE
GameVersion in GetProfile once black armory comes out

### ISSUE THREAD

**Issue by Akumati1435** [Bungie-net/api#784]
Hey - When will the game version be updated to show who has black armory?  I believe for now the only way to get it is to own the annual pass, but will the game version be updated to show who has the next two as well or just black armory?   I require my members to have the most recent expansion, so I'd like to give the people who would be kicked advanced warning.

Also if you can check edgar's DMs that'd be helpful!

**Comment by vthornheart-bng** [comment]
Oh, you know - this reminds me, I haven't uploaded the API docs in a while.  That is totally my bad!  To quote Gandalf, "I was... delayed." ;)  However, I just checked on it and indeed it hadn't gone live yet - it looks like it's going live on 11/27.

When that happens, DestinyGameVersions flags enum value 16 = YearTwoAnnualPass, which if true will tell you if they have Black Armory (and the other annual pass seasons access!)

**Comment by vthornheart-bng** [comment]
Oh yes!  It is:

[Flags]
	public enum DestinyGameVersions
	{
		None = 0,
		Destiny2 = 1,
		DLC1 = 2,
		DLC2 = 4,
		Forsaken = 8,
		YearTwoAnnualPass = 16
	}

**Comment by nine13tech** [comment]
Awesome thanks, but what is 15?
"profile": {
            "data": {
                "userInfo": {
                    "membershipType": 1,
                    "membershipId": "4611686018443649607",
                    "displayName": ...
                },
                "dateLastPlayed": "2018-10-24T03:51:36Z",
                "versionsOwned": 15,
                "characterIds": [
                    "2305843009284754459",
                    "2305843009284754460",
                    "2305843009290746427"
                ]
            },
            "privacy": 1

**Comment by vthornheart-bng** [comment]
Oh, 15 is the combination of every flag other than YearTwoAnnualPass - the trick is that this is a Flags enumeration, so each value represents a bit flag.  Destiny2 is the first bit, DLC1 the second etc... so if you do a bitwise OR of those values together, it'll equal 15.  (contrarily, if you're looking for a specific flag being set, you'll want to do a bitwise AND between YearTwoAnnualPass [16] and whatever value they have.  If the result equals 16, that means they have the bit set!)

**Comment by soren42** [comment]
They’re additive binary states… 15 is 8+4+2+1 … or 1111 in binary.
First bit is Destiny, second is DLC1, third is DLC ⒉..

**Comment by vthornheart-bng** [comment]
I go into it a little more here if it's helpful:

https://github.com/Bungie-net/api/wiki/FAQ:-Flags-Enumerations,-how-do-they-work%3F

**Comment by nine13tech** [comment]
Thanks @soren42 and @vthornheart-bng  - I learn something new every single time.

**Comment by Akumati1435** [comment]
So if they have the pass, it will be a 31?

**Comment by soren42** [comment]
Yep, if they have the pass and Forsaken … actually, I think you need Forsaken to buy the pass, and you need all the prior DLC to play Forsaken, so it may be impossible to have a 16 — as you say only a 31.

**Comment by vthornheart-bng** [comment]
Fixed as of v2.3.3 deployment (12/11)!
