### ISSUE TITLE
Saint 14 adventure chain character scoped but can only be played once

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#786]
How should I handle these two adventures, _Signal Light_ and _Not Even the Darkness_, as all other adventures are character scoped?

https://github.com/justrealmilk/dev2.braytech.org/issues/5

Is this something that may change or should I design around it?

**Comment by vthornheart-bng** [comment]
Hmm, interesting problem!

One thing you could do is go through and check if any of the characters have done it, and then show it.  Which feels bad, but could be an option.

That is super frustrating that something meant to be character scoped has some account-scoped restriction in doing it a second time.  I think the real solution if it ever ends up on a high enough priority might be to try and give you an account-scoped rollup with the "most optimistic" view of the checklist across all character data.  But that feels unsatisfying as well.  Hmm.

I don't think we're going to have time anytime soon to give a more permanent fix for these, and I can guarantee that the game side won't change unfortunately.  Indeed, a design workaround is probably your best short-term solution.  Long term, if we get time to loop back around to it I'd have to give some thought to whether this warrants changing how Checklists are returned.

**Comment by justrealmilk** [comment]
Knowing that the game side won't change makes it very easy to rationalise a design-a-round.

Thanks thorn 🦃

**Comment by vthornheart-bng** [comment]
No prob!  Wish I had a better answer!  Have a great thanksgiving!
