### ISSUE TITLE
New API user trying to figure out how to pull a characters subclass?

### ISSUE THREAD

**Issue by cozyrobinson** [Bungie-net/api#787]
Is it considered an item? I can get their main class, guns/armor but I'm failing to get the subclass. 

I'm assuming it's something simple I'm just missing. A little guidance would be so appreciated.

**Comment by vthornheart-bng** [comment]
Greetings!  Indeed, the subclass is just another item that's equipped!  Here's an example of one:

https://data.destinysets.com/i/InventoryItem:3382391785

You'll notice that its inventory.bucketHash property points to a bucket hash called "Subclass":

https://data.destinysets.com/i/InventoryItem:3382391785/InventoryBucket:3284755031

You can pull all of a character's available subclasses and the one they have equipped by looking for that bucketHash on the items!

You can then check which nodes are activated by checking the "talent grid" properties returned for the item.  (Fun fact: subclasses are the only remaining part of the game that uses Talent Grids.  In Destiny 1, that was how "perks" on items worked.  In Destiny 2, that moved to "Sockets" and Talent Grids were abandoned as a concept by everything except for Subclasses!)

**Comment by vthornheart-bng** [comment]
If you end up wanting to pull their talent grid info, here's some information about their definitions.  They can be a very confusing topic, so don't be afraid to ask questions about it!

This is the documentation for the "static" definition data of talent grids:

https://bungie-net.github.io/multi/schema_Destiny-Definitions-DestinyTalentGridDefinition.html#schema_Destiny-Definitions-DestinyTalentGridDefinition

And this is the info for the "live" data that you get from the GetProfile/GetCharacter/GetItem endpoints when you ask for Talent Grid data:

https://bungie-net.github.io/multi/schema_Destiny-Entities-Items-DestinyItemTalentGridComponent.html#schema_Destiny-Entities-Items-DestinyItemTalentGridComponent

**Comment by cozyrobinson** [comment]
Thanks a ton for the quick response!

**Comment by vthornheart-bng** [comment]
No prob, glad to be of help!
