### ISSUE TITLE
Being redirected when calling GetPostAndParent

### ISSUE THREAD

**Issue by frasermcarthur** [Bungie-net/api#791]
I'm trying to make a call to the GetPostAndParent endpoint. I can do it just fine in Postman, however when I make the request with my .NET Core app it is being redirected to this URL: http://bnetprodweb03.tiger.local/Platform/Forum/GetPostAndParent/

Any idea what may be causing this or how I can fix?

**Comment by floatingatoll** [comment]
Are you sending a trailing slash on your request? If not, appending it
should make the redirect stop occurring.

**Comment by frasermcarthur** [comment]
Adding the trailing slash sorted it. Thanks @floatingatoll!
