### ISSUE TITLE
Cached responses for GetProfile?

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#80]
I'm noticing an issue with DIM where we'll transfer an item, and then when I reload (rebuilding the view of inventory from a `GetProfile` call) the item is back where it started. This happens for quite a while, until eventually after enough time passes the item finally shows up where I'd expect. This doesn't seem to happen with the Companion app (when I pull to refresh the item is where I'd expect).

An example URL is `https://www.bungie.net/Platform/Destiny2/2/Profile/4611686018433092312/?components=100,102,103,200,201,202,204,205,300,301,302,304,305,306,307,308`

**Comment by JonnyOThan** [comment]
I've had caching problems in the past - if you hit the same Bungie server it might cache your data for up to a minute.  You can tell which server you got by looking at the x-bungienext-mid2 header in the response.  I'm not sure if there's a way to request a specific server - maybe send that header back? I dunno.  If that *does* work, then if you want a hard refresh then you could try changing it to a different server number than one you've hit in the last minute.

**Comment by floatingatoll** [comment]
Thorn, what property can we use in either the HTTP response headers or response body to determine the “cache time stamp” of a given response, for comparing between a POST reply and a following GET reply?

We need the ability to discard and ignore “stale” GET responses with a cached time from prior to the POST, and without that data, it’s impossible to provide a sane user experience without asking for a complete cache flush on every POST.

**Comment by vthornheart-bng** [comment]
Found and fixed - don't worry about that floatingatoll, the source of the bug was caching that we're doing on the server side.  It'll be fixed up in the next deployment.

**Comment by floatingatoll** [comment]
Excellent!

On Mon, Sep 11, 2017 at 1:48 PM, Vendal Thornheart <notifications@github.com

**Comment by bhollis** [comment]
Note: I don't know if there was a Bungie.net deployment today, but I am still seeing this.

**Comment by vthornheart-bng** [comment]
The deployment won't be until this afternoon - hang tight, this should be fixed soon.
