### ISSUE TITLE
[Question]: Is it possible to get some items details per single query?

### ISSUE THREAD

**Issue by crotaoryx** [Bungie-net/api#801]
Hi! 
I found way to check equipped items and get some base info via manifest, as result i may have list of items with image, name, type, slot etc. Next step is get items perks. i found Destiny2.GetItem in docs, but it seems this endpoint may use one item hash per request, as result for basic char equipment overview i need call Destiny2.GetItem about 10 times. I hope, maybe there is another way to ask items details via single request where i can provide list of hashes? or maybe there is another way to speed up detailed info for some equipped items?

**Comment by vthornheart-bng** [comment]
Greetings!

I think you're in luck - if it's perks you're after, you've got some bulk options available.  If you're looking at a specific character, you can call Destiny2's GetCharacter endpoint, and pass the following components to be requested:

(this is assuming you just care about equipped items):
?components=CharacterEquipment,ItemInstances,ItemPerks,ItemSockets

CharacterEquipment will give you the base information about all of a character's equipped items.

ItemInstances will give you basic information about those equipped item's states (their "primary stat", damage type if relevant, etc...)

ItemPerks will give you a summary of the perks applied to the item, be they intrinsic or derived from the item's sockets.

ItemSockets is a more detailed breakdown of each socket and each inserted plug in the item.  When you look at things like an item's scope, or its Masterwork level, etc... those are all "plugs" inserted into "sockets".

If you want it for all of your characters across the profile, pass the same components in the request but call the "GetProfile" endpoint.

Hopefully this helps!

**Comment by karandashek** [comment]
Awesome!
Thank you very very much!!!! :)

**Comment by crotaoryx** [comment]
Wow! So fast answer! This is exactly what i need! Thanks!

**Comment by vthornheart-bng** [comment]
Sweet, glad to be of help!
