### ISSUE TITLE
Banned acc becouse there was old cheat engine in my task manager!

### ISSUE THREAD

**Issue by Barrery** [Bungie-net/api#806]
My situation, i started the game, went to Mercury planet, than i discovored some freezing fps in the game,
i checked my task manager and there was app called Cheat engine, i killed this procces, also Destiny 2 crashed at the moment, i started game again, played for 15 min and got crash again, than i got banned. I didnt used cheat engine or something, it was in task manager and nothing more!!!
I 100% know that i didnt do anything illegal or used cheats or any of this!!
I AM NOT A CHEATER!
How can i unban this?
Blinky#21881

**Comment by vthornheart-bng** [comment]
Aye, sorry about that - floatingatoll is correct, we have no power to help you with this kind of issue on the API side.  Please do hit them up!
