### ISSUE TITLE
Authorization and Token with postman

### ISSUE THREAD

**Issue by Th3Trickster** [Bungie-net/api#807]
Hello everyone, I've been trying for going on 3 hours now to get a token in postman, does anyone know how to set this up properly in postman?

**Comment by nine13tech** [comment]
The Unofficial Dev Discord would be a better place for this kind of question.
https://discord.gg/dRhPXX

**Comment by vthornheart-bng** [comment]
I'll go ahead and close this one for now under the assumption that you went over there - but if you do need any further help, don't hesitate to ask!  I may not be able to help with specific clients/languages/libraries out in the wild, but if any questions end up relating to the API I can try to assist.
