### ISSUE TITLE
Items maybe not transferable off of uninitialized characters

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#81]
@SunburnedGoose has been told by some users that they had items transferred into alternate characters that they hadn't started, and that from then on they couldn't transfer those items back. I haven't been able to reproduce this, but @vthornheart-bng asked for an issue anyway :-). We have a bug for it in our repo too: https://github.com/DestinyItemManager/DIM/issues/2113.

Possible explanations:

1. They tried to transfer the Traveler's Chosen, which is weirdly not transferable (or lockable!) where the other starting gear is transferable.
2. They were confused by bugs DIM had in transferring items in general (we had their D1 characters in the menu of transfer targets instead of their D2 characters, and that obviously won't work) and it made them believe their item was stuck.
3. Issue #80 may have caused them to believe they couldn't transfer items, since it would make items look like they didn't move.

**Comment by bhollis** [comment]
I confirmed with a friend who had the problem described originally that DIM v4.13.0 fixes the issue and they can transfer off of the uninitialized character. So it was one of the explanations listed above.

**Comment by vthornheart-bng** [comment]
Ah, cool, that's one less thing at least.  ha :)  (I still haven't gone to bed yet, what is wrong with me)
