### ISSUE TITLE
GroupV2.KickMember not Kicking Member

### ISSUE THREAD

**Issue by Javano** [Bungie-net/api#816]
My code used to hit the /GroupV2/{groupId}/Members/{membershipType}/{membershipId}/Kick/ endpoint that was formerly functional no longer works. 

I'm not getting any error responses or anything... it actually seems like it might just be getting intercepted by the /GroupV2/{groupId}/ endpoint instead, and returning my clan info instead of trying to perform the requested kick?

 -- or has the expected implementation changed and the documentation wasn't updated?

**Example target URL:** https://www.bungie.net/Platform/GroupV2/2122734/Members/2/4611686018446405498/Kick/

**Example response:** 
`{"Response":{"group":{"groupId":"2122734","name":"Dab On Them Raiders [PS4]","groupType":1,"membershipIdCreated":"11874370","creationDate":"2017-08-31T03:21:48.85Z","modificationDate":"2018-01-17T17:17:40.304Z","about":"We're a community for finding teams for all of Destiny's end-game activities. \n\nNote: Our clan is not active in these online chat rooms. Please join our clan Discord server to chat/team up with clan-mates! \n\nClan Discord: https://discord.gg/CDSjNgK\n\n--\nTHIS IS THE PS4 PORTION OF OUR CLAN. FOR XBOX OR PC PLAYERS, SEE BELOW:\n- Xbox Clan: https://www.bungie.net/en/ClanV2?groupid=2743007\n- PC Clan: https://www.bungie.net/en/ClanV2?groupid=2743022","tags":[],"memberCount":77,"isPublic":true,"isPublicTopicAdminOnly":false,"motto":"What if the raiders dab back?","allowChat":true,"isDefaultPostPublic":false,"chatSecurity":0,"locale":"en","avatarImageIndex":0,"homepage":0,"membershipOption":1,"defaultPublicity":2,"theme":"Group_Community1","bannerPath":"/img/Themes/Group_Community1/struct_images/group_top_banner.jpg","avatarPath":"/img/profile/avatars/group/defaultGroup.png","conversationId":"27229392","enableInvitationMessagingForAdmins":false,"banExpireDate":"2001-01-01T00:00:00Z","features":{"maximumMembers":100,"maximumMembershipsOfGroupType":1,"capabilities":31,"membershipTypes":[1,2,4,10],"invitePermissionOverride":true,"updateCulturePermissionOverride":true,"hostGuidedGamePermissionOverride":2,"updateBannerPermissionOverride":true,"joinLevel":1},"clanInfo":{"d2ClanProgressions":{"584850370":{"progressionHash":584850370,"dailyProgress":125000,"dailyLimit":0,"weeklyProgress":35000,"weeklyLimit":100000,"currentProgress":125000,"level":2,"levelCap":6,"stepIndex":2,"progressToNextLevel":25000,"nextLevelAt":125000},"1273404180":{"progressionHash":1273404180,"dailyProgress":0,"dailyLimit":0,"weeklyProgress":0,"weeklyLimit":0,"currentProgress":0,"level":1,"levelCap":6,"stepIndex":1,"progressToNextLevel":0,"nextLevelAt":1},"3759191272":{"progressionHash":3759191272,"dailyProgress":0,"dailyLimit":0,"weeklyProgress":0,"weeklyLimit":0,"currentProgress":0,"level":1,"levelCap":6,"stepIndex":1,"progressToNextLevel":0,"nextLevelAt":1},"3381682691":{"progressionHash":3381682691,"dailyProgress":0,"dailyLimit":0,"weeklyProgress":0,"weeklyLimit":0,"currentProgress":0,"level":1,"levelCap":6,"stepIndex":1,"progressToNextLevel":0,"nextLevelAt":1}},"clanCallsign":"RAID","clanBannerData":{"decalId":4175778659,"decalColorId":3362610230,"decalBackgroundColorId":3568748757,"gonfalonId":1473910866,"gonfalonColorId":2140858746,"gonfalonDetailId":1698031297,"gonfalonDetailColorId":4128900502}}},"groupDeleted":false},"ErrorCode":1,"ThrottleSeconds":0,"ErrorStatus":"Success","Message":"Ok","MessageData":{}}`

**Comment by Akumati1435** [comment]
weird. still works for me.

url for me: https://www.bungie.net/platform/GroupV2/3628315/Members/4/4611686018474468942/Kick/
i'm not giving it anything in the body of the request.
I get the same response as in your example.
```
{{
  "Response": {
    "group": {
      "groupId": "3628315",
      "name": "Apexus Deft EU1",
      "groupType": 1,
      "membershipIdCreated": "19097601",
      "creationDate": "2018-11-22T01:06:11.002Z",
      "modificationDate": "2018-11-26T16:52:03.091Z",
      "about": "Welcome to Apexus Deft's first EU Destiny 2 division. \n\nIf you want to join our clan, join the discord first! Read the #recruitment-info section and the rules that link from there, then post in the #request-an-invite-here channel for an invite. \n\nJoin the discord @ discord.gg/apx",
      "tags": [],
      "memberCount": 89,
      "isPublic": true,
      "isPublicTopicAdminOnly": false,
      "motto": "Absolute power corrupts absolutely.",
      "allowChat": true,
      "isDefaultPostPublic": false,
      "chatSecurity": 0,
      "locale": "en",
      "avatarImageIndex": 0,
      "homepage": 0,
      "membershipOption": 0,
      "defaultPublicity": 2,
      "theme": "Group_Community1",
      "bannerPath": "/img/Themes/Group_Community1/struct_images/group_top_banner.jpg",
      "avatarPath": "/img/profile/avatars/group/defaultGroup.png",
      "conversationId": "45654560",
      "enableInvitationMessagingForAdmins": false,
      "banExpireDate": "2001-01-01T00:00:00Z",
      "features": {
        "maximumMembers": 100,
        "maximumMembershipsOfGroupType": 1,
        "capabilities": 31,
        "membershipTypes": [
          1,
          2,
          4,
          10
        ],
        "invitePermissionOverride": true,
        "updateCulturePermissionOverride": true,
        "hostGuidedGamePermissionOverride": 2,
        "updateBannerPermissionOverride": true,
        "joinLevel": 2
      },
      "clanInfo": {
        "d2ClanProgressions": {
          "584850370": {
            "progressionHash": 584850370,
            "dailyProgress": 384000,
            "dailyLimit": 0,
            "weeklyProgress": 84000,
            "weeklyLimit": 100000,
            "currentProgress": 384000,
            "level": 4,
            "levelCap": 6,
            "stepIndex": 4,
            "progressToNextLevel": 34000,
            "nextLevelAt": 125000
          },
          "1273404180": {
            "progressionHash": 1273404180,
            "dailyProgress": 0,
            "dailyLimit": 0,
            "weeklyProgress": 0,
            "weeklyLimit": 0,
            "currentProgress": 0,
            "level": 1,
            "levelCap": 6,
            "stepIndex": 1,
            "progressToNextLevel": 0,
            "nextLevelAt": 1
          },
          "3759191272": {
            "progressionHash": 3759191272,
            "dailyProgress": 0,
            "dailyLimit": 0,
            "weeklyProgress": 0,
            "weeklyLimit": 0,
            "currentProgress": 0,
            "level": 1,
            "levelCap": 6,
            "stepIndex": 1,
            "progressToNextLevel": 0,
            "nextLevelAt": 1
          },
          "3381682691": {
            "progressionHash": 3381682691,
            "dailyProgress": 0,
            "dailyLimit": 0,
            "weeklyProgress": 0,
            "weeklyLimit": 0,
            "currentProgress": 0,
            "level": 1,
            "levelCap": 6,
            "stepIndex": 1,
            "progressToNextLevel": 0,
            "nextLevelAt": 1
          }
        },
        "clanCallsign": "AXEU",
        "clanBannerData": {
          "decalId": 4175778658,
          "decalColorId": 3379387794,
          "decalBackgroundColorId": 3568748758,
          "gonfalonId": 1473910866,
          "gonfalonColorId": 2157636320,
          "gonfalonDetailId": 1664476154,
          "gonfalonDetailColorId": 4128900500
        }
      }
    },
    "groupDeleted": false
  },
  "ErrorCode": 1,
  "ThrottleSeconds": 0,
  "ErrorStatus": "Success",
  "Message": "Ok",
  "MessageData": {}
}}
```
and now bendyback is now clanless:
![image](https://user-images.githubusercontent.com/7931231/50185890-f4cae680-02cd-11e9-8692-8390d0c7bf46.png)


seems to work as intended for me!

**Comment by floatingatoll** [comment]
This seems like a good time to remind everyone having trouble to log and include here the bungled cookie value from any response that isn’t right.

**Comment by Javano** [comment]
Alright, odd that it'd just stop working without any code changes -- but I guess it must be something on my end then. 

Apologies.

**Comment by floatingatoll** [comment]
Don’t give up hope - sometimes there’s backend issues affecting specific clans, players, accounts, etc.
