### ISSUE TITLE
Scourge of the Past Milestone has the wrong image.

### ISSUE THREAD

**Issue by JpDeathBlade** [Bungie-net/api#818]
The new Raid Lair Milestone, Scourge of the Past (1342567285) is using the wrong image. The current image attached to it is from Spire of Stars. It's also the only raid with a different description.

**Comment by t3rr11** [comment]
I would also like to mention in the "DestinyActivityDefinition" under the ActivityHash 548750096 for the Scourge of the Past raid. The pgcrImage value returns: `"pgcrImage":"raids.1305rh0093145r13t5hn10tnz.raid_sunset.jpg"`

**Comment by vthornheart-bng** [comment]
Thanks for the info!  I'll take a peek.

**Comment by t3rr11** [comment]
Any update on this @vthornheart-bng ? The `activityHash: 548750096` for the Scourge of the Past raid still returns the image: '/img/destiny_content/pgcr/raids.1305rh0093145r13t5hn10tnz.raid_sunset.jpg'?

**Comment by vthornheart-bng** [comment]
Ah, glad you pinged this!  We fixed this up a while ago, but I neglected to close this issue.

Give it a try:

http://www.bungie.net/img/destiny_content/pgcr/raids.1305rh0093145r13t5hn10tnz.raid_sunset.jpg
