### ISSUE TITLE
Possible to increase recently obtained collectibles to 10-12?

### ISSUE THREAD

**Issue by t3rr11** [Bungie-net/api#819]
Would it be possible to show more than the 6 most recently obtained collectibles? When you call `json.Response.profileCollectibles.data.recentCollectibleHashes` from the profile endpoint. It will grab the last 6 collectibles. Which it should obviously it only displays 6 in the games collectible tab. But i was wondering if it could be extended to the last 10 or even 12?

**Comment by vthornheart-bng** [comment]
Unfortunately, the only source we have for this information is the same one as the game - so if the game's only storing information on the most recent six, so too do we. :(

There's not much we can do about this one, so I'm going to go ahead and close it up for now - sorry about that!

**Comment by t3rr11** [comment]
No worries man, completely understandable!

**Comment by t3rr11** [comment]
Just adding a comment just in-case any sees this in the future. As of lightfall it has been raised to 12 collectibles! Woohoo!

![image](https://user-images.githubusercontent.com/2139233/222900307-d2d2bb53-bf31-4436-98ad-2c92d580ae93.png)

**Comment by t3rr11** [comment]
Looks like in the API it has now been raised to 35 items! Not sure when this change was done, just looping back on the thread.
