### ISSUE TITLE
Ikora's missing meditations

### ISSUE THREAD

**Issue by mrphlip** [Bungie-net/api#82]
In the response for `Destiny2/Milestones/`, the section for the Meditations only includes one of the three missions that Ikora is offering this week... is that intended? Or an oversight?

Is it maybe that only one of them is "public" and the other two are restricted to logged-in users for some reason? But I don't see a personal version of the milestones api, just the public one.

Or maybe will we be able to get the other meditation options from Ikora's vendor data, when the vendor api becomes available?

**Comment by br-steph** [comment]
Same for me. I also one of the three missions's that Ikora is offering this week.

When the vendor api becomes available?

**Comment by vthornheart-bng** [comment]
Hmm, I'll have to look into that.  Did you already pick a milestone to play?  Once you've picked one, it will show only the one that you picked if I recall correctly.

The Vendor API is TBD, I don't have a reliable timeframe to share for when it will be functional again - but if you have further questions let's talk about that in a new/different issue so we don't muddy this one with an unrelated conversation.

**Comment by br-steph** [comment]
As @mrphlip says, it is a public element, not related at the character ID. 

Please fine output milestone for ikora's meditation :
`"3245985898": {
            "milestoneHash": 3245985898,
            "availableQuests": [
                {
                    "questItemHash": 4291922223,
                    "activity": {
                        "activityHash": 4291922223,
                        "variants": [
                            {
                                "activityHash": 4291922223
                            }
                        ]
                    }
                }
            ]
        }`

Ok for the other question about vendor API.

Thanks @vthornheart-bng !

**Comment by vthornheart-bng** [comment]
Ah, this should be coming through now!
