### ISSUE TITLE
GroupV2.IndividualGroupInvite broken?

### ISSUE THREAD

**Issue by Arrorr** [Bungie-net/api#825]
Since the last server maintenance I'm experiencing an issue with the GroupV2.IndividualGroupInvite endpoint. Whenever I'm trying to use it i get en ErrorCode : 12 in the response body saying that i have Insufficient Privileges althought endpoints like GroupV2.GetInvitedIndividuals , which require the same privileges work fine for me. This error occured as of yesterday after the maintenance ended.

Can anyone confirm if they are experiencing the same issue.

**Comment by richard4339** [comment]
Works perfectly for me.

**Comment by Arrorr** [comment]
Thanks for the feedback Richard.
I looked into it again and found that, if i let users undergo the OAuth process again, the token i get out of this will allow me to user the endpoin again, even though the "old" one weren't expired yet.

**Comment by richard4339** [comment]
Yeah, I did have to re-authenticate. If all oauth tokens are invalidated during server maintenance I’d think you’d get a 401 error though honestly.

**Comment by floatingatoll** [comment]
That's very interesting. I hope Thorn chimes in to let us know what was up!
