### ISSUE TITLE
gendered*ByGenderHash not populated

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#827]
https://github.com/Bungie-net/api/issues/77 says that these new `genderedClassNamesByGenderHash` and `genderedRaceNamesByGenderHash` properties should be available as of 12/11, but they do not appear in the manifest definitions for races/classes.

An example: https://data.destinysets.com/i/Race:898834093

**Comment by vthornheart-bng** [comment]
Hmm, I'm going to have to investigate: perhaps it ended up in the wrong branch and wasn't deployed.  I'm going to close this one and reopen the other one.
