### ISSUE TITLE
Destiny2CoreSettings not populating currentRankProgressionHashes

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#828]
The [`Destiny2CoreSettings`](https://bungie-net.github.io/multi/schema_Common-Models-Destiny2CoreSettings.html#schema_Common-Models-Destiny2CoreSettings) type says that there should be a `currentRankProgressionHashes` property, but the `GetCommonSettings` API doesn't really return them.

See https://github.com/Bungie-net/api/issues/805.

**Comment by vthornheart-bng** [comment]
Hmm, yep.  I get the feeling some of these issues didn't actually make it out to production.  I'll do the same I did with the other one, and reopen it until then.
