### ISSUE TITLE
Missing description for Mods

### ISSUE THREAD

**Issue by lax20attack** [Bungie-net/api#83]
Sample Hash: -1021424895  (3273542401)

`
"displayProperties": {
    "description": "",
    "name": "Solar Paragon Mod",
    "icon": "\/common\/destiny2_content\/icons\/98e11095021986e131c9210653bcf2b9.jpg",
    "hasIcon": true
  },
`

In Game text:
Class abilities recharge faster when using Solar subclasses.

**Comment by lax20attack** [comment]
Looks like it's in the perks object in InventoryItem definition!

**Comment by vthornheart-bng** [comment]
Sweet, glad you found it!
