### ISSUE TITLE
Stats UniqueWeapons returning empty results set

### ISSUE THREAD

**Issue by vpzed** [Bungie-net/api#84]
Like in Issue #79 the /Stats/UniqueWeapons/ endpoint is also returning empty results.  Are there query parameters required that aren't in the docs?

 ```/Destiny2/1/Account/4611686018452884034/Character/2305843009261882532/Stats/UniqueWeapons/```

    {
    "Response": {},
    "ErrorCode": 1,
    "ThrottleSeconds": 0,
    "ErrorStatus": "Success",
    "Message": "Ok",
    "MessageData": {}
    }

**Comment by vthornheart-bng** [comment]
Hmm, I'll give this a look while I'm looking into stats issues.

**Comment by Tetron-bng** [comment]
This is fixed!
