### ISSUE TITLE
Redundant "all" value in flag enums

### ISSUE THREAD

**Issue by arshakoor** [Bungie-net/api#842]
Each of the enums in Destiny.Definitions.DestinyTalentNodeStep* have an "all" value which is redundant for a flag enum, is this just to make life a little bit easier as an alternative to listing 14 different values at once? I would imagine this would throw off a few generators.

**Comment by vthornheart-bng** [comment]
Aye, it's as intended - if you check the binary value, the value is equal to the other defined bit fields set to 1, which should work just fine if you're treating it as a flags enumeration!
