### ISSUE TITLE
Getting power level of an armor piece

### ISSUE THREAD

**Issue by kjverble** [Bungie-net/api#843]
Hello,

I'm looking for how to get the power level of an armor piece that's on a character. I currently have code to list out the armor pieces and list their perks. I wanted to add the power level of each piece to that list. I started down the road of getting the ItemStats for an instanced item. Then getting the StatDefinition for that. It only shows me definitions for mobility, resilience and recovery. So I guess I'm lost a bit and looking for some hints.

Thanks,
Kevin

**Comment by joshhunt** [comment]
Generically, the name of the power level is called 'primaryStat'. 

You'll want to request component ItemInstances (300) from GetProfile, then you'll find the power level under `response.itemComponents.instances.data[itemInstanceId].primaryStat.value`


For reference, here is the data for my 642 Wright Side of Wrong:

```
    "itemComponents": {
      "instances": {
        "data": {
          "6917529074392146711": {
            "damageType": 1,
            "damageTypeHash": 3373582085,
            "primaryStat": {
              "statHash": 1480404414,
              "value": 642,
              "maximumValue": 0
            },
            "itemLevel": 64,
            "quality": 2,
            "isEquipped": true,
            "canEquip": true,
            "equipRequiredLevel": 50,
            "unlockHashesRequiredToEquip": [
              2166136261
            ],
            "cannotEquipReason": 0
          },
```

**Comment by kjverble** [comment]
Thanks. That's what I need.

**Comment by vthornheart-bng** [comment]
Ah, I'm going back through posts I missed now - looks like you're set on this one, good stuff!
