### ISSUE TITLE
No HistoricalStatDefinition for the 'Ghost in the Night' medal

### ISSUE THREAD

**Issue by lyrad87** [Bungie-net/api#850]
Hello,

I'm trying to find the 'Ghost in the Night' medal but I can't find it anywhere. All I could find is a hashId for the triumph (see [https://www.light.gg/db/legend/triumphs/3882642308/ghost-in-the-night/](https://www.light.gg/db/legend/triumphs/3882642308/ghost-in-the-night/)).

Could you please add it to the HistoricalStatDefinition or show me where else it may be? Thanks in advance!

By the way, the medal doesn't appear in the PGCR either. Here is an example: the player "x_MadMackie_x" got the medal/triumph in this game [ https://destinytracker.com/d2/pgcr/3043356538]( https://destinytracker.com/d2/pgcr/3043356538) or [https://youtu.be/OFNvj0ypDmk?t=124](https://youtu.be/OFNvj0ypDmk?t=124).

**Comment by vthornheart-bng** [comment]
Looping back to this, it looks like there's a whole set of new medals that aren't being exposed by the API yet.  I'll see if we can get that out for the end of January release - thanks for the heads up!

**Comment by justrealmilk** [comment]
`Medals_pvp_medal_streak_no_damage` (Ghost in the Night) is now apart of `DestinyHistoricalStatsDefinition` - presumably this holds true for other related medals and this issue is now resolved

**Comment by vthornheart-bng** [comment]
Sweet, thank you!
