### ISSUE TITLE
Rare Weekly Bounty for Scourge of the Past not being returned from getVendors

### ISSUE THREAD

**Issue by xenodus** [Bungie-net/api#858]
I'm able to get Last Wish's weekly bounty, "Forever Fight" but not Scourge of the Past's "Hold the Line" from getVendors.

Edit: I'm able to obtain Scourge of the Past's rare weekly bounty as well as clan bounties through the api only when I'm logged into the game.

**Comment by vthornheart-bng** [comment]
Hmm, I'm going to need to look into this.  I hope that it's not a similar problem to what we saw with Petra Venj.  If it is, I may not be able to resolve it - the underlying issue leaves the API at the mercy of the game designers.

**Comment by xenodus** [comment]
Looks like this has been fixed in update 2.2.0 😄

**Comment by vthornheart-bng** [comment]
Sweet!
