### ISSUE TITLE
January deployment moved out to 01/29

### ISSUE THREAD

**Issue by vthornheart-bng** [Bungie-net/api#862]
Just a heads up folks: we were planning for a 1/22 deployment of BNet, but with the impending game deployment on 1/29 it didn't make sense to ramp both deployments up.  We're going to have our deployment on the 29th of this month.  I'll keep you all posted if the situation changes!

**Comment by serkanbal** [comment]
Thanks for the info @vthornheart-bng. 

Is the public Xur API endpoint (https://github.com/Bungie-net/api/issues/502) also planned to release on the 29th?

**Comment by vthornheart-bng** [comment]
Yes indeed, albeit in "beta" form.  Internal tests for it have looked good so far, but I am still unsure of its performance characteristics when it hits production.
