### ISSUE TITLE
Can no longer link enum definitions.

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#865]
In the latest update of openapi-2.json, all of the enum references were removed. I suspect this was part of #148 (which I hadn't seen the discussion for), but there's no corresponding `x-enum-reference` in the document, so I can no longer link those fields to their definitions. This greatly reduces the ability of my [`bungie-api-ts`](https://github.com/DestinyItemManager/bungie-api-ts) generator (used in DIM) to build good types from the API docs.

**Comment by vthornheart-bng** [comment]
Ah, good call - I'd fixed the open API 3.0 spec, but not the 2.0 spec.  I'll see about getting x-enum-reference as an extension property in 2.0 as well.

**Comment by vthornheart-bng** [comment]
That one's easy enough to fix and has a separate deployment from the normal builds, so I went ahead and changed it up.  I should have new specs posted shortly!
