### ISSUE TITLE
What are the boss phase indexes in the raids?

### ISSUE THREAD

**Issue by SarKurd** [Bungie-net/api#866]
I'd like to do some changes to my app based on the `theStartingPhaseIndex` in PGCR

is there a way to know how many phases a raid has in the API and which one is for the boss?

**Comment by vthornheart-bng** [comment]
Sort of for the former - insertionPoints is the best we've got for phases, but unfortunately it has no human readable information.  You'll have to associate those "phase hashes" with your own string data manually.

For the latter - which one has the boss - we unfortunately don't have any data about that. :(

**Comment by SarKurd** [comment]
Thanks for the reply

**Comment by vthornheart-bng** [comment]
No prob!
