### ISSUE TITLE
Authenticated via OAuth and switching an API Key accidentally.

### ISSUE THREAD

**Issue by nine13tech** [Bungie-net/api#871]
So I ran across a wierdo problem. I was running 90% of the data collection via the production API, but for some reason when the background refresh was requested by the user, the function used the dev API key, resulting in an error being logged that the user had to sign in... BUT THEY WERE! and it was passing their auth token.
took me a week.
Find I had this one function using the development key. So, if you use the wrong API key on the call other than authenticated, you get the same error as if they were not signed in.

Add a note in the documentation? Maybe a bug to give a better error return? Or none of the above - all cool.
just thought I would point out something that was not obvious.
also - I know the error was all my fault, but I did create logic to pick the API key according to the environment variable for prod vs dev.
 All Bungie OAuth works as intended and securely. (thanks guys!)
9er

**Comment by Tetron-bng** [comment]
The access token is linked to the API key to which it was issued.  The process of validating the access token among other things verifies that the API key in the request matches the access token in the request.  The process results in the token either being valid or not being valid.  There is probably not much harm in letting you know WHY it is invalid (expired, wrong API key, etc) but in security related validation it is common to not give a potential attacker clues as to why his attack is failing.

**Comment by nine13tech** [comment]
Excellent explanation and as I said, the API is working as intended!
