### ISSUE TITLE
Is there a way to pull pvp kills with an exotic weapon that does not have a kill tracker on it?

### ISSUE THREAD

**Issue by corsak23** [Bungie-net/api#872]
Basically the title. I want to know how many kills any given clan mate has with a specific exotic, say Ace of Spades. I've pulled my stats but the numbers seem off. I'm thinking its counting pve and pvp kills.  Not really sure.

**Comment by floatingatoll** [comment]
AFAIK, the only mechanisms available for weapon kill tracking are
those that you're familiar with from inspecting your own items. If the
in-game counter matches the counter you see in the official companion
app, then the API is faithfully reporting the best data available to
it and you'll need to ask your question of Bungie Feedback.

Note, IIRC, that exotics are locked to the Vanguard counter and will
not track Crucible kills at all.

**Comment by Akumati1435** [comment]
Yes. I did this with my play of the game before ranting about how bad they've made grenade launchers since the patch.

Step 1:  Find the weapon id's from the manifest.
Step 2:  Query the API for activity that matches whatever you're searching for.   AKA, if you just want PVP kills put an AllPvP filter on your api call.
Step 3: Grab the post game carnage reports for every single game in there.  In the extended section it lists the weapon IDs and the number of kills you have with each one.

Mine is in c#.  I have the activity history for everyone in my clan in my database.  I grabbed my own activity history and ran this code:

```
foreach (var actId in pvpMatches)
                {
                    int kills = api.GetPGCRKillsForWeaponID(actId, 4611686018471051377, 195440257);
                    datas.Add(new ActIdKills() { ActId = actId, Kills = kills });
                }
                var TotalKills = datas.Sum(o => o.Kills);
```


```
  public int GetPGCRKillsForWeaponID(long activityId, long memberId, long weaponId)
        {
            //play of the game = 195440257
            dynamic apiResponse = GetPGCR(activityId + "");
            string deserialized= JsonConvert.SerializeObject(apiResponse);
            try
            {
                JObject jo = JObject.Parse(deserialized);
                var PlayerInfo = jo.Descendants().OfType<JProperty>()
                                   .Where(o => o.Name == "membershipId" && o.Value.ToString() == ""+memberId)
                                   .Select(o => o.Parent.Parent.Parent.Parent.Parent).Single();
                //does it contain kills for this weapon?
                var weaponsSection = PlayerInfo["extended"]["weapons"];
                if (weaponsSection != null)
                {
                    foreach (var weapon in weaponsSection)
                    {
                        if (weapon["referenceId"].Value<long>() == weaponId)
                        {
                            return weapon["values"]["uniqueWeaponKills"]["basic"]["value"].Value<int>();
                        }
                    }
                }
                return 0;

              
            }
            catch (Exception e)
            {
                Log.getInstance().Error("GetPGCRKillsForWeaponID: Failed to get member id from XML.", e);
                Log.getInstance().Debug("GetPGCRKillsForWeaponID" + apiResponse);
                throw e;
            }


        }
```

**Comment by ats** [comment]
I do something similar, but only for my own stats: I periodically fetch my new PGCRs into json files, and then I have a fish shell function that produces summarized output using `jq`:

```fish
for f in *.txt
    cat $f | jq  ' try( .Response.period as $date | .Response.activityDetails.instanceId as $eventId | .Response.activityDetails.mode as $mode | .Response.entries[] | .player.destinyUserInfo.displayName as $name | .characterId as $charId  | .extended.weapons[] | .referenceId as $weaponId  |  .values.uniqueWeaponKills.basic.value as $kills | { eventId: $eventId, date: $date, mode: $mode, name: $name, charId: $charId, weaponId: $weaponId, kills: $kills  } ) ' | jq -r 'to_entries|map(.value)|@tsv'
    end
end
```

I pipe that into more command line filters to search for a specific game mode or specific weapon, for example to make summaries like my season 3 round-up of top 20 weapons:

```
|       PVE         |  n   |               PVP                |  n  |
|-------------------|------|----------------------------------|-----|
|      Sunshot      | 2408 |          Vigilance Wing          | 325 |
|      Crimson      | 1763 |         The Jade Rabbit          | 251 |
|   Origin Story    | 1199 |             Crimson              | 188 |
|     Valakadyn     | 1193 |            Valakadyn             | 120 |
|   True Prophecy   | 1024 |            Kibou AR3             | 116 |
|   Polaris Lance   | 852  |         Perfect Paradox          | 63  |
|  Niflheim Frost   | 822  |         Positive Outlook         | 62  |
|    Vacuna SR4     | 715  |         Main Ingredient          | 56  |
| IKELOS_HC_v1.0.1  | 613  |       The Time-Worn Spire        | 39  |
|    Conspirator    | 522  |            The Vision            | 37  |
|  Perfect Paradox  | 443  |            Vacuna SR4            | 33  |
|     Kibou AR3     | 442  |           Proelium FR3           | 28  |
|   Better Devils   | 392  |         Sins of the Past         | 25  |
| Positive Outlook  | 355  |         Legend of Acrius         | 23  |
|   Machina Dei 4   | 333  | Hawthorne's Field-Forged Shotgun | 22  |
| Sins of the Past  | 244  |           Manannan SR4           | 18  |
| Inaugural Address | 200  |       Stochastic Variable        | 18  |
| Nameless Midnight | 170  |          Retrofuturist           | 15  |
| Skyburner's Oath  | 170  |           Conspirator            | 13  |
|  The Conqueror 2  | 156  |         Magnum Shepherd          | 13  |
```

**Comment by vthornheart-bng** [comment]
Aye, it's a bit of a pain but this is indeed the best way to do so: we don't have a better alternative for you at the moment.  I hope this works!

**Comment by APNPAPNU** [comment]
> I do something similar, but only for my own stats: I periodically fetch my new PGCRs into json files, and then I have a fish shell function that produces summarized output using `jq`:
> 
> ```fish
> for f in *.txt
>     cat $f | jq  ' try( .Response.period as $date | .Response.activityDetails.instanceId as $eventId | .Response.activityDetails.mode as $mode | .Response.entries[] | .player.destinyUserInfo.displayName as $name | .characterId as $charId  | .extended.weapons[] | .referenceId as $weaponId  |  .values.uniqueWeaponKills.basic.value as $kills | { eventId: $eventId, date: $date, mode: $mode, name: $name, charId: $charId, weaponId: $weaponId, kills: $kills  } ) ' | jq -r 'to_entries|map(.value)|@tsv'
>     end
> end
> ```
> 
> I pipe that into more command line filters to search for a specific game mode or specific weapon, for example to make summaries like my season 3 round-up of top 20 weapons:
> 
> ```
> |       PVE         |  n   |               PVP                |  n  |
> |-------------------|------|----------------------------------|-----|
> |      Sunshot      | 2408 |          Vigilance Wing          | 325 |
> |      Crimson      | 1763 |         The Jade Rabbit          | 251 |
> |   Origin Story    | 1199 |             Crimson              | 188 |
> |     Valakadyn     | 1193 |            Valakadyn             | 120 |
> |   True Prophecy   | 1024 |            Kibou AR3             | 116 |
> |   Polaris Lance   | 852  |         Perfect Paradox          | 63  |
> |  Niflheim Frost   | 822  |         Positive Outlook         | 62  |
> |    Vacuna SR4     | 715  |         Main Ingredient          | 56  |
> | IKELOS_HC_v1.0.1  | 613  |       The Time-Worn Spire        | 39  |
> |    Conspirator    | 522  |            The Vision            | 37  |
> |  Perfect Paradox  | 443  |            Vacuna SR4            | 33  |
> |     Kibou AR3     | 442  |           Proelium FR3           | 28  |
> |   Better Devils   | 392  |         Sins of the Past         | 25  |
> | Positive Outlook  | 355  |         Legend of Acrius         | 23  |
> |   Machina Dei 4   | 333  | Hawthorne's Field-Forged Shotgun | 22  |
> | Sins of the Past  | 244  |           Manannan SR4           | 18  |
> | Inaugural Address | 200  |       Stochastic Variable        | 18  |
> | Nameless Midnight | 170  |          Retrofuturist           | 15  |
> | Skyburner's Oath  | 170  |           Conspirator            | 13  |
> |  The Conqueror 2  | 156  |         Magnum Shepherd          | 13  |
> ```
> 
> I can grep those json files for date ranges and do just about anything with them to find specific output, like all kills from an Iron Banner during season 5, for example, or all kills with a specific weapon ID. It's pretty fun.

would you mind to do this for me and share the source files?
