### ISSUE TITLE
openapi-2.json not compliant with swagger, enum types in java SDK codegen not producing correctly

### ISSUE THREAD

**Issue by ROMVoid95** [Bungie-net/api#873]
This is more of a language spesific isssue, there is a severe lack of java api support/wrappers that are current. Being able too correctly generate a java api client for apps would be a godsend for time. Unless there is something i am just missing in terms of generating the code.

Attached a .txt with the current errors if it helps.
[swaggerErrors.txt](https://github.com/Bungie-net/api/files/2852165/swaggerErrors.txt)

**Comment by nine13tech** [comment]
If I remember correctly and unless something changed, the Swagger API is only for documentation right now. I abandoned it almost a year ago.

**Comment by ROMVoid95** [comment]
here's to hoping something changed. I can't exxactly put time aside to learn an entire code from the start just to access a current API Wrapper lol oohh well

**Comment by vthornheart-bng** [comment]
Aye, unfortunately we don't have a lot of time to prioritize the swagger spec right now - but this error file is very helpful, I appreciate it!  I'm going to file a bug specifically for these, as they give some concrete examples of the way that parsers are failing.  That's super helpful, thank you!

**Comment by vthornheart-bng** [comment]
TFS 765582

**Comment by ROMVoid95** [comment]
Closing this as the current openapi 3.0.0 spec passes client/server generation with a change to the GroupV2 `currentPage` parameter being changed to query as it is not defined in the path. Wonderful work y'all have done!
