### ISSUE TITLE
API Request: Add damage to carnage report endpoint for PVP

### ISSUE THREAD

**Issue by l2osati** [Bungie-net/api#874]
It would be great if the carnage report endpoint included damage per person. It seems like this should be possible since Damage shows up in some of the playlist match results. Cheers!

**Comment by BlazeBoss17** [comment]
We need it in PvE pgcr  first haha

**Comment by vthornheart-bng** [comment]
I'll ask the wizard!

**Comment by gossnj** [comment]
Think this is still relevant and would be wonderful - total damage done is a key metric to track in terms of improvement as a player (KD/KDA less reflective over time due to matchmaking variability).
