### ISSUE TITLE
Invalid PGCR JSONs Being Returned

### ISSUE THREAD

**Issue by BlazeBoss17** [Bungie-net/api#877]
I've been tracking a particularly nasty bug for the last few months. After a long investigation, I found the root cause is the API returning invalid postgame JSONs. 

There are a few different cases that this behavior can take:
1. The 'entries' player array changes length
On initial fetch of a postgame, not all the players are included in the entries array. Below are two different responses I revived for the same instanceId, one fetched soon after the activity completed and one 48 hours later.
-[3492333886 - original](https://textuploader.com/15dck)
-[3492333886 - 48 hours later](https://textuploader.com/15dc6)
In this example, the original JSON has 2 players while the other JSON has 6 players. Notably, playerCount is 6 for the JSON with 2 entries.
Examples: 1674614872, 2960997993, 3070610442, 3130887491, 3345212392, 3473497928. 

2. startingPhaseIndex changes
On initial fetch of a postgame, startingPhaseIndex does not exist at all in the JSON. On subsequent calls, startingPhaseIndex is properly populated
-[3651902391  - original](https://textuploader.com/15tkq)
Examples: 2857760460, 3043584026, 3123064534, 3374106161, 3418190856

3. startingPhaseIndex never gets populated
Somewhere a long time ago you mentioned startingPhaseIndex is a nullable field, but it is so rare that it seems like a bug to me.
Examples: 2071823505, 2071918551, 2071920588, 2071920628, 2071920266, 2087428368, 3354393990

This issue has dramatic consequences for our database, frequently causing major issues for us. Examples include 6 man raids reporting as solos, completed raids looking incomplete, full raids looking like checkpoints, etc. Right now so much of our data is corrupted I gave up on trying to fix it manually until a fix is found. And I'm sure this issue is affecting other apps as well.

**Comment by vthornheart-bng** [comment]
Good info, thank you!  I'll bring this up to some folks and see if we can find out more.
