### ISSUE TITLE
Query - Shader Colors

### ISSUE THREAD

**Issue by nine13tech** [Bungie-net/api#878]
Maybe this is a no brainer... maybe not.
Is there a way to get the RGB/T values of the 4 colors in a shader? I can't seem to find any of the dyeHash listings, and there is only a BG color, but being that a shader is just 4 colors, can we not get those RGB/T values passed or listed in the manifest description of the shader? 
Alternatively, I could pull the colors from specific pixels in the icon, but that seems kinda overkill if the data is in the API/Manifest (but I don't seem to be able to find it)...

Thanks,
9er

EDIT: I know that some of these are pattern images - such as TigerStripe, or the Carbon Fiber patterns. Maybe this is better as 4 PNGs with the colors.

**Comment by justrealmilk** [comment]
It'd be awesome to have easy access to this

**Comment by joshhunt** [comment]
AFAIK Shaders arent just simply 4 RGB colours. Ignoring shader shaders (like, animated shaders that are(?) graphics shaders), shaders are four 'textures'/images that are applied to parts of gear.

@lowlines this should be possible, at least to programmatically extract colours from the shader textures, no?

**Comment by lowlines** [comment]
At a high level yes, but then you also have material info and stuff. Like say you wanted to get the color of something that is gold, the raw color value would be puke color, so I'm not sure how useful that'd be. It'd maybe be more useful to generate renders of each shader similar to like how 3d editors do it.
![mpe3d_03-1171x605](https://user-images.githubusercontent.com/4862548/53421507-478af200-3a25-11e9-81c8-1d7d9e8ec3a2.jpg)

**Comment by nine13tech** [comment]
So I can see a number of applications with this. 
1) raw color for text/block color pallets
2) swatches for background images
From a performance viewpoint, I don't think it is cost effective to generate on the fly a web color palette from a shader. :( we've been bouncing the ideas around to pull a pixel's RGB values for a basic swatch then using the texture layering guides that Tom posted from his PPT about shader rebuilds assign primary vs complimentary colors.
It's possible for the metallic (vex chrome) and swatch based pattern (anything with carbon fiber or Artic Deamscape with its urban snow camo) inclusive shaders we would have to prebuild a swatch for and store it with some mapping to the swatch. Storing them in the static folder in 92x92 pixel swatches.

**Comment by vthornheart-bng** [comment]
I'll pass this along to some of the folks who worked on the 3d asset pipeline and see if they can chime in, as I'm pretty much entirely ignorant of this part of the system!
