### ISSUE TITLE
Discrepancy between Mobility 11 in API and (capped at 10) in-game

### ISSUE THREAD

**Issue by floatingatoll** [Bungie-net/api#879]
https://www.bungie.net/en/Gear/2/4611686018442199406/2305843009266733136

When I equip all Mobility gear, with all Mobility mods, I can reach Mobility 11 in the API, as shown both in third-party apps and on the Bungie.net website at that precise URL — but in-game it still shows Mobility 10 on my TV screen. Discrepancy noted.

**Comment by justrealmilk** [comment]
could this be similarly due to runtime scripts as it is with cases like weapon magazine size and other stats?

**Comment by vthornheart-bng** [comment]
Hmm, yucky.  My hope is that there's just an upper threshold cutoff that we're not honoring in the API.  I'll be very sad if it's yet another runtime script issue.  I'll need to look into this.

**Comment by vthornheart-bng** [comment]
TFS 765615
