### ISSUE TITLE
Get in-game "login messages"

### ISSUE THREAD

**Issue by ghost** [Bungie-net/api#880]
Hey! Is there a way to get the in-game "[login messages](https://mobile.twitter.com/A_dmg04/status/1096510680029573120)" via the API? They appear before Character Selection in-game. As dmg04 tweeted this might be a more regular thing in the future (and since the announcement, there have been 4 or 5 of these popups!), and I think it would be a great to have a way to get this via the API to display it on websites/post it to reddit.

Thanks!

**Comment by vthornheart-bng** [comment]
An interesting idea!  I am not 100% sure it's possible, but let me look into it!

**Comment by Akumati1435** [comment]
Agreed.  I could post that in my discord's news section!

**Comment by justrealmilk** [comment]
I could feed it directly to Braytech's homepage 👀

**Comment by kramrm** [comment]
Not just the message, but the graphic that goes with it too.
