### ISSUE TITLE
Weapon Perk Bug

### ISSUE THREAD

**Issue by t3rr11** [Bungie-net/api#881]
So i have a friend who managed to get a Crimil's Dagger with Rangefinder and Opening Shot. The bug is when you look at the API side. Where it shows Outlaw and Zen moment. 

Mbm_ID: 4611686018467731418
Char: 2305843009306194135
Crimil's Dagger Item ID: 6917529086234969060

I've provided screenshots of how it looks ingame, In the inventory it shows Outlaw - Zen Moment then in the examine it shows Rangefinder and Opening Shot.

Edit: Uploaded the wrong photo.

Inventory: 
![Inventory](https://user-images.githubusercontent.com/2139233/54068526-98a8aa80-429d-11e9-8750-d1d17ce67978.png)

Inspecting: 
![Inspecting](https://user-images.githubusercontent.com/2139233/54068579-677caa00-429e-11e9-8048-b637130e306f.png)

**Comment by justrealmilk** [comment]
Inspect view appears to display collection's roll

**Comment by t3rr11** [comment]
A didn't save a Crimil's Dagger to check my own, Does yours show the same or do you think it might just be a bugged weaponID?

**Comment by vthornheart-bng** [comment]
To get clarification on what I'm seeing in the screenshot and how it corresponds to the API, is both the API data and the game's pop-up dialog showing the wrong data compared to what you see when you inspect it?

When you actually use this item in-game, which of those two sets of perks actually are in effect?  This will help for me to bring that data to folks for further investigation, as it looks to me like the game itself is as confused about it as the API is!

**Comment by t3rr11** [comment]
When used in game it has Outlaw, Zen Moment. The same as it has in the API. But when inspecting the weapon it has Opening Shot and Rangefinder. 

After testing this weapon in PvP against my Opening Shot Crimils Dragger, At 15 meters I was hitting 91 to the head and he was hitting 82. Proving that his one is only using Outlaw and Zen Moment.

So it looks like the ingame inspect is showing the wrong data but not giving the weapon those perks. (which is good) but also confusing.

Another thing i have noticed is that they don't have a blue highlight around the icons in the inspect. So i got him to click them and the weapon changed from Zen Moment, Outlaw to Opening Shot, Rangefinder. 

We tested to see if Outlaw and Zen moment, Persisted. They do not and Then we tested the new perks and he indeed has Opening shot, Rangefinder.

Now taking another look at the API Item. It has changed from Outlaw Zen Moment, To Opening shot, Rangefinder.

**Comment by vthornheart-bng** [comment]
Huh, that is a very confusing situation.  It sounds like this issue may be on the game side, let me bubble it up to someone who might be able to take a closer look.

**Comment by t3rr11** [comment]
No worries! Thanks!

**Comment by floatingatoll** [comment]
Does your friend have two Crimil’s Daggers on the same character or in the vault, where the two Daggers between them have the described perks showing in some form?

**Comment by vthornheart-bng** [comment]
Oooh, floatingatoll has a point: that could indeed be what you're seeing and is definitely worth checking if you have the opportunity to do so.

Let me know.

**Comment by t3rr11** [comment]
No he has another 2 in the vault. Those have: (Triple tap, Zen) and (Kill clip, Snapshot). The one we tested was the only one he had with Outlaw, Zen and Opening Shot and Rangefinder.

**Comment by vthornheart-bng** [comment]
Ah, okay, here's the situation, from Bungie Support (https://www.bungie.net/en/Help/Article/46168#Drifter):

"Iron Banner Rolls: We are investigating reports regarding an issue where some Iron Banner weapons may have re-rolled perks after Update 2.2.0."

It is indeed a known issue, and happening game-side rather than in the API.  Keep tabs on the Bungie Support communication channels for more info on it if/when more info becomes available!  Sorry there's not more I can do!

**Comment by t3rr11** [comment]
Easy, this post was out before that post. But i'm glad it's known about! Thanks for the help guys!

**Comment by vthornheart-bng** [comment]
Ah, good stuff!  Yeah, it was the first I'd heard of it: and hopefully this info will be useful for their ongoing investigation!  Thanks for reporting it!

For now I'll go ahead and close this as there's nothing the API can do at this point.  But with any luck this'll provide some extra info to them as they continue to investigate.
