### ISSUE TITLE
Gambit Prime Perk Discrepancy

### ISSUE THREAD

**Issue by kramrm** [Bungie-net/api#882]
Not exactly an API issue, but I found some different terms used when looking up Gambit Prime armor perks.

Pinata of Death refers to "Special" ammo while Assassin's Munitions and Cashback refer to "Energy" ammo.

While most players probably won't notice, it may be nice to keep the wording consistent.

**Comment by vthornheart-bng** [comment]
Ah, I'll pass this along to the folks who make this content, and see if they can give it a look.  Thank you!

**Comment by kramrm** [comment]
Thanks.  I used this info to create an infographic.  Was nice to be able to get the text/graphics from the API.
https://twitter.com/kramrm/status/1104995661953478656

**Comment by vthornheart-bng** [comment]
Good deal, I'm glad it was helpful!

**Comment by kramrm** [comment]
Uh, it was later pointed out to me the difference between "Special" and "Energy" ammo.  Never mind. 😬
