### ISSUE TITLE
Getting a token

### ISSUE THREAD

**Issue by Mokoron911** [Bungie-net/api#885]
I can’t get a token so that I don’t do the result always alone. 

{"error":"invalid_request","error_description":"Cannot parse client_id"}

Help please solve the problem.

    var request = require('request'); 

    var data = {
        'grant_type': 'authorization_code',
        'code': '7f39897b4a1b17e4f5753a0a90c21***',
        'client_id': '20916457'
    };

    request.post({
        url: 'https://www.bungie.net/Platform/App/OAuth/Token/',
        headers: {'Content-Type': 'application/x-www-form-urlencoded'}, 
        data: data
      }, function(err, res, body){
        console.log(body);
    });

**Comment by caccavale** [comment]
I was having the same problem with this and found a forum post with the alternative of passing the client ID and the client secret in the header.  If you want to use it as a work around, you send the following request:

```
request.post({
    url: 'https://www.bungie.net/Platform/App/OAuth/Token/',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      'Authorization': 'Basic X'
    }, 
    data: {
      'grant_type': 'authorization_code',
      'code': '7f39897b4a1b17e4f5753a0a90c21***'
    }
  }, function(err, res, body){
    console.log(body);
});
```
where X is your client ID and secret (`<client ID>:<client secret>`) joined with a semi-colon, and then encoded in base64.  This is currently working for me whereas what you were trying was not.

**Comment by Mokoron911** [comment]
@caccavale it still doesn't work for me

    var X = base64encode("20916457" + ":" + "8jCRdq2-YssCuop0ZGN7ryCREbi-ge.sBxo9h6*****");

    request.post({
        url: 'https://www.bungie.net/Platform/App/OAuth/Token/',
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
          'Authorization': 'Basic ' + X
        }, 
        data: {
          'grant_type': 'authorization_code',
          'code': 'e678b4d851988652fd240ba528d*****'
        }
      }, function(err, res, body){
        console.log(body);
    });

**Comment by ckhicks** [comment]
Have you tried it with your X-API-Key header included? Your request body should include both `grant_type` and `client_id` - not sure how the `code` workaround is actually getting you what you need without the client id as well.

**Comment by Mokoron911** [comment]
I already tried all this! Before creating this query, I spent three days trying to figure out the api. I think I have already tried everything... Looks like you need to be elected to use oath in bungie api.

@ckhicks Not working:

    var X = base64encode("26395" + ":" + "8jCRdq2-YssCuop0ZGN7ryCREbi-ge.sBxo9h6*****");

    request.post({
        url: 'https://www.bungie.net/Platform/App/OAuth/Token/?grant_type=authorization_code&clinet_id=20916457&code=86571a7459eb30745b4c1c3dc7a*****',
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            'X-API-Key': '66755ea4ca934d1cbe099487e97*****',
            'Authorization': 'Basic ' + X
        },
        data: {
            'grant_type': 'authorization_code',
            'clinet_id': '20916457',
            'code': '86571a7459eb30745b4c1c3dc7a*****'
        }
      }, function(err, res, body){
        console.log(body);
    });

How do you log in? If you send code samples, I will be grateful.

**Comment by floatingatoll** [comment]
Client_id is misspelled in that code paste.

**Comment by Mokoron911** [comment]
@floatingatoll yes you are right. The fix did not work.

**Comment by floatingatoll** [comment]
Could you please provide the server’s HTTP response status code, the server’s HTTP response header “Set-Cookie”, and the server’s JSON response body that’s returned when you attempt to run that code?

**Comment by Mokoron911** [comment]
@floatingatoll 

    var X = base64encode("26395" + ":" + "8jCRdq2-YssCuop0ZGN7ryCREbi-ge.sBxo9h6*****");

    request.post({
        url: 'https://www.bungie.net/Platform/App/OAuth/Token/?grant_type=authorization_code&client_id=20916457&code=25403af13026fd967bfa4fdf7d2*****',
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            'X-API-Key': '66755ea4ca934d1cbe099487e97*****',
            'Authorization': 'Basic ' + X
        },
        data: {
            'grant_type': 'authorization_code',
            'client_id': '20916457',
            'code': '25403af13026fd967bfa4fdf7d2*****'
        }
      }, function(err, res, body) {
        console.log(body + " \nstatus code: " + res.statusCode + "\ncookie: " + res.headers['set-cookie']);
    });

{"error":"invalid_request","error_description":"Missing required parameter grant_type"}
status code: 400
cookie: __cfduid=d5aeee7cd477d1ea0f9c8341ba3f544e11553038750; expires=Wed, 18-Mar-20 23:39:10 GMT; path=/; domain=.bungie.net; HttpOnly,bungled=393500169594332306; expires=Sat, 19-Mar-2022 23:39:12 GMT; path=/,bungledid=Bz7NynY4hmxEgMETEKujmBOcXToXxKzWCAAA; expires=Mon, 19-Mar-2029 23:39:12 GMT; path=/; HttpOnly,Q6dA7jjmn3WPGkYAhga2oHvTT+8b849OPtfBrw@@=v1YtlRgw@@h5k; Expires=Wed, 20-Mar-2019 00:39:12 GMT; Path=/

**Comment by vthornheart-bng** [comment]
Greetings!  Sorry, only just saw this!

Hmm, judging by that response it sounds like we might have not been able to interpret the post data being passed.  Could you use a program such as Fiddler to see the specific HTTP post request and post data you're sending up when you make this post request?  If it ends up coming to us in - for example - JSON format as opposed to Form encoded, we're going to misinterpret it and fail with an error of the sort that you're seeing above.

If you can do that, let me know what you see in there and/or post the (appropriately redacted as needed) request/response up here!

**Comment by floatingatoll** [comment]
Try replacing `data:` with `json:`?

I don't see `data:` as a supported key in the `requests` docs [1], but I _do_ see `json:` offered as a "convert your Python hash to JSON". You may wish to look into preparing [2] your request and then studying what _would_ be sent, since that may confirm that you're transmitting a 0-byte request body rather than the JSON you expect.

[1] https://github.com/request/request#requestoptions-callback
[2] https://stackoverflow.com/questions/20658572/python-requests-print-entire-http-request-raw

**Comment by vthornheart-bng** [comment]
I wonder if in part this is a "do as it does, not as it says" scenario.  I am unfamiliar with Python in general so I don't have personal experience, but I see a lot of sites like this doing the exact same thing when mentioning the "x-www-form-urlencoded" content type:

http://docs.python-requests.org/en/v0.10.7/user/quickstart/

They *say* to use the data property, but in their example they actually *use* the "form" property.

Can you try using the "form" property instead of "data" and report back?

**Comment by Mokoron911** [comment]
@floatingatoll @vthornheart-bng this is not a python, but node js

This code is working:

    var X = base64encode("26395" + ":" + "8jCRdq2-YssCuop0ZGN7ryCREbi-ge.sBxo9h6*****");

    request.post({
        url: 'https://www.bungie.net/Platform/App/OAuth/Token/?grant_type=authorization_code&client_id=26395&code=578148907f2d6b913282d855723*****',
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            'X-API-Key': '66755ea4ca934d1cbe099487e97*****',
            'Authorization': 'Basic ' + X
        },
        form: {
            'grant_type': 'authorization_code',
            'client_id': '26395',
            'code': '578148907f2d6b913282d855723*****'
        }
      }, function(err, res, body) {
        console.log(body + " \nstatus code: " + res.statusCode + "\ncookie: " + res.headers['set-cookie']);
    });

I got my access_token and happy. Thanks!

**Comment by vthornheart-bng** [comment]
Sweeeeeeet!  I'm glad it worked out!

**Comment by vthornheart-bng** [comment]
I'll go ahead and close this for now - hit up a new issue if you run into anything else!
