### ISSUE TITLE
Medal Descriptions Aren't Descriptive

### ISSUE THREAD

**Issue by ClaytonMain** [Bungie-net/api#887]
Some of the `statDescription`s in `https://www.bungie.net/Platform/Destiny2/Stats/Definition/` aren't particularly descriptive. For instance, the `statDescription` for "I Made This For You" is "I Made This For You", whereas the `statDescription` for "We Ran Out of Medals" is "In a single life, defeat 20 opposing Guardians". Any chance of getting those descriptions added?

**Comment by vthornheart-bng** [comment]
I will have to give it a look - unfortunately, if they're not coming from the game data we might not be able to get the strings. :(

**Comment by vthornheart-bng** [comment]
TFS 772357
