### ISSUE TITLE
Gambit Prime and Reckoning milestones

### ISSUE THREAD

**Issue by dcaslin** [Bungie-net/api#889]
Any chance we can have milestones for the weekly completion of Gambit Prime and Reckoning milestones? Thanks!

**Comment by vthornheart-bng** [comment]
I'll need to investigate why it's not in there, I'll get back to you on this!

**Comment by vthornheart-bng** [comment]
TFS 772364

**Comment by jshaffstall-bng** [comment]
You should be getting the weekly challenges for Gambit Prime and Reckoning now, as of the update yesterday. Enjoy!
