### ISSUE TITLE
400 error

### ISSUE THREAD

**Issue by keyute** [Bungie-net/api#892]
spent 2 hours googling to no avail. what went wrong in this code?

$(function () {
	const urlParams = new URLSearchParams(window.location.search);
	let xhr = new XMLHttpRequest();
	let sendData = "client_id=26669&grant_type=authorization_code&code=" + urlParams.get('code');
	xhr.open("POST", "https://www.bungie.net/Platform/App/OAuth/Token/?"+sendData, true);
	xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
	xhr.setRequestHeader("X-API-Key","******");
	xhr.send(sendData);
});

**Comment by floatingatoll** [comment]
What is the response body received with the 400 error?

What is the 'bungled=....' value in the Set-Cookie response header, if any?

**Comment by keyute** [comment]
@floatingatoll no bungled value in cookie, just got this POST https://www.bungie.net/Platform/App/OAuth/Token/?client_id=26669&grant_type=authorization_code&code=***** 400

**Comment by floatingatoll** [comment]
Could you please provide the complete HTTP response body from the server?
"400 Bad Request" is the HTTP response status code, but there's usually a
request body as well (either JSON or HTML).

**Comment by keyute** [comment]
@floatingatoll there isnt 
<img width="730" alt="Screenshot 2019-03-28 at 12 49 32 AM" src="https://user-images.githubusercontent.com/24288858/55095622-6c8d8600-50f3-11e9-8423-819c3c56945f.png">

**Comment by floatingatoll** [comment]
The line you show is from the debug console of a modern browser. You will
need to use the Network/Requests pane of that browser's development tools
to inspect the request you transmitted more closely. Note that your method
of construction is appending the POST parameters to both the URL _and_ to
the request body, so that may be related somehow to this issue.

**Comment by keyute** [comment]
ah i see what you mean, my bad, i am very tired right now. here you go
{"error":"server_error","error_description":"OriginHeaderDoesNotMatchKey"}

**Comment by floatingatoll** [comment]
Ah, for that error — using that same trick, inspect your _request_'s
HTTP headers and check the Origin: that your browser is sending with
the request, and make sure it matches the Origin specified at the
bungie.net website's configuration page for your app.

**Comment by keyute** [comment]
well that fixed my issue, turns out there is a spelling mistake in the origin header set in bungie.net. man this makes me look stupid. thanks a lot!

**Comment by floatingatoll** [comment]
No worries! If it's of any comfort, several of us have been there before
too :)

**Comment by vthornheart-bng** [comment]
Aye, no worries on that!  I did almost the exact same thing just a couple of days ago!

**Comment by dkatina** [comment]
Over three years later this discussion thread saved me who knows how many hours fixing the same issue.
