### ISSUE TITLE
PGCR: divergence between completed and completionReason

### ISSUE THREAD

**Issue by rentalhost** [Bungie-net/api#894]
For a long time I have used the "completed.basic.value" to determines if the user have completed the activity, but at some moment it just glitched and diverges from "completionReason.basic.value".

The [PGCR 3673022477](https://www.bungie.net/Platform/Destiny2/Stats/PostGameCarnageReport/3673022477/) will have the following info (shortened for convenience).

```json
{
    "characterId": "2305843009261347887",
    "values": {
        "completed": { "basic": { "value": 1, "displayValue": "Yes" } },
        "completionReason": { "basic": { "value": 2, "displayValue": "Failed" } },
    },
},
{
    "characterId": "2305843009261817860",
    "values": {
        "completed": { "basic": { "value": 0, "displayValue": "No" } },
        "completionReason": { "basic": { "value": 2, "displayValue": "Failed" } },
    },
},
{
    "characterId": "2305843009262747950",
    "values": {
        "completed": { "basic": { "value": 0, "displayValue": "No" } },
        "completionReason": { "basic": { "value": 2, "displayValue": "Failed" } },
    },
},
{
    "characterId": "2305843009283628523",
    "values": {
        "completed": { "basic": { "value": 0, "displayValue": "No" } },
        "completionReason": { "basic": { "value": 2, "displayValue": "Failed" } },
    },
},
{
    "characterId": "2305843009342904390",
    "values": {
        "completed": { "basic": { "value": 0, "displayValue": "No" } },
        "completionReason": { "basic": { "value": 2, "displayValue": "Failed" } }
    },
},
{
    "characterId": "2305843009430014113",
    "values": {
        "completed": { "basic": { "value": 1, "displayValue": "Yes" } },
        "completionReason": { "basic": { "value": 2, "displayValue": "Failed" } },
    },
}
```

You will note that all `completionReason` is 2 ("Failed"), but the first and last `completed` is 1 ("Yes"), all others are 0 ("No"). Which is confuses.

The [doc](https://bungie-net.github.io/) don't have a clue about the difference between both.

For now, I will consider the `completionReason` to determine if the activity was completed.

**Comment by vthornheart-bng** [comment]
If I recall correctly "completed" means that they stayed until the activity ends, and completionReason attempts to give a hint about success/failure/disconnect/etc... however I'll check with the folks who work on the stats backend to make sure I'm conveying the right information.

**Comment by vthornheart-bng** [comment]
(in other words, completed = 0 means they bailed on the game before it hit the win/loss condition)

**Comment by vthornheart-bng** [comment]
Ah, so the truth came from the Wizard himself, and it's a bit more nuanced than I conveyed.

In general, completed does indeed mean "stuck around until the end of the activity".  But *when* that fires is fairly open-ended.  Some activities, like the Tower, never fire it.  Some fire it when you see the "activity complete" message.  Some might (theoretically) not fire it until the activity completely ends (I do not know specific activities that do this, but it is in the realm of possibility).  It's entirely controlled by activity designers, but the rule of thumb is that this generally ought to set to true whenever it would appear to the user that the activity is completely over.  And anyone who left before that is considered to not have "completed" the event.

**Comment by rentalhost** [comment]
Just to think about, the PGCR above is about a raid (Scourge of the Past), so what should mean that it is "completed" for just few members without the raid objective being completed in fact?

Anyway, I should consider the `completionReason` to have sure about raid conclusion, right?

If yes, so I think that this topic is done. :) 

Thanks a lot!

**Comment by vthornheart-bng** [comment]
Aye, if that was a raid it looks like a bunch of people dropped early and then the rest of them dropped out resulting in a failed attempt.  No problem!
