### ISSUE TITLE
/GroupV2/Search/ Endpoint Doesn't Like a + Sign

### ISSUE THREAD

**Issue by mikewojtkiewicz** [Bungie-net/api#896]
I'm working with this endpoint to search for clans, but if a clan has a '+' in their Clan Name, the url encoding throws some ugly errors. Here is the example clan I was searching and the url that gets passed:

Better Homes + Guardians
https://www.bungie.net/Platform/GroupV2/Name/Better%20Homes%20%2B%20Guardians/1/

The '%2B' seems to be throwing the error. Any thoughts on this?

**Comment by vthornheart-bng** [comment]
Ah, I just tried it out and got a 404 - was that what you were seeing?  Very interesting.  Yeah, I'll file a bug on that!  Thank you for the info!

**Comment by mikewojtkiewicz** [comment]
Yep. That's the issue. Thanks!

**Comment by Achronos-BNG** [comment]
Sorry this took so long to take a look at.  So, what you want is to call the /Platform/GroupV2/NameV2 endpoint.  It is a POST instead of a GET.  The endpoint you were using has been deprecated.
