### ISSUE TITLE
Sony 2 factor auth is broken

### ISSUE THREAD

**Issue by NigelHietala** [Bungie-net/api#897]
This isn't something affecting apps, but anything that uses Sony as part of the Oauth chain. So the following was done just using Google Chrome on Desktop and trying to sign in from scratch at bungie.net to see the normal bungie.net site.

You need a 2 factor auth sony account. Normal accounts login fine. Latest normal public version of Google Chrome was used on MacOS. 

1. Go to bungie.net
2. Chose login.
3. Choose Playstation.
4. Enter username + password
5. If prompted pass captcha
6. Login fails. However I did get the 2 factor sms code sent to my phone. The errors were as follows.

“Access Denied
You don’t have permission to access “http://auth.api.sonyentertainmentnetwork.com/signin/” on this server.
Reference #18.d2453c17.1554220891.19d5e95"

The URL was
https://auth.api.sonyentertainmentnetwork.com/signin/#/signin2sv/code?response_type=code&client_id=78420c74-1fdf-4575-b43f-eb94c7d770bf&redirect_uri=https%3A%2F%2Fwww.bungie.net%2Fen%2FUser%2FSignIn%2FPsnid&scope=psn:s2s&request_locale=en_US&state=4227901848734796181&ticket_uuid=eb0e23cf-086e-432f-804a-08d2c57a4952&layout_type=popup

**Comment by floatingatoll** [comment]
This occurs for me using Safari on macOS desktop as well. I first observed it last night at 10pm Pacific. Sony sends the 6-digit text message code by SMS but their (https-secured) server then fails to display the input form correctly, with the error Nigel shows below.

**Comment by hellocontrol-bng** [comment]
This is a known issue, we are working with Sony to resolve it. We're continuing to investigate.

**Comment by adh1310** [comment]
Would this authentication failure explain why I can't see my list of application on the Bungie.net Your Apps page? I was able to sign in with my Battle.net ID but usually use my PSN. Since signing in that way, I can't see any of my applications except for one old one I had disabled a while ago. I thought everything was tied to my Bungie account and not the auth provider I choose to sign-in with but yeah, no apps.

**Comment by hellocontrol-bng** [comment]
@adh1310 These are not tied to a particular provider, they are tied to your Bungie.net account. Are you positive you have both providers linked to the same Bungie.net account?

**Comment by adh1310** [comment]
@hellocontrol-bng I am like 99% sure they were both linked to my Bungie ID but can’t verify until the PSN with is working again. Once that happens, I’ll check and open a new issue if that’s the case.

**Comment by vthornheart-bng** [comment]
An easy way to check is on bungie.net.  Sign in with that battle.net ID, then go to your Settings, and then "Accounts & Linking".  Check if the exact PSN account you were expecting is linked there.

**Comment by adh1310** [comment]
![Capture](https://user-images.githubusercontent.com/8731789/55521149-7bbd8800-564d-11e9-832d-b4a226786e96.PNG)

It's got both my accounts listed as linked. When I visit the Applications page, this is what I see:

![Capture3](https://user-images.githubusercontent.com/8731789/55521174-9db70a80-564d-11e9-9ecc-a0254d7e4ce4.PNG)

Which is one of the applications I've used in the past. My other applications though aren't listed. They are still working though, I can use the API key and refresh token so they weren't deleted.

**Comment by floatingatoll** [comment]
Do you have the numeric application ID of any/all of the applications not listed?

**Comment by adh1310** [comment]
I do not, unfortunately. Only one of them am I actively using and I can provide the API key if that helps. If I have to create it again it's not that much of a deal but just wanted to see if it was on my end or not.

**Comment by vthornheart-bng** [comment]
Interesting, that is very unusual!  I think I'm going to have to investigate this more closely.

Can you give me a link to your profile URL?  That'll help me track down what's going on, I can use the membership IDs found in that link to do some digging over here.

**Comment by adh1310** [comment]
So I was able to look through my web history and find the URL to the main application I use. Interestingly enough, if I click on it, I can access the application page. It just isn't showing up in the list.

Here is the link to that application page: [https://www.bungie.net/en/Application/Detail/29492](https://www.bungie.net/en/Application/Detail/29492)

And here is my profile URL: [https://www.bungie.net/en/Profile/254/6138511/TheAndrata](https://www.bungie.net/en/Profile/254/6138511/TheAndrata)

**Comment by adh1310** [comment]
@NigelHietala Sorry to hijack your issue thread, lol

**Comment by vthornheart-bng** [comment]
Interesting - ah, how about we pull this over into another github issue.  Go ahead and move over your info into a new one and we'll handle it there!

**Comment by adh1310** [comment]
Done! 

[https://github.com/Bungie-net/api/issues/899](https://github.com/Bungie-net/api/issues/899)

**Comment by vthornheart-bng** [comment]
Try it now!  Should be good to go.
