### ISSUE TITLE
Downloading the Manifest

### ISSUE THREAD

**Issue by ashleypb** [Bungie-net/api#90]
Im struggling to work out how to get the sqlite file from the manifest response.

Ive called the manifest and found the path:
[Response] [mobileWorldContentPaths] [en]
which gives a link to a .content file

If i visit this link it just downloads the .content file but when i open it up is just a mess of symbols.

How do i turn that file into the sqlite file??

**Comment by ArkahnX** [comment]
the *.content files are actually archives, if you save it as a zip, then extract it as a *.content file, you can view that file as an sql database, which has entries for each of the different definition files in JSON format.

However there is a signing issue for the hashes for each definition, a solution to that was brought up in an earlier issue.

**Comment by vpzed** [comment]
It is zipped.  Just unzip it and that will be the sqlite db.

**Comment by ashleypb** [comment]
Thanks guys, All sorted, i didn't check the filesize of the unzipped .content file, original file was ~2MB but after renaming to .zip, then extracting is was 11MB, originally i thought it was the same file so stopped right there!
