### ISSUE TITLE
Gambit Prime medals not yet being returned

### ISSUE THREAD

**Issue by vthornheart-bng** [Bungie-net/api#900]
A heads up for anyone who was looking for them - we don't yet have Gambit Prime medals in the API.  It's in our backlog, we'll loop back here once we get them in.

**Comment by afpac** [comment]
Awesome! I'm building some stuff around this at the moment and was disappointed to see the new medals weren't included. Glad to see they'll be in there eventually.

By the way, while you're in the neighborhood of medals, it looks like [#762](https://github.com/Bungie-net/api/issues/762) is still happening - the medal icons for normal Gambit matches still are not included in the manifest.

**Comment by t3rr11** [comment]
Any news on this, is it making it's way up the backlog? Just went looking for the missing medals myself.

**Comment by vthornheart-bng** [comment]
I'll hit some folks up and check on that, thank you for bringing it up!

**Comment by justrealmilk** [comment]
So it seems that matches returns medals they're aware of and for any others, it returns `medalUnknown` instead.

Is there, like, a dictionary sever side that needs to be updated or
