### ISSUE TITLE
Gambit Private Matches doesn't have its own activity mode yet

### ISSUE THREAD

**Issue by vthornheart-bng** [Bungie-net/api#901]
This is also on our backlog to investigate, and I wanted to give you all a heads up about it that we're not returning it as its own activity mode currently.

**Comment by mikechambers** [comment]
fyi, was going to log this, but saw this report, so sharing some more info here:

Pulling activity history:
https://www.bungie.net/Platform/Destiny2/1/Account/4611686018429783292/Character/2305843009264966985/Stats/Activities/?count=2&page=0

Private Gambit matches are coming back as mode 0, with empty modes.

```
"period": "2020-09-20T00:34:46Z",
"activityDetails": {
    "referenceId": 2428492447,
    "directorActivityHash": 2624692004,
    "instanceId": "6927126303",
    "mode": 0,
    "modes": [],
    "isPrivate": false,
    "membershipType": 3
},
```

I would expect it would come back as mode 63 (Gambit), and that modes would be 63 [Gambit].

Looking at the post game report:

https://stats.bungie.net/Platform/Destiny2/Stats/PostGameCarnageReport/6927126303/

mode, and modes are also incorrect, and isPrivate is wrongly set to false.

Note, current PrivateMatchesAll (32) only returns crucible private matches. Its not clear from the docs if this is intended, or it is a bug that private gambmit matches are not included. Ideally, there would be a seperate mode for PrivateGambitMatches.
