### ISSUE TITLE
About an important an issue

### ISSUE THREAD

**Issue by ByErdem** [Bungie-net/api#903]
Dear Destiny Team,
If possible I want to an important something from you. I have a friend with a deadly disease. My friend cannot speak and is bedridden sick. My friend has very little time of life. He is playing Destiny 2 game. He wants a gun in the game he plays. We just want to get him the gun he wants as a couple of friends. We can send you how many money you want. We just want the happiness of our friend. If he leaves us one day, we want him to leave happily. Name of the gun Luna's Howl and our friend's name in the game is Resul_boba_31. Please help us. As I say, money is not important. We can send as much as you want.
We are waiting your replies. Thank you in advance for your interest,
Best Regards,
Erdem Cantürk
Our Clan name: Gizli_Gölge

**Comment by floatingatoll** [comment]
I’m sorry to report that the Destiny API team has neither the authority nor the ability to be of assistance with your plea. You may instead wish to post this to the Destiny2 > Help forum at Bungie.net using any Bungie account that has played Destiny2; while a reply is not guaranteed, you’ll have better odds than the guaranteed “we cannot help” here.

**Comment by vthornheart-bng** [comment]
Aye, I'm sorry about that, but indeed I've unfortunately got no ability to help with such a situation - but hit up DeeJ or Cozmo on Twitter.  I can't promise that he will be able to respond as he gets a lot of messages, but they may be in a better position to help.

**Comment by ByErdem** [comment]
In fact, I realized that what I wanted was not ethical, I apologize for asking for it.
