### ISSUE TITLE
Probably-accidentally unclassified material "Apex Catalyst" (1606076864)

### ISSUE THREAD

**Issue by floatingatoll** [Bungie-net/api#907]
This item might not have been intended to be left exposed in the API:

https://www.light.gg/db/items/1606076864/apex-catalyst/

per

https://www.reddit.com/r/DestinyTheGame/comments/bcqz1o/new_infusion_material/

**Comment by vthornheart-bng** [comment]
Checking up with some folks now, I'll update once I hear back from them!

**Comment by vthornheart-bng** [comment]
Got an answer back - the item's not currently in use and can be safely ignored!

**Comment by floatingatoll** [comment]
Could you please mark it Classified in the API?

**Comment by vthornheart-bng** [comment]
Yeah, I can do that if it'd alleviate concerns!

**Comment by floatingatoll** [comment]
People react to it as if they've uncovered new game functionality
that's coming up in the near future. It's misleading. Since it's
confirmed unused, I ask to classify it in whatever manner you do that
with for other such unused items, so that API explorers stop reporting
it as "omg new" every couple months.

**Comment by vthornheart-bng** [comment]
Yeah, I totally agree with you on that.  I'll go ahead and get it redacted!
