### ISSUE TITLE
Shattered Throne Milestone

### ISSUE THREAD

**Issue by dcaslin** [Bungie-net/api#908]
Similar to https://github.com/Bungie-net/api/issues/889 only with Shattered Throne: 

Shattered throne has 3 powerful drops that are only available once per week per char. Any chance that we can those drops as in the character milestones? (bonus: Only include on weeks when Shattered Throne is active).

**Comment by vthornheart-bng** [comment]
I dig that!  I'll add it to the backlog.

**Comment by vthornheart-bng** [comment]
TFS 780983

**Comment by lowlines** [comment]
This would be handy since Shattered Throne is now always active and actually drops Powerful Gear! Maybe it could be added along with the upcoming Shadowkeep Dungeon?
