### ISSUE TITLE
Possibility to add an endingPhaseIndex for incompleted raids on PostGameCarnageReport?

### ISSUE THREAD

**Issue by StormTester** [Bungie-net/api#909]
I have a discord robot which gives users roles based on their raid achievements, such flawless, low mans (3 or less people) and speedruns. The problem is that for low mans, I can only give them roles for the final encounter of each raid, or for all of them if they complete the raid from start to finish. This is an issue because certain encounters can be completed with a lower playercount than what the final encounter can be and sometimes the final encounter cannot be completed with a lower playercount, like Spire of Stars. 

If there was a possibility to add something like a endingPhaseIndex which shows at what checkpoint the activity ended on that would be a massive help and I'm sure other raid services would also find this helpful. If it's not too much trouble to add something like this, it'd be greatly appreciated. Thanks.

**Comment by vthornheart-bng** [comment]
I'll hit up the folks who work on the Stats backend about it - it seems like a good idea!  But I know their plate is full right now, and I don't know if it will be possible to get you that data (both from a technical standpoint and due to time/resource constraints for working on new stats presently).  But I'll hit them up about it so that it at least ends up in the list of ideas that can be worked on if time allows!

**Comment by vthornheart-bng** [comment]
Okay, so it's going to be a while until it comes out the other side, but we're going to try to get that to you for activities toward the end of the year.

As usual, these phase indexes are going to be the same "you'll have to figure out what it means yourself" style integer value: we don't and still won't have any human readable related to these phase indexes.  But if you're already doing that part, then this should just work when we're able to push it out to you!

**Comment by StormTester** [comment]
Nice. Looking forward to the release!

**Comment by vthornheart-bng** [comment]
Woot!  I wish we could get it earlier - due to the risk and other features in flight, I had to check it into a branch that's a bit far away from release.  But when it gets closer to release I'll loop back around and let you guys know more about when it will make it live.

**Comment by StormTester** [comment]
I was also wondering, would this new feature be retroactive? I know it was for the startingPhaseIndex.

**Comment by vthornheart-bng** [comment]
Unfortunately it won't be - we were never saving this data before, so it won't exist until we start saving it. :(

**Comment by BlazeBoss17** [comment]
I would love to see an array of all phaseIndexes completed in a given instance. This would be extremely helpful for something like last wish, where a player can skip around the raid to any checkpoint.

**Comment by vthornheart-bng** [comment]
Ooh, I forgot about the phase skipping - that's a good point as well.  Let me bring that up over there.  I know that at some point we're going to hit a tradeoff of storage requirements vs. benefit it provides, but this should be a relatively limited amount of data.

We also don't currently have a way to return you an array of data with the current stats infrastructure if I recall correctly offhand, but I could also see us potentially changing that and adding that as a feature - it'd be nice even outside of this request, I imagine this isn't the only thing that would make sense to have an array of results for a single "stat value."

So it'll be a bit more work than just providing the ending phase index, but I think it would definitely be nice to have if we can find the time to plumb it through!

**Comment by vthornheart-bng** [comment]
Also though, I should note that we don't actually have any information that we'd be able to use to know for sure that a phase was actually completed in the data, at least in a maintainable way.  We do have a way to get you the data about what phases someone went *into*, but if there's some way to get into a phase and then abandon it while still being in the activity (I don't know if there is!), we wouldn't have any knowledge of that.  We'd only know that you got to that phase.

So if you can think of scenarios where that would limit the usefulness of your data - if there is a way to abandon a phase and choose a different phase without leaving the whole activity for example - then our data's going to be insufficient for that purpose.

**Comment by BlazeBoss17** [comment]
Seeing what phase a player went into is just as useful.

**Comment by vthornheart-bng** [comment]
Sweet, good deal - that is definitely feasible as long as we have time to make those changes required to expose them!  I kicked off a separate task to discuss with them now about the possibility of plumbing that data through.

**Comment by StormTester** [comment]
As far as Last Wish is concerned, a temporary solution could be to return whether or not the player went into the PhaseIndex of the bridge (after Kalli and before Shuro), this would allow us to determine whether or not a player used teleport wishes, as this PhaseIndex is inaccessible through any wish and once the player reaches this point, they're unable to access the wish wall. The array would still be the most ideal solution though.

**Comment by floatingatoll** [comment]
To throw out a point to consider for the design team, using phaseIndex to
determine whether the wishing wall was used to teleport to a phase is quite
a hack — simply recording a didWallTeleport: TRUE note would be invaluable
in that particular respect.

**Comment by vthornheart-bng** [comment]
I agree with you in principle, but whether we can give that kind of information is going to depend on if we can find a way to automate it.  I can't sign up the team that's working on that (and already a bit overloaded) to ongoing maintenance if an activity in the future ends up needing a similar fix... BUT in an ideal world I would love to return that!

I'll do a little looking around, but my gut feeling is that we aren't going to find a good way to know that aside from specifically for Last Wish.  But if there is a way to know that more universally, I'd be glad to see that added in!
