### ISSUE TITLE
Will triumph score be added to any of the DestinyActivityModeTypes for Destiny2.GetLeaderboards?

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#913]
I've been experimenting with ranking Braytech users by triumph score and grabbing a numerical representation by querying the data I've scraped. 

As Destiny2.GetLeaderboards does ranking so well, is it far fetched for me to hope that a certain wonderful API overlord could slip triumph score into one of the DestinyActivityModeTypes? 🤫

**Comment by floatingatoll** [comment]
Is triumph score not already included in the Profile data response?

**Comment by ckhicks** [comment]
Yep, it is, under `Records: 900` (https://bungie-net.github.io/multi/schema_Destiny-DestinyComponentType.html#schema_Destiny-DestinyComponentType)

**Comment by justrealmilk** [comment]
@floatingatoll @ckhicks 
Yeah, no, I'm asking for clan leaderboard rankings. It's a new endpoint.

**Comment by vthornheart-bng** [comment]
It's a cool idea, but unfortunately the stats system isn't set up well to provide data about a user outside of the context of activity completions and the data that comes down with that.

The tricky part of Leaderboards and other stats is that their data is scraped entirely from the raw data that is aggregated at the completion of an activity.  That means that, even if we can get this data, it'd be at a resolution of activity completion: so if you don't play an activity but get a huge Triumph score somehow, we won't actually see it until the next time you complete an activity.  Which is probably fine.  Probably more limiting is that we may not even get that data - at which point I don't think it'll be possible to find the time required to start getting it for this purpose.

I'll ask around though - if we get it from the raw end of activity data, it is at least feasible!

**Comment by TorKallon** [comment]
Is this a new endpoint or just the same Clan Leaderboards endpoint that has been around since D2 launched?
