### ISSUE TITLE
ActivityMode:2096553452 displayProperties.name is "Salvage" but should be "Lockdown"

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#914]
2096553452 

https://data.destinysets.com/i/ActivityMode:2096553452

**Comment by vthornheart-bng** [comment]
Hmm, I feel like we've fixed this once before.  Perhaps it regressed?  I'll take a peek!

**Comment by vthornheart-bng** [comment]
Sure enough!  Okay, this won't be fixed for the deployment tomorrow, but it will be for the next one.

**Comment by vthornheart-bng** [comment]
Also, thank you for reporting this!
