### ISSUE TITLE
Expose in-game activity time in PGCR

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#915]
There's now a lot of attention on comparing and tracking Nightfall speed run times, since it's been discovered the likely trigger to obtain the After the Nightfall emblem. I build a [Nightfall compare tool](https://clan.report/compare-nightfalls?players=2%2F4611686018469271298) to keep track on your fastest run for each Nightfall.

The main difficulty for this is that the activityDuration we get on the Nightfalls (and most activities actually) differs from the timer shown in game by about 30-60s, which leads to lots of confusion - I've gotten loads of questions on reddit and twitter about this 😅

Take [this example](https://mobile.twitter.com/trevorevans/status/1124351186776158208), [PGCR 3922934187](https://www.bungie.net/en/PGCR/3922934187) which on the in-game Activity Summary screen shows the time as 9:43, whereas in the API activityDuration actually comes through over 1m longer at 10m 47s.

My guess/understanding here is that the activityDuration time starts the moment the _activity_ is started, and ends when they go to orbit, so it includes flying-in-time and black-screen-time, whereas the in-game time is just the 'mission logic'.

For future activities, would it be possible to include the 'mission timer'  that's shown in-game as an additional field on PGCRs? It would be a huge boon to loads of people.

**Comment by vthornheart-bng** [comment]
Hmm, I'll need to look into it - if the mission timer is implemented in a standardized and predictable way, I think this is possible.  If it's implemented in an "each designer got to choose their own way to implement it" way, I don't think I'll be able to sign us up for the ongoing maintenance costs that would come with trying to keep up with it.

However, I really would like to see this come through.  I need to find out which it is though - and I fear it's almost certainly the latter case.  My confidence of being able to reliably provide this information in a future proof way is about ~15% right now.  But I'll loop back once I find out more info.

**Comment by vthornheart-bng** [comment]
Okay, I did a little digging - indeed, unfortunately we can't return the data in a maintainable way at this time, and the work to turn it into a feature that we could realistically maintain is such that I don't think we'll get greenlit on working on it in the near future.

However, I think the discussion got people (myself at least, hopefully others!) excited about the possibilities that would come from building a more robust system for extracting and interpreting the kind of data from which this is sourced.  I added it to the long term backlog, in hopes that it will be something we could work on in the future.

**Comment by BlazeBoss17** [comment]
I would love to see this for raids too maybe one day. Would help eliminate the difference in PC vs console load times.

**Comment by TorKallon** [comment]
+1

**Comment by vthornheart-bng** [comment]
Yes, I would love to see that come to pass as well!  My hope is that the idea I have for future improvements on this would make it possible.  Definitely some work needed before it can come to pass. :(

**Comment by ckhicks** [comment]
Thanks for your research and bringing those findings back, mate. This repo always gives me a shot in the arm and we all appreciate the work y'all are doing.

**Comment by vthornheart-bng** [comment]
<3
