### ISSUE TITLE
What are the usual API update days?

### ISSUE THREAD

**Issue by t3rr11** [Bungie-net/api#917]
When does the API undergo an update? For example, when could we expect an update that would include the classified weapons for that previous tuesday update? Since they don't come out the same day and usually a few days later. Is there a schedule the API team follow?

**Comment by justrealmilk** [comment]
Actually, usually manifest updates seems to coincide with releases aka weekly reset. Sometimes there's subsequent updates over the next few days, especially in the past few weeks.

**Comment by vthornheart-bng** [comment]
Yes - we will always do a new release of the site coinciding with major game updates, and generally with patches as well if the change included a revision to game content.

On top of that, we usually release changes to the website every two weeks.

Note though with all of this that I am talking about the website, and not specifically the API.  We don't have anyone working full time on the API these days - so meaningful changes aren't going to be on a similarly fixed schedule.  A website update will almost always include an update to game content/the manifest databases, but changes and improvements to the API will only come along as we have time to work on them.

When it comes to declassifying items, we generally don't do that until the release after a classified item is "visible" in the game - so the wait will usually be between 1 and 2 weeks.  (this is up to the discretion of the content creators however.  They may ask for an item to be classified for longer than that, or even indefinitely.  Though we try to discourage that.)

**Comment by vthornheart-bng** [comment]
<3

**Comment by floatingatoll** [comment]
To mention something I didn't see above: Most API updates seem to be on
Tuesdays, barring unusual circumstances.
