### ISSUE TITLE
Cannot access application after linking xbox and playstation accounts

### ISSUE THREAD

**Issue by maskalek** [Bungie-net/api#919]
Hi. What happened?
1. I Logged in through playstation account.
2. Created application https://www.bungie.net/en/Application/Detail/29470.
3. Logged through xbox account with new profile.
4. Linked my playstation account with deleting old profile.

And now I don't have access to application from any accounts. Could you help me please?

New profile: https://www.bungie.net/en/Profile/254/21122425/WindingLizard89

**Comment by vthornheart-bng** [comment]
Yes, unfortunately this is a limitation of the way that our Bungie.Net Profiles work (which Applications are tied to).  If you orphan a Bungie.Net account by moving all login options away from it (which occurred by moving your playstation account to the new profile), you will lose access to everything on your old profile, including Applications.

Unfortunately, we don't have the time to provide a more robust fix for this problem: you'll find that you have also lost your Bungie.Net forum history, any non-Clan group memberships you had, and your settings.  You will have to create a new application with your new profile, and update your application.  I apologize for the inconvenience this has caused you!

**Comment by maskalek** [comment]
Ok. I see. Can you delete this application then? Because I would like to reuse its name, but cant because it's taken.

**Comment by vthornheart-bng** [comment]
Handled the rest of this issue offline - @maskalek , check your Bungie.net messages on your new profile, I sent you some follow up information!
