### ISSUE TITLE
GroupV2.AbdicateFoundership throws a AccessNotPermittedByApplicationScope error

### ISSUE THREAD

**Issue by ghost** [Bungie-net/api#921]
It might be designed that way, but the docs make it sound like it's available to us.  

It threw an "AccessNotPermittedByApplicationScope: 2108" error while using a clan leader's auth tokens (clan admin permissions).  I was able to demote/promote people with those tokens so they definitely work.

This method is described as "An **administrative method** to allow the founder of a group or clan to give up their position to another admin permanently.".

It doesn't list the required scopes like the others, but the scope for banning people is "**AdminGroups**".  AdminGroups seems pretty similar to how the abdicate founder call is described.

**Comment by vthornheart-bng** [comment]
Hitting up some folks to take a look, we'll loop back to you on this.

**Comment by vthornheart-bng** [comment]
For the time being, the only way to be able to do it is through the admin page on Bungie.net itself - you can appoint a new Founder in your Clan Settings page!

Just to make sure though, is Abdication doing what you intend?  It allows you, when you are the founder, to give your founder status to someone else.  It won't let you demote anyone other than yourself.

**Comment by Akumati1435** [comment]
If that is what bungie.net's clan admin page calls, then yea, it works through there.  My plan was to have an "oh shit" button that i can hit to get a clan back from one of my other leaders.  They log into my website and store their tokens with clan admin privs in my database so the API call would be coming through them. If that call worked through the API, I'd be able to transfer a clan back to me if something terrible happens.

I suppose another question might be... Seeing as my clan system is # 1 atm and we are a very heavy API hitter, is it possible to get access to some of the API calls that generally aren't accessible to the public?  Things like this call for example, maybe if there is a hidden messaging API call we could use to message people through bungie.net, or possible make it easier to automate recruitment so they just need to click a button on our website and we can get them in instantly (aka, leave their clan, invite them to ours, and accept them into ours)...  I think at this point we'd be considered trustworthy, but I'd obviously expect our api keys to be heavily monitored if this happens.

**Comment by vthornheart-bng** [comment]
Sorry, we're not in a position to grant people any kind of preferential treatment or permissions.
