### ISSUE TITLE
Could different Raids be added to Destiny.HistoricalStats.Definitions.DestinyActivityModeType as their own types?

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#922]
Weird request, I know. But for the convenience of being able to pull summary stats and particular sets of PGCRs, could you add raids groups to Destiny.HistoricalStats.Definitions.DestinyActivityModeType?

Groups as in one for Leviathan-based activities, one for Last Wish, one for SotP...

Loading all of a users activity history is impractical and a potentially costly exercise - my excuse.

The UI I've built enables a user to effectively filter PGCRs by activity mode. Obviously, raids only have one mode, 4!

Example of the Crucible equivalent:
![image](https://user-images.githubusercontent.com/156681/58385889-d61a0a00-803a-11e9-916a-3d70ef995a42.png)

Now, I know, this isn't really the same thing or appropriate for the purpose of DestinyActivityModeType... But, nothing ventured, nothing gained...

**Comment by kramrm** [comment]
Do you mean like turn 4 in to "AllRaid" and then have a separate mode for each of the individual raids?

**Comment by vthornheart-bng** [comment]
I'd like to see this come to pass as well.  I need to do some looking into it - I'd be more hesitant if the change wouldn't be backwards compatible (i.e. if old activities wouldn't categorize properly), but if it would be then I'd like to see it come to pass.

**Comment by TorKallon** [comment]
This feels very inconsistent to me. Why do this for raids but not Strikes?
Why not have story missions from different expansions sit in different
modes?

If this does happen, please make sure there is plenty of advance notice. A
change like this would cause massive data corruption issues for those of us
scraping and storing raids.

**Comment by vthornheart-bng** [comment]
It would be backwards compatible if they were all still grouped under the current activity mode: I wouldn't plan on changing that, but instead having new, more granular activity modes under the existing Raid mode.  That is, if it's even technically possible with the data we have at the moment and the way Raids are set up.

The point about doing this for individual Strikes vs. Raids is a good point - I definitely wouldn't want our activity modes to be so granular that it breaks up into Activity-level granularity.  In my mind, Raids are distinct enough experiences from each other that they feel more like separate modes or sub-modes of play (with differences-in-kind such as their own distinct puzzles and mechanics, where Strikes tend to have similar gameplay but in different settings), but that's just my entirely subjective perspective on the distinction between the two.  I also see individual Raid activities as being something specialized enough that people would care more about summary stats for them compared to, say, an individual strike.  In an ideal world, we'd provide both: but we're definitely not living in that ideal world right now

I also would not want to push my subjective opinion as canon in this regard: I recognize that giving Raids special treatment for the reasons above would be highly subjective.  I'm definitely open to alternative opinions on this.  @TorKallon, how would you feel if the activity mode changes were backward compatible in the way I mentioned?  And others, what are your thoughts?

(and note that I can't guarantee we even can do this without a larger change that we can't afford the time or resources to make, so this is all theoretical)

**Comment by TorKallon** [comment]
If the change was to add new modes to the mode list, but keep the root
"mode" for the PGCR the same (4) then it would be backwards compatible but
very different from all other cases where the most specific mode is the one
used in the root "mode" of the PGCR. But if the root "mode" were to change
to the mode specific mode then it would not be backwards compatible. We
would need to change quite a bit in order to make that work.

I do think that even for Raids, it is confusing to add this inconsistency
to the API. Raids are different and individual, but so are strikes and so
are story missions. I'm also not sure what this would really add since you
can get individual raid stats today via the proper endpoint.

**Comment by vthornheart-bng** [comment]
Hmm, it looks like the conversation may be moot.  I took a little time to look into it, and it doesn't look like it's actually feasible to safely split these without the larger work I was fearing.

In an ideal world - and hopefully if we ever get the thumbs up to make a new iteration of the stats backend - I'd like to see something where you could get a per activity breakdown for any activity.  I think that'd be something that'd be a nice to have to add to a wishlist for such a refactor.
