### ISSUE TITLE
Item 3216785214 Rune of War has incorrect description

### ISSUE THREAD

**Issue by kramrm** [Bungie-net/api#923]
description:"• Armor rolled with this rune active is guaranteed to have a mobility **rait.** • Weapons rolled with this rune active have low rounds-per-minute traits."
name:"Rune of War"

The word "trait" is missing the `t`.

**Comment by floatingatoll** [comment]
I would alter that to "trait", since it's not capitalized in the second
sentence. No argument otherwise.

**Comment by vthornheart-bng** [comment]
Interesting - is it showing up that way in game as well?  We can pass that on!

**Comment by kramrm** [comment]
Haven't gotten in game yet....

**Comment by vthornheart-bng** [comment]
I'm passing this info along for the folks who create that text to take a look.  Thanks for letting us know!
