### ISSUE TITLE
Bounty Based Loudouts

### ISSUE THREAD

**Issue by CTOverton** [Bungie-net/api#924]
Getting back into destiny 2 has been nothing short of overwhelming, but in a good way. With so many bounties it's often hard to sort through them and pick what to do. Something I thought might be useful though is just simply having DIM suggest which items or classes you should run based on your current bounties. 

For example: If you had a bounty for getting hand cannon kills DIM could suggest using a hand cannon.

Then just taking into account more and more bounties so it can give you a full list of possible loudouts and related bounties.

----
As a developer myself I might have some extra time on my hands so let me know if anyone finds this idea useful or if anyone more experienced with DIM would like to work on it. I'd be happy to help or potentially work on it myself.

**Comment by floatingatoll** [comment]
This sounds neat, though you may find it more usefully filed in the DIM GitHub for their team to consider:

https://github.com/DestinyItemManager/DIM/issues

**Comment by CTOverton** [comment]
> This sounds neat, though you may find it more usefully filed in the DIM GitHub for their team to consider: https://github.com/DestinyItemManager/DIM/issues
> […](#)
> On Jun 4, 2019, at 19:52, CTOverton ***@***.***> wrote: Getting back into destiny 2 has been nothing short of overwhelming, but in a good way. With so many bounties it's often hard to sort through them and pick what to do. Something I thought might be useful though is just simply having DIM suggest which items or classes you should run based on your current bounties. For example: If you had a bounty for getting hand cannon kills DIM could suggest using a hand cannon. Then just taking into account more and more bounties so it can give you a full list of possible loudouts and related bounties. As a developer myself I might have some extra time on my hands so let me know if anyone finds this idea useful or if anyone more experienced with DIM would like to work on it. I'd be happy to help or potentially work on it myself. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

ahh I had both git hubs open! Posted to the wrong one whoops! Thanks
