### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Akumati1435** [Bungie-net/api#926]
.

**Comment by bladefist** [comment]
@Akumati1435 https://careers.bungie.com/en-US/

**Comment by Akumati1435** [comment]
That's where the " There are a couple positions that peaked my interest." came from.

I have a damn good job atm so i'm hesitant to apply immediately before asking some questions.

**Comment by Akumati1435** [comment]
a simple yes or no would have been nice, but i understand that with all the new content coming out, you have to be incredibly busy.  I'm just going to apply and see what happens.
