### ISSUE TITLE
Duplicate intrinsic perks on armor

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#927]
We're seeing items where the intrinsic socket's `reusablePlugs` list contains multiple active plugs. In game, only the first shows (and applies to stats): 
https://github.com/DestinyItemManager/DIM/issues/3815

<img width="314" alt="Screen Shot 2019-06-06 at 10 26 48 PM" src="https://user-images.githubusercontent.com/313208/59082964-35cdac00-88aa-11e9-8a60-023b39d6a29e.png">

I'm able to filter these out, but it seems like they're being returned unnecessarily.

**Comment by vthornheart-bng** [comment]
Mmm, interesting - yeah, we'll have to dig into this too when we get a chance.  Thanks!

**Comment by vthornheart-bng** [comment]
TFS 797619

**Comment by vthornheart-bng** [comment]
Is this still occurring?

**Comment by bhollis** [comment]
Nope, this appears to be fixed now.
