### ISSUE TITLE
Some bounties do not have an item category

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#928]
Bounties like https://data.destinysets.com/i/InventoryItem:3631073612 don't have any item categories. If they had the "bounties" category (1784235469) they'd be easier to categorize in UIs.

**Comment by bhollis** [comment]
Similarly, stuff like https://data.destinysets.com/i/InventoryItem:814073777 should be in the "quests" category.

**Comment by vthornheart-bng** [comment]
TFS 797620

**Comment by JpDeathBlade** [comment]
Just to add to this, the following Bounty types have either no category or listed as dummy and not Bounty:

- Additional Bounties
- Prime Daily Bounty
- Prime Weekly Bounty
- Prime 'Civic Duty' Bounty
- Timelost Weapon Bounty

**Comment by joshhunt** [comment]
For what it's worth, the new `traidId`s solve this. Everything in the Persuits tab has a matching traitId value that describes in what category its placed in in the Persuits tab UI.

[Bounties will have `inventory_filtering.bounty`](https://data.destinysets.com/i/InventoryItem:711490543), and [everything else will have `inventory_filtering.quest`](https://data.destinysets.com/i/InventoryItem:546212857).

Additionally, all Quests/Quest items will have an extra trait that says what subcategory it's placed in. For example, [Powerful Synthesizer](https://data.destinysets.com/i/InventoryItem:1160544511) has [Feel the Burn whereas has `quest.seasonal`](https://data.destinysets.com/i/InventoryItem:2826194714).
