### ISSUE TITLE
500 Internal Server Error on DestinyAccountNotFound

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#929]
Since the change to use non-200 status codes, I've noticed that DestinyAccountNotFound returns as a 500. I don't think that returning an "Internal Server Error" code is appropriate - this should be a 404. 500 usually indicates an error in the service itself.

Example URL: https://www.bungie.net/Platform/Destiny2/1/Profile/4611686018429726245/?components=100

**Comment by mattybeard** [comment]
Just to add further, the Activity History endpoint returns an error 500 when the user has made their privacy settings private to.

**Comment by vthornheart-bng** [comment]
Hmm, yeah that sounds like a bug in our status codes.  Thank you, we'll take a look!

**Comment by vthornheart-bng** [comment]
TFS 797621

**Comment by serkanbal** [comment]
Quick question about the status codes change: Is it safe to assume that unless we get a successful response from the call (meaning `"ErrorStatus": "Success"`); we are going to get a non-200 code from now on?

**Comment by vthornheart-bng** [comment]
Yes.  If we run into scenarios where we decide that's not the case, we'll try to add it to our documentation!
