### ISSUE TITLE
Adding lastPlayed to GetMembershipsForCurrentUser

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#93]
Sorting memberships by `lastPlayed` was a convenient way to display a choose a default membership to display to the user and this missing field makes it harder to do this, as well as the migration from `GetCurrentBungieAccount` harder as well.

Would be great to see this added back in.

**Comment by hellocontrol-bng** [comment]
It is currently possible to get at that information by calling `GetProfile` for each Destiny membership returned from `GetMembershipDataForCurrentUser`. It will be inside `profile.dateLastPlayed` in the resulting data, so it's still possible to get at that field once you load all of the Profiles in question.

Whether we can make that field more available from the membership data summary is another issue.

**Comment by vthornheart-bng** [comment]
Yes, I would indeed like to make this flow simpler when time allows.

**Comment by Tetron-bng** [comment]
In an effort to keep user account data independent of game data, we cannot discover when the profile last played without knowing with game they were playing (D1, D2, ???).  You will need to use the specific game endpoints to learn that information.
