### ISSUE TITLE
The Menagerie, ModeType

### ISSUE THREAD

**Issue by t3rr11** [Bungie-net/api#930]
Interesting question. Why is The Menagerie under the `modeType: 4110605575` which is for "Normal Strikes"? 

That is messing with the statistics a little. Considering every completion of The Menagerie is considered a "Strike" completion? 

Will it get it's own mode type? Was this just a placeholder for now? Was this a bug? Was it intentional?

**Comment by t3rr11** [comment]
Update: Apparently the heroic mode for the menagerie has the `modeType: 400075666` which is for "The Menagerie".
So guessing this is more on the bug side since there is actually a modeType for "The Menagerie".

**Comment by floatingatoll** [comment]
It’s subject to heroic strike modifiers, which could possibly play some part in this representation coming out in the stats to us.

**Comment by justrealmilk** [comment]
I liken it to how they handled Reckoning and I don't think it's a mistake. As @floatingatoll suggested, it's probably in order to tie it to weekly modifiers.

Interesting that the heroic version has a different mode though 🤔

**Comment by t3rr11** [comment]
Didn't even think of the modifiers, good call!

**Comment by vthornheart-bng** [comment]
Ah, let me file a bug on this.  If my memory serves me correctly, this ought to have its own mode though there was some difficulty in segregating it safely from strikes.

**Comment by vthornheart-bng** [comment]
TFS 811301
