### ISSUE TITLE
Erroneous records

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#931]
https://data.destinysets.com/i/Record:3653101661
https://data.destinysets.com/i/Record:4182231867

![image](https://user-images.githubusercontent.com/156681/59158132-2ee8a880-8af9-11e9-8829-bf802c2dcc85.png)
![image](https://user-images.githubusercontent.com/156681/59158133-36a84d00-8af9-11e9-8ca2-e9258e11e152.png)

**Comment by justrealmilk** [comment]
Remember to put on Sunscreen when jumping into a Strike
_Gotta watch for Solar Burn_

**Comment by vthornheart-bng** [comment]
To save me some time when I file the bug, what's erroneous in there?  What was the expected vs. actual?

**Comment by justrealmilk** [comment]
Record item's displayProperties content mismatches record's objective data.

**Comment by vthornheart-bng** [comment]
Ah, interesting - thanks, I'll have to take a look in there!

**Comment by vthornheart-bng** [comment]
TFS 811428
