### ISSUE TITLE
Ban Member doesn't appear to be storing the comment you input.

### ISSUE THREAD

**Issue by ghost** [Bungie-net/api#932]
![Screenshot](https://user-images.githubusercontent.com/7931231/59166617-5c752800-8ae0-11e9-8f96-8697444d761d.png)

The top is the comment that the API has stored when I did a GetBannedMembersOfGroup call.  The @ leadership bit at the bottom shows the reason text I submitted.  I checked my inputs and I am definitely inputting something to it.

As a test, I went to ban myself just to see the inputs.  It's sending this:
`{"length":"8"}{"comment":"test"}`

The top part of the screenshot shows the ban duration expires in the year 9999 so I assume my input is fine, unless that is just a default?

For reference: 

https://bungie-net.github.io/multi/operation_post_GroupV2-BanMember.html#operation_post_GroupV2-BanMember

https://bungie-net.github.io/multi/schema_GroupsV2-GroupBanRequest.html#schema_GroupsV2-GroupBanRequest

**Comment by Akumati1435** [comment]
Do you know if this data is lost?   I assume this won't be looked at much until after Sept 17th.

**Comment by vthornheart-bng** [comment]
Ah, good question - I have not had a chance to investigate!  I've been knee deep in cross save, and this fell off my radar.  I get the strong feeling that, if it's not coming back there, this is a bug and the comment is not actually being saved.  I'll file a bug for us to investigate when we get a window of time to do so.  Until then, if you need to hit someone up about why they were banned, one workaround would be to send them a private message through BNet.

**Comment by vthornheart-bng** [comment]
TFS 810013
