### ISSUE TITLE
GetBannedMembersOfGroup issue

### ISSUE THREAD

**Issue by ghost** [Bungie-net/api#933]
I tried the api discord first for this because it could be something I'm doing here to cause this.

For reference: https://bungie-net.github.io/multi/operation_get_GroupV2-GetBannedMembersOfGroup.html#operation_get_GroupV2-GetBannedMembersOfGroup

Someone applied who said they were banned so I figured I'd check what comment I put in when banning him.  There were no comments (#932) and the bans only went back a few months.  The clan I checked has been around a long time so there should be more than what it's sending me.

Then I realized this might be shown on bungie.net so I went there to check too.  Bungie.net shows the exact stuff from the first page of bans I'm getting and no more.  So you'd think it's the actual list of users, but it's exactly 50 people for the 2 other clans of mine that I've checked too.  It just doesn't seem likely that this is accurate.

URL's tried (successes all return the same data):
`
URL:https://www.bungie.net/platform/GroupV2/2846113/Banned/?currentpage=1
URL:https://www.bungie.net/platform/GroupV2/2846113/Banned/?currentpage=2
URL:https://www.bungie.net/platform/GroupV2/2846113/Banned/?currentpage=1&groupId=2846113
URL:https://www.bungie.net/platform/GroupV2/2846113/Banned/?currentpage=2&groupId=2846113
URL:https://www.bungie.net/platform/GroupV2/2846113/Banned/?currentpage=2

Failures:
URL:https://www.bungie.net/platform/GroupV2/2846113/Banned?currentpage=1
URL:https://www.bungie.net/platform/GroupV2/2846113/Banned/2/
`

Am I doing something wrong or is this broken?

**Comment by vthornheart-bng** [comment]
Ah, definitely sounds like you hit a bug with paging on this endpoint - thanks (and sorry for the delay in responding!), I'll file a bug!

**Comment by vthornheart-bng** [comment]
TFS 811306
