### ISSUE TITLE
Quick play and competitive modes [question]

### ISSUE THREAD

**Issue by SarKurd** [Bungie-net/api#934]
I'm not a big fan of PVP so i don't know which modes are in quick play and which modes are in competitive

I appreciate if someone share the list of modes with their respective activity type

Also i think it would be great if we could have a slack, spectrum or discord channel to ask these silly questions :-D

**Comment by floatingatoll** [comment]
You may find the Discord API server useful: https://discord.gg/WJDSUgj

**Comment by Thom-Roberts** [comment]
List of game modes can be found here: https://bungie-net.github.io/multi/schema_Destiny-HistoricalStats-Definitions-DestinyActivityModeType.html#schema_Destiny-HistoricalStats-Definitions-DestinyActivityModeType

**Comment by SarKurd** [comment]
@floatingatoll thanks how come i didn't about this lol
@Thom-Roberts it doesn't say which ones are quick play and which ones are comp

**Comment by floatingatoll** [comment]
You should be able to search for the comp/qp entries from that list (69, 70
i think?) in this GitHub and find the writeup.

Thorn, if you're willing, adding that list of modes as a text note to 69,
70 would be a kindness for developers.

**Comment by vthornheart-bng** [comment]
Oy, yes totally - that's a good call.  This is definitely one of those aspects of the API that is both extremely difficult to discover on one's own and not well documented.
