### ISSUE TITLE
Adding list of modes as a text note to game modes 69, 70

### ISSUE THREAD

**Issue by floatingatoll** [Bungie-net/api#935]
Repeating https://github.com/Bungie-net/api/issues/934#issuecomment-500576275 — It would be handy to have modes 69 and 70 list in the developer text note whatever modes they contain, for those wondering what "Quickplay" and "Competitive" are.

**Comment by vthornheart-bng** [comment]
Good call!  Thank you!  Will file a bug momentarily!
