### ISSUE TITLE
Spider returning quest items from getVendors

### ISSUE THREAD

**Issue by xenodus** [Bungie-net/api#936]
getVendors for Spider (863940356) started returning the following quest items over the past weekend. Had to apply a quick fix to my app to accommodate the change. Not sure if intended.

- The Bits (706346979)
- The Ruckus (570362378)
- The Midnight Special (520901579)
- The Jerky (3777789414)
- The Bad News (3977277090)
- The Good News (1956212994)
- A Lion (2864267637)

**Comment by floatingatoll** [comment]
Those are valid quest items during the Drifter Quest, and you can
technically buy one of them if you get extraordinarily bad luck with a
certain RNG!

**Comment by vthornheart-bng** [comment]
As a clarification question - when you're in-game for the character you're querying vendors for, do you see those as available to purchase?  Just to make sure before I file a bug.

**Comment by xenodus** [comment]
Yes, they are visible! Attached a screenshot for reference.

![image](https://user-images.githubusercontent.com/9331270/61340020-12b3f600-a873-11e9-9dcc-6fc3b2b8c50e.png)

**Comment by vthornheart-bng** [comment]
Ah, cool - yes, if they're showing up in game then it's good that they're showing up with the Vendors request!

I get the feeling that I may be potentially misunderstanding the nature of the issue though.  Let me know if I'm not seeing the forest for the trees!
