### ISSUE TITLE
Menagerie details in PGCR

### ISSUE THREAD

**Issue by mattybeard** [Bungie-net/api#937]
When Gambit dropped, it was amazing and contains extra details in the PGCR around blockers and damage etc.

Is there a chance of more information in a PGCR from Menagerie? Maybe rounds completed? Or boss damage?

Just anything that would make Mengerie more unique from a PGCR perspective, much like Gambit.

**Comment by vthornheart-bng** [comment]
I would like that as well - unfortunately we don't have any special Menagerie-specific stats being saved off.  It may be too late to add it to Menagerie, but I will bring up the idea of adding more stats for upcoming modes.  Unfortunately, as you've seen over the past couple of years, Stats work competes with a bunch of other mission critical work and often falls short compared to that work: so I can't promise that we'll have them.  But I'll at least make an effort to bring it up and make sure people are thinking about it.
