### ISSUE TITLE
Internal server errors for 1 specific user

### ISSUE THREAD

**Issue by ghost** [Bungie-net/api#939]
This has been happening every run for my activity loader since 6/11/2019 3:23:08 AM PT

`Errored out on: Velton#1370;  mmemberid:4611686018468602035; charid: 2305843009299309015
-- DBLoader-Activities.exe 6/11/2019 3:23:08 AM --
HttpStatusCode was not OK.  It was a '500' (InternalServerError)
-- DBLoader-Activities.exe 6/11/2019 3:23:09 AM --
Errored out on: Velton#1370;  mmemberid:4611686018468602035; charid: 2305843009325235761
-- DBLoader-Activities.exe 6/11/2019 3:23:09 AM --
HttpStatusCode was not OK.  It was a '500' (InternalServerError)`

It hits the /Destiny2/{membershipType}/Account/{destinyMembershipId}/Character/{characterId}/Stats/Activities/ end point

He's got a last played date of 6/12/2019 9:32:09 PM PT.  I figured that may be important because he has logged in after it started.

[The api tester also fails.](http://destinydevs.github.io/BungieNetPlatform/docs/API-Test#/Destiny2/GetActivityHistory/p:membershipType=4,destinyMembershipId=4611686018468602035,characterId=2305843009299309015/q:mode=0)

**Comment by mattybeard** [comment]
Are you still getting a response body though regardless of StatusCode? 

I've just tested that link and even though I hit a 500 status, I have a response body.
```
{
    "ErrorCode": 1665,
    "ThrottleSeconds": 0,
    "ErrorStatus": "DestinyPrivacyRestriction",
    "Message": "The user has chosen for this data to be private.  No peeking!",
    "MessageData": {}
}
```

For more info, I'd check out [https://github.com/Bungie-net/api/issues/895](https://github.com/Bungie-net/api/issues/895)

**Comment by floatingatoll** [comment]
Thorn, is this an instance where you’d prefer to return another HTTP code?

403 Forbidden would be good

**Comment by Akumati1435** [comment]
thanks @mattybeard.  i assumed that if it returned an InternalServerError it wouldn't return any json.  i moved some code around and it's back to doing what it should.

**Comment by vthornheart-bng** [comment]
Ah yeah, totally makes sense.  I'll file a bug, thank you all!
