### ISSUE TITLE
Subclass perks not included in the ItemComponents response for Profiles

### ISSUE THREAD

**Issue by v-fedorov** [Bungie-net/api#94]
To replicate

```
Platform/Destiny2/2/Profile/4611686018433723819/?components=100,205,302,200,304
```

`2305843009262875275 ` is the only character I have played D2 on so far.

using the bucket for subclass (`3284755031`) I am able to get the itemInstance of my equipped subclass  `6917529029292377589 `

That ID isnt in the block for itemComponent perks, but strangely the other 2 characters have their instance on there

**Comment by vthornheart-bng** [comment]
Hmm, I finally got around to looking into this - I'm not able to reproduce it, but this was filed a while ago.  It could be that our various un-redaction efforts have repaired this problem (particularly if your equipped subclass was one of the ones we had redacted on day 1).  Let me know if you're still running into it - I tried with the profile in question and saw the perks and talent grid info for all 3 character's equipped subclasses.
