### ISSUE TITLE
problem with vendorLocationIndex: petra (1841717884)

### ISSUE THREAD

**Issue by michabbb** [Bungie-net/api#940]
hi there,

when i do a lookup of petra, i get:

`
{
    "Response": {
        "vendor": {
            "data": {
                "canPurchase": false,
                "vendorLocationIndex": 0,
                "vendorHash": 1841717884,
                "nextRefreshDate": "2019-06-18T17:00:00Z",
                "enabled": true
            },
            "privacy": 2
        }
}
`  

but `vendorLocationIndex:0` does not help to find one of these locations:

`SELECT CASE WHEN id < 0 THEN id + 4294967296 ELSE id END AS id, json FROM DestinyLocationDefinition WHERE json like '%1841717884%'`

ids from DestinyLocationDefinition:

3206676663
1378079612
2097628065

so, please: what is the correct way to find petras (or any others vendors) location ?

thanks!

**Comment by floatingatoll** [comment]
If you check all other vendors, does this issue affect Petra only?

**Comment by michabbb** [comment]
@floatingatoll most vendors have a fixed location, so i am more interested in petra´s location 😏 
but, spider and banshee show me `vendorLocationIndex: 0`, too.

**Comment by floatingatoll** [comment]
Petra’s location will not be valid in the API for the purpose you seek, due to a known game-side design flaw that breaks that specific API value:

https://github.com/Bungie-net/api/issues/704

(Deferring to Bungie on the other two.)

**Comment by michabbb** [comment]
@floatingatoll thanks for the info. my main intesion is, to find out, which curse week we have. i know there is a 3 week cycle, but you are able to get this from petras location, i hoped to get this by api.

so i guess i have to cycle my without api.

if i may ask: beside the curse-week, i also wanted to find out, which "ascendent challange" is active.
so i have found [this reddit posting](https://www.reddit.com/r/DestinyTheGame/comments/9yv1cv/ascendant_challenges_thru_spring_2019/).

i don´t get the logic here 🙈 😕 
according to what i know:

- we are in week 1 of the dreaming city (everything normal)
- we are in week 3 of season 7 

but the reddit posting shows only the challanges till week5, what happens after that ?
does the cycle go on the same way like it did in the last season ? so week6 would be
the same challange as in season6 - week6 ??

**Comment by michabbb** [comment]
it´s not logical to me, but would be happy if someone you tell me, if i get this right. according to #704  i checked the response of `/Vendors/1841717884/?components=400%2C402%2C300%2C301%2C304%2C305%2C306%2C307%2C308%2C600` and i was able to find the itemhash `2103539490` inside `currencyLookups` . because that´s the only item and that item tells us, where to find petra, it´s a strange way to find out, where she is. is this a way it works ? it looks to me like that.

**Comment by vthornheart-bng** [comment]
Whoa, that blows my mind - very clever!  I wonder though if you can depend on that - for instance, if you continue that quest you wouldn't have it anymore.  But it might be a good workaround for some players.

(sorry I've not been responding to Github issues well the past few days, we are super swamped with work right now - but I just saw this come in and I have to say that's a clever workaround for our lack of data about Petra's true location!)

**Comment by michabbb** [comment]
@vthornheart-bng thanks for your 🌷 but it´s not my idea, it´s mentioned in #704 

https://github.com/Bungie-net/api/issues/704#issuecomment-443207941

and you already said, that this is "clever" 🙈 😁 

can you give me an adivse howto get the current ascendent challange ?
is there any way via api or do i have to use some kind of rotation like it´s used
at the escalation protocol ? thanks !

**Comment by floatingatoll** [comment]
it's still clever, i totally didn't understand it the first time

#726 notes that the same problem applies to ascendant challenge — so if you
can figure out a hack like that one, i bet lots of people would like to
know it

**Comment by vthornheart-bng** [comment]
Ha!  How quickly I forget!

Unfortunately I don't know a fix or workaround for ascendant challenge either.  We haven't had time to investigate it unfortunately, so I've got no current proposal for a workaround. :(

**Comment by michabbb** [comment]
Barney would say: "challange accepted" 😂 but in fact, i have no idea. @floatingatoll many thanks for the hint with #704. if i will ever find something, i will post it. 
@vthornheart-bng okay, thanks anyway for responding !

**Comment by michabbb** [comment]
hey guys, just an idea, please let me know, what you think.
if i call petra, i see the bounty itemhash `3207732940` there.

if i search the database (in german, sorry):

`SELECT CASE WHEN id < 0 THEN id + 4294967296 ELSE id END AS id, json FROM DestinyInventoryItemDefinition WHERE json like '%Aszendenten-Herausforderung%';`

i see these challanges:

2256480378
2338128705
3118323621
3207732940
3337739523
128980839
542328999
1147672297

every item-data has a `stackUniqueLabel` like:

2256480378: `open_world.d2.v400.dreaming_city.capstone.dc_capstone.decurse_legs`
2338128705: `open_world.d2.v400.dreaming_city.weekly_asc_chal.weekly_bounties.asc_challenge_heist`
3118323621: `open_world.d2.v400.dreaming_city.weekly_asc_chal.weekly_bounties.asc_challenge_dive`
and so on.

so: if we could assign the challanges (by name) to these `stackUniqueLabel` - might this be a solution ??? 🤔

**Comment by floatingatoll** [comment]
“Heist”, “Dive” - are those specific challenges to you as a human being who knows the ascendant challenges? (I don’t know them, but I mean in a not-algorithm plain-human knowledge sense)

**Comment by michabbb** [comment]
let´s say i have a website where each challange is explained or i have a youtube link for every challange. you should be able to link these urls to these names:

[asc_challenge_heist]
[asc_challenge_dive]
[asc_challenge_maze]
[asc_challenge_purify]
[asc_challenge_swat]
[asc_challenge_tower]

why not.

**Comment by floatingatoll** [comment]
I just meant - what is “swat”? Is that a specific challenge?

**Comment by michabbb** [comment]
@floatingatoll yes it is.  for me this is working. background: as many others: with a weekly reset i want to provide my people with regular infos, the same stuff you see at the reddit weekly postings. i have a link to a german guide for every challange, the only thing i have todo now is: assign each name to my urls and that´s it. whenever the challange/bounty changes, i can provide a guide to the challange. that´s all i wanted i am sure its working that way.

**Comment by floatingatoll** [comment]
Huh — this looks like a localization-not-provided generated label —
"2256480378: open_world.d2.v400.dreaming_city.capstone.dc_capstone.decurse_legs"

Thorn, should these have the in-game localized text present in the manifest DB?

**Comment by vthornheart-bng** [comment]
Oh yeah, you're looking at the stackUniqueLabel.  Unfortunately, those will always be non-localized - they're whatever a designer wants to put in there.  However, I do think that they probably ought to be anonymized somewhat: what really matters is that they're unique.  These will probably end up being anonymized at some point in the future.

**Comment by floatingatoll** [comment]
To take a stab at translating that means "these are leaking data
unintentionally from the game internals and will be reduced to gibberish to
prevent that", so you'll want to focus on building your own hand-crafted
mapping rather than hoping for improvements.

**Comment by michabbb** [comment]
sorry i have to say it: @vthornheart-bng the fact that i only see the "sales" of petra when the char is logged into the game and inside the dreaming city, makes it impossible to automize anything. i really hope that this whole petra thing gets fixed in the near future. right now, i have to start my box, log into the game, fly to the city, go to petra, grab the bounty, than i am able to get the infos via API where petra is and what the challange is... holy 🐄  😖

**Comment by floatingatoll** [comment]
I remember seeing Bungie API team (which is 2 people iirc) feeling terrible about this some time ago, saying so openly to us, and noting that they’d discussed it with the game team and the constraints of D2 might not permit a fix at all. So they are at least aware of how we feel here :(

**Comment by vthornheart-bng** [comment]
Indeed, unfortunately what we need for a fix would require a significant change in how Petra is implemented in the game, which they're not going to be able to provide.  I did speak with folks on the game side after this, and hopefully future vendors will not be set up in this way: but we are not going to have a fix for Petra herself given the scope of changes that would be required.

**Comment by michabbb** [comment]
To be clear: does that include, that there is also no chance to add any kind of info to the milestones? Let's say, the milestones would also include "do the ascendet challange - grab it from Petra at the place XYZ"

If that could be added, maybe there is no need for a change at the vendor itself. Just an idea.

**Comment by vthornheart-bng** [comment]
I dig that idea, and I wish we could provide it!  Unfortunately, the mechanisms that choose what a vendor has for sale (and thus, which challenge is active) are intrinsically tied to the mechanism that determines whether the vendor is available, and we don't have a good way to bypass that without changes that touch game-side code.  As a result, we don't have a good way to consistently return that information right now given our schedule and the nature of the changes we'd need to make to get that data down to you consistently.

**Comment by michabbb** [comment]
@vthornheart-bng 🆗 😕 anyway: thanks for your time and all the info to that issue 👍

**Comment by vthornheart-bng** [comment]
<3 I'm sorry that this sucks.  My hope is that at least, though we can't fix Petra, we raised enough of a stink about it that we won't get vendors that behave this way again.
