### ISSUE TITLE
CORS Error: Response to preflight request doesn't pass access control check

### ISSUE THREAD

**Issue by CTOverton** [Bungie-net/api#941]
I'm trying to get the database from a get request using axios within a react app for browser. 

I can make a call to get the manifest just fine but when I try and get the database file itself I get blocked by CORS

> Access to XMLHttpRequest at 'https://www.bungie.net/common/destiny2_content/sqlite/en/world_sql_content_5c2e1bf00371d79d06bc403ef84a06dc.content' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

![image](https://user-images.githubusercontent.com/33900517/59545534-8918ad80-8eed-11e9-81a6-fec42f6d010a.png)

The call I'm making looks like this: (I defaulted my api key for all axios requests so yes I didn't forget that)

```
const responseStream = await axios({
            method: 'GET',
            url: "https://www.bungie.net/common/destiny2_content/sqlite/en/world_sql_content_5c2e1bf00371d79d06bc403ef84a06dc.content",
            responseType: 'stream',
        });

        console.log(responseStream);
```

I also have this set on my bungie app which I found worked for some people on this github issues.
![image](https://user-images.githubusercontent.com/33900517/59545568-2247c400-8eee-11e9-824f-24e82ca46bf8.png)

What am I missing?

**Comment by floatingatoll** [comment]
Does setting your Origin domain to “localhost” (in your final screenshot) fix it?

**Comment by Thom-Roberts** [comment]
I haven't attempted this with the manifest endpoints, but trying to get any other endpoint without a trailing slash will get cors errors. Try adding a slash after content?

**Comment by CTOverton** [comment]
@floatingatoll yes I've tried `http://localhost:3000`, `localhost`, `https://localhost` but none seem to work.
@Thom-Roberts good suggestion but that didn't seem to work either. 

The weird thing is I can tell the origin is correct since if I change the origin on bungie.net then my initial get request to /Destiny2/Manifest fails as the origin isn't correct, but no matter what the next request to get the actual file is always blocked by cors...

**Comment by CTOverton** [comment]
**The Solution**

I had defaulted the API key to all axios requests, meaning when I did the call for the actual database I was including my api key in the header. I'm not sure if this is how it's suposed to work but I removed the api key from that call and now it works just fine...
