### ISSUE TITLE
Icon Request for Presentation Node: 332314936

### ISSUE THREAD

**Issue by t3rr11** [Bungie-net/api#942]
Was wondering if an icon could be declared in the API under this presentation node. Here is a little bit of my project it uses the presentation nodes to create the triumphs menu:
![image](https://user-images.githubusercontent.com/2139233/59558494-7e1b6580-9032-11e9-957e-9ce5c7dfea8a.png)

But because the events presentation node has no image it errors like this:
![image](https://user-images.githubusercontent.com/2139233/59558495-82478300-9032-11e9-8dc6-2b50823ee2ab.png)

I was curious if the presentation node `332314936` could get it's respective icon as it has the variable `"hasIcon":false`. If it's not possible i can create a work around for this one category but i don't have access to the image: 
![image](https://user-images.githubusercontent.com/2139233/59558497-870c3700-9032-11e9-9e7a-9930dfd563c6.png)

**Comment by justrealmilk** [comment]
For parent nodes with a single child, I’d suggest omitting the children row.

**Comment by t3rr11** [comment]
Thank would work well too! I mean really there is no need for a selection when there is only one.

**Comment by vthornheart-bng** [comment]
Hmm... let me give this some thought.  I hate having you guys add special logic for this situation, but I also don't want to break future use cases of presentation nodes with too many assumptions.  I'll file a bug to consider this further when I get time to address it!

**Comment by vthornheart-bng** [comment]
TFS 811408
