### ISSUE TITLE
No way to find how many runes a player have 

### ISSUE THREAD

**Issue by Wobow** [Bungie-net/api#943]
I'm trying to get the number of runes (for the chalice of opulence) of each type a player have in his inventory. 

Even though the runes are described as materials, they don't appear in the player's inventory. The only think I can get is the runes I can insert in each slot of the chalice (through the chalice instance), but it doesn't tell me how many in total the player have.

Is there something I missed or is the information obfuscated ?
Thanks !

**Comment by vthornheart-bng** [comment]
Oh, interesting - it may be that this was implemented as something other than items (which is a bit odd, as pretty much everything is implemented as items!).  I'll have to do some investigating on this!

**Comment by vthornheart-bng** [comment]
TFS 811411
