### ISSUE TITLE
Addind a locale query parameter to Destiny2.GetDestinyEntityDefinition

### ISSUE THREAD

**Issue by Wobow** [Bungie-net/api#944]
In the current state of the api, it doesn't seem possible to get a single item definition in a different language than english.
The only way to get single item descriptions in another language is to load the entier manifest, which is not ideal in some cases.

Is it possible to add a ?locale=<locale> or /{locale} to the endpoint ?

**Comment by vthornheart-bng** [comment]
Unfortunately this is undocumented, but you can pass ?lc={locale code} and that'll give you what you seek!  I need to file a bug to add this to the documentation.  We implicitly allow that querystring parameter for every endpoint, but it's not explicitly mentioned anywhere.
