### ISSUE TITLE
Ocasos

### ISSUE THREAD

**Issue by ZxFrankxZ** [Bungie-net/api#946]
Hola, he estado revisando y usando la api pero no encuentro la manera de listar todos los tiempos mas rapidos de los ocasos entre todos los personajes, he conseguido hacerlo de uno de los personajes pero no se como ver el tiempo mas rapido de cierto ocaso entre los 3 personajes, es decir, 
Hechicero: 
Piramidion ---> 10:50
Cubil Hueco ---> 8:50

Cazador: 
Piramidion ---> 9:30
Cubil Hueco ---> 10:55

Titan: 
Piramidion ---> 12:45
Cubil Hueco ---> 14:20

¿Como puedo hacer que para el esos ocasos muestre el tiempo mas rapido sin tener que estar revisando los 3 personajes?

**Comment by ckhicks** [comment]
If my Google-fu is correct, it looks like this user is trying to find the fastest strike time between characters without having to iterate over each one. 🤔

**Comment by cowgod** [comment]
Yep, correct. I'll translate his question:

> Hello, I've been searching and using the api, but I can't find the way to list all the fastest times of strikes among all my characters. I've managed to do it for one character, but I don't know how to see the fastest time for a certain strike among the three characters. In other words,
> 
> Warlock:
> Pyramidion ---> 10:50
> Hollowed Lair ---> 8:50
> 
> Hunter:
> Pyramidion ---> 9:30
> Hollowed Lair ---> 10:55
> 
> Titan:
> Pyramidion ---> 12:45
> Hollowed Lair ---> 14:20
> 
> How can I make it so that for each strike, it shows the fastest time, without having to check each character [for each one]?

**Comment by floatingatoll** [comment]
I don't think there is an account-wide leaderboard entry for these times,
because the reason everyone cares about them is due to a secret reward. API
team, before you pursue implementing this, I recommend discussing "After
the Nightfall" with your stats wizard.

**Comment by mistahj67** [comment]
@ZxFrankxZ feel free to check out https://warmind.io/nf for your personal nf stats and times. They are all accurate and very fast to check.

**Comment by vthornheart-bng** [comment]
Lo siento, pero no tengo los datos en este momento.

Hablaré con la gente y veré si se puede agregar en el futuro, pero no puedo prometer si se puede agregar o cuándo. ¡Mis disculpas!

**Comment by vthornheart-bng** [comment]
TFS 811415
