### ISSUE TITLE
Crimil's Dagger metadata says it is can be reacquired.

### ISSUE THREAD

**Issue by SunburnedGoose** [Bungie-net/api#948]
The collectable state for this item says that it can be reacquired from the collections.  In game, it cannot.

 ```      
       if (
          item.collectibleState !== null &&
          !(item.collectibleState & DestinyCollectibleState.NotAcquired) &&
          !(item.collectibleState & DestinyCollectibleState.PurchaseDisabled)
        ) {
          return true;
        }
```

![image](https://user-images.githubusercontent.com/984608/59950012-6a10a300-943a-11e9-9113-99ee85f7cec2.png)

**Comment by floatingatoll** [comment]
Which item ID - more specifically, is this the Y1 variant or Y2 variant (or is it a Y2 curated, if such exists)?

**Comment by SunburnedGoose** [comment]
https://data.destinysets.com/i/InventoryItem:4292849692

All I see is this Black Armory drop in Destiny Sets.  Was there a D2Y1 version?

**Comment by SunburnedGoose** [comment]
There is a D2Y1 version. I'll follow up w/ the user to get a screenshot and see which one he is going on about.

**Comment by floatingatoll** [comment]
Yeah, it has an Osiris icon. There’s a Black Armor one?

http://db.destinytracker.com/d2/en/items/3649055823-crimils-dagger

http://db.destinytracker.com/d2/en/items/4292849692-crimils-dagger

**Comment by SunburnedGoose** [comment]
Yeah, the second link is Black Armory.

**Comment by floatingatoll** [comment]
Glad I could (probably) help - it looks like a bunch of Y1 came back as Y2 - good luck!
