### ISSUE TITLE
Confusion regarding gearset/armor sets

### ISSUE THREAD

**Issue by megannnjay** [Bungie-net/api#950]
I'm pretty new to all of this, so I apologize if this isn't the right place.

I've been trying to find a way to pull the hashes of armor pieces that make up particular sets (e.g. Leviathan, Crucible, Iron Banner, etc.). At first I thought it'd be found as [gearset ](https://bungie-net.github.io/multi/schema_Destiny-Definitions-DestinyItemGearsetBlockDefinition.html#schema_Destiny-Definitions-DestinyItemGearsetBlockDefinition)under [DestinyInventoryItemDefinition](https://bungie-net.github.io/multi/schema_Destiny-Definitions-DestinyInventoryItemDefinition.html#schema_Destiny-Definitions-DestinyInventoryItemDefinition) but there's an issue open [here](https://github.com/Bungie-net/api/issues/120) which seemed to indicate I wouldn't be able to find it that way (and when I experimented by making a request for the legs from Crown of Sorrows, it didn't include gearset in the json). 

The other way I thought I could do it was going in through Collectibles since they're sorted by set there, but I was having some trouble since I didn't want it for a particular character/account and the request seems to [require](https://bungie-net.github.io/multi/operation_get_Destiny2-GetCollectibleNodeDetails.html#operation_get_Destiny2-GetCollectibleNodeDetails) that. 

Any guidance (even if it's just confirmation that getting the information through the API isn't possible) would be very much appreciated

**Comment by vthornheart-bng** [comment]
(First, I apologize to everyone for being MIA lately!  I'm knee deep in Cross Save work, but I think this may be a quick answer so I'm trying to jump in over lunch break)

Greetings!  This is a good question, and fortunately this was indeed made a bit easier by collectibles.  If you're looking in particular for the hashes themselves and other static info, you can skip making any live queries by grabbing *just* the destiny definitions and then find the ["Presentation Node" definition](https://bungie-net.github.io/multi/schema_Destiny-Definitions-Presentation-DestinyPresentationNodeDefinition.html#schema_Destiny-Definitions-Presentation-DestinyPresentationNodeDefinition) you're looking for, and scrape all of the [collectible definitions](https://bungie-net.github.io/multi/schema_Destiny-Definitions-Collectibles-DestinyCollectibleDefinition.html#schema_Destiny-Definitions-Collectibles-DestinyCollectibleDefinition) it is pointing to.

To grab these static definitions, it's a bit of a multi-step process unfortunately: but the nice thing is that once you set it up, you'll have access to this data as JSON that you can store and use at will.

First, call the [GetDestinyManifest endpoint](https://bungie-net.github.io/multi/operation_get_Destiny2-GetDestinyManifest.html#operation_get_Destiny2-GetDestinyManifest) to get information about where the static databases are located.

This will give you an object that has a jsonWorldContentPaths property.  That property is keyed by the language, with the value being a path to a JSON file hosted on Bungie.net that contains all of the Destiny Definition data.  Store this locally (don't download it every time you need it - it's huge!), and open it up and inspect it.  You'll find that it's set up such that every type of entity has its own sets of definitions with its own properties.  Amidst that you'll find the Presentation Nodes mentioned above, and those will point to Collectibles, and the collectibles themselves will have item hashes.  It takes some time to get used to using this data, but give it a look and hopefully it'll give you what you seek!

**Comment by TorKallon** [comment]
If you are only knee deep then I'm not sure what you are complaining about.
:)

**Comment by vthornheart-bng** [comment]
Ha :D

**Comment by vthornheart-bng** [comment]
Closing this for now - let me know if you are still experiencing issues!
