### ISSUE TITLE
Icons licensing

### ISSUE THREAD

**Issue by louis-bompart** [Bungie-net/api#952]
***Context:***
I'm working on a Discord Rich Experience link for Destiny 2 and I'd like to use activity icons to hint what's the player's actually doing. However, I need at the very least 512x512 icons.

Seeing that #643 seems to be inactive, I'm considering scaling up the icons before sending to my discordApp, which lead to my actual question:

How the icons are licensed? Are they under the license of the Repo (i.e. derivative work allowed)

> *TL;DR:* I want big icons. I want to scale them. May I do so, pretty please ? 😄

**Comment by Tetron-bng** [comment]
Review the terms of use, especially the 'game content usage rules.'

https://www.bungie.net/7/en/Legal/Terms

**Comment by vthornheart-bng** [comment]
Ah, thank you Tetron!

Importantly:

"You may use game footage, screenshots, and other elements of Bungie games that are owned by Bungie (“Bungie Content”) to create your own content (“Your Content”) provided that you must comply with these Terms and all of the following restrictions (the “Content Usage Rules”):"

Check out those terms below that line, and if they check out for your use case then it should be fine.

**Comment by vthornheart-bng** [comment]
And of course, make sure you're aware of the other limitations set by the terms of use!  It's definitely worth a read for anyone making an app or using game content!

**Comment by louis-bompart** [comment]
Thanks a lot for your answers! I wasn't sure to which ToS the icons are under, this answers that.
