### ISSUE TITLE
List of discrepancy with OAS2

### ISSUE THREAD

**Issue by louis-bompart** [Bungie-net/api#953]
1. There's no component section in OAS 2: https://swagger.io/docs/specification/components/
So `#/components/schemas/Exceptions.PlatformErrorCodes` (and the likes) cannot be resolved properly.

To fix it, replace all instances of `#/components/schemas` by `#/definitions` 

2. Items don't have a description in OAS2: https://swagger.io/specification/v2/#itemsObject.

To fix, remove all of them (the description can be found by following the `$ref`, so we're cool)

3. deprecated is not available on parameters in OAS2: https://swagger.io/docs/specification/2-0/describing-parameters/

To fix, remove the deprecated those occurrences (I spotted only one)

The editor I used:http://editor.swagger.io/#/

**Comment by vthornheart-bng** [comment]
Ah, thank you!  I'll file a bug for this.

**Comment by vthornheart-bng** [comment]
TFS 811423
