### ISSUE TITLE
Can i invite player to my fireteam through api?

### ISSUE THREAD

**Issue by Arasfon** [Bungie-net/api#955]
I am trying to make custom Discord RPC for Destiny 2 (PC), but i don't know how to invite players to fireteam. Can i invite or player himself must invite?

**Comment by floatingatoll** [comment]
The player must invite in-game. What’s a “Discord RPC”?

**Comment by Arasfon** [comment]
Discord rich presence, you can see, what player is playing, and join his party, or spectate, great feature.
https://discordapp.com/rich-presence


> The player must invite in-game. What’s a “Discord RPC”?
> […](#)
> On Jul 4, 2019, at 22:35, Egor Arasfon ***@***.***> wrote: I am trying to make custom Discord RPC for Destiny 2 (PC), but i don't know how to invite players to fireteam. Can i invite or player himself must invite?

**Comment by vthornheart-bng** [comment]
Unfortunately, we can't provide Fireteam creation through the API at this time.  Sorry about that!

**Comment by Arasfon** [comment]
@vthornheart-bng Will it be available in future?

**Comment by vthornheart-bng** [comment]
It is unfortunately unclear at the moment.  There is some backend work that would need to be done (both on our side and the game side) before we could safely provide an endpoint purely through API mechanisms.  Unfortunately, particularly on the game side that's an expensive/time consuming ask, so it's sitting in the backlog at the moment.

**Comment by ArkahnX** [comment]
Would just like to add that with more "write" style API features being requested (grabbing bounties, fireteams) it was brought up before that theoretically the API could allow for these actions, but then have user confirmation in the Destiny Companion app.

Hopefully something like that could be made in a future where there is infinite time to work on the API

**Comment by vthornheart-bng** [comment]
Indeed, we do want to add that in!  There's some more hardening we were going to do and then let it loose back when Tetron was here, but being a bit short staffed since then it's ended up in the black hole of our backlog.  So close to being finished, but never high enough priority to bump past the things that "must absolutely be done right now". :(

I still want to make this come to pass!  I just don't know when it's going to go from "would be great to finally finish up" to "we actually have time to finish it up". :(

**Comment by floatingatoll** [comment]
@vthornheart-bng If you're willing to update on the July 5th comment to clarify "let it loose" — let _which_ aspects of 'write' API discussed here loose, specifically? — then that would be useful for various folks reading up historically, e.g. @rraziel.

**Comment by vthornheart-bng** [comment]
Ah, so this discussion shifted toward "write actions in general" later on in this thread.  When I talk about write actions, I'm referring specifically to actions such as picking up bounties, plug insertion, and other write actions of that nature.  The inability to provide Fireteam access is still true.

**Comment by braincomb** [comment]
+1 for Fireteam API. I was looking into creating a real-time LFG tool, because working with currently available 3rd party tools is a huge hassle, but was disappointed to see that Fireteam API is very limited and doesn't have an invite feature.

**Comment by ckhicks** [comment]
While unsupported...it _is_ possible to create/close a Fireteam via the same way the Bungie.net website handles it:

```{
  activityType: "5",
  isPublic: true,
  locale: "en",
  ownerCharacterId: "2305843009264704477",
  ownerHasMicrophone: true,
  platform: "2",
  playerSlotCount: "1",
  scheduledTime: "2019-10-21T14:00:00.000Z",
  title: "My Great Fireteam",
}```

Open: `https://www.bungie.net/Platform/Fireteam/Clan/0/Create/?lc=en&fmt=true&lcin=true`
Close: `https://www.bungie.net/Platform/Fireteam/Clan/0/Close/17576289/?lc=en&fmt=true&lcin=true`

Not that I've, uh, tried it out to be sure, of course. 👼

**Comment by floatingatoll** [comment]
Note that the above-cited fireteam API, by its documentation anyways, does not control in-game fireteams:

https://www.bungie.net/en/Help/Article/44705

> Players can use this Fireteam chat to privately share their PSN ID, Xbox Gamertag, or Blizzard BattleTag information to find each other and join the Fireteam in Destiny 2.

**Comment by ckhicks** [comment]
^ Correct, this is only for the web version of Fireteam creation, which then has to be accepted by each player before creating an in-game Fireteam. Invites being sent via the API isn't something I've played with but that's an interesting thought as well...
