### ISSUE TITLE
Gambit activity type missing icon

### ISSUE THREAD

**Issue by t3rr11** [Bungie-net/api#957]
In the PGCR's for gambit activities they give reference to activity mode types under the `"activityTypeHash": 2490937569` which have the missing icon value even though there is an activity icon in the manifest under the ActivityModeDefinition: `1848252830`

Could these get linked up so the PGCR for gambit return an icon rather than the missing icon?

**Comment by vthornheart-bng** [comment]
I think for Gambit activities that makes a lot of sense, as Gambit activities can only be played for Gambit.  Historically I've avoided trying to create a manual mapping of mode or type data to the Activity itself, as activities in Destiny (particularly for PVP) are often "maps" on which may modes can be played.  But I think it's a safe assumption that Gambit maps won't be used for non-Gambit activities!

I'll file a bug and put it in ye olde backlog.

**Comment by t3rr11** [comment]
Thanks as always vthornheart!

**Comment by t3rr11** [comment]
So i've noticed that a fix got around to this as some gambit maps are now displaying the gambit activity icon, thanks for that! But not all maps are showing icons. 
Instead i've resorted to using the PGCRs directorActivityHash in order to pull the icon from there as all maps have the same directorActivityHash but different referenceIds (obviously because referenceIds are the map data whereas the directorActivityHash is the activity data)

None the less i wanted to say thanks for getting on this @vthornheart-bng <3
