### ISSUE TITLE
[Q] I would like to find weekly xur item information and spider item information.

### ISSUE THREAD

**Issue by kdeun1** [Bungie-net/api#959]
I would like to find weekly xur item information and spider item information.

Using 'Destiny.Milestones.DestinyMilestone'
You can get weekly information,
xur, spider's information is missing.

How can I get it?

**Comment by xenodus** [comment]
GetVendors
Xur - 2190858386
Spider - 863940356

**Comment by kdeun1** [comment]
Thank you. I appreciate your answer. But, I have a additional question. I need your help.
https://github.com/Bungie-net/api/issues/971

**Comment by C-CG** [comment]
> 2190858386

How did you find these ID's, is there a list somewhere or possibly on a wiki page? Been trying to find them for a while...

**Comment by xenodus** [comment]
You can get them from the manifest. Alternatively, you can use the awesome  https://data.destinysets.com/.
