### ISSUE TITLE
[Suggestion] PCKE OAuth flow for native app & co.

### ISSUE THREAD

**Issue by louis-bompart** [Bungie-net/api#961]
I won't get in too much details, because the specs would really do a better job to explain the concepts and all around that, but, first the 'need':
 If I have a native application, I'm limited to uses a Public OAuth grant because I should not ship the `client_secret` w/ the `client_id`. This prevent me to have a sweet, sweet `refresh_token`.

That's, from my understanding, a common issue with native app w/ OAuth.

Introducing the [Authorization Code Flow with Proof Key for Code Exchange (PKCE)](https://auth0.com/docs/flows/concepts/auth-code-pkce). Also, the associated 
[RFC](https://tools.ietf.org/html/rfc7636)
It's not _too_ different from the current flow, but introduce the concept of code verifier and generator that the native client and the Authorization Endpoint will exchange.

This allow the Auth Endpoint to ensure that he's "talking" with the client and not a program that sniffed out the authorization code and is trying to impersonate the native app.

It'd allow to check the client identity when providing the tokens, even without server secret, allowing native app to have refresh tokens (yay!) without compromising on security.

**Comment by vthornheart-bng** [comment]
TFS 811423

**Comment by louis-bompart** [comment]
I'd have thought it'd be an enhancement not a bug, because it doesn't break anything in the Bungie OAuth specification, assuming the wiki of the repo is the source of truth. But well, it's yours to judge 😄
Just a fellow dev opinion 😉

**Comment by vthornheart-bng** [comment]
Oops... I may have actually put this bug in the wrong issue!  Hang on

**Comment by vthornheart-bng** [comment]
Ah yeah, somehow this ended up here and not in your other bug about the swagger spec errors.  TFS 811423 was meant for that one

**Comment by vthornheart-bng** [comment]
There we go - that's what I get for having ten issue tabs open.

I like the idea if we have time to work on it!  I'll file a real TFS item this time for it.
