### ISSUE TITLE
[Q] Is it possible to see if a user is online or offline?

### ISSUE THREAD

**Issue by TheTimebike** [Bungie-net/api#962]
Hi, I haven't had much luck in finding a way to see if someone is online through the Bungie API, and am wondering if it is possible at all. Thanks

**Comment by louis-bompart** [comment]
You can check the character activities to know when a character get online,
however the cache is quite persistent and won't clear if the player
disconnect.

**Comment by TheTimebike** [comment]
I see, thanks.

**Comment by Tetron-bng** [comment]
You can get the online status of clan members in the context of a clan request.  This value may lag by several minutes so may not be useful depending on your purpose.

https://bungie-net.github.io/multi/operation_get_GroupV2-GetGroup.html#operation_get_GroupV2-GetGroup

**Comment by floatingatoll** [comment]
Does this only work for members of your own clan?

**Comment by Tetron-bng** [comment]
It does only work for your own clan members. 
Here is the correct link: https://bungie-net.github.io/multi/operation_get_GroupV2-GetMembersOfGroup.html#operation_get_GroupV2-GetMembersOfGroup
