### ISSUE TITLE
Expected date for manifest including Moments of Triumph 2019?

### ISSUE THREAD

**Issue by Lalo-ATX** [Bungie-net/api#964]
Hi team, are you able to share the forecasted date for when the manifest will include the triumph/seal/etc for Moments of Triumph 2019?

**Comment by vthornheart-bng** [comment]
Good question!  We're currently experiencing issues in our production environment that are delaying the release of new game content.  We hope to have this resolved today - I will update here when it's live!

**Comment by jshaffstall-bng** [comment]
And they're live!
