### ISSUE TITLE
Nightfalls returning 5 hashes instead of 4

### ISSUE THREAD

**Issue by DeCoded-Void** [Bungie-net/api#967]
Recently the API has been returning the incorrect number of nightfalls, 

when the nightfalls were [manually swapped](https://twitter.com/Bungie/status/1143927969745756161) the API returned 6 nightfalls but the hashes were still pointing to the correct swapped nightfalls, just the incorrect number of them (2 of each unique nightfalls, when only 1 of them should be duplicated). 

This week, the API returns 4 different nightfall missions instead of 3 (The Arms Dealer, Will of Thousands, Warden of Nothing, and The Insight Terminus) with 1 being a duplicate (Arms dealer for guided games)

Via [Destiny2.GetPublicMilestones](https://bungie-net.github.io/multi/operation_get_Destiny2-GetPublicMilestones.html#operation_get_Destiny2-GetPublicMilestones) with a lot of the info stripped down, here is what it looks like in my end:
```json
{  
    "2171429505":{  
        "milestoneHash":2171429505,
        "activities":[  
            {  
                "activityHash":3145298904
            },
            {  
                "activityHash":272852450
            },
            {  
                "activityHash":3108813009
            },
            {  
                "activityHash":2258250028
            },
            {  
                "activityHash":927394522
            }
        ]
    }
}
```

**Comment by floatingatoll** [comment]
Was the nightfall changed between this Tuesday’s reset and Tuesday at the conclusion of the 2.5.1.1 maintenance, perhaps as part of the “background” maintenance and/or just to mitigate bad luck RNG?

Is there any JSON timestamp or other distinction between the “not live” Nightfall and the four “live” Nightfalls?

**Comment by DeCoded-Void** [comment]
start date is showing 7/9/2019 at 17:00 UTC and ending with 7/16/2019 at 17:00 UTC associated the nightfall hash which should be the correct weekly reset date and time. 

This probably happened as a result of the api being down/the 2.5.1.1 maintenance like you said.

**Comment by W1ndst0rm** [comment]
Here's the workaround I shifted to.

The Weekly Score Challenge (milestoneHash: 2853331463) is currently returning only the three current nightfalls without any duplicates. It might be a more consistent source than the Nightfall milestone.

**Comment by DeCoded-Void** [comment]
A good workaround for what I needed it for, the only thing left is how to tell if something is a legitimate guided games nightfall or not.

**Comment by DeCoded-Void** [comment]
I'm now getting 6 hashes from the api this week.

x2 "Tree of Probabilities" hashes (guided games and regular)
x1 "A Garden World" hash (regular)
x2 "The Corrupted" hashes (guided games and regular)
x1 "The Inverted Spire" hashes (guided games)

simplified manifest once again:
```json
{  
    "2171429505":{  
        "milestoneHash":2171429505,
        "activities":[  
            {  
                "activityHash":936308438
            },
            {  
                "activityHash":3718330161
            },
            {  
                "activityHash":3034843176
            },
            {  
                "activityHash":48090081
            },
            {  
                "activityHash":3326586101
            },
            {  
                "activityHash":3447375316
            }
        ]
    }
}
```
![thisweek](https://user-images.githubusercontent.com/11778439/61315636-33c20b80-a7cd-11e9-9515-eb133417eabe.png)

**Comment by vthornheart-bng** [comment]
Ooh, yeah that's no good.  Filing a bug shortly.

**Comment by vthornheart-bng** [comment]
TFS 811426

**Comment by michabbb** [comment]
pardon, when i do "GetPublicMilestones" i don´t see the hash "2171429505" any longer. has something changed here ? 🤔
