### ISSUE TITLE
Minor wrong naming for clan progressions

### ISSUE THREAD

**Issue by iBotPeaches** [Bungie-net/api#97]
```
1273404180
array (
  'displayUnitsName' => '',
  'description' => 'Tracks your success at leading Nightfall Guided Games.',
  'name' => 'Nightfall Success',
  'hasIcon' => false,
)
```

```
3759191272
array (
  'displayUnitsName' => '',
  'description' => 'Tracks your success at leading Trials of the Nine Guided Games.',
  'name' => 'Nightfall Success',
  'hasIcon' => false,
)
```

`3759191272` name field should probably be `Trials Success`

**Comment by vthornheart-bng** [comment]
Looks like a bug in the game content - I'll let the right people know.  Thanks!

**Comment by vthornheart-bng** [comment]
Annoyingly, they responded by removing the text entirely: apparently those progressions weren't intended to have text on the game side.  Unfortunately I've got nothing I can do for now but close the bug, since the fix was to remove this unapproved text.  Bummer. :(

**Comment by iBotPeaches** [comment]
![screen shot 2017-12-06 at 4 50 30 pm](https://user-images.githubusercontent.com/611784/33687250-98034fa6-daa5-11e7-8d1a-3c9c1d92e54a.png)

Appreciate digging into it @vthornheart-bng , guess I'll manually name these now.

**Comment by vthornheart-bng** [comment]
Yeah, sorry about that.  It was definitely not the answer that I wanted them to give me. :(
