### ISSUE TITLE
DestinyHistoricalStatsActivity - Docs are a little out of date (low priority)

### ISSUE THREAD

**Issue by ghost** [Bungie-net/api#970]
https://bungie-net.github.io/multi/schema_Destiny-HistoricalStats-DestinyHistoricalStatsActivity.html#schema_Destiny-HistoricalStats-DestinyHistoricalStatsActivity

The IsPrivate flag says there aren't private matches yet (DUN DUN DUNNNN) and the membershipType isn't in there yet.

**Comment by vthornheart-bng** [comment]
Ah yeah!  Good find on the ancient documentation comment!  Thanks!

**Comment by vthornheart-bng** [comment]
TFS 810017

**Comment by vthornheart-bng** [comment]
Just found this in the backlog.  It was the matter of a few seconds to change it, so I'm fixing it for next release
