### ISSUE TITLE
[Q] I don't know how to use 'GetVendors' 

### ISSUE THREAD

**Issue by kdeun1** [Bungie-net/api#971]
To find spider, xur's weekly rotation information, I received an answer. (ref1)

I tried to use it as documented, but no result (ref2)

What's wrong with the code here?
(Env: vue.js es6 es-lint axios)

```
let url = 'https://www.bungie.net/Platform';
url += '/Destiny2/4/'; // I'm blizzard user. (TigerBlizzard: 4)
url += 'Profile/4611686018485******/';
url += 'Character/2305843009410******/';
url += 'Vendors/863940356/'; // spider vendor hash
url += '?components=402';

      this.$http.get(url, {
        method: 'GET',
        headers: {
          'X-API-Key': 'a502c7f6b1304f4***************',
          Authorization: `Bearer ${localStorage.getItem('accessToken')}`,
        },
      })
        .then((result) => {
          const res = result.data.Response;
          console.log(`result: ${res}`);
        })
        .catch((e) => {
          console.log(`error: ${e}`);
        });

```

ref1) https://github.com/Bungie-net/api/issues/959
ref2) https://bungie-net.github.io/multi/operation_get_Destiny2-GetVendors.html#operation_get_Destiny2-GetVendors

**Comment by xgerhard** [comment]
Might want to share what's happening with this current code, is the console log reached, if so what's in it?

**Comment by vthornheart-bng** [comment]
Can you show an example of the response you're getting?

Can you try passing components 400, 401, and 402 and seeing if you get a different response?  I recall a bug a while back where you couldn't grab Vendor Item components unless you also grabbed the Vendor component, and I suspect that bug may have returned.

**Comment by kdeun1** [comment]
![image](https://user-images.githubusercontent.com/10824092/61429382-08702580-a961-11e9-92fc-e6a311bf78f2.png)

I did not check the check box. So I do not think the results came out.

I refer to the above issue. (https://github.com/Bungie-net/api/issues/975)

Thank you for your help.
