### ISSUE TITLE
Custom font replacement for [...] to [replacement] isn't being done in zh-*

### ISSUE THREAD

**Issue by floatingatoll** [Bungie-net/api#973]
Hi, the custom substitution you're doing API-side for e.g. #642 appears not to be applied to locale zh-cht, at least in json/zh-cht/guid-guid-guid-guid-aggregate.json.

**Comment by delphiactual** [comment]
zh-* are being replaced with unicode characters

https://github.com/delphiactual/d2-additional-info/commit/cfa18b9e806e0799ff71ea2bfe9912d75994d537

**Comment by floatingatoll** [comment]
So, originally, they _were_ Unicode characters, but then the localized text was inserted using the form '[Localized text]' replacing the Unicode characters in the feed (which are invalid — U+E138 is part of the Unicode "private use area").

The resulting U+E138 and similar in the zh-cht data vary from the [Replacement Strings] approach unusually — namely, they don't have the square brackets. Is that an intentional variance?

**Comment by delphiactual** [comment]
It's like this in both zh-cht and zh-chs and no other languages

**Comment by floatingatoll** [comment]
Updated title, thanks

**Comment by vthornheart-bng** [comment]
Ah, good stuff!  TFS: 811430

**Comment by delphiactual** [comment]
Also should point out there are some typos in the translated strings
English:
`[Rocker Launcher]`

and extra spaces for Japanese:
`[ヘッドショット ]`
German:
`[Helmtreffer ]`

**Comment by floatingatoll** [comment]
What’s the correct spelling for German?

**Comment by delphiactual** [comment]
extra space at the end... I'll edit to make more clear

**Comment by vthornheart-bng** [comment]
Ah, thanks, I'll see if we can take a look at those too!
