### ISSUE TITLE
InsufficientPriveleges While Getting Vendor Information [help wanted]

### ISSUE THREAD

**Issue by HeroicosHM** [Bungie-net/api#975]
Hello, I am having issues with the [GetVendor](https://bungie-net.github.io/multi/operation_get_Destiny2-GetVendor.html#operation_get_Destiny2-GetVendor) endpoint. Here is the Python code that I am using:

```python
headers = {
    'X-API-Key': 'my_key',
    'Authorization': 'Bearer my_token'
}

res = requests.get('https://www.bungie.net/Platform/Destiny2/4/Profile/4611686018483530949/Character/2305843009402927792/Vendors/863940356?components=400,401,402', headers = headers)
with open('./vendors.json', 'w') as file:
    file.write(json.dumps(json.loads(res.text), indent = 4))
```
and the result returned is
```json
{
    "ErrorCode": 12,
    "ThrottleSeconds": 0,
    "ErrorStatus": "InsufficientPrivileges",
    "Message": "You lack the privileges to read or write this data.",
    "MessageData": {}
}
```
I am sure that my OAuth token has permission to access this information because it requests access to every single permission type:
![image](https://user-images.githubusercontent.com/32232419/61178277-ef512880-a59e-11e9-9afb-356acb787b10.png)

Where am I going wrong here?

**Comment by vthornheart-bng** [comment]
Double check that the Bearer token you're passing is for the user who actually owns the Membership ID 4611686018483530949 and Character 2305843009402927792.  The Vendor Endpoint will throw InsufficientPrivileges if you are asking for someone other than yourself.

**Comment by HeroicosHM** [comment]
I have just double checked that the Bearer token is indeed the one bound to my own account, and also confirmed the membership id and character ids. I do have the correct hash for Xur right? Thank you for your response by the way, I appreciate the support.

**Comment by vthornheart-bng** [comment]
Oh, I have a suspicion.

Try adding a trailing slash to the endpoint, before the querystring parameter, like:

(rest of url).../2305843009402927792/Vendors/86394035**6/?**components=400,401,402

It's dumb, but our API requires trailing slashes at the end of every request, and will attempt to redirect you if it doesn't see it.  It's some nonsense that I'd like to fix but have never had the time to go back and change.  I have a suspicion that the library you're using for HTTP communication may be doing the redirect but doesn't pass the headers along with the redirect, and thus it fails.  I'm not 100% sure that's what's happening, but it's definitely worth a shot.

If that fails, see if you can hook up Fiddler or a similar man-in-the-middle HTTP traffic listener and see if you can capture the exact request as your library is making it, and the response you're getting back.  It could be very telling as to what's going on!

**Comment by floatingatoll** [comment]
> On Jul 13, 2019, at 18:49, Heroicos_HM <notifications@github.com> wrote:
> 
> res = requests.get('https://www.bungie.net/Platform/Destiny2/4/Profile/4611686018483530949/Character/2305843009402927792/Vendors/863940356?components=400,401,402 <https://www.bungie.net/Platform/Destiny2/4/Profile/4611686018483530949/Character/2305843009402927792/Vendors/863940356?components=400,401,402>', headers = headers)
Theoretically, if I read the docs right, you can (and, to avoid these problems, you should) disable redirects on your requests with:

`, headers=headers, allow_redirects=False)`

This Stackoverflow has more, and includes tips on inspecting the response to see if you got a redirect back, etc.

https://stackoverflow.com/a/14678220

**Comment by HeroicosHM** [comment]
I am not sure how redirects have anything to do with this, but adding the extra slash in the url has done the trick for me! Thank you for your help!

**Comment by floatingatoll** [comment]
To summarize:

All non-trailing-slash API URLs - /1234 instead of /1234/ for example - have a bug that will break your API code.

Make sure every request URL for an API endpoint ends with a / directly prior to the ?a=b section, or with a / at the end of the URL if no ? section.

**Comment by HeroicosHM** [comment]
Got it, thanks for the explanation.
