### ISSUE TITLE
New Vendor: Visage of Calus has missing properties in its vendor definition

### ISSUE THREAD

**Issue by serkanbal** [Bungie-net/api#977]
The new vendor: Visage of Calus (hash: 1944634565) has missing properties such as `largeIcon`, `smallTransparentIcon`, `largeTransparentIcon`, `mapIcon` in its `displayProperties` property in the manifest definition.

For consistency's sake; I think it would be great if we could have these properties even if we have empty strings or missing icon urls as values. Just a thought. :pray:

**Comment by vthornheart-bng** [comment]
Oh, good to know - I'll have to look into that.  We've had this problem with some vendors before, and it may be that the game's no longer providing them for new vendors (that was what was happening previously).  If that's happening again, I'll hit them up to see if they can resume populating it.

**Comment by vthornheart-bng** [comment]
TFS 811432
