### ISSUE TITLE
The Vendor You Requested Was Not Found - Xûr [Question]

### ISSUE THREAD

**Issue by Aryathel** [Bungie-net/api#979]
When I run a GetVendors request for Xur, using hash `2190858386`, all I get in response is this:
```json
{
    "ErrorCode": 1627,
    "ThrottleSeconds": 0,
    "ErrorStatus": "DestinyVendorNotFound",
    "Message": "The Vendor you requested was not found.",
    "MessageData": {}
}
```
Is this due to the fact that Xur is currently not available in game?

**Comment by vthornheart-bng** [comment]
Oh, yes - if the Vendor isn't actually in the world, they won't be returned and you'll get DestinyVendorNotFound.

It might be worthwhile for us to change this error code to something like "DestinyVendorNotInWorld" or something to distinguish it from situations where you passed the hash of a vendor that truly doesn't exist/is invalid, but I fear that people may have already written dependencies into their code that check for this specific error message.  If we make a change to this, we'll have to give people some lead time to change it around: but it'd be nice to distinguish between the two states.

**Comment by vthornheart-bng** [comment]
TFS 811549
