### ISSUE TITLE
CurrentActivity gets "stuck" for some players

### ISSUE THREAD

**Issue by dcaslin** [Bungie-net/api#981]
This is intermittent so it may be fixed by the time this issue is looked at, but the user (kpax on XBL) reports it has happened a few times in the last few weeks. Consider this URL: 

https://www.bungie.net/Platform/Destiny2/1/Profile/4611686018431601143/?components=CharacterActivities

This returns the following for current activity info: 

```
 "2305843009261738332": {
                    "dateActivityStarted": "2019-07-18T02:35:11Z",                    
                    "currentActivityHash": 2086906937,
                    "currentActivityModeHash": 1418469392,
                    "currentActivityModeType": 75,
                    "currentActivityModeHashes": [
                        1418469392,
                        2449176354
                    ],
                    "currentActivityModeTypes": [
                        75,
                        64
                    ],
                    "currentPlaylistActivityHash": 1183187383,
                    "lastCompletedStoryHash": 0
                },
```

The user assures me that, despite the reports here, they haven't actually been playing a 17 hour long Gambit Prime match =)

Compare that to my account when not playing, which shows zeroes. 

```
 "data": {
                "2305843009264730899": {
                    "dateActivityStarted": "2019-07-13T12:49:35Z",
                    "currentActivityHash": 0,
                    "currentActivityModeHash": 0,
                    "lastCompletedStoryHash": 0
                },
```

I don't think this is an urgent issue given the feature and the intermittent nature of it. Thanks!

**Comment by louis-bompart** [comment]
I encountered the issue too with a bunch of client, I thinks it's related with how the API is handling its caches:
https://github.com/Bungie-net/api/wiki/FAQ:-Cache-times,-in-game-interactions,-and-busting-the-cache

**Comment by dcaslin** [comment]
I haven't seen this cache effect last that long, but you might be right. 

I've been able to work around the issue rather simply by applying the following reasonable logic: 

- If more than one character reports as currently playing, only trust the one with the most recent "last played" date. 

- For my user with the problem, this leaves them reporting as in orbit rather than in the middle of an absurdly long Gambit prime match

**Comment by vthornheart-bng** [comment]
Yes, unfortunately this has to do with the fact that Bungie.net can only obtain the last information that our game servers saw about a user.  I believe that, under certain conditions (if you can ask them, ask them how they left that activity: did they get disconnected for example, or quit while mid activity?) the state can end up essentially "frozen" in what we saw last before they logged off.

The caching even in the worst case shouldn't last more than a minute or so, which leads me to believe you're probably hitting the scenario above.  Definitely go with your heuristic for now, and I'll see if I can bubble this up.  There might not be anything that can be done with the way the game side is architected, but we can ask!

**Comment by dcaslin** [comment]
Good deal thanks!

Glad to have that answer, honestly that's all I was looking for (since I found a workaround 20 mins after opening this), so feel free to close. I'd hate you all to waste time on this in favor or other more important stuff.

**Comment by vthornheart-bng** [comment]
Good deal, and no worries - I'll close it for now, but I am also going to push it up the chain just in case it's feasible to fix in the future!

**Comment by vthornheart-bng** [comment]
I filed it under TFS 812957 - unsure if they'll be able to address it, but at least now they'll know it causes trouble for folks trying to use the data outside of the game itself.
