### ISSUE TITLE
no floor

### ISSUE THREAD

**Issue by Nasset** [Bungie-net/api#982]
please, fix missing floor:
![tiger_release_final_20190719_201304](https://user-images.githubusercontent.com/53094527/61553656-916f8580-aa63-11e9-8a13-ed81f395c475.png)
![tiger_release_final_20190719_201312](https://user-images.githubusercontent.com/53094527/61553658-92081c00-aa63-11e9-9b9c-e50cf6bb3d0a.png)
![tiger_release_final_20190719_201325](https://user-images.githubusercontent.com/53094527/61553659-92081c00-aa63-11e9-91b3-427033d712c2.png)
![tiger_release_final_20190719_201527](https://user-images.githubusercontent.com/53094527/61553660-92081c00-aa63-11e9-8047-6d416e6cacd4.png)
![tiger_release_final_20190719_200016](https://user-images.githubusercontent.com/53094527/61553661-92081c00-aa63-11e9-828d-ef284efcf5a5.png)
![tiger_release_final_20190719_201205](https://user-images.githubusercontent.com/53094527/61553662-92a0b280-aa63-11e9-92cd-3f149fbb35ca.png)

**Comment by floatingatoll** [comment]
This is the API GitHub, and so unfortunately the API team cannot help you with fixing in-game issues that aren't directly related to the API itself. You're pointing out in-game model issues with a certain zone, with screenshots, which is a terrific problem report - but that is something you'll have to post to the Bungie Help forum to get attention to it, as they don't watch this API-only queue.

https://www.bungie.net/en/Forums/Topics/?tg=Help
