### ISSUE TITLE
Items from some sources show only the selected plug instead of all reusables

### ISSUE THREAD

**Issue by archived-2f4dd0** [Bungie-net/api#983]
in Y2, some instanced armors come back from the API showing only the selected perks.
these are from "interesting" sources, such as
• direct purchases from Tess (fixed rolls, not from bright engrams)
• S7 Iron Banner quest (acceptance page, fixed rolls, not from saladin engrams)
• some event armors (no details here)

the API returns these instances with the plug representing the selected perk, but no `reusablePlugHashes` or `reusablePlugs` keys at all.
this applies to perks, not the stat toggle as far as i can tell.
the perks are still togglable in the game, and this changes the API response.

example time:

**me:**
4611686018475612431
**some affected items:**
6917529095057618829
6917529095358838085
6917529095223730214
6917529095180116381
6917529069080348797
6917529095163652309
6917529095284568069

sorry there's not a huge variety, mostly IB and s4.
season 8 is coming and we gotta dismantle all that eververse armor :_)_

![image](https://user-images.githubusercontent.com/31990469/61576689-e88c4f00-aa91-11e9-87a9-18b5e1bcc181.png)
![image](https://user-images.githubusercontent.com/31990469/61576691-f2ae4d80-aa91-11e9-8b0b-e05f23e3e0b4.png)
![image](https://user-images.githubusercontent.com/31990469/61583946-6c772300-aaf4-11e9-9bfb-b992954ecdb5.png)

(6917529095187372247)

**Comment by vthornheart-bng** [comment]
Hmm, interesting!  Are these items "wrapped" by any chance?  (i.e. refundable items?)

**Comment by sundevour** [comment]
none of mine anyway. none from packages or of silver purchases. just bright dust & saladin right now

**Comment by vthornheart-bng** [comment]
Interesting - good to know, thank you!

TFS 816022

**Comment by Lalo-ATX** [comment]
I just want to note that I'm seeing this as well. Iron Truage gear.

**Comment by vthornheart-bng** [comment]
Is this still occurring as of the latest reusablePlugs changes?

**Comment by sundevour** [comment]
yep!

**Comment by sundevour** [comment]
and on all y2 class items now. or at least very similar.

**Comment by vthornheart-bng** [comment]
Mmm, good to know. thank you!

**Comment by sundevour** [comment]
the new season's ritual weapons are also affected by this:
edgewise, randy's throwing knife, and exit strategy

only their selected perks are shown

**Comment by sundevour** [comment]
and **some** y2 exotics are now showing only their selected perks
