### ISSUE TITLE
OAuth without client interaction

### ISSUE THREAD

**Issue by dyl10s** [Bungie-net/api#984]
I was wondering if there was any way to authenticate without having interaction. I already have my username and password and I am the only one using my application and do not want to have to login every time. It would be great if I could set it in the background!

**Comment by mattybeard** [comment]
Can’t you just store refresh token after first login? You’ll be good for a long time then. Thats what I run on my private stuff.

**Comment by dyl10s** [comment]
How long is the refresh token good for?

**Comment by louis-bompart** [comment]
90 days if I remember correctly. And correct me if I'm wrong but when you
refresh it, you get a new one that is valid for 90 new days (and you can do
it only with rest call, no user interaction required). So technically,
except if you don't start your app for a quarter of a year, you're set
forever.

**Comment by Tetron-bng** [comment]
The authorization lasts for one year as long as you grab a new refresh token before the old one expires (90 days).  The OAuth token response includes the parameter refresh_expires_in which is the number of seconds the refresh token is valid.
