### ISSUE TITLE
Valor progression seasonResets property is on Glory item

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#986]
![image](https://user-images.githubusercontent.com/156681/61626129-c415ba00-acbf-11e9-9da1-642bc9c9fae2.png)

I was racking my brain as I thought @vthornheart-bng added these arrays. Gave up checking the two valor keys and filtered characterProgressions.progressions by seaspmsResets and found Glory and Infamy 😃

**Comment by sundevour** [comment]
+1 to this,
`2679551909` "Glory Rank" DestinyProgressionDefinition
is returning my valor resets

maybe if i had any PVP skill `3882308435` Valor Rank would return my glory resets? :_)_

**Comment by vthornheart-bng** [comment]
Ooh yeah, I see what you all are talking about in there.  Let me see what can be done

**Comment by vthornheart-bng** [comment]
Okay, I'm going to move the Valor Resets to the Valor progression starting with the deployment after this tuesday's (ideally next week, though it may get pushed out to the week after that - I will try to keep folks posted here)

**Comment by justrealmilk** [comment]
Fixed!
