### ISSUE TITLE
OAuth help

### ISSUE THREAD

**Issue by ZxFrankxZ** [Bungie-net/api#987]
I need help about the Oauth request with node.js but i don't know how do that, someone can help me please?
I want do this request
https://www.bungie.net/Platform/GroupV2/3775090/Members/ApproveAll/

**Comment by ckhicks** [comment]
Can you post the code you're using at present? There's also a lot of really great minds ready and able to help in the unofficial API Discord: https://discord.gg/E5uB4BW
