### ISSUE TITLE
data requested via API

### ISSUE THREAD

**Issue by jakibbe** [Bungie-net/api#988]
I was wondering if any of the following can be added to the public API, especially in a PGCR, for uses like Destiny Clan Warfare event scoring:

- pvp orbs generated
- control zones captured (esp. Iron Banner)
- raid boss damage
- equipped armor/shell/ship/emblem (as part of PGCR to allow for event modifier based on equipped gear)

There are around 1400 clans that participate in Destiny Clan Warfare events every week. We would like to be able to apply scoring modifiers to give bonus for orbs, zones capped, and gear, for a bit of context. Currently we use weapon types, precision, grenade kills, and various medals, but it would be nice to have more options and greater flexibility.

I mentioned this to Edgar Verona via Reddit, and he recommended that I submit an issue here.

Thanks for considering!

**Comment by TorKallon** [comment]
+1

**Comment by vthornheart-bng** [comment]
I like those suggestions!

Unfortunately, the folks who work on stats are pretty swamped (they do work across a wide spectrum of the server infrastructure), and we've historically had to limit the amount of data we save in PGCRs, so I can't promise that we can actually make any of these happen.  But I will bring it up for discussion!

**Comment by SolidKalium** [comment]
I have some clan members who want to be able to see their damage numbers after they defeat the boss. If boss damage is added, it would be great if it could be broken down by damage phase.

I definitely understand if that's too much data, but we can always hope it's possible. Thanks!

**Comment by justrealmilk** [comment]
More mode-specific stats in general! 📢💥

**Comment by MadMikeyB** [comment]
I see an email has been sent out with damage numbers for the King's Fall raid as a part of Bungie's #RaidMemories marketing campaign, this leads me to believe they're stored somewhere and your Data Science team had to do some form of query to grab them for your marketing team to include in the email.  

Do you guys think the ability to get those numbers into an API endpoint, maybe separate from PGCR's but linked by PGCR ID as an optional thing we can query (so as not to slow down / overload the PGCR endpoint) will ever happen? 

I like to imagine the flow would be something akin to grabbing the PGCR, waiting for that data, and after that request is finished, run another request with the PGCR ID and maybe a boss/encounter name/ID to get the damage numbers for the encounter in question (if completed). The numbers returned could only be for successful encounter completions, so partial data is not returned and making the response bigger.

**Comment by cowgod** [comment]
I was about to make a similar post. Given that the numbers are clearly available, I'd love to have the data accessible via the API in some way. I recognize they may be currently excluded because the DB queries are too slow, or something like that, but a solution on a separate endpoint that could only be called when needed would be wonderful.

**Comment by Cr3aHal0** [comment]
Bump, please add damages to API <3
