### ISSUE TITLE
Players' profile response doesn't include City Dance emote despite having obtained it

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#989]
So I've been adding emotes to Braytech's Collections view, based off of the plugSet for emotes `3224618006`.

Some items aren't returned, including the 6 class-specific waves and sits. These are fine to exclude though - it's understandable and consistent.

All this said, there is one emote that feels like it's just been left off of the list: City Dance `3134905452` - a legendary season 1 emote.

I've checked with a few users, including myself, who have the emote in-game but it doesn't appear in their profile response data.

![image](https://user-images.githubusercontent.com/156681/61995236-e432e800-b0c8-11e9-8d5f-697985757cc6.png)

This isn't something worth spending your time on, but thank you for reading 🤗

**Comment by justrealmilk** [comment]
Also receiving reports that the 3 Eververse Arc week emotes from season 6, `3225062820, 3325808341, 429106713`, don't make it into the profile response data either.

**Comment by vthornheart-bng** [comment]
Huh, interesting!  I'll have to investigate.  Out of curiosity, I assume in game it actually comes up as available?

**Comment by justrealmilk** [comment]
You assume correctly! I tried equipping it and visiting various destinations to see if it would wake up something sleepy but alas...

**Comment by vthornheart-bng** [comment]
Hmm, very interesting!  I think this is one of the rare ones that I can check with my own production account, I think I actually have this emote.  I'll give it a look soon!

**Comment by vthornheart-bng** [comment]
TFS 815977
