### ISSUE TITLE
Innocuous looking weapons still 'classified' (not sure if bug or feature)

### ISSUE THREAD

**Issue by Lalo-ATX** [Bungie-net/api#99]
A number of innocuous looking legendary weapons are still 'classified'. These were rewarded through typical activities, e.g. rank-up engrams, engram drops from killed enemies in the world. There's nothing obviously special about them. They don't appear to be from FWC, DO, or NM.

In my inventory alone, 1 each of

* grenade launcher
* sniper rifle
* rocket launcher
* hand cannon
* sidearm
* submachine gun
* pulse rifle

Not sure if this is a bug or a feature, but it impacts player ability to manage inventory with apps. I can provide further details if its helpful.

**Comment by floatingatoll** [comment]
The item IDs will help ensure that the right things are fixed, but the declassification process may still take Bungie up to "several weeks" to complete, once any given item is found in the wild in the game.

**Comment by Lalo-ATX** [comment]
@floatingatoll I just can't fathom why these would be classified in the first place, hence why I think it *might* be a bug. However, you're right, it could also be on purpose as well. I have no way of distinguishing so I thought I'd say something.

IDs:

- [ ] 339343290
- [ ] 566976652
- [ ] 1533499362
- [ ] 3860697508
- [ ] 3748713778
- [ ] 3666954563
- [ ] 896923850

**Comment by vthornheart-bng** [comment]
Sweet, thanks for the IDs - I'll ask around about these.

**Comment by floatingatoll** [comment]
I can come up with some interesting ideas, but in the end, it’s either intentional or accidental, and they’ll figure it out :)

**Comment by ArkahnX** [comment]
Here is a list of all of the items I have encountered in my inventory currently that are classified, if this list helps https://gist.github.com/ArkahnX/bfc0c4fa7f47cf7dfde7eff6d8925226

**Comment by vthornheart-bng** [comment]
Sweet, thanks to your guys' information I'll be declassifying these when the Raid gear declassifies tomorrow!  Thanks for all the info!

**Comment by vthornheart-bng** [comment]
(to clarify, not everything in ArkahnX's list will be un-redacted, but many things will be.  I'm talking with people about the others.  Thanks for that list!)

**Comment by apokalyptik** [comment]
Sentencer IV (scout) is currently classified as well.
