### ISSUE TITLE
kinetic damage transparentIconPath typo

### ISSUE THREAD

**Issue by sundevour** [Bungie-net/api#990]
`DestinyDamageTypeDefinition > 3373582085 > transparentIconPath`

^ this entry is missing the leading slash that all other paths have

**Comment by vthornheart-bng** [comment]
Ooh, good find, thank you!  I think I can fix that up in short order.

**Comment by vthornheart-bng** [comment]
Easiest fix of the day!  This'll be fixed next bnet update.
