### ISSUE TITLE
Decline Clan Join Request

### ISSUE THREAD

**Issue by dyl10s** [Bungie-net/api#993]
I am not seeing an API call for declining a join request in the documentation. Am I missing something?

**Comment by vthornheart-bng** [comment]
Does this one work for you?  You pass in a list of membership IDs for memberships whose requests you want to decline.

https://bungie-net.github.io/multi/operation_post_GroupV2-DenyPendingForList.html#operation_post_GroupV2-DenyPendingForList

**Comment by dyl10s** [comment]
Yes.. I don't know why I didn't think I could use that and just send 1 member in the list. Thanks for the help!

**Comment by vthornheart-bng** [comment]
No prob, glad to help!
