### ISSUE TITLE
How to view Clan Log

### ISSUE THREAD

**Issue by dyl10s** [Bungie-net/api#994]
Is there any way to view the Clan Log?

![image](https://user-images.githubusercontent.com/12243691/62087738-d009fa80-b230-11e9-9b8e-3130ee3953f8.png)

I see that the destiny website is using the endpoint 
https://www.bungie.net/Platform/Message/GetConversationThreadV3/45465596/1/?lc=en&fmt=true&lcin=true&format=0&before=349672154&after=0

I do not see any documentation on this however.

**Comment by vthornheart-bng** [comment]
Ah yes - the clan chat is actually part of our "Messaging" system, which unfortunately for the time being is not officially supported for public calls.  You can make calls to it, but we don't support it officially for public use at this time.

However, unofficially, your group data should include a conversationId - that's the 45465596 in the request above.   The /1/ is the page number (1-based... it's a long story and part of why this isn't publicly supported!) of activity you want to get.  You don't get to choose how many you get back, so you'll have to handle however many the server gives you (which is more or less a fixed quantity), and the pages go from most recent to least.

lc= is the locale, which doesn't actually matter here as this data is stored pre-localized for your clan's locale settings

fmt= should always be passed as true, it's for a feature that has been deprecated.

lcin= also does not apply, it has to do with locales as well.

format= should always pass 0, it's another deprecated feature.

before= if you pass this field, pass a message ID with it.  We will not return any messages older than that message.  You can omit this field or pass 0 to ignore it.

after= if you pass this field, pass a message ID with it.  We will not return any messages newer than that message.  You can omit this field or pass 0 to ignore it.

I can't provide any more support than that, hopefully it's enough to get you going!

Note that with all unsupported APIs, we reserve the right to change their schema, deprecate features, break it in backwards incompatible ways etc... without notice.

**Comment by dyl10s** [comment]
Awesome, thanks so much for the "unofficial" documentation!
