### ISSUE TITLE
Result of GetVendor for Tess Everis not in sync with actual in game sale items

### ISSUE THREAD

**Issue by xenodus** [Bungie-net/api#997]
Similar issue as #963 

Getting the following items from Tess after this week's patch:

![image](https://user-images.githubusercontent.com/9331270/62345099-6ab15480-b523-11e9-898b-13156f3d7eb4.png)

**Comment by floatingatoll** [comment]
That list reminds me of “an entire season worth of Tess in a single list”, in case that offers a speedy diagnosis.

**Comment by vthornheart-bng** [comment]
Thanks for the info!  I will need to investigate further.

**Comment by vthornheart-bng** [comment]
TFS 818022

**Comment by vthornheart-bng** [comment]
Finally had a chance to take a look at this.  Yep, our content is mismatching the game's, resulting in this mismatch.  That is a bummer.

I'm hitting up some folks to see what we can do about that - I anticipate that, in the worst case, this error may persist until 8/13.  But hopefully we can patch content earlier than that.

**Comment by xenodus** [comment]
Update after this week's patch: Partially fixed.

The items highlighted in green appears in the call but not the items in red.

![image](https://user-images.githubusercontent.com/9331270/62986026-6adb1980-be6c-11e9-8edd-50501aa119ed.png)

![image](https://user-images.githubusercontent.com/9331270/62986031-6d3d7380-be6c-11e9-9649-d46a444caef0.png)

**Comment by vthornheart-bng** [comment]
Hmm, very interesting - thank you for this info!  I'll loop back around with folks and investigate this further.

**Comment by mistahj67** [comment]
For what it's worth Charlemagne properly displays all of those, even in red.

!Tess from discord

I believe the item category is: 21

**Comment by xenodus** [comment]
Found out why! 

Previously, when item was offered for dust, it wouldn't be offered for silver hence I had unique constraint item hash.

The api is now returning similar items twice for both silver and dust cost. Thanks for the help!

**Comment by vthornheart-bng** [comment]
Ahh, sweet!  Glad it's all working out!

We'll be keeping an eye on our content to try and minimize this kind of issue in the future.
